//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Meazure.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_PREF_CALIBRATION            102
#define IDD_PREF_CUSTOM                 106
#define ID_MEA_CROSSHAIR_TIMER          115
#define IDC_MEA_RUNSTATE                119
#define ID_HELP_SCREEN_INFO             122
#define ID_HELP_TOOL_INFO               123
#define ID_MEA_COPYDATA                 124
#define ID_MEA_DATAWIN_TIMER            125
#define ID_MEA_MASTER_RESET             126
#define IDR_MAINFRAME                   128
#define IDR_MEAZURTYPE                  129
#define IDS_MEA_ASPECT                  129
#define IDD_PREF_RULERS                 135
#define IDD_PREF_TOOLS                  136
#define IDB_MEA_NORMPAUSE               138
#define IDB_MEA_SELPAUSE                139
#define IDB_MEA_FOCUSPAUSE              140
#define IDD_GRID_SPACING                141
#define IDD_PREF_ADVANCED               142
#define IDB_LOGO                        145
#define IDC_HAND_CUR                    146
#define IDD_RES_WARNING                 156
#define IDD_DIM_WARNING                 159
#define IDB_MEA_WARNING                 160
#define IDI_LOG_ICON                    162
#define IDD_POSITION_MGR                163
#define IDD_POSITION_SAVE               164
#define IDD_PREF_PRECISION              165
#define IDC_ORIENT_TOP                  1004
#define IDC_ORIENT_BOTTOM               1005
#define IDC_ORIENT_LEFT                 1006
#define IDC_ORIENT_RIGHT                1007
#define IDC_AUTO_RES                    1026
#define IDC_MANUAL_RES                  1027
#define IDC_CAL_RY_FIELD                1029
#define IDC_CAL_RX_FIELD                1030
#define IDC_CAL_RES_LABEL               1035
#define IDC_CAL_RY_LABEL                1036
#define IDC_CAL_RX_LABEL                1037
#define IDC_RULER_BACK_BTN              1039
#define IDC_RULER_BORDER_BTN            1040
#define IDC_RULER_SAMPLE                1041
#define IDC_CAL_H_FIELD                 1045
#define IDC_CAL_W_FIELD                 1047
#define IDC_RULER_BACK_DEF              1048
#define IDC_RULER_BORDER_DEF            1049
#define IDC_CAL_DIM_LABEL               1049
#define IDC_TOOLS_CHBACK_DEF            1050
#define IDC_CAL_H_LABEL                 1050
#define IDC_TOOLS_CHBORDER_DEF          1051
#define IDC_CAL_W_LABEL                 1051
#define IDC_TOOLS_CHHILITE_DEF          1052
#define IDC_TOOLS_CHBACK_BTN            1053
#define IDC_TOOLS_CHBORDER_BTN          1054
#define IDC_TOOLS_CHHILITE_BTN          1055
#define IDC_TOOLS_LINE_DEF              1056
#define IDC_TOOLS_LINE_BTN              1057
#define IDC_LINE_SAMPLE                 1058
#define IDC_CHNORM_SAMPLE               1059
#define IDC_CHHI_SAMPLE                 1060
#define IDC_GRID_HSPACE_SPIN            1062
#define IDC_GRID_VSPACE_SPIN            1064
#define IDC_GRID_HSPACE                 1065
#define IDC_GRID_VSPACE                 1066
#define IDC_GRID_LINK                   1069
#define IDC_PROFILE_PATHNAME            1074
#define IDC_PROFILE_BTN                 1075
#define IDC_CLEAR_PROFILE               1076
#define IDC_HOME_URL                    1077
#define IDC_FEEDBACK_EMAIL              1078
#define IDC_PROGRAM_TITLE               1079
#define IDC_MEA_DATA_WIN                1080
#define IDC_PROGRAM_VERSION             1080
#define IDC_CAL_RX_SLIDER               1081
#define IDC_CAL_RY_SLIDER               1082
#define IDC_CAL_INSTR                   1084
#define IDC_CAL_INSTR2                  1085
#define IDC_CAL_RX_SPIN                 1086
#define IDC_CAL_RY_SPIN                 1087
#define IDC_MEA_WARNING                 1091
#define IDC_MEA_CAL_BTN                 1092
#define IDC_PROGRAM_BUILD               1093
#define IDC_CAL_INCHES                  1094
#define IDC_CAL_CM                      1095
#define IDC_MEA_ADD_POSITION            1097
#define IDC_MEA_REPLACE_POSITION        1098
#define IDC_MEA_DELETE_POSITION         1099
#define IDC_MEA_DELETE_ALL_POSITIONS    1100
#define IDC_MEA_LOAD_POSITIONS          1101
#define IDC_MEA_SAVE_POSITIONS          1102
#define IDC_MEA_SAVE_POSITIONS_AS       1103
#define IDC_MEA_POSITION_DATE           1106
#define IDC_MEA_POSITION_DESC           1108
#define IDC_LOG_TITLE                   1108
#define IDC_MEA_POSITION_NUM            1109
#define IDC_LOG_DESC                    1109
#define IDC_MEA_POSITION_NUM_LBL        1110
#define IDC_MEA_POSITION_DATE_LBL       1111
#define IDC_MEA_POSITION_DESC_LBL       1112
#define IDC_MEA_POSITION_SCROLLBAR      1113
#define IDC_CALRES_TITLE                1114
#define IDC_PREC_PX                     1116
#define IDC_PREC_TP                     1117
#define IDC_PREC_PT                     1118
#define IDC_PREC_PC                     1119
#define IDC_PREC_IN                     1120
#define IDC_PREC_CM                     1121
#define IDC_PREC_MM                     1122
#define IDC_PREC_CUSTOM                 1123
#define IDC_PREC_DEG                    1124
#define IDC_PREC_RAD                    1125
#define IDC_PREC_X_FIELD                1126
#define IDC_PREC_X_SPIN                 1127
#define IDC_PREC_RX_FIELD               1128
#define IDC_PREC_RX_SPIN                1129
#define IDC_PREC_X_LABEL                1130
#define IDC_PREC_Y_LABEL                1131
#define IDC_PREC_D_LABEL                1132
#define IDC_PREC_W_LABEL                1133
#define IDC_PREC_H_LABEL                1134
#define IDC_PREC_A_LABEL                1135
#define IDC_PREC_RX_LABEL               1136
#define IDC_PREC_RY_LABEL               1137
#define IDC_PREC_W_FIELD                1138
#define IDC_PREC_W_SPIN                 1139
#define IDC_PREC_Y_FIELD                1140
#define IDC_PREC_Y_SPIN                 1141
#define IDC_PREC_RY_FIELD               1142
#define IDC_PREC_RY_SPIN                1143
#define IDC_PREC_H_FIELD                1144
#define IDC_PREC_H_SPIN                 1145
#define IDC_PREC_D_FIELD                1146
#define IDC_PREC_D_SPIN                 1147
#define IDC_PREC_AR_FIELD               1148
#define IDC_PREC_AR_SPIN                1149
#define IDC_PREC_A_FIELD                1150
#define IDC_PREC_A_SPIN                 1151
#define IDC_PREC_AR_LABEL               1152
#define IDC_PREC_DEF                    1153
#define IDC_CUST_PX                     1154
#define IDC_CUST_IN                     1155
#define IDC_CUST_CM                     1156
#define IDC_CUST_PX_FIELD               1157
#define IDC_CUST_IN_FIELD               1158
#define IDC_CUST_CM_FIELD               1159
#define IDC_CUST_PREC                   1160
#define IDC_CUST_NAME_FIELD             1161
#define IDC_CUST_ABBREV_FIELD           1162
#define IDC_CUST_CLEAR                  1163
#define IDC_CUST_PX_ABBREV              1164
#define IDC_CUST_IN_ABBREV              1165
#define IDC_CUST_CM_ABBREV              1166
#define IDC_CUST_PX_LABEL               1167
#define IDC_CUST_IN_LABEL               1168
#define IDC_CUST_CM_LABEL               1169
#define IDC_CUST_BASIS_LABEL            1170
#define IDC_DATAWIN_SAMPLE              1171
#define IDC_CH_OPACITY                  1172
#define IDC_RULER_OPACITY               1173
#define IDC_CH_OPACITY_LABEL1           1174
#define IDC_CH_OPACITY_LABEL2           1175
#define IDC_RULER_OPACITY_LABEL1        1176
#define IDC_RULER_OPACITY_LABEL2        1177
#define IDC_MEA_ORIGIN_MARKER           1178
#define IDC_MASTER_RESET                1179
#define ID_MEA_CURSOR                   32771
#define ID_MEA_POINT                    32772
#define ID_MEA_LINE                     32773
#define ID_MEA_RECT                     32774
#define ID_MEA_CIRCLE                   32775
#define ID_MEA_ANGLE                    32776
#define ID_MEA_WINDOW                   32777
#define ID_MEA_RULER                    32778
#define ID_MEA_UNITS_PIXELS             32779
#define ID_MEA_UNITS_TWIPS              32780
#define ID_MEA_UNITS_INCHES             32781
#define ID_MEA_UNITS_CM                 32782
#define ID_MEA_UNITS_MM                 32783
#define ID_MEA_UNITS_POINTS             32784
#define ID_MEA_UNITS_PICAS              32785
#define ID_MEA_ONTOP                    32786
#define ID_MEA_INVERTY                  32787
#define ID_MEA_ORIGIN                   32788
#define ID_MEA_RESET_ORIGIN             32789
#define ID_MEA_PREFERENCES              32790
#define ID_MEA_MAGNIFIER                32791
#define ID_MEA_MAGGRID                  32792
#define ID_MEA_SCREEN_INFO              32794
#define ID_MEA_RUNSTATE                 32797
#define ID_MEA_GRID                     32798
#define ID_MEA_SCREEN_GRID              32799
#define ID_MEA_SCREEN_GRID_SPACING      32800
#define ID_MEA_SAVE_PROFILE             32801
#define ID_MEA_LOAD_PROFILE             32802
#define ID_HELP_SEARCH                  32804
#define ID_MEA_COPY_RGN                 32805
#define ID_MEA_TOOL_INFO                32806
#define ID_MEA_COLLAPSE                 32809
#define ID_VIEW_STATUSBAR               32810
#define ID_MEA_FIND                     32812
#define ID_MEA_DELETE_POSITIONS         32817
#define ID_MEA_LOAD_POSITIONS           32818
#define ID_MEA_SAVE_POSITIONS           32819
#define ID_MEA_RECORD                   32820
#define ID_MEA_SAVE_POSITIONS_AS        32821
#define ID_MEA_MANAGE_POSITIONS         32822
#define ID_MEA_RGBFMT                   32826
#define ID_MEA_RGBHEXFMT                32827
#define ID_MEA_CMYFMT                   32828
#define ID_MEA_CMYKFMT                  32829
#define ID_MEA_HSLFMT                   32830
#define ID_MEA_YCBCRFMT                 32831
#define ID_MEA_YIQFMT                   32832
#define ID_MEA_ZOOM_IN                  32833
#define ID_MEA_ZOOM_OUT                 32834
#define ID_MEA_DEGREES                  32835
#define ID_MEA_RADIANS                  32836
#define ID_MEA_HIDE_CROSSHAIR           32842
#define ID_MEA_UNITS_SET_CUSTOM         32843
#define ID_MEA_UNITS_CUSTOM             32844
#define ID_MEA_UNITS_DEF_CUSTOM         32845
#define ID_MEA_POS1                     32846
#define ID_MEA_POS2                     32847
#define ID_MEA_POS3                     32848
#define IDS_MEA_PIXELS                  61204
#define IDS_MEA_CM                      61205
#define IDS_MEA_MM                      61206
#define IDS_MEA_POINTS                  61207
#define IDS_MEA_TWIPS                   61208
#define IDS_MEA_INCHES                  61209
#define IDS_MEA_SQCM                    61210
#define IDS_MEA_SQMM                    61211
#define IDS_MEA_SQIN                    61212
#define IDS_MEA_SQPIX                   61213
#define IDS_MEA_SQPTS                   61214
#define IDS_MEA_SQTWIPS                 61215
#define IDS_MEA_RES_INCHES              61216
#define IDS_MEA_RES_CM                  61217
#define IDS_MEA_RES_MM                  61218
#define IDS_MEA_RES_POINTS              61219
#define IDS_MEA_RES_TWIPS               61220
#define IDS_MEA_X1                      61221
#define IDS_MEA_Y1                      61222
#define IDS_MEA_X2                      61223
#define IDS_MEA_Y2                      61224
#define IDS_MEA_WIDTH                   61225
#define IDS_MEA_HEIGHT                  61226
#define IDS_MEA_LENGTH                  61227
#define IDS_MEA_AREA                    61228
#define IDS_MEA_RESOLUTION_X            61231
#define IDS_MEA_SCREEN                  61233
#define IDS_MEA_RESOLUTION_Y            61234
#define IDS_MEA_ANGLE                   61235
#define IDS_MEA_DEGREES                 61236
#define IDS_MEA_PREFERENCES             61237
#define IDS_MEA_POINT1                  61238
#define IDS_MEA_POINT2                  61239
#define IDS_MEA_ZOOM                    61240
#define IDS_MEA_FACTOR                  61241
#define IDS_MEA_COLOR                   61243
#define IDS_MEA_CURSOR                  61244
#define IDS_MEA_POINT                   61245
#define IDS_MEA_LINE                    61246
#define IDS_MEA_RECTANGLE               61247
#define IDS_MEA_WINDOW                  61248
#define IDS_MEA_EMPTY                   61249
#define IDS_MEA_BACKDLG_TITLE           61250
#define IDS_MEA_BORDERDLG_TITLE         61251
#define IDS_MEA_HILITEDLG_TITLE         61252
#define IDS_MEA_LINEDLG_TITLE           61253
#define IDS_MEA_SAVE_PROFILE_DLG        61254
#define IDS_MEA_LOAD_PROFILE_DLG        61255
#define IDS_MEA_NO_SAVE_PROFILE         61256
#define IDS_MEA_NO_LOAD_PROFILE         61257
#define IDS_MEA_FE_NONE                 61258
#define IDS_MEA_FE_FILE_NOT_FOUND       61259
#define IDS_MEA_FE_BAD_PATH             61260
#define IDS_MEA_FE_TOO_MANY_OPEN_FILES  61261
#define IDS_MEA_FE_ACCESS_DENIED        61262
#define IDS_MEA_FE_INVALID_FILE         61263
#define IDS_MEA_FE_REMOVE_CURRENT_DIR   61264
#define IDS_MEA_FE_DIRECTORY_FULL       61265
#define IDS_MEA_FE_BAD_SEEK             61266
#define IDS_MEA_FE_HARD_IO              61267
#define IDS_MEA_FE_SHARING_VIOLATION    61268
#define IDS_MEA_FE_LOCK_VIOLATION       61269
#define IDS_MEA_FE_DISK_FULL            61270
#define IDS_MEA_FE_END_OF_FILE          61271
#define IDS_MEA_FE_UNSPECIFIED          61272
#define IDS_MEA_PARSER_ERROR            61273
#define IDS_MEA_INVALID_PROFILE         61274
#define IDS_MEA_NO_PROFILE              61275
#define IDS_MEA_NOEXEC                  61276
#define IDS_MEA_PICAS                   61277
#define IDS_MEA_SQPCS                   61278
#define IDS_MEA_RES_PICAS               61279
#define IDS_MEA_COLLAPSE                61280
#define IDS_MEA_EXPAND                  61281
#define IDS_MEA_POINT_STATUS            61282
#define IDS_MEA_LINE_STATUS             61283
#define IDS_MEA_RECT_STATUS             61284
#define IDS_MEA_WIN_STATUS              61285
#define IDS_MEA_FIELD_VALUE             61286
#define IDS_MEA_GRID_FIELD_VALUE        61287
#define IDS_MEA_CAL_WARNING             61288
#define IDS_MEA_PAUSE                   61289
#define IDS_MEA_CURSOR_STATUS           61290
#define IDS_MEA_IN_INSTR                61291
#define IDS_MEA_CM_INSTR                61292
#define IDS_MEA_SAVE_LOG_DLG            61293
#define IDS_MEA_LOAD_LOG_DLG            61294
#define IDS_MEA_NO_SAVE_LOG             61295
#define IDS_MEA_NO_LOAD_LOG             61296
#define IDS_MEA_ASK_SAVE                61297
#define IDS_MEA_NO_POSITIONS            61298
#define IDS_MEA_VALIDATION_TITLE        61299
#define IDS_MEA_VALIDATION_MSG          61300
#define IDS_MEA_MULTIPLE_DOCUMENT_ELEMENTS 61301
#define IDS_MEA_MULTIPLE_TOP_LEVEL_ELEMENTS 61302
#define IDS_MEA_INVALID_DOCUMENT_ELEMENT 61303
#define IDS_MEA_UNDECLARED_ELEMENT      61304
#define IDS_MEA_UNDECLARED_ATTRIBUTE    61305
#define IDS_MEA_INVALID_ELEMENT         61307
#define IDS_MEA_NO_CHARACTER_DATA       61308
#define IDS_MEA_UNCONTAINED_CHARACTER_DATA 61309
#define IDS_MEA_MISMATCHED_FIXED_VALUE  61310
#define IDS_MEA_MISSING_REQUIRED_ATTRIBUTE 61311
#define IDS_MEA_BAD_ATTRIBUTE_VALUE     61312
#define IDS_MEA_DUPLICATE_ID            61313
#define IDS_MEA_UNDECLARED_NOTATION     61314
#define IDS_MEA_UNDECLARED_ENTITY       61315
#define IDS_MEA_ID_NOT_FOUND            61316
#define IDS_MEA_INVALID_ELEMENT_PATTERN 61317
#define IDS_MEA_PARSER_TITLE            61318
#define IDS_MEA_PARSER_MSG              61319
#define IDS_MEA_NO_MEMORY               61320
#define IDS_MEA_SYNTAX                  61321
#define IDS_MEA_NO_ELEMENTS             61322
#define IDS_MEA_INVALID_TOKEN           61323
#define IDS_MEA_UNCLOSED_TOKEN          61324
#define IDS_MEA_PARTIAL_CHAR            61325
#define IDS_MEA_TAG_MISMATCH            61326
#define IDS_MEA_DUPLICATE_ATTRIBUTE     61327
#define IDS_MEA_DOC_ELEMENT             61328
#define IDS_MEA_ENTITY_REF              61329
#define IDS_MEA_UNDEFINED_ENTITY        61330
#define IDS_MEA_RECURSIVE_ENTITY_REF    61331
#define IDS_MEA_ASYNC_ENTITY            61332
#define IDS_MEA_BAD_CHAR_REF            61333
#define IDS_MEA_BINARY_ENTITY_REF       61334
#define IDS_MEA_ATTRIBUTE_EXTERNAL_ENTITY_REF 61335
#define IDS_MEA_MISPLACED_XML_PI        61336
#define IDS_MEA_UNKNOWN_ENCODING        61337
#define IDS_MEA_INCORRECT_ENCODING      61338
#define IDS_MEA_UNCLOSED_CDATA_SECTION  61339
#define IDS_MEA_EXTERNAL_ENTITY_HANDLING 61340
#define IDS_MEA_NOT_STANDALONE          61341
#define IDS_MEA_UNEXPECTED_STATE        61342
#define IDS_MEA_ENTITY_DECLARED_IN_PE   61343
#define IDS_MEA_INVALID_LOGFILE         61344
#define IDS_MEA_INVALID_SCREENID        61345
#define IDS_MEA_INVALID_DESKTOPID       61345
#define IDS_MEA_INVALID_SCREENREF       61346
#define IDS_MEA_INVALID_DESKTOPREF      61346
#define IDS_MEA_ANGLE_LBL               61347
#define IDS_MEA_VERTEX                  61348
#define IDS_MEA_ANGLE_STATUS            61349
#define IDS_MEA_XV                      61350
#define IDS_MEA_YV                      61351
#define IDS_MEA_POSDLG_TITLE            61352
#define IDS_MEA_UNTITLED                61353
#define IDS_MEA_RADIANS                 61354
#define IDS_MEA_SCREEN_PRIMARY          61355
#define IDS_MEA_CALRES_TITLE            61356
#define IDS_MEA_CIRCLE                  61357
#define IDS_MEA_DEF_LABEL_FMT           61358
#define IDS_MEA_LENGTH_LABEL_FMT        61358
#define IDS_MEA_AREA_LABEL_FMT          61359
#define IDS_MEA_RES_LABEL_FMT           61360
#define IDS_MEA_CUSTOM_UNITS            61361
#define IDS_MEA_CUSTOM_MENU             61362
#define IDS_MEA_CUSTOM_LABEL            61363
#define IDS_MEA_CUSTOM_NAME_WARNING     61364
#define IDS_MEA_CUSTOM_FACTOR_WARNING   61365
#define IDS_MEA_MASTER_RESET            61366
#define IDS_MEA_CIRCLE_STATUS           61367
#define IDS_MEA_PREC_MIN                61368
#define IDS_MEA_PREC_VALUE              61369

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        166
#define _APS_NEXT_COMMAND_VALUE         32850
#define _APS_NEXT_CONTROL_VALUE         1180
#define _APS_NEXT_SYMED_VALUE           129
#endif
#endif
