Meazure: CMeazureApp Class Reference
CMeazureApp Class Reference
The application class.
#include <Meazure.h>
Public Member Functions
CMeazureApp ()
Starts the application.
virtual BOOL SaveAllModified ()
Called by the framework to see if each modified doc wants to save before the app goes away.
virtual void WinHelp (DWORD dwData, UINT nCmd)
Central interface to the windows help system.
virtual BOOL InitInstance ()
Performs all initialization for the application including processing of the command line arguments, if any.
virtual int ExitInstance ()
Called when the application is terminating.
afx_msg void OnAppAbout ()
Displays the application About dialog.
afx_msg void OnMouseHook (WPARAM wParam, LPARAM lParam)
Called by the Mouse Hook DLL to route pointer movement messages to the View.
Detailed Description
The application class.
Instantiating this class starts the app.
Member Function Documentation
CMeazureApp::ExitInstance () [virtual]
Called when the application is terminating.
Destroys all managers.
Returns:
Application exit code.
References MeaSingleton_T< MeaPositionLogMgr >::DestroyInstance(), MeaSingleton_T< MeaScreenMgr >::DestroyInstance(), MeaSingleton_T< MeaUnitsMgr >::DestroyInstance(), MeaSingleton_T< MeaToolMgr >::DestroyInstance(), and MeaSingleton_T< MeaProfileMgr >::DestroyInstance().
CMeazureApp::InitInstance () [virtual]
Performs all initialization for the application including processing of the command line arguments, if any.
Returns:
TRUE if initialization successful.
References MeaColors::Initialize(), CMainFrame::IsNewInstall(), OnAppAbout(), and CMainFrame::SetCommandLineFile().
CMeazureApp::OnAppAbout ()
Displays the application About dialog.
Referenced by InitInstance().
void CMeazureApp::OnMouseHook (WPARAM wParam, LPARAM lParam)
Called by the Mouse Hook DLL to route pointer movement messages to the View.
Parameters:
wParam [in] Message ID.
lParam [in] MOUSEHOOKSTRUCT
Returns:
Always returns 0.
BOOL CMeazureApp::SaveAllModified () [virtual]
Called by the framework to see if each modified doc wants to save before the app goes away.
Returns:
TRUE if safe to exit the application, FALSE otherwise.
References MeaSingleton_T< MeaPositionLogMgr >::Instance(), and MeaPositionLogMgr::SaveIfModified().
void CMeazureApp::WinHelp (DWORD dwData, UINT nCmd) [virtual]
Central interface to the windows help system.
In this case we override the base class calls to the old WinHelp system and instead call the new Windows HTML Help system.
Parameters:
dwData [in] ID for context sensitive help.
nCmd [in] Type of help requested.
The documentation for this class was generated from the following files:
Meazure.h
Meazure.cpp
Copyright 2011 C Thing Software