Meazure: MeaScreenProvider::Screen Class Reference
MeaScreenProvider::Screen Class Reference
Represents a single display screen.
Public Member Functions
Screen (LPCRECT rect)
Constructs a display screen object.
virtual ~Screen ()=default
Destroys a display screen object.
const CRect & GetRect () const
Returns the screen rectangle.
const CPoint & GetCenter () const
Determines the center of the screen.
void SetScreenRes (bool useManualRes, const MeaFSize *manualRes=nullptr)
Sets the resolution of the screen, in pixels per inch.
void GetScreenRes (bool &useManualRes, MeaFSize &manualRes) const
Obtains the currently set manual screen resolution, if set.
const MeaFSize & GetScreenRes () const
Obtains the current screen resolution.
bool IsManualRes () const
Indicates if the screen resolution has been manually set.
void SetPrimary (bool primary)
In multiple monitor environments, one of the monitors is designated as the primary.
bool IsPrimary () const
Indicates if this is the primary screen.
void SetCalInInches (bool calInInches)
Specifies whether the resolution calibration has been performed in inches or centimeters.
bool IsCalInInches () const
Indicates whether the resolution calibration has been performed in inches or centimeters.
void SetName (PCTSTR name)
Sets a descriptive name for the screen.
CString GetName () const
Returns the descriptive name for the screen.
Static Private Member Functions
static MeaFSize GetOSScreenRes ()
Obtains the screen resolution reported by the operating system.
Private Attributes
CRect m_rect
Screen rectangle.
CPoint m_center
Center point of the screen.
MeaFSize m_currentRes
Current screen resolution, pixels per inch.
MeaFSize m_manualRes
Manually calibrated resolution, pixels per inch.
bool m_useManualRes
Indicates if manually calibrated resolution is used.
bool m_calInInches
Indicates if calibration in inches or centimeters.
bool m_primary
Indicates if this is the primary screen.
CString m_name
Descriptive name for the screen.
Static Private Attributes
static const MeaFSize m_osRes = GetOSScreenRes()
DPI reported by the operating system.
Detailed Description
Represents a single display screen.
Constructor & Destructor Documentation
Screen()
MeaScreenProvider::Screen::Screen (LPCRECT rect) inline
Constructs a display screen object.
Parameters
rect [in] Rectangle representing the screen, in pixels. In multiple monitor environments, the screen rectangle can have negative coordinates.
References m_center, and m_rect.
Member Function Documentation
GetCenter()
const CPoint & MeaScreenProvider::Screen::GetCenter () const inline
Determines the center of the screen.
Returns
Center point of the screen.
References m_center.
GetName()
CString MeaScreenProvider::Screen::GetName () const inline
Returns the descriptive name for the screen.
Returns
Name for the screen or the empty string if there is no name.
References m_name.
GetOSScreenRes()
static MeaFSize MeaScreenProvider::Screen::GetOSScreenRes () inline static private
Obtains the screen resolution reported by the operating system.
Returns
Resolution in pixels per inch.
References MeaFSize::cx, and MeaFSize::cy.
GetRect()
const CRect & MeaScreenProvider::Screen::GetRect () const inline
Returns the screen rectangle.
Note that in multiple monitor environments, the screen rectangle can have negative coordinates.
Returns
Screen rectangle, in pixels.
References m_rect.
GetScreenRes() [1/2]
const MeaFSize & MeaScreenProvider::Screen::GetScreenRes () const inline
Obtains the current screen resolution.
If the resolution has been manually calibrated, it is returned. Otherwise the operating system reported resolution is returned.
Returns
Screen resolution, in pixels per inch.
References m_currentRes.
GetScreenRes() [2/2]
void MeaScreenProvider::Screen::GetScreenRes (bool & useManualRes, MeaFSize & manualRes) const inline
Obtains the currently set manual screen resolution, if set.
Parameters
useManualRes [out] Indicates whether the manually calibrated resolution is used (true) or the operating system resolution (false).
manualRes [out] Manually calibrated resolution, in pixels per inch.
References m_manualRes, and m_useManualRes.
IsCalInInches()
bool MeaScreenProvider::Screen::IsCalInInches () const inline
Indicates whether the resolution calibration has been performed in inches or centimeters.
Returns
true if the calibration has been performed in inches.
References m_calInInches.
IsManualRes()
bool MeaScreenProvider::Screen::IsManualRes () const inline
Indicates if the screen resolution has been manually set.
Returns
true if the screen resolution has been set manually.
References m_useManualRes.
IsPrimary()
bool MeaScreenProvider::Screen::IsPrimary () const inline
Indicates if this is the primary screen.
Returns
true if this is the primary screen.
References m_primary.
SetCalInInches()
void MeaScreenProvider::Screen::SetCalInInches (bool calInInches) inline
Specifies whether the resolution calibration has been performed in inches or centimeters.
Parameters
calInInches [in] true if the calibration has been performed in inches.
References m_calInInches.
Referenced by MeaScreenMgr::LoadProfile(), and MeaScreenMgr::MasterReset().
SetName()
void MeaScreenProvider::Screen::SetName (PCTSTR name) inline
Sets a descriptive name for the screen.
Parameters
name [in] Name for the screen.
References m_name.
Referenced by MeaScreenMgr::CreateScreens().
SetPrimary()
void MeaScreenProvider::Screen::SetPrimary (bool primary) inline
In multiple monitor environments, one of the monitors is designated as the primary.
This method designates the screen as the primary.
Parameters
primary [in] Specify true if this screen is the primary.
References m_primary.
Referenced by MeaScreenMgr::CreateScreens().
SetScreenRes()
void MeaScreenProvider::Screen::SetScreenRes (bool useManualRes, const MeaFSize * manualRes = nullptr) inline
Sets the resolution of the screen, in pixels per inch.
Parameters
useManualRes [in] Specifies whether the manually calibrated resolution should be used (true) or the operating system resolution (false).
manualRes [in] If non-nullptr, specifies the manually calibrated resolution.
References MeaFSize::cx, MeaFSize::cy, m_currentRes, m_manualRes, m_osRes, and m_useManualRes.
Referenced by MeaScreenMgr::LoadProfile(), and MeaScreenMgr::MasterReset().
The documentation for this class was generated from the following file:
ScreenMgr.cpp
Copyright 2011 C Thing Software