Meazure: MeaImageButton Class Reference
MeaImageButton Class Reference
A button that uses bitmap resources.
#include <ImageButton.h>
Public Member Functions
MeaImageButton (UINT up, UINT down=0, UINT disabled=0)
Constructs a image button using the specified image(s).
MeaImageButton ()
Constructs an image button with no images specified; the LoadBitmaps method must be called.
virtual ~MeaImageButton ()
Destroys a image button object.
bool Create (DWORD dwStyle, CWnd *pParentWnd, UINT nID=0xffff, UINT toolTipID=0xffff)
Convenience version of the button create method.
virtual BOOL PreTranslateMessage (MSG *pMsg)
Relays messages to the tooltip control.
void SetToggleType (bool toggle)
Specifies whether the button is a push button or a toggle button.
void LoadBitmaps (UINT up, UINT down, UINT disabled=0)
Loads the button's bitamps.
void GetBitmaps (UINT &up, UINT &down, UINT &disabled) const
Returns the bitmaps associated with the button image.
void SetState (bool state)
Sets the button state: up or down.
Protected Member Functions
afx_msg void OnDestroy ()
Performs cleanup of objects created in the Create method.
afx_msg void DrawItem (LPDRAWITEMSTRUCT lpDrawItemStruct)
Called to render the button.
afx_msg void OnLButtonDown (UINT nFlags, CPoint point)
Called when the left mouse button is pressed down.
Protected Attributes
HTHEME m_theme
Windows rendering theme for buttons.
UINT m_up
ID of bitmap for button up appearance.
UINT m_down
ID of bitmap for button down appearance.
UINT m_disabled
ID of bitmap for button disabled appearance.
bool m_depressed
Indicates if the button is depressed.
bool m_toggle
Indicates if this is a toggle button.
CToolTipCtrl m_toolTip
Tool tip control for the button.
Detailed Description
A button that uses bitmap resources.
Based on code from Joseph M. Newcomer at:
http://www.codeproject.com/buttonctrl/betterbmpbutton.asp
Constructor & Destructor Documentation
MeaImageButton()
MeaImageButton::MeaImageButton (UINT up, UINT down = 0, UINT disabled = 0) explicit
Constructs a image button using the specified image(s).
Parameters
up [in] Resource ID of image for button in up position.
down [in] Resource ID of image for button in down position.
disabled [in] Resource ID of image to use when button is disabled.
Member Function Documentation
Create()
bool MeaImageButton::Create (DWORD dwStyle, CWnd * pParentWnd, UINT nID = 0xffff, UINT toolTipID = 0xffff)
Convenience version of the button create method.
Using this method allows the button to size itself to the bitmap.
Parameters
dwStyle [in] Button style as defined by CButton.
pParentWnd [in] Parent window for the button.
nID [in] ID for the button.
toolTipID [in] String resource ID for the button's tooltip.
Returns
true if creation successful.
References IsThemeActive, m_theme, m_toolTip, m_up, and OpenThemeData.
Referenced by MeaMagnifier::Create(), and MeaDataDisplay::CreateScreenSection().
DrawItem()
void MeaImageButton::DrawItem (LPDRAWITEMSTRUCT lpDrawItemStruct) protected
Called to render the button.
Parameters
lpDrawItemStruct [in] Button item information structure.
References DrawThemeEdge, m_depressed, m_disabled, m_down, m_theme, m_toggle, and m_up.
GetBitmaps()
void MeaImageButton::GetBitmaps (UINT & up, UINT & down, UINT & disabled) const inline
Returns the bitmaps associated with the button image.
Parameters
up [out] Resource ID of image to use for up appearance when enabled.
down [out] Resource ID of image to use for down appearance when enabled.
disabled [out] Resource ID of image to use for disabled appearance.
References m_disabled, m_down, and m_up.
LoadBitmaps()
void MeaImageButton::LoadBitmaps (UINT up, UINT down, UINT disabled = 0) inline
Loads the button's bitamps.
Parameters
up [in] Resource ID of image to use for up appearance when enabled.
down [in] Resource ID of image to use for down appearance when enabled. If 0, the up image is used.
disabled [in] Resource ID of image to use for disabled appearance. If 0, the up image is halftoned gray
References m_disabled, m_down, and m_up.
Referenced by MeaMagnifier::Create(), and MeaDataDisplay::CreateScreenSection().
OnLButtonDown()
void MeaImageButton::OnLButtonDown (UINT nFlags, CPoint point) protected
Called when the left mouse button is pressed down.
Parameters
nFlags [in] Flags present when button pressed.
point [in] Location of the mouse when the button was pressed.
References m_depressed.
PreTranslateMessage()
BOOL MeaImageButton::PreTranslateMessage (MSG * pMsg) virtual
Relays messages to the tooltip control.
Parameters
pMsg [in] Message information structure.
Returns
TRUE if message was processed.
References m_toolTip.
SetState()
void MeaImageButton::SetState (bool state) inline
Sets the button state: up or down.
Parameters
state [in] Button state (0 = up, 1 = down).
References m_depressed.
Referenced by MeaMagnifier::SetRunState().
SetToggleType()
void MeaImageButton::SetToggleType (bool toggle) inline
Specifies whether the button is a push button or a toggle button.
Parameters
toggle [in] true if the button should have toggle behavior.
References m_toggle.
Referenced by MeaMagnifier::Create().
The documentation for this class was generated from the following files:
ImageButton.h
ImageButton.cpp
Copyright 2011 C Thing Software