Meazure: MeaTimer Class Reference
MeaTimer Class Reference
Implements a timer that issues timing messages at a higher priority than the standard windows timer that issues WM_TIMER messages.
#include <Timer.h>
Public Member Functions
MeaTimer ()
Instantiates a timer.
virtual ~MeaTimer ()
Destroys a timer.
void Create (CWnd *parent, WPARAM userData=0)
Registers the specified parent window to receive the timer messages.
void Start (int elapse)
Sets the timer to the specified interval and starts it running.
void Stop ()
Cancels the current timer if it is set.
Private Member Functions
UINT TimerProc ()
Called when the timer expires.
Static Private Member Functions
static UINT TimerProc (LPVOID pParam)
Called when the timer expires.
Private Attributes
CWinThread * m_timerThread
Thread in which the timer runs.
CCriticalSection m_critSect
Critical section guard.
CEvent m_stopEvent
Used internally to indicate the timer has been stopped.
CEvent m_exitEvent
Used internally to indicate the timer has completed all processing.
int m_elapse
Timer period, in milliseconds.
CWnd * m_parent
Window to receive the timer expire message.
WPARAM m_userData
Caller defined data.
Detailed Description
Implements a timer that issues timing messages at a higher priority than the standard windows timer that issues WM_TIMER messages.
Constructor & Destructor Documentation
MeaTimer()
MeaTimer::MeaTimer ()
Instantiates a timer.
To use the timer, the Create method must be called.
References m_exitEvent.
Member Function Documentation
Create()
void MeaTimer::Create (CWnd * parent, WPARAM userData = 0) inline
Registers the specified parent window to receive the timer messages.
The timer will send the parent a MeaHPTimerMsg message.
Parameters
parent [in] Parent window to receive the MeaHPTimerMsg message.
userData [in] Caller defined data.
References m_parent, m_userData, and MeaAssert.
Referenced by MeaCircle::Create(), MeaMagnifier::Create(), MeaLine::Create(), MeaRectangle::Create(), and CChildView::OnCreate().
Start()
void MeaTimer::Start (int elapse)
Sets the timer to the specified interval and starts it running.
Parameters
elapse [in] Time interval in milliseconds.
References m_critSect, m_elapse, m_parent, m_timerThread, MeaAssert, and TimerProc().
Referenced by CChildView::OnCopyRegion(), MeaMagnifier::OnHPTimer(), MeaCircle::SetPosition(), MeaRectangle::SetPosition(), and MeaLine::SetPosition().
TimerProc() [1/2]
UINT MeaTimer::TimerProc () private
Called when the timer expires.
Sends the MeaHPTimerMsg message to the parent window.
Returns
Zero indicating success.
References m_critSect, m_elapse, m_exitEvent, m_parent, m_stopEvent, m_timerThread, m_userData, and MeaHPTimerMsg.
Referenced by Start(), and TimerProc().
TimerProc() [2/2]
static UINT MeaTimer::TimerProc (LPVOID pParam) inline static private
Called when the timer expires.
Simply calls the instance method of the same name.
Parameters
pParam [i] Timer instance pointer.
Returns
Zero indicating success.
References TimerProc().
The documentation for this class was generated from the following files:
Timer.h
Timer.cpp
Copyright 2011 C Thing Software