Meazure: ev::ElementDecl Class Reference
ev::ElementDecl Class Reference
Represents an element declaration.
Public Types
typedef std::map< EVString, AttributeDecl * > AttributeMap
Maps the name of an attribute to its declaration object.
typedef AttributeMap::const_iterator AttributeIter_c
Constant iterator over the element's attributes.
Public Member Functions
ElementDecl (Validator &validator, const XML_Char *elementName)
Constructs an element declaration.
virtual ~ElementDecl ()
Destroys an element declaration.
const State * GetStartState () const
Obtains the start state for the DFA representing this element's content model.
EVString GetName () const
Returns the name of the element.
void SetDFA (DFA *dfa)
Places the specified DFA on the element.
void AddAttributeDecl (const XML_Char *attrName, const XML_Char *attrType, const XML_Char *defValue, bool isRequired)
Places the specified attribute declaration on the element.
const AttributeDecl * GetAttributeDecl (const XML_Char *attrName) const
Returns the declaration for the specified attribute name.
AttributeIter_c StartRequiredAttributes () const
Returns an iterator over the required attributes.
AttributeIter_c EndRequiredAttributes () const
Returns an iterator pointed at the end of the required attribute list.
const Validator & GetValidator () const
Returns the parent validator for the element declaration.
Protected Types
typedef AttributeMap::iterator AttributeIter
Iterator over the element's attributes.
Protected Member Functions
ElementDecl (const ElementDecl &decl)
Purposely undefined.
ElementDecl & operator= (const ElementDecl &decl)
Purposely undefined.
Protected Attributes
DFA * m_dfa
DFA representing this element's content model.
EVString m_elementName
Name of the element being declared.
AttributeMap m_attributes
Attributes for the element.
AttributeMap m_requiredAttributes
Required attributes for the element.
Validator & m_validator
Parent validator for the element.
Friends
EVOstream & operator<< (EVOstream &stream, const ElementDecl *elementDecl)
Output stream operator for an element declaration.
Detailed Description
Represents an element declaration.
Constructor & Destructor Documentation
ElementDecl()
ElementDecl::ElementDecl (Validator & validator, const XML_Char * elementName)
Constructs an element declaration.
Parameters
validator [in] Parent validator for the declaration.
elementName [in] Name of the element being declared.
Member Function Documentation
AddAttributeDecl()
void ElementDecl::AddAttributeDecl (const XML_Char * attrName, const XML_Char * attrType, const XML_Char * defValue, bool isRequired)
Places the specified attribute declaration on the element.
Parameters
attrName [in] Attribute name.
attrType [in] Attribute type.
defValue [in] Default value for the attribute or NULL if there is no default value.
isRequired [in] Indicates whether the attribute must be specified.
References ev::AttributeDecl::IsRequired(), m_attributes, and m_requiredAttributes.
Referenced by ev::Validator::AddAttributeDecl().
EndRequiredAttributes()
AttributeIter_c ev::ElementDecl::EndRequiredAttributes () const inline
Returns an iterator pointed at the end of the required attribute list.
Returns
Constant iterator pointed at the end of the list of required attributes.
References m_requiredAttributes.
Referenced by ev::Validator::StartElement().
GetAttributeDecl()
const AttributeDecl * ev::ElementDecl::GetAttributeDecl (const XML_Char * attrName) const inline
Returns the declaration for the specified attribute name.
Parameters
attrName [in] Name of attribute whose declaration is desired.
Returns
Attribute declaration corresponding to the specified attribute name.
References m_attributes.
Referenced by ev::Validator::StartElement().
GetName()
EVString ev::ElementDecl::GetName () const inline
Returns the name of the element.
Returns
Element name.
References m_elementName.
GetStartState()
const State * ElementDecl::GetStartState () const
Obtains the start state for the DFA representing this element's content model.
Returns
Start state for this element's DFA.
References ev::DFA::GetStartState(), and m_dfa.
Referenced by ev::Validator::StartElement().
GetValidator()
const Validator & ev::ElementDecl::GetValidator () const inline
Returns the parent validator for the element declaration.
Returns
Parent validator for the element declaration.
References m_validator.
SetDFA()
void ev::ElementDecl::SetDFA (DFA * dfa) inline
Places the specified DFA on the element.
Parameters
dfa [in] DFA that represents the element's content model.
References m_dfa.
Referenced by ev::Validator::AddElementDecl().
StartRequiredAttributes()
AttributeIter_c ev::ElementDecl::StartRequiredAttributes () const inline
Returns an iterator over the required attributes.
Returns
Constant iterator pointed at the start of the list of required attributes.
References m_requiredAttributes.
Referenced by ev::Validator::StartElement().
Friends And Related Function Documentation
operator<<
EVOstream & operator<< (EVOstream & stream, const ElementDecl * elementDecl) friend
Output stream operator for an element declaration.
Used to dump the state of the element declaration to the specified output stream for debugging purposes.
Parameters
stream [in] Output stream.
elementDecl [in] Element declaration to output.
Returns
Output stream.
The documentation for this class was generated from the following file:
exval.cpp
Copyright 2011 C Thing Software