Meazure: MeaTextField Class Reference
MeaTextField Class Reference
Provides a text field control with appropriate fonts and sizes configured.
#include <TextField.h>
Public Member Functions
bool Create (DWORD style, const POINT &topLeft, int numChars, CWnd *parentWnd, UINT id=0xFFFF)
Creates the window for the field.
bool IsTextSelected () const
Indicates if the value in the field is selected.
Protected Member Functions
afx_msg void OnKillFocus (CWnd *win)
Called when the field loses keyboard focus.
Detailed Description
Provides a text field control with appropriate fonts and sizes configured.
Member Function Documentation
Create()
bool MeaTextField::Create (DWORD style, const POINT & topLeft, int numChars, CWnd * parentWnd, UINT id = 0xFFFF)
Creates the window for the field.
To make the field visible, add the WS_VISIBLE style or call ShowWindow.
Parameters
style [in] Field styles as defined for CEdit.
topLeft [in] Position of the top, left corner for the field, in pixels.
numChars [in] Number of visible characters. For proportional fonts the number of characters actually visible may vary from the specified value.
parentWnd [in] Parent window for the field.
id [in] ID for the field.
Returns
true if the field was created successfully.
References MeaLayout::SetWindowSize().
Referenced by MeaMagnifier::Create(), and MeaDataDisplay::DataItem::CreateField().
IsTextSelected()
bool MeaTextField::IsTextSelected () const inline
Indicates if the value in the field is selected.
Returns
true if the value in the field is selected.
Referenced by AppView::OnUpdateEditClear(), AppView::OnUpdateEditCopy(), and AppView::OnUpdateEditCut().
OnKillFocus()
void MeaTextField::OnKillFocus (CWnd * win) protected
Called when the field loses keyboard focus.
The parent window is sent a MeaFieldFocusMsg message so that it can take actions such as reading the value in the field.
Parameters
win [in] Next window to receive focus.
References MeaFieldFocusMsg.
The documentation for this class was generated from the following files:
TextField.h
TextField.cpp
Copyright 2011 C Thing Software