Meazure: MeaUnitsMgr Class Reference
MeaUnitsMgr Class Reference
Manager for all units related operations including creating the units objects and labels, specifying the current units, setting the measurement origin and setting the y-axis orientation.
#include <UnitsMgr.h>
Public Member Functions
MeaUnitsMgr (token)
MeaUnitsMgr (const MeaUnitsMgr &)=delete
MeaUnitsMgr & operator= (const MeaUnitsMgr &)=delete
void SaveProfile (MeaProfile &profile)
Persists the state of the units manager to the specified profile object.
void LoadProfile (MeaProfile &profile)
Restores the state of the units manager from the specified profile object.
void MasterReset ()
Called when the master application reset is initiated.
void SetLinearUnits (MeaLinearUnitsId unitsId)
Sets the current linear measurement units based on the specified units identifier.
void SetLinearUnits (PCTSTR unitsStr)
Sets the current linear measurement units based on the specified units identifier string (e.g.
void SetAngularUnits (MeaAngularUnitsId unitsId)
Sets the current angular measurement units based on the specified units identifier.
void SetAngularUnits (PCTSTR unitsStr)
Sets the current angular measurement units based on the specified units identifier string (e.g.
MeaLinearUnits * GetLinearUnits () const override
Returns the current linear measurement units.
MeaLinearUnits * GetLinearUnits (const CString &unitsStr) const override
Returns the linear measurement units object corresponding to the specified identifier string (e.g.
MeaLinearUnitsId GetLinearUnitsId () const
Returns the identifier for the current linear measurement units.
CString GetLinearUnitsStr () const
Returns the identifier string for the current linear measurement units (e.g.
MeaAngularUnits * GetAngularUnits () const override
Returns the current angular measurement units.
MeaAngularUnits * GetAngularUnits (const CString &unitsStr) const override
Returns the angular measurement units object corresponding to the specified identifier string (e.g.
MeaAngularUnitsId GetAngularUnitsId () const
Returns the identifier for the current angular measurement units.
CString GetAngularUnitsStr () const
Returns the identifier string for the current angular measurement units (e.g.
MeaCustomUnits * GetCustomUnits ()
Returns the user defined units object.
void SetLinearDisplayPrecisions (MeaLinearUnitsId unitsId, const MeaUnits::DisplayPrecisions &precisions)
Set the number of decimal places to show on the data display for all types of linear measurements in the specified units (e.g.
const MeaUnits::DisplayPrecisions & GetLinearDisplayPrecisions (MeaLinearUnitsId unitsId)
Returns the array of decimal places currently set for each linear measurement type in the specified units.
const MeaUnits::DisplayPrecisions & GetLinearDefaultPrecisions (MeaLinearUnitsId unitsId)
Returns the array of default decimal places for each linear measurement type in the specified units.
void SetAngularDisplayPrecisions (MeaAngularUnitsId unitsId, const MeaUnits::DisplayPrecisions &precisions)
Set the number of decimal places to show on the data display for angular measurements in the specified units.
const MeaUnits::DisplayPrecisions & GetAngularDisplayPrecisions (MeaAngularUnitsId unitsId)
Returns the array of decimal places currently set for the specified angular measurement units.
const MeaUnits::DisplayPrecisions & GetAngularDefaultPrecisions (MeaAngularUnitsId unitsId)
Returns the array of default decimal places for the specified angular measurement units.
void SetInvertY (bool invertY) const
By default, the Windows coordinate system is inverted from the typical Cartesian coordinate system in that the origin is located in the upper left corner of the primary screen and the positive y-axis points downward.
bool IsInvertY () const override
Returns the orientation of the y-axis.
void SetSupplementalAngle (boolean showSupplemental)
Sets whether to show the included angle (default) or the supplemental angle.
bool IsSupplementalAngle ()
Indicates whether the included angle is shown (default) or the supplemental angle.
void SetOrigin (const POINT &origin) const
Moves the origin of the coordinate system to the specified point.
const POINT & GetOrigin () const override
Returns the location of the origin of the coordinate system.
MeaFSize GetWidthHeight (const POINT &p1, const POINT &p2) const override
Uses the current linear measurement units to convert the two specified points from pixels to the current units, and then calculates the width and height of the rectangle formed by the two points.
MeaLengthUnitsLabel * NewLengthUnitsLabel ()
Creates a new length measurement units label object.
MeaAngularUnitsLabel * NewAngleUnitsLabel ()
Creates a new angular measurement units label object.
MeaAreaUnitsLabel * NewAreaUnitsLabel ()
Creates a new area measurement units label object.
MeaResUnitsLabel * NewResUnitsLabel ()
Creates a new resolution measurement units label object.
void DeleteUnitsLabel (MeaUnitsLabel *label)
Destroys the specified measurement units label.
CString FormatConvertAngle (double angle) const override
Converts the specified angle to the current angular units and formats the result for display.
CString Format (MeaLinearMeasurementId id, double value) const override
Formats the specified linear measurement value for display.
CString Format (MeaAngularMeasurementId id, double value) const override
Formats the specified angular measurement value for display.
MeaFPoint ConvertCoord (const POINT &pos) const override
Converts the specified coordinate from pixels to the desired units.
POINT UnconvertCoord (const MeaFPoint &pos) const
Converts from the current units to pixels.
MeaFPoint ConvertPos (const POINT &pos) const override
Converts the specified position from pixels to the desired units.
POINT UnconvertPos (const MeaFPoint &pos) const override
Converts from the current units to pixels.
MeaFSize ConvertRes (const MeaFSize &res) const override
Converts the specified resolution in pixels/inch to the desired units.
double ConvertAngle (double angle) const override
Converts the specified angle value from its native radians to the desired units.
SIZE ConvertToPixels (MeaLinearUnitsId id, const MeaFSize &res, double value, int minPixels) const override
Converts the specified value from the specified units to pixels.
int GetMajorTickCount () const override
Returns the number of minor ticks to display before a major tick mark is displayed on the measurement rulers.
MeaFSize GetMinorIncr (const RECT &rect) const override
Returns the increment between minor tick marks on the measurement rulers.
virtual MeaLinearUnits * GetLinearUnits () const =0
Returns the current linear measurement units.
virtual MeaLinearUnits * GetLinearUnits (const CString &unitsStr) const =0
Returns the linear measurement units object corresponding to the specified identifier string (e.g.
virtual MeaAngularUnits * GetAngularUnits () const =0
Returns the current angular measurement units.
virtual MeaAngularUnits * GetAngularUnits (const CString &unitsStr) const =0
Returns the angular measurement units object corresponding to the specified identifier string (e.g.
virtual bool IsInvertY () const =0
Returns the orientation of the y-axis.
virtual const POINT & GetOrigin () const =0
Returns the location of the origin of the coordinate system.
virtual MeaFSize GetWidthHeight (const POINT &p1, const POINT &p2) const =0
Uses the current linear measurement units to convert the two specified points from pixels to the current units, and then calculates the width and height of the rectangle formed by the two points.
virtual CString FormatConvertAngle (double angle) const =0
Converts the specified angle to the current angular units and formats the result for display.
virtual CString Format (MeaLinearMeasurementId id, double value) const =0
Formats the specified linear measurement value for display.
virtual CString Format (MeaAngularMeasurementId id, double value) const =0
Formats the specified angular measurement value for display.
virtual MeaFPoint ConvertCoord (const POINT &pos) const =0
Converts the specified coordinate from pixels to the desired units.
virtual MeaFPoint ConvertPos (const POINT &pos) const =0
Converts the specified position from pixels to the desired units.
virtual POINT UnconvertPos (const MeaFPoint &pos) const =0
Converts from the current units to pixels.
virtual MeaFSize ConvertRes (const MeaFSize &res) const =0
Converts the specified resolution in pixels/inch to the desired units.
virtual double ConvertAngle (double angle) const =0
Converts the specified angle value from its native radians to the desired units.
virtual SIZE ConvertToPixels (MeaLinearUnitsId id, const MeaFSize &res, double value, int minPixels) const =0
Converts the specified value from the specified units to pixels.
virtual int GetMajorTickCount () const =0
Returns the number of minor ticks to display before a major tick mark is displayed on the measurement rulers.
virtual MeaFSize GetMinorIncr (const RECT &rect) const =0
Returns the increment between minor tick marks on the measurement rulers.
Public Member Functions inherited from MeaSingleton_T< MeaUnitsMgr >
MeaSingleton_T (const MeaSingleton_T< MeaUnitsMgr > &src)=delete
Singletons have no copy semantics.
MeaSingleton_T< MeaUnitsMgr > & operator= (const MeaSingleton_T< MeaUnitsMgr > &src)=delete
Singletons have no assignment semantics.
Static Public Attributes
static constexpr bool kDefHaveWarned { false }
Indicates whether the user has already been warned about using the operating system reported resolution.
static constexpr PCTSTR kDefLinearUnits { _T("px") }
Default units for linear measurements.
static constexpr PCTSTR kDefAngularUnits { _T("deg") }
Default units for angular measurements.
static constexpr bool kDefInvertY { false }
Default orientation of the y-axis.
static constexpr bool kDefSupplmentalAngle { false }
Default angle to show.
Private Types
typedef std::map< MeaLinearUnitsId, MeaLinearUnits * > LinearUnitsMap
Maps linear units identifiers to the corresponding linear units objects.
typedef std::map< MeaAngularUnitsId, MeaAngularUnits * > AngularUnitsMap
Maps angular units identifiers to the corresponding angular units objects.
typedef std::list< MeaLinearUnitsLabel * > LinearLabelsList
List of all linear units labels.
typedef std::list< MeaAngularUnitsLabel * > AngularLabelsList
List of all angular units labels.
Private Attributes
MeaPixelUnits m_pixelUnits
Pixel units object.
MeaPointUnits m_pointUnits
Point units object.
MeaTwipUnits m_twipUnits
Twips units object.
MeaInchUnits m_inchUnits
Inch units object.
MeaCentimeterUnits m_cmUnits
Centimeter units object.
MeaMillimeterUnits m_mmUnits
Millimeter units object.
MeaPicaUnits m_picaUnits
Pica units object.
MeaCustomUnits m_customUnits
User defined units object.
MeaDegreeUnits m_degreeUnits
Degree units object.
MeaRadianUnits m_radianUnits
Radian units object.
MeaLinearUnits * m_currentLinearUnits
Points to the current linear units object.
MeaAngularUnits * m_currentAngularUnits
Points to the current angular units object.
LinearUnitsMap m_linearUnitsMap
Map of linear units identifiers to units objects.
AngularUnitsMap m_angularUnitsMap
Map of angular units identifiers to units objects.
LinearLabelsList m_linearLabelsList
List of linear units labels.
AngularLabelsList m_angularLabelsList
List of angular units labels.
bool m_haveWarned
Indicates whether the user has already been warned about using the operating system reported resolution.
int m_majorTickCount
Number of minor ruler tick marks between major tick marks.
Static Private Attributes
static constexpr double kTickIncrements [] { 10.0, 25.0, 50.0, 75.0, 100.0 }
Ruler tick increments. The order of magnitude of these values is adjusted based on the units.
static constexpr int kNumTickIncrements { sizeof(kTickIncrements) / sizeof(*kTickIncrements) }
Number of tick mark increments in the kTickIncrements array.
static constexpr int kMinSepPixels { 5 }
Minimum separation between ruler tick marks, in pixels.
static constexpr double kMinSepInches { 0.1 }
Additional Inherited Members
Static Public Member Functions inherited from MeaSingleton_T< MeaUnitsMgr >
static MeaUnitsMgr & Instance ()
The first time this method is called, a instance of the Singleton object is created and returned.
Protected Member Functions inherited from MeaSingleton_T< MeaUnitsMgr >
MeaSingleton_T ()=default
Constructs a Singleton object instance.
Detailed Description
Manager for all units related operations including creating the units objects and labels, specifying the current units, setting the measurement origin and setting the y-axis orientation.
Member Function Documentation
ConvertAngle()
double MeaUnitsMgr::ConvertAngle (double angle) const inline override virtual
Converts the specified angle value from its native radians to the desired units.
Parameters
angle [in] Value to be converted.
Returns
Angle value converted to the desired units.
Implements MeaUnitsProvider.
References MeaAngularUnits::ConvertAngle(), and m_currentAngularUnits.
Referenced by FormatConvertAngle().
ConvertCoord()
MeaFPoint MeaUnitsMgr::ConvertCoord (const POINT & pos) const inline override virtual
Converts the specified coordinate from pixels to the desired units.
This conversion takes into account the location of the origin and the orientation of the y-axis.
Parameters
pos [in] Coordinates in pixels to convert to the desired units.
Returns
Coordinates converted from pixels to the desired units. The conversion takes into account the location of the origin and the orientation of the y-axis.
Implements MeaUnitsProvider.
References MeaLinearUnits::ConvertCoord(), and m_currentLinearUnits.
Referenced by GetWidthHeight().
ConvertPos()
MeaFPoint MeaUnitsMgr::ConvertPos (const POINT & pos) const inline override virtual
Converts the specified position from pixels to the desired units.
This conversion does not take into account the location of the origin nor does it compensate for the orientation of the y-axis.
Parameters
pos [in] Position in pixels to convert to the desired units.
Returns
Position converted from pixels to the desired units. The conversion does not take into account the location of the origin nor does it compensate for the orientation of the y-axis.
Implements MeaUnitsProvider.
References MeaLinearUnits::ConvertPos(), and m_currentLinearUnits.
Referenced by SaveProfile().
ConvertRes()
MeaFSize MeaUnitsMgr::ConvertRes (const MeaFSize & res) const inline override virtual
Converts the specified resolution in pixels/inch to the desired units.
Parameters
res [in] Resolution in pixels/inch to convert to the desired units.
Returns
Resolution converted from pixels/inch to the desired units.
Implements MeaUnitsProvider.
References MeaLinearUnits::ConvertRes(), and m_currentLinearUnits.
ConvertToPixels()
SIZE MeaUnitsMgr::ConvertToPixels (MeaLinearUnitsId id, const MeaFSize & res, double value, int minPixels) const inline override virtual
Converts the specified value from the specified units to pixels.
A minimum pixel value is specified in case the resolution is such that the conversion to pixels results in a value that is too small.
Parameters
id [in] Linear units identifier.
res [in] Screen resolution to use to perform the conversion.
value [in] Value to be converted to pixels.
minPixels [in] If the converted pixel value in less than this minimum value, the minimum value is returned.
Returns
X and Y pixel values.
Implements MeaUnitsProvider.
References m_linearUnitsMap.
Referenced by GetMinorIncr().
DeleteUnitsLabel()
void MeaUnitsMgr::DeleteUnitsLabel (MeaUnitsLabel * label)
Destroys the specified measurement units label.
Parameters
label [in] Label object to be deleted.
References m_angularLabelsList, and m_linearLabelsList.
Referenced by MeaDataDisplay::DataItem::~DataItem().
Format() [1/2]
CString MeaUnitsMgr::Format (MeaAngularMeasurementId id, double value) const inline override virtual
Formats the specified angular measurement value for display.
Parameters
id [in] Identifies the angular measurement for use in determining the display precision.
value [in] Angular measurement value to format, in current units.
Returns
String containing the formatted measurement data.
Implements MeaUnitsProvider.
References MeaAngularUnits::Format(), and m_currentAngularUnits.
Format() [2/2]
CString MeaUnitsMgr::Format (MeaLinearMeasurementId id, double value) const inline override virtual
Formats the specified linear measurement value for display.
Parameters
id [in] Identifies the linear measurement for use in determining the display precision.
value [in] Linear measurement value to format, in current units.
Returns
String containing the formatted measurement data.
Implements MeaUnitsProvider.
References MeaLinearUnits::Format(), and m_currentLinearUnits.
Referenced by FormatConvertAngle(), MeaDataDisplay::ShowScreenRes(), MeaDataDisplay::ShowScreenWH(), MeaDataDisplay::ShowWH(), MeaDataDisplay::ShowXY1(), MeaDataDisplay::ShowXY2(), and MeaDataDisplay::ShowXYV().
FormatConvertAngle()
CString MeaUnitsMgr::FormatConvertAngle (double angle) const inline override virtual
Converts the specified angle to the current angular units and formats the result for display.
Parameters
angle [in] Angle to be converted and displayed, in radians.
Returns
String containing the converted and formatted angle data.
Implements MeaUnitsProvider.
References ConvertAngle(), Format(), and MeaA.
GetAngularDefaultPrecisions()
const MeaUnits::DisplayPrecisions & MeaUnitsMgr::GetAngularDefaultPrecisions (MeaAngularUnitsId unitsId) inline
Returns the array of default decimal places for the specified angular measurement units.
Parameters
unitsId [in] Identifier for the units whose precisions are desired.
Returns
Array of decimal places.
References m_angularUnitsMap.
Referenced by MeaPrecisionPrefs::OnDefault().
GetAngularDisplayPrecisions()
const MeaUnits::DisplayPrecisions & MeaUnitsMgr::GetAngularDisplayPrecisions (MeaAngularUnitsId unitsId) inline
Returns the array of decimal places currently set for the specified angular measurement units.
Parameters
unitsId [in] Identifier for the units whose precisions are desired.
Returns
Array of decimal places.
References m_angularUnitsMap.
Referenced by AppView::OnPreferences().
GetAngularUnits() [1/2]
MeaAngularUnits * MeaUnitsMgr::GetAngularUnits () const inline override virtual
Returns the current angular measurement units.
Returns
Current angular units.
Implements MeaUnitsProvider.
References m_currentAngularUnits.
Referenced by MeaDataDisplay::CreateRegionSection().
GetAngularUnits() [2/2]
MeaAngularUnits * MeaUnitsMgr::GetAngularUnits (const CString & unitsStr) const inline override virtual
Returns the angular measurement units object corresponding to the specified identifier string (e.g.
"deg").
Parameters
unitsStr [in] Angular units identifier string.
Returns
Angular measurement units object.
Implements MeaUnitsProvider.
References m_angularUnitsMap.
GetAngularUnitsId()
MeaAngularUnitsId MeaUnitsMgr::GetAngularUnitsId () const inline
Returns the identifier for the current angular measurement units.
Returns
Identifier for the current angular measurement units.
References MeaAngularUnits::GetUnitsId(), and m_currentAngularUnits.
Referenced by MeaPrecisionPrefs::OnInitDialog(), and AppView::OnUpdateAngles().
GetAngularUnitsStr()
CString MeaUnitsMgr::GetAngularUnitsStr () const inline
Returns the identifier string for the current angular measurement units (e.g.
"deg").
Returns
Identifier string for the current angular measurement units.
References MeaUnits::GetUnitsStr(), and m_currentAngularUnits.
Referenced by SaveProfile(), and MeaPositionLogMgr::ShowPosition().
GetCustomUnits()
MeaCustomUnits * MeaUnitsMgr::GetCustomUnits () inline
Returns the user defined units object.
This is not necessarily the current measurement units object.
Returns
User defined measurement units object.
References m_customUnits.
Referenced by AppView::ApplyPreferences(), AppView::OnPreferences(), AppView::OnUpdateCustomUnits(), and MeaPositionLogMgr::ShowPosition().
GetLinearDefaultPrecisions()
const MeaUnits::DisplayPrecisions & MeaUnitsMgr::GetLinearDefaultPrecisions (MeaLinearUnitsId unitsId) inline
Returns the array of default decimal places for each linear measurement type in the specified units.
Parameters
unitsId [in] Identifier for the units whose precisions are desired.
Returns
Array of decimal places for each linear measurement type.
References m_linearUnitsMap.
Referenced by MeaPrecisionPrefs::OnDefault().
GetLinearDisplayPrecisions()
const MeaUnits::DisplayPrecisions & MeaUnitsMgr::GetLinearDisplayPrecisions (MeaLinearUnitsId unitsId) inline
Returns the array of decimal places currently set for each linear measurement type in the specified units.
Parameters
unitsId [in] Identifier for the units whose precisions are desired.
Returns
Array of decimal places for each linear measurement type.
References m_linearUnitsMap.
Referenced by AppView::OnPreferences().
GetLinearUnits() [1/2]
MeaLinearUnits * MeaUnitsMgr::GetLinearUnits () const inline override virtual
Returns the current linear measurement units.
Returns
Current linear units.
Implements MeaUnitsProvider.
References m_currentLinearUnits.
Referenced by MeaDataDisplay::CreateRegionSection(), and MeaDataDisplay::CreateScreenSection().
GetLinearUnits() [2/2]
MeaLinearUnits * MeaUnitsMgr::GetLinearUnits (const CString & unitsStr) const inline override virtual
Returns the linear measurement units object corresponding to the specified identifier string (e.g.
"px").
Parameters
unitsStr [in] Linear units identifier string.
Returns
Linear measurement units object.
Implements MeaUnitsProvider.
References m_linearUnitsMap.
GetLinearUnitsId()
MeaLinearUnitsId MeaUnitsMgr::GetLinearUnitsId () const inline
Returns the identifier for the current linear measurement units.
Returns
Identifier for the current linear measurement units.
References MeaLinearUnits::GetUnitsId(), and m_currentLinearUnits.
Referenced by AppView::ApplyPreferences(), MeaPrecisionPrefs::OnInitDialog(), AppView::OnUpdateCustomUnits(), and AppView::OnUpdateUnits().
GetLinearUnitsStr()
CString MeaUnitsMgr::GetLinearUnitsStr () const inline
Returns the identifier string for the current linear measurement units (e.g.
"px").
Returns
Identifier string for the current linear measurement units.
References MeaUnits::GetUnitsStr(), and m_currentLinearUnits.
Referenced by SaveProfile(), and MeaPositionLogMgr::ShowPosition().
GetMajorTickCount()
int MeaUnitsMgr::GetMajorTickCount () const inline override virtual
Returns the number of minor ticks to display before a major tick mark is displayed on the measurement rulers.
Returns
Number of minor tick marks to display before displaying a major tick mark.
Implements MeaUnitsProvider.
References m_majorTickCount.
GetMinorIncr()
MeaFSize MeaUnitsMgr::GetMinorIncr (const RECT & rect) const override virtual
Returns the increment between minor tick marks on the measurement rulers.
Parameters
rect [in] Rectangle in screen coordinates, used to determine the current screen resolution.
Returns
Increment for the minor tick marks, in the current units.
Implements MeaUnitsProvider.
References ConvertToPixels(), MeaFSize::cx, MeaFSize::cy, floor(), MeaLinearUnits::FromPixels(), MeaScreenMgr::GetScreenIter(), MeaScreenMgr::GetScreenRes(), MeaSingleton_T< MeaScreenMgr >::Instance(), kMinSepPixels, kNumTickIncrements, kTickIncrements, log10(), m_currentLinearUnits, and MeaInchesId.
GetOrigin()
const POINT & MeaUnitsMgr::GetOrigin () const inline override virtual
Returns the location of the origin of the coordinate system.
Returns
Location of the origin of the coordinate system, in pixels.
Implements MeaUnitsProvider.
References MeaLinearUnits::GetOrigin().
Referenced by SaveProfile(), and MeaPositionLogMgr::ShowPosition().
GetWidthHeight()
MeaFSize MeaUnitsMgr::GetWidthHeight (const POINT & p1, const POINT & p2) const override virtual
Uses the current linear measurement units to convert the two specified points from pixels to the current units, and then calculates the width and height of the rectangle formed by the two points.
Parameters
p1 [in] One point defining the rectangle, in pixels.
p2 [in] The other point defining the rectangle, in pixels.
Returns
The width and height of the rectangle formed by the two specified points converted to the current linear measurement units. Regardless of the relative locations of the two points, the width and height are always positive. In addition, the width and height are inclusive (e.g. p1.x = 1, p2.x = 3, width = p2.x - p1.x + 1 = 3).
Implements MeaUnitsProvider.
References ConvertCoord(), MeaFPoint::x, and MeaFPoint::y.
IsInvertY()
bool MeaUnitsMgr::IsInvertY () const inline override virtual
Returns the orientation of the y-axis.
Returns
If true is returned, the origin of the coordinate system is located at the lower left of the primary screen, and the positive y-axis is pointing upward. If false is returned, the origin is located at the upper left corner and the positive y-axis is pointing down. Note that the actual location of the origin is determined by the SetOrigin method.
Implements MeaUnitsProvider.
References MeaLinearUnits::IsInvertY().
Referenced by SaveProfile(), and MeaPositionLogMgr::ShowPosition().
IsSupplementalAngle()
bool MeaUnitsMgr::IsSupplementalAngle () inline
Indicates whether the included angle is shown (default) or the supplemental angle.
Returns
true if the supplemental angle is shown.
References MeaAngularUnits::IsSupplementalAngle().
Referenced by SaveProfile().
LoadProfile()
void MeaUnitsMgr::LoadProfile (MeaProfile & profile)
Restores the state of the units manager from the specified profile object.
Parameters
profile [in] Profile object from which the manager state is restored.
References MeaProfile::GetVersion(), kDefAngularUnits, kDefInvertY, kDefLinearUnits, kDefSupplmentalAngle, m_angularUnitsMap, m_haveWarned, m_linearUnitsMap, MeaPixelsId, MeaProfile::ReadBool(), MeaProfile::ReadDbl(), MeaProfile::ReadInt(), MeaProfile::ReadStr(), SetAngularUnits(), SetInvertY(), SetLinearUnits(), SetOrigin(), SetSupplementalAngle(), UnconvertPos(), MeaProfile::UserInitiated(), MeaFPoint::x, and MeaFPoint::y.
Referenced by AppView::LoadProfile().
MasterReset()
void MeaUnitsMgr::MasterReset ()
Called when the master application reset is initiated.
The units manager is reset to its default state.
References kDefAngularUnits, kDefHaveWarned, kDefInvertY, kDefLinearUnits, kDefSupplmentalAngle, m_angularUnitsMap, m_haveWarned, m_linearUnitsMap, SetAngularUnits(), SetInvertY(), SetLinearUnits(), SetOrigin(), and SetSupplementalAngle().
Referenced by AppView::MasterReset().
NewAngleUnitsLabel()
MeaAngularUnitsLabel * MeaUnitsMgr::NewAngleUnitsLabel ()
Creates a new angular measurement units label object.
Returns
Newly created angular measurement units label. When no longer needed, the object should be destroyed using the DeleteUnitsLabel method on the object.
References m_angularLabelsList.
Referenced by MeaDataDisplay::DataItem::CreateAngleUnits().
NewAreaUnitsLabel()
MeaAreaUnitsLabel * MeaUnitsMgr::NewAreaUnitsLabel ()
Creates a new area measurement units label object.
Returns
Newly created area measurement units label. When no longer needed, the object should be destroyed using the DeleteUnitsLabel method on the object.
References m_linearLabelsList.
Referenced by MeaDataDisplay::DataItem::CreateAreaUnits().
NewLengthUnitsLabel()
MeaLengthUnitsLabel * MeaUnitsMgr::NewLengthUnitsLabel ()
Creates a new length measurement units label object.
Returns
Newly created length measurement units label. When no longer needed, the object should be destroyed using the DeleteUnitsLabel method on the object.
References m_linearLabelsList.
Referenced by MeaDataDisplay::DataItem::CreateLengthUnits().
NewResUnitsLabel()
MeaResUnitsLabel * MeaUnitsMgr::NewResUnitsLabel ()
Creates a new resolution measurement units label object.
Returns
Newly created resolution measurement units label. When no longer needed, the object should be destroyed using the DeleteUnitsLabel method on the object.
References m_linearLabelsList.
Referenced by MeaDataDisplay::DataItem::CreateResUnits().
SaveProfile()
void MeaUnitsMgr::SaveProfile (MeaProfile & profile)
Persists the state of the units manager to the specified profile object.
Parameters
profile [in] Profile object into which the manager state is persisted.
References ConvertPos(), GetAngularUnitsStr(), GetLinearUnitsStr(), GetOrigin(), IsInvertY(), IsSupplementalAngle(), m_angularUnitsMap, m_haveWarned, m_linearUnitsMap, MeaProfile::UserInitiated(), MeaProfile::WriteBool(), MeaProfile::WriteStr(), MeaFPoint::x, and MeaFPoint::y.
Referenced by AppView::SaveProfile().
SetAngularDisplayPrecisions()
void MeaUnitsMgr::SetAngularDisplayPrecisions (MeaAngularUnitsId unitsId, const MeaUnits::DisplayPrecisions & precisions) inline
Set the number of decimal places to show on the data display for angular measurements in the specified units.
Parameters
unitsId [in] Identifier for the units whose precisions are to be set.
precisions [in] Array of decimal places.
References m_angularUnitsMap.
Referenced by AppView::ApplyPreferences().
SetAngularUnits() [1/2]
void MeaUnitsMgr::SetAngularUnits (MeaAngularUnitsId unitsId)
Sets the current angular measurement units based on the specified units identifier.
Parameters
unitsId [in] Measurement units identifier.
References m_angularLabelsList, m_angularUnitsMap, and m_currentAngularUnits.
Referenced by LoadProfile(), MasterReset(), AppView::OnAngles(), SetAngularUnits(), and MeaPositionLogMgr::ShowPosition().
SetAngularUnits() [2/2]
void MeaUnitsMgr::SetAngularUnits (PCTSTR unitsStr)
Sets the current angular measurement units based on the specified units identifier string (e.g.
"deg").
Parameters
unitsStr [in] Measurement units identifier.
References m_angularUnitsMap, and SetAngularUnits().
SetInvertY()
void MeaUnitsMgr::SetInvertY (bool invertY) const inline
By default, the Windows coordinate system is inverted from the typical Cartesian coordinate system in that the origin is located in the upper left corner of the primary screen and the positive y-axis points downward.
This method sets whether the y-axis should be inverted so that the origin is moved to the lower left corner of the primary screen and the positive y-axis points up. Note that the actual location of the origin is determined by the SetOrigin method.
Parameters
invertY [in] true inverts the y-axis, placing the origin at the lower left of the primary display screen and making positive y pointing upward.
References MeaLinearUnits::SetInvertY().
Referenced by LoadProfile(), MasterReset(), AppView::OnInvertY(), and MeaPositionLogMgr::ShowPosition().
SetLinearDisplayPrecisions()
void MeaUnitsMgr::SetLinearDisplayPrecisions (MeaLinearUnitsId unitsId, const MeaUnits::DisplayPrecisions & precisions) inline
Set the number of decimal places to show on the data display for all types of linear measurements in the specified units (e.g.
coordinates, length, area, etc.).
Parameters
unitsId [in] Identifier for the units whose precisions are to be set.
precisions [in] Array of decimal places for each measurement type.
References m_linearUnitsMap.
Referenced by AppView::ApplyPreferences().
SetLinearUnits() [1/2]
void MeaUnitsMgr::SetLinearUnits (MeaLinearUnitsId unitsId)
Sets the current linear measurement units based on the specified units identifier.
Parameters
unitsId [in] Measurement units identifier.
References MeaScreenMgr::AnyOSRes(), MeaSingleton_T< MeaScreenMgr >::Instance(), m_currentLinearUnits, m_haveWarned, m_linearLabelsList, m_linearUnitsMap, MeaShowCalPrefsMsg, MeaLinearUnits::RequiresRes(), and MeaScreenMgr::SizeChanged().
Referenced by AppView::ApplyPreferences(), LoadProfile(), MasterReset(), AppView::OnCustomUnits(), AppView::OnUnits(), SetLinearUnits(), and MeaPositionLogMgr::ShowPosition().
SetLinearUnits() [2/2]
void MeaUnitsMgr::SetLinearUnits (PCTSTR unitsStr)
Sets the current linear measurement units based on the specified units identifier string (e.g.
"in").
Parameters
unitsStr [in] Measurement units identifier string (e.g. "in").
References m_linearUnitsMap, and SetLinearUnits().
SetOrigin()
void MeaUnitsMgr::SetOrigin (const POINT & origin) const inline
Moves the origin of the coordinate system to the specified point.
The orientation of the axes is not effected by this method. To change the orientation of the y-axis use the SetInvertY method.
Parameters
origin [in] New location for the origin of the coordinate system. in pixels.
References MeaLinearUnits::SetOrigin().
Referenced by LoadProfile(), MasterReset(), AppView::OnOrigin(), AppView::OnResetOrigin(), and MeaPositionLogMgr::ShowPosition().
SetSupplementalAngle()
void MeaUnitsMgr::SetSupplementalAngle (boolean showSupplemental) inline
Sets whether to show the included angle (default) or the supplemental angle.
The supplemental angle is defined as:
Parameters
showSupplemental [in] true to show supplemental angle instead of included angle
References MeaAngularUnits::SetSupplementalAngle().
Referenced by LoadProfile(), MasterReset(), and AppView::OnSupplementalAngle().
UnconvertCoord()
POINT MeaUnitsMgr::UnconvertCoord (const MeaFPoint & pos) const inline
Converts from the current units to pixels.
The conversion takes into account the location of the origin and the orientation of the y-axis.
Parameters
pos [in] Coordinates to convert to pixels.
Returns
Coordinates converted from the current units to pixels. The conversion takes into account the location of the origin and the orientation of the y-axis.
References m_currentLinearUnits, and MeaLinearUnits::UnconvertCoord().
Referenced by MeaDataDisplay::OnFieldEntry(), and MeaPositionLogMgr::ShowPosition().
UnconvertPos()
POINT MeaUnitsMgr::UnconvertPos (const MeaFPoint & pos) const inline override virtual
Converts from the current units to pixels.
The conversion does not take into account the location of the origin nor the orientation of the y-axis.
Parameters
pos [in] Position to convert to pixels.
Returns
Position converted from the current units to pixels. The conversion does not take into account the location of the origin nor the orientation of the y-axis.
Implements MeaUnitsProvider.
References m_currentLinearUnits, and MeaLinearUnits::UnconvertPos().
Referenced by LoadProfile().
Member Data Documentation
kMinSepPixels
constexpr int MeaUnitsMgr::kMinSepPixels { 5 } static constexpr private
Minimum separation between ruler tick marks, in pixels.
Minimum separation between ruler tick marks, in inches.
Referenced by GetMinorIncr().
The documentation for this class was generated from the following files:
UnitsMgr.h
UnitsMgr.cpp
Copyright 2011 C Thing Software