Meazure: MeaWindowTool Class Reference
MeaWindowTool Class Reference
Window measurement tool.
#include <WindowTool.h>
Public Member Functions
MeaWindowTool (MeaToolMgr &mgr, const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Constructs a new instance of a Window measurement tool.
virtual ~MeaWindowTool ()
Hides and then destroys the Window tool.
virtual void Enable () override
Displays the Window tool.
virtual void Disable () override
Hides the Window tool.
virtual void Update (MeaUpdateReason reason) override
Requests that the tool update the display of the window data.
virtual bool HasCrosshairs () const override
Indicates whether the tool uses crosshairs.
virtual void Strobe () override
Visually strobes the tool.
virtual bool HasRegion () override
Indicates whether the tool can define a rectangular region that can then be read for a screen capture.
virtual RECT GetRegion () override
Returns the rectangle defined by the tool.
virtual void OnMouseHook (WPARAM wParam, LPARAM lParam) override
Called by the OS when the mouse pointer is moved.
virtual const POINT & GetPosition () const override
Returns the position of the mouse pointer.
virtual void RecordPosition (MeaPosition &position) const override
Records the position of the window rectangle.
virtual PCTSTR GetToolName () const override
Returns the name of the tool.
virtual UINT GetLabelId () const override
Returns a resource ID for the string used to label this tool on the data display.
virtual void ColorsChanged () override
Called to notify the tool that the colors in the MeaColors class have been changed.
Public Member Functions inherited from MeaRadioTool
MeaRadioTool (MeaToolMgr &mgr, const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Constructs a new instance of an radio based measurement tool.
virtual bool IsRadioTool () override
Indicates that the derived tool is a Radio tool and cannot be enabled until any other enabled Radio tool is disabled.
virtual UINT GetLabelId () const
Returns a resource ID for the string used to label this tool on the data display.
virtual bool HasCrosshairs () const
Indicates whether the derived tool uses crosshairs.
virtual void EnableCrosshairs ()
Displays the tool's crosshairs.
virtual void DisableCrosshairs ()
Hides the tool's crosshairs.
virtual void Flash ()
Visually flashes the tool.
virtual void Strobe ()
Visually strobes the tool.
virtual bool HasRegion ()
Indicates whether the tool can define a rectangular region that can then be read for a screen capture.
virtual RECT GetRegion ()
Returns the rectangle defined by the tool.
virtual void SetPosition (const PointMap &points)
Sets the position of the tool.
virtual void RecordPosition (MeaPosition &position) const =0
Records the position of the tool.
virtual void OnMouseHook (WPARAM wParam, LPARAM lParam)
Called by the OS when the mouse pointer is moved.
Public Member Functions inherited from MeaTool
MeaTool (MeaToolMgr &mgr, const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Base class constructor.
virtual ~MeaTool ()=default
Destroys the tool.
virtual void Enable ()
Typically used by derived classes to show the tool.
virtual void Disable ()
Typically used by derived classes to hide the tool.
virtual void Update (MeaUpdateReason reason)
Used by derived classes to update the display of their data.
virtual bool IsRadioTool ()
Indicates whether the derived tool is a radio tool and cannot be enabled until any other enabled Radio tool is disabled.
virtual void SetPosition (MeaDataFieldId which, int pixels)
Sets the position of the tool.
virtual const POINT & GetPosition () const =0
Returns the tool's current position.
virtual void IncPosition (MeaDataFieldId which)
Increments the specified position field.
virtual void DecPosition (MeaDataFieldId which)
Decrements the specified position field.
virtual PCTSTR GetToolName () const =0
Returns the name of the tool.
virtual void SaveProfile (MeaProfile &profile)
Persists the state of the tool to the specified profile object.
virtual void LoadProfile (MeaProfile &profile)
Restores the state of the tool from the specified profile object.
virtual void MasterReset ()
Resets the tool to its default state.
virtual void ColorsChanged ()
Called to notify the tool that the colors in the MeaColors class have been changed.
bool IsEnabled () const
Indicates whether the tool is enabled.
Static Public Attributes
static constexpr PCTSTR kToolName { _T("WindowTool") }
Private Member Functions
void Create ()
Creates the tool's graphical components.
bool FindWindow ()
Attempts to locate a window under the mouse pointer.
Static Private Member Functions
static BOOL CALLBACK EnumChildProc (HWND hwnd, LPARAM lParam)
Called by the win32 EnumChildWindows function when it enumerates child windows.
Private Attributes
CPoint m_pointerPos
Cached position of the mouse pointer, in pixels.
CPoint m_point1
Upper left position of the window rectangle.
CPoint m_point2
Lower right position of the window rectangle.
MeaRectangle m_rectangle
Window highlight rectangle.
HWND m_currentWnd
Window currently highlighted.
HWND m_hiliteWnd
Window to highlight.
MeaDataWin m_dataWin
Data window tooltip.
Additional Inherited Members
Public Types inherited from MeaRadioTool
typedef std::map< CString, POINT > PointMap
Map of points used to set the position of a tool.
Protected Attributes inherited from MeaTool
MeaToolMgr & m_mgr
Tool manager.
const MeaScreenProvider & m_screenProvider
Screen information provider.
const MeaUnitsProvider & m_unitsProvider
Units information provider.
bool m_enabled
Indicates whether the tool is enabled.
Static Protected Attributes inherited from MeaTool
static const CPoint m_defaultPos
A default position used by tools that do not have a defined position.
Detailed Description
Window measurement tool.
This tool tracks the mouse pointer and attempts to identify the deepest window in the window hierarchy under the pointer. the dimensions of that window are displayed. The tool consists of a rectangle that is used to highlight the window selected for measurement. In addition, a data window is attached to the rectangle to provide a measurement information popup.
Constructor & Destructor Documentation
MeaWindowTool()
MeaWindowTool::MeaWindowTool (MeaToolMgr & mgr, const MeaScreenProvider & screenProvider, const MeaUnitsProvider & unitsProvider) explicit
Constructs a new instance of a Window measurement tool.
To use a newly constructed Window tool, the Enable() method must be called. Enable() will call the Create() method the first time it is called if Create() has not previously been called.
Parameters
mgr [in] Tool manager parent of the Window tool.
screenProvider [in] Screen information provider
unitsProvider [in] Units information provider
Member Function Documentation
ColorsChanged()
void MeaWindowTool::ColorsChanged () override virtual
Called to notify the tool that the colors in the MeaColors class have been changed.
The window rectangle color and the data window opacity are updated.
Reimplemented from MeaTool.
References MeaColors::CrossHairOpacity, MeaColors::Get(), MeaColors::GetA(), MeaColors::LineFore, m_dataWin, m_rectangle, MeaRectangle::SetColor(), and MeaDataWin::SetOpacity().
Create()
void MeaWindowTool::Create () private
Creates the tool's graphical components.
The components include the window rectangle and the data window. The Enable() method must be called to make the tool visible.
References MeaDataWin::Create(), MeaColors::CrossHairOpacity, MeaColors::GetA(), and m_dataWin.
Referenced by Enable().
Disable()
void MeaWindowTool::Disable () override virtual
Hides the Window tool.
Reimplemented from MeaTool.
References MeaTool::Disable(), MeaDataWin::Hide(), MeaRectangle::Hide(), MeaTool::IsEnabled(), m_dataWin, m_rectangle, and MeaDisableMouseHook().
Referenced by ~MeaWindowTool().
Enable()
void MeaWindowTool::Enable () override virtual
Displays the Window tool.
If the Create() method has not been previously called, it will be called by Enable.
Reimplemented from MeaTool.
References Create(), MeaRectangle::Create(), MeaTool::Enable(), MeaToolMgr::EnableRegionFields(), MeaTool::IsEnabled(), m_currentWnd, m_dataWin, MeaTool::m_mgr, m_point1, m_point2, m_rectangle, MeaAngleField, MeaAreaField, MeaAspectField, MeaDistanceField, MeaEnableMouseHook(), MeaHeightField, MeaWidthField, MeaX1Field, MeaX2Field, MeaY1Field, MeaY2Field, NormalUpdate, MeaRectangle::SetPosition(), MeaToolMgr::SetStatus(), MeaGraphic::Show(), MeaDataWin::Show(), and Update().
EnumChildProc()
BOOL CALLBACK MeaWindowTool::EnumChildProc (HWND hwnd, LPARAM lParam) static private
Called by the win32 EnumChildWindows function when it enumerates child windows.
Also tests to see if the child window is under the cursor.
Parameters
hwnd [in] Child window to test
lParam [in] this pointer
Returns
TRUE if enumeration should continue.
References m_hiliteWnd.
Referenced by FindWindow().
FindWindow()
bool MeaWindowTool::FindWindow () private
Attempts to locate a window under the mouse pointer.
The window hierarchy is searched to identify the deepest window in the hierarchy.
Returns
true if the pointer has moved over a new window.
References EnumChildProc(), m_currentWnd, m_hiliteWnd, m_point1, m_point2, m_pointerPos, and m_rectangle.
Referenced by OnMouseHook().
GetLabelId()
UINT MeaWindowTool::GetLabelId () const override virtual
Returns a resource ID for the string used to label this tool on the data display.
Returns
Resource ID for the label.
Reimplemented from MeaRadioTool.
GetPosition()
const POINT & MeaWindowTool::GetPosition () const override virtual
Returns the position of the mouse pointer.
Returns
Position of the mouse pointer.
Implements MeaTool.
References m_pointerPos.
GetRegion()
RECT MeaWindowTool::GetRegion () override virtual
Returns the rectangle defined by the tool.
This rectangle can then be read for a screen capture.
Returns
The rectangle formed by the tool.
Reimplemented from MeaRadioTool.
References m_point1, and m_point2.
Referenced by HasRegion().
GetToolName()
PCTSTR MeaWindowTool::GetToolName () const override virtual
Returns the name of the tool.
Each tool has a unique name which is used to identify the tool in profiles and position logs.
Returns
Always "WindowTool". The memory for the string is owned by the tool.
Implements MeaTool.
HasCrosshairs()
bool MeaWindowTool::HasCrosshairs () const override virtual
Indicates whether the tool uses crosshairs.
The Window tool does not use crosshairs.
Returns
For this class this method always returns false.
Reimplemented from MeaRadioTool.
HasRegion()
bool MeaWindowTool::HasRegion () override virtual
Indicates whether the tool can define a rectangular region that can then be read for a screen capture.
The Window tool defines such a rectangular area.
Returns
true if the tool defines a non-empty rectangular region.
Reimplemented from MeaRadioTool.
References GetRegion().
OnMouseHook()
void MeaWindowTool::OnMouseHook (WPARAM wParam, LPARAM lParam) override virtual
Called by the OS when the mouse pointer is moved.
Via this method the window under the pointer is identified.
Parameters
wParam [in] OS Message ID
lParam [in] MOUSEHOOKSTRUCT
Reimplemented from MeaRadioTool.
References FindWindow(), m_point1, m_point2, m_pointerPos, m_rectangle, NormalUpdate, MeaRectangle::SetPosition(), and Update().
RecordPosition()
void MeaWindowTool::RecordPosition (MeaPosition & position) const override virtual
Records the position of the window rectangle.
This method is called by the position log manager to record a position.
Parameters
position [in] The position of the window rectangle is recorded into the position log manager's position object.
Implements MeaRadioTool.
References MeaGeometry::CalcAngle(), MeaUnitsProvider::ConvertAngle(), MeaUnitsProvider::ConvertCoord(), MeaUnitsProvider::GetWidthHeight(), m_point1, m_point2, MeaTool::m_unitsProvider, MeaPosition::RecordAngle(), MeaPosition::RecordDistance(), MeaPosition::RecordRectArea(), MeaPosition::RecordWH(), MeaPosition::RecordXY1(), MeaPosition::RecordXY2(), and MeaPosition::SetToolName().
Strobe()
void MeaWindowTool::Strobe () override virtual
Visually strobes the tool.
The tool data window attached to the window rectangle is cycled between hidden and visible. Strobing the tool is done to visually confirm region capture and position recording.
Reimplemented from MeaRadioTool.
References m_dataWin, and MeaDataWin::Strobe().
Update()
void MeaWindowTool::Update (MeaUpdateReason reason) override virtual
Requests that the tool update the display of the window data.
Parameters
reason [in] Reason why the update has been requested
Reimplemented from MeaTool.
References AllChanged, MeaGeometry::CalcAngle(), MeaUnitsProvider::ConvertCoord(), DataWinArming, MeaUnitsProvider::GetWidthHeight(), MeaDataWin::Hide(), MeaDataWin::IsArmed(), MeaTool::IsEnabled(), m_currentWnd, m_dataWin, MeaTool::m_mgr, m_point1, m_point2, m_pointerPos, MeaTool::m_unitsProvider, OriginChanged, MeaDataWin::Show(), MeaToolMgr::ShowAngle(), MeaToolMgr::ShowAspect(), MeaToolMgr::ShowDistance(), MeaToolMgr::ShowRectArea(), MeaToolMgr::ShowWH(), MeaDataWin::ShowWH(), MeaToolMgr::ShowXY1(), MeaToolMgr::ShowXY2(), UnitsChanged, MeaDataWin::Update(), MeaTool::Update(), and MeaToolMgr::UpdateScreenInfo().
Referenced by Enable(), and OnMouseHook().
The documentation for this class was generated from the following files:
WindowTool.h
WindowTool.cpp
Copyright 2011 C Thing Software