Meazure: MeaPrecisionPrefs Class Reference
MeaPrecisionPrefs Class Reference
Property page for setting display precisions for each set of measurement units.
#include <PrecisionPrefs.h>
Public Types
enum { IDD = IDD_PREF_PRECISION }
Public Member Functions
MeaPrecisionPrefs ()
Constructs an instance of the precision property page.
~MeaPrecisionPrefs ()
Destroys an instance of the precision property page.
void SetLinearPrecisions (MeaLinearUnitsId unitsId, const MeaUnits::DisplayPrecisions &precisions)
Sets the display precisions for the specified linear measurement units.
void SetAngularPrecisions (MeaAngularUnitsId unitsId, const MeaUnits::DisplayPrecisions &precisions)
Sets the display precisions for the specified angular measurement units.
const MeaUnits::DisplayPrecisions & GetLinearPrecisions (MeaLinearUnitsId unitsId)
Obtains the display precisions for the specified linear measurement units.
const MeaUnits::DisplayPrecisions & GetAngularPrecisions (MeaAngularUnitsId unitsId)
Obtains the display precisions for the specified angular measurement units.
void SelectCustomUnits ()
Called by the custom units property page when the display precision button on that page is pressed.
virtual BOOL OnInitDialog ()
Called when the property page is created.
Protected Member Functions
virtual void DoDataExchange (CDataExchange *pDX)
Performs Dynamic Data Exchange (DDX) for the page.
afx_msg void OnCm ()
Called when the centimeter radio button is pressed.
afx_msg void OnCustom ()
Called when the custom units radio button is pressed.
afx_msg void OnDeg ()
Called when the degrees radio button is pressed.
afx_msg void OnIn ()
Called when the inches radio button is pressed.
afx_msg void OnMm ()
Called when the millimeters radio button is pressed.
afx_msg void OnPc ()
Called when the picas radio button is pressed.
afx_msg void OnPt ()
Called when the points radio button is pressed.
afx_msg void OnPx ()
Called when the pixels radio button is pressed.
afx_msg void OnRad ()
Called when the radians radio button is pressed.
afx_msg void OnTp ()
Called when the twips radio button is pressed.
afx_msg void OnKillFocusA ()
Called when the input focus is lost from the angle text field.
afx_msg void OnKillFocusAr ()
Called when the input focus is lost from the area text field.
afx_msg void OnKillFocusD ()
Called when the input focus is lost from the distance text field.
afx_msg void OnKillFocusH ()
Called when the input focus is lost from the height text field.
afx_msg void OnKillFocusRx ()
Called when the input focus is lost from the x-axis resolution text field.
afx_msg void OnKillFocusRy ()
Called when the input focus is lost from the y-axis resolution text field.
afx_msg void OnKillFocusW ()
Called when the input focus is lost from the width text field.
afx_msg void OnKillFocusX ()
Called when the input focus is lost from the x position text field.
afx_msg void OnKillFocusY ()
Called when the input focus is lost from the y position text field.
afx_msg void OnDefault ()
Called when the Default button is pressed.
afx_msg void OnChange ()
Called when any display precision values are changed so that the modified flag can be set.
Private Types
typedef std::map< int, CStatic * > Labels
Maps a measurement ID to a label control.
typedef std::map< int,
MeaNumberField * > Fields
Maps a measurement ID to a numeric text field.
typedef std::map< int,
CSpinButtonCtrl * > Spins
Maps a measurement ID to the spin control on a text field.
typedef std::map< int,
MeaUnits::DisplayPrecisions > Precisions
Maps a measurement ID to a set of display precisions.
Private Member Functions
MeaPrecisionPrefs (const MeaPrecisionPrefs &)
Purposely undefined.
MeaPrecisionPrefs & operator= (const MeaPrecisionPrefs &)
Purposely undefined.
void SetCheck (UINT buttonId) const
Ensures radio button behavior among the units radio buttons.
void ShowLinearPrecisions ()
Enables the linear units controls, disables the angular units controls, and displays the precision values for the currently selected linear units.
void ShowAngularPrecisions ()
Enables the angular units controls, disables the linear units controls, and displays the precision values for the currently selected angular units.
void EnableLinearDisplay (bool enable)
Enables or disables the linear units controls.
void EnableAngularDisplay (bool enable)
Enables or disables the angular units controls.
void UpdateLinearDisplay ()
Redisplays the display precisions for the currently selected linear units.
void UpdateAngularDisplay ()
Redisplays the display precisions for the currently selected angular units.
int GetLinearValue (MeaLinearMeasurementId id)
Obtains the value in the specified linear measurement text field, validates it, and returns it.
int GetAngularValue (MeaAngularMeasurementId id)
Obtains the value in the specified angular measurement text field, validates it, and returns it.
int GetValue (MeaNumberField *field)
Obtains the value in the specified measurement text field, validates it, and returns it.
Private Attributes
Precisions m_linearPrecisions
Precisions for all linear measurements.
Precisions m_angularPrecisions
Precisions for all angular measurements.
Labels m_linearLabels
Labels for all linear measurements.
Labels m_angularLabels
Labels for all angular measurements.
Fields m_linearFields
Text fields for all linear measurements.
Fields m_angularFields
Text fields for all angular measurements.
Spins m_linearSpins
Spin controls for all linear measurements.
Spins m_angularSpins
Spin controls for all angular measurements.
MeaLinearUnitsId m_curLinearUnitsId
ID of the currently selected linear units.
MeaAngularUnitsId m_curAngularUnitsId
ID of the currently selected angular units.
bool m_lockout
Prevents circular notification of text field changes.
Static Private Attributes
static const int kMaxPlaces = 6
Maximum allowable number of decimal places.
Detailed Description
Property page for setting display precisions for each set of measurement units.
Each measurement unit has associated with it a set of display precisions, one for each measurement (e.g. width, height, x, y).
Member Function Documentation
MeaPrecisionPrefs::DoDataExchange (CDataExchange * pDX) [protected, virtual]
Performs Dynamic Data Exchange (DDX) for the page.
Parameters:
pDX [in] DDX object for exchanging data between the page UI and the member variables.
const MeaUnits::DisplayPrecisions& MeaPrecisionPrefs::GetAngularPrecisions (MeaAngularUnitsId unitsId) [inline]
Obtains the display precisions for the specified angular measurement units.
Parameters:
unitsId [in] Angular units whose precisions are to be obtained.
Returns:
Set of display precisions for the specified units.
References m_angularPrecisions.
Referenced by CChildView::ApplyPreferences().
int MeaPrecisionPrefs::GetAngularValue (MeaAngularMeasurementId id) [inline, private]
Obtains the value in the specified angular measurement text field, validates it, and returns it.
Parameters:
id [in] ID of the angular measurement precision text field.
Returns:
Value from the text field.
References GetValue(), and m_angularFields.
Referenced by OnKillFocusA().
const MeaUnits::DisplayPrecisions& MeaPrecisionPrefs::GetLinearPrecisions (MeaLinearUnitsId unitsId) [inline]
Obtains the display precisions for the specified linear measurement units.
Parameters:
unitsId [in] Linear units whose precisions are to be obtained.
Returns:
Set of display precisions for the specified units.
References m_linearPrecisions.
Referenced by CChildView::ApplyPreferences().
int MeaPrecisionPrefs::GetLinearValue (MeaLinearMeasurementId id) [inline, private]
Obtains the value in the specified linear measurement text field, validates it, and returns it.
Parameters:
id [in] ID of the linear measurement precision text field.
Returns:
Value from the text field.
References GetValue(), and m_linearFields.
Referenced by OnKillFocusAr(), OnKillFocusD(), OnKillFocusH(), OnKillFocusRx(), OnKillFocusRy(), OnKillFocusW(), OnKillFocusX(), and OnKillFocusY().
int MeaPrecisionPrefs::GetValue (MeaNumberField * field) [private]
Obtains the value in the specified measurement text field, validates it, and returns it.
Parameters:
field [in] Measurement precision text field.
Returns:
Value from the text field.
References MeaNumberField::GetValue(), kMaxPlaces, and MeaNumberField::SetValue().
Referenced by GetAngularValue(), and GetLinearValue().
MeaPrecisionPrefs::OnChange () [protected]
Called when any display precision values are changed so that the modified flag can be set.
References m_lockout.
Referenced by OnDefault().
MeaPrecisionPrefs::OnCm () [protected]
Called when the centimeter radio button is pressed.
References m_curLinearUnitsId, MeaCentimetersId, and ShowLinearPrecisions().
MeaPrecisionPrefs::OnCustom () [protected]
Called when the custom units radio button is pressed.
References m_curLinearUnitsId, MeaCustomId, and ShowLinearPrecisions().
MeaPrecisionPrefs::OnDefault () [protected]
Called when the Default button is pressed.
References MeaUnitsMgr::GetAngularDefaultPrecisions(), MeaUnitsMgr::GetLinearDefaultPrecisions(), MeaSingleton_T< MeaUnitsMgr >::Instance(), m_angularPrecisions, m_curAngularUnitsId, m_curLinearUnitsId, m_linearPrecisions, OnChange(), UpdateAngularDisplay(), and UpdateLinearDisplay().
MeaPrecisionPrefs::OnDeg () [protected]
Called when the degrees radio button is pressed.
References m_curAngularUnitsId, MeaDegreesId, and ShowAngularPrecisions().
MeaPrecisionPrefs::OnIn () [protected]
Called when the inches radio button is pressed.
References m_curLinearUnitsId, MeaInchesId, and ShowLinearPrecisions().
BOOL MeaPrecisionPrefs::OnInitDialog () [virtual]
Called when the property page is created.
This method subclasses a number of controls on the page, with our implementations.
Returns:
TRUE, indicating that the input focus should be set to the first control on the page.
References MeaUnitsMgr::GetAngularUnitsId(), MeaUnitsMgr::GetLinearUnitsId(), MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaNumberField::IntValues, kMaxPlaces, log10(), m_angularFields, m_angularLabels, m_angularSpins, m_curAngularUnitsId, m_curLinearUnitsId, m_linearFields, m_linearLabels, m_linearSpins, MeaA, MeaAr, MeaCentimetersId, MeaCustomId, MeaD, MeaDegreesId, MeaH, MeaInchesId, MeaMillimetersId, MeaPicasId, MeaPixelsId, MeaPointsId, MeaRx, MeaRy, MeaTwipsId, MeaW, MeaX, MeaY, MeaNumberField::PosValues, SetCheck(), ShowLinearPrecisions(), and UpdateAngularDisplay().
MeaPrecisionPrefs::OnKillFocusA () [protected]
Called when the input focus is lost from the angle text field.
When the input focus is lost, the value in the text field is set.
References GetAngularValue(), m_angularPrecisions, m_curAngularUnitsId, and MeaA.
MeaPrecisionPrefs::OnKillFocusAr () [protected]
Called when the input focus is lost from the area text field.
When the input focus is lost, the value in the text field is set.
References GetLinearValue(), m_curLinearUnitsId, m_linearPrecisions, and MeaAr.
MeaPrecisionPrefs::OnKillFocusD () [protected]
Called when the input focus is lost from the distance text field.
When the input focus is lost, the value in the text field is set.
References GetLinearValue(), m_curLinearUnitsId, m_linearPrecisions, and MeaD.
MeaPrecisionPrefs::OnKillFocusH () [protected]
Called when the input focus is lost from the height text field.
When the input focus is lost, the value in the text field is set.
References GetLinearValue(), m_curLinearUnitsId, m_linearPrecisions, and MeaH.
MeaPrecisionPrefs::OnKillFocusRx () [protected]
Called when the input focus is lost from the x-axis resolution text field.
When the input focus is lost, the value in the text field is set.
References GetLinearValue(), m_curLinearUnitsId, m_linearPrecisions, and MeaRx.
MeaPrecisionPrefs::OnKillFocusRy () [protected]
Called when the input focus is lost from the y-axis resolution text field.
When the input focus is lost, the value in the text field is set.
References GetLinearValue(), m_curLinearUnitsId, m_linearPrecisions, and MeaRy.
MeaPrecisionPrefs::OnKillFocusW () [protected]
Called when the input focus is lost from the width text field.
When the input focus is lost, the value in the text field is set.
References GetLinearValue(), m_curLinearUnitsId, m_linearPrecisions, and MeaW.
MeaPrecisionPrefs::OnKillFocusX () [protected]
Called when the input focus is lost from the x position text field.
When the input focus is lost, the value in the text field is set.
References GetLinearValue(), m_curLinearUnitsId, m_linearPrecisions, and MeaX.
MeaPrecisionPrefs::OnKillFocusY () [protected]
Called when the input focus is lost from the y position text field.
When the input focus is lost, the value in the text field is set.
References GetLinearValue(), m_curLinearUnitsId, m_linearPrecisions, and MeaY.
MeaPrecisionPrefs::OnMm () [protected]
Called when the millimeters radio button is pressed.
References m_curLinearUnitsId, MeaMillimetersId, and ShowLinearPrecisions().
MeaPrecisionPrefs::OnPc () [protected]
Called when the picas radio button is pressed.
References m_curLinearUnitsId, MeaPicasId, and ShowLinearPrecisions().
MeaPrecisionPrefs::OnPt () [protected]
Called when the points radio button is pressed.
References m_curLinearUnitsId, MeaPointsId, and ShowLinearPrecisions().
MeaPrecisionPrefs::OnPx () [protected]
Called when the pixels radio button is pressed.
References m_curLinearUnitsId, MeaPixelsId, and ShowLinearPrecisions().
MeaPrecisionPrefs::OnRad () [protected]
Called when the radians radio button is pressed.
References m_curAngularUnitsId, MeaRadiansId, and ShowAngularPrecisions().
MeaPrecisionPrefs::OnTp () [protected]
Called when the twips radio button is pressed.
References m_curLinearUnitsId, MeaTwipsId, and ShowLinearPrecisions().
void MeaPrecisionPrefs::SelectCustomUnits ()
Called by the custom units property page when the display precision button on that page is pressed.
This method selects the custom units display precisions.
References m_curLinearUnitsId, MeaCustomId, SetCheck(), ShowLinearPrecisions(), and UpdateAngularDisplay().
Referenced by MeaPreferences::ShowCustomPrecision().
void MeaPrecisionPrefs::SetAngularPrecisions (MeaAngularUnitsId unitsId, const MeaUnits::DisplayPrecisions & precisions) [inline]
Sets the display precisions for the specified angular measurement units.
Parameters:
unitsId [in] Angular units whose precisions are being set.
precisions [in] Set of display precisions for the specified units.
References m_angularPrecisions.
Referenced by CChildView::OnPreferences().
void MeaPrecisionPrefs::SetCheck (UINT buttonId) const [private]
Ensures radio button behavior among the units radio buttons.
That is, when the specified button is set, all other buttons in the radio group are unset.
Parameters:
buttonId [in] Radio button to set.
Referenced by OnInitDialog(), and SelectCustomUnits().
void MeaPrecisionPrefs::SetLinearPrecisions (MeaLinearUnitsId unitsId, const MeaUnits::DisplayPrecisions & precisions) [inline]
Sets the display precisions for the specified linear measurement units.
Parameters:
unitsId [in] Linear units whose precisions are being set.
precisions [in] Set of display precisions for the specified units.
References m_linearPrecisions.
Referenced by CChildView::OnPreferences().
The documentation for this class was generated from the following files:
PrecisionPrefs.h
PrecisionPrefs.cpp
Copyright 2011 C Thing Software