Meazure: MeaCrossHair Class Reference
MeaCrossHair Class Reference
A crosshair element.
#include <CrossHair.h>
Public Member Functions
MeaCrossHair ()
Constructs a crosshair.
virtual ~MeaCrossHair ()
Destroys the circle.
bool Create (COLORREF borderColor, COLORREF backColor, COLORREF hiliteColor, BYTE opacity, MeaCrossHairCallback *callback, const CWnd *parent=NULL, UINT toolTipId=0xffff, UINT id=0xffff)
Creates the window for the crosshair.
void Flash (int flashCount=kFlashCount)
Visually flashes the crosshair by cycling its background between normal and hilited the number of times specified.
void SetPosition (const POINT &center)
Sets the position of the crosshair.
void SetColors (COLORREF borderColor, COLORREF backColor, COLORREF hiliteColor)
Sets the colors for the crosshair.
void SetOpacity (BYTE opacity)
Sets the opacity for the crosshair.
virtual BOOL PreTranslateMessage (MSG *pMsg)
Relays messages to the crosshair's tooltip.
Public Member Functions inherited from MeaGraphic
MeaGraphic ()
Base class constructor.
virtual ~MeaGraphic ()
Base class destructor.
bool Create (LPCTSTR classname, const SIZE &size, const CWnd *parent, UINT id=0xFFFF)
Creates the window for the graphic.
virtual void Show ()
Displays the graphic.
virtual void Hide ()
Hides the graphic.
void SetAbove (const CWnd *winBelow)
Changes the z-order of the graphic window so that it if above the specified window.
Static Public Attributes
static const int kFlashCount = 9
Number of times to flash the crosshair when Flash() is called.
static const int kStrobeCount = 1
Number of times to flash the crosshair when Strobe() is called.
Protected Member Functions
afx_msg void OnDestroy ()
Called when the crosshair window is about to be destroyed.
afx_msg void OnPaint ()
Called when the crosshair needs repainting.
afx_msg void OnMouseMove (UINT flags, CPoint point)
Called when the crosshair is dragged.
afx_msg LRESULT OnMouseLeave (WPARAM wParam, LPARAM lParam)
Called when the pointer leaves the crosshair window.
afx_msg void OnLButtonDown (UINT flags, CPoint point)
Called when the left mouse button is pressed while the pointer is over the crosshair window.
afx_msg void OnLButtonUp (UINT flags, CPoint point)
Called when the left mouse button is released while the pointer is captured by the crosshair window.
afx_msg void OnTimer (UINT_PTR timerId)
Called when the crosshair is cycling between normal and hilited display as a result of a call to the Flash() method.
Private Types
enum DrawState {
Normal ,
Inverted
}
Specifies how to draw the crosshair (i.e.
Private Member Functions
void SetRegion ()
Forms the window into the shape of the crosshair.
void DrawCrossHair (CDC &dc)
Draws the crosshair background and border.
void DestroyColors ()
Deletes the brushes used to draw the crosshair's background and border.
void FillInfo (MeaCrossHairCallback::CHInfo &chs, UINT flags, const CPoint &point)
Fills in the crosshair information structure with the current location of the pointer and the state of the keyboard modifiers.
Static Private Member Functions
static CPoint GetLeftTop (const CPoint &center)
Given the center of the crosshair, returns the corresponding upper left corner.
Private Attributes
MeaCrossHairCallback * m_callback
Object to call for crosshair events.
bool m_mouseCaptured
Indicates if the pointer is captured.
bool m_mouseOver
Indicates if the pointer is over the crosshair.
CBrush * m_backBrush
Brush to paint the normal crosshair background.
CBrush * m_borderBrush
Brush to paint the crosshair border.
CBrush * m_hiliteBrush
Brush to paint the hilited crosshair background.
CSize m_pointerOffset
Offset from the pointer location in the window to the center of the crosshair.
DrawState m_drawState
Indicates how the crosshair should be drawn.
int m_flashCount
Number of times to flash the crosshair.
CToolTipCtrl m_toolTip
Tooltip associated with the crosshair.
BYTE m_opacity
Opacity of the crosshair (0 - transparent, 255 - opaque)
CDC m_chDC
Crosshair device context.
CDC m_backDC
Background device context for alpha blending when the crosshair is a child window.
CBitmap m_chBitmap
Bitmap into which to draw the crosshair when it is a child window.
CBitmap * m_origCHBitmap
Original bitmap for the crosshair.
CBitmap m_backBitmap
Bitmap for the background when alpha blending when the crosshair is a child window.
CBitmap * m_origBackBitmap
Original background bitmap.
Static Private Attributes
static SIZE m_size
Width and height of the crosshair, in pixels.
static SIZE m_halfSize
Half the width and height of the crosshair, in pixels.
static SIZE m_spread
Half the length of the base of a triangular section of the crosshair, in pixels.
static UINT m_flashInterval = 100
Number of milliseconds to hold each display state while flashing the crosshair.
static int * m_numCoords = NULL
Number of coordinates in each rectangle making up part of the crosshair (4)
Additional Inherited Members
Protected Attributes inherited from MeaGraphic
UINT m_id
ID for the graphic.
bool m_visible
Indicates whether the graphic is shown or hidden.
const CWnd * m_parent
Graphic's parent window or NULL if graphic is a popup window.
Static Protected Attributes inherited from MeaGraphic
static const int kInitCoord = -1000
An arbitrary initial coordinate for placing new graphics.
Detailed Description
A crosshair element.
A crosshair consists of four triangular window segments arranged vertically and horizontally such that each triangle is aimed at a center point. The crosshair is used by a number of the measurement tools to identify their measurement points and to allow the user to perform measurements by dragging the crosshairs using the pointer.
Member Enumeration Documentation
DrawState
enum MeaCrossHair::DrawState private
Specifies how to draw the crosshair (i.e.
normally or inverted).
Enumerator
Normal
Draw the crosshair in its normal appearance.
Inverted
Draw the crosshair in its inverted appearance.
Constructor & Destructor Documentation
MeaCrossHair()
MeaCrossHair::MeaCrossHair ()
Constructs a crosshair.
Prior to displaying the crosshair with the Show() method, the Create() method must be called to create the crosshair's window.
Member Function Documentation
Create()
bool MeaCrossHair::Create (COLORREF borderColor, COLORREF backColor, COLORREF hiliteColor, BYTE opacity, MeaCrossHairCallback * callback, const CWnd * parent = NULL, UINT toolTipId = 0xffff, UINT id = 0xffff)
Creates the window for the crosshair.
This method must be called before the crosshair can be displayed and before any operation that attempts to manipulate the crosshair's window.
Parameters
borderColor [in] The color for the crosshair border lines. The border lines are drawn around each triangular section of the crosshair.
backColor [in] Background color for the crosshair. Each triangular section of the crosshair is drawn in the background color. The crosshair is displayed in the background color when the pointer is not over the crosshair.
hiliteColor [in] Background color for the crosshair when the pointer is over the crosshair.
opacity [in] Opacity value for the crosshair expressed as a value between 0 (transparent) and 255 (opaque) inclusive.
callback [in] A class derived from MeaCrossHairCallback that wants to receive notification of crosshair events. Can be set to NULL if no callback is desired.
parent [in] Parent window or NULL if the crosshair does not have an immediate parent. If a parent window is specified, the crosshair is created as a child window (WS_CHILD). Otherwise the crosshair is created as a popup window (WS_POPUP) and is assigned the main window as a parent.
toolTipId [in] String resource ID for the tooltip associated with the crosshair.
id [in] Caller-defined ID for the crosshair.
Returns
true if the window is created successfully.
References MeaUnitsMgr::ConvertToPixels(), MeaGraphic::Create(), MeaLayout::DrawOpacityBackground(), MeaScreenMgr::GetScreenIter(), MeaScreenMgr::GetScreenRes(), HaveLayeredWindows(), MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaSingleton_T< MeaScreenMgr >::Instance(), m_backBitmap, m_backBrush, m_backDC, m_callback, m_chBitmap, m_chDC, m_halfSize, m_origBackBitmap, m_origCHBitmap, MeaGraphic::m_parent, m_size, m_spread, m_toolTip, MeaAssert, MeaInchesId, SetColors(), SetOpacity(), SetRegion(), and WS_EX_LAYERED.
Referenced by MeaAngleTool::Create(), MeaCircleTool::Create(), MeaLineTool::Create(), MeaPointTool::Create(), MeaRectTool::Create(), and MeaToolsPrefs::OnInitDialog().
DrawCrossHair()
void MeaCrossHair::DrawCrossHair (CDC & dc) private
Draws the crosshair background and border.
Before this method is called, the shape of the crosshair has already been set by the SetRegion() method. The DrawCrossHair() method simply draws the appropriate background color and frames the window's region. The background color depends on whether the crosshair is in a hilite state or not.
Parameters
dc [in] Device context into which the crosshair is drawn
References m_backBrush, m_borderBrush, m_drawState, m_hiliteBrush, m_mouseOver, and Normal.
Referenced by OnPaint().
FillInfo()
void MeaCrossHair::FillInfo (MeaCrossHairCallback::CHInfo & chs, UINT flags, const CPoint & point) private
Fills in the crosshair information structure with the current location of the pointer and the state of the keyboard modifiers.
Parameters
chs [in, out] Crosshair information structure to fill
flags [in] State of the keyboard modifier keys
point [in] Current location of the pointer, in pixels
References MeaCrossHairCallback::CHInfo::centerPoint, MeaCrossHairCallback::CHInfo::ch, MeaCrossHairCallback::CHInfo::flags, MeaCrossHairCallback::CHInfo::id, MeaSingleton_T< MeaScreenMgr >::Instance(), MeaScreenMgr::LimitPosition(), m_halfSize, MeaGraphic::m_id, and m_pointerOffset.
Referenced by OnLButtonDown(), OnLButtonUp(), OnMouseLeave(), and OnMouseMove().
Flash()
void MeaCrossHair::Flash (int flashCount = kFlashCount)
Visually flashes the crosshair by cycling its background between normal and hilited the number of times specified.
Parameters
flashCount [in] Number of times to cycle the crosshair background.
References Inverted, m_drawState, m_flashCount, and m_flashInterval.
Referenced by MeaAngleTool::Flash(), MeaCircleTool::Flash(), MeaLineTool::Flash(), MeaPointTool::Flash(), MeaRectTool::Flash(), MeaAngleTool::Strobe(), MeaCircleTool::Strobe(), MeaLineTool::Strobe(), MeaPointTool::Strobe(), and MeaRectTool::Strobe().
GetLeftTop()
static CPoint MeaCrossHair::GetLeftTop (const CPoint & center) inline static private
Given the center of the crosshair, returns the corresponding upper left corner.
Parameters
center [in] Location of the center of the crosshair, in pixels
Returns
Location of the upper left corner of the crosshair window, in pixels.
References m_halfSize.
Referenced by SetPosition().
OnDestroy()
void MeaCrossHair::OnDestroy () protected
Called when the crosshair window is about to be destroyed.
If the crosshair was created with a parent window specified, a number of bitmaps were created to simulate an opacity effect. This method deletes those bitmaps.
References DestroyColors(), m_backBitmap, m_backDC, m_chBitmap, m_chDC, m_origBackBitmap, and m_origCHBitmap.
OnLButtonDown()
void MeaCrossHair::OnLButtonDown (UINT flags, CPoint point) protected
Called when the left mouse button is pressed while the pointer is over the crosshair window.
Parameters
flags [in] Virtual key state
point [in] Location of the pointer, in pixels
References FillInfo(), m_callback, m_mouseCaptured, m_pointerOffset, and MeaCrossHairCallback::OnCHSelect().
OnLButtonUp()
void MeaCrossHair::OnLButtonUp (UINT flags, CPoint point) protected
Called when the left mouse button is released while the pointer is captured by the crosshair window.
Parameters
flags [in] Virtual key state
point [in] Location of the pointer, in pixels
References FillInfo(), m_callback, m_mouseCaptured, and MeaCrossHairCallback::OnCHDeselect().
OnMouseLeave()
LRESULT MeaCrossHair::OnMouseLeave (WPARAM wParam, LPARAM lParam) protected
Called when the pointer leaves the crosshair window.
The method initializes the crosshair information structure and calls the callback MeaCrossHairCallback::OnCHLeave, if a callback has been specified.
Parameters
wParam [in] Not used
lParam [in] Not used
Returns
Always zero.
References FillInfo(), m_callback, m_mouseOver, and MeaCrossHairCallback::OnCHLeave().
OnMouseMove()
void MeaCrossHair::OnMouseMove (UINT flags, CPoint point) protected
Called when the crosshair is dragged.
The method initializes the crosshair information structure and calls the callback MeaCrossHairCallback::OnCHMove method, if a callback has been specified.
Parameters
flags [in] Virtual key state
point [in] Location of the pointer, in pixels
References FillInfo(), m_callback, m_mouseCaptured, m_mouseOver, MeaCrossHairCallback::OnCHEnter(), and MeaCrossHairCallback::OnCHMove().
OnTimer()
void MeaCrossHair::OnTimer (UINT_PTR timerId) protected
Called when the crosshair is cycling between normal and hilited display as a result of a call to the Flash() method.
This method redraws the crosshair in the appropriate background color.
Parameters
timerId [in] ID for the timer that has expired.
References Inverted, m_drawState, m_flashCount, m_flashInterval, and Normal.
PreTranslateMessage()
BOOL MeaCrossHair::PreTranslateMessage (MSG * pMsg) virtual
Relays messages to the crosshair's tooltip.
Parameters
pMsg [in] Window message to relay
Returns
TRUE if message was processed.
References m_toolTip.
SetColors()
void MeaCrossHair::SetColors (COLORREF borderColor, COLORREF backColor, COLORREF hiliteColor)
Sets the colors for the crosshair.
Parameters
borderColor [in] Color for the crosshair border lines
backColor [in] Normal background color
hiliteColor [in] Hilite background color
References DestroyColors(), m_backBrush, m_borderBrush, and m_hiliteBrush.
Referenced by MeaAngleTool::ColorsChanged(), MeaCircleTool::ColorsChanged(), MeaLineTool::ColorsChanged(), MeaPointTool::ColorsChanged(), MeaRectTool::ColorsChanged(), Create(), MeaToolsPrefs::OnChangeBackColor(), MeaToolsPrefs::OnChangeBorderColor(), MeaToolsPrefs::OnChangeHiliteColor(), MeaToolsPrefs::OnDefBackColor(), MeaToolsPrefs::OnDefBorderColor(), and MeaToolsPrefs::OnDefHiliteColor().
SetOpacity()
void MeaCrossHair::SetOpacity (BYTE opacity)
Sets the opacity for the crosshair.
Parameters
opacity [in] Opacity value between 0 (transparent) and 255 (opaque) inclusive
References LWA_ALPHA, m_opacity, MeaGraphic::m_parent, and SetLayeredWindowAttributes.
Referenced by MeaAngleTool::ColorsChanged(), MeaCircleTool::ColorsChanged(), MeaLineTool::ColorsChanged(), MeaPointTool::ColorsChanged(), MeaRectTool::ColorsChanged(), Create(), MeaToolsPrefs::OnHScroll(), and MeaToolsPrefs::OnInitDialog().
SetPosition()
void MeaCrossHair::SetPosition (const POINT & center)
Sets the position of the crosshair.
Parameters
center [in] Position for the center of the crosshair, in pixels.
References GetLeftTop().
Referenced by MeaAngleTool::OnCHMove(), MeaCircleTool::OnCHMove(), MeaLineTool::OnCHMove(), MeaRectTool::OnCHMove(), MeaToolsPrefs::OnInitDialog(), MeaPointTool::SetPosition(), MeaAngleTool::SetPosition(), MeaCircleTool::SetPosition(), MeaLineTool::SetPosition(), and MeaRectTool::SetPosition().
SetRegion()
void MeaCrossHair::SetRegion () private
Forms the window into the shape of the crosshair.
A series of rectangular regions are aggregated together to form the four petals of the crosshair.
References m_halfSize, m_numCoords, m_size, and m_spread.
Referenced by Create().
The documentation for this class was generated from the following files:
CrossHair.h
CrossHair.cpp
Copyright 2011 C Thing Software