Meazure: MeaFileProfile Class Reference
MeaFileProfile Class Reference
Persists the application state to an XML file.
#include <FileProfile.h>
Public Types
enum Mode {
ProfRead ,
ProfWrite
}
File access mode.
Public Member Functions
MeaFileProfile (LPCTSTR pathname, Mode mode)
Creates an instance of a profile file object.
virtual ~MeaFileProfile ()
Closes the profile file and destroys the object instance.
virtual bool WriteBool (LPCTSTR key, bool value) override
Writes a boolean value to the specified key.
virtual bool WriteInt (LPCTSTR key, int value) override
Writes an integer value to the specified key.
virtual bool WriteDbl (LPCTSTR key, double value) override
Writes a double value to the specified key.
virtual bool WriteStr (LPCTSTR key, LPCTSTR value) override
Writes a string value to the specified key.
virtual bool ReadBool (LPCTSTR key, bool defaultValue) override
Reads a boolean value from the specified key.
virtual UINT ReadInt (LPCTSTR key, int defaultValue) override
Reads an unsigned integer value from the specified key.
virtual double ReadDbl (LPCTSTR key, double defaultValue) override
Reads a double value from the specified key.
virtual CString ReadStr (LPCTSTR key, LPCTSTR defaultValue) override
Reads a string value from the specified key.
virtual bool UserInitiated () override
Indicates whether the profile is being written at the user's request (i.e.
virtual int GetVersion () override
Returns the profile format version number.
virtual void StartElementHandler (const CString &container, const CString &elementName, const MeaXMLAttributes &attrs) override
Called when the XML parser encounters the start of an element.
virtual void CharacterDataHandler (const CString &container, const CString &data) override
Called when the XML parser encounters character data.
virtual void ParseEntity (MeaXMLParser &parser, const CString &pathname) override
Called when the XML parser needs to parse an external entity.
virtual CString GetFilePathname () override
Obtains the pathname of the profile file represented by an instance of this class.
Public Member Functions inherited from MeaProfile
MeaProfile ()
Constructs a profile instance.
virtual ~MeaProfile ()
Destroys a profile instance.
virtual bool WriteBool (LPCTSTR key, bool value)
Writes a boolean value to the specified key.
virtual bool WriteInt (LPCTSTR key, int value)
Writes an integer value to the specified key.
virtual bool WriteDbl (LPCTSTR key, double value)
Writes a double value to the specified key.
virtual bool WriteStr (LPCTSTR key, LPCTSTR value)
Writes a string value to the specified key.
virtual bool ReadBool (LPCTSTR key, bool defaultValue)
Reads a boolean value from the specified key.
virtual UINT ReadInt (LPCTSTR key, int defaultValue)
Reads an unsigned integer value from the specified key.
virtual double ReadDbl (LPCTSTR key, double defaultValue)
Reads a double value from the specified key.
virtual CString ReadStr (LPCTSTR key, LPCTSTR defaultValue)
Reads a string value from the specified key.
virtual bool UserInitiated ()
Indicates whether the profile is being written at the user's request (i.e.
virtual int GetVersion ()
Returns the profile format version number.
Public Member Functions inherited from MeaXMLParserHandler
MeaXMLParserHandler ()
Empty constructor for the handler class.
virtual ~MeaXMLParserHandler ()
Empty destructor for the handler class.
virtual void StartElementHandler (const CString &container, const CString &elementName, const MeaXMLAttributes &attrs)
Called when a new element is opened (e.g.
virtual void EndElementHandler (const CString &container, const CString &elementName)
Called when an element is closed (e.g.
virtual void CharacterDataHandler (const CString &container, const CString &data)
Called for all character data encountered between elements.
virtual void ParseEntity (MeaXMLParser &parser, const CString &pathname)
Called to parse an external entity.
virtual CString GetFilePathname ()
Returns the pathname of the currently parsed file.
Private Member Functions
void Write (int indentLevel, LPCTSTR format,...)
Printf style method that writes the specified values using the specified format and indentation level.
void WriteFileStart ()
Writes the XML boilerplate at the start of the XML profile file.
void WriteFileEnd ()
Write the XML boilerplate at the end of the XML profile file.
void ParseFile ()
Supervises the parsing of the XML profile file.
Private Attributes
CStdioFile m_stdioFile
File object representing the profile.
Mode m_mode
Opening mode for the profile file.
int m_readVersion
Profile format version number read from the profile file.
CString m_title
Title for the profile file.
std::map< CString, CString > m_valueMap
Maps profile keys to values.
Detailed Description
Persists the application state to an XML file.
Member Enumeration Documentation
Mode
enum MeaFileProfile::Mode
File access mode.
Enumerator
ProfRead
Open profile file for reading.
ProfWrite
Open profile file for writing.
Constructor & Destructor Documentation
MeaFileProfile()
MeaFileProfile::MeaFileProfile (LPCTSTR pathname, Mode mode)
Creates an instance of a profile file object.
The specified profile file is opened for either reading or writing.
Parameters
pathname [in] Pathname for the profile file. If the file is opened for writing, it is created if it does not exist.
mode [in] Opening mode for the profile file (i.e. read or write).
References m_mode, m_stdioFile, m_title, ParseFile(), ProfRead, ProfWrite, and WriteFileStart().
Member Function Documentation
CharacterDataHandler()
void MeaFileProfile::CharacterDataHandler (const CString & container, const CString & data) override virtual
Called when the XML parser encounters character data.
Parameters
container [in] Name of the element containing the character data.
data [in] Character data.
Reimplemented from MeaXMLParserHandler.
References m_title.
GetFilePathname()
CString MeaFileProfile::GetFilePathname () override virtual
Obtains the pathname of the profile file represented by an instance of this class.
Returns
Pathname of the profile file.
Reimplemented from MeaXMLParserHandler.
References m_stdioFile.
GetVersion()
int MeaFileProfile::GetVersion () override virtual
Returns the profile format version number.
Returns
Profile format version number.
Reimplemented from MeaProfile.
References m_readVersion.
ParseEntity()
void MeaFileProfile::ParseEntity (MeaXMLParser & parser, const CString & pathname) override virtual
Called when the XML parser needs to parse an external entity.
Parameters
parser [in] XML parser.
pathname [in] Pathname of the external entity to open and parse.
Reimplemented from MeaXMLParserHandler.
References MeaXMLParser::GetBuffer(), and MeaXMLParser::ParseBuffer().
ReadBool()
bool MeaFileProfile::ReadBool (LPCTSTR key, bool defaultValue) override virtual
Reads a boolean value from the specified key.
Parameters
key [in] Profile key to read
defaultValue [in] Default value to use if the key is not found in the profile.
Reimplemented from MeaProfile.
References m_valueMap.
ReadDbl()
double MeaFileProfile::ReadDbl (LPCTSTR key, double defaultValue) override virtual
Reads a double value from the specified key.
Parameters
key [in] Profile key to read
defaultValue [in] Default value to use if the key is not found in the profile.
Reimplemented from MeaProfile.
References m_valueMap.
ReadInt()
UINT MeaFileProfile::ReadInt (LPCTSTR key, int defaultValue) override virtual
Reads an unsigned integer value from the specified key.
Parameters
key [in] Profile key to read
defaultValue [in] Default value to use if the key is not found in the profile.
Reimplemented from MeaProfile.
References m_valueMap.
ReadStr()
CString MeaFileProfile::ReadStr (LPCTSTR key, LPCTSTR defaultValue) override virtual
Reads a string value from the specified key.
Parameters
key [in] Profile key to read
defaultValue [in] Default value to use if the key is not found in the profile.
Reimplemented from MeaProfile.
References m_valueMap.
StartElementHandler()
void MeaFileProfile::StartElementHandler (const CString & container, const CString & elementName, const MeaXMLAttributes & attrs) override virtual
Called when the XML parser encounters the start of an element.
Parameters
container [in] Name of the element containing this element.
elementName [in] Name of the element.
attrs [in] Attributes for the element.
Reimplemented from MeaXMLParserHandler.
References MeaXMLAttributes::GetValueInt(), MeaXMLAttributes::GetValueStr(), m_readVersion, and m_valueMap.
UserInitiated()
bool MeaFileProfile::UserInitiated () override virtual
Indicates whether the profile is being written at the user's request (i.e.
a file profile).
Returns
Always true because a file profile is only written at the user's request.
Reimplemented from MeaProfile.
Write()
void MeaFileProfile::Write (int indentLevel, LPCTSTR format, ...) private
Printf style method that writes the specified values using the specified format and indentation level.
Parameters
indentLevel [in] Indentation level for the output.
format [in] Printf-style format string for the output.
... [in] Items to write to the file.
References m_stdioFile, and MeaXMLParser::ToUTF8().
Referenced by WriteBool(), WriteDbl(), WriteFileEnd(), WriteFileStart(), WriteInt(), and WriteStr().
WriteBool()
bool MeaFileProfile::WriteBool (LPCTSTR key, bool value) override virtual
Writes a boolean value to the specified key.
Parameters
key [in] Profile key to write
value [in] Boolean value for the key
Reimplemented from MeaProfile.
References Write().
WriteDbl()
bool MeaFileProfile::WriteDbl (LPCTSTR key, double value) override virtual
Writes a double value to the specified key.
Parameters
key [in] Profile key to write
value [in] Double value for the key
Reimplemented from MeaProfile.
References Write().
WriteInt()
bool MeaFileProfile::WriteInt (LPCTSTR key, int value) override virtual
Writes an integer value to the specified key.
Parameters
key [in] Profile key to write
value [in] Integer value for the key
Reimplemented from MeaProfile.
References Write().
WriteStr()
bool MeaFileProfile::WriteStr (LPCTSTR key, LPCTSTR value) override virtual
Writes a string value to the specified key.
Parameters
key [in] Profile key to write
value [in] String value for the key
Reimplemented from MeaProfile.
References Write().
The documentation for this class was generated from the following files:
FileProfile.h
FileProfile.cpp
Copyright 2011 C Thing Software