Meazure: MeaUtils Class Reference
MeaUtils Class Reference
Static Public Member Functions
static CString DblToStr (double value)
Converts the specified double to a string with the minimum number of decimal places.
static bool IsNumber (LPCTSTR str, double *valuep=nullptr)
Tests whether the specified string is a number.
static bool IsBoolean (LPCTSTR str, bool *valuep=nullptr)
Tests whether the specified string is a boolean value.
static CString LFtoCRLF (CString str)
Converts standalone LF characters into a CR+LF pair.
static CString CRLFtoLF (CString str)
Converts CR+LF pairs to a single LF character.
static bool IsKeyPressed (int keyCode)
Indicates whether the specified key is being pressed.
Private Member Functions
MeaUtils ()
All members of this class are static.
~MeaUtils ()
All members of this class are static.
Constructor & Destructor Documentation
MeaUtils()
MeaUtils::MeaUtils () inline private
All members of this class are static.
No instances of this class are ever created.
~MeaUtils()
MeaUtils::~MeaUtils () inline private
All members of this class are static.
No instances of this class are ever created.
Member Function Documentation
CRLFtoLF()
CString MeaUtils::CRLFtoLF (CString str) static
Converts CR+LF pairs to a single LF character.
Parameters
str [in] String to process.
Returns
Converted string.
Referenced by MeaPositionLogMgr::Position::Save(), and MeaPositionLogMgr::WriteInfoSection().
DblToStr()
CString MeaUtils::DblToStr (double value) static
Converts the specified double to a string with the minimum number of decimal places.
Parameters
value [in] Numerical value to convert to a string.
Returns
String corresponding to the double value.
Referenced by MeaPositionLogMgr::Position::Save(), MeaPositionLogMgr::Screen::Save(), MeaPositionLogMgr::DesktopInfo::Save(), MeaUnitsMgr::SaveProfile(), MeaScreenMgr::SaveProfile(), MeaAngleTool::SaveProfile(), MeaCircleTool::SaveProfile(), MeaLineTool::SaveProfile(), MeaPointTool::SaveProfile(), and MeaRectTool::SaveProfile().
IsBoolean()
bool MeaUtils::IsBoolean (LPCTSTR str, bool * valuep = nullptr) static
Tests whether the specified string is a boolean value.
For the purpose of this method, the strings "1", "TRUE", "true" are boolean true values, while "0", "FALSE", "false" are boolean false.
Parameters
str [in] String to test
valuep [out] Value parsed from the string. nullptr if not interested. If the return value is false, valuep's value is undefined.
Returns
true if string represents a boolean value.
IsKeyPressed()
bool MeaUtils::IsKeyPressed (int keyCode) static
Indicates whether the specified key is being pressed.
Parameters
keyCode ASCII character code or VK_* for a virtual key.
IsNumber()
bool MeaUtils::IsNumber (LPCTSTR str, double * valuep = nullptr) static
Tests whether the specified string is a number.
For the purposes of this method, a number is a base 10 double precision floating point value.
Parameters
str [in] String to test
valuep [out] Value parsed from the string. nullptr if not interested. If the return value is false, valuep's value is undefined.
Returns
true if string represents a number.
LFtoCRLF()
CString MeaUtils::LFtoCRLF (CString str) static
Converts standalone LF characters into a CR+LF pair.
Existing CR+LF pairs in the string are not effected.
Parameters
str [in] String to process.
Returns
Converted string.
Referenced by MeaPositionLogMgr::ProcessDataNodes().
The documentation for this class was generated from the following files:
Utils.h
Utils.cpp
Copyright 2011 C Thing Software