Meazure: MeaScreenMgr Class Reference
MeaScreenMgr Class Reference
Provides information on the display monitor(s).
#include <ScreenMgr.h>
Classes
struct less
Used by the STL collections for ordering comparisons.
class Screen
Represents a single display screen.
Public Types
typedef Screens::const_iterator ScreenIter
Constant iterator over the screens.
Public Member Functions
void SaveProfile (MeaProfile &profile) const
Persists the state of the manager to the specified profile object.
void LoadProfile (MeaProfile &profile)
Restore the state of the manager from the specified profile object.
void MasterReset () const
Resets the screen manager to its default state.
int GetNumScreens () const
Returns the number of display screens attached to the system.
ScreenIter GetScreenIter () const
Obtains an iterator over each screen attached to the system.
ScreenIter GetScreenIter (const CWnd *wnd) const
Obtains an iterator pointed at the screen that contains the specified window.
ScreenIter GetScreenIter (const POINT &point) const
Obtains an iterator pointed at the screen that contains the specified point.
ScreenIter GetScreenIter (const RECT &rect) const
Obtains an iterator pointed at the screen that contains the specified rectangle.
bool AtEnd (const ScreenIter &iter) const
Indicates if the screen iterator is at the end of the screen collection.
const CPoint & GetCenter () const
Determines the center of the screen that contains the app's main window.
CPoint GetOffScreen () const
Returns a point guaranteed to be located off any screen.
const CRect & GetVirtualRect () const
Returns the virtual screen rectangle.
const CRect & GetScreenRect (const ScreenIter &iter) const
Returns the screen rectangle for the screen pointed to by the specified iterator.
void GetScreenRes (const ScreenIter &iter, bool &useManualRes, FSIZE &manualRes) const
Returns the manually set screen resolution for the screen pointed to by the specified iterator.
const FSIZE & GetScreenRes (const ScreenIter &iter) const
Returns the resolution for the screen pointed to by the specified iterator.
bool IsManualRes (const ScreenIter &iter) const
Indicates it the resolution for the specified screen has been set manually.
bool AnyOSRes () const
Indicates whether any screen is using the operating system reported resolution.
void SetScreenRes (const ScreenIter &iter, bool useManualRes, const FSIZE *manualRes=NULL) const
Sets the resolution for the screen pointed to by the specified iterator.
bool IsPrimary (const ScreenIter &iter) const
Indicates if the screen pointed to by the specified iterator is the primary.
CString GetScreenName (const ScreenIter &iter) const
Returns the name for the specified screen.
bool GetCalInInches (const ScreenIter &iter) const
Indicates if the specified screen was calibrated in inches or centimeters.
void SetCalInInches (const ScreenIter &iter, bool calInInches) const
Specifies the calibration units for the specified screen.
bool SizeChanged () const
Indicates whether the virtual screen rectangle has changed since the last time the app was run.
CRect EnsureVisible (const RECT &windowRect) const
Ensures that the specified window rectangle is visible on the nearest screen.
CPoint LimitPosition (const CPoint &pt) const
Ensures that the specified point is on a screen.
FSIZE GetOSScreenRes () const
Obtains the screen resolution reported by the operating system.
Public Member Functions inherited from MeaSingleton_T< MeaScreenMgr >
virtual ~MeaSingleton_T ()
Destructor for the Singleton.
Static Public Attributes
static const bool kDefUseManualRes = false
Use manual resolution by default.
static const bool kDefCalInInches = true
Calibrate in inches by default.
Private Types
typedef std::map< HMONITOR, Screen * > Screens
Maps a monitor handle to a screen object.
Private Member Functions
MeaScreenMgr (const MeaScreenMgr &)
Managers are singletons.
MeaScreenMgr & operator= (const MeaScreenMgr &)
Purposely undefined.
Screen * GetScreen (const POINT &point) const
Obtains the screen containing the specified point.
Static Private Member Functions
static BOOL CALLBACK CreateScreens (HMONITOR hMonitor, HDC hdcMonitor, LPRECT monitorRect, LPARAM userData)
Called by the constructor via EnumDisplayMonitors.
Private Attributes
Screens m_screens
Display monitors.
CRect m_virtualRect
Bounding box of all screen rectangles.
bool m_sizeChanged
Virtual screen rectangle changed since last run.
Friends
class MeaSingleton_T< MeaScreenMgr >
Additional Inherited Members
Static Public Member Functions inherited from MeaSingleton_T< MeaScreenMgr >
static MeaScreenMgr & Instance ()
The first time this method is called, a instance of the Singleton object is created and returned.
static void DestroyInstance ()
When the Singleton object is no longer needed, it must be destroyed using this method.
static bool IsDestroyed ()
Indicates whether the Singleton object has been destroyed.
Protected Member Functions inherited from MeaSingleton_T< MeaScreenMgr >
MeaSingleton_T ()
Constructs a Singleton object instance.
Detailed Description
Provides information on the display monitor(s).
One of the primary jobs of this manager is to properly handle multiple display monitor environments.
Constructor & Destructor Documentation
MeaScreenMgr()
MeaScreenMgr::MeaScreenMgr (const MeaScreenMgr &) private
Managers are singletons.
Purposely undefined.
Member Function Documentation
AnyOSRes()
bool MeaScreenMgr::AnyOSRes () const inline
Indicates whether any screen is using the operating system reported resolution.
In other words, are there any screen that require calibration.
Returns
true if there are any screens requiring manual calibration.
References m_screens.
Referenced by CChildView::ApplyPreferences(), MeaUnitsMgr::SetLinearUnits(), and MeaScreenTool::SetPosition().
AtEnd()
bool MeaScreenMgr::AtEnd (const ScreenIter & iter) const inline
Indicates if the screen iterator is at the end of the screen collection.
Parameters
iter [in] Screen iterator to test.
Returns
true if the specified iterator is pointed to the end of the collection of screens.
References m_screens.
Referenced by MeaRulerTool::Enable(), MeaLinearUnits::FindResFromCoord(), MeaLinearUnits::FindResFromPos(), MeaPositionLogMgr::DesktopInfo::Init(), MeaRulerTool::LoadProfile(), LoadProfile(), MasterReset(), CChildView::OnPreferences(), and SaveProfile().
CreateScreens()
BOOL CALLBACK MeaScreenMgr::CreateScreens (HMONITOR hMonitor, HDC hdcMonitor, LPRECT monitorRect, LPARAM userData) static private
Called by the constructor via EnumDisplayMonitors.
Instantiates a Screen object for each display monitor on the system.
Parameters
hMonitor [in] Monitor handle.
hdcMonitor [in] Not used.
monitorRect [in] Rectangle representing the monitors logical dimensions.
userData [in] this pointer.
Returns
TRUE to continue enumeration of monitors.
References GetNumScreens(), m_screens, MeaScreenMgr::Screen::SetName(), and MeaScreenMgr::Screen::SetPrimary().
EnsureVisible()
CRect MeaScreenMgr::EnsureVisible (const RECT & windowRect) const
Ensures that the specified window rectangle is visible on the nearest screen.
If the window rectangle is already visible, the rectangle is not changed.
Parameters
windowRect [in] Window rectangle that is to be tested for visibility. The rectangle is altered if necessary to ensure at least a part of the window is visible.
Returns
New rectangle that is guaranteed to be visible.
References m_screens, and MeaAssert.
Referenced by CMainFrame::LoadProfile().
GetCalInInches()
bool MeaScreenMgr::GetCalInInches (const ScreenIter & iter) const inline
Indicates if the specified screen was calibrated in inches or centimeters.
Parameters
iter [in] Points at the screen whose calibration units are desired.
Returns
true if the resolution was calibrated in inches.
Referenced by CChildView::OnPreferences().
GetCenter()
const CPoint & MeaScreenMgr::GetCenter () const
Determines the center of the screen that contains the app's main window.
Returns
Center point of the screen containing the app's main window.
References m_screens, and MeaAssert.
Referenced by MeaAngleTool::MeaAngleTool(), MeaCircleTool::MeaCircleTool(), MeaLineTool::MeaLineTool(), MeaPointTool::MeaPointTool(), and MeaRectTool::MeaRectTool().
GetNumScreens()
int MeaScreenMgr::GetNumScreens () const inline
Returns the number of display screens attached to the system.
Returns
Number of display screens attached to the system.
References m_screens.
Referenced by CreateScreens(), MeaLinearUnits::FindResFromCoord(), MeaLinearUnits::FindResFromPos(), MeaRulerTool::MeaRulerTool(), and SaveProfile().
GetOffScreen()
CPoint MeaScreenMgr::GetOffScreen () const
Returns a point guaranteed to be located off any screen.
Returns
Point located off any display screen.
References GetVirtualRect().
Referenced by MeaRuler::ClearIndicator().
GetOSScreenRes()
FSIZE MeaScreenMgr::GetOSScreenRes () const
Obtains the screen resolution reported by the operating system.
Returns
Resolution in pixels per inch.
References FSIZE::cx, and FSIZE::cy.
GetScreen()
MeaScreenMgr::Screen * MeaScreenMgr::GetScreen (const POINT & point) const private
Obtains the screen containing the specified point.
Parameters
point [in] Point whose screen is desired.
Returns
Screen containing the specified point or NULL if the point is not contained by any screen.
References m_screens, and MeaAssert.
Referenced by LoadProfile().
GetScreenIter() [1/4]
ScreenIter MeaScreenMgr::GetScreenIter () const inline
Obtains an iterator over each screen attached to the system.
Returns
Constant iterator over all screens.
References m_screens.
Referenced by MeaLinearUnits::ConvertCoord(), MeaLinearUnits::ConvertPos(), MeaRuler::Create(), MeaCrossHair::Create(), MeaMagnifier::Draw(), MeaLayout::DrawOpacityBackground(), MeaRulerTool::Enable(), MeaLinearUnits::FindResFromCoord(), MeaLinearUnits::FindResFromPos(), MeaLinearUnits::GetMinorIncr(), MeaPositionLogMgr::DesktopInfo::Init(), MeaRulerTool::LoadProfile(), LoadProfile(), MasterReset(), CChildView::OnPreferences(), SaveProfile(), MeaScreenTool::SetPosition(), MeaLinearUnits::UnconvertCoord(), MeaDataWin::Update(), MeaOriginTool::Update(), and MeaCalibrationPrefs::UpdateCurrentScreen().
GetScreenIter() [2/4]
MeaScreenMgr::ScreenIter MeaScreenMgr::GetScreenIter (const CWnd * wnd) const
Obtains an iterator pointed at the screen that contains the specified window.
Parameters
wnd [in] Window whose screen is desired.
Returns
Constant iterator pointed at screen containing the specified window.
References m_screens, and MeaAssert.
GetScreenIter() [3/4]
MeaScreenMgr::ScreenIter MeaScreenMgr::GetScreenIter (const POINT & point) const
Obtains an iterator pointed at the screen that contains the specified point.
Parameters
point [in] Point whose screen is desired.
Returns
Constant iterator pointed at screen containing the specified point.
References m_screens, and MeaAssert.
GetScreenIter() [4/4]
MeaScreenMgr::ScreenIter MeaScreenMgr::GetScreenIter (const RECT & rect) const
Obtains an iterator pointed at the screen that contains the specified rectangle.
Parameters
rect [in] Rectangle whose screen is desired.
Returns
Constant iterator pointed at screen containing the specified rectangle.
References m_screens, and MeaAssert.
GetScreenName()
CString MeaScreenMgr::GetScreenName (const ScreenIter & iter) const inline
Returns the name for the specified screen.
Parameters
iter [in] Iterator pointing to the screen whose name is desired.
Returns
Name of the specified screen.
Referenced by MeaPositionLogMgr::Screen::Screen(), MeaScreenTool::SetPosition(), and MeaCalibrationPrefs::UpdateCurrentScreen().
GetScreenRect()
const CRect & MeaScreenMgr::GetScreenRect (const ScreenIter & iter) const inline
Returns the screen rectangle for the screen pointed to by the specified iterator.
Parameters
iter [in] Screen iterator pointed at the screen whose rectangle is desired.
Returns
Screen rectangle, in pixels.
Referenced by MeaMagnifier::Draw(), MeaRulerTool::Enable(), MeaLinearUnits::FindResFromCoord(), MeaLinearUnits::FindResFromPos(), MeaRulerTool::LoadProfile(), MeaCalibrationPrefs::OnCaliperChange(), MeaCalibrationPrefs::OnHFieldChange(), MeaCalibrationPrefs::OnRxFieldChange(), MeaCalibrationPrefs::OnRyFieldChange(), MeaCalibrationPrefs::OnWFieldChange(), MeaPositionLogMgr::Screen::Screen(), MeaScreenTool::SetPosition(), MeaDataWin::Update(), MeaCalibrationPrefs::UpdateView(), and MeaCalibrationPrefs::Validate().
GetScreenRes() [1/2]
const FSIZE & MeaScreenMgr::GetScreenRes (const ScreenIter & iter) const inline
Returns the resolution for the screen pointed to by the specified iterator.
Parameters
iter [in] Screen iterator pointed at the screen whose resolution is desired.
Returns
Screen resolution, in pixels per inch. If the resolution has been set manually, it is returned. Otherwise, the operating system reported resolution is returned.
GetScreenRes() [2/2]
void MeaScreenMgr::GetScreenRes (const ScreenIter & iter, bool & useManualRes, FSIZE & manualRes) const inline
Returns the manually set screen resolution for the screen pointed to by the specified iterator.
Parameters
iter [in] Screen iterator pointed at the screen whose manual resolution is desired.
useManualRes [out] true if the resolution was set manually.
manualRes [out] Manually set resolution, in pixels per inch.
Referenced by MeaLinearUnits::ConvertCoord(), MeaLinearUnits::ConvertPos(), MeaRuler::Create(), MeaCrossHair::Create(), MeaLayout::DrawOpacityBackground(), MeaLinearUnits::FindResFromCoord(), MeaLinearUnits::FindResFromPos(), MeaLinearUnits::GetMinorIncr(), CChildView::OnPreferences(), MeaPositionLogMgr::Screen::Screen(), MeaScreenTool::SetPosition(), MeaLinearUnits::UnconvertCoord(), MeaOriginTool::Update(), and MeaCalibrationPrefs::Validate().
GetVirtualRect()
const CRect & MeaScreenMgr::GetVirtualRect () const inline
Returns the virtual screen rectangle.
The virtual rectangle is the rectangle containing all display screen attached to the system.
Returns
Rectangle encompassing all display screens attached to the system, in pixels.
References m_virtualRect.
Referenced by MeaDataWin::CalcWidth(), MeaLinearUnits::ConvertCoord(), MeaCircle::Create(), MeaLine::Create(), MeaDataDisplay::CreateRegionSection(), MeaRuler::DrawRuler(), GetOffScreen(), MeaPositionLogMgr::DesktopInfo::Init(), MeaGridTool::SetLines(), MeaGridTool::ShowLines(), MeaLinearUnits::UnconvertCoord(), and MeaOriginTool::Update().
IsManualRes()
bool MeaScreenMgr::IsManualRes (const ScreenIter & iter) const inline
Indicates it the resolution for the specified screen has been set manually.
Parameters
iter [in] Screen iterator pointed at the screen whose resolution setting is being queried.
Returns
true if the screen's resolution was set manually.
Referenced by MeaPositionLogMgr::Screen::Screen().
IsPrimary()
bool MeaScreenMgr::IsPrimary (const ScreenIter & iter) const inline
Indicates if the screen pointed to by the specified iterator is the primary.
Returns
true if the specified screen is the primary.
Referenced by MeaPositionLogMgr::Screen::Screen().
LimitPosition()
CPoint MeaScreenMgr::LimitPosition (const CPoint & pt) const
Ensures that the specified point is on a screen.
Parameters
pt [in] Point to check.
Returns
New point based on the specified point that is guaranteed to be on a screen.
References m_screens, and MeaAssert.
Referenced by MeaCrossHair::FillInfo(), MeaRuler::FillInfo(), MeaAngleTool::OnCHMove(), MeaCircleTool::OnCHMove(), MeaLineTool::OnCHMove(), MeaRectTool::OnCHMove(), MeaPointTool::SetPosition(), MeaAngleTool::SetPosition(), MeaCircleTool::SetPosition(), MeaLineTool::SetPosition(), and MeaRectTool::SetPosition().
LoadProfile()
void MeaScreenMgr::LoadProfile (MeaProfile & profile)
Restore the state of the manager from the specified profile object.
Parameters
profile [in] Profile object from which the manager state is restored.
References AtEnd(), FSIZE::cx, FSIZE::cy, GetScreen(), GetScreenIter(), MeaProfile::GetVersion(), kDefCalInInches, kDefUseManualRes, m_sizeChanged, m_virtualRect, MeaProfile::ReadBool(), MeaProfile::ReadDbl(), MeaProfile::ReadInt(), MeaScreenMgr::Screen::SetCalInInches(), MeaScreenMgr::Screen::SetScreenRes(), and MeaProfile::UserInitiated().
Referenced by CChildView::LoadProfile().
SaveProfile()
void MeaScreenMgr::SaveProfile (MeaProfile & profile) const
Persists the state of the manager to the specified profile object.
Parameters
profile [in] Profile object into which the manager state is persisted.
References AtEnd(), FSIZE::cx, FSIZE::cy, MeaUtils::DblToStr(), GetNumScreens(), GetScreenIter(), m_virtualRect, MeaProfile::UserInitiated(), MeaProfile::WriteBool(), MeaProfile::WriteInt(), and MeaProfile::WriteStr().
Referenced by CChildView::SaveProfile().
SetCalInInches()
void MeaScreenMgr::SetCalInInches (const ScreenIter & iter, bool calInInches) const inline
Specifies the calibration units for the specified screen.
Parameters
iter [in] Points at the screen whose calibration units are to be set.
calInInches [in] true if the resolution is calibrated in inches.
Referenced by CChildView::ApplyPreferences().
SetScreenRes()
void MeaScreenMgr::SetScreenRes (const ScreenIter & iter, bool useManualRes, const FSIZE * manualRes = NULL) const inline
Sets the resolution for the screen pointed to by the specified iterator.
Parameters
iter [in] Iterator pointing to the screen whose resolution is to be set.
useManualRes [in] true if the resolution is manually calibrated.
manualRes [in] Manually calibrated screen resolution, in pixels.
Referenced by CChildView::ApplyPreferences().
SizeChanged()
bool MeaScreenMgr::SizeChanged () const inline
Indicates whether the virtual screen rectangle has changed since the last time the app was run.
If the virtual screen size has changed, re-calibration is recommended.
Returns
true if the virtual screen rectangle has changed.
References m_sizeChanged.
Referenced by MeaUnitsMgr::SetLinearUnits().
Member Data Documentation
kDefUseManualRes
const bool MeaScreenMgr::kDefUseManualRes = false static
Use manual resolution by default.
Managers are singletons.
Referenced by LoadProfile(), and MasterReset().
The documentation for this class was generated from the following files:
ScreenMgr.h
ScreenMgr.cpp
Copyright 2011 C Thing Software