Meazure: MeaGridTool Class Reference
MeaGridTool Class Reference
Grid overlay tool.
#include <GridTool.h>
Public Member Functions
MeaGridTool (MeaToolMgr *mgr)
Constructs a new instance of the Grid overlay tool.
virtual ~MeaGridTool ()
Hides and then destroys the Grid tool.
virtual void Enable () override
Displays the Grid tool.
virtual void Disable () override
Hides the Grid tool.
virtual void SaveProfile (MeaProfile &profile) override
Persists the state of the tool to the specified profile object.
virtual void LoadProfile (MeaProfile &profile) override
Restores the state of the tool from the specified profile object.
virtual void MasterReset () override
Resets the tool to its default state.
virtual void Update (MeaUpdateReason reason) override
Draws the horizontal and vertical grid lines, if the tool is enabled.
void UpdateH ()
Draws the horizontal grid lines.
void UpdateV ()
Draws the vertical grid lines.
virtual CString GetToolName () const override
Returns the name of the tool.
virtual const POINT & GetPosition () const override
Returns the tool's current position which, for the Grid tool, is always the position (0, 0).
virtual void ColorsChanged () override
Called to notify the tool that the colors in the MeaColors class have been changed.
void SetGridSpacing (const SIZE &spacing)
Sets the horizontal and vertical grid spacing.
const SIZE & GetGridSpacing () const
Gets the horizontal and vertical grid spacing.
bool GetLinked () const
Indicates if the grid spacing is linked so that the horizontal and vertical grid spacing is the same.
void SetLinked (bool linked)
Sets the grid spacing link state.
Public Member Functions inherited from MeaTool
MeaTool (MeaToolMgr *mgr)
Base class constructor.
virtual ~MeaTool ()
Destroys the tool.
virtual void Enable ()
Typically used by derived classes to show the tool.
virtual void Disable ()
Typically used by derived classes to hide the tool.
virtual void Update (MeaUpdateReason reason)
Used by derived classes to update the display of their data.
virtual bool IsRadioTool ()
Indicates whether the derived tool is a radio tool and cannot be enabled until any other enabled Radio tool is disabled.
virtual void SetPosition (MeaFields which, int pixels)
Sets the position of the tool.
virtual const POINT & GetPosition () const =0
Returns the tool's current position.
virtual void IncPosition (MeaFields which)
Increments the specified position field.
virtual void DecPosition (MeaFields which)
Decrements the specified position field.
virtual CString GetToolName () const =0
Returns the name of the tool.
virtual void SaveProfile (MeaProfile &profile)
Persists the state of the tool to the specified profile object.
virtual void LoadProfile (MeaProfile &profile)
Restores the state of the tool from the specified profile object.
virtual void MasterReset ()
Resets the tool to its default state.
virtual void ColorsChanged ()
Called to notify the tool that the colors in the MeaColors class have been changed.
bool IsEnabled () const
Indicates whether the tool is enabled.
Static Public Attributes
static constexpr int kDefMinSpacing { 10 }
Minimum allowable grid spacing in pixels.
static constexpr int kDefMaxSpacing { 4000 }
Maximum allowable grid spacing in pixels.
static constexpr int kDefDefaultSpacing { 100 }
Default grid spacing in pixels.
static constexpr bool kDefGrid { false }
Default grid display state.
static constexpr bool kDefLinked { true }
Default spacing link state.
static const CString kToolName
"GridTool"
Private Types
enum LineDir {
HDir = 0 ,
VDir = 1
}
Grid line direction.
typedef std::list< MeaLine * > LineList
List of grid lines.
Private Member Functions
void SetLines (LineDir dir)
Creates the vertical or horizontal lines for the grid as needed and positions them on the grid according to the currently set grid spacing.
void ShowLines (LineDir dir)
Displays the vertical or horizontal grid lines.
void HideLines (LineDir dir) const
Hides the vertical or horizontal grid lines.
void DeleteLines (LineList &list) const
Hides and then destroys the lines in the specified line list.
Private Attributes
CSize m_gridSpacing
Vertical and horizontal grid spacing, in pixels.
bool m_linked
true if the vertical and horizontal grid spacings are linked (i.e. kept equal)
LineList m_hlineList
List of horizontal grid lines.
LineList m_vlineList
List of vertical grid lines.
Additional Inherited Members
Protected Attributes inherited from MeaTool
MeaToolMgr * m_mgr
Tool manager.
bool m_enabled
Indicates whether the tool is enabled.
Static Protected Attributes inherited from MeaTool
static POINT m_defaultPos { 0, 0 }
A default position used by tools that do not have a defined position.
Detailed Description
Grid overlay tool.
This tool overlays a rectangular grid on the screen. If there are multiple monitors, the grid is overlayed continuously across all monitors. The grid spacing can be changed using the MeaGridDialog.
Constructor & Destructor Documentation
MeaGridTool()
MeaGridTool::MeaGridTool (MeaToolMgr * mgr) explicit
Constructs a new instance of the Grid overlay tool.
To use a newly constructed Grid tool, the Enable() method must be called.
Parameters
mgr [in] Tool manager parent of the Grid tool.
Member Function Documentation
ColorsChanged()
void MeaGridTool::ColorsChanged () override virtual
Called to notify the tool that the colors in the MeaColors class have been changed.
The grid lines are redrawn in their new colors.
Reimplemented from MeaTool.
References MeaColors::Get(), MeaColors::LineFore, m_hlineList, and m_vlineList.
DeleteLines()
void MeaGridTool::DeleteLines (LineList & list) const private
Hides and then destroys the lines in the specified line list.
The line list is then cleared.
Parameters
list [in] List of lines whose contents is to be destroyed. The list is empty following the call to this method.
Disable()
void MeaGridTool::Disable () override virtual
Hides the Grid tool.
Reimplemented from MeaTool.
References MeaTool::Disable(), HideLines(), and MeaTool::IsEnabled().
Referenced by LoadProfile(), MasterReset(), and ~MeaGridTool().
Enable()
void MeaGridTool::Enable () override virtual
Displays the Grid tool.
Reimplemented from MeaTool.
References MeaTool::Enable(), MeaTool::IsEnabled(), NormalUpdate, and Update().
Referenced by LoadProfile(), and MasterReset().
GetGridSpacing()
const SIZE & MeaGridTool::GetGridSpacing () const inline
Gets the horizontal and vertical grid spacing.
Returns
Horizontal and vertical grid spacing, in pixels.
References m_gridSpacing.
GetLinked()
bool MeaGridTool::GetLinked () const inline
Indicates if the grid spacing is linked so that the horizontal and vertical grid spacing is the same.
Returns
true if the horizontal and vertical grid spacing are linked.
References m_linked.
GetPosition()
const POINT & MeaGridTool::GetPosition () const override virtual
Returns the tool's current position which, for the Grid tool, is always the position (0, 0).
Returns
The position (0, 0)
Implements MeaTool.
References MeaTool::m_defaultPos.
GetToolName()
CString MeaGridTool::GetToolName () const override virtual
Returns the name of the tool.
Each tool has a unique name which is used to identify the tool in profiles and position logs.
Returns
Name of the tool ("GridTool").
Implements MeaTool.
References kToolName.
HideLines()
void MeaGridTool::HideLines (LineDir dir) const private
Hides the vertical or horizontal grid lines.
Parameters
dir [in] Direction of the lines to display
References m_hlineList, and m_vlineList.
Referenced by Disable(), Update(), UpdateH(), and UpdateV().
LoadProfile()
void MeaGridTool::LoadProfile (MeaProfile & profile) override virtual
Restores the state of the tool from the specified profile object.
Parameters
profile [in] The source for the state information. Typically an MeaFileProfile or MeaRegistryProfile object.
Reimplemented from MeaTool.
References Disable(), Enable(), kDefGrid, m_gridSpacing, m_linked, MeaProfile::ReadBool(), and MeaProfile::ReadInt().
MasterReset()
void MeaGridTool::MasterReset () override virtual
Resets the tool to its default state.
Reimplemented from MeaTool.
References Disable(), Enable(), kDefDefaultSpacing, kDefGrid, kDefLinked, m_gridSpacing, and m_linked.
SaveProfile()
void MeaGridTool::SaveProfile (MeaProfile & profile) override virtual
Persists the state of the tool to the specified profile object.
Parameters
profile [in] The destination for the state information. Typically an MeaFileProfile or MeaRegistryProfile object.
Reimplemented from MeaTool.
References MeaTool::IsEnabled(), m_gridSpacing, m_linked, MeaProfile::WriteBool(), and MeaProfile::WriteInt().
SetGridSpacing()
void MeaGridTool::SetGridSpacing (const SIZE & spacing)
Sets the horizontal and vertical grid spacing.
Parameters
spacing [in] Horizontal and vertical grid spacing, in pixels
References kDefMaxSpacing, kDefMinSpacing, m_gridSpacing, UpdateH(), and UpdateV().
Referenced by MeaGridDialog::UpdateDisplay().
SetLines()
void MeaGridTool::SetLines (LineDir dir) private
Creates the vertical or horizontal lines for the grid as needed and positions them on the grid according to the currently set grid spacing.
Since there are many lines on a grid and line creation is expensive, lines are created on demand and reused. The lines are destroyed only when the tool is destroyed.
Parameters
dir [in] Direction of the lines to create
References MeaLine::Create(), MeaScreenMgr::GetVirtualRect(), MeaSingleton_T< MeaScreenMgr >::Instance(), m_gridSpacing, m_hlineList, m_vlineList, and MeaTool::SetPosition().
Referenced by Update(), UpdateH(), and UpdateV().
SetLinked()
void MeaGridTool::SetLinked (bool linked) inline
Sets the grid spacing link state.
Parameters
linked [in] true to link the spacing
References m_linked.
Referenced by MeaGridDialog::UpdateDisplay().
ShowLines()
void MeaGridTool::ShowLines (LineDir dir) private
Displays the vertical or horizontal grid lines.
Parameters
dir [in] Direction of the lines to display
References MeaScreenMgr::GetVirtualRect(), MeaSingleton_T< MeaScreenMgr >::Instance(), m_gridSpacing, m_hlineList, and m_vlineList.
Referenced by Update(), UpdateH(), and UpdateV().
Update()
void MeaGridTool::Update (MeaUpdateReason reason) override virtual
Draws the horizontal and vertical grid lines, if the tool is enabled.
Parameters
reason [in] Reason why the update has been requested
Reimplemented from MeaTool.
References HideLines(), MeaTool::IsEnabled(), SetLines(), ShowLines(), and MeaTool::Update().
Referenced by Enable().
The documentation for this class was generated from the following files:
GridTool.h
GridTool.cpp
Copyright 2011 C Thing Software