Meazure: MeaLabel Class Reference
MeaLabel Class Reference
Creates a label control whose size is automatically set to the size of its text.
#include <Label.h>
Public Member Functions
MeaLabel ()
Constructs a label object.
virtual ~MeaLabel ()
Destroys an instance of a label object.
bool Create (LPCTSTR label, DWORD style, const POINT &topLeft, CWnd *parentWnd, UINT id=0xffff)
Creates the window for the label.
bool Create (UINT labelID, DWORD style, const POINT &topLeft, CWnd *parentWnd, UINT id=0xffff)
Creates the window for the label.
Detailed Description
Creates a label control whose size is automatically set to the size of its text.
Constructor & Destructor Documentation
MeaLabel()
MeaLabel::MeaLabel ()
Constructs a label object.
Before the label can be used, the Create method must be called.
Member Function Documentation
Create() [1/2]
bool MeaLabel::Create (LPCTSTR label, DWORD style, const POINT & topLeft, CWnd * parentWnd, UINT id = 0xffff)
Creates the window for the label.
To make the label visible, add the WS_VISIBLE style or call ShowWindow.
Parameters
label [in] Label text.
style [in] Label window styles as defined for CStatic.
topLeft [in] Position of the top, left corner for the label, in pixels.
parentWnd [in] Parent window for the label.
id [in] ID for the label.
Returns
true if the label was created successfully.
References MeaLayout::SetWindowSize().
Referenced by MeaMagnifier::Create(), Create(), MeaUnitsLabel::Create(), and MeaDataDisplay::DataItem::CreateField().
Create() [2/2]
bool MeaLabel::Create (UINT labelID, DWORD style, const POINT & topLeft, CWnd * parentWnd, UINT id = 0xffff)
Creates the window for the label.
To make the label visible, add the WS_VISIBLE style or call ShowWindow.
Parameters
labelID [in] String resource ID for the label text.
style [in] Label window styles as defined for CStatic.
topLeft [in] Position of the top, left corner for the label, in pixels.
parentWnd [in] Parent window for the label.
id [in] ID for the label.
Returns
true if the label was created successfully.
References Create().
The documentation for this class was generated from the following files:
Label.h
Label.cpp
Copyright 2011 C Thing Software