Meazure: MeaRulerTool Class Reference
MeaRulerTool Class Reference
Ruler measurement tool.
#include <RulerTool.h>
Classes
class RulerSet
Class representing a single screen's set of rulers.
Public Member Functions
MeaRulerTool (MeaToolMgr *mgr)
Constructs a new instance of the Ruler tool.
virtual ~MeaRulerTool ()
Hides and then destroys the Ruler tool.
virtual void Enable () override
Displays the Ruler tool.
virtual void Disable () override
Hides the Ruler tool.
virtual void Update (MeaUpdateReason reason) override
Positions and draws the rulers.
virtual void SaveProfile (MeaProfile &profile) override
Persists the state of the tool to the specified profile object.
virtual void LoadProfile (MeaProfile &profile) override
Restores the state of the tool from the specified profile object.
virtual void MasterReset () override
Resets the tool to its default state.
virtual CString GetToolName () const override
Returns the name of the tool.
virtual const POINT & GetPosition () const override
Returns the tool's current position which, for the Ruler tool, is always the position (0, 0).
virtual void ColorsChanged () override
Called to notify the tool that the colors in the MeaColors class have been changed.
void SetIndicator (MeaRuler::IndicatorId indId, const POINT &indicatorPos)
Sets the position of the specified ruler indicator.
virtual void OnRulerMove (const RulerInfo *info) override
Called when the user drags a ruler to a new position.
Public Member Functions inherited from MeaTool
MeaTool (MeaToolMgr *mgr)
Base class constructor.
virtual ~MeaTool ()
Destroys the tool.
virtual void Enable ()
Typically used by derived classes to show the tool.
virtual void Disable ()
Typically used by derived classes to hide the tool.
virtual void Update (MeaUpdateReason reason)
Used by derived classes to update the display of their data.
virtual bool IsRadioTool ()
Indicates whether the derived tool is a radio tool and cannot be enabled until any other enabled Radio tool is disabled.
virtual void SetPosition (MeaFields which, int pixels)
Sets the position of the tool.
virtual const POINT & GetPosition () const =0
Returns the tool's current position.
virtual void IncPosition (MeaFields which)
Increments the specified position field.
virtual void DecPosition (MeaFields which)
Decrements the specified position field.
virtual CString GetToolName () const =0
Returns the name of the tool.
virtual void SaveProfile (MeaProfile &profile)
Persists the state of the tool to the specified profile object.
virtual void LoadProfile (MeaProfile &profile)
Restores the state of the tool from the specified profile object.
virtual void MasterReset ()
Resets the tool to its default state.
virtual void ColorsChanged ()
Called to notify the tool that the colors in the MeaColors class have been changed.
bool IsEnabled () const
Indicates whether the tool is enabled.
Public Member Functions inherited from MeaRulerCallback
MeaRulerCallback ()
Constructs a callback object.
virtual ~MeaRulerCallback ()
Destroys a callback object.
virtual void OnRulerMove (const RulerInfo *info)
Called when the user presses the left mouse button and then moves the mouse pointer while over the ruler (i.e.
Static Public Attributes
static constexpr bool kShowRulers { false }
Indicates if the rulers are shown by default.
static const CString kToolName
"RulerTool"
Private Types
typedef std::vector< RulerSet * > Rulers
Collection of rulers.
Private Member Functions
MeaRulerTool (const MeaRulerTool &)
Copy constructor is purposely undefined.
MeaRulerTool & operator= (const MeaRulerTool &)
Assignment operator is purposely undefined.
void PositionRulers (int rulerIdx)
Repositions the specified ruler to the location specified in the corresponding member variable.
void UpdateRulers (int rulerIdx)
Updates the visual state of the specified ruler.
void PositionIndicators (int rulerIdx, MeaRuler::IndicatorId indId)
Repositions the specified ruler's indicators to the location specified in the corresponding member variable.
Private Attributes
CPoint m_indicatorPos [MeaRuler::NumIndicators]
Position of each ruler indicator, in pixels.
Rulers m_rulers
Collection of all rulers on all screens.
Additional Inherited Members
Protected Attributes inherited from MeaTool
MeaToolMgr * m_mgr
Tool manager.
bool m_enabled
Indicates whether the tool is enabled.
Static Protected Attributes inherited from MeaTool
static POINT m_defaultPos { 0, 0 }
A default position used by tools that do not have a defined position. This position is returned by the GetPosition() method.
Detailed Description
Ruler measurement tool.
The Ruler tool provides vertical and horizontal rulers on each screen. The rulers can be dragged to any position on the screen.
Constructor & Destructor Documentation
MeaRulerTool()
MeaRulerTool::MeaRulerTool (MeaToolMgr * mgr) explicit
Constructs a new instance of the Ruler tool.
To use a newly constructed Ruler tool, the Enable() method must be called.
Parameters
mgr [in] Tool manager parent of the Ruler tool.
References MeaScreenMgr::GetNumScreens(), MeaSingleton_T< MeaScreenMgr >::Instance(), m_indicatorPos, m_rulers, and MeaRuler::NumIndicators.
Member Function Documentation
ColorsChanged()
void MeaRulerTool::ColorsChanged () override virtual
Called to notify the tool that the colors in the MeaColors class have been changed.
The rulers are redrawn in their new colors.
Reimplemented from MeaTool.
References MeaColors::Get(), MeaColors::GetA(), m_rulers, MeaColors::RulerBack, MeaColors::RulerBorder, and MeaColors::RulerOpacity.
Disable()
void MeaRulerTool::Disable () override virtual
Hides the Ruler tool.
Reimplemented from MeaTool.
References MeaTool::Disable(), MeaTool::IsEnabled(), and m_rulers.
Referenced by LoadProfile(), MasterReset(), and ~MeaRulerTool().
Enable()
void MeaRulerTool::Enable () override virtual
Displays the Ruler tool.
Reimplemented from MeaTool.
References MeaScreenMgr::AtEnd(), MeaTool::Enable(), MeaColors::Get(), MeaColors::GetA(), MeaScreenMgr::GetScreenIter(), MeaScreenMgr::GetScreenRect(), MeaRuler::Horizontal, MeaSingleton_T< MeaScreenMgr >::Instance(), MeaTool::IsEnabled(), m_rulers, MeaRuler::NumIndicators, PositionIndicators(), PositionRulers(), MeaColors::RulerBack, MeaColors::RulerBorder, MeaColors::RulerOpacity, and MeaRuler::Vertical.
Referenced by LoadProfile(), and MasterReset().
GetPosition()
const POINT & MeaRulerTool::GetPosition () const override virtual
Returns the tool's current position which, for the Ruler tool, is always the position (0, 0).
Returns
The position (0, 0)
Implements MeaTool.
References MeaTool::m_defaultPos.
GetToolName()
CString MeaRulerTool::GetToolName () const override virtual
Returns the name of the tool.
Each tool has a unique name which is used to identify the tool in profiles and position logs.
Returns
Name of the tool ("RulerTool").
Implements MeaTool.
References kToolName.
Referenced by MeaToolMgr::MeaToolMgr().
LoadProfile()
void MeaRulerTool::LoadProfile (MeaProfile & profile) override virtual
Restores the state of the tool from the specified profile object.
Parameters
profile [in] The source for the state information. Typically an MeaFileProfile or MeaRegistryProfile object.
Reimplemented from MeaTool.
References MeaScreenMgr::AtEnd(), Disable(), Enable(), MeaScreenMgr::GetScreenIter(), MeaScreenMgr::GetScreenRect(), MeaSingleton_T< MeaScreenMgr >::Instance(), kShowRulers, m_rulers, MeaProfile::ReadBool(), and MeaProfile::ReadInt().
MasterReset()
void MeaRulerTool::MasterReset () override virtual
Resets the tool to its default state.
Reimplemented from MeaTool.
References Disable(), Enable(), and kShowRulers.
OnRulerMove()
void MeaRulerTool::OnRulerMove (const RulerInfo * info) override virtual
Called when the user drags a ruler to a new position.
This method is responsible for actually repositioning the specified ruler to the new position.
Parameters
info [in] Ruler information structure
Reimplemented from MeaRulerCallback.
References MeaRuler::GetOrientation(), MeaRuler::Horizontal, MeaRulerCallback::RulerInfo::id, m_rulers, MeaRulerTool::RulerSet::m_xPos, MeaRulerTool::RulerSet::m_yPos, MeaAssert, MeaRulerCallback::RulerInfo::position, MeaRulerCallback::RulerInfo::ruler, and MeaRuler::SetPosition().
PositionIndicators()
void MeaRulerTool::PositionIndicators (int rulerIdx, MeaRuler::IndicatorId indId) private
Repositions the specified ruler's indicators to the location specified in the corresponding member variable.
Parameters
rulerIdx [in] Index specifying the ruler whose indicator is to be repositioned
indId [in] ID of the indicator to reposition
References MeaTool::IsEnabled(), m_indicatorPos, and m_rulers.
Referenced by Enable(), SetIndicator(), and Update().
PositionRulers()
void MeaRulerTool::PositionRulers (int rulerIdx) private
Repositions the specified ruler to the location specified in the corresponding member variable.
Parameters
rulerIdx [in] Index specifying the ruler to reposition
References m_rulers.
Referenced by Enable(), and Update().
SaveProfile()
void MeaRulerTool::SaveProfile (MeaProfile & profile) override virtual
Persists the state of the tool to the specified profile object.
Parameters
profile [in] The destination for the state information. Typically an MeaFileProfile or MeaRegistryProfile object.
Reimplemented from MeaTool.
References MeaRuler::GetPosition(), MeaTool::IsEnabled(), MeaRulerTool::RulerSet::m_hRuler, m_rulers, MeaRulerTool::RulerSet::m_vRuler, MeaRulerTool::RulerSet::m_xPos, MeaRulerTool::RulerSet::m_yPos, MeaProfile::WriteBool(), and MeaProfile::WriteInt().
SetIndicator()
void MeaRulerTool::SetIndicator (MeaRuler::IndicatorId indId, const POINT & indicatorPos)
Sets the position of the specified ruler indicator.
The ruler indicator shows the position of a crosshair, pointer or some other characteristic of a radio tool.
Parameters
indId [in] Specifies the indicator to position
indicatorPos [in] Position for the indicator, in pixels
References m_indicatorPos, m_rulers, and PositionIndicators().
Referenced by MeaToolMgr::EnableRegionFields(), MeaToolMgr::ShowXY1(), MeaToolMgr::ShowXY2(), and MeaToolMgr::ShowXYV().
Update()
void MeaRulerTool::Update (MeaUpdateReason reason) override virtual
Positions and draws the rulers.
Parameters
reason [in] Reason why the update has been requested
Reimplemented from MeaTool.
References MeaTool::IsEnabled(), m_rulers, MeaRuler::NumIndicators, PositionIndicators(), PositionRulers(), MeaTool::Update(), and UpdateRulers().
UpdateRulers()
void MeaRulerTool::UpdateRulers (int rulerIdx) private
Updates the visual state of the specified ruler.
Parameters
rulerIdx [in] Index specifying the ruler to update
References m_rulers.
Referenced by Update().
The documentation for this class was generated from the following files:
RulerTool.h
RulerTool.cpp
Copyright 2011 C Thing Software