Meazure: MeaCircle Class Reference
MeaCircle Class Reference
A circle element.
#include <Circle.h>
Public Member Functions
MeaCircle ()
Constructs a circle.
virtual ~MeaCircle ()
Destroys the circle.
bool Create (const CWnd *parent=nullptr)
Creates the window for the circle.
virtual void Hide () override
Hides the graphic.
void SetPosition (const POINT &center, const POINT &perimeter)
Sets the position and size of the circle.
void GetPosition (POINT &center, POINT &perimeter)
Obtains the position and size of the circle.
int GetRadius () const
Calculates the radius of the circle based on the center and perimeter points.
void SetColor (COLORREF color)
Sets the color of the circle's line.
Public Member Functions inherited from MeaGraphic
MeaGraphic ()
Base class constructor.
virtual ~MeaGraphic ()
Base class destructor.
bool Create (LPCTSTR classname, const SIZE &size, const CWnd *parent, UINT id=0xFFFF)
Creates the window for the graphic.
virtual void Show ()
Displays the graphic.
virtual void Hide ()
Hides the graphic.
void SetAbove (const CWnd *winBelow)
Changes the z-order of the graphic window so that it if above the specified window.
Protected Member Functions
afx_msg LRESULT OnHPTimer (WPARAM wParam, LPARAM lParam)
Windows GDI was not optimized for doing crazy things like creating a window that is a thin lined circle.
Private Member Functions
MeaCircle (const MeaCircle &)
Copy constructor is purposely undefined.
MeaCircle & operator= (const MeaCircle &)
Assignment operator is purposely undefined.
void PlotCircle (int radius)
The circular window region is composed of single pixel rectangles arranged in a circle.
void AddPoint (int x, int y)
The circular window is composed of a series of single pixel rectangles arranged in a circle.
Private Attributes
CPoint m_center
Location of the center of the circle, in pixels.
CPoint m_perimeter
Location of a point on the perimeter of the circle, in pixels.
CRect m_clipRect
Virtual rectangle formed by all display monitors, in pixels.
CBrush * m_foreBrush
Brush for drawing the circle.
MeaTimer m_timer
Timer for delayed drawing of circle to reduce visual artifacts.
POINT * m_arr
Array of coordinates for each rectangle making up the circular region.
unsigned int m_count
Number of rectangles in the circular region.
Static Private Attributes
static const CSize kMargin
Padding around the circle, in pixels.
static int * m_varr { nullptr }
Number of coordinates comprising each polygon making up the circular region (always 4 in our case)
Additional Inherited Members
Protected Attributes inherited from MeaGraphic
UINT m_id
ID for the graphic.
bool m_visible
Indicates whether the graphic is shown or hidden.
const CWnd * m_parent
Graphic's parent window or nullptr if graphic is a popup window.
Static Protected Attributes inherited from MeaGraphic
static constexpr int kInitCoord { -1000 }
An arbitrary initial coordinate for placing new graphics.
Detailed Description
A circle element.
The circle is positioned by specifying the center and it is sized by specifying a point on the perimeter. The circle is formed by using a series of circularly arranged polygonal regions to create a thin circular window.
Constructor & Destructor Documentation
MeaCircle()
MeaCircle::MeaCircle ()
Constructs a circle.
Prior to displaying the circle with the Show() method, the Create() method must be called to create the circle's window.
Member Function Documentation
AddPoint()
void MeaCircle::AddPoint (int x, int y) inline private
The circular window is composed of a series of single pixel rectangles arranged in a circle.
At each point on the circle the coordinates of a rectangle surrounding that point are added to an array of points. This array of points will eventually be handed to the GDI function CreatePolyPolygonRgn.
Parameters
x [in] X coordinate of the point on the circle
y [in] Y coordinate of the point on the circle
References m_arr, m_clipRect, and m_count.
Referenced by PlotCircle().
Create()
bool MeaCircle::Create (const CWnd * parent = nullptr)
Creates the window for the circle.
This method must be called before the circle can be displayed and before any operation that attempts to manipulate the circle's window.
Parameters
parent [in] Parent window or nullptr if the circle does not have an immediate parent. If a parent window is specified, the circle is created as a child window (WS_CHILD). Otherwise the circle is created as a popup window (WS_POPUP) and is assigned the main window as a parent.
Returns
true if the window is created successfully.
References MeaLayout::CalcCircumference(), MeaLayout::CalcLength(), MeaTimer::Create(), MeaGraphic::Create(), MeaScreenMgr::GetVirtualRect(), MeaSingleton_T< MeaScreenMgr >::Instance(), m_arr, m_clipRect, m_foreBrush, m_timer, and m_varr.
Referenced by MeaCircleTool::Create().
GetPosition()
void MeaCircle::GetPosition (POINT & center, POINT & perimeter) inline
Obtains the position and size of the circle.
Parameters
center [out] Location of the center of the circle, in pixels
perimeter [out] Location of a point on the perimeter of the circle, in pixels
References m_center, and m_perimeter.
GetRadius()
int MeaCircle::GetRadius () const inline
Calculates the radius of the circle based on the center and perimeter points.
The following classic equation is used:
Returns
The length of the circle's radius, in pixels.
References MeaLayout::CalcLength(), m_center, and m_perimeter.
Referenced by MeaCircleTool::GetPosition(), MeaCircleTool::GetRegion(), OnHPTimer(), and MeaCircleTool::Update().
Hide()
void MeaCircle::Hide () override virtual
Hides the graphic.
Call the Create() method prior to calling this method for the first time.
Reimplemented from MeaGraphic.
References MeaGraphic::Hide(), m_timer, and MeaTimer::Stop().
Referenced by MeaCircleTool::Disable().
OnHPTimer()
LRESULT MeaCircle::OnHPTimer (WPARAM wParam, LPARAM lParam) protected
Windows GDI was not optimized for doing crazy things like creating a window that is a thin lined circle.
Because of this, drawing the window is very expensive. To minimize visual artifacts when the circle is repositioned or resized a timer is used to effectively add damping to the drawing process. Even if the user may be making quick changes to the circle, the time delay reduces the number of redraws. When the SetPosition() method is called, it just sets a timer and returns. When the timer expires, this method is called and actually redraws the window.
Parameters
wParam [in] not used
lParam [in] not used
Returns
The return is not used so 0 is returned.
References GetRadius(), kMargin, m_arr, m_center, m_count, m_varr, MeaGraphic::m_visible, MeaAssert, PlotCircle(), and MeaGraphic::Show().
PlotCircle()
void MeaCircle::PlotCircle (int radius) private
The circular window region is composed of single pixel rectangles arranged in a circle.
The location of each rectangle is determined using an algorithm from the paper "A Fast Bresenham Type Algorithm for Drawing Circles" by John Kennedy, Mathematics Dept., Santa Monica College (http://homepage.smc.edu/kennedy_john/BCIRCLE.PDF, rkenn.nosp@m.edy@.nosp@m.ix.ne.nosp@m.tcom.nosp@m..com).
Parameters
radius [in] radius of the circle, in pixels
References AddPoint(), m_center, and m_count.
Referenced by OnHPTimer().
SetColor()
void MeaCircle::SetColor (COLORREF color)
Sets the color of the circle's line.
Parameters
color [in] Color value defined by the Windows GDI RGB macro.
References m_foreBrush.
Referenced by MeaCircleTool::ColorsChanged().
SetPosition()
void MeaCircle::SetPosition (const POINT & center, const POINT & perimeter)
Sets the position and size of the circle.
Parameters
center [in] Location of the center of the circle, in pixels
perimeter [in] Location of a point on the perimeter of the circle, in pixels
References m_center, m_perimeter, m_timer, MeaGraphic::m_visible, MeaGraphic::Show(), and MeaTimer::Start().
Referenced by MeaCircleTool::OnCHMove(), and MeaCircleTool::SetPosition().
The documentation for this class was generated from the following files:
Circle.h
Circle.cpp
Copyright 2011 C Thing Software