Meazure: MeaMagnifier Class Reference
MeaMagnifier Class Reference
Provides a screen magnifier window complete with freeze frame, optional pixel grid and pixel color capture.
#include <Magnifier.h>
Public Types
enum ColorFmt {
RGBFmt = 0 ,
RGBHexFmt = 1 ,
CMYFmt = 2 ,
CMYKFmt = 3 ,
HSLFmt = 4 ,
YCbCrFmt = 5 ,
YIQFmt = 6
}
The magnifier displays the color of the pixel at the center of the window.
enum class RunState {
Run = 0 ,
Freeze = 1
}
Indicates whether the magnifier is running or in freeze frame mode.
Public Member Functions
MeaMagnifier ()
Constructs a magnifier.
virtual ~MeaMagnifier ()
Destroys a magnifier instance.
bool Create (const POINT &topLeft, int width, CWnd *parentWnd)
Creates the window for the magnifier.
void SaveProfile (MeaProfile &profile)
Persists the magnifier settings to the specified profile object.
void LoadProfile (MeaProfile &profile)
Restores the magnifier settings from the specified profile object.
void MasterReset ()
Called to tell the magnifier to restore its default state.
void Enable ()
Displays the magnifier window and places it in the desired run mode.
void Disable ()
Hides the magnifier window.
void Update ()
Forces a redraw of the magnifier window.
bool IsEnabled () const
Indicates whether the magnifier is visible.
int GetHeight () const
Returns the height of the magnifier.
void ZoomIn ()
Zooms in the magnifier.
void ZoomOut ()
Zooms out the magnifier.
bool CanZoomIn () const
Indicates whether it is possible to zoom in the magnifier.
bool CanZoomOut () const
Indicates whether it is possible to zoom out the magnifier.
void SetZoomIndex (int zoomIndex)
Sets a specific zoom factor index.
int GetZoomIndex () const
Returns the current zoom factor index.
void SetColorFmt (ColorFmt colorFmt)
Sets the color display format.
ColorFmt GetColorFmt () const
Returns the current color display format.
void SetRunState (RunState runState)
Set the display mode of the magnifier to either running or frozen.
RunState GetRunState () const
Returns the display mode of the magnifier.
void SetShowGrid (bool show)
Displays or hides the magnifier grid.
bool IsShowGrid () const
Indicates whether the magnifier grid is displayed.
MeaNumberField * GetFieldFocus ()
Returns a pointer to the pixel color display text field if it has the keyboard focus, and nullptr if it does not.
Static Public Attributes
static constexpr int kDefZoomIndex { 1 }
Default index for the zoom factor.
static constexpr bool kDefShowGrid { true }
Indicates whether the grid should be display by default.
static constexpr ColorFmt kDefColorFmt { RGBFmt }
Default color display format.
static constexpr RunState kDefRunState { RunState::Run }
Default magnifier display mode.
Protected Member Functions
afx_msg void OnPaint ()
Repaints the magnifier window.
afx_msg LRESULT OnHPTimer (WPARAM, LPARAM)
Called when the timer expires and it is time to capture and draw another magnified view.
afx_msg void OnHScroll (UINT nSBCode, UINT nPos, CScrollBar *pScrollBar)
Called when the zoom factor slider is moved.
afx_msg void OnRunState ()
Called when the pause button is toggled to either freeze the magnifier image or start it running again.
afx_msg LRESULT OnHelpHitTest (WPARAM, LPARAM lparam)
Called to display the magnifier help topic when help is requested.
Private Member Functions
void Draw (HDC hDC)
Reads an appropriately sized region around the cursor and zooms it into the magnifier window.
void ChangeRunState (RunState runState)
Performs the work of changing the display run mode.
Private Attributes
CPoint m_curPos
Current position being magnified.
bool m_enabled
Indicates whether the magnifier is visible.
RunState m_runState
Display mode run state.
MeaImageButton m_runStateBtn
Magnifier pause button.
MeaTimer m_timer
Refresh timer.
ColorFmt m_colorFmt
Pixel color display format.
MeaLabel m_swatchLabel
Label for the pixel color swatch.
MeaNumberField m_swatchField
Text field to display the pixel color.
CWnd m_swatchWin
Window for the pixel color swatch.
MeaLabel m_zoomLabel
Label for the zoom factor slider.
CSliderCtrl m_zoomSlider
Zoom factor slider.
MeaLabel m_factorLabel
Zoom factor label.
int m_zoomIndex
Currently selected zoom factor index.
bool m_showGrid
Indicates whether the grid should be displayed, if possible.
int m_magHeight
Height of the magnifier, in pixels.
Static Private Attributes
static constexpr int kUpdateRate { 70 }
Magnifier refresh rate, in milliseconds.
static constexpr int kZoomHeight { 22 }
Height of the zoom factor slider, in pixels.
static constexpr SIZE kMargin { 5, 5 }
Margin around the magnifier window.
static constexpr int kSwatchWidth { 40 }
Width of the pixel color swatch, in pixels.
static constexpr int kZoomFactorArr [] { 1, 2, 3, 4, 6, 8, 16, 32 }
Arrays of zoom factors selected by the zoom index.
static constexpr int kMaxZoomIndex { sizeof(kZoomFactorArr) / sizeof(int) - 1 }
Index of the maximum allowable zoom factor.
static constexpr int kMinZoomIndex { 0 }
Index of the minimum allowable zoom factor.
static constexpr int kMinGridFactor { 6 }
Minimum zoom factor below which the grid is not displayed.
Detailed Description
Provides a screen magnifier window complete with freeze frame, optional pixel grid and pixel color capture.
A number of color spaces are available for the display of the captured pixel color. The contents of the screen are read and displayed in this window using a 1X through 32X zoom factor. Note that layered windows will not appear in the magnifier. Similarly, windows rendered using DirectX will appear black since they are drawing directly to the hardware and displaying using a hardware overlay.
Typically, the magnifier is centered on the active graphic element, usually a crosshair.
Member Enumeration Documentation
ColorFmt
enum MeaMagnifier::ColorFmt
The magnifier displays the color of the pixel at the center of the window.
This point typically corresponds to the hot spot of an active graphic element such as a crosshair. The color can be displayed in a number of different color spaces. This enumeration indicates which color space is in use.
Enumerator
RGBFmt
Red, green and blue as individual values between 0 and 255 inclusive.
RGBHexFmt
Red, green and blue as a composite hex number of the form #RRGGBB.
CMYFmt
Cyan, magenta and yellow as individual values between 0 and 255 inclusive.
CMYKFmt
Cyan, magenta, yellow and black as individual values.
HSLFmt
Hue, saturation and lightness as individual values.
YCbCrFmt
Luminance and chrominance as individual values.
YIQFmt
Luminance, and inphase and quadrature chrominance channels.
RunState
enum class MeaMagnifier::RunState strong
Indicates whether the magnifier is running or in freeze frame mode.
Enumerator
Run
Magnifier is in real time mode.
Freeze
Magnifier is in freeze frame mode.
Constructor & Destructor Documentation
MeaMagnifier()
MeaMagnifier::MeaMagnifier ()
Constructs a magnifier.
To use the magnifier the Create method must be called.
Member Function Documentation
CanZoomIn()
bool MeaMagnifier::CanZoomIn () const inline
Indicates whether it is possible to zoom in the magnifier.
Returns
true if the magnifier can zoom in further.
References kMaxZoomIndex, and m_zoomIndex.
Referenced by AppView::OnUpdateZoomIn().
CanZoomOut()
bool MeaMagnifier::CanZoomOut () const inline
Indicates whether it is possible to zoom out the magnifier.
Returns
true if the magnifier can zoom out further.
References kMinZoomIndex, and m_zoomIndex.
Referenced by AppView::OnUpdateZoomOut().
ChangeRunState()
void MeaMagnifier::ChangeRunState (RunState runState) private
Performs the work of changing the display run mode.
Parameters
runState [in] Indicates the desired display run state.
References m_enabled, m_runState, m_timer, OnHPTimer(), Run, and MeaTimer::Stop().
Referenced by OnRunState(), and SetRunState().
Create()
bool MeaMagnifier::Create (const POINT & topLeft, int width, CWnd * parentWnd)
Creates the window for the magnifier.
Parameters
topLeft [in] Location of the top left corner of the magnifier window.
width [in] Width of the magnifier, in pixels. The aspect ratio of the magnifier is fixed, so the width determines the height.
parentWnd [in] Parent window for the magnifier.
Returns
true if the window was created successfully.
References MeaLayout::AlignCenter(), MeaTimer::Create(), MeaImageButton::Create(), MeaNumberField::Create(), MeaLabel::Create(), kMargin, kMaxZoomIndex, kMinZoomIndex, kSwatchWidth, kZoomHeight, MeaImageButton::LoadBitmaps(), m_factorLabel, m_magHeight, m_runStateBtn, m_swatchField, m_swatchLabel, m_swatchWin, m_timer, m_zoomLabel, m_zoomSlider, OnHPTimer(), MeaLayout::PlaceAfter(), MeaImageButton::SetToggleType(), and MeaLayout::SetWindowSize().
Referenced by AppView::OnCreate().
Draw()
void MeaMagnifier::Draw (HDC hDC) private
Reads an appropriately sized region around the cursor and zooms it into the magnifier window.
Parameters
hDC [in] Magnifier window device context.
References CMYFmt, CMYKFmt, MeaScreenMgr::GetScreenIter(), MeaScreenMgr::GetScreenRect(), HSLFmt, MeaSingleton_T< MeaScreenMgr >::Instance(), kMinGridFactor, kZoomFactorArr, m_colorFmt, m_curPos, m_runState, m_showGrid, m_swatchField, m_swatchLabel, m_swatchWin, m_zoomIndex, MeaGetPositionMsg, RGBFmt, RGBHexFmt, MeaColors::RGBtoHSL(), Run, YCbCrFmt, and YIQFmt.
Referenced by OnPaint().
GetColorFmt()
ColorFmt MeaMagnifier::GetColorFmt () const inline
Returns the current color display format.
Returns
Color display format specifier.
References m_colorFmt.
Referenced by AppView::OnUpdateColorFmt().
GetFieldFocus()
MeaNumberField * MeaMagnifier::GetFieldFocus () inline
Returns a pointer to the pixel color display text field if it has the keyboard focus, and nullptr if it does not.
Returns
Pointer to the color display text field if it has the focus, and nullptr if it does not.
References m_swatchField.
Referenced by AppView::OnEditCopy(), and AppView::OnUpdateEditCopy().
GetHeight()
int MeaMagnifier::GetHeight () const inline
Returns the height of the magnifier.
Returns
Height of the magnifier, in pixels.
References m_magHeight.
Referenced by AppView::ViewMagnifier().
GetRunState()
RunState MeaMagnifier::GetRunState () const inline
Returns the display mode of the magnifier.
Returns
Magnifier display mode.
References m_runState.
Referenced by AppView::OnRunState(), OnRunState(), and AppView::OnUpdateRunState().
GetZoomIndex()
int MeaMagnifier::GetZoomIndex () const inline
Returns the current zoom factor index.
Returns
Index that selects the zoom factor.
References m_zoomIndex.
IsEnabled()
bool MeaMagnifier::IsEnabled () const inline
Indicates whether the magnifier is visible.
Returns
true if the magnifier is enabled.
References m_enabled.
Referenced by AppView::CheckMargins(), AppView::IsCollapsed(), AppView::LoadProfile(), AppView::OnCollapse(), AppView::OnMagnifier(), AppView::OnUpdateMagnifier(), AppView::SaveProfile(), Update(), and AppView::ViewMagnifier().
IsShowGrid()
bool MeaMagnifier::IsShowGrid () const inline
Indicates whether the magnifier grid is displayed.
Note that regardless of whether the magnifier grid is selected for display, it will not be displayed if the zoom factor is low because it would obscure the display.
Returns
true if the magnifier grid is selected for display.
References m_showGrid.
Referenced by AppView::OnShowMagGrid(), and AppView::OnUpdateShowMagGrid().
LoadProfile()
void MeaMagnifier::LoadProfile (MeaProfile & profile)
Restores the magnifier settings from the specified profile object.
Parameters
profile [in] Persistence object.
References m_colorFmt, m_showGrid, m_zoomIndex, MeaProfile::ReadBool(), MeaProfile::ReadInt(), SetColorFmt(), SetShowGrid(), SetZoomIndex(), and MeaProfile::UserInitiated().
Referenced by AppView::LoadProfile().
OnHelpHitTest()
LRESULT MeaMagnifier::OnHelpHitTest (WPARAM , LPARAM lparam) protected
Called to display the magnifier help topic when help is requested.
Parameters
lparam [in] Cursor coordinates.
Returns
Help ID corresponding to section where mouse clicked.
OnHPTimer()
LRESULT MeaMagnifier::OnHPTimer (WPARAM , LPARAM) protected
Called when the timer expires and it is time to capture and draw another magnified view.
Returns
Always zero.
References kUpdateRate, m_timer, MeaTimer::Start(), and Update().
Referenced by ChangeRunState(), Create(), and Enable().
SaveProfile()
void MeaMagnifier::SaveProfile (MeaProfile & profile)
Persists the magnifier settings to the specified profile object.
Parameters
profile [in] Persistence object.
References m_colorFmt, m_showGrid, m_zoomIndex, MeaProfile::UserInitiated(), MeaProfile::WriteBool(), and MeaProfile::WriteInt().
Referenced by AppView::SaveProfile().
SetColorFmt()
void MeaMagnifier::SetColorFmt (ColorFmt colorFmt) inline
Sets the color display format.
Parameters
colorFmt [in] Color format specifier.
References m_colorFmt, and Update().
Referenced by LoadProfile(), MasterReset(), and AppView::OnColorFmt().
SetRunState()
void MeaMagnifier::SetRunState (RunState runState)
Set the display mode of the magnifier to either running or frozen.
Parameters
runState [in] Display mode.
References ChangeRunState(), Freeze, m_runState, m_runStateBtn, and MeaImageButton::SetState().
Referenced by MasterReset(), and AppView::OnRunState().
SetShowGrid()
void MeaMagnifier::SetShowGrid (bool show) inline
Displays or hides the magnifier grid.
The grid is one pixel in dimension. Note that regardless of the setting, the grid is not displayed for lower zoom factors because it would completely obscure the display.
Parameters
show [in] Indicates whether to show or hide the magnifier grid.
References m_showGrid, and Update().
Referenced by LoadProfile(), MasterReset(), and AppView::OnShowMagGrid().
SetZoomIndex()
void MeaMagnifier::SetZoomIndex (int zoomIndex) inline
Sets a specific zoom factor index.
Parameters
zoomIndex [in] Index that selects a zoom factor.
References kMaxZoomIndex, kMinZoomIndex, m_zoomIndex, m_zoomSlider, and Update().
Referenced by LoadProfile(), MasterReset(), ZoomIn(), and ZoomOut().
ZoomIn()
void MeaMagnifier::ZoomIn () inline
Zooms in the magnifier.
If the magnifier is already at the minimum zoom, calling this method has no effect.
References m_zoomIndex, and SetZoomIndex().
Referenced by AppView::OnZoomIn().
ZoomOut()
void MeaMagnifier::ZoomOut () inline
Zooms out the magnifier.
If the magnifier is already at the maximum zoom, calling this method has no effect.
References m_zoomIndex, and SetZoomIndex().
Referenced by AppView::OnZoomOut().
The documentation for this class was generated from the following files:
Magnifier.h
Magnifier.cpp
Copyright 2011 C Thing Software