Meazure: MeaScreenTool Class Reference
MeaScreenTool Class Reference
Screen information tool.
#include <ScreenTool.h>
Public Member Functions
MeaScreenTool (MeaToolMgr &mgr, const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Constructs a new instance of the Screen information tool.
virtual ~MeaScreenTool ()
Disables and then destroys the Screen information tool.
virtual void LoadProfile (MeaProfile &profile) override
This class uses this method to call the SetPosition method to set the information about the current display screen.
virtual void Enable () override
Enables the display of the tool.
virtual void Disable () override
Disables the tool.
virtual void Update (MeaUpdateReason reason) override
Updates the display of the tool's information.
virtual PCTSTR GetToolName () const override
Returns the name of the tool.
void SetPosition (const POINT &pos)
Provides the tool a position so that it can determine which display screen's information to provide.
virtual const POINT & GetPosition () const override
Returns the tool's current position which, for the Screen tool, is always the position (0, 0).
Public Member Functions inherited from MeaTool
MeaTool (MeaToolMgr &mgr, const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Base class constructor.
virtual ~MeaTool ()=default
Destroys the tool.
virtual void Enable ()
Typically used by derived classes to show the tool.
virtual void Disable ()
Typically used by derived classes to hide the tool.
virtual void Update (MeaUpdateReason reason)
Used by derived classes to update the display of their data.
virtual bool IsRadioTool ()
Indicates whether the derived tool is a radio tool and cannot be enabled until any other enabled Radio tool is disabled.
virtual void SetPosition (MeaDataFieldId which, int pixels)
Sets the position of the tool.
virtual const POINT & GetPosition () const =0
Returns the tool's current position.
virtual void IncPosition (MeaDataFieldId which)
Increments the specified position field.
virtual void DecPosition (MeaDataFieldId which)
Decrements the specified position field.
virtual PCTSTR GetToolName () const =0
Returns the name of the tool.
virtual void SaveProfile (MeaProfile &profile)
Persists the state of the tool to the specified profile object.
virtual void LoadProfile (MeaProfile &profile)
Restores the state of the tool from the specified profile object.
virtual void MasterReset ()
Resets the tool to its default state.
virtual void ColorsChanged ()
Called to notify the tool that the colors in the MeaColors class have been changed.
bool IsEnabled () const
Indicates whether the tool is enabled.
Static Public Attributes
static constexpr PCTSTR kToolName { _T("ScreenTool") }
Private Attributes
CRect m_rect
Rectangle representing the current display screen.
MeaFSize m_res
Resolution of the current display screen.
bool m_anyOSRes
Indicates if any of the screen resolutions are not calibrated (i.e. the OS reported resolution is used)
CString m_name
Name of the display screen.
Additional Inherited Members
Protected Attributes inherited from MeaTool
MeaToolMgr & m_mgr
Tool manager.
const MeaScreenProvider & m_screenProvider
Screen information provider.
const MeaUnitsProvider & m_unitsProvider
Units information provider.
bool m_enabled
Indicates whether the tool is enabled.
Static Protected Attributes inherited from MeaTool
static const CPoint m_defaultPos
A default position used by tools that do not have a defined position.
Detailed Description
Screen information tool.
This tool provides size and resolution information for each display screen attached to the system.
Constructor & Destructor Documentation
MeaScreenTool()
MeaScreenTool::MeaScreenTool (MeaToolMgr & mgr, const MeaScreenProvider & screenProvider, const MeaUnitsProvider & unitsProvider) explicit
Constructs a new instance of the Screen information tool.
To use a newly constructed Screen info tool, the Enable() method must be called.
Parameters
mgr [in] Tool manager parent of the Screen info tool
screenProvider [in] Screen information provider
unitsProvider [in] Units information provider
Member Function Documentation
Disable()
void MeaScreenTool::Disable () override virtual
Disables the tool.
This method must be called to properly tear down the tool.
Reimplemented from MeaTool.
References MeaTool::Disable(), and MeaTool::IsEnabled().
Referenced by ~MeaScreenTool().
Enable()
void MeaScreenTool::Enable () override virtual
Enables the display of the tool.
This method must be called to properly set up the tool for use.
Reimplemented from MeaTool.
References MeaTool::Enable(), MeaToolMgr::EnableScreenFields(), MeaTool::IsEnabled(), MeaTool::m_mgr, MeaResXField, MeaResYField, MeaScreenHeightField, MeaScreenWidthField, NormalUpdate, and Update().
GetPosition()
const POINT & MeaScreenTool::GetPosition () const override virtual
Returns the tool's current position which, for the Screen tool, is always the position (0, 0).
Returns
The position (0, 0)
Implements MeaTool.
References MeaTool::m_defaultPos.
GetToolName()
PCTSTR MeaScreenTool::GetToolName () const override virtual
Returns the name of the tool.
Each tool has a unique name which is used to identify the tool in profiles and position logs.
Returns
Always "ScreenTool". The memory for the string is owned by the tool.
Implements MeaTool.
LoadProfile()
void MeaScreenTool::LoadProfile (MeaProfile & profile) override virtual
This class uses this method to call the SetPosition method to set the information about the current display screen.
Parameters
profile [in] Not used.
Reimplemented from MeaTool.
References SetPosition().
SetPosition()
void MeaScreenTool::SetPosition (const POINT & pos)
Provides the tool a position so that it can determine which display screen's information to provide.
Parameters
pos [in] Position on a display screen, in pixels
References MeaScreenProvider::AnyOSRes(), MeaFSize::cx, MeaFSize::cy, MeaScreenProvider::GetScreenIter(), MeaScreenProvider::GetScreenName(), MeaScreenProvider::GetScreenRect(), MeaScreenProvider::GetScreenRes(), MeaNumericUtils::IsEqualF(), m_anyOSRes, m_name, m_rect, m_res, MeaTool::m_screenProvider, NormalUpdate, and Update().
Referenced by LoadProfile(), and MeaToolMgr::UpdateScreenInfo().
Update()
void MeaScreenTool::Update (MeaUpdateReason reason) override virtual
Updates the display of the tool's information.
Parameters
reason [in] Reason why the update has been requested
Reimplemented from MeaTool.
References MeaUnitsProvider::ConvertRes(), MeaUnitsProvider::GetWidthHeight(), MeaTool::IsEnabled(), m_anyOSRes, MeaTool::m_mgr, m_name, m_rect, m_res, MeaTool::m_unitsProvider, MeaToolMgr::ShowCalButton(), MeaToolMgr::ShowScreenName(), MeaToolMgr::ShowScreenRes(), MeaToolMgr::ShowScreenWH(), and MeaTool::Update().
Referenced by Enable(), and SetPosition().
The documentation for this class was generated from the following files:
ScreenTool.h
ScreenTool.cpp
Copyright 2011 C Thing Software