Meazure: MeaPositionLogMgr Class Reference
MeaPositionLogMgr Class Reference
Manages the recording, saving and loading of tool positions.
#include <PositionLogMgr.h>
Public Member Functions
MeaPositionLogMgr (token)
MeaPositionLogMgr (const MeaPositionLogMgr &)=delete
MeaPositionLogMgr & operator= (const MeaPositionLogMgr &)=delete
void RecordPosition ()
Records the position of the current radio tool.
void ReplacePosition (int posIndex)
Replaces the specified position list entry with the current radio tool position.
void DeletePosition (int posIndex)
Deletes the position recorded at the specified index.
void DeletePositions ()
Deletes all positions.
bool HavePositions () const
Indicates if there are any recorded positions.
unsigned int NumPositions () const
Returns the number of positions that have been recorded or loaded.
bool IsModified () const
Indicates if new positions have been recorded or the information associated with a position has changed since the last time the positions were saved in the log file.
MeaPosition & GetPosition (int posIndex)
Returns the position object at the specified index.
void ShowPosition (unsigned int posIndex)
Works with the tool manager to set the radio tool and its position based on the specified position in the list.
bool Load (LPCTSTR pathname=nullptr)
Loads the specified position log file.
bool Save (bool askPathname)
Saves the recorded positions to a log file.
bool SaveIfModified ()
If there are positions that have not been saved, ask the user if they should be saved.
void SetObserver (MeaPositionLogObserver *observer)
When a change occurs in this manager, the registered observer object is informed.
void ManagePositions ()
Displays the position management dialog.
void SaveProfile (MeaProfile &profile) const
Persists the state of the log manager itself to the specified profile object.
void LoadProfile (MeaProfile &profile)
Restores the state of the log manager from the specified profile object.
void MasterReset ()
Resets the position manager to its default state.
virtual void ParseEntity (MeaXMLParser &parser, const CString &pathname) override
Called during the XML parsing of the log file, to parse an external entity such as a DTD.
virtual CString GetFilePathname () override
Returns the pathname of the currently parsed log file.
Public Member Functions inherited from MeaXMLParserHandler
MeaXMLParserHandler ()
Empty constructor for the handler class.
virtual ~MeaXMLParserHandler ()
Empty destructor for the handler class.
virtual void StartElementHandler (const CString &container, const CString &elementName, const MeaXMLAttributes &attrs)
Called when a new element is opened (e.g.
virtual void EndElementHandler (const CString &container, const CString &elementName)
Called when an element is closed (e.g.
virtual void CharacterDataHandler (const CString &container, const CString &data)
Called for all character data encountered between elements.
virtual void ParseEntity (MeaXMLParser &parser, const CString &pathname)
Called to parse an external entity.
virtual CString GetFilePathname ()
Returns the pathname of the currently parsed file.
virtual void AddDesktopRef (const MeaGUID &id)=0
Increments the reference count for the specified desktop information object.
virtual void ReleaseDesktopRef (const MeaGUID &id)=0
Decrements the reference count for the specified desktop information object.
virtual void Write (int indentLevel, LPCTSTR format,...)=0
Printf-like method for writing to a position log file.
Public Member Functions inherited from MeaSingleton_T< MeaPositionLogMgr >
MeaSingleton_T (const MeaSingleton_T< MeaPositionLogMgr > &src)=delete
Singletons have no copy semantics.
MeaSingleton_T< MeaPositionLogMgr > & operator= (const MeaSingleton_T< MeaPositionLogMgr > &src)=delete
Singletons have no assignment semantics.
Static Public Member Functions
static bool IsPositionFile (LPCTSTR filename)
Tests whether the specified filename represents a position log file.
Static Public Member Functions inherited from MeaSingleton_T< MeaPositionLogMgr >
static MeaPositionLogMgr & Instance ()
The first time this method is called, a instance of the Singleton object is created and returned.
Private Types
typedef std::map< MeaGUID, MeaPositionDesktop, MeaGUID::less > DesktopInfoMap
Maps GUID to a desktop information object.
typedef std::map< MeaGUID, int, MeaGUID::less > RefCountMap
Maps a GUID to a reference count.
Private Member Functions
MeaPositionSaveDlg * CreateSaveDialog ()
Constructs a file save dialog tailored to saving position log files.
CFileDialog * CreateLoadDialog ()
Constructs a file open dialog tailored to loading position log files.
void ManageDlgDestroyed ()
Called when the position management dialog is destroyed.
void WriteInfoSection (int indent)
Writes the general information section of the position log file.
void WriteDesktopsSection (int indent)
Writes the desktop information section of the position log file.
void WritePositionsSection (MeaPositionLogWriter &writer, int indent)
Writes the positions section of the position log file.
bool Open (const CString &pathname, UINT mode)
Opens the specified position log file either for reading or writing.
void Close ()
Closes the currently open position log file.
void Write (int indentLevel, LPCTSTR format,...) override
Printf-like method for writing to a position log file.
void ProcessDOM (const MeaXMLNode *dom)
Handles the top level elements of the log file DOM and supervises the processing of the lower level elements.
void ProcessInfoNode (const MeaXMLNode *infoNode)
Handles the info element of the log file.
void ProcessDesktopNode (const MeaXMLNode *desktopNode)
Handles the desktop elements of the log file.
void ProcessPositionNode (const MeaXMLNode *positionNode)
Handles the position elements of the log file.
MeaPositionDesktopRef RecordDesktopInfo ()
Records the current desktop information if the information has not already been recorded.
MeaPositionDesktop & GetDesktopInfo (const MeaGUID &id)
Returns the desktop information object corresponding to the specified ID.
void AddDesktopRef (const MeaGUID &id) override
Increments the reference count for the specified desktop information object.
void ReleaseDesktopRef (const MeaGUID &id) override
Decrements the reference count for the specified desktop information object.
void ClearPositions ()
Performs the actual work or deleting all positions.
Private Attributes
MeaPositionLogObserver * m_observer
Position log manager observer.
DesktopInfoMap m_desktopInfoMap
Desktop information objects.
RefCountMap m_refCountMap
Desktop information object reference count.
MeaPositionCollection m_positions
Recorded positions.
MeaPositionSaveDlg * m_saveDialog
Position log file save dialog.
CFileDialog * m_loadDialog
Position log file open dialog.
CString m_saveDlgTitle
Title for the file save dialog.
CString m_loadDlgTitle
Title for the file open dialog.
CString m_initialDir
Initial directory for the file save and open dialogs.
CString m_pathname
Pathname of current position log file.
CStdioFile m_stdioFile
File pointer for an open position log file.
bool m_stdioOpen
Is the position log file open.
CString m_title
Title for the positions.
CString m_desc
Description of the positions.
bool m_modified
Have the positions been modified since last save.
MeaPositionLogDlg * m_manageDialog
Position management dialog.
Static Private Attributes
static constexpr int kChunkSize { 1024 }
Log file parsing buffer allocation increment.
static constexpr LPCTSTR kExt { _T("mpl") }
Log file suffix.
static constexpr LPCTSTR kFilter { _T("Meazure Position Log Files (*.mpl)|*.mpl|All Files (*.*)|*.*||") }
File dialog filter string.
Friends
class MeaPositionLogDlg
Position save dialog.
Additional Inherited Members
Protected Member Functions inherited from MeaSingleton_T< MeaPositionLogMgr >
MeaSingleton_T ()=default
Constructs a Singleton object instance.
Detailed Description
Manages the recording, saving and loading of tool positions.
The positions are saved to an XML format file.
Member Function Documentation
AddDesktopRef()
void MeaPositionLogMgr::AddDesktopRef (const MeaGUID & id) override private virtual
Increments the reference count for the specified desktop information object.
Parameters
id [in] ID of the desktop info object whose reference count is to be incremented.
Implements MeaPositionDesktopRefCounter.
References m_refCountMap.
CreateLoadDialog()
CFileDialog * MeaPositionLogMgr::CreateLoadDialog () private
Constructs a file open dialog tailored to loading position log files.
Returns
Position log file option dialog.
References kExt, kFilter, m_initialDir, m_loadDialog, and m_loadDlgTitle.
Referenced by Load().
CreateSaveDialog()
MeaPositionSaveDlg * MeaPositionLogMgr::CreateSaveDialog () private
Constructs a file save dialog tailored to saving position log files.
Returns
Position log file save dialog.
References kExt, kFilter, m_desc, MeaPositionSaveDlg::m_desc, m_initialDir, m_saveDialog, m_saveDlgTitle, m_title, and MeaPositionSaveDlg::m_title.
Referenced by Save().
DeletePosition()
void MeaPositionLogMgr::DeletePosition (int posIndex)
Deletes the position recorded at the specified index.
Parameters
posIndex [in] Zero based index of the position to delete.
References MeaPositionCollection::Delete(), HavePositions(), m_modified, m_observer, m_positions, and MeaPositionLogObserver::PositionDeleted().
Referenced by MeaPositionLogDlg::OnDeletePosition().
GetDesktopInfo()
MeaPositionDesktop & MeaPositionLogMgr::GetDesktopInfo (const MeaGUID & id) private
Returns the desktop information object corresponding to the specified ID.
Parameters
id [in] Desktop information object ID.
Returns
Desktop information object corresponding to the ID.
References m_desktopInfoMap.
Referenced by ShowPosition(), and WriteDesktopsSection().
GetFilePathname()
CString MeaPositionLogMgr::GetFilePathname () override virtual
Returns the pathname of the currently parsed log file.
Returns
Pathname of the currently parsed position log file.
Reimplemented from MeaXMLParserHandler.
References m_pathname, m_stdioFile, and m_stdioOpen.
Referenced by MeaPositionLogDlg::SetDlgTitle().
GetPosition()
MeaPosition & MeaPositionLogMgr::GetPosition (int posIndex) inline
Returns the position object at the specified index.
Parameters
posIndex [in] Zero based index of the position to return.
Returns
Position at the specified index.
References MeaPositionCollection::Get(), and m_positions.
Referenced by MeaPositionLogDlg::OnKillfocusPositionDesc(), and MeaPositionLogDlg::UpdatePositionInfo().
HavePositions()
bool MeaPositionLogMgr::HavePositions () const inline
Indicates if there are any recorded positions.
Returns
true if there are recorded positions.
References MeaPositionCollection::Empty(), and m_positions.
Referenced by DeletePosition(), MeaPositionLogDlg::OnKillfocusPositionDesc(), MeaPositionLogDlg::SetScrollRange(), and MeaPositionLogDlg::UpdateEnable().
IsPositionFile()
bool MeaPositionLogMgr::IsPositionFile (LPCTSTR filename) static
Tests whether the specified filename represents a position log file.
Parameters
filename [in] File to test
Returns
true if the specified file is a position log file.
References kExt.
Referenced by AppView::LoadStartupFile().
Load()
bool MeaPositionLogMgr::Load (LPCTSTR pathname = nullptr)
Loads the specified position log file.
Parameters
pathname [in] Pathname of file to load or nullptr if a file dialog should be shown.
Returns
true if loaded, false if canceled or unable to load.
References ClearPositions(), Close(), CreateLoadDialog(), MeaXMLParser::GetBuffer(), MeaXMLParser::GetDOM(), kChunkSize, MeaPositionLogObserver::LogLoaded(), m_initialDir, m_modified, m_observer, m_pathname, m_stdioFile, Open(), MeaXMLParser::ParseBuffer(), ProcessDOM(), and SaveIfModified().
Referenced by MeaPositionLogDlg::OnLoadPositions().
LoadProfile()
void MeaPositionLogMgr::LoadProfile (MeaProfile & profile)
Restores the state of the log manager from the specified profile object.
Parameters
profile [in] Profile object from which the position log manager will restore itself.
References m_initialDir, MeaProfile::ReadStr(), and MeaProfile::UserInitiated().
Referenced by AppView::LoadProfile().
NumPositions()
unsigned int MeaPositionLogMgr::NumPositions () const inline
Returns the number of positions that have been recorded or loaded.
Returns
Number of recorded or loaded positions.
References m_positions, and MeaPositionCollection::Size().
Referenced by MeaPositionLogDlg::SetScrollRange(), and MeaPositionLogDlg::UpdatePositionInfo().
Open()
bool MeaPositionLogMgr::Open (const CString & pathname, UINT mode) private
Opens the specified position log file either for reading or writing.
Parameters
pathname [in] Pathname of position log file to open.
mode [in] one of CFile::modeRead or CFile::modeWrite | CFile::modeCreate
Returns
true if file opened successfully.
References m_stdioFile, and m_stdioOpen.
Referenced by Load(), and Save().
ParseEntity()
void MeaPositionLogMgr::ParseEntity (MeaXMLParser & parser, const CString & pathname) override virtual
Called during the XML parsing of the log file, to parse an external entity such as a DTD.
Parameters
parser [in] XML parser.
pathname [in] Pathname of the external entity.
Reimplemented from MeaXMLParserHandler.
References MeaXMLParser::GetBuffer(), and MeaXMLParser::ParseBuffer().
ProcessDesktopNode()
void MeaPositionLogMgr::ProcessDesktopNode (const MeaXMLNode * desktopNode) private
Handles the desktop elements of the log file.
Parameters
desktopNode [in] desktop node in the DOM.
References MeaXMLNode::GetAttributes(), MeaPositionDesktop::GetId(), MeaXMLAttributes::GetValueStr(), MeaSingleton_T< MeaScreenMgr >::Instance(), MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaPositionDesktop::Load(), and m_desktopInfoMap.
Referenced by ProcessDOM().
ProcessDOM()
void MeaPositionLogMgr::ProcessDOM (const MeaXMLNode * dom) private
Handles the top level elements of the log file DOM and supervises the processing of the lower level elements.
Parameters
dom [in] Root node of the DOM.
References MeaXMLNode::AtEnd(), MeaXMLNode::Element, MeaXMLNode::GetChildIter(), MeaXMLNode::GetData(), MeaXMLNode::GetType(), ProcessDesktopNode(), ProcessInfoNode(), and ProcessPositionNode().
Referenced by Load().
ProcessInfoNode()
void MeaPositionLogMgr::ProcessInfoNode (const MeaXMLNode * infoNode) private
Handles the info element of the log file.
Parameters
infoNode [in] info node in the DOM.
References MeaXMLNode::AtEnd(), MeaXMLNode::Element, MeaXMLNode::GetChildData(), MeaXMLNode::GetChildIter(), MeaXMLNode::GetData(), MeaXMLNode::GetType(), m_desc, and m_title.
Referenced by ProcessDOM().
ProcessPositionNode()
void MeaPositionLogMgr::ProcessPositionNode (const MeaXMLNode * positionNode) private
Handles the position elements of the log file.
Parameters
positionNode [in] position node in the DOM
References MeaPositionCollection::Add(), MeaXMLNode::GetAttributes(), MeaXMLAttributes::GetValueStr(), MeaPosition::Load(), and m_positions.
Referenced by ProcessDOM().
RecordDesktopInfo()
MeaPositionDesktopRef MeaPositionLogMgr::RecordDesktopInfo () private
Records the current desktop information if the information has not already been recorded.
Returns
Reference to the desktop information object that was either created of reused.
References MeaPositionDesktop::GetId(), MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaSingleton_T< MeaScreenMgr >::Instance(), and m_desktopInfoMap.
Referenced by RecordPosition(), and ReplacePosition().
ReleaseDesktopRef()
void MeaPositionLogMgr::ReleaseDesktopRef (const MeaGUID & id) override private virtual
Decrements the reference count for the specified desktop information object.
Parameters
id [in] ID of the desktop info object whose reference count is to be decremented.
Implements MeaPositionDesktopRefCounter.
References m_refCountMap.
ReplacePosition()
void MeaPositionLogMgr::ReplacePosition (int posIndex)
Replaces the specified position list entry with the current radio tool position.
Parameters
posIndex [in] Zero based index of the position to replace.
References MeaSingleton_T< MeaToolMgr >::Instance(), m_modified, m_observer, m_positions, MeaPositionLogObserver::PositionReplaced(), RecordDesktopInfo(), MeaToolMgr::RecordPosition(), MeaPositionCollection::Set(), and MeaToolMgr::StrobeTool().
Referenced by MeaPositionLogDlg::OnReplacePosition().
Save()
bool MeaPositionLogMgr::Save (bool askPathname)
Saves the recorded positions to a log file.
Parameters
askPathname [in] true means ask user to supply a pathname even if there is already a pathname.
Returns
true if saved, false if canceled or unable to save.
References Close(), CreateSaveDialog(), MeaSingleton_T< MeaVersionInfo >::Instance(), MeaPositionLogObserver::LogSaved(), m_desc, MeaPositionSaveDlg::m_desc, m_initialDir, m_modified, m_observer, m_pathname, m_title, MeaPositionSaveDlg::m_title, Open(), Write(), WriteDesktopsSection(), WriteInfoSection(), and WritePositionsSection().
Referenced by MeaPositionLogDlg::OnSavePositions(), AppView::OnSavePositions(), MeaPositionLogDlg::OnSavePositionsAs(), AppView::OnSavePositionsAs(), and SaveIfModified().
SaveIfModified()
bool MeaPositionLogMgr::SaveIfModified ()
If there are positions that have not been saved, ask the user if they should be saved.
Called before the app exits or a load will destroy the unsaved positions.
Returns
true if the pending operation should proceed (e.g. exit or load), false if pending operation should be canceled.
References IsModified(), and Save().
Referenced by Load(), and App::SaveAllModified().
SaveProfile()
void MeaPositionLogMgr::SaveProfile (MeaProfile & profile) const
Persists the state of the log manager itself to the specified profile object.
Parameters
profile [in] Profile object into which the position log manager should persist itself.
References m_initialDir, MeaProfile::UserInitiated(), and MeaProfile::WriteStr().
Referenced by AppView::SaveProfile().
SetObserver()
void MeaPositionLogMgr::SetObserver (MeaPositionLogObserver * observer) inline
When a change occurs in this manager, the registered observer object is informed.
Parameters
observer [in] Object to register as an observer of the position log manager.
References m_observer.
Referenced by MeaPositionLogDlg::OnInitDialog(), and MeaPositionLogDlg::PostNcDestroy().
ShowPosition()
void MeaPositionLogMgr::ShowPosition (unsigned int posIndex)
Works with the tool manager to set the radio tool and its position based on the specified position in the list.
Parameters
posIndex [in] Zero based index of the position to display.
References MeaPositionCollection::Get(), MeaPositionDesktop::GetAngularUnits(), MeaUnitsMgr::GetAngularUnitsStr(), MeaPositionDesktop::GetCustomAbbrev(), MeaPositionDesktop::GetCustomBasisStr(), MeaPositionDesktop::GetCustomFactor(), MeaPositionDesktop::GetCustomName(), MeaPositionDesktop::GetCustomPrecisions(), MeaUnitsMgr::GetCustomUnits(), GetDesktopInfo(), MeaPosition::GetDesktopRef(), MeaPositionDesktop::GetLinearUnits(), MeaUnitsMgr::GetLinearUnitsStr(), MeaPositionDesktop::GetOrigin(), MeaUnitsMgr::GetOrigin(), MeaPosition::GetPoints(), MeaPosition::GetToolName(), MeaToolMgr::GetToolName(), MeaLinearUnits::GetUnitsId(), MeaUnits::GetUnitsStr(), MeaSingleton_T< MeaToolMgr >::Instance(), MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaPositionDesktop::IsInvertY(), MeaUnitsMgr::IsInvertY(), MeaCursorTool::kToolName, MeaPointTool::kToolName, MeaRectTool::kToolName, MeaWindowTool::kToolName, m_positions, MeaCustomId, OriginChanged, MeaCustomUnits::SetAbbrev(), MeaUnitsMgr::SetAngularUnits(), MeaUnits::SetDisplayPrecisions(), MeaUnitsMgr::SetInvertY(), MeaUnitsMgr::SetLinearUnits(), MeaCustomUnits::SetName(), MeaUnitsMgr::SetOrigin(), MeaToolMgr::SetPosition(), MeaToolMgr::SetRadioTool(), MeaCustomUnits::SetScaleBasis(), MeaCustomUnits::SetScaleFactor(), MeaPositionCollection::Size(), MeaUnitsMgr::UnconvertCoord(), UnitsChanged, and MeaToolMgr::UpdateTools().
Referenced by MeaPositionLogDlg::LogLoaded(), MeaPositionLogDlg::OnHScroll(), and MeaPositionLogDlg::OnInitDialog().
Write()
void MeaPositionLogMgr::Write (int indentLevel, LPCTSTR format, ...) override private virtual
Printf-like method for writing to a position log file.
Parameters
indentLevel [in] Output indentation level.
format [in] Printf-style format string.
... [in] Items to write to the file.
Exceptions
CFileException if there was a problem writing the information
Implements MeaPositionLogWriter.
References m_stdioFile, and MeaXMLParser::ToUTF8().
Referenced by Save(), WriteDesktopsSection(), WriteInfoSection(), and WritePositionsSection().
WriteDesktopsSection()
void MeaPositionLogMgr::WriteDesktopsSection (int indent) private
Writes the desktop information section of the position log file.
Parameters
indent [in] Output indentation level.
Exceptions
CFileException if there was a problem writing the information
References GetDesktopInfo(), m_refCountMap, MeaPositionDesktop::Save(), and Write().
Referenced by Save().
WriteInfoSection()
void MeaPositionLogMgr::WriteInfoSection (int indent) private
Writes the general information section of the position log file.
Parameters
indent [in] Output indentation level.
Exceptions
CFileException if there was a problem writing the information
References MeaXMLParser::Encode(), MeaSingleton_T< MeaVersionInfo >::Instance(), m_desc, m_title, and Write().
Referenced by Save().
WritePositionsSection()
void MeaPositionLogMgr::WritePositionsSection (MeaPositionLogWriter & writer, int indent) private
Writes the positions section of the position log file.
Parameters
writer [in] Provides ability to write a position to the log.
indent [in] Output indentation level.
Exceptions
CFileException if there was a problem writing the information
References m_positions, MeaPositionCollection::Save(), and Write().
Referenced by Save().
The documentation for this class was generated from the following files:
PositionLogMgr.h
PositionLogMgr.cpp
Copyright 2011 C Thing Software