Meazure: MeaRegistryProfile Class Reference
MeaRegistryProfile Class Reference
Persists the application state to the registry.
#include <RegistryProfile.h>
Public Member Functions
MeaRegistryProfile (MeaRegistryProvider &registry)
Creates an instance of the registry profile and opens the appropriate registry key.
virtual ~MeaRegistryProfile ()
Destroys the instance of the registry profile object.
virtual bool WriteBool (LPCTSTR key, bool value) override
Writes a boolean value to the specified key.
virtual bool WriteInt (LPCTSTR key, int value) override
Writes an integer value to the specified key.
virtual bool WriteDbl (LPCTSTR key, double value) override
Writes a double value to the specified key.
virtual bool WriteStr (LPCTSTR key, LPCTSTR value) override
Writes a string value to the specified key.
virtual bool ReadBool (LPCTSTR key, bool defaultValue) override
Reads a boolean value from the specified key.
virtual UINT ReadInt (LPCTSTR key, int defaultValue) override
Reads an unsigned integer value from the specified key.
virtual double ReadDbl (LPCTSTR key, double defaultValue) override
Reads a double value from the specified key.
virtual CString ReadStr (LPCTSTR key, LPCTSTR defaultValue) override
Reads a string value from the specified key.
virtual bool UserInitiated () override
Indicates whether the profile is being written at the user's request (i.e.
virtual int GetVersion () override
Returns the profile format version number.
virtual bool WriteBool (LPCTSTR key, bool value)=0
Writes a boolean value to the specified key.
virtual bool WriteInt (LPCTSTR key, int value)=0
Writes an integer value to the specified key.
virtual bool WriteDbl (LPCTSTR key, double value)=0
Writes a double value to the specified key.
virtual bool WriteStr (LPCTSTR key, LPCTSTR value)=0
Writes a string value to the specified key.
virtual bool ReadBool (LPCTSTR key, bool defaultValue)=0
Reads a boolean value from the specified key.
virtual UINT ReadInt (LPCTSTR key, int defaultValue)=0
Reads an unsigned integer value from the specified key.
virtual double ReadDbl (LPCTSTR key, double defaultValue)=0
Reads a double value from the specified key.
virtual CString ReadStr (LPCTSTR key, LPCTSTR defaultValue)=0
Reads a string value from the specified key.
virtual bool UserInitiated ()=0
Indicates whether the profile is being written at the user's request (i.e.
virtual int GetVersion ()=0
Returns the profile format version number.
Private Member Functions
bool HaveVersionKey (LPCTSTR version) const
Tests whether the specified version number key is present in the registry.
Private Attributes
MeaRegistryProvider & m_registry
Access to the Windows Registry.
CString m_loadVersion
Profile format version read.
CString m_saveVersion
Profile format version written.
Detailed Description
Persists the application state to the registry.
On application startup the registry profile is read to restore the program state from the last time it was run. On exit, the registry profile is written so that the application can be restore to the same state when it is next run.
Constructor & Destructor Documentation
MeaRegistryProfile()
MeaRegistryProfile::MeaRegistryProfile (MeaRegistryProvider & registry)
Creates an instance of the registry profile and opens the appropriate registry key.
Parameters
registry [in] Provider for reading and writing the Windows Registry
References HaveVersionKey(), MeaSingleton_T< MeaVersionInfo >::Instance(), m_loadVersion, and m_saveVersion.
Member Function Documentation
GetVersion()
int MeaRegistryProfile::GetVersion () override virtual
Returns the profile format version number.
Returns
Profile format version number.
Implements MeaProfile.
References m_loadVersion.
HaveVersionKey()
bool MeaRegistryProfile::HaveVersionKey (LPCTSTR version) const private
Tests whether the specified version number key is present in the registry.
The version key is located at:
HKEY_CURRENT_USER\Software\C Thing Software\Meazure\[version]
Parameters
version [in] Version number to test
Returns
true if key exists.
References MeaRegistryProvider::CloseKey(), MeaRegistryProvider::GetKeyName(), m_registry, and MeaRegistryProvider::OpenKey().
Referenced by MeaRegistryProfile().
ReadBool()
bool MeaRegistryProfile::ReadBool (LPCTSTR key, bool defaultValue) override virtual
Reads a boolean value from the specified key.
Parameters
key [in] Profile key to read
defaultValue [in] Default value to use if the key is not found in the profile.
Implements MeaProfile.
References MeaRegistryProvider::GetInt(), m_loadVersion, and m_registry.
ReadDbl()
double MeaRegistryProfile::ReadDbl (LPCTSTR key, double defaultValue) override virtual
Reads a double value from the specified key.
Parameters
key [in] Profile key to read
defaultValue [in] Default value to use if the key is not found in the profile.
Implements MeaProfile.
References MeaRegistryProvider::GetString(), m_loadVersion, and m_registry.
ReadInt()
UINT MeaRegistryProfile::ReadInt (LPCTSTR key, int defaultValue) override virtual
Reads an unsigned integer value from the specified key.
Parameters
key [in] Profile key to read
defaultValue [in] Default value to use if the key is not found in the profile.
Implements MeaProfile.
References MeaRegistryProvider::GetInt(), m_loadVersion, and m_registry.
ReadStr()
CString MeaRegistryProfile::ReadStr (LPCTSTR key, LPCTSTR defaultValue) override virtual
Reads a string value from the specified key.
Parameters
key [in] Profile key to read
defaultValue [in] Default value to use if the key is not found in the profile.
Implements MeaProfile.
References MeaRegistryProvider::GetString(), m_loadVersion, and m_registry.
UserInitiated()
bool MeaRegistryProfile::UserInitiated () override virtual
Indicates whether the profile is being written at the user's request (i.e.
a file profile).
Returns
Always false because a registry profile is not written at the user's request.
Implements MeaProfile.
WriteBool()
bool MeaRegistryProfile::WriteBool (LPCTSTR key, bool value) override virtual
Writes a boolean value to the specified key.
Parameters
key [in] Profile key to write
value [in] Boolean value for the key
Implements MeaProfile.
References m_registry, m_saveVersion, and MeaRegistryProvider::WriteInt().
WriteDbl()
bool MeaRegistryProfile::WriteDbl (LPCTSTR key, double value) override virtual
Writes a double value to the specified key.
Parameters
key [in] Profile key to write
value [in] Double value for the key
Implements MeaProfile.
References m_registry, m_saveVersion, and MeaRegistryProvider::WriteString().
WriteInt()
bool MeaRegistryProfile::WriteInt (LPCTSTR key, int value) override virtual
Writes an integer value to the specified key.
Parameters
key [in] Profile key to write
value [in] Integer value for the key
Implements MeaProfile.
References m_registry, m_saveVersion, and MeaRegistryProvider::WriteInt().
WriteStr()
bool MeaRegistryProfile::WriteStr (LPCTSTR key, LPCTSTR value) override virtual
Writes a string value to the specified key.
Parameters
key [in] Profile key to write
value [in] String value for the key
Implements MeaProfile.
References m_registry, m_saveVersion, and MeaRegistryProvider::WriteString().
The documentation for this class was generated from the following files:
RegistryProfile.h
RegistryProfile.cpp
Copyright 2011 C Thing Software