Meazure: MeaAngleTool Class Reference
MeaAngleTool Class Reference
Angle measurement tool.
#include <AngleTool.h>
Public Member Functions
MeaAngleTool (MeaToolMgr *mgr)
Constructs a new instance of an angle measurement tool.
virtual ~MeaAngleTool ()
Hides and then destroys the Angle tool.
virtual void Enable () override
Displays the Angle tool.
virtual void Disable () override
Hides the Angle tool.
virtual void Update (MeaUpdateReason reason) override
Requests that the tool update the display of its position data.
virtual void SaveProfile (MeaProfile &profile) override
Persists the state of the tool to the specified profile object.
virtual void LoadProfile (MeaProfile &profile) override
Restores the state of the tool from the specified profile object.
virtual void EnableCrosshairs () override
Displays the tool's crosshairs.
virtual void DisableCrosshairs () override
Hides the tool's crosshairs.
virtual void Flash () override
Visually flashes the tool.
virtual void Strobe () override
Visually strobes the tool.
virtual void SetPosition (MeaFields which, int pixels) override
Sets the position of the tool.
virtual void SetPosition (const PointMap &points) override
Sets the position of the tool.
virtual const POINT & GetPosition () const override
Returns the tool's current position.
virtual void GetPosition (MeaPositionLogMgr::Position &position) const override
Records the position of the tool.
virtual void IncPosition (MeaFields which) override
Increments the specified position field.
virtual void DecPosition (MeaFields which) override
Decrements the specified position field.
virtual CString GetToolName () const override
Returns the name of the tool.
virtual UINT GetLabelId () const override
Returns a resource ID for the string used to label this tool on the data display.
virtual void ColorsChanged () override
Called to notify the tool that the colors in the MeaColors class have been changed.
virtual void OnCHEnter (const CHInfo *info) override
Called when the pointer enters one of the tool's crosshairs.
virtual void OnCHLeave (const CHInfo *info) override
Called when the pointer leaves one of the tool's crosshairs.
virtual void OnCHMove (const CHInfo *info) override
Called when the user attempts to drag one of the tool's crosshairs.
Public Member Functions inherited from MeaRadioTool
MeaRadioTool (MeaToolMgr *mgr)
Constructs a new instance of an radio based measurement tool.
virtual ~MeaRadioTool ()
Destroys the tool.
virtual bool IsRadioTool () override
Indicates that the derived tool is a Radio tool and cannot be enabled until any other enabled Radio tool is disabled.
virtual UINT GetLabelId () const
Returns a resource ID for the string used to label this tool on the data display.
virtual bool HasCrosshairs () const
Indicates whether the derived tool uses crosshairs.
virtual void EnableCrosshairs ()
Displays the tool's crosshairs.
virtual void DisableCrosshairs ()
Hides the tool's crosshairs.
virtual void Flash ()
Visually flashes the tool.
virtual void Strobe ()
Visually strobes the tool.
virtual bool HasRegion ()
Indicates whether the tool can define a rectangular region that can then be read for a screen capture.
virtual RECT GetRegion ()
Returns the rectangle defined by the tool.
virtual void SetPosition (const PointMap &points)
Sets the position of the tool.
virtual void GetPosition (MeaPositionLogMgr::Position &position) const =0
Records the position of the tool.
virtual void OnMouseHook (WPARAM wParam, LPARAM lParam)
Called by the OS when the mouse pointer is moved.
Public Member Functions inherited from MeaTool
MeaTool (MeaToolMgr *mgr)
Base class constructor.
virtual ~MeaTool ()
Destroys the tool.
virtual void Enable ()
Typically used by derived classes to show the tool.
virtual void Disable ()
Typically used by derived classes to hide the tool.
virtual void Update (MeaUpdateReason reason)
Used by derived classes to update the display of their data.
virtual bool IsRadioTool ()
Indicates whether the derived tool is a radio tool and cannot be enabled until any other enabled Radio tool is disabled.
virtual void SetPosition (MeaFields which, int pixels)
Sets the position of the tool.
virtual const POINT & GetPosition () const =0
Returns the tool's current position.
virtual void IncPosition (MeaFields which)
Increments the specified position field.
virtual void DecPosition (MeaFields which)
Decrements the specified position field.
virtual CString GetToolName () const =0
Returns the name of the tool.
virtual void SaveProfile (MeaProfile &profile)
Persists the state of the tool to the specified profile object.
virtual void LoadProfile (MeaProfile &profile)
Restores the state of the tool from the specified profile object.
virtual void MasterReset ()
Resets the tool to its default state.
virtual void ColorsChanged ()
Called to notify the tool that the colors in the MeaColors class have been changed.
bool IsEnabled () const
Indicates whether the tool is enabled.
Public Member Functions inherited from MeaCrossHairCallback
MeaCrossHairCallback ()
Constructs a callback object.
virtual ~MeaCrossHairCallback ()
Destroys a callback object.
virtual void OnCHSelect (const CHInfo *info)
Called when the left mouse button is pressed while the pointer is positioned over the crosshair.
virtual void OnCHDeselect (const CHInfo *info)
Called when the left mouse button is release while the pointer is positioned over the crosshair.
virtual void OnCHMove (const CHInfo *info)
Called when the user moves the mouse pointer over the crosshair while the left mouse button is pressed (i.e.
virtual void OnCHEnter (const CHInfo *info)
Called when the pointer enters the crosshair window.
virtual void OnCHLeave (const CHInfo *info)
Called when the pointer leaves the crosshair window.
Static Public Attributes
static const CString kToolName
"AngleTool"
Private Member Functions
bool Create ()
Creates the tool's graphical components.
void SetPosition ()
Sets the position of the tool's crosshairs based on the current values of m_point1, m_point2, and m_vertex.
void UpdateBisector ()
Updates the position of the angle bisector to reflect the positions of the angle lines.
Private Attributes
CPoint m_point1
Location of the line 1 end point.
CPoint m_point2
Location of the line 2 end point.
CPoint m_vertex
Location of the intersection of line 1 and line 2.
CPoint m_vertexAnchor
Location for vertical / horizontal lock when Shift is held while dragging.
CPoint * m_curPos
Points to m_point1, m_point2, or m_vertex depending on point the user is moving.
MeaCrossHair m_point1CH
Crosshair for the line 1 end point.
MeaCrossHair m_point2CH
Crosshair for the line 2 end point.
MeaCrossHair m_vertexCH
Crosshair for the line 1 / line 2 intersection point.
MeaLine m_line1
Line from vertex to point 1.
MeaLine m_line2
Line from vertex to point 2.
MeaLine m_lineB
Line forming the angle bisector.
MeaDataWin m_dataWin1
Data window tooltip for point 1.
MeaDataWin m_dataWin2
Data window tooltip for point 2.
MeaDataWin m_dataWinV
Data window tooltip for the vertex.
Static Private Attributes
static constexpr double kLengthB { 50.0 }
Length of the angle bisector line in pixels.
static constexpr UINT kPoint1Id { 1 }
ID for the point 1 crosshair.
static constexpr UINT kPoint2Id { 2 }
ID for the point 2 crosshair.
static constexpr UINT kVertexId { 3 }
ID for the vertex crosshair.
Additional Inherited Members
Public Types inherited from MeaRadioTool
typedef std::map< CString, POINT > PointMap
Map of points used to set the position of a tool.
Protected Attributes inherited from MeaTool
MeaToolMgr * m_mgr
Tool manager.
bool m_enabled
Indicates whether the tool is enabled.
Static Protected Attributes inherited from MeaTool
static POINT m_defaultPos { 0, 0 }
A default position used by tools that do not have a defined position.
Detailed Description
Angle measurement tool.
This tool measures the acute or obtuse angle between two intersecting lines. There are three crosshairs associated with the tool: one at the intersection of the two lines (vertex), and one at the end of each line (point 1 and point 2). Each crosshair can be arbitrarily positioned. An angle bisector is displayed to indicate on which side of the intersection the angle is being measured.
Constructor & Destructor Documentation
MeaAngleTool()
MeaAngleTool::MeaAngleTool (MeaToolMgr * mgr) explicit
Constructs a new instance of an angle measurement tool.
To use a newly constructed Angle tool, the Enable() method must be called. Enable() will call the Create() method the first time it is called if Create() has not previously been called.
Parameters
mgr [in] Tool manager parent of the Angle tool.
References m_point1, m_point2, m_vertex, and m_vertexAnchor.
Member Function Documentation
ColorsChanged()
void MeaAngleTool::ColorsChanged () override virtual
Called to notify the tool that the colors in the MeaColors class have been changed.
The crosshair and line colors are updated as well as the crosshair and data window opacities.
Reimplemented from MeaTool.
References MeaColors::CrossHairBack, MeaColors::CrossHairBorder, MeaColors::CrossHairHilite, MeaColors::CrossHairOpacity, MeaColors::Get(), MeaColors::GetA(), MeaColors::LineFore, m_dataWin1, m_dataWin2, m_dataWinV, m_line1, m_line2, m_lineB, m_point1CH, m_point2CH, m_vertexCH, MeaLine::SetColor(), MeaCrossHair::SetColors(), MeaCrossHair::SetOpacity(), and MeaDataWin::SetOpacity().
Create()
bool MeaAngleTool::Create () private
Creates the tool's graphical components.
The components include the crosshairs, lines and data windows. The Enable() method must be called to make the tool visible.
Returns
true if the window is successfully created.
References MeaDataWin::Create(), MeaCrossHair::Create(), MeaLine::Create(), MeaColors::CrossHairBack, MeaColors::CrossHairBorder, MeaColors::CrossHairHilite, MeaColors::CrossHairOpacity, MeaColors::Get(), MeaColors::GetA(), MeaDataWin::kNoLabelId, kPoint1Id, kPoint2Id, kVertexId, m_dataWin1, m_dataWin2, m_dataWinV, m_line1, m_line2, m_lineB, m_point1CH, m_point2CH, m_vertexCH, MeaGraphic::SetAbove(), and SetPosition().
Referenced by Enable().
DecPosition()
void MeaAngleTool::DecPosition (MeaFields which) override virtual
Decrements the specified position field.
Parameters
which Field to decrement
Reimplemented from MeaTool.
References m_point1, m_point2, m_vertex, MeaX1Field, MeaX2Field, MeaXVField, MeaY1Field, MeaY2Field, MeaYVField, and SetPosition().
Disable()
void MeaAngleTool::Disable () override virtual
Hides the Angle tool.
Reimplemented from MeaTool.
References MeaTool::Disable(), DisableCrosshairs(), MeaLine::Hide(), MeaTool::IsEnabled(), m_line1, m_line2, and m_lineB.
Referenced by ~MeaAngleTool().
DisableCrosshairs()
void MeaAngleTool::DisableCrosshairs () override virtual
Hides the tool's crosshairs.
Reimplemented from MeaRadioTool.
References MeaGraphic::Hide(), m_point1CH, m_point2CH, and m_vertexCH.
Referenced by Disable().
Enable()
void MeaAngleTool::Enable () override virtual
Displays the Angle tool.
If the Create() method has not been previously called, it will be called by Enable.
Reimplemented from MeaTool.
References Create(), MeaTool::Enable(), EnableCrosshairs(), MeaToolMgr::EnableRegionFields(), Flash(), MeaTool::IsEnabled(), m_line1, m_line2, m_lineB, MeaTool::m_mgr, MeaAngleField, MeaX1Field, MeaX2Field, MeaXVField, MeaY1Field, MeaY2Field, MeaYVField, NormalUpdate, MeaToolMgr::SetStatus(), MeaGraphic::Show(), and Update().
EnableCrosshairs()
void MeaAngleTool::EnableCrosshairs () override virtual
Displays the tool's crosshairs.
If the Enable() method has not been previously called, this method has no effect.
Reimplemented from MeaRadioTool.
References MeaToolMgr::CrosshairsEnabled(), MeaTool::m_mgr, m_point1CH, m_point2CH, m_vertexCH, and MeaGraphic::Show().
Referenced by Enable().
Flash()
void MeaAngleTool::Flash () override virtual
Visually flashes the tool.
The tool crosshairs are cycled between a highlight color and their normal color a number of times. Flashing the tool helps the user find it on the screen.
Reimplemented from MeaRadioTool.
References MeaCrossHair::Flash(), m_point1CH, m_point2CH, and m_vertexCH.
Referenced by Enable().
GetLabelId()
UINT MeaAngleTool::GetLabelId () const override virtual
Returns a resource ID for the string used to label this tool on the data display.
Returns
Resource ID for the label.
Reimplemented from MeaRadioTool.
GetPosition() [1/2]
const POINT & MeaAngleTool::GetPosition () const override virtual
Returns the tool's current position.
The current position is the position of the last crosshair entered or moved. The default position is the location of the point 1.
Returns
Current position
Implements MeaTool.
References m_curPos.
GetPosition() [2/2]
void MeaAngleTool::GetPosition (MeaPositionLogMgr::Position & position) const override virtual
Records the position of the tool.
This method is called by the position log manager to record a position.
Parameters
position [in] The tool's current position is recorded into the position log manager's position object.
Implements MeaRadioTool.
References MeaUnitsMgr::ConvertCoord(), MeaLayout::GetAngle(), MeaSingleton_T< MeaUnitsMgr >::Instance(), m_point1, m_point2, m_vertex, MeaPositionLogMgr::Position::RecordAngle(), MeaPositionLogMgr::Position::RecordXY1(), MeaPositionLogMgr::Position::RecordXY2(), and MeaPositionLogMgr::Position::RecordXYV().
GetToolName()
CString MeaAngleTool::GetToolName () const override virtual
Returns the name of the tool.
Each tool has a unique name which is used to identify the tool in profiles and position logs.
Returns
Name of the tool ("AngleTool").
Implements MeaTool.
References kToolName.
IncPosition()
void MeaAngleTool::IncPosition (MeaFields which) override virtual
Increments the specified position field.
Parameters
which Field to increment
Reimplemented from MeaTool.
References m_point1, m_point2, m_vertex, MeaX1Field, MeaX2Field, MeaXVField, MeaY1Field, MeaY2Field, MeaYVField, and SetPosition().
LoadProfile()
void MeaAngleTool::LoadProfile (MeaProfile & profile) override virtual
Restores the state of the tool from the specified profile object.
Parameters
profile [in] The source for the state information. Typically an MeaFileProfile or MeaRegistryProfile object.
Reimplemented from MeaTool.
References MeaUnitsMgr::ConvertPos(), MeaSingleton_T< MeaUnitsMgr >::Instance(), m_point1, m_point2, m_vertex, m_vertexAnchor, MeaProfile::ReadDbl(), SetPosition(), MeaUnitsMgr::UnconvertPos(), FPOINT::x, and FPOINT::y.
OnCHEnter()
void MeaAngleTool::OnCHEnter (const CHInfo * info) override virtual
Called when the pointer enters one of the tool's crosshairs.
The crosshair entered is identified by the MeaCrossHairCallback::CHInfo structure passed to the method.
Parameters
info [in] Crosshair information structure
Reimplemented from MeaCrossHairCallback.
References MeaCrossHairCallback::CHInfo::id, kPoint1Id, kPoint2Id, kVertexId, m_dataWin1, m_dataWin2, m_dataWinV, MeaAssert, NormalUpdate, MeaDataWin::Show(), and Update().
OnCHLeave()
void MeaAngleTool::OnCHLeave (const CHInfo * info) override virtual
Called when the pointer leaves one of the tool's crosshairs.
The crosshair exited is identified by the MeaCrossHairCallback::CHInfo structure passed to the method.
Parameters
info [in] Crosshair information structure
Reimplemented from MeaCrossHairCallback.
References MeaDataWin::Hide(), MeaCrossHairCallback::CHInfo::id, kPoint1Id, kPoint2Id, kVertexId, m_dataWin1, m_dataWin2, m_dataWinV, and MeaAssert.
OnCHMove()
void MeaAngleTool::OnCHMove (const CHInfo * info) override virtual
Called when the user attempts to drag one of the tool's crosshairs.
The crosshair to be moved is identified by the MeaCrossHairCallback::CHInfo structure passed to the method. The info parameter indicates where the crosshair is to be moved and the tool actually moves the crosshair to the new position. This allows the tool to perform vertical or horizontal locking and move the entire tool depending on which keyboard modifiers are pressed during the drag.
Parameters
info [in] Crosshair information structure
Reimplemented from MeaCrossHairCallback.
References MeaCrossHairCallback::CHInfo::centerPoint, MeaCrossHairCallback::CHInfo::flags, MeaLine::GetPosition(), MeaLayout::GetSector(), MeaCrossHairCallback::CHInfo::id, MeaSingleton_T< MeaScreenMgr >::Instance(), kPoint1Id, kPoint2Id, MeaScreenMgr::LimitPosition(), m_curPos, m_line1, m_line2, m_point1, m_point1CH, m_point2, m_point2CH, m_vertex, m_vertexAnchor, m_vertexCH, NormalUpdate, MeaCrossHair::SetPosition(), MeaLine::SetPosition(), and Update().
SaveProfile()
void MeaAngleTool::SaveProfile (MeaProfile & profile) override virtual
Persists the state of the tool to the specified profile object.
Parameters
profile [in] The destination for the state information. Typically an MeaFileProfile or MeaRegistryProfile object.
Reimplemented from MeaTool.
References MeaUnitsMgr::ConvertPos(), MeaUtils::DblToStr(), MeaSingleton_T< MeaUnitsMgr >::Instance(), m_point1, m_point2, m_vertex, MeaProfile::WriteStr(), FPOINT::x, and FPOINT::y.
SetPosition() [1/2]
void MeaAngleTool::SetPosition (const PointMap & points) override virtual
Sets the position of the tool.
This method is called by the position log manager to play back a tool's position that was previously recorded using the GetPosition method.
Parameters
points [in] Map of positions for the tool's crosshairs.
Reimplemented from MeaRadioTool.
References m_point1, m_point2, m_vertex, NormalUpdate, SetPosition(), and Update().
SetPosition() [2/2]
void MeaAngleTool::SetPosition (MeaFields which, int pixels) override virtual
Sets the position of the tool.
This method sets the position one location component at a time. For example, the x position of the point 1 crosshair is specified by calling this method with the new position and specifying the MeaX1Field for the which parameter.
Parameters
which [in] Position component
pixels [in] Position to set for the component, in pixels
Reimplemented from MeaTool.
References MeaSingleton_T< MeaScreenMgr >::Instance(), MeaScreenMgr::LimitPosition(), m_curPos, m_line1, m_line2, m_point1, m_point1CH, m_point2, m_point2CH, m_vertex, m_vertexCH, MeaX1Field, MeaX2Field, MeaXVField, MeaY1Field, MeaY2Field, MeaYVField, NormalUpdate, MeaCrossHair::SetPosition(), MeaLine::SetPosition(), and Update().
Strobe()
void MeaAngleTool::Strobe () override virtual
Visually strobes the tool.
The tool crosshairs are cycled between a highlight color and their normal color once. In addition, the data windows attached to the crosshairs are cycled between hidden and visible. Strobing the tool is done to visually confirm position recording.
Reimplemented from MeaRadioTool.
References MeaCrossHair::Flash(), MeaCrossHair::kStrobeCount, m_dataWin1, m_dataWin2, m_dataWinV, m_point1CH, m_point2CH, m_vertexCH, and MeaDataWin::Strobe().
Update()
void MeaAngleTool::Update (MeaUpdateReason reason) override virtual
Requests that the tool update the display of its position data.
Parameters
reason [in] Reason why the update has been requested
Reimplemented from MeaTool.
References MeaUnitsMgr::ConvertCoord(), MeaLayout::GetAngle(), MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaTool::IsEnabled(), m_curPos, m_dataWin1, m_dataWin2, m_dataWinV, MeaTool::m_mgr, m_point1, m_point1CH, m_point2, m_point2CH, m_vertex, m_vertexCH, MeaDataWin::ShowAngle(), MeaToolMgr::ShowAngle(), MeaDataWin::ShowXY(), MeaToolMgr::ShowXY1(), MeaToolMgr::ShowXY2(), MeaToolMgr::ShowXYV(), MeaDataWin::Update(), MeaTool::Update(), UpdateBisector(), and MeaToolMgr::UpdateScreenInfo().
Referenced by Enable(), OnCHEnter(), OnCHMove(), and SetPosition().
The documentation for this class was generated from the following files:
AngleTool.h
AngleTool.cpp
Copyright 2011 C Thing Software