Meazure: MeaOriginTool Class Reference
MeaOriginTool Class Reference
Origin marker tool.
#include <OriginTool.h>
Public Member Functions
MeaOriginTool (MeaToolMgr *mgr)
Constructs a new instance of an Origin marker tool.
virtual ~MeaOriginTool ()
Hides and then destroys the Origin tool.
virtual void Enable () override
Displays the Origin tool.
virtual void Disable () override
Hides the Origin tool.
virtual void Update (MeaUpdateReason reason) override
Requests that the tool update its position based on the current origin location.
virtual void SaveProfile (MeaProfile &profile) override
Persists the state of the tool to the specified profile object.
virtual void LoadProfile (MeaProfile &profile) override
Restores the state of the tool from the specified profile object.
virtual void MasterReset () override
Resets the tool to its default state.
virtual const POINT & GetPosition () const override
Returns the tool's current position which, for the Origin tool, is location of the origin.
virtual CString GetToolName () const override
Returns the name of the tool.
virtual void ColorsChanged () override
Called to notify the tool that the colors in the MeaColors class have been changed.
Public Member Functions inherited from MeaTool
MeaTool (MeaToolMgr *mgr)
Base class constructor.
virtual ~MeaTool ()
Destroys the tool.
virtual void Enable ()
Typically used by derived classes to show the tool.
virtual void Disable ()
Typically used by derived classes to hide the tool.
virtual void Update (MeaUpdateReason reason)
Used by derived classes to update the display of their data.
virtual bool IsRadioTool ()
Indicates whether the derived tool is a radio tool and cannot be enabled until any other enabled Radio tool is disabled.
virtual void SetPosition (MeaFields which, int pixels)
Sets the position of the tool.
virtual const POINT & GetPosition () const =0
Returns the tool's current position.
virtual void IncPosition (MeaFields which)
Increments the specified position field.
virtual void DecPosition (MeaFields which)
Decrements the specified position field.
virtual CString GetToolName () const =0
Returns the name of the tool.
virtual void SaveProfile (MeaProfile &profile)
Persists the state of the tool to the specified profile object.
virtual void LoadProfile (MeaProfile &profile)
Restores the state of the tool from the specified profile object.
virtual void MasterReset ()
Resets the tool to its default state.
virtual void ColorsChanged ()
Called to notify the tool that the colors in the MeaColors class have been changed.
bool IsEnabled () const
Indicates whether the tool is enabled.
Static Public Attributes
static constexpr bool kShowMarker { true }
Indicates whether to show the origin marker by default.
static const CString kToolName
"OriginTool"
Private Member Functions
bool Create ()
Creates the tool's graphical components.
Private Attributes
MeaLine m_xAxis
Line to depict the x-axis.
MeaLine m_yAxis
Line to depict the y-axis.
Additional Inherited Members
Protected Attributes inherited from MeaTool
MeaToolMgr * m_mgr
Tool manager.
bool m_enabled
Indicates whether the tool is enabled.
Static Protected Attributes inherited from MeaTool
static POINT m_defaultPos { 0, 0 }
A default position used by tools that do not have a defined position. This position is returned by the GetPosition() method.
Detailed Description
Origin marker tool.
Two thin lines are arranged to form axes indicators on the screen at the location of the origin of the coordinate system. The intersection of the lines indicates the origin and the direction of the lines from the origin indicates the positive direction along the axis.
Constructor & Destructor Documentation
MeaOriginTool()
MeaOriginTool::MeaOriginTool (MeaToolMgr * mgr) explicit
Constructs a new instance of an Origin marker tool.
To use a newly constructed tool, the Enable() method must be called. Enable() will call the Create() method the first time it is called if Create() has not previously been called.
Parameters
mgr [in] Tool manager parent of the Origin tool.
Member Function Documentation
ColorsChanged()
void MeaOriginTool::ColorsChanged () override virtual
Called to notify the tool that the colors in the MeaColors class have been changed.
The origin lines are redrawn in their new colors.
Reimplemented from MeaTool.
References MeaColors::Get(), MeaColors::LineFore, m_xAxis, m_yAxis, and MeaLine::SetColor().
Create()
bool MeaOriginTool::Create () private
Creates the tool's graphical components.
The Origin tool consists of two lines arranged to form a coordinate axes indicator. The Enable() method must be called to make the tool visible.
Returns
true if the window is successfully created.
References MeaLine::Create(), m_xAxis, and m_yAxis.
Referenced by Enable().
Disable()
void MeaOriginTool::Disable () override virtual
Hides the Origin tool.
Reimplemented from MeaTool.
References MeaTool::Disable(), MeaLine::Hide(), MeaTool::IsEnabled(), m_xAxis, and m_yAxis.
Referenced by LoadProfile(), MasterReset(), and ~MeaOriginTool().
Enable()
void MeaOriginTool::Enable () override virtual
Displays the Origin tool.
If the Create() method has not been previously called, it will be called by Enable.
Reimplemented from MeaTool.
References Create(), MeaTool::Enable(), MeaTool::IsEnabled(), m_xAxis, m_yAxis, NormalUpdate, MeaGraphic::Show(), and Update().
Referenced by LoadProfile(), and MasterReset().
GetPosition()
const POINT & MeaOriginTool::GetPosition () const override virtual
Returns the tool's current position which, for the Origin tool, is location of the origin.
Returns
The location of the origin, in pixels
Implements MeaTool.
References MeaUnitsMgr::GetOrigin(), and MeaSingleton_T< MeaUnitsMgr >::Instance().
GetToolName()
CString MeaOriginTool::GetToolName () const override virtual
Returns the name of the tool.
Each tool has a unique name which is used to identify the tool in profiles and position logs.
Returns
Name of the tool ("OriginTool").
Implements MeaTool.
References kToolName.
Referenced by MeaToolMgr::MeaToolMgr().
LoadProfile()
void MeaOriginTool::LoadProfile (MeaProfile & profile) override virtual
Restores the state of the tool from the specified profile object.
Parameters
profile [in] The source for the state information. Typically an MeaFileProfile or MeaRegistryProfile object.
Reimplemented from MeaTool.
References Disable(), Enable(), kShowMarker, and MeaProfile::ReadBool().
MasterReset()
void MeaOriginTool::MasterReset () override virtual
Resets the tool to its default state.
Reimplemented from MeaTool.
References Disable(), Enable(), and kShowMarker.
SaveProfile()
void MeaOriginTool::SaveProfile (MeaProfile & profile) override virtual
Persists the state of the tool to the specified profile object.
Parameters
profile [in] The destination for the state information. Typically an MeaFileProfile or MeaRegistryProfile object.
Reimplemented from MeaTool.
References MeaTool::IsEnabled(), and MeaProfile::WriteBool().
Update()
void MeaOriginTool::Update (MeaUpdateReason reason) override virtual
Requests that the tool update its position based on the current origin location.
Parameters
reason [in] Reason why the update has been requested
Reimplemented from MeaTool.
References MeaUnitsMgr::ConvertToPixels(), MeaUnitsMgr::GetInvertY(), MeaUnitsMgr::GetOrigin(), MeaScreenMgr::GetScreenIter(), MeaScreenMgr::GetScreenRes(), MeaScreenMgr::GetVirtualRect(), MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaSingleton_T< MeaScreenMgr >::Instance(), MeaTool::IsEnabled(), m_xAxis, m_yAxis, MeaInchesId, MeaLine::SetPosition(), and MeaTool::Update().
Referenced by Enable().
The documentation for this class was generated from the following files:
OriginTool.h
OriginTool.cpp
Copyright 2011 C Thing Software