Meazure: MeaLayout Class Reference
MeaLayout Class Reference
Utility methods for performing various window layout tasks.
#include <Layout.h>
Static Public Member Functions
static void AlignLeft (int leftX,...)
Aligns the specified windows such that their left edges all begin at the specified x location.
static void AlignRight (int leftX,...)
Aligns the specified windows such that their right edges are all aligned.
static void AlignCenter (int topY,...)
Aligns the specified windows such that they all share a common vertical center.
static void AlignRightTo (const CWnd *baseWnd,...)
Performs a right alignment of the specified windows relative to the right edge of the specified base window.
static void PlaceAfter (const CWnd &frontWnd, const CWnd &backWnd, int spacing)
Places the back window after the specified front window and separates them by the specified spacing.
static bool SetWindowPos (const CWnd &wnd, int x, int y)
Sets the position of the specified window.
static bool SetWindowSize (const CWnd &wnd, int cx, int cy)
Sets the size of the specified window.
static int GetWindowHeight (const CWnd &wnd)
Returns the height of the specified window.
static bool SetWindowHeight (const CWnd &wnd, int cy)
Sets the height of the window.
static bool MoveWindowHeight (const CWnd &wnd, int cy)
Moves the specified window vertically.
static void GetBoundingSize (SIZE *sizep, const CWnd *parentWnd)
Calculates the bounding dimensions for all the children of the specified window.
static double CalcLength (double dx, double dy)
Calculates the length corresponding to the specified x and y distances using the formula:
static double CalcLength (const POINT &p1, const POINT &p2)
Calculates the length between the two specified points using the formula:
static double CalcCircumference (double radius)
Calculates the circumference of the circle with the specified radius using the formula:
static int GetSector (const POINT &start, const POINT &end)
Returns the angular sector containing the line specified by the two points.
static double GetAngle (const FPOINT &start, const FPOINT &end)
Returns the angle of the line from the specified start point to the specified end point relative to the horizontal (x-axis), measured in radians.
static double GetAngle (const FPOINT &vertex, const FPOINT &p1, const FPOINT &p2)
Returns the angle, in radians, between the line from the vertex to point p1 and the line from the vertex to point p2.
static bool ScreenToClientX (const CWnd &wnd, int &x)
Converts the x position in screen coordinates to an x position in the specified window's coordinate system.
static bool ScreenToClientY (const CWnd &wnd, int &y)
Converts the y position in screen coordinates to a y position in the specified window's coordinate system.
static void AlphaBlend (CDC &dstDC, const CDC &srcDC, int width, int height, BYTE alpha)
Performs and alpha blend on the two specified device contexts.
static void DrawOpacityBackground (const CWnd &wnd, CDC &dc)
Draws an image to use as a background for use in setting the a control's opacity.
Detailed Description
Utility methods for performing various window layout tasks.
Member Function Documentation
AlignCenter()
void MeaLayout::AlignCenter (int topY, ...) static
Aligns the specified windows such that they all share a common vertical center.
The top of the tallest window begins at the specified y position.
Parameters
topY [in] Tallest window begins at this y position, in pixels.
... [in] CWnd pointers terminated by NULL.
References SetWindowPos().
Referenced by MeaMagnifier::Create(), MeaDataDisplay::CreateRegionSection(), and MeaDataDisplay::CreateScreenSection().
AlignLeft()
void MeaLayout::AlignLeft (int leftX, ...) static
Aligns the specified windows such that their left edges all begin at the specified x location.
Parameters
leftX [in] Align each window's left edge to this x position, in pixels.
... [in] CWnd pointers terminated by NULL.
References SetWindowPos().
AlignRight()
void MeaLayout::AlignRight (int leftX, ...) static
Aligns the specified windows such that their right edges are all aligned.
The widest window is positioned at the specified x location.
Parameters
leftX [in] Widest window starts at this x position, in pixels.
... [in] CWnd pointers terminated by NULL.
References SetWindowPos().
Referenced by MeaDataDisplay::CreateRegionSection(), and MeaDataDisplay::CreateScreenSection().
AlignRightTo()
void MeaLayout::AlignRightTo (const CWnd * baseWnd, ...) static
Performs a right alignment of the specified windows relative to the right edge of the specified base window.
Parameters
baseWnd [in] Align windows relative to this base window.
... [in] CWnd pointers terminated by NULL.
References SetWindowPos().
Referenced by MeaDataDisplay::CreateRegionSection(), and MeaDataDisplay::CreateScreenSection().
AlphaBlend()
void MeaLayout::AlphaBlend (CDC & dstDC, const CDC & srcDC, int width, int height, BYTE alpha) static
Performs and alpha blend on the two specified device contexts.
The resulting blend is stored in the destination device context. The device contexts must be the same size.
Parameters
dstDC [in] Destination device context.
srcDC [in] Source device context.
width [in] Width of the device contexts, in pixels.
height [in] Height of the device contexts, in pixels.
alpha [in] Opacity value between 0 (transparent) and 255 (opaque).
Referenced by MeaCrossHair::OnPaint(), MeaDataWin::OnPaint(), and MeaRuler::OnPaint().
CalcCircumference()
static double MeaLayout::CalcCircumference (double radius) inline static
Calculates the circumference of the circle with the specified radius using the formula:
Parameters
radius [in] Radius of the circle.
Returns
Circumference of the circle.
References MeaUnits::kPI.
Referenced by MeaCircle::Create().
CalcLength() [1/2]
static double MeaLayout::CalcLength (const POINT & p1, const POINT & p2) inline static
Calculates the length between the two specified points using the formula:
Parameters
p1 [in] Point 1.
p2 [in] Point 2.
Returns
Length between point 1 and point 2.
References CalcLength().
CalcLength() [2/2]
static double MeaLayout::CalcLength (double dx, double dy) inline static
Calculates the length corresponding to the specified x and y distances using the formula:
Parameters
dx [in] X distance.
dy [in] Y distance.
Returns
Length corresponding to the vertical and horizontal distances.
Referenced by CalcLength(), MeaDataWin::CalcWidth(), MeaCircle::Create(), MeaLine::Create(), MeaCircle::GetRadius(), MeaPositionLogMgr::Position::RecordDistance(), MeaDataWin::ShowDistance(), and MeaDataDisplay::ShowDistance().
DrawOpacityBackground()
void MeaLayout::DrawOpacityBackground (const CWnd & wnd, CDC & dc) static
Draws an image to use as a background for use in setting the a control's opacity.
Parameters
wnd [in] Window representing the control.
dc [in] Device context into which to draw the background.
References MeaUnitsMgr::ConvertToPixels(), MeaScreenMgr::GetScreenIter(), MeaScreenMgr::GetScreenRes(), MeaSingleton_T< MeaScreenMgr >::Instance(), MeaSingleton_T< MeaUnitsMgr >::Instance(), and MeaInchesId.
Referenced by MeaRuler::Create(), MeaCrossHair::Create(), and MeaDataWin::OnPaint().
GetAngle() [1/2]
static double MeaLayout::GetAngle (const FPOINT & start, const FPOINT & end) inline static
Returns the angle of the line from the specified start point to the specified end point relative to the horizontal (x-axis), measured in radians.
Using the default coordinate system (i.e. positive y-axis pointed down from the origin), positive angles are measured clockwise from the horizontal to the line from start point to end point. The following formula is used:
Parameters
start [in] Starting point for the line whose angle is to be determined.
end [in] Ending point for the line whose angle is to be determined.
Returns
Angle between the x-axis and the line, in radians. Degenerate cases return 0.0.
References FPOINT::x, and FPOINT::y.
Referenced by MeaAngleTool::GetPosition(), MeaCircleTool::GetPosition(), MeaLineTool::GetPosition(), MeaRectTool::GetPosition(), MeaWindowTool::GetPosition(), MeaAngleTool::Update(), MeaCircleTool::Update(), MeaLineTool::Update(), MeaRectTool::Update(), MeaWindowTool::Update(), and MeaAngleTool::UpdateBisector().
GetAngle() [2/2]
static double MeaLayout::GetAngle (const FPOINT & vertex, const FPOINT & p1, const FPOINT & p2) inline static
Returns the angle, in radians, between the line from the vertex to point p1 and the line from the vertex to point p2.
Using the default coordinate system (i.e. positive y-axis pointed down from the origin), positive angles are measured clockwise from the vertex-p1 line to the vertex-p2 line.
Parameters
vertex [in] Intersection point for the two lines.
p1 [in] Forms the end point for the first line from the vertex.
p2 [in] Forms the end point for the second line from the vertex.
Returns
Angle between the the lines vertex-p1 and vertex-p2.
References FPOINT::x, and FPOINT::y.
GetBoundingSize()
void MeaLayout::GetBoundingSize (SIZE * sizep, const CWnd * parentWnd) static
Calculates the bounding dimensions for all the children of the specified window.
Parameters
sizep [out] Bounding dimensions encompassing all child windows.
parentWnd [in] All child windows of this window form the bounding dimensions.
Referenced by MeaDataDisplay::Create(), MeaDataDisplay::CreateRegionSection(), and MeaDataDisplay::CreateScreenSection().
GetSector()
static int MeaLayout::GetSector (const POINT & start, const POINT & end) inline static
Returns the angular sector containing the line specified by the two points.
Parameters
start [in] Starting point for the line.
end [in] Ending point for the line.
Returns
The circular sector corresponding to the line. The value is an integer between -4 and 4
Referenced by MeaAngleTool::OnCHMove(), MeaCircleTool::OnCHMove(), MeaLineTool::OnCHMove(), MeaPointTool::OnCHMove(), and MeaRectTool::OnCHMove().
GetWindowHeight()
static int MeaLayout::GetWindowHeight (const CWnd & wnd) inline static
Returns the height of the specified window.
Parameters
wnd [in] Window whose height is desired.
Returns
Height of the window in pixels.
Referenced by CChildView::CheckMargins(), MeaToolsPrefs::OnInitDialog(), CChildView::ViewMagnifier(), CChildView::ViewScreenInfo(), and CChildView::ViewToolInfo().
MoveWindowHeight()
static bool MeaLayout::MoveWindowHeight (const CWnd & wnd, int cy) inline static
Moves the specified window vertically.
Parameters
wnd [in] Window to be moved.
cy [in] Vertical distance to move window, in pixels.
Returns
true if the method succeeds.
Referenced by MeaDataDisplay::Disable(), MeaDataDisplay::Enable(), CChildView::ViewScreenInfo(), and CChildView::ViewToolInfo().
PlaceAfter()
void MeaLayout::PlaceAfter (const CWnd & frontWnd, const CWnd & backWnd, int spacing) static
Places the back window after the specified front window and separates them by the specified spacing.
Parameters
frontWnd [in] Window in front of backWnd.
backWnd [in] Window to place after frontWnd.
spacing [in] Separation between the two windows, in pixels.
References SetWindowPos().
Referenced by MeaMagnifier::Create(), MeaDataDisplay::CreateRegionSection(), and MeaDataDisplay::CreateScreenSection().
ScreenToClientX()
static bool MeaLayout::ScreenToClientX (const CWnd & wnd, int & x) inline static
Converts the x position in screen coordinates to an x position in the specified window's coordinate system.
Parameters
wnd [in] The x coordinate is converts to this window's coordinate system.
x [in, out] The x coordinate to convert.
Returns
true if the conversion was successful.
Referenced by MeaRuler::DrawIndicator(), and MeaRuler::DrawRuler().
ScreenToClientY()
static bool MeaLayout::ScreenToClientY (const CWnd & wnd, int & y) inline static
Converts the y position in screen coordinates to a y position in the specified window's coordinate system.
Parameters
wnd [in] The y coordinate is converts to this window's coordinate system.
y [in, out] The y coordinate to convert.
Returns
true if the conversion was successful.
Referenced by MeaRuler::DrawIndicator(), and MeaRuler::DrawRuler().
SetWindowHeight()
static bool MeaLayout::SetWindowHeight (const CWnd & wnd, int cy) inline static
Sets the height of the window.
Parameters
wnd [in] Window whose height is to be set.
cy [in] Height for the window, in pixels.
Returns
true if the method succeeds.
Referenced by CChildView::CheckMargins(), CChildView::ViewMagnifier(), CChildView::ViewScreenInfo(), and CChildView::ViewToolInfo().
SetWindowPos()
static bool MeaLayout::SetWindowPos (const CWnd & wnd, int x, int y) inline static
Sets the position of the specified window.
Parameters
wnd [in] Window to position.
x [in] X position for the window, in pixels.
y [in] Y position for the window, in pixels.
Returns
true if the method succeeds.
Referenced by AlignCenter(), AlignLeft(), AlignRight(), AlignRightTo(), MeaDataDisplay::Create(), MeaDataDisplay::CreateScreenSection(), CChildView::OnCreate(), and PlaceAfter().
SetWindowSize()
static bool MeaLayout::SetWindowSize (const CWnd & wnd, int cx, int cy) inline static
Sets the size of the specified window.
Parameters
wnd [in] Window to size.
cx [in] Width for the window, in pixels.
cy [in] Height for the window, in pixels.
Returns
true if the method succeeds.
Referenced by MeaDataDisplay::Create(), MeaMagnifier::Create(), MeaNumberField::Create(), MeaLabel::Create(), MeaDataDisplay::CreateRegionSection(), MeaDataDisplay::CreateScreenSection(), MeaDataDisplay::DataItem::CreateSpinButton(), CMainFrame::OnCreate(), MeaUnitsLabel::SetSize(), CMainFrame::ViewStatusbar(), and CMainFrame::ViewToolbar().
The documentation for this class was generated from the following files:
Layout.h
Layout.cpp
Copyright 2011 C Thing Software