Meazure: App Class Reference
App Class Reference
The application class.
#include <App.h>
Public Member Functions
App ()
Starts the application.
virtual BOOL SaveAllModified () override
Called by the framework to see if each modified doc wants to save before the application goes away.
virtual void WinHelp (DWORD dwData, UINT nCmd)
Central interface to the windows help system.
virtual BOOL InitInstance () override
Performs all initialization for the application including processing of the command line arguments, if any.
afx_msg void OnAppAbout ()
Displays the application About dialog.
afx_msg void OnMouseHook (WPARAM wParam, LPARAM lParam)
Called by the Mouse Hook DLL to route pointer movement messages to the View.
Detailed Description
The application class.
Instantiating this class starts the application.
Member Function Documentation
InitInstance()
BOOL App::InitInstance () override virtual
Performs all initialization for the application including processing of the command line arguments, if any.
Returns
TRUE if initialization successful.
References AppFrame::SetCommandLineFile().
OnMouseHook()
void App::OnMouseHook (WPARAM wParam, LPARAM lParam)
Called by the Mouse Hook DLL to route pointer movement messages to the View.
Parameters
wParam [in] Message ID.
lParam [in] MOUSEHOOKSTRUCT
SaveAllModified()
BOOL App::SaveAllModified () override virtual
Called by the framework to see if each modified doc wants to save before the application goes away.
Returns
TRUE if safe to exit the application, FALSE otherwise.
References MeaSingleton_T< MeaPositionLogMgr >::Instance(), and MeaPositionLogMgr::SaveIfModified().
WinHelp()
void App::WinHelp (DWORD dwData, UINT nCmd) virtual
Central interface to the windows help system.
In this case we override the base class calls to the old WinHelp system and instead call the new Windows HTML Help system.
Parameters
dwData [in] ID for context sensitive help.
nCmd [in] Type of help requested.
The documentation for this class was generated from the following files:
App.h
App.cpp
Copyright 2011 C Thing Software