Meazure: ev::ValidationError Class Reference
ev::ValidationError Class Reference
Class to represent a validation error.
#include <exval.h>
Public Types
enum Code {
MultipleDocumentElements,
MultipleTopLevelElements,
InvalidDocumentElement,
UndeclaredElement,
UndeclaredAttribute,
InvalidElement,
NoCharacterData,
UncontainedCharacterData,
MismatchedFixedValue,
MissingRequiredAttribute,
BadAttributeValue,
DuplicateId,
UndeclaredNotation,
UndeclaredEntity,
IdNotFound,
InvalidElementPattern
}
Validation error code.
Public Member Functions
const XML_Char * GetMessage () const
Returns the validation error message.
Code GetCode () const
Returns the validation error code.
const XML_Char * GetCurrentElement () const
Returns the last element parsed before the error occurred.
const XML_Char * GetContainingElement () const
Returns the current element's container element.
int GetLineNumber () const
Returns the line number on which the validation error occurred.
int GetCharacterPosition () const
Returns the character position on the line which caused the validation error.
long GetByteOffset () const
Returns the total byte offset into the file to the point where the validation error occurred.
Protected Member Functions
ValidationError (XML_Parser parser, Code errorCode, const XML_Char *currentElement, const XML_Char *containingElement)
Constructs a validation error object.
virtual ~ValidationError ()
Destroys a validation error object.
Protected Attributes
Code m_errorCode
Validation error code.
EVString m_errorMsg
Validation error message.
EVString m_currentElement
Name of the last element parsed.
EVString m_containingElement
Name of the element's containing element.
int m_lineNumber
Line number where the validation error occurred.
int m_characterPosition
Character position on line where the validation error occurred.
long m_byteOffset
Byte offset to point where the validation error occurred.
Friends
class Validator
Only a Validator is allowed to construct a validation error object.
Detailed Description
Class to represent a validation error.
An application class inherits from the IValidationHandler interface and overrides the HandleValidationError method. This method is passed a ValidationError instance whenever the validator detects an invalid construct.
Member Enumeration Documentation
enum ev::ValidationError::Code
Validation error code.
Enumerator:
MultipleDocumentElements
The Document Element occurs more than once at the top level.
MultipleTopLevelElements
There are multiple top level elements.
InvalidDocumentElement
The top level element does not match DOCTYPE declaration.
UndeclaredElement
Element not found in DTD.
UndeclaredAttribute
Attribute not found in DTD.
InvalidElement
Element not allowed by content model.
NoCharacterData
Element does not allow PCDATA.
UncontainedCharacterData
Character data with no containing element.
MismatchedFixedValue
Value of #FIXED attribute does not match DTD.
MissingRequiredAttribute
Required attribute missing from element.
BadAttributeValue
Attribute value not in set of possible values.
DuplicateId
Duplicate ID values within document.
UndeclaredNotation
Notation not found in DTD.
UndeclaredEntity
Entity not found in DTD.
IdNotFound
Could not find ID corresponding to IDREF.
InvalidElementPattern
Element pattern violates content model.
Constructor & Destructor Documentation
ValidationError::ValidationError (XML_Parser parser, Code errorCode, const XML_Char * currentElement, const XML_Char * containingElement) [protected]
Constructs a validation error object.
Parameters:
parser [in] Parser object.
errorCode [in] Validation error code.
currentElement [in] Name of the last element parsed.
containingElement [in] Current element's containing element name.
References BadAttributeValue, DuplicateId, EV_T, IdNotFound, InvalidDocumentElement, InvalidElement, InvalidElementPattern, m_errorCode, m_errorMsg, MismatchedFixedValue, MissingRequiredAttribute, MultipleDocumentElements, MultipleTopLevelElements, NoCharacterData, UncontainedCharacterData, UndeclaredAttribute, UndeclaredElement, UndeclaredEntity, and UndeclaredNotation.
Member Function Documentation
long ev::ValidationError::GetByteOffset () const [inline]
Returns the total byte offset into the file to the point where the validation error occurred.
Returns:
Number of bytes into the file to the point where the validation error occurred.
References m_byteOffset.
int ev::ValidationError::GetCharacterPosition () const [inline]
Returns the character position on the line which caused the validation error.
Returns:
Character position on the line that caused the validation error.
References m_characterPosition.
Referenced by MeaXMLParser::HandleValidationError().
Code ev::ValidationError::GetCode () const [inline]
Returns the validation error code.
Returns:
Validation error message code.
References m_errorCode.
Referenced by MeaXMLParser::HandleValidationError().
const XML_Char* ev::ValidationError::GetContainingElement () const [inline]
Returns the current element's container element.
Returns:
Name of the current element's container element.
References m_containingElement.
Referenced by MeaXMLParser::HandleValidationError().
const XML_Char* ev::ValidationError::GetCurrentElement () const [inline]
Returns the last element parsed before the error occurred.
Returns:
Name of the element parsed before the error occurred.
References m_currentElement.
Referenced by MeaXMLParser::HandleValidationError().
int ev::ValidationError::GetLineNumber () const [inline]
Returns the line number on which the validation error occurred.
Returns:
Line number where the validation error occurred.
References m_lineNumber.
Referenced by MeaXMLParser::HandleValidationError().
const XML_Char* ev::ValidationError::GetMessage () const [inline]
Returns the validation error message.
Returns:
Validation error message string.
References m_errorMsg.
Friends And Related Function Documentation
friend class Validator [friend]
Only a Validator is allowed to construct a validation error object.
The documentation for this class was generated from the following files:
exval.h
exval.cpp
Copyright 2011 C Thing Software