Meazure: MeaVersionInfo Class Reference
MeaVersionInfo Class Reference
Convenience class for obtaining version number information for the applications.
#include <VersionInfo.h>
Public Member Functions
MeaVersionInfo (token)
Constructs an instance of the version number information class.
virtual ~MeaVersionInfo ()
Destroys an instance of the class.
CString GetProductVersion () const
Retrieves the product version number.
int GetProductMajor () const
Returns the product major version number.
int GetProductMinor () const
Returns the product minor version number.
int GetProductFix () const
Returns the product fix number.
int GetProductBuild () const
Returns the product build number.
constexpr int GetProfileFileMajor () const
Returns the version number of the profile file format.
constexpr int GetLogFileMajor () const
Returns the version number of the position log file format.
Public Member Functions inherited from MeaSingleton_T< MeaVersionInfo >
MeaSingleton_T (const MeaSingleton_T< MeaVersionInfo > &src)=delete
Singletons have no copy semantics.
MeaSingleton_T< MeaVersionInfo > & operator= (const MeaSingleton_T< MeaVersionInfo > &src)=delete
Singletons have no assignment semantics.
Private Member Functions
MeaVersionInfo (const MeaVersionInfo &)
The class does not have copy semantics so this method is purposely undefined.
MeaVersionInfo & operator= (const MeaVersionInfo &)
The class does not have assignment semantics so this method is purposely undefined.
Private Attributes
void * m_data
Version information buffer.
VS_FIXEDFILEINFO * m_info
Version information.
Additional Inherited Members
Static Public Member Functions inherited from MeaSingleton_T< MeaVersionInfo >
static MeaVersionInfo & Instance ()
The first time this method is called, a instance of the Singleton object is created and returned.
Protected Member Functions inherited from MeaSingleton_T< MeaVersionInfo >
MeaSingleton_T ()=default
Constructs a Singleton object instance.
Detailed Description
Convenience class for obtaining version number information for the applications.
Member Function Documentation
GetLogFileMajor()
constexpr int MeaVersionInfo::GetLogFileMajor () const inline constexpr
Returns the version number of the position log file format.
Returns
Version number of the position log file format.
GetProductBuild()
int MeaVersionInfo::GetProductBuild () const inline
Returns the product build number.
Returns
Build number.
References m_info.
GetProductFix()
int MeaVersionInfo::GetProductFix () const inline
Returns the product fix number.
Returns
Fix number.
References m_info.
Referenced by GetProductVersion().
GetProductMajor()
int MeaVersionInfo::GetProductMajor () const inline
Returns the product major version number.
Returns
Major version number.
References m_info.
Referenced by GetProductVersion().
GetProductMinor()
int MeaVersionInfo::GetProductMinor () const inline
Returns the product minor version number.
Returns
Minor version number.
References m_info.
Referenced by GetProductVersion().
GetProductVersion()
CString MeaVersionInfo::GetProductVersion () const
Retrieves the product version number.
Returns
Product version number expressed as string of the form major.minor or major.minor.fix (if fix > 0).
References GetProductFix(), GetProductMajor(), and GetProductMinor().
Referenced by CAboutDlg::OnInitDialog().
GetProfileFileMajor()
constexpr int MeaVersionInfo::GetProfileFileMajor () const inline constexpr
Returns the version number of the profile file format.
Returns
Version number of the profile file format.
The documentation for this class was generated from the following files:
VersionInfo.h
VersionInfo.cpp
Copyright 2011 C Thing Software