Meazure: MeaCustomUnits Class Reference
MeaCustomUnits Class Reference
Provides linear measurements in user defined units.
#include <Units.h>
Public Types
enum ScaleBasis {
PixelBasis = 0 ,
InchBasis = 1 ,
CentimeterBasis = 2
}
User defined units are based on a conversion factor.
typedef void(* ChangeLabelFunc) (MeaLinearUnitsId, const CString &)
Public Types inherited from MeaUnits
typedef std::vector< int > DisplayPrecisions
Number of decimal places to display for each type of measurement.
typedef std::vector< CString > DisplayPrecisionNames
Strings to identify units precisions in profiles.
Public Member Functions
MeaCustomUnits (const MeaScreenProvider &screenProvider, ChangeLabelFunc changeLabelFunc)
Constructs custom units.
~MeaCustomUnits ()
Destroys custom units.
virtual void SaveProfile (MeaProfile &profile) override
Persists the custom units conversion factor and basis to the specified profile object.
virtual void LoadProfile (MeaProfile &profile) override
Restores the custom units conversion factor and basis from the specified profile object.
virtual void MasterReset () override
Called when the master reset is initiated.
virtual bool RequiresRes () const override
Indicates whether the custom units requires a screen resolution to perform its conversion from pixels.
bool HaveCustomUnits () const
Indicates whether custom units have been defined.
CString GetName () const
Returns the name of the custom units.
void SetName (const CString &name)
Sets a name for the custom units.
CString GetAbbrev () const
Returns the abbreviation for the custom units.
void SetAbbrev (const CString &abbrev)
Sets an abbreviation for the custom units.
ScaleBasis GetScaleBasis () const
Returns the conversion basis.
CString GetScaleBasisStr () const
Returns the scale basis as an identifying string (e.g.
void SetScaleBasis (ScaleBasis scaleBasis)
Sets the conversion basis.
void SetScaleBasis (CString scaleBasisStr)
Sets the conversion basis using a string identifier.
double GetScaleFactor () const
Returns the conversion factor for the custom units.
void SetScaleFactor (double scaleFactor)
Sets the conversion factor for the custom units.
virtual MeaFSize FromPixels (const MeaFSize &res) const override
Returns the X and Y factors to convert from pixels to the custom units.
Public Member Functions inherited from MeaLinearUnits
virtual ~MeaLinearUnits ()
Destroys the linear units.
MeaLinearUnitsId GetUnitsId () const
Returns the identifier for the linear units.
virtual bool RequiresRes () const
Internally all measurements are in pixels.
CString Format (MeaLinearMeasurementId id, double value) const
Formats the specified linear measurement value using the precision for the specified measurement ID.
MeaFPoint ConvertCoord (const POINT &pos) const
Converts the specified coordinate from pixels to the desired units.
MeaFPoint ConvertPos (const POINT &pos) const
Converts the specified position from pixels to the desired units.
MeaFSize ConvertRes (const MeaFSize &res) const
Converts the specified resolution in pixels/inch to the desired units.
double UnconvertCoord (MeaConvertDir dir, const CWnd *wnd, double pos) const
Converts from the current units to pixels.
bool UnconvertCoord (MeaConvertDir dir, const CWnd *wnd, double pos, int &c1, int &c2) const
Converts from the current units to pixels.
POINT UnconvertCoord (const MeaFPoint &pos) const
Converts from the current units to pixels.
POINT UnconvertPos (const MeaFPoint &pos) const
Converts from the current units to pixels.
SIZE ConvertToPixels (const MeaFSize &res, double value, int minPixels) const
Converts the specified value from the current units to pixels.
virtual MeaFSize FromPixels (const MeaFSize &res) const =0
Returns the X and Y factors to convert from pixels to the current units.
Public Member Functions inherited from MeaUnits
virtual ~MeaUnits ()
Base class destructor.
virtual void SaveProfile (MeaProfile &profile)
Persists the state of a units class instance to the specified profile object.
virtual void LoadProfile (MeaProfile &profile)
Restores the state of a units class instance from the specified profile object.
void SavePrecision (MeaProfile &profile)
Persists the measurement precisions to the specified profile object.
void LoadPrecision (MeaProfile &profile)
Restores the measurement precisions from the specified profile object.
virtual void MasterReset ()
Called to restores the units to their default state.
CString GetUnitsStr () const
Returns a string describing the units.
void SetDisplayPrecisions (const DisplayPrecisions &displayPrecisions)
Sets the decimal place precisions for all measurement types.
const DisplayPrecisions & GetDisplayPrecisions () const
Returns the current decimal place precisions for all measurement types.
const DisplayPrecisions & GetDefaultPrecisions () const
Returns the default decimal place precisions for all measurement types.
void RestoreDefaultPrecisions ()
Sets the default display precisions as the current precisions.
const DisplayPrecisionNames & GetDisplayPrecisionNames () const
Returns the identifying names for the display precisions.
Static Public Attributes
static const double kDefScaleFactor = 1.0
Default scale factor.
static const ScaleBasis kDefScaleBasis = MeaCustomUnits::PixelBasis
Default basis for the custom units.
Private Attributes
ChangeLabelFunc m_changeLabelFunc
Function to change the label text.
CString m_name
Name for the custom units.
CString m_abbrev
Abbreviation for the custom units.
ScaleBasis m_scaleBasis
Conversion basis for the custom units.
double m_scaleFactor
Conversion factor for the custom units.
Additional Inherited Members
Static Public Member Functions inherited from MeaLinearUnits
static void SetInvertY (bool invertY)
By default, the Windows coordinate system is inverted from the typical Cartesian coordinate system in that the origin is located in the upper left corner of the primary screen and the positive y-axis points downward.
static bool IsInvertY ()
Returns the orientation of the y-axis.
static void SetOrigin (const POINT &origin)
Moves the origin of the coordinate system to the specified point.
static const POINT & GetOrigin ()
Returns the location of the origin of the coordinate system.
Protected Member Functions inherited from MeaLinearUnits
MeaLinearUnits (MeaLinearUnitsId unitsId, LPCTSTR unitsStr, const MeaScreenProvider &screenProvider)
Constructs the linear units.
virtual MeaFSize GetResFromPixels (const MeaFSize &res) const
Returns a resolution conversion factor.
double ConvertCoord (MeaConvertDir dir, const CWnd *wnd, int pos) const
Converts from the pixels to the current units.
const MeaFSize & FindResFromCoord (const MeaFPoint &pos) const
In a multiple monitor environment there are multiple screen resolutions, one set per monitor.
const MeaFSize & FindResFromPos (const MeaFPoint &pos) const
In a multiple monitor environment there are multiple screen resolutions, one set per monitor.
Protected Member Functions inherited from MeaUnits
MeaUnits (LPCTSTR unitsStr)
Base class constructor.
void AddPrecisionName (LPCTSTR name)
Adds the specified identifying name to the list of precision names.
void AddPrecision (int precision)
Adds the specified precision value to both the list of current precisions and the list of default precisions.
Protected Attributes inherited from MeaLinearUnits
const MeaScreenProvider & m_screenProvider
Screen information provider.
Detailed Description
Provides linear measurements in user defined units.
Member Enumeration Documentation
ScaleBasis
enum MeaCustomUnits::ScaleBasis
User defined units are based on a conversion factor.
This factor converts from a basis set of units to the custom units. The basis for the conversion is identified by this enumeration.
Enumerator
PixelBasis
Custom units = factor * pixels.
InchBasis
Custom units = factor * inches.
CentimeterBasis
Custom units = factor * centimeters.
Constructor & Destructor Documentation
MeaCustomUnits()
MeaCustomUnits::MeaCustomUnits (const MeaScreenProvider & screenProvider, ChangeLabelFunc changeLabelFunc)
Constructs custom units.
Parameters
screenProvider [in] Screen information provider
changeLabelFunc [in] Function to change the label of the custom units
References MeaUnits::AddPrecision().
Member Function Documentation
FromPixels()
MeaFSize MeaCustomUnits::FromPixels (const MeaFSize & res) const override virtual
Returns the X and Y factors to convert from pixels to the custom units.
In other words, multiplying the values returned from this method by pixels results in a value expressed in the custom units.
Parameters
res [in] Screen resolution, in pixels/inch.
Returns
X and Y conversion factors, in custom units/pixels.
Implements MeaLinearUnits.
References CentimeterBasis, MeaFSize::cx, MeaFSize::cy, InchBasis, m_scaleBasis, m_scaleFactor, and PixelBasis.
GetAbbrev()
CString MeaCustomUnits::GetAbbrev () const inline
Returns the abbreviation for the custom units.
The abbreviation is used by the data display and in other places.
Returns
Abbreviation for the units.
References m_abbrev.
Referenced by MeaPositionDesktop::MeaPositionDesktop(), and AppView::OnPreferences().
GetName()
CString MeaCustomUnits::GetName () const inline
Returns the name of the custom units.
The name is used on the units menu as well as other places.
Returns
Name for the units.
References m_name.
Referenced by MeaPositionDesktop::MeaPositionDesktop(), AppView::OnPreferences(), and AppView::OnUpdateCustomUnits().
GetScaleBasis()
ScaleBasis MeaCustomUnits::GetScaleBasis () const inline
Returns the conversion basis.
Returns
Custom units conversion basis.
References m_scaleBasis.
Referenced by AppView::OnPreferences().
GetScaleBasisStr()
CString MeaCustomUnits::GetScaleBasisStr () const
Returns the scale basis as an identifying string (e.g.
"px").
Returns
Conversion basis as a string.
References CentimeterBasis, InchBasis, m_scaleBasis, and PixelBasis.
Referenced by MeaPositionDesktop::MeaPositionDesktop(), and SaveProfile().
GetScaleFactor()
double MeaCustomUnits::GetScaleFactor () const inline
Returns the conversion factor for the custom units.
Returns
Conversion factor from the conversion basis to the custom units.
References m_scaleFactor.
Referenced by MeaPositionDesktop::MeaPositionDesktop(), and AppView::OnPreferences().
HaveCustomUnits()
bool MeaCustomUnits::HaveCustomUnits () const inline
Indicates whether custom units have been defined.
Returns
true if custom units have been defined. Custom units are considered to be defined if they have a name and abbreviation.
References m_abbrev, and m_name.
Referenced by AppView::ApplyPreferences(), and AppView::OnUpdateCustomUnits().
LoadProfile()
void MeaCustomUnits::LoadProfile (MeaProfile & profile) override virtual
Restores the custom units conversion factor and basis from the specified profile object.
Parameters
profile [in] Profile object from which to restore the custom units.
Reimplemented from MeaUnits.
References MeaUnits::LoadPrecision(), m_abbrev, m_name, m_scaleFactor, MeaProfile::ReadDbl(), MeaProfile::ReadStr(), SetAbbrev(), SetName(), SetScaleBasis(), and SetScaleFactor().
MasterReset()
void MeaCustomUnits::MasterReset () override virtual
Called when the master reset is initiated.
Resets the custom units to its default state.
Reimplemented from MeaUnits.
References kDefScaleBasis, kDefScaleFactor, MeaUnits::MasterReset(), SetAbbrev(), SetName(), SetScaleBasis(), and SetScaleFactor().
RequiresRes()
bool MeaCustomUnits::RequiresRes () const override virtual
Indicates whether the custom units requires a screen resolution to perform its conversion from pixels.
Returns
true if the conversion basis is not based on pixels.
Reimplemented from MeaLinearUnits.
References m_scaleBasis, and PixelBasis.
SaveProfile()
void MeaCustomUnits::SaveProfile (MeaProfile & profile) override virtual
Persists the custom units conversion factor and basis to the specified profile object.
Parameters
profile [in] Profile object into which to persist the custom units.
Reimplemented from MeaUnits.
References GetScaleBasisStr(), m_abbrev, m_name, m_scaleFactor, MeaUnits::SavePrecision(), MeaProfile::WriteDbl(), and MeaProfile::WriteStr().
SetAbbrev()
void MeaCustomUnits::SetAbbrev (const CString & abbrev)
Sets an abbreviation for the custom units.
The abbreviation is displayed by the data display and in other places.
Parameters
abbrev [in] Abbreviation for the units.
References m_abbrev, m_changeLabelFunc, and MeaCustomId.
Referenced by AppView::ApplyPreferences(), LoadProfile(), MasterReset(), and MeaPositionLogMgr::ShowPosition().
SetName()
void MeaCustomUnits::SetName (const CString & name)
Sets a name for the custom units.
The name is displayed on the units menu and in other places.
Parameters
name [in] Name for the units.
References m_name.
Referenced by AppView::ApplyPreferences(), LoadProfile(), MasterReset(), and MeaPositionLogMgr::ShowPosition().
SetScaleBasis() [1/2]
void MeaCustomUnits::SetScaleBasis (CString scaleBasisStr)
Sets the conversion basis using a string identifier.
Parameters
scaleBasisStr [in] Conversion basis as an identifying string.
References CentimeterBasis, InchBasis, PixelBasis, and SetScaleBasis().
SetScaleBasis() [2/2]
void MeaCustomUnits::SetScaleBasis (ScaleBasis scaleBasis) inline
Sets the conversion basis.
Parameters
scaleBasis [in] Conversion basis.
References m_scaleBasis.
Referenced by AppView::ApplyPreferences(), LoadProfile(), MasterReset(), SetScaleBasis(), and MeaPositionLogMgr::ShowPosition().
SetScaleFactor()
void MeaCustomUnits::SetScaleFactor (double scaleFactor) inline
Sets the conversion factor for the custom units.
Parameters
scaleFactor [in] Conversion factor from the conversion basis to the custom units.
References m_scaleFactor.
Referenced by AppView::ApplyPreferences(), LoadProfile(), MasterReset(), and MeaPositionLogMgr::ShowPosition().
The documentation for this class was generated from the following files:
Units.h
Units.cpp
Copyright 2011 C Thing Software