Meazure: MeaCircleTool Class Reference
MeaCircleTool Class Reference
Circle measurement tool.
#include <CircleTool.h>
Public Member Functions
MeaCircleTool (MeaToolMgr &mgr, const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Constructs a new instance of a circle measurement tool.
virtual ~MeaCircleTool ()
Hides and then destroys the Circle tool.
virtual void Enable () override
Displays the Circle tool.
virtual void Disable () override
Hides the Circle tool.
virtual void Update (MeaUpdateReason reason) override
Requests that the tool update the display of its position data.
virtual bool HasRegion () override
Indicates whether the tool can define a rectangular region that can then be read for a screen capture.
virtual RECT GetRegion () override
Returns the rectangle defined by the tool.
virtual void SaveProfile (MeaProfile &profile) override
Persists the state of the tool to the specified profile object.
virtual void LoadProfile (MeaProfile &profile) override
Restores the state of the tool from the specified profile object.
virtual void EnableCrosshairs () override
Displays the tool's crosshairs.
virtual void DisableCrosshairs () override
Hides the tool's crosshairs.
virtual void Flash () override
Visually flashes the tool.
virtual void Strobe () override
Visually strobes the tool.
virtual void SetPosition (MeaDataFieldId which, int pixels) override
Sets the position of the tool.
virtual void SetPosition (const PointMap &points) override
Sets the position of the tool.
virtual const POINT & GetPosition () const override
Returns the tool's current position.
virtual void RecordPosition (MeaPosition &position) const override
Records the position of the tool.
virtual void IncPosition (MeaDataFieldId which) override
Increments the specified position field.
virtual void DecPosition (MeaDataFieldId which) override
Decrements the specified position field.
virtual PCTSTR GetToolName () const override
Returns the name of the tool.
virtual UINT GetLabelId () const override
Returns a resource ID for the string used to label this tool on the data display.
virtual void ColorsChanged () override
Called to notify the tool that the colors in the MeaColors class have been changed.
virtual void OnCHEnter (const CrossHairInfo *info) override
Called when the pointer enters one of the tool's crosshairs.
virtual void OnCHLeave (const CrossHairInfo *info) override
Called when the pointer leaves one of the tool's crosshairs.
virtual void OnCHMove (const CrossHairInfo *info) override
Called when the user attempts to drag one of the tool's crosshairs.
Public Member Functions inherited from MeaRadioTool
MeaRadioTool (MeaToolMgr &mgr, const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Constructs a new instance of an radio based measurement tool.
virtual bool IsRadioTool () override
Indicates that the derived tool is a Radio tool and cannot be enabled until any other enabled Radio tool is disabled.
virtual UINT GetLabelId () const
Returns a resource ID for the string used to label this tool on the data display.
virtual bool HasCrosshairs () const
Indicates whether the derived tool uses crosshairs.
virtual void EnableCrosshairs ()
Displays the tool's crosshairs.
virtual void DisableCrosshairs ()
Hides the tool's crosshairs.
virtual void Flash ()
Visually flashes the tool.
virtual void Strobe ()
Visually strobes the tool.
virtual bool HasRegion ()
Indicates whether the tool can define a rectangular region that can then be read for a screen capture.
virtual RECT GetRegion ()
Returns the rectangle defined by the tool.
virtual void SetPosition (const PointMap &points)
Sets the position of the tool.
virtual void RecordPosition (MeaPosition &position) const =0
Records the position of the tool.
virtual void OnMouseHook (WPARAM wParam, LPARAM lParam)
Called by the OS when the mouse pointer is moved.
Public Member Functions inherited from MeaTool
MeaTool (MeaToolMgr &mgr, const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Base class constructor.
virtual ~MeaTool ()=default
Destroys the tool.
virtual void Enable ()
Typically used by derived classes to show the tool.
virtual void Disable ()
Typically used by derived classes to hide the tool.
virtual void Update (MeaUpdateReason reason)
Used by derived classes to update the display of their data.
virtual bool IsRadioTool ()
Indicates whether the derived tool is a radio tool and cannot be enabled until any other enabled Radio tool is disabled.
virtual void SetPosition (MeaDataFieldId which, int pixels)
Sets the position of the tool.
virtual const POINT & GetPosition () const =0
Returns the tool's current position.
virtual void IncPosition (MeaDataFieldId which)
Increments the specified position field.
virtual void DecPosition (MeaDataFieldId which)
Decrements the specified position field.
virtual PCTSTR GetToolName () const =0
Returns the name of the tool.
virtual void SaveProfile (MeaProfile &profile)
Persists the state of the tool to the specified profile object.
virtual void LoadProfile (MeaProfile &profile)
Restores the state of the tool from the specified profile object.
virtual void MasterReset ()
Resets the tool to its default state.
virtual void ColorsChanged ()
Called to notify the tool that the colors in the MeaColors class have been changed.
bool IsEnabled () const
Indicates whether the tool is enabled.
Public Member Functions inherited from MeaCrossHairCallback
virtual void OnCHSelect (const CrossHairInfo *info)
Called when the left mouse button is pressed while the pointer is positioned over the crosshair.
virtual void OnCHDeselect (const CrossHairInfo *info)
Called when the left mouse button is release while the pointer is positioned over the crosshair.
virtual void OnCHMove (const CrossHairInfo *info)
Called when the user moves the mouse pointer over the crosshair while the left mouse button is pressed (i.e.
virtual void OnCHEnter (const CrossHairInfo *info)
Called when the pointer enters the crosshair window.
virtual void OnCHLeave (const CrossHairInfo *info)
Called when the pointer leaves the crosshair window.
Static Public Attributes
static constexpr PCTSTR kToolName { _T("CircleTool") }
Private Member Functions
bool Create ()
Creates the tool's graphical components.
void SetPosition ()
Sets the position of the tool's crosshairs based on the current values of m_center, and m_perimeter.
Private Attributes
CPoint m_center
Location of the center of the circle.
CPoint m_perimeter
A point on the perimeter of the circle.
CPoint * m_curPos
Points to m_center or m_perimeter depending on point the user is moving.
CPoint m_anchorCenter
Location for vertical/horizontal lock when Shift held while dragging center crosshair.
CPoint m_anchorPerimeter
Location for vertical/horizontal lock when Shift held while dragging perimeter crosshair.
MeaCrossHair m_centerCH
Crosshair for the center point.
MeaCrossHair m_perimeterCH
Crosshair for the perimeter point.
MeaCircle m_circle
Circle graphic object.
MeaLine m_line
Radial line.
MeaDataWin m_dataWinCenter
Data window tooltip for the center point.
MeaDataWin m_dataWinPerimeter
Data window tooltip for the perimeter point.
Static Private Attributes
static constexpr UINT kPerimeterId { 1 }
ID for the perimeter crosshair.
static constexpr UINT kCenterId { 2 }
ID for the center crosshair.
Additional Inherited Members
Public Types inherited from MeaRadioTool
typedef std::map< CString, POINT > PointMap
Map of points used to set the position of a tool.
Protected Attributes inherited from MeaTool
MeaToolMgr & m_mgr
Tool manager.
const MeaScreenProvider & m_screenProvider
Screen information provider.
const MeaUnitsProvider & m_unitsProvider
Units information provider.
bool m_enabled
Indicates whether the tool is enabled.
Static Protected Attributes inherited from MeaTool
static const CPoint m_defaultPos
A default position used by tools that do not have a defined position.
Detailed Description
Circle measurement tool.
This tool provides a circle and its radius. Two crosshairs are provided: one at the center of the circle (vertex) and one where the radius intersects the perimeter (point 1). Each crosshair can be arbitrarily positioned, which will result in moving and resizing the circle.
Constructor & Destructor Documentation
MeaCircleTool()
MeaCircleTool::MeaCircleTool (MeaToolMgr & mgr, const MeaScreenProvider & screenProvider, const MeaUnitsProvider & unitsProvider) explicit
Constructs a new instance of a circle measurement tool.
To use a newly constructed Circle tool, the Enable() method must be called. Enable() will call the Create() method the first time it is called if Create() has not previously been called.
Parameters
mgr [in] Tool manager parent of the Circle tool
screenProvider [in] Screen information provider
unitsProvider [in] Units information provider
References m_anchorCenter, m_anchorPerimeter, m_center, and m_perimeter.
Member Function Documentation
ColorsChanged()
void MeaCircleTool::ColorsChanged () override virtual
Called to notify the tool that the colors in the MeaColors class have been changed.
The crosshair and line colors are updated as well as the crosshair and data window opacities.
Reimplemented from MeaTool.
References MeaColors::CrossHairBack, MeaColors::CrossHairBorder, MeaColors::CrossHairHilite, MeaColors::CrossHairOpacity, MeaColors::Get(), MeaColors::GetA(), MeaColors::LineFore, m_centerCH, m_circle, m_dataWinCenter, m_dataWinPerimeter, m_line, m_perimeterCH, MeaCircle::SetColor(), MeaLine::SetColor(), MeaCrossHair::SetColors(), MeaCrossHair::SetOpacity(), and MeaDataWin::SetOpacity().
Create()
bool MeaCircleTool::Create () private
Creates the tool's graphical components.
The components include the crosshairs, lines and data windows. The Enable() method must be called to make the tool visible.
Returns
true if the window is successfully created.
References MeaDataWin::Create(), MeaCrossHair::Create(), MeaCircle::Create(), MeaLine::Create(), MeaColors::CrossHairBack, MeaColors::CrossHairBorder, MeaColors::CrossHairHilite, MeaColors::CrossHairOpacity, MeaColors::Get(), MeaColors::GetA(), kCenterId, MeaDataWin::kNoLabelId, kPerimeterId, m_centerCH, m_circle, m_dataWinCenter, m_dataWinPerimeter, m_line, m_perimeterCH, MeaTool::m_screenProvider, MeaGraphic::SetAbove(), and SetPosition().
Referenced by Enable().
DecPosition()
void MeaCircleTool::DecPosition (MeaDataFieldId which) override virtual
Decrements the specified position field.
Parameters
which Field to decrement
Reimplemented from MeaTool.
References m_center, m_perimeter, MeaX1Field, MeaXVField, MeaY1Field, MeaYVField, and SetPosition().
Disable()
void MeaCircleTool::Disable () override virtual
Hides the Circle tool.
Reimplemented from MeaTool.
References MeaTool::Disable(), DisableCrosshairs(), MeaDataWin::Hide(), MeaCircle::Hide(), MeaLine::Hide(), MeaTool::IsEnabled(), m_circle, m_dataWinCenter, m_dataWinPerimeter, and m_line.
Referenced by ~MeaCircleTool().
DisableCrosshairs()
void MeaCircleTool::DisableCrosshairs () override virtual
Hides the tool's crosshairs.
Reimplemented from MeaRadioTool.
References MeaGraphic::Hide(), m_centerCH, and m_perimeterCH.
Referenced by Disable().
Enable()
void MeaCircleTool::Enable () override virtual
Displays the Circle tool.
If the Create() method has not been previously called, it will be called by Enable.
Reimplemented from MeaTool.
References Create(), MeaTool::Enable(), EnableCrosshairs(), MeaToolMgr::EnableRegionFields(), Flash(), MeaTool::IsEnabled(), m_circle, m_line, MeaTool::m_mgr, MeaAngleField, MeaAreaField, MeaDistanceField, MeaHeightField, MeaWidthField, MeaX1Field, MeaXVField, MeaY1Field, MeaYVField, NormalUpdate, MeaToolMgr::SetStatus(), MeaGraphic::Show(), and Update().
EnableCrosshairs()
void MeaCircleTool::EnableCrosshairs () override virtual
Displays the tool's crosshairs.
If the Enable() method has not been previously called, this method has no effect.
Reimplemented from MeaRadioTool.
References MeaToolMgr::CrosshairsEnabled(), m_centerCH, MeaTool::m_mgr, m_perimeterCH, and MeaGraphic::Show().
Referenced by Enable().
Flash()
void MeaCircleTool::Flash () override virtual
Visually flashes the tool.
The tool crosshairs are cycled between a highlight color and their normal color a number of times. Flashing the tool helps the user find it on the screen.
Reimplemented from MeaRadioTool.
References MeaCrossHair::Flash(), m_centerCH, and m_perimeterCH.
Referenced by Enable().
GetLabelId()
UINT MeaCircleTool::GetLabelId () const override virtual
Returns a resource ID for the string used to label this tool on the data display.
Returns
Resource ID for the label.
Reimplemented from MeaRadioTool.
GetPosition()
const POINT & MeaCircleTool::GetPosition () const override virtual
Returns the tool's current position.
The current position is the position of the last crosshair entered or moved. The default position is the location of the center of the circle.
Returns
Current position
Implements MeaTool.
References m_curPos.
GetRegion()
RECT MeaCircleTool::GetRegion () override virtual
Returns the rectangle defined by the tool.
This rectangle can then be read for a screen capture.
Returns
The circle's bounding square.
Reimplemented from MeaRadioTool.
References MeaCircle::GetRadius(), m_center, and m_circle.
Referenced by HasRegion().
GetToolName()
PCTSTR MeaCircleTool::GetToolName () const override virtual
Returns the name of the tool.
Each tool has a unique name which is used to identify the tool in profiles and position logs.
Returns
Always "CircleTool"). The memory for the string is owned by the tool.
Implements MeaTool.
HasRegion()
bool MeaCircleTool::HasRegion () override virtual
Indicates whether the tool can define a rectangular region that can then be read for a screen capture.
For the Circle tool, the region is the circle's bounding square.
Returns
true if the tool defines a non-empty rectangular region.
Reimplemented from MeaRadioTool.
References GetRegion().
IncPosition()
void MeaCircleTool::IncPosition (MeaDataFieldId which) override virtual
Increments the specified position field.
Parameters
which Field to increment
Reimplemented from MeaTool.
References m_center, m_perimeter, MeaX1Field, MeaXVField, MeaY1Field, MeaYVField, and SetPosition().
LoadProfile()
void MeaCircleTool::LoadProfile (MeaProfile & profile) override virtual
Restores the state of the tool from the specified profile object.
Parameters
profile [in] The source for the state information. Typically an MeaFileProfile or MeaRegistryProfile object.
Reimplemented from MeaTool.
References MeaUnitsProvider::ConvertPos(), m_anchorCenter, m_anchorPerimeter, m_center, m_perimeter, MeaTool::m_unitsProvider, MeaProfile::ReadDbl(), SetPosition(), MeaUnitsProvider::UnconvertPos(), MeaFPoint::x, and MeaFPoint::y.
OnCHEnter()
void MeaCircleTool::OnCHEnter (const CrossHairInfo * info) override virtual
Called when the pointer enters one of the tool's crosshairs.
The crosshair entered is identified by the MeaCrossHairCallback::CrossHairInfo structure passed to the method.
Parameters
info [in] Crosshair information structure
Reimplemented from MeaCrossHairCallback.
References MeaCrossHairCallback::CrossHairInfo::id, kCenterId, m_dataWinCenter, m_dataWinPerimeter, NormalUpdate, MeaDataWin::Show(), and Update().
OnCHLeave()
void MeaCircleTool::OnCHLeave (const CrossHairInfo * info) override virtual
Called when the pointer leaves one of the tool's crosshairs.
The crosshair exited is identified by the MeaCrossHairCallback::CrossHairInfo structure passed to the method.
Parameters
info [in] Crosshair information structure
Reimplemented from MeaCrossHairCallback.
References MeaDataWin::Hide(), MeaCrossHairCallback::CrossHairInfo::id, kCenterId, m_dataWinCenter, and m_dataWinPerimeter.
OnCHMove()
void MeaCircleTool::OnCHMove (const CrossHairInfo * info) override virtual
Called when the user attempts to drag one of the tool's crosshairs.
The crosshair to be moved is identified by the MeaCrossHairCallback::CrossHairInfo structure passed to the method. The info parameter indicates where the crosshair is to be moved and the tool actually moves the crosshair to the new position. This allows the tool to perform vertical or horizontal locking and move the entire tool depending on which keyboard modifiers are pressed during the drag.
Parameters
info [in] Crosshair information structure
Reimplemented from MeaCrossHairCallback.
References MeaCrossHairCallback::CrossHairInfo::center, MeaCrossHairCallback::CrossHairInfo::flags, MeaCrossHairCallback::CrossHairInfo::id, MeaGeometry::IsVerticallyOriented(), kCenterId, MeaScreenProvider::LimitPosition(), m_center, m_centerCH, m_circle, m_curPos, m_line, m_perimeter, m_perimeterCH, MeaTool::m_screenProvider, NormalUpdate, MeaCrossHair::SetPosition(), MeaCircle::SetPosition(), MeaLine::SetPosition(), and Update().
RecordPosition()
void MeaCircleTool::RecordPosition (MeaPosition & position) const override virtual
Records the position of the tool.
This method is called by the position log manager to record a position.
Parameters
position [in] The tool's current position is recorded into the position log manager's position object.
Implements MeaRadioTool.
References MeaGeometry::CalcAngle(), MeaUnitsProvider::ConvertAngle(), MeaUnitsProvider::ConvertCoord(), MeaFSize::cx, MeaCircle::GetRadius(), MeaUnitsProvider::GetWidthHeight(), m_center, m_circle, m_perimeter, MeaTool::m_unitsProvider, MeaPosition::RecordAngle(), MeaPosition::RecordCircleArea(), MeaPosition::RecordDistance(), MeaPosition::RecordWH(), MeaPosition::RecordXY1(), MeaPosition::RecordXYV(), and MeaPosition::SetToolName().
SaveProfile()
void MeaCircleTool::SaveProfile (MeaProfile & profile) override virtual
Persists the state of the tool to the specified profile object.
Parameters
profile [in] The destination for the state information. Typically an MeaFileProfile or MeaRegistryProfile object.
Reimplemented from MeaTool.
References MeaUnitsProvider::ConvertPos(), m_center, m_perimeter, MeaTool::m_unitsProvider, MeaProfile::WriteStr(), MeaFPoint::x, and MeaFPoint::y.
SetPosition() [1/2]
void MeaCircleTool::SetPosition (const PointMap & points) override virtual
Sets the position of the tool.
This method is called by the position log manager to play back a tool's position that was previously recorded using the RecordPosition method.
Parameters
points [in] Map of positions for the tool's crosshairs.
Reimplemented from MeaRadioTool.
References m_center, m_perimeter, NormalUpdate, SetPosition(), and Update().
SetPosition() [2/2]
void MeaCircleTool::SetPosition (MeaDataFieldId which, int pixels) override virtual
Sets the position of the tool.
This method sets the position one location component at a time. For example, the x position of the center crosshair is specified by calling this method with the new position and specifying the MeaXVField for the which parameter.
Parameters
which [in] Position component
pixels [in] Position to set for the component, in pixels
Reimplemented from MeaTool.
References MeaScreenProvider::LimitPosition(), m_center, m_centerCH, m_circle, m_curPos, m_line, m_perimeter, m_perimeterCH, MeaTool::m_screenProvider, MeaX1Field, MeaXVField, MeaY1Field, MeaYVField, NormalUpdate, MeaCrossHair::SetPosition(), MeaCircle::SetPosition(), MeaLine::SetPosition(), and Update().
Strobe()
void MeaCircleTool::Strobe () override virtual
Visually strobes the tool.
The tool crosshairs are cycled between a highlight color and their normal color once. In addition, the data windows attached to the crosshairs are cycled between hidden and visible. Strobing the tool is done to visually confirm region capture and position recording.
Reimplemented from MeaRadioTool.
References MeaCrossHair::Flash(), MeaCrossHair::kStrobeCount, m_centerCH, m_dataWinCenter, m_dataWinPerimeter, m_perimeterCH, and MeaDataWin::Strobe().
Update()
void MeaCircleTool::Update (MeaUpdateReason reason) override virtual
Requests that the tool update the display of its position data.
Parameters
reason [in] Reason why the update has been requested
Reimplemented from MeaTool.
References MeaGeometry::CalcAngle(), MeaUnitsProvider::ConvertCoord(), MeaFSize::cx, MeaCircle::GetRadius(), MeaUnitsProvider::GetWidthHeight(), MeaTool::IsEnabled(), m_center, m_centerCH, m_circle, m_curPos, m_dataWinCenter, m_dataWinPerimeter, MeaTool::m_mgr, m_perimeter, m_perimeterCH, MeaTool::m_unitsProvider, MeaToolMgr::ShowAngle(), MeaToolMgr::ShowCircleArea(), MeaDataWin::ShowDistance(), MeaToolMgr::ShowDistance(), MeaToolMgr::ShowWH(), MeaDataWin::ShowXY(), MeaToolMgr::ShowXY1(), MeaToolMgr::ShowXYV(), MeaDataWin::Update(), MeaTool::Update(), and MeaToolMgr::UpdateScreenInfo().
Referenced by Enable(), OnCHEnter(), OnCHMove(), and SetPosition().
The documentation for this class was generated from the following files:
CircleTool.h
CircleTool.cpp
Copyright 2011 C Thing Software