Meazure: ev::State Class Reference
ev::State Class Reference
A deterministic finite state automata (DFA) consists of a set of states.
Public Types
enum Type {
Normal ,
Empty ,
Any ,
Mixed
}
Identifies the content type for the state.
typedef std::map< EVString, State * > TransMap
Represents a transition to a state based on an input symbol.
typedef TransMap::iterator TransIter
Iterator over the state transition map.
typedef TransMap::const_iterator TransIter_c
Constant iterator over the state transition map.
Public Member Functions
State (DFA &dfa, Type type, const ParseNode::NodeSet &positions)
Constructs a DFA state.
State (DFA &dfa, Type type, bool accepting=false)
Constructs a DFA state.
virtual ~State ()
Destroys a state instance.
const State * GetNextState (const EVString &elementName) const
Based on the specified input symbol (i.e.
bool IsNormal () const
Indicates if the state represents plain element content.
bool IsEmpty () const
Indicates if the state represents an empty element.
bool IsAny () const
Indicates if the state represents any element.
bool IsMixed () const
Indicates if the state represents PCDATA.
bool IsMarked () const
Indicates whether the state has been marked.
void Mark ()
Marks the state.
bool IsAccepting () const
Indicates whether this state can be a final state when matching a content model.
void SetAccepting (bool accepting=true)
Marks the state as allowing a pattern match to end.
const ParseNode::NodeSet & GetPositions () const
Returns the set of parse positions that correspond to this state.
void AddTransition (const EVString &symbol, State *nextState)
Adds a transition arc from this state to the specified next state.
void GetSymbolSet (SymbolSet &symbols) const
The set of symbols from all the transition arc from this state.
int GetId () const
Obtains the ID assigned to the state.
bool operator== (const State &rhs) const
Compares this state with the specified state.
bool operator== (const ParseNode::NodeSet &positions)
Compares the parse nodes contained in this state with the specified set of parse nodes.
Static Public Member Functions
static void ResetId ()
Resets the ID assigned to the states.
Protected Member Functions
State (const State &state)
Purposely undefined.
State & operator= (const State &state)
Purposely undefined.
bool ContainsEnd () const
Indicates if this state contains a terminal parse node.
Protected Attributes
DFA & m_dfa
Parent DFA for this state.
int m_id
ID for this state.
Type m_type
Type identifier for this state.
ParseNode::NodeSet m_positions
Parse nodes corresponding to this state.
bool m_marked
Used during DFA construction to indicate this state is marked.
bool m_accepting
Indicates if this state allows a match pattern to terminate.
TransMap m_transitions
Transitions from this state to the next states based on element names.
Static Protected Attributes
static int m_currentId = 0
ID to assign to the parse node created next.
Friends
EVOstream & operator<< (EVOstream &stream, const State *state)
Output stream operator for a state.
Detailed Description
A deterministic finite state automata (DFA) consists of a set of states.
The states are connected by directed arcs that represent input symbols. This class represents a state in a DFA.
Member Enumeration Documentation
Type
enum ev::State::Type
Identifies the content type for the state.
Enumerator
Normal
State represents plain element content.
Empty
State represents an empty element.
Any
State represents an any content model.
Mixed
State represents PCDATA.
Constructor & Destructor Documentation
State() [1/2]
State::State (DFA & dfa, Type type, const ParseNode::NodeSet & positions)
Constructs a DFA state.
Parameters
dfa [in] DFA parent for the state.
type [in] Type of state.
positions [in] Set of parse nodes that are represented by this state
State() [2/2]
State::State (DFA & dfa, Type type, bool accepting = false)
Constructs a DFA state.
Parameters
dfa [in] DFA parent for the state.
type [in] Type of state.
accepting [in] Can this state be a final state when matching a pattern.
Member Function Documentation
AddTransition()
void ev::State::AddTransition (const EVString & symbol, State * nextState) inline
Adds a transition arc from this state to the specified next state.
The transition occurs if the specified input symbol (i.e. element) is encountered.
Parameters
symbol [in] Input symbol that will cause the transition.
nextState [in] The state pointed to by the transition arc.
References m_transitions.
Referenced by ev::DFA::BuildChoiceDFA(), ev::DFA::BuildComplexDFA(), ev::DFA::BuildMixedDFA(), and ev::DFA::BuildSeqDFA().
ContainsEnd()
bool ev::State::ContainsEnd () const inline protected
Indicates if this state contains a terminal parse node.
Returns
true if this state contains a terminal parse node.
References ev::ParseNode::End, and m_positions.
GetId()
int ev::State::GetId () const inline
Obtains the ID assigned to the state.
Returns
ID assigned to the state.
References m_id.
GetNextState()
const State * State::GetNextState (const EVString & elementName) const
Based on the specified input symbol (i.e.
element name), a transition arc is selected and the state pointed to by that arc is returned.
Parameters
elementName [in] Input symbol that selects the transition arc to the next state.
Returns
The next state based on following the transition arc selected by the element name.
References ev::Validator::GetAnyElements(), ev::DFA::GetValidator(), IsAny(), IsEmpty(), m_dfa, and m_transitions.
Referenced by ev::Validator::StartElement().
GetPositions()
const ParseNode::NodeSet & ev::State::GetPositions () const inline
Returns the set of parse positions that correspond to this state.
Returns
The set of parse nodes that correspond to this state.
References m_positions.
Referenced by ev::DFA::BuildComplexDFA().
GetSymbolSet()
void ev::State::GetSymbolSet (SymbolSet & symbols) const inline
The set of symbols from all the transition arc from this state.
Parameters
symbols [out] Set of symbols (i.e. element names) comprising the input set on the transition arcs.
References m_transitions.
Referenced by ev::Validator::GetAllowableElements().
IsAccepting()
bool ev::State::IsAccepting () const inline
Indicates whether this state can be a final state when matching a content model.
Returns
true indicates that a pattern can end in this state.
References m_accepting.
Referenced by ev::Validator::EndElement().
IsAny()
bool ev::State::IsAny () const inline
Indicates if the state represents any element.
Returns
true if the state represents any element.
References Any, and m_type.
Referenced by ev::Validator::CharacterData(), ev::Validator::GetAllowableElements(), and GetNextState().
IsEmpty()
bool ev::State::IsEmpty () const inline
Indicates if the state represents an empty element.
Returns
true if the state represents an empty element.
References Empty, and m_type.
Referenced by GetNextState().
IsMarked()
bool ev::State::IsMarked () const inline
Indicates whether the state has been marked.
States are marked during the building of a complex DFA to assist the construction process. Marks are not used after the DFA has been constructed.
Returns
true if the state has been marked.
References m_marked.
IsMixed()
bool ev::State::IsMixed () const inline
Indicates if the state represents PCDATA.
Returns
true if the state represents PCDATA.
References m_type, and Mixed.
Referenced by ev::Validator::CharacterData().
IsNormal()
bool ev::State::IsNormal () const inline
Indicates if the state represents plain element content.
Returns
true if the state represents plain element content.
References m_type, and Normal.
Mark()
void ev::State::Mark () inline
Marks the state.
States are marked during the building of a complex DFA to assist the construction process. Marks are not used after the DFA has been constructed.
References m_marked.
Referenced by ev::DFA::BuildComplexDFA().
operator==() [1/2]
bool ev::State::operator== (const ParseNode::NodeSet & positions) inline
Compares the parse nodes contained in this state with the specified set of parse nodes.
Parameters
positions [in] Set of parse nodes to compare.
Returns
true if the specified parse nodes are equal to the parse nodes contained in this state.
References ev::ParseNode::EqualOp(), and m_positions.
operator==() [2/2]
bool State::operator== (const State & rhs) const
Compares this state with the specified state.
Parameters
rhs [in] State to compare against this.
Returns
true if the specified state equals this state.
References m_positions, m_transitions, and m_type.
SetAccepting()
void ev::State::SetAccepting (bool accepting = true) inline
Marks the state as allowing a pattern match to end.
Parameters
accepting [in] Sets whether this state allows a pattern match to end.
References m_accepting.
Referenced by ev::DFA::BuildSeqDFA().
Friends And Related Function Documentation
operator<<
EVOstream & operator<< (EVOstream & stream, const State * state) friend
Output stream operator for a state.
Used to dump the state object to the specified output stream for debugging purposes.
Parameters
stream [in] Output stream.
state [in] State object to output.
Returns
Output stream.
The documentation for this class was generated from the following file:
exval.cpp
Copyright 2011 C Thing Software