Meazure: MeaPosition Class Reference
MeaPosition Class Reference
Represents a tool position.
#include <Position.h>
Public Types
typedef std::map< CString, MeaFPoint > PointMap
Maps a point name to the coordinates of the point.
Public Member Functions
MeaPosition (MeaPositionDesktopRef desktopInfoRef)
Constructs a position object that references the specified desktop information object.
MeaPosition (MeaPositionDesktopRef desktopInfoRef, const CString &toolName, const CString &timestamp)
Constructs a position object that represents the position of the specified tool at the specified time.
MeaPosition (const MeaPosition &position)
Copy constructor.
MeaPosition & operator= (const MeaPosition &position)
Performs assignment of the specified position object to this position object.
void SetToolName (const CString &toolName)
Sets the name of the tool that recorded this position.
CString GetToolName () const
Returns the name of the tool that recorded this position.
void SetDesc (const CString &desc)
Places a description on the position.
CString GetDesc () const
Returns the description of the position.
CString GetTimeStamp () const
Returns the timestamp indicating when this position was recorded.
MeaPositionDesktopRef GetDesktopRef () const
Returns the identifier of the desktop information object referenced by this position.
const PointMap & GetPoints () const
Returns the points representing the position.
double GetWidth () const
Returns the recorded width.
double GetHeight () const
Returns the recorded height.
double GetDistance () const
Returns the recorded distance.
double GetArea () const
Returns the recorded area.
double GetAngle () const
Returns the recorded angle.
void AddPoint (PCTSTR name, const MeaFPoint &pt)
Adds the specified point to the position using the specified name to identify the point.
void RecordXY1 (const MeaFPoint &point)
Records the specified point as an x1, y1 point.
void RecordXY2 (const MeaFPoint &point)
Records the specified point as an x2, y2 point.
void RecordXYV (const MeaFPoint &point)
Records the specified point as an xv, yv point.
void RecordWH (const MeaFSize &size)
Records the specified width and height.
void RecordDistance (const MeaFSize &size)
Records a distance.
void RecordDistance (double dist)
Records the specified distance.
void RecordAngle (double angle)
Records the angle.
void RecordRectArea (const MeaFSize &size)
Records a rectangular area.
void RecordCircleArea (double radius)
Records a circular area.
void Load (const MeaXMLNode *positionNode)
Loads the position elements of the log file.
void Save (MeaXMLWriter &writer) const
Saves the position in the position log file.
bool operator== (const MeaPosition &position) const
Compares the specified position information object with this to determine equality.
bool operator!= (const MeaPosition &position) const
Compares the specified position information object with this to determine inequality.
Private Attributes
UINT m_fieldMask
Data fields defined for this position. Different tools provide different amounts of data.
PointMap m_points
Location of the current tool, in the units in effect when the position was recorded.
double m_width
Width of rectangle or bounding box, in the units in effect when the position was recorded.
double m_height
Height of rectangle or bounding box, in the units in effect when the position was recorded.
double m_distance
Length of line or diagonal, in the units in effect when the position was recorded.
double m_area
Area of rectangle or bounding box, in the units in effect when the position was recorded.
double m_angle
Angle of diagonal, line, or angle tool, in the units in effect when the position was recorded.
MeaPositionDesktopRef m_desktopRef
Reference to the desktop information object for this position.
CString m_toolName
Name of measurement tool whose position is represented by this object.
CString m_timestamp
Date and time the position was recorded.
CString m_desc
Description for position.
Detailed Description
Represents a tool position.
A position object references the desktop information that provides its environment. Since desktop environments do not tend to change often, many position objects typically reference the same desktop information object. The position object is ultimately persisted to the position log file along with the desktop information object.
A position consists of one or more (x,y) points. The number of points required for a position depends on the measurement tool whose position is being recorded. For example, the Point tool requires only one point to completely describe its position, whereas the Line tool requires two points, one per endpoint of the line. Each point is named by the tool (e.g. "v", "1", "2").
Constructor & Destructor Documentation
MeaPosition() [1/3]
MeaPosition::MeaPosition (MeaPositionDesktopRef desktopInfoRef)
Constructs a position object that references the specified desktop information object.
Parameters
desktopInfoRef [in] Reference to the desktop information object for this position
MeaPosition() [2/3]
MeaPosition::MeaPosition (MeaPositionDesktopRef desktopInfoRef, const CString & toolName, const CString & timestamp)
Constructs a position object that represents the position of the specified tool at the specified time.
Parameters
desktopInfoRef [in] Reference to the desktop information object for this position
toolName [in] Name of the measurement tool whose position is represented by this position object.
timestamp [in] Identifies when this position was recorded.
MeaPosition() [3/3]
MeaPosition::MeaPosition (const MeaPosition & position)
Copy constructor.
Parameters
position [in] Position object to be copied into a new position object.
Member Function Documentation
AddPoint()
void MeaPosition::AddPoint (PCTSTR name, const MeaFPoint & pt) inline
Adds the specified point to the position using the specified name to identify the point.
Parameters
name [in] Name to assign the point.
pt [in] Point to be stored in the position.
References m_points.
Referenced by Load().
GetAngle()
double MeaPosition::GetAngle () const inline
Returns the recorded angle.
Returns
Recorded angle.
References m_angle.
GetArea()
double MeaPosition::GetArea () const inline
Returns the recorded area.
Returns
Recorded area
References m_area.
GetDesc()
CString MeaPosition::GetDesc () const inline
Returns the description of the position.
Returns
Description of the position or the empty string if there is no description.
References m_desc.
Referenced by MeaPositionLogDlg::OnKillfocusPositionDesc(), and MeaPositionLogDlg::UpdatePositionInfo().
GetDesktopRef()
MeaPositionDesktopRef MeaPosition::GetDesktopRef () const inline
Returns the identifier of the desktop information object referenced by this position.
Returns
Desktop information identifier referenced by this position.
References m_desktopRef.
Referenced by MeaPositionLogMgr::ShowPosition().
GetDistance()
double MeaPosition::GetDistance () const inline
Returns the recorded distance.
Returns
Recorded distance
References m_distance.
GetHeight()
double MeaPosition::GetHeight () const inline
Returns the recorded height.
Returns
Recorded height
References m_height.
GetPoints()
const PointMap & MeaPosition::GetPoints () const inline
Returns the points representing the position.
Returns
Points representing the position as a map of the name of the point (e.g. "1") and its coordinates. The point names are meaningful to the tool that recorded the position.
References m_points.
Referenced by MeaPositionLogMgr::ShowPosition().
GetTimeStamp()
CString MeaPosition::GetTimeStamp () const inline
Returns the timestamp indicating when this position was recorded.
Returns
Timestamp for the position in ISO 8601 format.
References m_timestamp.
Referenced by MeaPositionLogDlg::UpdatePositionInfo().
GetToolName()
CString MeaPosition::GetToolName () const inline
Returns the name of the tool that recorded this position.
Returns
Name of the tool that recorded this position.
References m_toolName.
Referenced by MeaPositionLogMgr::ShowPosition().
GetWidth()
double MeaPosition::GetWidth () const inline
Returns the recorded width.
Returns
Recorded width
References m_width.
Load()
void MeaPosition::Load (const MeaXMLNode * positionNode)
Loads the position elements of the log file.
Parameters
positionNode [in] Position node in the DOM.
References AddPoint(), MeaXMLNode::AtEnd(), MeaXMLNode::Element, MeaXMLNode::GetAttributes(), MeaXMLNode::GetChildData(), MeaXMLNode::GetChildIter(), MeaXMLNode::GetData(), MeaXMLNode::GetType(), MeaXMLAttributes::GetValueDbl(), MeaXMLAttributes::GetValueStr(), m_angle, m_area, m_distance, m_fieldMask, m_height, m_width, MeaAngleField, MeaAreaField, MeaDistanceField, MeaHeightField, MeaWidthField, SetDesc(), MeaFPoint::x, and MeaFPoint::y.
Referenced by MeaPositionLogMgr::ProcessPositionNode().
operator!=()
bool MeaPosition::operator!= (const MeaPosition & position) const inline
Compares the specified position information object with this to determine inequality.
Parameters
position [in] Position information object to compare with this.
Returns
true if the specified object and this are not equal.
operator=()
MeaPosition & MeaPosition::operator= (const MeaPosition & position)
Performs assignment of the specified position object to this position object.
Parameters
position [in] Object to be copied to this.
Returns
This object.
References m_angle, m_area, m_desc, m_desktopRef, m_distance, m_fieldMask, m_height, m_points, m_timestamp, m_toolName, and m_width.
operator==()
bool MeaPosition::operator== (const MeaPosition & position) const inline
Compares the specified position information object with this to determine equality.
Parameters
position [in] Position information object to compare with this.
Returns
true if the specified object and this are equal.
References MeaNumericUtils::IsEqualF(), m_angle, m_area, m_desc, m_desktopRef, m_distance, m_height, m_points, m_timestamp, m_toolName, and m_width.
RecordAngle()
void MeaPosition::RecordAngle (double angle)
Records the angle.
Parameters
angle [in] Angle to record, in the current angular units.
References m_angle, m_fieldMask, and MeaAngleField.
Referenced by MeaAngleTool::RecordPosition(), MeaCircleTool::RecordPosition(), MeaLineTool::RecordPosition(), MeaRectTool::RecordPosition(), and MeaWindowTool::RecordPosition().
RecordCircleArea()
void MeaPosition::RecordCircleArea (double radius)
Records a circular area.
The area is calculated using the formula:
Parameters
radius [in] Radius used to calculate the area, in the current units.
References m_area, m_fieldMask, and MeaAreaField.
Referenced by MeaCircleTool::RecordPosition().
RecordDistance() [1/2]
void MeaPosition::RecordDistance (const MeaFSize & size)
Records a distance.
The distance is calculated by the method using the formula:
Parameters
size [in] Width and height used to calculate the distance, in the current units.
References MeaGeometry::CalcLength(), MeaFSize::cx, MeaFSize::cy, m_distance, m_fieldMask, and MeaDistanceField.
Referenced by MeaCircleTool::RecordPosition(), MeaLineTool::RecordPosition(), MeaRectTool::RecordPosition(), and MeaWindowTool::RecordPosition().
RecordDistance() [2/2]
void MeaPosition::RecordDistance (double dist)
Records the specified distance.
Parameters
dist [in] Distance to record, in the current units.
References m_distance, m_fieldMask, and MeaDistanceField.
RecordRectArea()
void MeaPosition::RecordRectArea (const MeaFSize & size)
Records a rectangular area.
The area is calculated by the formula:
Parameters
size [in] WWidth and height used to calculate the area, in the current units.
References MeaFSize::cx, MeaFSize::cy, m_area, m_fieldMask, and MeaAreaField.
Referenced by MeaLineTool::RecordPosition(), MeaRectTool::RecordPosition(), and MeaWindowTool::RecordPosition().
RecordWH()
void MeaPosition::RecordWH (const MeaFSize & size)
Records the specified width and height.
Parameters
size [in] Width and height to record, in the current units.
References MeaFSize::cx, MeaFSize::cy, m_fieldMask, m_height, m_width, MeaHeightField, and MeaWidthField.
Referenced by MeaCircleTool::RecordPosition(), MeaLineTool::RecordPosition(), MeaRectTool::RecordPosition(), and MeaWindowTool::RecordPosition().
RecordXY1()
void MeaPosition::RecordXY1 (const MeaFPoint & point)
Records the specified point as an x1, y1 point.
Parameters
point [in] Point to record, in the current units.
References m_fieldMask, m_points, MeaX1Field, and MeaY1Field.
Referenced by MeaAngleTool::RecordPosition(), MeaCircleTool::RecordPosition(), MeaCursorTool::RecordPosition(), MeaLineTool::RecordPosition(), MeaPointTool::RecordPosition(), MeaRectTool::RecordPosition(), and MeaWindowTool::RecordPosition().
RecordXY2()
void MeaPosition::RecordXY2 (const MeaFPoint & point)
Records the specified point as an x2, y2 point.
Parameters
point [in] Point to record, in the current units.
References m_fieldMask, m_points, MeaX2Field, and MeaY2Field.
Referenced by MeaAngleTool::RecordPosition(), MeaLineTool::RecordPosition(), MeaRectTool::RecordPosition(), and MeaWindowTool::RecordPosition().
RecordXYV()
void MeaPosition::RecordXYV (const MeaFPoint & point)
Records the specified point as an xv, yv point.
Parameters
point [in] Point to record, in the current units.
References m_fieldMask, m_points, MeaXVField, and MeaYVField.
Referenced by MeaAngleTool::RecordPosition(), and MeaCircleTool::RecordPosition().
Save()
void MeaPosition::Save (MeaXMLWriter & writer) const
Saves the position in the position log file.
Parameters
writer [in] Provides ability to write a position to the log.
References MeaXMLWriter::AddAttribute(), MeaXMLWriter::Characters(), MeaXMLWriter::EndElement(), m_angle, m_area, m_desc, m_desktopRef, m_distance, m_fieldMask, m_height, m_points, m_timestamp, m_toolName, m_width, MeaAngleField, MeaAreaField, MeaDistanceField, MeaHeightField, MeaWidthField, and MeaXMLWriter::StartElement().
SetDesc()
void MeaPosition::SetDesc (const CString & desc) inline
Places a description on the position.
Parameters
desc [in] Descriptive text for the position.
References m_desc.
Referenced by Load(), and MeaPositionLogDlg::OnKillfocusPositionDesc().
SetToolName()
void MeaPosition::SetToolName (const CString & toolName) inline
Sets the name of the tool that recorded this position.
Parameters
toolName Name of the tool that recorded this position
References m_toolName.
Referenced by MeaAngleTool::RecordPosition(), MeaCircleTool::RecordPosition(), MeaCursorTool::RecordPosition(), MeaLineTool::RecordPosition(), MeaPointTool::RecordPosition(), MeaRectTool::RecordPosition(), and MeaWindowTool::RecordPosition().
The documentation for this class was generated from the following files:
Position.h
Position.cpp
Copyright 2011 C Thing Software