Meazure: MeaPositionLogObserver Class Reference
MeaPositionLogObserver Class Reference abstract
Interface for objects that need to be informed about changes to the position log.
#include <PositionLogObserver.h>
Public Member Functions
MeaPositionLogObserver ()
Interface does nothing in a constructor.
virtual ~MeaPositionLogObserver ()
Interface does nothing in a destructor.
virtual void LogLoaded ()=0
Called when a position log file is loaded.
virtual void LogSaved ()=0
Called when a position log file is saved.
virtual void PositionAdded (int posIndex)=0
Called when a new position is recorded.
virtual void PositionReplaced (int posIndex)=0
Called when an existing position is replaced with a new position.
virtual void PositionDeleted (int posIndex)=0
Called when a position is deleted.
virtual void PositionsDeleted ()=0
Called when all recorded positions have been deleted.
Detailed Description
Interface for objects that need to be informed about changes to the position log.
Classes that wish to be informed about changes to the position log file inherit from this interface as a mix-in. The class then implements the methods declared by this interface.
Member Function Documentation
LogLoaded()
virtual void MeaPositionLogObserver::LogLoaded () pure virtual
Called when a position log file is loaded.
Implemented in MeaPositionLogDlg.
Referenced by MeaPositionLogMgr::Load().
LogSaved()
virtual void MeaPositionLogObserver::LogSaved () pure virtual
Called when a position log file is saved.
Implemented in MeaPositionLogDlg.
Referenced by MeaPositionLogMgr::Save().
PositionAdded()
virtual void MeaPositionLogObserver::PositionAdded (int posIndex) pure virtual
Called when a new position is recorded.
Parameters
posIndex [in] Index of the new position.
Implemented in MeaPositionLogDlg.
Referenced by MeaPositionLogMgr::RecordPosition().
PositionDeleted()
virtual void MeaPositionLogObserver::PositionDeleted (int posIndex) pure virtual
Called when a position is deleted.
Parameters
posIndex [in] Index of the deleted position.
Implemented in MeaPositionLogDlg.
Referenced by MeaPositionLogMgr::DeletePosition().
PositionReplaced()
virtual void MeaPositionLogObserver::PositionReplaced (int posIndex) pure virtual
Called when an existing position is replaced with a new position.
Parameters
posIndex [in] Index of the replaced position.
Implemented in MeaPositionLogDlg.
Referenced by MeaPositionLogMgr::ReplacePosition().
PositionsDeleted()
virtual void MeaPositionLogObserver::PositionsDeleted () pure virtual
Called when all recorded positions have been deleted.
Implemented in MeaPositionLogDlg.
Referenced by MeaPositionLogMgr::DeletePositions().
The documentation for this class was generated from the following file:
PositionLogObserver.h
Copyright 2011 C Thing Software