Meazure: MeaGridDialog Class Reference
MeaGridDialog Class Reference
Grid tool configuration dialog.
#include <GridTool.h>
Public Member Functions
MeaGridDialog (MeaGridTool *tool)
Constructs a new instance of the Grid tool dialog.
virtual ~MeaGridDialog ()
Destroy the Grid tool dialog.
virtual BOOL OnInitDialog ()
Called immediately before the dialog is displayed in response to a DoModal call.
Protected Member Functions
afx_msg void OnGridLink ()
Called when the user clicks the checkbox that controls whether the vertical and horizontal grid spacings are set independently.
afx_msg void OnHSpaceChange ()
Called when the value in the horizontal grid spacing text field is changed.
afx_msg void OnVSpaceChange ()
Called when the value in the vertical grid spacing text field is changed.
virtual void DoDataExchange (CDataExchange *pDX)
Called by Windows to perform Dynamic Data Exchange between the dialog's controls and their corresponding member variables.
virtual void OnOK ()
Called when the dialog's OK button is pressed.
virtual void OnCancel ()
Called when the dialog's Cancel button is pressed.
Private Member Functions
void UpdateDisplay ()
Updates the dialog's controls to reflect the member variable values.
bool GetFieldValue (UINT fieldId, long &value) const
Reads the content of the specified text field and attempts to convert it to a numerical value.
Private Attributes
MeaGridTool * m_tool
Grid tool being configured by the dialog.
MeaNumberField m_hSpaceField
Horizontal grid spacing text field.
MeaNumberField m_vSpaceField
Vertical grid spacing text field.
CSpinButtonCtrl * m_hSpaceSpin
Horizontal spacing increment / decrement control.
CSpinButtonCtrl * m_vSpaceSpin
Vertical spacing increment / decrement spacing.
bool m_origLinked
State of the lock checkbox before the dialog was displayed.
bool m_linked
Current state of the lock checkbox.
SIZE m_origSpacing
Grid spacing before the dialog was displayed.
SIZE m_spacing
Current grid spacing.
Detailed Description
Grid tool configuration dialog.
This dialog allows the user to set the grid spacing. The grid spacing can be set independently in the vertical and horizontal directions.
Constructor & Destructor Documentation
MeaGridDialog()
MeaGridDialog::MeaGridDialog (MeaGridTool * tool) explicit
Constructs a new instance of the Grid tool dialog.
To display the dialog call its DoModal method.
Parameters
tool [in] Grid tool being configured by the dialog.
Member Function Documentation
DoDataExchange()
void MeaGridDialog::DoDataExchange (CDataExchange * pDX) protected virtual
Called by Windows to perform Dynamic Data Exchange between the dialog's controls and their corresponding member variables.
Parameters
pDX [in] Object containing the dialog data exchange context.
References m_linked, and m_spacing.
GetFieldValue()
bool MeaGridDialog::GetFieldValue (UINT fieldId, long & value) const private
Reads the content of the specified text field and attempts to convert it to a numerical value.
In order to succeed, the contents must represent a number and the number must be in the range:
MeaGridTool::kDefMinSpacing value MeaGridTool::kDefMaxSpacing
Parameters
fieldId [in] Species the text field to read
value [out] Field contents converted to a numerical value
Returns
true if the text field's contents were successfully converted and the value was within the allowable range. The value parameter is changed only if the method returns true.
References MeaGridTool::kDefMaxSpacing, and MeaGridTool::kDefMinSpacing.
Referenced by OnHSpaceChange(), OnOK(), and OnVSpaceChange().
OnCancel()
void MeaGridDialog::OnCancel () protected virtual
Called when the dialog's Cancel button is pressed.
The method restores the original spacing values.
References m_linked, m_origLinked, m_origSpacing, m_spacing, and UpdateDisplay().
OnInitDialog()
BOOL MeaGridDialog::OnInitDialog () virtual
Called immediately before the dialog is displayed in response to a DoModal call.
Returns
TRUE to indicate Windows should set the input focus.
References MeaNumberField::IntValues, MeaGridTool::kDefMaxSpacing, MeaGridTool::kDefMinSpacing, m_hSpaceField, m_hSpaceSpin, m_vSpaceField, m_vSpaceSpin, MeaNumberField::PosValues, MeaNumberField::SetValueType(), and UpdateDisplay().
OnOK()
void MeaGridDialog::OnOK () protected virtual
Called when the dialog's OK button is pressed.
The method verifies that the spacing fields contain valid numerical values. If not, a dialog is displayed, the erroneous field is selected and the dialog is not dismissed.
References GetFieldValue(), m_hSpaceField, and m_vSpaceField.
The documentation for this class was generated from the following files:
GridTool.h
GridTool.cpp
Copyright 2011 C Thing Software