Meazure: MeaNumberField Class Reference
MeaNumberField Class Reference
Provides a text field control that allows only numeric entries.
#include <NumberField.h>
Public Types
enum ValueType {
AllValues = 0 ,
IntValues = 1 ,
PosValues = 2
}
Configurations for the text field.
Public Member Functions
MeaNumberField ()
Constructs a field object.
virtual ~MeaNumberField ()
Destroys a field object.
bool Create (DWORD style, const POINT &topLeft, int numChars, CWnd *parentWnd, UINT id=0xFFFF)
Creates the window for the field.
void SetValueType (DWORD valueType)
Configures the field with the type of value to accept.
void SetValue (int value)
Displays an integer value in the field.
void SetValue (double value)
Displays a double precision value in the field.
bool GetValue (int &value) const
Obtains the value contained in the text field as an integer.
bool GetValue (double &value) const
Obtains the value contained in the text field as a double precision value.
bool IsTextSelected () const
Indicates if the value in the field is selected.
virtual BOOL PreTranslateMessage (MSG *msg)
Handles the RETURN key, UP and DOWN arrow keys.
Protected Member Functions
afx_msg void OnChar (UINT nChar, UINT nRepCnt, UINT nFlags)
Filters out characters not used in a number.
afx_msg LRESULT OnPaste (WPARAM, LPARAM)
Ensures only a valid number is pasted.
afx_msg void OnKillFocus (CWnd *win)
Called when the field loses keyboard focus.
bool IsSign (TCHAR ch) const
Indicates if the specified character is an acceptable sign character.
bool IsPoint (TCHAR ch) const
Indicates if the specified character is an acceptable decimal point.
Private Member Functions
bool IsValid (LPCTSTR str, int len) const
Tests whether the specified string can be placed in the text field.
bool IntOnly () const
Indicates whether the field has been configured to only accept integer values.
bool PosOnly () const
Indicates whether the field has been configured to only accept positive integer values.
Private Attributes
DWORD m_valueType
Configuration for the field as defined by MeaNumberField::ValueType.
Static Private Attributes
static int m_edgeHeight = -1
Height of the field's 3D sunken edge.
Detailed Description
Provides a text field control that allows only numeric entries.
The text field can be configured to allow any floating point value, only integer values, or only positive integer values.
Member Enumeration Documentation
ValueType
enum MeaNumberField::ValueType
Configurations for the text field.
Enumerator
AllValues
Allows entry of any floating point number.
IntValues
Allows entry of positive or negative integers.
PosValues
Allows entry of positive integers.
Constructor & Destructor Documentation
MeaNumberField()
MeaNumberField::MeaNumberField ()
Constructs a field object.
Before the field can be used, the Create method must be called.
Member Function Documentation
Create()
bool MeaNumberField::Create (DWORD style, const POINT & topLeft, int numChars, CWnd * parentWnd, UINT id = 0xFFFF)
Creates the window for the field.
To make the field visible, add the WS_VISIBLE style or call ShowWindow.
Parameters
style [in] Field styles as defined for CEdit.
topLeft [in] Position of the top, left corner for the field, in pixels.
numChars [in] Number of visible characters. For proportional fonts the number of characters actually visible may vary from the specified value.
parentWnd [in] Parent window for the field.
id [in] ID for the field.
Returns
true if the field was created successfully.
References m_edgeHeight, and MeaLayout::SetWindowSize().
Referenced by MeaMagnifier::Create(), and MeaDataDisplay::DataItem::CreateField().
GetValue() [1/2]
bool MeaNumberField::GetValue (double & value) const inline
Obtains the value contained in the text field as a double precision value.
Parameters
value [out] Value contained in the field converted to a double.
Returns
true if the field is not empty.
GetValue() [2/2]
bool MeaNumberField::GetValue (int & value) const inline
Obtains the value contained in the text field as an integer.
Parameters
value [out] Value contained in the field converted to an integer.
Returns
true if the field is not empty.
Referenced by MeaPrecisionPrefs::GetValue(), and MeaCustomUnitsPrefs::Validate().
IntOnly()
bool MeaNumberField::IntOnly () const inline private
Indicates whether the field has been configured to only accept integer values.
Returns
true if the field has been configured to only accept integers.
References IntValues, and m_valueType.
Referenced by IsPoint().
IsPoint()
bool MeaNumberField::IsPoint (TCHAR ch) const inline protected
Indicates if the specified character is an acceptable decimal point.
An acceptable decimal point character is a '.' when the field is configured to accept floating point values.
Parameters
ch [in] Character to test.
Returns
true if the specified character represents an acceptable decimal point character.
References IntOnly().
Referenced by IsValid().
IsSign()
bool MeaNumberField::IsSign (TCHAR ch) const inline protected
Indicates if the specified character is an acceptable sign character.
Acceptable sign characters are '+' and '-' for a float and integer configured field, and only '+' for a positive integer configured field.
Parameters
ch [in] Character to test.
Returns
true if the specified character represents an acceptable sign character.
References PosOnly().
Referenced by IsValid().
IsTextSelected()
bool MeaNumberField::IsTextSelected () const inline
Indicates if the value in the field is selected.
Returns
true if the value in the field is selected.
Referenced by CChildView::OnUpdateEditClear(), CChildView::OnUpdateEditCopy(), and CChildView::OnUpdateEditCut().
IsValid()
bool MeaNumberField::IsValid (LPCTSTR str, int len) const private
Tests whether the specified string can be placed in the text field.
Parameters
str [in] String to test.
len [in] Length of string.
Returns
true if the specified string can be placed in the field.
References IsPoint(), and IsSign().
Referenced by OnChar(), and OnPaste().
OnChar()
void MeaNumberField::OnChar (UINT nChar, UINT nRepCnt, UINT nFlags) protected
Filters out characters not used in a number.
Parameters
nChar [in] Character code.
nRepCnt [in] Character repeat count.
nFlags [in] Low level key codes.
References IsValid().
OnKillFocus()
void MeaNumberField::OnKillFocus (CWnd * win) protected
Called when the field loses keyboard focus.
The parent window is sent a MeaFieldFocusMsg message so that it can take actions such as reading the value in the field.
Parameters
win [in] Next window to receive focus.
References MeaFieldFocusMsg.
OnPaste()
LRESULT MeaNumberField::OnPaste (WPARAM , LPARAM) protected
Ensures only a valid number is pasted.
Returns
Always returns TRUE.
References IsValid().
PosOnly()
bool MeaNumberField::PosOnly () const inline private
Indicates whether the field has been configured to only accept positive integer values.
Returns
true if the field has been configured to only accept positive integers.
References m_valueType, and PosValues.
Referenced by IsSign().
PreTranslateMessage()
BOOL MeaNumberField::PreTranslateMessage (MSG * msg) virtual
Handles the RETURN key, UP and DOWN arrow keys.
Parameters
msg [in] Message structure.
Returns
TRUE if UP/DOWN and FALSE otherwise.
References MeaFieldArrowMsg, and MeaFieldEnterMsg.
SetValue() [1/2]
void MeaNumberField::SetValue (double value) inline
Displays a double precision value in the field.
Parameters
value [in] Double value to display in the field.
SetValue() [2/2]
void MeaNumberField::SetValue (int value) inline
Displays an integer value in the field.
Parameters
value [in] Integer value to display in the field.
Referenced by MeaPrecisionPrefs::GetValue().
SetValueType()
void MeaNumberField::SetValueType (DWORD valueType) inline
Configures the field with the type of value to accept.
Parameters
valueType [in] One of the type defined by MeaNumberField::ValueType.
References m_valueType.
Referenced by MeaCalibrationPrefs::OnInitDialog(), MeaCustomUnitsPrefs::OnInitDialog(), and MeaGridDialog::OnInitDialog().
The documentation for this class was generated from the following files:
NumberField.h
NumberField.cpp
Copyright 2011 C Thing Software