Meazure: MeaCrossHairCallback Class Reference
MeaCrossHairCallback Class Reference
Crosshair activity callback mixin class.
#include <CrossHair.h>
Classes
struct CHInfo
Callback information structure.
Public Member Functions
MeaCrossHairCallback ()
Constructs a callback object.
virtual ~MeaCrossHairCallback ()
Destroys a callback object.
virtual void OnCHSelect (const CHInfo *info)
Called when the left mouse button is pressed while the pointer is positioned over the crosshair.
virtual void OnCHDeselect (const CHInfo *info)
Called when the left mouse button is release while the pointer is positioned over the crosshair.
virtual void OnCHMove (const CHInfo *info)
Called when the user moves the mouse pointer over the crosshair while the left mouse button is pressed (i.e.
virtual void OnCHEnter (const CHInfo *info)
Called when the pointer enters the crosshair window.
virtual void OnCHLeave (const CHInfo *info)
Called when the pointer leaves the crosshair window.
Detailed Description
Crosshair activity callback mixin class.
A class wishing to receive notification of crosshair events (e.g. movement), can inherit from this class and override the On* methods of interest.
Member Function Documentation
OnCHDeselect()
void MeaCrossHairCallback::OnCHDeselect (const CHInfo * info) virtual
Called when the left mouse button is release while the pointer is positioned over the crosshair.
Parameters
info [in] Crosshair information structure
Referenced by MeaCrossHair::OnLButtonUp().
OnCHEnter()
void MeaCrossHairCallback::OnCHEnter (const CHInfo * info) virtual
Called when the pointer enters the crosshair window.
Parameters
info [in] Crosshair information structure
Reimplemented in MeaAngleTool, MeaCircleTool, MeaLineTool, MeaPointTool, and MeaRectTool.
Referenced by MeaCrossHair::OnMouseMove().
OnCHLeave()
void MeaCrossHairCallback::OnCHLeave (const CHInfo * info) virtual
Called when the pointer leaves the crosshair window.
Parameters
info [in] Crosshair information structure
Reimplemented in MeaAngleTool, MeaCircleTool, MeaLineTool, MeaPointTool, and MeaRectTool.
Referenced by MeaCrossHair::OnMouseLeave().
OnCHMove()
void MeaCrossHairCallback::OnCHMove (const CHInfo * info) virtual
Called when the user moves the mouse pointer over the crosshair while the left mouse button is pressed (i.e.
a drag operation). It is the responsibility of the callback method to actually moved the crosshair to its new position as specified in the callback information structure.
Parameters
info [in] Crosshair information structure
Reimplemented in MeaAngleTool, MeaCircleTool, MeaLineTool, MeaPointTool, and MeaRectTool.
Referenced by MeaCrossHair::OnMouseMove().
OnCHSelect()
void MeaCrossHairCallback::OnCHSelect (const CHInfo * info) virtual
Called when the left mouse button is pressed while the pointer is positioned over the crosshair.
Parameters
info [in] Crosshair information structure
Referenced by MeaCrossHair::OnLButtonDown().
The documentation for this class was generated from the following files:
CrossHair.h
CrossHair.cpp
Copyright 2011 C Thing Software