Meazure: MeaPositionLogMgr::DesktopInfo Class Reference
MeaPositionLogMgr::DesktopInfo Class Reference
Represents all information of interest about the system at the time a position is recorded.
#include <PositionLogMgr.h>
Public Member Functions
DesktopInfo ()
Constructs a desktop information object.
DesktopInfo (LPCTSTR guidStr)
Constructs a desktop information object with the specified unique ID.
DesktopInfo (const DesktopInfo &desktop)
Constructs a desktop information object as a copy of the specified object.
~DesktopInfo ()
Destroys a desktop information object.
DesktopInfo & operator= (const DesktopInfo &desktop)
Assigns the specified desktop information object to this object.
MeaLinearUnits * GetLinearUnits ()
Returns the linear units in effect when this object was created.
const MeaLinearUnits * GetLinearUnits () const
Returns the linear units in effect when this object was created.
MeaAngularUnits * GetAngularUnits ()
Returns the angular units in effect when this object was created.
const MeaAngularUnits * GetAngularUnits () const
Returns the angular units in effect when this object was created.
bool GetInvertY () const
Indicates whether the y-axis was inverted when this object was created.
const FPOINT & GetOrigin () const
Returns the location of the origin when this object was created.
const MeaGUID & GetId () const
Returns the unique ID for this object.
void SetId (LPCTSTR guidStr)
Sets a unique ID for this object.
CString GetCustomName () const
Returns the name for custom units.
CString GetCustomAbbrev () const
Returns the abbreviation for custom units.
CString GetCustomBasisStr () const
Returns the units basis for custom units (i.e.
double GetCustomFactor () const
Returns the conversion factor for custom units.
MeaUnits::DisplayPrecisions GetCustomPrecisions () const
Returns the set of display precisions for custom units.
void Load (const MeaXMLNode *desktopNode)
Loads desktop elements of the log file.
void Save (MeaPositionLogMgr &mgr, int indent) const throw (CFileException)
Saves the desktop information.
bool operator== (const DesktopInfo &di) const
Compares the specified desktop information object with this to determine equality.
bool operator!= (const DesktopInfo &di) const
Compares the specified desktop information object with this to determine inequality.
Private Types
typedef std::list< Screen > ScreenList
List of all display screens attached to the system.
Private Member Functions
DesktopInfo & Copy (const DesktopInfo &desktop)
Copies the specified desktop information object into this object.
void Init ()
Centralized initialization method for the class.
bool IsEqual (const DesktopInfo &desktop) const
Determines whether the specified desktop information object is equal to this object.
void SetLinearUnits (const CString &unitsStr)
Sets the linear units for the object based on the specified units name.
void SetAngularUnits (const CString &unitsStr)
Sets the angular units for the object based on the specified units name.
void LoadCustomPrecisions (const MeaXMLNode *displayPrecisionNode)
Loads the display precisions values for the custom units.
void SaveCustomPrecisions (MeaPositionLogMgr &mgr, int indent) const throw (CFileException)
Saves the display precisions for custom units.
Private Attributes
MeaGUID m_id
ID for use by a Position object to reference this object.
FPOINT m_origin
Origin in the units that were in effect when the desktop object was created.
bool m_invertY
Is origin inverted.
FSIZE m_size
Desktop size in units in effect when desktop object created.
MeaLinearUnits * m_linearUnits
Current linear units.
MeaAngularUnits * m_angularUnits
Current angle units.
ScreenList m_screens
List of display screens.
CString m_customName
Custom units name.
CString m_customAbbrev
Custom units abbreviation.
CString m_customBasisStr
Custom scale factor basis.
double m_customFactor
Custom scale factor.
MeaUnits::DisplayPrecisions m_customPrecisions
Custom display precisions.
Detailed Description
Represents all information of interest about the system at the time a position is recorded.
This includes the list of all display screens attached to the system. The desktop information is saved in the position log file. To minimize repetition, positions reference the desktop information in effect when they were recorded. This means that one desktop information section can serve many positions.
Constructor & Destructor Documentation
DesktopInfo() [1/2]
MeaPositionLogMgr::DesktopInfo::DesktopInfo (LPCTSTR guidStr) explicit
Constructs a desktop information object with the specified unique ID.
Parameters
guidStr [in] GUID ID for the desktop information object.
References Init().
DesktopInfo() [2/2]
MeaPositionLogMgr::DesktopInfo::DesktopInfo (const DesktopInfo & desktop) inline
Constructs a desktop information object as a copy of the specified object.
Parameters
desktop [in] Desktop information object to copy.
References Copy().
Member Function Documentation
Copy()
DesktopInfo & MeaPositionLogMgr::DesktopInfo::Copy (const DesktopInfo & desktop) inline private
Copies the specified desktop information object into this object.
Parameters
desktop [in] Desktop information object to copy.
Returns
This object.
References m_angularUnits, m_customAbbrev, m_customBasisStr, m_customFactor, m_customName, m_customPrecisions, m_id, m_invertY, m_linearUnits, m_origin, m_screens, and m_size.
Referenced by DesktopInfo(), and operator=().
GetAngularUnits() [1/2]
MeaAngularUnits * MeaPositionLogMgr::DesktopInfo::GetAngularUnits () inline
Returns the angular units in effect when this object was created.
Returns
Angular units object in effect when this object was created.
References m_angularUnits.
Referenced by MeaPositionLogMgr::Position::Show().
GetAngularUnits() [2/2]
const MeaAngularUnits * MeaPositionLogMgr::DesktopInfo::GetAngularUnits () const inline
Returns the angular units in effect when this object was created.
Returns
Angular units object in effect when this object was created.
References m_angularUnits.
GetCustomAbbrev()
CString MeaPositionLogMgr::DesktopInfo::GetCustomAbbrev () const inline
Returns the abbreviation for custom units.
Returns
Abbreviation for custom units.
References m_customAbbrev.
Referenced by MeaPositionLogMgr::Position::Show().
GetCustomBasisStr()
CString MeaPositionLogMgr::DesktopInfo::GetCustomBasisStr () const inline
Returns the units basis for custom units (i.e.
pixels, inches or centimeters).
Returns
The units basis for custom units.
References m_customBasisStr.
Referenced by MeaPositionLogMgr::Position::Show().
GetCustomFactor()
double MeaPositionLogMgr::DesktopInfo::GetCustomFactor () const inline
Returns the conversion factor for custom units.
Returns
Conversion factor.
References m_customFactor.
Referenced by MeaPositionLogMgr::Position::Show().
GetCustomName()
CString MeaPositionLogMgr::DesktopInfo::GetCustomName () const inline
Returns the name for custom units.
Returns
Name for custom units.
References m_customName.
Referenced by MeaPositionLogMgr::Position::Show().
GetCustomPrecisions()
MeaUnits::DisplayPrecisions MeaPositionLogMgr::DesktopInfo::GetCustomPrecisions () const inline
Returns the set of display precisions for custom units.
Returns
Set of custom units display precisions.
References m_customPrecisions.
Referenced by MeaPositionLogMgr::Position::Show().
GetId()
const MeaGUID & MeaPositionLogMgr::DesktopInfo::GetId () const inline
Returns the unique ID for this object.
Returns
GUID ID for this object.
References m_id.
Referenced by MeaPositionLogMgr::ProcessDesktopNode(), and MeaPositionLogMgr::RecordDesktopInfo().
GetInvertY()
bool MeaPositionLogMgr::DesktopInfo::GetInvertY () const inline
Indicates whether the y-axis was inverted when this object was created.
Returns
true if the y-axis was inverted when this object was created.
References m_invertY.
Referenced by MeaPositionLogMgr::Position::Show().
GetLinearUnits() [1/2]
MeaLinearUnits * MeaPositionLogMgr::DesktopInfo::GetLinearUnits () inline
Returns the linear units in effect when this object was created.
Returns
Linear units object in effect when this object was created.
References m_linearUnits.
Referenced by MeaPositionLogMgr::Position::Show().
GetLinearUnits() [2/2]
const MeaLinearUnits * MeaPositionLogMgr::DesktopInfo::GetLinearUnits () const inline
Returns the linear units in effect when this object was created.
Returns
Linear units object in effect when this object was created.
References m_linearUnits.
GetOrigin()
const FPOINT & MeaPositionLogMgr::DesktopInfo::GetOrigin () const inline
Returns the location of the origin when this object was created.
Returns
The location of the origin when this object was created.
References m_origin.
Referenced by MeaPositionLogMgr::Position::Show().
Init()
void MeaPositionLogMgr::DesktopInfo::Init () private
Centralized initialization method for the class.
All non-copy constructors call this method.
References MeaScreenMgr::AtEnd(), MeaUnitsMgr::ConvertPos(), MeaCustomUnits::GetAbbrev(), MeaUnitsMgr::GetAngularUnits(), MeaUnits::GetDefaultPrecisions(), MeaUnitsMgr::GetInvertY(), MeaUnitsMgr::GetLinearUnits(), MeaCustomUnits::GetName(), MeaUnitsMgr::GetOrigin(), MeaCustomUnits::GetScaleBasisStr(), MeaCustomUnits::GetScaleFactor(), MeaScreenMgr::GetScreenIter(), MeaScreenMgr::GetVirtualRect(), MeaUnitsMgr::GetWidthHeight(), MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaSingleton_T< MeaScreenMgr >::Instance(), and MeaCustomId.
Referenced by DesktopInfo().
IsEqual()
bool MeaPositionLogMgr::DesktopInfo::IsEqual (const DesktopInfo & desktop) const inline private
Determines whether the specified desktop information object is equal to this object.
Parameters
desktop [in] Desktop information object to compare with this.
Returns
true if the specified object and this object are equal. Note that the object's unique IDs are not compared.
References FSIZE::cx, FSIZE::cy, m_angularUnits, m_customAbbrev, m_customBasisStr, m_customFactor, m_customName, m_customPrecisions, m_invertY, m_linearUnits, m_origin, m_screens, m_size, MEA_DBL_EQL, FPOINT::x, and FPOINT::y.
Referenced by operator!=(), and operator==().
Load()
void MeaPositionLogMgr::DesktopInfo::Load (const MeaXMLNode * desktopNode)
Loads desktop elements of the log file.
Parameters
desktopNode [in] Desktop node in the DOM.
References MeaXMLNode::AtEnd(), MeaXMLNode::Element, MeaXMLNode::GetAttributes(), MeaXMLNode::GetChildIter(), MeaXMLNode::GetData(), MeaXMLNode::GetType(), MeaXMLAttributes::GetValueBool(), MeaXMLAttributes::GetValueDbl(), MeaXMLAttributes::GetValueStr(), and MeaPositionLogMgr::Screen::Load().
Referenced by MeaPositionLogMgr::ProcessDesktopNode().
LoadCustomPrecisions()
void MeaPositionLogMgr::DesktopInfo::LoadCustomPrecisions (const MeaXMLNode * displayPrecisionNode) private
Loads the display precisions values for the custom units.
Parameters
displayPrecisionNode [in] displayPrecisions element in the DOM.
References MeaXMLNode::AtEnd(), MeaXMLNode::GetAttributes(), MeaXMLNode::GetChildIter(), MeaXMLNode::GetData(), MeaXMLAttributes::GetValueInt(), and MeaXMLAttributes::GetValueStr().
operator!=()
bool MeaPositionLogMgr::DesktopInfo::operator!= (const DesktopInfo & di) const inline
Compares the specified desktop information object with this to determine inequality.
Parameters
di [in] Desktop information object to compare with this.
Returns
true if the specified object and this are not equal.
References IsEqual().
operator=()
DesktopInfo & MeaPositionLogMgr::DesktopInfo::operator= (const DesktopInfo & desktop) inline
Assigns the specified desktop information object to this object.
Parameters
desktop [in] Desktop information object to be assigned.
Returns
This object.
References Copy().
operator==()
bool MeaPositionLogMgr::DesktopInfo::operator== (const DesktopInfo & di) const inline
Compares the specified desktop information object with this to determine equality.
Parameters
di [in] Desktop information object to compare with this.
Returns
true if the specified object and this are equal.
References IsEqual().
Save()
void MeaPositionLogMgr::DesktopInfo::Save (MeaPositionLogMgr & mgr, int indent) const throw (CFileException)
Saves the desktop information.
Parameters
mgr [in] Parent manager.
indent [in] Output indentation level.
References MeaUtils::DblToStr(), and MeaCustomId.
SaveCustomPrecisions()
void MeaPositionLogMgr::DesktopInfo::SaveCustomPrecisions (MeaPositionLogMgr & mgr, int indent) const throw (CFileException) private
Saves the display precisions for custom units.
Parameters
mgr [in] Parent manager.
indent [in] Output indentation level.
SetAngularUnits()
void MeaPositionLogMgr::DesktopInfo::SetAngularUnits (const CString & unitsStr) private
Sets the angular units for the object based on the specified units name.
Parameters
unitsStr [in] Angular units name.
References MeaUnitsMgr::GetAngularUnits(), MeaSingleton_T< MeaUnitsMgr >::Instance(), and MeaAssert.
SetId()
void MeaPositionLogMgr::DesktopInfo::SetId (LPCTSTR guidStr) inline
Sets a unique ID for this object.
Parameters
guidStr [in] GUID ID to set for this object.
References m_id.
SetLinearUnits()
void MeaPositionLogMgr::DesktopInfo::SetLinearUnits (const CString & unitsStr) private
Sets the linear units for the object based on the specified units name.
Parameters
unitsStr [in] Linear units name.
References MeaUnitsMgr::GetLinearUnits(), MeaSingleton_T< MeaUnitsMgr >::Instance(), and MeaAssert.
The documentation for this class was generated from the following files:
PositionLogMgr.h
PositionLogMgr.cpp
Copyright 2011 C Thing Software