Meazure: MeaXMLParser Class Reference
MeaXMLParser Class Reference
Provides SAX style XML parsing.
#include <XMLParser.h>
Public Member Functions
MeaXMLParser (MeaXMLParserHandler *handler, bool buildDOM=false)
Constructs an XML parser.
MeaXMLParser (const MeaXMLParser &parentParser)
Creates an external entity parser.
virtual ~MeaXMLParser ()
Destroys either a primary or a sub-parser.
void SetBasePath (const CString &path)
Sets the base path for resolving relative external entities.
void * GetBuffer (int len)
Obtains a buffer to load with XML data.
void ParseBuffer (int len, bool isFinal)
Parses the XML data contained in the buffer obtained by a previous call to GetBuffer.
const MeaXMLNode * GetDOM () const
If a DOM was constructed, this method returns its root node.
virtual void HandleValidationError (const ValidationError &error)=0
Called when a validation error occurs.
Static Public Member Functions
static CString FromUTF8 (const XML_Char *str)
Convenience method for converting the specified string from UTF8 encoding to a string.in ACP encoding.
static CString ToUTF8 (const CString &str)
Convenience method for converting the specified string from ACP encoding to UTF-8 encoding.
static CString Encode (const CString &str)
Replaces all occurrences of '&', '<', '>', '"', and "'" with the corresponding entities.
Private Types
typedef std::stack< CString > ElementStack
A stack type for elements.
typedef std::stack< MeaXMLNode * > NodeStack
A stack type for DOM nodes.
typedef std::stack< CString > PathnameStack
A stack type for entity pathnames.
Private Member Functions
MeaXMLParser & operator= (const MeaXMLParser &)
The parser has not assignment semantics so this method is purposely undefined.
void HandleParserError ()
Called when an XML parsing error occurrs.
virtual void HandleValidationError (const ev::ValidationError &error)
Called when an XML validation error occurrs.
Static Private Member Functions
static void StartElementHandler (void *userData, const XML_Char *elementName, const XML_Char **attrs)
Called by the underlying expat parser when an element is opened.
static void EndElementHandler (void *userData, const XML_Char *elementName)
Called by the underlying expat parser when an element is closed.
static void CharacterDataHandler (void *userData, const XML_Char *s, int len)
Called by the underlying expat parser when any character data is encountered.
static int ExternalEntityRefHandler (XML_Parser parser, const XML_Char *context, const XML_Char *base, const XML_Char *systemId, const XML_Char *publicId)
Called by the underlying expat parser when an external entity reference is encountered.
static void DoctypeDeclHandler (void *userData, const XML_Char *doctypeName, const XML_Char *sysid, const XML_Char *pubid, int has_internal_subset)
Called by the underlying expat parser when a DOCTYPE declaration is encountered in the XML file.
static void ElementDeclHandler (void *userData, const XML_Char *name, XML_Content *model)
Called by the underlying expat parser when a DTD element declaration is encountered.
static void AttributeDeclHandler (void *userData, const XML_Char *elname, const XML_Char *attname, const XML_Char *att_type, const XML_Char *dflt, int isrequired)
Called by the underlying expat parser when a DTD attribute declaration is encountered.
Private Attributes
XML_Parser m_parser
The expat XML parser.
bool m_isSubParser
Indicates whether this is an external entity sub-parser.
ev::Validator * m_validator
XML validator.
MeaXMLParserHandler * m_handler
XML event callback object.
ElementStack * m_elementStack
Stack of open elements.
PathnameStack * m_pathnameStack
Stack of pathnames for the entities being parsed.
bool m_haveDTD
Indicates if a DTD is referenced by the XML file being parsed.
const XML_Char * m_context
Internal expat parser state.
bool m_buildDOM
Indicates whether a DOM is being built.
MeaXMLNode * m_dom
Root node of the DOM being built, or NULL.
NodeStack * m_nodeStack
Stack of XML DOM nodes.
Static Private Attributes
static LPCTSTR m_homeURL = _T("https://www.cthing.com/")
URL for cthing.com.
Detailed Description
Provides SAX style XML parsing.
This class is a wrapper around the expat parser and adds XML validation. A class that wants XML parsing services mix-in inherits from the MeaXMLParserHandler class, overrides the methods of that class for the events of interest, creates an instance of this class and points it at the XML file to parse. The parser calls back using the methods of the MeaXMLParserHandler class to indicate various XML parsing events. This is classic SAX parsing behavior. The class can also build a primitive DOM.
Constructor & Destructor Documentation
MeaXMLParser() [1/2]
MeaXMLParser::MeaXMLParser (MeaXMLParserHandler * handler, bool buildDOM = false) explicit
Constructs an XML parser.
Parameters
handler [in] Callback object for parsing events.
buildDOM [in] Indicates whether a DOM should be built.
References AttributeDeclHandler(), CharacterDataHandler(), DoctypeDeclHandler(), ElementDeclHandler(), EndElementHandler(), ExternalEntityRefHandler(), m_elementStack, m_nodeStack, m_parser, m_pathnameStack, m_validator, MeaAssert, and StartElementHandler().
MeaXMLParser() [2/2]
MeaXMLParser::MeaXMLParser (const MeaXMLParser & parentParser)
Creates an external entity parser.
When an external is encountered, the MeaXMLParserHandler::ParseEntity method is called. This method should instantiate an XML sub-parser using this constructor and passing the parent parser provided by the callback method.
Parameters
parentParser [in] Parent parser for the external entity sub-parser.
References m_context, m_parser, and MeaAssert.
Member Function Documentation
AttributeDeclHandler()
void MeaXMLParser::AttributeDeclHandler (void * userData, const XML_Char * elname, const XML_Char * attname, const XML_Char * att_type, const XML_Char * dflt, int isrequired) static private
Called by the underlying expat parser when a DTD attribute declaration is encountered.
Parameters
userData [in] this
elname [in] Name of the element whose attribute is being declared.
attname [in] Name of the attribute being declared.
att_type [in] The type for the attribute.
dflt [in] Default value for the attribute, if any.
isrequired [in] Non-zero if the attribute must be specified.
References ev::Validator::AddAttributeDecl(), and m_validator.
Referenced by MeaXMLParser().
CharacterDataHandler()
void MeaXMLParser::CharacterDataHandler (void * userData, const XML_Char * s, int len) static private
Called by the underlying expat parser when any character data is encountered.
Parameters
userData [in] this
s [in] Buffer containing character data. The buffer might not be NULL terminated so the len parameter must be used to determine the end of the buffer.
len [in] Number of bytes of data in the buffer, s.
References ev::Validator::CharacterData(), MeaXMLParserHandler::CharacterDataHandler(), ev::Validator::IsMixed(), m_buildDOM, m_elementStack, m_handler, m_haveDTD, m_nodeStack, m_parser, and m_validator.
Referenced by MeaXMLParser().
DoctypeDeclHandler()
void MeaXMLParser::DoctypeDeclHandler (void * userData, const XML_Char * doctypeName, const XML_Char * sysid, const XML_Char * pubid, int has_internal_subset) static private
Called by the underlying expat parser when a DOCTYPE declaration is encountered in the XML file.
Parameters
userData [in] this
doctypeName [in] Document element name.
sysid [in] The XML system identifier for the DTD.
pubid [in] The public identifier for the DTD, or NULL if none.
has_internal_subset [in] Non-zero if an internal DTD subset has been specified.
References m_haveDTD, m_validator, and ev::Validator::SetDocumentElement().
Referenced by MeaXMLParser().
ElementDeclHandler()
void MeaXMLParser::ElementDeclHandler (void * userData, const XML_Char * name, XML_Content * model) static private
Called by the underlying expat parser when a DTD element declaration is encountered.
Parameters
userData [in] this
name [in] Name of the element being declared.
model [in] Content model for the element.
References ev::Validator::AddElementDecl(), m_parser, and m_validator.
Referenced by MeaXMLParser().
Encode()
CString MeaXMLParser::Encode (const CString & str) static
Replaces all occurrences of '&', '<', '>', '"', and "'" with the corresponding entities.
Attribute values and character data (i.e. text between start/end elements) must be encoded. This method should be called before converting the string to UTF-8.
Parameters
str [in] String to encode.
Returns
XML encoded string.
Referenced by MeaPositionLogMgr::Position::Save(), MeaFileProfile::WriteFileStart(), and MeaPositionLogMgr::WriteInfoSection().
EndElementHandler()
void MeaXMLParser::EndElementHandler (void * userData, const XML_Char * elementName) static private
Called by the underlying expat parser when an element is closed.
Parameters
userData [in] this
elementName [in] Name of the element being closed.
References ev::Validator::EndElement(), MeaXMLParserHandler::EndElementHandler(), FromUTF8(), m_buildDOM, m_elementStack, m_handler, m_haveDTD, m_nodeStack, m_parser, m_validator, and MeaAssert.
Referenced by MeaXMLParser().
ExternalEntityRefHandler()
int MeaXMLParser::ExternalEntityRefHandler (XML_Parser parser, const XML_Char * context, const XML_Char * base, const XML_Char * systemId, const XML_Char * publicId) static private
Called by the underlying expat parser when an external entity reference is encountered.
Parameters
parser [in] this
context [in] Expat internal parsing state.
base [in] Base path for the entity previously set by the SetBasePath method.
systemId [in] The XML system identifier for the entity.
publicId [in] The XML public identifier for the entity. This parameter will be NULL if no public identifier was specified for the entity.
Returns
The value 1, to indicate that the entity has been successfully parsed and parsing of the remainder of the XML file should continue.
References FromUTF8(), m_context, m_handler, m_homeURL, m_pathnameStack, and MeaXMLParserHandler::ParseEntity().
Referenced by MeaXMLParser().
FromUTF8()
CString MeaXMLParser::FromUTF8 (const XML_Char * str) static
Convenience method for converting the specified string from UTF8 encoding to a string.in ACP encoding.
Parameters
str [in] String in UTF-8 encoding.
Returns
String in ACP encoding.
Referenced by EndElementHandler(), ExternalEntityRefHandler(), MeaXMLAttributes::MeaXMLAttributes(), and StartElementHandler().
GetBuffer()
void * MeaXMLParser::GetBuffer (int len) inline
Obtains a buffer to load with XML data.
This method must be called prior to each call to ParseBuffer.
Parameters
len [in] Size of the buffer, in bytes.
Returns
Pointer to the allocated buffer. The class instance also holds a pointer to this buffer and owns the memory for it. Do not call free or delete on this pointer. A subsequent call to the ParseBuffer method will parse the contents of this buffer.
References m_parser.
Referenced by MeaPositionLogMgr::Load(), MeaFileProfile::ParseEntity(), MeaPositionLogMgr::ParseEntity(), and MeaFileProfile::ParseFile().
GetDOM()
const MeaXMLNode * MeaXMLParser::GetDOM () const inline
If a DOM was constructed, this method returns its root node.
Returns
Root node of the DOM or NULL if none was constructed.
References m_dom.
Referenced by MeaPositionLogMgr::Load().
HandleParserError()
void MeaXMLParser::HandleParserError () private
Called when an XML parsing error occurrs.
Queries the parser to determine the error and displays a dialog with a description of the problem.
References MeaXMLParserHandler::GetFilePathname(), m_handler, m_parser, and m_pathnameStack.
Referenced by ParseBuffer().
HandleValidationError()
void MeaXMLParser::HandleValidationError (const ev::ValidationError & error) private virtual
Called when an XML validation error occurrs.
Parameters
error [in] Describes the validation error.
Implements ev::IValidationHandler.
References ev::ValidationError::BadAttributeValue, ev::ValidationError::DuplicateId, ev::ValidationError::GetCharacterPosition(), ev::ValidationError::GetCode(), ev::ValidationError::GetContainingElement(), ev::ValidationError::GetCurrentElement(), MeaXMLParserHandler::GetFilePathname(), ev::ValidationError::GetLineNumber(), ev::ValidationError::IdNotFound, ev::ValidationError::InvalidDocumentElement, ev::ValidationError::InvalidElement, ev::ValidationError::InvalidElementPattern, m_handler, ev::ValidationError::MismatchedFixedValue, ev::ValidationError::MissingRequiredAttribute, ev::ValidationError::MultipleDocumentElements, ev::ValidationError::MultipleTopLevelElements, ev::ValidationError::NoCharacterData, ev::ValidationError::UncontainedCharacterData, ev::ValidationError::UndeclaredAttribute, ev::ValidationError::UndeclaredElement, ev::ValidationError::UndeclaredEntity, and ev::ValidationError::UndeclaredNotation.
ParseBuffer()
void MeaXMLParser::ParseBuffer (int len, bool isFinal)
Parses the XML data contained in the buffer obtained by a previous call to GetBuffer.
Each call to this method must be preceded by a call to GetBuffer.
Parameters
len [in] Actual number of bytes loaded into the buffer.
isFinal [in] Indicates if this is the end of the XML data.
References HandleParserError(), and m_parser.
Referenced by MeaPositionLogMgr::Load(), MeaFileProfile::ParseEntity(), MeaPositionLogMgr::ParseEntity(), and MeaFileProfile::ParseFile().
SetBasePath()
void MeaXMLParser::SetBasePath (const CString & path)
Sets the base path for resolving relative external entities.
Parameters
path [in] Base path.
References m_parser, and ToUTF8().
Referenced by MeaFileProfile::ParseFile().
StartElementHandler()
void MeaXMLParser::StartElementHandler (void * userData, const XML_Char * elementName, const XML_Char ** attrs) static private
Called by the underlying expat parser when an element is opened.
Parameters
userData [in] this
elementName [in] Name of the opened element.
attrs [in] Array of attributes arranged as name followed by value and terminated by a NULL entry.
References FromUTF8(), m_buildDOM, m_dom, m_elementStack, m_handler, m_haveDTD, m_nodeStack, m_parser, m_validator, MeaAssert, ev::Validator::StartElement(), and MeaXMLParserHandler::StartElementHandler().
Referenced by MeaXMLParser().
ToUTF8()
CString MeaXMLParser::ToUTF8 (const CString & str) static
Convenience method for converting the specified string from ACP encoding to UTF-8 encoding.
Parameters
str [in] String in ACP encoding.
Returns
String in UTF8 encoding.
Referenced by SetBasePath(), MeaFileProfile::Write(), and MeaPositionLogMgr::Write().
The documentation for this class was generated from the following files:
XMLParser.h
XMLParser.cpp
Copyright 2011 C Thing Software