Meazure: MeaDataDisplay Class Reference
MeaDataDisplay Class Reference
This class is responsible for the display of all measurement data.
#include <DataDisplay.h>
Classes
class DataItem
Each data display field is actually composed of a label, a text field, possibly a spin control, and usually a units label.
Public Member Functions
MeaDataDisplay ()
Constructs the data display component.
virtual ~MeaDataDisplay ()
Destroys the data display component.
bool Create (const POINT &topLeft, CWnd *parentWnd)
Creates the window for the data display.
void SetRegionLabel (UINT labelId)
Sets the label for the region frame.
void ShowCalButton (bool show)
Controls the display of the resolution calibration button.
void EnableRegionFields (UINT enableFields, UINT editableFields)
This method specifies which Region section text field should be enabled and, in addition, which fields should be editable.
void EnableScreenFields (UINT enableFields, UINT editableFields)
This method specifies which Screen section text field should be enabled and, in addition, which fields should be editable.
void ClearRegionData ()
Erases the contents of all region data fields.
void Enable (MeaSection section)
Enables the specified data display section.
void Disable (MeaSection section)
Disables the specified data display section.
bool IsEnabled (MeaSection section) const
Indicates whether the specified data display section is enabled.
int GetHeight (MeaSection section) const
Returns the height of the specified data display section.
void ShowXY1 (const POINT &point, const FPOINT &cpoint)
Displays the specified X1, Y1 coordinates.
void ShowXY2 (const POINT &point, const FPOINT &cpoint)
Displays the specified X2, Y2 coordinates.
void ShowXYV (const POINT &point, const FPOINT &cpoint)
Displays the specified vertex or center X, Y coordinates.
void ShowWH (const FSIZE &size)
Displays the specified width and height.
void ShowDistance (const FSIZE &size)
Displays a diagonal distance calculated from the specified width and height.
void ShowDistance (double dist)
Displays the specified distance.
void ShowAngle (double angle)
Displays the specified angle.
void ShowRectArea (const FSIZE &size)
Displays the rectangular area calculated from the specified width and height.
void ShowCircleArea (double radius)
Displays the circular area calculated from the specified radius.
void ShowScreenName (const CString &name)
Displays the specified string as the name for the current monitor.
void ShowScreenWH (const FSIZE &size)
Displays the specified screen width and height.
void ShowScreenRes (const FSIZE &res)
Displays the specified screen resolution.
MeaNumberField * GetFieldFocus () const
If one of the enabled text fields has the focus, a pointer to that window is returned.
Protected Member Functions
afx_msg LRESULT OnFieldEntry (WPARAM wParam, LPARAM id)
Called when the Enter key is pressed on one of the text fields.
afx_msg LRESULT OnHelpHitTest (WPARAM, LPARAM lparam)
Determines where the help cursor was clicked and provides the appropriate ID.
afx_msg BOOL OnNotify (WPARAM wParam, LPARAM lParam, LRESULT *pResult)
Called when spin control UDN_DELTAPOS messages are sent.
Private Types
typedef std::set
< MeaNumberField * > Fields
A set of numerical text fields.
Private Member Functions
bool CreateRegionSection ()
Creates the section devoted to displaying radio tool measurements.
bool CreateScreenSection ()
Create the section devoted to displaying screen information.
Private Attributes
MeaDataSection m_regionSection
Measurement tool display section.
MeaDataSection m_screenSection
Screen information display section.
bool m_regionSectionProfileEnabled
Indicates if the measurement tool display section is shown based on the user preferences.
bool m_screenSectionProfileEnabled
Indicates if the screen information display section is shown based on the user preferences.
bool m_regionSectionEnabled
Indicates if the measurement tool display is shown.
bool m_screenSectionEnabled
Indicates if the screen information section is shown.
CRect m_regionSectionRect
Rectangle containing the measurement tool display section.
CRect m_screenSectionRect
Rectangle containing the screen information section.
DataItem m_x1
X1 coordinate data item.
DataItem m_y1
Y1 coordinate data item.
DataItem m_x2
X2 coordinate data item.
DataItem m_y2
Y2 coordinate data item.
DataItem m_xv
Vertex or center X coordinate data item.
DataItem m_yv
Vertex or center Y coordinate data item.
DataItem m_width
Width data item.
DataItem m_height
Height data item.
DataItem m_length
Distance data item.
DataItem m_angle
Angle data item.
DataItem m_area
Area data item.
DataItem m_screenWidth
Screen width data item.
DataItem m_screenHeight
Screen height data item.
DataItem m_screenResX
Screen X resolution data item.
DataItem m_screenResY
Screen Y resolution data item.
MeaImageButton m_calBtn
Calibration warning button.
Fields m_fields
Set of all text fields.
Static Private Attributes
static const RECT kMargin = { 7, 17, 7, 7 }
Margins for the sections, in pixels.
static const SIZE kControlSpacing = { 7, 5 }
Horizontal and vertical spacing for the controls in a data item, in pixels.
static const int kSectionSpacing = 3
Vertical spacing between sections, in pixels.
static const int kLabelSpacing = 3
Spacing between labels and their text fields, in pixels.
static const unsigned int kLengthChars = 6
Number of visible and allowable characters for length fields.
static const int kAngleChars = 6
Number of visible and allowable characters for the angle field.
static const int kAreaChars = 17
Number of visible and allowable characters for the area field.
static const int kResChars = 6
Number of visible and allowable characters for the screen resolution fields.
Detailed Description
This class is responsible for the display of all measurement data.
The data display is divided into two major sections: Region and Screen. The Region section displays the measurement data from the radio measurement tools (e.g. Point tool, Line Tool). The Screen section displays data about the current monitor (e.g. resolution, width, height).
Within each section are a set of text fields, which display the measurement data. Depending on the measurement tool being used, certain text fields are editable and offer up/down spin controls for fine adjustment of tool crosshair positions.
Constructor & Destructor Documentation
MeaDataDisplay::MeaDataDisplay ()
Constructs the data display component.
To complete the construction of the component, the Create method must be called.
Member Function Documentation
bool MeaDataDisplay::Create (const POINT & topLeft, CWnd * parentWnd)
Creates the window for the data display.
Parameters:
topLeft [in] Position of the top, left corner of the display.
parentWnd [in] Parent window for the display.
Returns:
true if successful; false otherwise.
References CreateRegionSection(), CreateScreenSection(), MeaLayout::GetBoundingSize(), kSectionSpacing, m_regionSection, m_regionSectionRect, m_screenSection, m_screenSectionRect, MeaLayout::SetWindowPos(), and MeaLayout::SetWindowSize().
Referenced by CChildView::OnCreate().
bool MeaDataDisplay::CreateRegionSection () [private]
Creates the section devoted to displaying radio tool measurements.
Returns:
true if the section was created successfully.
References MeaLayout::AlignCenter(), MeaLayout::AlignRight(), MeaLayout::AlignRightTo(), MeaDataDisplay::DataItem::CreateAngleUnits(), MeaDataDisplay::DataItem::CreateAreaUnits(), MeaDataDisplay::DataItem::CreateField(), MeaDataDisplay::DataItem::CreateLengthUnits(), MeaUnitsMgr::GetAngularUnits(), MeaLayout::GetBoundingSize(), MeaDataDisplay::DataItem::GetField(), MeaUnitsMgr::GetLinearUnits(), MeaDataDisplay::DataItem::GetSpin(), MeaDataDisplay::DataItem::GetTitleLabel(), MeaDataDisplay::DataItem::GetUnitsLabel(), MeaScreenMgr::GetVirtualRect(), MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaSingleton_T< MeaScreenMgr >::Instance(), kAngleChars, kAreaChars, kControlSpacing, kLabelSpacing, kLengthChars, kMargin, m_angle, m_area, m_height, m_length, m_regionSection, m_width, m_x1, m_x2, m_xv, m_y1, m_y2, m_yv, MeaAngleField, MeaAreaField, MeaDistanceField, MeaHeightField, MeaWidthField, MeaX1Field, MeaX2Field, MeaXVField, MeaY1Field, MeaY2Field, MeaYVField, MeaLayout::PlaceAfter(), MeaDataDisplay::DataItem::SetLimitText(), MeaDataDisplay::DataItem::SetSpinRange(), and MeaLayout::SetWindowSize().
Referenced by Create().
bool MeaDataDisplay::CreateScreenSection () [private]
Create the section devoted to displaying screen information.
Returns:
true if the section was created successfully.
References MeaLayout::AlignCenter(), MeaLayout::AlignRight(), MeaLayout::AlignRightTo(), MeaImageButton::Create(), MeaDataDisplay::DataItem::CreateField(), MeaDataDisplay::DataItem::CreateLengthUnits(), MeaDataDisplay::DataItem::CreateResUnits(), MeaLayout::GetBoundingSize(), MeaDataDisplay::DataItem::GetField(), MeaUnitsMgr::GetLinearUnits(), MeaDataDisplay::DataItem::GetTitleLabel(), MeaDataDisplay::DataItem::GetUnitsLabel(), MeaSingleton_T< MeaUnitsMgr >::Instance(), kControlSpacing, kLabelSpacing, kLengthChars, kMargin, kResChars, MeaImageButton::LoadBitmaps(), m_calBtn, m_screenHeight, m_screenResX, m_screenResY, m_screenSection, m_screenWidth, MeaResXField, MeaResYField, MeaScreenHeightField, MeaScreenWidthField, MeaLayout::PlaceAfter(), MeaLayout::SetWindowPos(), and MeaLayout::SetWindowSize().
Referenced by Create().
void MeaDataDisplay::Disable (MeaSection section)
Disables the specified data display section.
Parameters:
section [in] Data display section to enable.
References m_regionSection, m_regionSectionEnabled, m_regionSectionRect, m_screenSection, m_screenSectionEnabled, MeaRegionSection, and MeaLayout::MoveWindowHeight().
Referenced by CChildView::ViewScreenInfo(), and CChildView::ViewToolInfo().
void MeaDataDisplay::Enable (MeaSection section)
Enables the specified data display section.
Parameters:
section [in] Data display section to enable.
References m_regionSection, m_regionSectionEnabled, m_regionSectionRect, m_screenSection, m_screenSectionEnabled, MeaRegionSection, and MeaLayout::MoveWindowHeight().
Referenced by CChildView::ViewScreenInfo(), and CChildView::ViewToolInfo().
void MeaDataDisplay::EnableRegionFields (UINT enableFields, UINT editableFields)
This method specifies which Region section text field should be enabled and, in addition, which fields should be editable.
The fields are specified as an OR'd set of MeaFields identifiers. Fields that are not specified are disabled.
Parameters:
enableFields [in] OR'd set of field identifiers for the fields to enable.
editableFields [in] OR'd set of field identifiers for the fields to make editable.
References MeaDataDisplay::DataItem::Enable(), m_angle, m_area, m_height, m_length, m_width, m_x1, m_x2, m_xv, m_y1, m_y2, m_yv, MeaAngleField, MeaAreaField, MeaDistanceField, MeaHeightField, MeaWidthField, MeaX1Field, MeaX2Field, MeaXVField, MeaY1Field, MeaY2Field, MeaYVField, and MeaDataDisplay::DataItem::SetReadOnly().
Referenced by MeaToolMgr::EnableRegionFields().
void MeaDataDisplay::EnableScreenFields (UINT enableFields, UINT editableFields)
This method specifies which Screen section text field should be enabled and, in addition, which fields should be editable.
The fields are specified as an OR'd set of MeaFields identifiers. Fields that are not specified are disabled.
Parameters:
enableFields [in] OR'd set of field identifiers for the fields to enable.
editableFields [in] OR'd set of field identifiers for the fields to make editable.
References MeaDataDisplay::DataItem::Enable(), m_screenHeight, m_screenResX, m_screenResY, m_screenWidth, MeaResXField, MeaResYField, MeaScreenHeightField, MeaScreenWidthField, and MeaDataDisplay::DataItem::SetReadOnly().
Referenced by MeaToolMgr::EnableScreenFields().
MeaNumberField * MeaDataDisplay::GetFieldFocus () const
If one of the enabled text fields has the focus, a pointer to that window is returned.
Returns:
Pointer to enabled field if it has the focus and NULL otherwise.
References m_fields.
Referenced by CChildView::OnEditClear(), CChildView::OnEditCopy(), CChildView::OnEditCut(), CChildView::OnEditPaste(), CChildView::OnUpdateEditClear(), CChildView::OnUpdateEditCopy(), CChildView::OnUpdateEditCut(), and CChildView::OnUpdateEditPaste().
int MeaDataDisplay::GetHeight (MeaSection section) const [inline]
Returns the height of the specified data display section.
Parameters:
section [in] Data display section whose height is desired.
Returns:
Height of the specified data display section, in pixels.
References kSectionSpacing, m_regionSectionRect, m_screenSectionRect, and MeaRegionSection.
Referenced by CChildView::ViewScreenInfo(), and CChildView::ViewToolInfo().
bool MeaDataDisplay::IsEnabled (MeaSection section) const [inline]
Indicates whether the specified data display section is enabled.
Returns:
true if the specified data display section is enabled.
References m_regionSectionEnabled, m_screenSectionEnabled, and MeaRegionSection.
Referenced by CChildView::CheckMargins(), CChildView::IsCollapsed(), CChildView::LoadProfile(), CChildView::OnCollapse(), CChildView::OnScreenInfo(), CChildView::OnToolInfo(), CChildView::OnUpdateScreenInfo(), CChildView::OnUpdateToolInfo(), CChildView::SaveProfile(), CChildView::ViewScreenInfo(), and CChildView::ViewToolInfo().
LRESULT MeaDataDisplay::OnFieldEntry (WPARAM wParam, LPARAM id) [protected]
Called when the Enter key is pressed on one of the text fields.
Parameters:
wParam [in] 0, 1, -1 as increment.
id [in] ID of the text field.
Returns:
Always returns TRUE.
References MeaDataDisplay::DataItem::GetField(), MeaDataDisplay::DataItem::GetValue(), MeaSingleton_T< MeaUnitsMgr >::Instance(), m_x1, m_x2, m_xv, m_y1, m_y2, m_yv, MeaAssert, MeaDataChangeMsg, MeaX1Field, MeaX2Field, MeaXVField, MeaY1Field, MeaY2Field, MeaYVField, MeaUnitsMgr::UnconvertCoord(), FPOINT::x, and FPOINT::y.
LRESULT MeaDataDisplay::OnHelpHitTest (WPARAM , LPARAM lparam) [protected]
Determines where the help cursor was clicked and provides the appropriate ID.
Parameters:
lparam [in] Pointer coordinates.
Returns:
Help ID corresponding to section where mouse clicked.
References m_regionSectionRect.
BOOL MeaDataDisplay::OnNotify (WPARAM wParam, LPARAM lParam, LRESULT * pResult) [protected]
Called when spin control UDN_DELTAPOS messages are sent.
Parameters:
wParam [in] Control ID.
lParam [in] Pointer to NMHDR structure.
pResult [in] FALSE to allow the spin control to change its position or TRUE to indicate that the message has already been processed.
Returns:
TRUE if the message has been processed or FALSE if the spin control needs to process the message.
References MeaDataChangeMsg.
void MeaDataDisplay::SetRegionLabel (UINT labelId) [inline]
Sets the label for the region frame.
Parameters:
labelId [in] String resource ID for the region frame label.
References m_regionSection.
Referenced by MeaToolMgr::ChangeRadioToolEnable().
void MeaDataDisplay::ShowAngle (double angle)
Displays the specified angle.
Parameters:
angle [in] Angle, in current angular units.
References MeaSingleton_T< MeaUnitsMgr >::Instance(), m_angle, and MeaDataDisplay::DataItem::SetText().
Referenced by MeaToolMgr::ShowAngle().
void MeaDataDisplay::ShowCalButton (bool show) [inline]
Controls the display of the resolution calibration button.
Typically, the screen resolution reported by the operating system is inaccurate. Because of this inaccuracy, if the operating system resolution is being used for measurements, a warning button is displayed on the Screen region of the data display. Pressing the button displays the resolution calibration preference page. If a manually calibrated resolution is being used, the calibration warning button is not displayed.
Parameters:
show [in] Specified whether the calibration warning button should be shown or hidden.
References m_calBtn.
Referenced by CChildView::ApplyPreferences(), and MeaToolMgr::ShowCalButton().
void MeaDataDisplay::ShowCircleArea (double radius)
Displays the circular area calculated from the specified radius.
Parameters:
radius [in] Radius, in current units.
References MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaUnits::kPI, m_area, MeaAr, and MeaDataDisplay::DataItem::SetText().
Referenced by MeaToolMgr::ShowCircleArea().
void MeaDataDisplay::ShowDistance (const FSIZE & size)
Displays a diagonal distance calculated from the specified width and height.
Parameters:
size [in] Width and height, in current units.
References MeaLayout::CalcLength(), FSIZE::cx, FSIZE::cy, MeaSingleton_T< MeaUnitsMgr >::Instance(), m_length, MeaD, and MeaDataDisplay::DataItem::SetText().
Referenced by MeaToolMgr::ShowDistance().
void MeaDataDisplay::ShowDistance (double dist)
Displays the specified distance.
Parameters:
dist [in] Distance, in current units.
References MeaSingleton_T< MeaUnitsMgr >::Instance(), m_length, MeaD, and MeaDataDisplay::DataItem::SetText().
void MeaDataDisplay::ShowRectArea (const FSIZE & size)
Displays the rectangular area calculated from the specified width and height.
Parameters:
size [in] Width and height, in current units.
References FSIZE::cx, FSIZE::cy, MeaSingleton_T< MeaUnitsMgr >::Instance(), m_area, MeaAr, and MeaDataDisplay::DataItem::SetText().
Referenced by MeaToolMgr::ShowRectArea().
void MeaDataDisplay::ShowScreenName (const CString & name)
Displays the specified string as the name for the current monitor.
This helps identify the screen information in multiple monitor environments.
Parameters:
name [in] Name for the current monitor.
References m_screenSection.
Referenced by MeaToolMgr::ShowScreenName().
void MeaDataDisplay::ShowScreenRes (const FSIZE & res)
Displays the specified screen resolution.
Parameters:
res [in] Screen resolution in the X and Y dimensions, in the current units.
References FSIZE::cx, FSIZE::cy, MeaUnitsMgr::Format(), MeaSingleton_T< MeaUnitsMgr >::Instance(), m_screenResX, m_screenResY, MeaRx, MeaRy, and MeaDataDisplay::DataItem::SetText().
Referenced by MeaToolMgr::ShowScreenRes().
void MeaDataDisplay::ShowScreenWH (const FSIZE & size)
Displays the specified screen width and height.
Parameters:
size [in] Screen width and height, in the current units.
References FSIZE::cx, FSIZE::cy, MeaUnitsMgr::Format(), MeaSingleton_T< MeaUnitsMgr >::Instance(), m_screenHeight, m_screenWidth, MeaH, MeaW, and MeaDataDisplay::DataItem::SetText().
Referenced by MeaToolMgr::ShowScreenWH().
void MeaDataDisplay::ShowWH (const FSIZE & size)
Displays the specified width and height.
Parameters:
size [in] Width and height, in current units.
References FSIZE::cx, FSIZE::cy, MeaUnitsMgr::Format(), MeaSingleton_T< MeaUnitsMgr >::Instance(), m_height, m_width, MeaH, MeaW, and MeaDataDisplay::DataItem::SetText().
Referenced by MeaToolMgr::ShowWH().
void MeaDataDisplay::ShowXY1 (const POINT & point, const FPOINT & cpoint)
Displays the specified X1, Y1 coordinates.
Parameters:
point [in] Coordinates, in pixels.
cpoint [in] Coordinates, in current units.
References MeaUnitsMgr::Format(), MeaSingleton_T< MeaUnitsMgr >::Instance(), m_x1, m_y1, MeaX, MeaY, MeaDataDisplay::DataItem::SetSpinPos(), MeaDataDisplay::DataItem::SetText(), FPOINT::x, and FPOINT::y.
Referenced by MeaToolMgr::ShowXY1().
void MeaDataDisplay::ShowXY2 (const POINT & point, const FPOINT & cpoint)
Displays the specified X2, Y2 coordinates.
Parameters:
point [in] Coordinates, in pixels.
cpoint [in] Coordinates, in current units.
References MeaUnitsMgr::Format(), MeaSingleton_T< MeaUnitsMgr >::Instance(), m_x2, m_y2, MeaX, MeaY, MeaDataDisplay::DataItem::SetSpinPos(), MeaDataDisplay::DataItem::SetText(), FPOINT::x, and FPOINT::y.
Referenced by MeaToolMgr::ShowXY2().
void MeaDataDisplay::ShowXYV (const POINT & point, const FPOINT & cpoint)
Displays the specified vertex or center X, Y coordinates.
Parameters:
point [in] Coordinates, in pixels.
cpoint [in] Coordinates, in current units.
References MeaUnitsMgr::Format(), MeaSingleton_T< MeaUnitsMgr >::Instance(), m_xv, m_yv, MeaX, MeaY, MeaDataDisplay::DataItem::SetSpinPos(), MeaDataDisplay::DataItem::SetText(), FPOINT::x, and FPOINT::y.
Referenced by MeaToolMgr::ShowXYV().
Member Data Documentation
const int MeaDataDisplay::kAngleChars = 6 [static, private]
Number of visible and allowable characters for the angle field.
Referenced by CreateRegionSection().
const int MeaDataDisplay::kAreaChars = 17 [static, private]
Number of visible and allowable characters for the area field.
Referenced by CreateRegionSection().
const SIZE MeaDataDisplay::kControlSpacing = { 7, 5 } [static, private]
Horizontal and vertical spacing for the controls in a data item, in pixels.
Referenced by CreateRegionSection(), and CreateScreenSection().
const int MeaDataDisplay::kLabelSpacing = 3 [static, private]
Spacing between labels and their text fields, in pixels.
Referenced by CreateRegionSection(), and CreateScreenSection().
const unsigned int MeaDataDisplay::kLengthChars = 6 [static, private]
Number of visible and allowable characters for length fields.
Referenced by CreateRegionSection(), and CreateScreenSection().
const int MeaDataDisplay::kResChars = 6 [static, private]
Number of visible and allowable characters for the screen resolution fields.
Referenced by CreateScreenSection().
bool MeaDataDisplay::m_regionSectionProfileEnabled [private]
Indicates if the measurement tool display section is shown based on the user preferences.
bool MeaDataDisplay::m_screenSectionProfileEnabled [private]
Indicates if the screen information display section is shown based on the user preferences.
The documentation for this class was generated from the following files:
DataDisplay.h
DataDisplay.cpp
Copyright 2011 C Thing Software