Meazure: MeaTool Class Reference
MeaTool Class Reference abstract
Abstract base class for all measurement tools.
#include <Tool.h>
Public Member Functions
MeaTool (MeaToolMgr &mgr, const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Base class constructor.
virtual ~MeaTool ()=default
Destroys the tool.
virtual void Enable ()
Typically used by derived classes to show the tool.
virtual void Disable ()
Typically used by derived classes to hide the tool.
virtual void Update (MeaUpdateReason reason)
Used by derived classes to update the display of their data.
virtual bool IsRadioTool ()
Indicates whether the derived tool is a radio tool and cannot be enabled until any other enabled Radio tool is disabled.
virtual void SetPosition (MeaDataFieldId which, int pixels)
Sets the position of the tool.
virtual const POINT & GetPosition () const =0
Returns the tool's current position.
virtual void IncPosition (MeaDataFieldId which)
Increments the specified position field.
virtual void DecPosition (MeaDataFieldId which)
Decrements the specified position field.
virtual CString GetToolName () const =0
Returns the name of the tool.
virtual void SaveProfile (MeaProfile &profile)
Persists the state of the tool to the specified profile object.
virtual void LoadProfile (MeaProfile &profile)
Restores the state of the tool from the specified profile object.
virtual void MasterReset ()
Resets the tool to its default state.
virtual void ColorsChanged ()
Called to notify the tool that the colors in the MeaColors class have been changed.
bool IsEnabled () const
Indicates whether the tool is enabled.
Protected Attributes
MeaToolMgr & m_mgr
Tool manager.
const MeaScreenProvider & m_screenProvider
Screen information provider.
const MeaUnitsProvider & m_unitsProvider
Units information provider.
bool m_enabled
Indicates whether the tool is enabled.
Static Protected Attributes
static const CPoint m_defaultPos
A default position used by tools that do not have a defined position.
Detailed Description
Abstract base class for all measurement tools.
Both radio and non-radio measurement tools inherit from this base class.
Constructor & Destructor Documentation
MeaTool()
MeaTool::MeaTool (MeaToolMgr & mgr, const MeaScreenProvider & screenProvider, const MeaUnitsProvider & unitsProvider) explicit
Base class constructor.
Typically, to use a newly constructed tool, the Enable() method must be called.
Parameters
mgr [in] Tool manager parent of the tool.
screenProvider [in] Screen information provider
unitsProvider [in] Units information provider
Member Function Documentation
ColorsChanged()
void MeaTool::ColorsChanged () virtual
Called to notify the tool that the colors in the MeaColors class have been changed.
Typically a derived class redraws its components with the new colors and opacities.
Reimplemented in MeaAngleTool, MeaCircleTool, MeaCursorTool, MeaGridTool, MeaLineTool, MeaOriginTool, MeaPointTool, MeaRectTool, MeaRulerTool, and MeaWindowTool.
DecPosition()
void MeaTool::DecPosition (MeaDataFieldId which) virtual
Decrements the specified position field.
Parameters
which Position field to decrement
Reimplemented in MeaAngleTool, MeaCircleTool, MeaLineTool, MeaPointTool, and MeaRectTool.
Referenced by MeaToolMgr::DecPosition().
Disable()
void MeaTool::Disable () virtual
Typically used by derived classes to hide the tool.
Reimplemented in MeaAngleTool, MeaCircleTool, MeaCursorTool, MeaGridTool, MeaLineTool, MeaOriginTool, MeaPointTool, MeaRectTool, MeaRulerTool, MeaScreenTool, and MeaWindowTool.
References m_enabled.
Referenced by MeaAngleTool::Disable(), MeaCircleTool::Disable(), MeaCursorTool::Disable(), MeaGridTool::Disable(), MeaLineTool::Disable(), MeaOriginTool::Disable(), MeaPointTool::Disable(), MeaRectTool::Disable(), MeaRulerTool::Disable(), MeaScreenTool::Disable(), MeaWindowTool::Disable(), MeaToolMgr::DisableRadioTool(), MeaToolMgr::DisableRadioTools(), MeaToolMgr::DisableTool(), and MeaToolMgr::ToggleEnableTool().
Enable()
void MeaTool::Enable () virtual
Typically used by derived classes to show the tool.
In addition, the first time this method is called, it typically creates the components that comprise the tool.
Reimplemented in MeaAngleTool, MeaCircleTool, MeaCursorTool, MeaGridTool, MeaLineTool, MeaOriginTool, MeaPointTool, MeaRectTool, MeaRulerTool, MeaScreenTool, and MeaWindowTool.
References m_enabled.
Referenced by MeaAngleTool::Enable(), MeaCircleTool::Enable(), MeaCursorTool::Enable(), MeaGridTool::Enable(), MeaLineTool::Enable(), MeaOriginTool::Enable(), MeaPointTool::Enable(), MeaRectTool::Enable(), MeaRulerTool::Enable(), MeaScreenTool::Enable(), MeaWindowTool::Enable(), MeaToolMgr::EnableRadioTool(), MeaToolMgr::EnableTool(), and MeaToolMgr::ToggleEnableTool().
GetPosition()
virtual const POINT & MeaTool::GetPosition () const pure virtual
Returns the tool's current position.
The current position is the position of the last crosshair entered or moved. The default position is the location of point 1.
Returns
Current position
Implemented in MeaAngleTool, MeaCircleTool, MeaCursorTool, MeaGridTool, MeaLineTool, MeaOriginTool, MeaPointTool, MeaRectTool, MeaRulerTool, MeaScreenTool, and MeaWindowTool.
GetToolName()
virtual CString MeaTool::GetToolName () const pure virtual
Returns the name of the tool.
Each tool has a unique name which is used to identify the tool in profiles and position logs.
Returns
Name of the tool
Implemented in MeaAngleTool, MeaCircleTool, MeaCursorTool, MeaGridTool, MeaLineTool, MeaOriginTool, MeaPointTool, MeaRectTool, MeaRulerTool, MeaScreenTool, and MeaWindowTool.
Referenced by MeaToolMgr::GetToolName(), MeaToolMgr::LoadProfile(), and MeaToolMgr::SaveProfile().
IncPosition()
void MeaTool::IncPosition (MeaDataFieldId which) virtual
Increments the specified position field.
Parameters
which Position field to increment
Reimplemented in MeaAngleTool, MeaCircleTool, MeaLineTool, MeaPointTool, and MeaRectTool.
Referenced by MeaToolMgr::IncPosition().
IsEnabled()
bool MeaTool::IsEnabled () const inline
Indicates whether the tool is enabled.
A tool is enabled when the Enable() method is called and is disabled when the Disable() method is called.
Returns
true if the tool is enabled.
References m_enabled.
Referenced by MeaAngleTool::Disable(), MeaCircleTool::Disable(), MeaCursorTool::Disable(), MeaGridTool::Disable(), MeaLineTool::Disable(), MeaOriginTool::Disable(), MeaPointTool::Disable(), MeaRectTool::Disable(), MeaRulerTool::Disable(), MeaScreenTool::Disable(), MeaWindowTool::Disable(), MeaToolMgr::DisableRadioTools(), MeaAngleTool::Enable(), MeaCircleTool::Enable(), MeaCursorTool::Enable(), MeaGridTool::Enable(), MeaLineTool::Enable(), MeaOriginTool::Enable(), MeaPointTool::Enable(), MeaRectTool::Enable(), MeaRulerTool::Enable(), MeaScreenTool::Enable(), MeaWindowTool::Enable(), MeaToolMgr::IsToolEnabled(), MeaRulerTool::PositionIndicators(), MeaGridTool::SaveProfile(), MeaOriginTool::SaveProfile(), MeaRulerTool::SaveProfile(), MeaToolMgr::ToggleEnableTool(), MeaAngleTool::Update(), MeaCircleTool::Update(), MeaCursorTool::Update(), MeaGridTool::Update(), MeaLineTool::Update(), MeaOriginTool::Update(), MeaPointTool::Update(), MeaRectTool::Update(), MeaRulerTool::Update(), MeaScreenTool::Update(), MeaWindowTool::Update(), MeaGridTool::UpdateH(), and MeaGridTool::UpdateV().
IsRadioTool()
bool MeaTool::IsRadioTool () virtual
Indicates whether the derived tool is a radio tool and cannot be enabled until any other enabled Radio tool is disabled.
Returns
Always false indicating that this class and its derived classes are not radio tools unless they have overridden this method.
Reimplemented in MeaRadioTool.
Referenced by MeaToolMgr::DisableRadioTools(), MeaToolMgr::LoadProfile(), and MeaToolMgr::SetRadioTool().
LoadProfile()
void MeaTool::LoadProfile (MeaProfile & profile) virtual
Restores the state of the tool from the specified profile object.
This base class implementation does nothing.
Parameters
profile [in] The source for the state information. Typically an MeaFileProfile or MeaRegistryProfile object.
Reimplemented in MeaAngleTool, MeaCircleTool, MeaGridTool, MeaLineTool, MeaOriginTool, MeaPointTool, MeaRectTool, MeaRulerTool, and MeaScreenTool.
MasterReset()
void MeaTool::MasterReset () virtual
Resets the tool to its default state.
Reimplemented in MeaGridTool, MeaOriginTool, and MeaRulerTool.
SaveProfile()
void MeaTool::SaveProfile (MeaProfile & profile) virtual
Persists the state of the tool to the specified profile object.
This base class implementation does nothing.
Parameters
profile [in] The destination for the state information. Typically an MeaFileProfile or MeaRegistryProfile object.
Reimplemented in MeaAngleTool, MeaCircleTool, MeaGridTool, MeaLineTool, MeaOriginTool, MeaPointTool, MeaRectTool, and MeaRulerTool.
SetPosition()
void MeaTool::SetPosition (MeaDataFieldId which, int pixels) virtual
Sets the position of the tool.
This method sets the position one location component at a time.
Parameters
which [in] Position component
pixels [in] Position to set for the component, in pixels
Reimplemented in MeaAngleTool, MeaCircleTool, MeaLineTool, MeaPointTool, and MeaRectTool.
Referenced by MeaGridTool::SetLines().
Update()
void MeaTool::Update (MeaUpdateReason reason) virtual
Used by derived classes to update the display of their data.
Parameters
reason [in] Reason why the update has been requested
Reimplemented in MeaAngleTool, MeaCircleTool, MeaCursorTool, MeaGridTool, MeaLineTool, MeaOriginTool, MeaPointTool, MeaRectTool, MeaRulerTool, MeaScreenTool, and MeaWindowTool.
References m_enabled.
Referenced by MeaAngleTool::Update(), MeaCircleTool::Update(), MeaCursorTool::Update(), MeaGridTool::Update(), MeaLineTool::Update(), MeaOriginTool::Update(), MeaPointTool::Update(), MeaRectTool::Update(), MeaRulerTool::Update(), MeaScreenTool::Update(), MeaWindowTool::Update(), MeaGridTool::UpdateH(), and MeaGridTool::UpdateV().
Member Data Documentation
m_defaultPos
const CPoint MeaTool::m_defaultPos static protected
A default position used by tools that do not have a defined position.
This position is returned by the RecordPosition() method
Referenced by MeaGridTool::GetPosition(), MeaRulerTool::GetPosition(), and MeaScreenTool::GetPosition().
The documentation for this class was generated from the following files:
Tool.h
Tool.cpp
Copyright 2011 C Thing Software