Meazure: MeaGraphic Class Reference
MeaGraphic Class Reference
Base class for all graphic elements.
#include <Graphic.h>
Public Member Functions
MeaGraphic ()
Base class constructor.
virtual ~MeaGraphic ()
Base class destructor.
bool Create (LPCTSTR classname, const SIZE &size, const CWnd *parent, UINT id=0xFFFF)
Creates the window for the graphic.
virtual void Show ()
Displays the graphic.
virtual void Hide ()
Hides the graphic.
void SetAbove (const CWnd *winBelow)
Changes the z-order of the graphic window so that it if above the specified window.
Protected Attributes
UINT m_id
ID for the graphic.
bool m_visible
Indicates whether the graphic is shown or hidden.
const CWnd * m_parent
Graphic's parent window or NULL if graphic is a popup window.
Static Protected Attributes
static const int kInitCoord = -1000
An arbitrary initial coordinate for placing new graphics.
Detailed Description
Base class for all graphic elements.
Classes derived from this base class are used by the measurement tools to perform their function.
Constructor & Destructor Documentation
MeaGraphic()
MeaGraphic::MeaGraphic ()
Base class constructor.
Prior to displaying the graphic with the Show() method, the Create() method must be called to create the graphic's window.
Member Function Documentation
Create()
bool MeaGraphic::Create (LPCTSTR classname, const SIZE & size, const CWnd * parent, UINT id = 0xFFFF)
Creates the window for the graphic.
This method must be called before the graphic can be displayed and before any operation that attempts to manipulate the graphic's window.
Parameters
classname [in] Class name for the window. Typically, a derived class obtains a window class name from a call to the AfxRegisterWndClass function.
size [in] Initial size for the window.
parent [in] Parent window or NULL if the graphic does not have an immediate parent. If a parent window is specified, the graphic is created as a child window (WS_CHILD). Otherwise the graphic is created as a popup window (WS_POPUP) and is assigned the main window as a parent.
id Unique ID for this graphic element. Typically, the ID is used to identify the graphic element in a callback.
Returns
true if the window is created successfully.
References m_id, and m_parent.
Referenced by MeaRuler::Create(), MeaCrossHair::Create(), MeaCircle::Create(), MeaLine::Create(), and MeaRectangle::Create().
Hide()
void MeaGraphic::Hide () virtual
Hides the graphic.
Call the Create() method prior to calling this method for the first time.
Reimplemented in MeaCircle, MeaLine, and MeaRectangle.
References m_visible.
Referenced by MeaAngleTool::DisableCrosshairs(), MeaCircleTool::DisableCrosshairs(), MeaLineTool::DisableCrosshairs(), MeaPointTool::DisableCrosshairs(), MeaRectTool::DisableCrosshairs(), MeaCircle::Hide(), MeaLine::Hide(), and MeaRectangle::Hide().
SetAbove()
void MeaGraphic::SetAbove (const CWnd * winBelow) inline
Changes the z-order of the graphic window so that it if above the specified window.
Call the Create() method prior to calling this method for the first time.
Parameters
winBelow [in] Window to place below this class's window
Referenced by MeaAngleTool::Create(), MeaCircleTool::Create(), MeaLineTool::Create(), and MeaRectTool::Create().
Show()
void MeaGraphic::Show () virtual
Displays the graphic.
Call the Create() method prior to calling this method for the first time.
References m_visible.
Referenced by MeaAngleTool::Enable(), MeaCircleTool::Enable(), MeaLineTool::Enable(), MeaOriginTool::Enable(), MeaRectTool::Enable(), MeaWindowTool::Enable(), MeaAngleTool::EnableCrosshairs(), MeaCircleTool::EnableCrosshairs(), MeaLineTool::EnableCrosshairs(), MeaPointTool::EnableCrosshairs(), MeaRectTool::EnableCrosshairs(), MeaCircle::OnHPTimer(), MeaLine::OnHPTimer(), MeaRectangle::OnHPTimer(), MeaRulerPrefs::OnInitDialog(), MeaToolsPrefs::OnInitDialog(), MeaCircle::SetPosition(), and MeaLine::SetPosition().
The documentation for this class was generated from the following files:
Graphic.h
Graphic.cpp
Copyright 2011 C Thing Software