Meazure: MeaRulerSlider Class Reference
MeaRulerSlider Class Reference
Slider control on a ruler background.
#include <RulerSlider.h>
Public Member Functions
MeaRulerSlider ()
Constructs a ruler slider control.
virtual ~MeaRulerSlider ()
Destroys a ruler slider control.
int GetSliderPos ()
Returns the position value of the slider.
void SetSliderPos (int pos)
Set the position of the slider.
virtual BOOL Create (DWORD dwStyle, const RECT &rect, CWnd *pParentWnd, UINT nID) override
Creates the window for the ruler slider control.
virtual void PreSubclassWindow () override
Called right before the base class control is subclassed.
Protected Member Functions
void Init (const CRect &rect)
Initializes the slider.
void DrawCalipers (CDC *pDC)
Draws the calipers that form the thumb control for the slider.
afx_msg void OnLButtonDown (UINT nFlags, CPoint point)
Called when the left mouse button is pressed.
afx_msg void OnLButtonUp (UINT nFlags, CPoint point)
Called when the left mouse button is released.
afx_msg void OnMouseMove (UINT nFlags, CPoint point)
Called when the mouse is moved over the slider.
afx_msg void OnPaint ()
Called to repaint the slider control.
afx_msg BOOL OnEraseBkgnd (CDC *pDC)
Called to clear the control's background.
afx_msg void OnSize (UINT nType, int cx, int cy)
Called when the size of the control's window is changed.
afx_msg void OnEnable (BOOL bEnable)
Called when the control is enabled or disabled so that it can redraw itself to reflect the new state.
Private Member Functions
bool IsHot (int pos) const
Indicates whether the specified slider position is in the draggable area.
Private Attributes
bool m_vertical
Indicates if the slider is oriented vertically.
bool m_captured
Indicates if the slider thumb control captured.
bool m_sliderActive
Indicates the slider can be dragged.
CFont m_posFont
Font used for displaying the current slider position.
CPen m_activePen
Pen to draw the control when enabled.
CPen m_inactivePen
Pen to draw the control when disabled.
CBrush m_activeBrush
Brush to paint the control when enabled.
CBrush m_inactiveBrush
Brush to paint the control when disabled.
CRect m_sliderRect
Window rectangle for the control.
int m_sliderPos
Current slider position.
Static Private Attributes
static constexpr int kHotSpotOffset { 4 }
Offset around the caliper that is draggable.
static constexpr int kTickPosition { 10 }
Relative position for the ruler tick marks.
static constexpr int kTickFactor { 4 }
The tick height is the thickness of the window divided by this factor.
Detailed Description
Slider control on a ruler background.
Dynamic readout of pixel position is provided while the slider is dragged.
Constructor & Destructor Documentation
MeaRulerSlider()
MeaRulerSlider::MeaRulerSlider ()
Constructs a ruler slider control.
Before the control can be used, the Create method must be called.
Member Function Documentation
Create()
BOOL MeaRulerSlider::Create (DWORD dwStyle, const RECT & rect, CWnd * pParentWnd, UINT nID) override virtual
Creates the window for the ruler slider control.
Parameters
dwStyle [in] Style for the control's window as defined by CProgressCtrl.
rect [in] Bounding retangle for the control, in pixels.
pParentWnd [in] Parent window for the control.
nID [in] ID for the control.
Returns
TRUE if the control was created successfully.
References Init().
DrawCalipers()
void MeaRulerSlider::DrawCalipers (CDC * pDC) protected
Draws the calipers that form the thumb control for the slider.
Parameters
pDC [in] Device context into which the calipers are drawn.
References kTickFactor, m_activeBrush, m_inactiveBrush, m_sliderRect, and m_vertical.
Referenced by OnPaint().
GetSliderPos()
int MeaRulerSlider::GetSliderPos ()
Returns the position value of the slider.
Returns
The slider's current position.
References m_sliderPos.
Referenced by OnMouseMove().
Init()
void MeaRulerSlider::Init (const CRect & rect) protected
Initializes the slider.
Parameters
rect [in] Client rectangle for the slider.
References m_sliderPos, m_sliderRect, and m_vertical.
Referenced by Create(), OnSize(), and PreSubclassWindow().
IsHot()
bool MeaRulerSlider::IsHot (int pos) const private
Indicates whether the specified slider position is in the draggable area.
Returns
true if the position is in the draggable area for the slider.
References kHotSpotOffset, and m_sliderPos.
Referenced by OnLButtonDown(), and OnMouseMove().
OnEnable()
void MeaRulerSlider::OnEnable (BOOL bEnable) protected
Called when the control is enabled or disabled so that it can redraw itself to reflect the new state.
Parameters
bEnable [in] Indicates if the control has been enabled or disabled.
OnEraseBkgnd()
BOOL MeaRulerSlider::OnEraseBkgnd (CDC * pDC) protected
Called to clear the control's background.
Parameters
pDC [in] Device context into which to draw the background.
Returns
Always returns TRUE.
OnLButtonDown()
void MeaRulerSlider::OnLButtonDown (UINT nFlags, CPoint point) protected
Called when the left mouse button is pressed.
Captures the pointer for subsequent dragging of the slider.
Parameters
nFlags [in] Modifier flags in effect.
point [in] Location of the pointer.
References IsHot(), m_captured, m_sliderActive, and m_vertical.
OnLButtonUp()
void MeaRulerSlider::OnLButtonUp (UINT nFlags, CPoint point) protected
Called when the left mouse button is released.
Releases the capture of the pointer.
Parameters
nFlags [in] Modifier flags in effect.
point [in] Location of the pointer.
References m_captured, and m_sliderActive.
OnMouseMove()
void MeaRulerSlider::OnMouseMove (UINT nFlags, CPoint point) protected
Called when the mouse is moved over the slider.
If the pointer is captured, the slider thumb control is dragged.
Parameters
nFlags [in] Modifier flags in effect.
point [in] Location of the pointer.
References GetSliderPos(), IsHot(), m_captured, m_sliderActive, m_sliderPos, m_vertical, and MeaCaliperPositionMsg.
OnSize()
void MeaRulerSlider::OnSize (UINT nType, int cx, int cy) protected
Called when the size of the control's window is changed.
The control resets its position accordingly.
Parameters
nType [in] Indicates the type of resizing.
cx [in] New width, in pixels.
cy [in] New height, in pixels.
References Init().
PreSubclassWindow()
void MeaRulerSlider::PreSubclassWindow () override virtual
Called right before the base class control is subclassed.
This method is used to perform intial setup of the slider.
References Init().
SetSliderPos()
void MeaRulerSlider::SetSliderPos (int pos)
Set the position of the slider.
Parameters
pos [in] Position for the slider.
References m_sliderPos.
Referenced by MeaCalibrationPrefs::UpdateSlider().
The documentation for this class was generated from the following files:
RulerSlider.h
RulerSlider.cpp
Copyright 2011 C Thing Software