Meazure: MeaProfileMgr Class Reference
MeaProfileMgr Class Reference
Manages the saving and loading of profile files.
#include <ProfileMgr.h>
Public Member Functions
CFileDialog * CreateSaveDialog ()
Creates the profile file save dialog.
CFileDialog * CreateLoadDialog ()
Creates the profile file open dialog.
void Load ()
Displays the file open dialog and loads the selected profile file.
void Load (LPCTSTR pathname) const
Loads the specified profile file.
void Save ()
Displays the file save dialog and saves the selected profile file.
void SaveProfile (MeaProfile &profile) const
Persists the state of the profile file manager.
void LoadProfile (MeaProfile &profile)
Restores the state of the profile file manager.
void MasterReset ()
Resets the profile manager to its default state.
Public Member Functions inherited from MeaSingleton_T< MeaProfileMgr >
virtual ~MeaSingleton_T ()
Destructor for the Singleton.
Static Public Member Functions
static bool IsProfileFile (LPCTSTR filename)
Tests whether the specified filename represents a profile file.
Static Public Member Functions inherited from MeaSingleton_T< MeaProfileMgr >
static MeaProfileMgr & Instance ()
The first time this method is called, a instance of the Singleton object is created and returned.
static void DestroyInstance ()
When the Singleton object is no longer needed, it must be destroyed using this method.
static bool IsDestroyed ()
Indicates whether the Singleton object has been destroyed.
Private Member Functions
MeaProfileMgr (const MeaProfileMgr &)
Managers are singletons.
MeaProfileMgr & operator= (const MeaProfileMgr &)
Purposely undefined.
Private Attributes
CFileDialog * m_saveDialog
Profile file save dialog.
CFileDialog * m_loadDialog
Profile file open dialog.
CString m_saveDlgTitle
File save dialog title.
CString m_loadDlgTitle
File open dialog title.
CString m_initialDir
Initial directory for file dialogs.
Static Private Attributes
static LPCTSTR m_ext = _T("mea")
Profile file suffix.
static LPCTSTR m_filter = _T("Meazure Profiles (*.mea)|*.mea|All Files (*.*)|*.*||")
File dialog filter string.
Friends
class MeaSingleton_T< MeaProfileMgr >
Additional Inherited Members
Protected Member Functions inherited from MeaSingleton_T< MeaProfileMgr >
MeaSingleton_T ()
Constructs a Singleton object instance.
Detailed Description
Manages the saving and loading of profile files.
A profile file records the state of all tools and other aspects of the measurement environment.
Constructor & Destructor Documentation
MeaProfileMgr()
MeaProfileMgr::MeaProfileMgr (const MeaProfileMgr &) private
Managers are singletons.
Purposely undefined.
Member Function Documentation
CreateLoadDialog()
CFileDialog * MeaProfileMgr::CreateLoadDialog ()
Creates the profile file open dialog.
Returns
File open dialog.
References m_ext, m_filter, m_initialDir, m_loadDialog, and m_loadDlgTitle.
Referenced by Load(), and CChildView::OnPreferences().
CreateSaveDialog()
CFileDialog * MeaProfileMgr::CreateSaveDialog ()
Creates the profile file save dialog.
Returns
File save dialog.
References m_ext, m_filter, m_initialDir, m_saveDialog, and m_saveDlgTitle.
Referenced by Save().
IsProfileFile()
bool MeaProfileMgr::IsProfileFile (LPCTSTR filename) static
Tests whether the specified filename represents a profile file.
Parameters
filename [in] File to test
Returns
true if the specified file is a profile file.
References m_ext.
Referenced by CChildView::LoadStartupFile().
Load()
void MeaProfileMgr::Load (LPCTSTR pathname) const
Loads the specified profile file.
Parameters
pathname [in] Profile pathname.
References LoadProfile(), and MeaFileProfile::ProfRead.
LoadProfile()
void MeaProfileMgr::LoadProfile (MeaProfile & profile)
Restores the state of the profile file manager.
Parameters
profile [in] Profile object from which the manager should restore its state.
References m_initialDir, MeaProfile::ReadStr(), and MeaProfile::UserInitiated().
Referenced by Load(), and CChildView::LoadProfile().
SaveProfile()
void MeaProfileMgr::SaveProfile (MeaProfile & profile) const
Persists the state of the profile file manager.
Parameters
profile [in] Profile object into which the manager should persist its state.
References m_initialDir, MeaProfile::UserInitiated(), and MeaProfile::WriteStr().
Referenced by Save(), and CChildView::SaveProfile().
Member Data Documentation
m_ext
LPCTSTR MeaProfileMgr::m_ext = _T("mea") static private
Profile file suffix.
Managers are singletons.
Referenced by CreateLoadDialog(), CreateSaveDialog(), and IsProfileFile().
The documentation for this class was generated from the following files:
ProfileMgr.h
ProfileMgr.cpp
Copyright 2011 C Thing Software