Meazure: MeaPositionDesktop Class Reference
MeaPositionDesktop Class Reference
Represents all information of interest about the system at the time a position is recorded.
#include <PositionDesktop.h>
Public Member Functions
MeaPositionDesktop (const MeaUnitsProvider &unitsProvider, const MeaScreenProvider &screenProvider)
Constructs a desktop information object.
MeaPositionDesktop (PCTSTR guidStr, const MeaUnitsProvider &unitsProvider, const MeaScreenProvider &screenProvider)
Constructs a desktop information object with the specified unique ID.
MeaPositionDesktop (const MeaPositionDesktop &desktop)
Constructs a desktop information object as a copy of the specified object.
~MeaPositionDesktop ()
Destroys a desktop information object.
MeaPositionDesktop & operator= (const MeaPositionDesktop &desktop)
Assigns the specified desktop information object to this object.
MeaLinearUnits * GetLinearUnits ()
Returns the linear units in effect when this object was created.
const MeaLinearUnits * GetLinearUnits () const
Returns the linear units in effect when this object was created.
MeaAngularUnits * GetAngularUnits ()
Returns the angular units in effect when this object was created.
const MeaAngularUnits * GetAngularUnits () const
Returns the angular units in effect when this object was created.
bool IsInvertY () const
Indicates whether the y-axis was inverted when this object was created.
const MeaFPoint & GetOrigin () const
Returns the location of the origin when this object was created.
const MeaGUID & GetId () const
Returns the unique ID for this object.
void SetId (PCTSTR guidStr)
Sets a unique ID for this object.
CString GetCustomName () const
Returns the name for custom units.
CString GetCustomAbbrev () const
Returns the abbreviation for custom units.
CString GetCustomBasisStr () const
Returns the units basis for custom units (i.e.
double GetCustomFactor () const
Returns the conversion factor for custom units.
MeaUnits::DisplayPrecisions GetCustomPrecisions () const
Returns the set of display precisions for custom units.
void Load (const MeaXMLNode *desktopNode)
Loads desktop elements of the log file.
void Save (MeaXMLWriter &writer) const
Saves the desktop information.
bool operator== (const MeaPositionDesktop &desktop) const
Compares the specified desktop information object with this to determine equality.
bool operator!= (const MeaPositionDesktop &desktop) const
Compares the specified desktop information object with this to determine inequality.
Private Types
typedef std::list< MeaPositionScreen > PositionScreenList
List of all display screens attached to the system.
Private Member Functions
MeaPositionDesktop & Copy (const MeaPositionDesktop &desktop)
Copies the specified desktop information object into this object.
void SetLinearUnits (const CString &unitsStr)
Sets the linear units for the object based on the specified units name.
void SetAngularUnits (const CString &unitsStr)
Sets the angular units for the object based on the specified units name.
void LoadCustomPrecisions (const MeaXMLNode *displayPrecisionNode)
Loads the display precisions values for the custom units.
void SaveCustomPrecisions (MeaXMLWriter &writer) const
Saves the display precisions for custom units.
Private Attributes
const MeaUnitsProvider * m_unitsProvider
Units information object.
MeaGUID m_id
ID for use by a Position object to reference this object.
MeaFPoint m_origin
Origin in the units that were in effect when the desktop object was created.
bool m_invertY
Is origin inverted.
MeaFSize m_size
Desktop size in units in effect when desktop object created.
MeaLinearUnits * m_linearUnits
Current linear units.
MeaAngularUnits * m_angularUnits
Current angle units.
PositionScreenList m_screens
List of display screens.
CString m_customName
Custom units name.
CString m_customAbbrev
Custom units abbreviation.
CString m_customBasisStr
Custom scale factor basis.
double m_customFactor
Custom scale factor.
MeaUnits::DisplayPrecisions m_customPrecisions
Custom display precisions.
Detailed Description
Represents all information of interest about the system at the time a position is recorded.
This includes the list of all display screens attached to the system. The desktop information is saved in the position log file. To minimize repetition, positions reference the desktop information in effect when they were recorded. This means that one desktop information section can serve many positions.
Constructor & Destructor Documentation
MeaPositionDesktop() [1/3]
MeaPositionDesktop::MeaPositionDesktop (const MeaUnitsProvider & unitsProvider, const MeaScreenProvider & screenProvider)
Constructs a desktop information object.
Parameters
unitsProvider [in] Units information and conversion provider
screenProvider [in] Screen information provider
MeaPositionDesktop() [2/3]
MeaPositionDesktop::MeaPositionDesktop (PCTSTR guidStr, const MeaUnitsProvider & unitsProvider, const MeaScreenProvider & screenProvider) explicit
Constructs a desktop information object with the specified unique ID.
Parameters
guidStr [in] GUID ID for the desktop information object.
unitsProvider [in] Units information and conversion provider
screenProvider [in] Screen information provider
References MeaScreenProvider::AtEnd(), MeaCustomUnits::GetAbbrev(), MeaUnits::GetDefaultPrecisions(), MeaCustomUnits::GetName(), MeaCustomUnits::GetScaleBasisStr(), MeaCustomUnits::GetScaleFactor(), MeaScreenProvider::GetScreenIter(), MeaLinearUnits::GetUnitsId(), MeaScreenProvider::GetVirtualRect(), MeaUnitsProvider::GetWidthHeight(), m_customAbbrev, m_customBasisStr, m_customFactor, m_customName, m_customPrecisions, m_linearUnits, m_screens, m_size, and MeaCustomId.
MeaPositionDesktop() [3/3]
MeaPositionDesktop::MeaPositionDesktop (const MeaPositionDesktop & desktop) inline
Constructs a desktop information object as a copy of the specified object.
Parameters
desktop [in] Desktop information object to copy.
References Copy().
Member Function Documentation
Copy()
MeaPositionDesktop & MeaPositionDesktop::Copy (const MeaPositionDesktop & desktop) inline private
Copies the specified desktop information object into this object.
Parameters
desktop [in] Desktop information object to copy.
Returns
This object.
References m_angularUnits, m_customAbbrev, m_customBasisStr, m_customFactor, m_customName, m_customPrecisions, m_id, m_invertY, m_linearUnits, m_origin, m_screens, m_size, and m_unitsProvider.
Referenced by MeaPositionDesktop(), and operator=().
GetAngularUnits() [1/2]
MeaAngularUnits * MeaPositionDesktop::GetAngularUnits () inline
Returns the angular units in effect when this object was created.
Returns
Angular units object in effect when this object was created.
References m_angularUnits.
Referenced by MeaPositionLogMgr::ShowPosition().
GetAngularUnits() [2/2]
const MeaAngularUnits * MeaPositionDesktop::GetAngularUnits () const inline
Returns the angular units in effect when this object was created.
Returns
Angular units object in effect when this object was created.
References m_angularUnits.
GetCustomAbbrev()
CString MeaPositionDesktop::GetCustomAbbrev () const inline
Returns the abbreviation for custom units.
Returns
Abbreviation for custom units.
References m_customAbbrev.
Referenced by MeaPositionLogMgr::ShowPosition().
GetCustomBasisStr()
CString MeaPositionDesktop::GetCustomBasisStr () const inline
Returns the units basis for custom units (i.e.
pixels, inches or centimeters).
Returns
The units basis for custom units.
References m_customBasisStr.
Referenced by MeaPositionLogMgr::ShowPosition().
GetCustomFactor()
double MeaPositionDesktop::GetCustomFactor () const inline
Returns the conversion factor for custom units.
Returns
Conversion factor.
References m_customFactor.
Referenced by MeaPositionLogMgr::ShowPosition().
GetCustomName()
CString MeaPositionDesktop::GetCustomName () const inline
Returns the name for custom units.
Returns
Name for custom units.
References m_customName.
Referenced by MeaPositionLogMgr::ShowPosition().
GetCustomPrecisions()
MeaUnits::DisplayPrecisions MeaPositionDesktop::GetCustomPrecisions () const inline
Returns the set of display precisions for custom units.
Returns
Set of custom units display precisions.
References m_customPrecisions.
Referenced by MeaPositionLogMgr::ShowPosition().
GetId()
const MeaGUID & MeaPositionDesktop::GetId () const inline
Returns the unique ID for this object.
Returns
GUID ID for this object.
References m_id.
Referenced by MeaPositionLogMgr::ProcessDesktopNode(), and MeaPositionLogMgr::RecordDesktopInfo().
GetLinearUnits() [1/2]
MeaLinearUnits * MeaPositionDesktop::GetLinearUnits () inline
Returns the linear units in effect when this object was created.
Returns
Linear units object in effect when this object was created.
References m_linearUnits.
Referenced by MeaPositionLogMgr::ShowPosition().
GetLinearUnits() [2/2]
const MeaLinearUnits * MeaPositionDesktop::GetLinearUnits () const inline
Returns the linear units in effect when this object was created.
Returns
Linear units object in effect when this object was created.
References m_linearUnits.
GetOrigin()
const MeaFPoint & MeaPositionDesktop::GetOrigin () const inline
Returns the location of the origin when this object was created.
Returns
The location of the origin when this object was created.
References m_origin.
Referenced by MeaPositionLogMgr::ShowPosition().
IsInvertY()
bool MeaPositionDesktop::IsInvertY () const inline
Indicates whether the y-axis was inverted when this object was created.
Returns
true if the y-axis was inverted when this object was created.
References m_invertY.
Referenced by MeaPositionLogMgr::ShowPosition().
Load()
void MeaPositionDesktop::Load (const MeaXMLNode * desktopNode)
Loads desktop elements of the log file.
Parameters
desktopNode [in] Desktop node in the DOM.
References MeaXMLNode::AtEnd(), MeaFSize::cx, MeaFSize::cy, MeaXMLNode::Element, MeaXMLNode::GetAttributes(), MeaXMLNode::GetChildIter(), MeaXMLNode::GetData(), MeaXMLNode::GetType(), MeaXMLAttributes::GetValueBool(), MeaXMLAttributes::GetValueDbl(), MeaXMLAttributes::GetValueStr(), MeaPositionScreen::Load(), LoadCustomPrecisions(), m_customAbbrev, m_customBasisStr, m_customFactor, m_customName, m_invertY, m_origin, m_screens, m_size, SetAngularUnits(), SetLinearUnits(), MeaFPoint::x, and MeaFPoint::y.
Referenced by MeaPositionLogMgr::ProcessDesktopNode().
LoadCustomPrecisions()
void MeaPositionDesktop::LoadCustomPrecisions (const MeaXMLNode * displayPrecisionNode) private
Loads the display precisions values for the custom units.
Parameters
displayPrecisionNode [in] displayPrecisions element in the DOM.
References MeaXMLNode::AtEnd(), MeaXMLNode::GetAttributes(), MeaXMLNode::GetChildIter(), MeaXMLNode::GetData(), MeaUnits::GetDisplayPrecisionNames(), MeaUnits::GetDisplayPrecisions(), MeaXMLAttributes::GetValueInt(), MeaXMLAttributes::GetValueStr(), m_customPrecisions, and m_linearUnits.
Referenced by Load().
operator!=()
bool MeaPositionDesktop::operator!= (const MeaPositionDesktop & desktop) const inline
Compares the specified desktop information object with this to determine inequality.
Parameters
desktop [in] Desktop information object to compare with this.
Returns
true if the specified object and this are not equal.
operator=()
MeaPositionDesktop & MeaPositionDesktop::operator= (const MeaPositionDesktop & desktop) inline
Assigns the specified desktop information object to this object.
Parameters
desktop [in] Desktop information object to be assigned.
Returns
This object.
References Copy().
operator==()
bool MeaPositionDesktop::operator== (const MeaPositionDesktop & desktop) const inline
Compares the specified desktop information object with this to determine equality.
Parameters
desktop [in] Desktop information object to compare with this.
Returns
true if the specified object and this are equal.
References MeaFSize::cx, MeaFSize::cy, MeaNumericUtils::IsEqualF(), m_angularUnits, m_customAbbrev, m_customBasisStr, m_customFactor, m_customName, m_customPrecisions, m_invertY, m_linearUnits, m_origin, m_screens, m_size, MeaFPoint::x, and MeaFPoint::y.
Save()
void MeaPositionDesktop::Save (MeaXMLWriter & writer) const
Saves the desktop information.
Parameters
writer [in] Provides ability to write a position to the log.
References MeaXMLWriter::AddAttribute(), MeaFSize::cx, MeaFSize::cy, MeaXMLWriter::EndElement(), MeaLinearUnits::GetUnitsId(), MeaUnits::GetUnitsStr(), m_angularUnits, m_customAbbrev, m_customBasisStr, m_customFactor, m_customName, m_id, m_invertY, m_linearUnits, m_origin, m_screens, m_size, MeaCustomId, SaveCustomPrecisions(), MeaXMLWriter::StartElement(), MeaGUID::ToString(), MeaFPoint::x, and MeaFPoint::y.
SaveCustomPrecisions()
void MeaPositionDesktop::SaveCustomPrecisions (MeaXMLWriter & writer) const private
Saves the display precisions for custom units.
Parameters
writer [in] Provides ability to write a position to the log.
References MeaXMLWriter::AddAttribute(), MeaXMLWriter::EndElement(), MeaUnits::GetDisplayPrecisionNames(), MeaUnits::GetUnitsStr(), m_customPrecisions, m_linearUnits, and MeaXMLWriter::StartElement().
Referenced by Save().
SetAngularUnits()
void MeaPositionDesktop::SetAngularUnits (const CString & unitsStr) private
Sets the angular units for the object based on the specified units name.
Parameters
unitsStr [in] Angular units name.
References MeaUnitsProvider::GetAngularUnits(), m_angularUnits, and m_unitsProvider.
Referenced by Load().
SetId()
void MeaPositionDesktop::SetId (PCTSTR guidStr) inline
Sets a unique ID for this object.
Parameters
guidStr [in] GUID ID to set for this object.
References m_id.
SetLinearUnits()
void MeaPositionDesktop::SetLinearUnits (const CString & unitsStr) private
Sets the linear units for the object based on the specified units name.
Parameters
unitsStr [in] Linear units name.
References MeaUnitsProvider::GetLinearUnits(), m_linearUnits, and m_unitsProvider.
Referenced by Load().
The documentation for this class was generated from the following files:
PositionDesktop.h
PositionDesktop.cpp
Copyright 2011 C Thing Software