Meazure: CChildView Class Reference
CChildView Class Reference
The view class for the application.
#include <ChildView.h>
Public Member Functions
CChildView ()
Constructs the view.
virtual ~CChildView ()
Destroys the view.
void OnMouseHook (WPARAM wParam, LPARAM lParam)
A number of tools (e.g.
void SaveProfile (MeaProfile &profile)
Persists the state of the view to the specified profile object.
void LoadProfile (MeaProfile &profile)
Restores the state of the view from the specified profile object.
void MasterReset ()
Called when the application master reset is initiated.
void LoadStartupFile (const CString &cmdLineFile) const
This method handles the processing of any files specified on the command-line or specified in preferences.
void InitView ()
Called at startup right before the app windows are shown.
virtual BOOL PreCreateWindow (CREATESTRUCT &cs)
Called before the window is created.
Static Public Attributes
static const bool kDefToolbarVisible = true
Indicates if the toolbar is visible by default.
static const bool kDefStatusbarVisible = true
Indicates if the status bar is visible by default.
static const bool kDefToolInfoVisible = true
Indicates if the measurement information section is visible by default.
static const bool kDefScreenInfoVisible = true
Indicates if the screen information section is visible by default.
static const bool kDefMagnifierVisible = true
Indicates if the magnifier is visible by default.
Protected Member Functions
afx_msg void OnUnits (UINT nID)
Called when new units are selected from the Units menu.
afx_msg void OnAngles (UINT nID)
Called when the degrees or radians units are selected.
afx_msg void OnRadioTool (UINT nID)
Called when a radio tool is selected.
afx_msg void OnColorFmt (UINT nID)
Called when a new color display format is requested.
afx_msg LRESULT OnDataChange (WPARAM wParam, LPARAM lParam)
Called when data is entered into a field in the data display or a spin button is used.
afx_msg LRESULT OnPrefsApply (WPARAM wParam, LPARAM lParam)
Called when the Apply button is pressed on the preferences dialog.
afx_msg LRESULT OnShowCalPrefs (WPARAM wParam, LPARAM lParam)
Called when the show calibration preferences message is received.
afx_msg LRESULT OnGetPosition (WPARAM wParam, LPARAM lParam)
Called when the magnifier wants the current position.
afx_msg LRESULT OnHPTimer (WPARAM wParam, LPARAM lParam)
Called when the region snapshot timer expires.
afx_msg int OnCreate (LPCREATESTRUCT lpCreateStruct)
Creates the view and the data display.
afx_msg void OnUpdateUnits (CCmdUI *pCmdUI)
Updates the radio button state on the Units menu right before the menu is displayed.
afx_msg void OnUpdateAngles (CCmdUI *pCmdUI)
Updates the radio button state on the Units menu right before the menu is displayed.
afx_msg void OnUpdateRadioTool (CCmdUI *pCmdUI)
Called right before the Tool menu is displayed to update its radio state.
afx_msg void OnDestroy ()
Disables all tools including the magnifier and destroys the window.
afx_msg void OnEditCopy ()
Wires the application Edit menu Copy item into the data display text field that has the keyboard focus so that its contents are copied to the clipboard.
afx_msg void OnEditCut ()
Wires the application Edit menu Cut item into the data display text field that has the keyboard focus so that its contents are cut into the clipboard.
afx_msg void OnEditPaste ()
Wires the application Edit menu Paste item into the data display text field that has the keyboard focus so that the clipboard contents are pasted into the field.
afx_msg void OnEditClear ()
Wires the application Edit menu Delete item into the data display text field that has the keyboard focus so that its contents are deleted.
afx_msg void OnUpdateEditCopy (CCmdUI *pCmdUI)
Updates the application Edit menu Copy item so that its state reflects the Copy state of the data display text field that has the keyboard focus.
afx_msg void OnUpdateEditCut (CCmdUI *pCmdUI)
Updates the application Edit menu Cut item so that its state reflects the Cut state of the data display text field that has the keyboard focus.
afx_msg void OnUpdateEditPaste (CCmdUI *pCmdUI)
Updates the application Edit menu Paste item so that its state reflects the Paste state of the data display text field that has the keyboard focus.
afx_msg void OnUpdateEditClear (CCmdUI *pCmdUI)
Updates the application Edit menu Delete item so that its state reflects the Delete state of the data display text field that has the keyboard focus.
afx_msg void OnInvertY ()
Called when the Invert Y menu item is selected.
afx_msg void OnUpdateInvertY (CCmdUI *pCmdUI)
Updates the state of the Invert Y menu item before it is displayed.
afx_msg void OnOrigin ()
Called when the Set Origin menu item is selected.
afx_msg void OnResetOrigin ()
Called to reset the origin to its default location (0, 0).
afx_msg void OnRuler ()
Called when the ruler menu item is selected to toggle the display of the screen measurement rulers.
afx_msg void OnUpdateRuler (CCmdUI *pCmdUI)
Updates the state of the ruler menu item before it is displayed.
afx_msg void OnPreferences ()
Called when the Preferences menu item is selected to bring up the preferences dialog.
afx_msg void OnMagnifier ()
Called when the magnifier menu item is selected to toggle between showing and hiding the magnifier.
afx_msg void OnUpdateMagnifier (CCmdUI *pCmdUI)
Updates the state of the magnifier item on the view menu before it is displayed.
afx_msg void OnShowMagGrid ()
Called when the magnifier grid menu item is selected to toggle the display of the pixel grid on the magnifier window.
afx_msg void OnUpdateShowMagGrid (CCmdUI *pCmdUI)
Updates the state of the magnifier grid menu item before it is displayed.
afx_msg void OnScreenInfo ()
Called when the Screen Info view menu item is selected.
afx_msg void OnUpdateScreenInfo (CCmdUI *pCmdUI)
Updates the state of the Screen Info view menu item before it is displayed.
afx_msg void OnUpdateColorFmt (CCmdUI *pCmdUI)
Updates the state of the pixel color format menu item before it is displayed.
afx_msg void OnRunState ()
Called to toggle between paused and running states on the magnifier window.
afx_msg void OnUpdateRunState (CCmdUI *pCmdUI)
Updates the state of the pause button on the magnifier window and on the menu.
afx_msg void OnScreenGrid ()
Called to toggle the display of the screen grid.
afx_msg void OnUpdateScreenGrid (CCmdUI *pCmdUI)
Updates the state of the screen grid menu item before it is displayed.
afx_msg void OnScreenGridSpacing ()
Called when the screen grid spacing menu item is selected.
afx_msg void OnSaveProfile ()
Saves the current application configuration to the user selected profile file.
afx_msg void OnLoadProfile ()
Loads the user specified profile file to set the application configuration.
afx_msg void OnCopyRegion ()
Enabled when the Rectangle, Circle or Window tool is selected.
afx_msg void OnUpdateCopyRegion (CCmdUI *pCmdUI)
If a tool reports that it has a region that can be copied, the Copy Region menu item is enabled.
afx_msg void OnToolInfo ()
Called when the Tool Info view menu item is selected.
afx_msg void OnUpdateToolInfo (CCmdUI *pCmdUI)
Updates the state of the Tool Info menu item before it is displayed.
afx_msg void OnCollapse ()
Called to toggle the application window between a collapsed presentation and an expanded presentation.
afx_msg void OnUpdateCollapse (CCmdUI *pCmdUI)
Updates the state of the collapse menu item to reflect whether the app is currently in a collapsed presentation.
afx_msg void OnFindCrosshair ()
Called to flash the current radio tool's crosshair(s).
afx_msg void OnUpdateFindCrosshair (CCmdUI *pCmdUI)
Updates the flash menu item to reflect whether the tool has crosshairs that can be flashed.
afx_msg void OnRecordPosition ()
Called to record the current radio tool's position.
afx_msg void OnDeletePositions ()
Called to delete all recorded positions.
afx_msg void OnUpdateDeletePositions (CCmdUI *pCmdUI)
Updates the state of the delete positions menu item to reflect whether there are any positions that can be deleted.
afx_msg void OnLoadPositions ()
Called to load a position log file.
afx_msg void OnSavePositions ()
Called to save a position log file.
afx_msg void OnSavePositionsAs ()
Called to save a position log file with a new pathname.
afx_msg void OnUpdateSavePositions (CCmdUI *pCmdUI)
Called to update the state of the position save menu items.
afx_msg void OnManagePositions ()
Called to bring up the position management dialog.
afx_msg void OnZoomIn ()
Called to increase magnification on the magnifier window.
afx_msg void OnUpdateZoomIn (CCmdUI *pCmdUI)
Updates the state of the Zoom In menu item before it is displayed.
afx_msg void OnZoomOut ()
Called to decrease magnification on the magnifier window.
afx_msg void OnUpdateZoomOut (CCmdUI *pCmdUI)
Updates the state of the Zoom Out menu item before it is displayed.
afx_msg void OnHideCrosshairs ()
Called to toggle between showing and hiding the tool crosshair(s).
afx_msg void OnUpdateHideCrosshairs (CCmdUI *pCmdUI)
Updates the state of the Hide Crosshairs menu item to reflect whether the tool crosshair(s) are shown or hidden.
afx_msg void OnDefineCustomUnits ()
Called when the user selects the Define Custom units menu item.
afx_msg void OnUpdateCustomUnits (CCmdUI *pCmdUI)
Updates the custom units menu item to show the name of the custom units, if custom units have been defined.
afx_msg void OnCustomUnits ()
If custom units have been defined, this method is called to select them for use.
Private Member Functions
int GetMenuWidth ()
Determines the desired width of the application menu.
void ApplyPreferences (int prefPage=MeaPreferences::kAllPages)
Applies the preferences currently specified on the Preferences dialog.
void CheckMargins ()
If no sections are shown, nuke the app margins.
bool IsCollapsed () const
Determines whether all sections of the display are hidden.
bool IsToolbarVisible () const
Indicates whether the toolbar is being shown.
bool IsStatusbarVisible () const
Indicates whether the status bar is being shown.
void ViewToolInfo (bool enable)
Displays or hides the measurement data section.
void ViewScreenInfo (bool enable)
Displays or hides the screen information section.
void ViewMagnifier (bool enable)
Displays or hides the magnifier section.
Private Attributes
CSize m_margin
Vertical and horizontal margins around major sections.
bool m_enabled
Used in determining margins when the app is collapsed.
bool m_profileMagnifierEnabled
Indicates if the stored user preference is to show the magnifier window.
bool m_profileScreenEnabled
Indicates if the stored user preference is to show the screen information section.
bool m_profileRegionEnabled
Indicates if the stored user preference is to show the measurement data window.
MeaDataDisplay m_dataDisplay
Tool and screen measurement data display object.
MeaMagnifier m_magnifier
Screen capture and magnifier object.
MeaPreferences m_prefs
Application preferences.
CString m_startupProfile
Pathname for the startup profile, if any.
MeaTimer m_snapshotTimer
Timer used in copying a tool's region to the clipboard.
int m_adjustHeight
Adjustment used when computing the height of the application, in pixels.
bool m_expandToolbar
Indicates if the toolbar is displayed.
bool m_expandStatusbar
Indicates if the status bar is displayed.
bool m_expandMagnifier
Indicates if the magnifier is displayed.
bool m_expandScreenInfo
Indicates if the screen information section is displayed.
bool m_expandToolInfo
Indicates if the tool measurement section is displayed.
Detailed Description
The view class for the application.
There is only a single view in this app and it is owned directly by the application frame window.
Member Function Documentation
void CChildView::ApplyPreferences (int prefPage = MeaPreferences::kAllPages) [private]
Applies the preferences currently specified on the Preferences dialog.
Parameters:
prefPage [in] Index of preference page whose settings should be applied.
References MeaScreenMgr::AnyOSRes(), MeaDataWin::Arm(), MeaCalibrationPrefs::AutoRes, MeaToolMgr::ColorsChanged(), MeaColors::CrossHairBack, MeaColors::CrossHairBorder, MeaColors::CrossHairHilite, MeaColors::CrossHairOpacity, DataWinArming, MeaToolMgr::DisableTool(), MeaToolMgr::EnableTool(), MeaPrecisionPrefs::GetAngularPrecisions(), MeaUnitsMgr::GetCustomUnits(), MeaPrecisionPrefs::GetLinearPrecisions(), MeaUnitsMgr::GetLinearUnitsId(), MeaCustomUnitsPrefs::GetScaleFactor(), MeaCustomUnits::HaveCustomUnits(), MeaSingleton_T< MeaScreenMgr >::Instance(), MeaSingleton_T< MeaToolMgr >::Instance(), MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaPreferences::kAdvancedPage, MeaPreferences::kAllPages, MeaPreferences::kCalibrationPage, MeaPreferences::kCustomPage, MeaPreferences::kPrecisionPage, MeaPreferences::kRulerPage, MeaOriginTool::kToolName, MeaPreferences::kToolsPage, MeaColors::LineFore, MeaCustomUnitsPrefs::m_abbrev, MeaPreferences::m_advancedPrefs, MeaRulerPrefs::m_backColor, MeaToolsPrefs::m_backColor, MeaRulerPrefs::m_borderColor, MeaToolsPrefs::m_borderColor, MeaPreferences::m_calibrationPrefs, MeaPreferences::m_customPrefs, m_dataDisplay, MeaToolsPrefs::m_hiliteColor, MeaToolsPrefs::m_lineColor, MeaCustomUnitsPrefs::m_name, MeaRulerPrefs::m_opacity, MeaToolsPrefs::m_opacity, MeaToolsPrefs::m_originMarker, MeaPreferences::m_precisionPrefs, m_prefs, MeaCalibrationPrefs::Screen::m_res, MeaCalibrationPrefs::Screen::m_resMode, MeaCalibrationPrefs::Screen::m_resUnits, MeaPreferences::m_rulerPrefs, MeaCalibrationPrefs::m_screens, MeaToolsPrefs::m_showDataWin, MeaAdvancedPrefs::m_startupProfile, m_startupProfile, MeaPreferences::m_toolsPrefs, MeaCentimetersId, MeaCustomId, MeaDegreesId, MeaInchesId, MeaMillimetersId, MeaPicasId, MeaPixelsId, MeaPointsId, MeaRadiansId, MeaTwipsId, MeaColors::RulerBack, MeaColors::RulerBorder, MeaColors::RulerOpacity, MeaColors::Set(), MeaColors::SetA(), MeaCustomUnits::SetAbbrev(), MeaUnitsMgr::SetAngularDisplayPrecisions(), MeaScreenMgr::SetCalInInches(), MeaUnitsMgr::SetLinearDisplayPrecisions(), MeaUnitsMgr::SetLinearUnits(), MeaCustomUnits::SetName(), MeaCustomUnits::SetScaleBasis(), MeaCustomUnits::SetScaleFactor(), MeaScreenMgr::SetScreenRes(), MeaDataDisplay::ShowCalButton(), UnitsChanged, MeaToolMgr::UpdateTools(), and MeaCalibrationPrefs::UseInches.
Referenced by OnPreferences(), and OnPrefsApply().
void CChildView::CheckMargins () [private]
If no sections are shown, nuke the app margins.
Otherwise add app margins.
References MeaLayout::GetWindowHeight(), MeaMagnifier::IsEnabled(), MeaDataDisplay::IsEnabled(), m_adjustHeight, m_dataDisplay, m_enabled, m_magnifier, m_margin, MeaRegionSection, MeaScreenSection, and MeaLayout::SetWindowHeight().
Referenced by ViewMagnifier(), ViewScreenInfo(), and ViewToolInfo().
int CChildView::GetMenuWidth () [private]
Determines the desired width of the application menu.
Returns:
Pixel width to fit all menu items in one row.
Referenced by OnCreate().
void CChildView::InitView ()
Called at startup right before the app windows are shown.
Shows/hides the portions of the view according to the registry profile.
References m_profileMagnifierEnabled, m_profileRegionEnabled, m_profileScreenEnabled, OnMagnifier(), OnScreenInfo(), and OnToolInfo().
Referenced by CMainFrame::OnCreate().
bool CChildView::IsCollapsed () const [private]
Determines whether all sections of the display are hidden.
Returns:
true if all sections hidden.
References MeaMagnifier::IsEnabled(), MeaDataDisplay::IsEnabled(), IsStatusbarVisible(), IsToolbarVisible(), m_dataDisplay, m_magnifier, MeaRegionSection, and MeaScreenSection.
Referenced by OnCollapse(), and OnUpdateCollapse().
bool CChildView::IsStatusbarVisible () const [inline, private]
Indicates whether the status bar is being shown.
Returns:
true if the status bar is displayed.
Referenced by IsCollapsed(), and OnCollapse().
bool CChildView::IsToolbarVisible () const [inline, private]
Indicates whether the toolbar is being shown.
Returns:
true if the toolbar is displayed.
Referenced by IsCollapsed(), and OnCollapse().
void CChildView::LoadProfile (MeaProfile & profile)
Restores the state of the view from the specified profile object.
In addition, this method calls the LoadProfile method on all objects it contains.
Parameters:
profile [in] Profile object from which the state is restored.
References MeaToolMgr::ChangeRadioToolEnable(), MeaToolMgr::ColorsChanged(), MeaToolMgr::DisableRadioTools(), MeaSingleton_T< MeaScreenMgr >::Instance(), MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaSingleton_T< MeaPositionLogMgr >::Instance(), MeaSingleton_T< MeaProfileMgr >::Instance(), MeaSingleton_T< MeaToolMgr >::Instance(), MeaMagnifier::IsEnabled(), MeaDataDisplay::IsEnabled(), MeaToolMgr::LoadProfile(), MeaProfileMgr::LoadProfile(), MeaMagnifier::LoadProfile(), MeaScreenMgr::LoadProfile(), MeaPositionLogMgr::LoadProfile(), MeaUnitsMgr::LoadProfile(), m_dataDisplay, m_expandMagnifier, m_expandScreenInfo, m_expandStatusbar, m_expandToolbar, m_expandToolInfo, m_magnifier, m_profileMagnifierEnabled, m_profileRegionEnabled, m_profileScreenEnabled, m_startupProfile, MeaRegionSection, MeaScreenSection, MeaProfile::ReadBool(), MeaProfile::ReadStr(), MeaToolMgr::UpdateTools(), and MeaProfile::UserInitiated().
Referenced by CMainFrame::LoadProfile().
void CChildView::LoadStartupFile (const CString & cmdLineFile) const
This method handles the processing of any files specified on the command-line or specified in preferences.
The following processing is performed:
If a profile file is specified on the command-line, that file is loaded.
If no file is specified on the command-line, or the file is not a profile, the preferences are checked to see if a startup profile file has been specified. If it has, that file is loaded.
If a position log file is specified on the command-line, that file is loaded.
Parameters:
cmdLineFile [in] File pathname specified on the command-line.
References MeaSingleton_T< MeaProfileMgr >::Instance(), MeaSingleton_T< MeaPositionLogMgr >::Instance(), MeaPositionLogMgr::IsPositionFile(), MeaProfileMgr::IsProfileFile(), MeaProfileMgr::Load(), MeaPositionLogMgr::Load(), m_startupProfile, and MeaPositionLogMgr::ManagePositions().
Referenced by CMainFrame::OnCopyData(), and CMainFrame::OnCreate().
void CChildView::MasterReset ()
Called when the application master reset is initiated.
This method restores the view to its default state and calls the MasterReset method on all contained objects.
References AllChanged, MeaToolMgr::ChangeRadioToolEnable(), MeaToolMgr::ColorsChanged(), MeaToolMgr::DisableRadioTools(), MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaSingleton_T< MeaProfileMgr >::Instance(), MeaSingleton_T< MeaPositionLogMgr >::Instance(), MeaSingleton_T< MeaScreenMgr >::Instance(), MeaSingleton_T< MeaToolMgr >::Instance(), kDefMagnifierVisible, kDefScreenInfoVisible, kDefStatusbarVisible, kDefToolbarVisible, kDefToolInfoVisible, m_expandMagnifier, m_expandScreenInfo, m_expandStatusbar, m_expandToolbar, m_expandToolInfo, m_magnifier, m_startupProfile, MeaToolMgr::MasterReset(), MeaProfileMgr::MasterReset(), MeaMagnifier::MasterReset(), MeaScreenMgr::MasterReset(), MeaPositionLogMgr::MasterReset(), MeaUnitsMgr::MasterReset(), MeaToolMgr::UpdateTools(), ViewMagnifier(), ViewScreenInfo(), and ViewToolInfo().
Referenced by CMainFrame::OnMasterReset().
void CChildView::OnAngles (UINT nID) [protected]
Called when the degrees or radians units are selected.
Parameters:
nID [in] ID of the Units menu angle item that was selected.
References MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaSingleton_T< MeaToolMgr >::Instance(), MeaAssert, MeaDegreesId, MeaRadiansId, MeaUnitsMgr::SetAngularUnits(), UnitsChanged, and MeaToolMgr::UpdateTools().
CChildView::OnCollapse () [protected]
Called to toggle the application window between a collapsed presentation and an expanded presentation.
Note that the expanded state maintains the the display state of individual sections of the application so that expanding the app does not display sections that have been explicitly hidden.
References IsCollapsed(), MeaMagnifier::IsEnabled(), MeaDataDisplay::IsEnabled(), IsStatusbarVisible(), IsToolbarVisible(), m_dataDisplay, m_expandMagnifier, m_expandScreenInfo, m_expandStatusbar, m_expandToolbar, m_expandToolInfo, m_magnifier, MeaRegionSection, MeaScreenSection, OnMagnifier(), OnScreenInfo(), and OnToolInfo().
void CChildView::OnColorFmt (UINT nID) [protected]
Called when a new color display format is requested.
Parameters:
nID [in] ID of the color format menu item.
References MeaMagnifier::CMYFmt, MeaMagnifier::CMYKFmt, MeaMagnifier::HSLFmt, m_magnifier, MeaAssert, MeaMagnifier::RGBFmt, MeaMagnifier::RGBHexFmt, MeaMagnifier::SetColorFmt(), MeaMagnifier::YCbCrFmt, and MeaMagnifier::YIQFmt.
CChildView::OnCopyRegion () [protected]
Enabled when the Rectangle, Circle or Window tool is selected.
Copies the area of the screen bounded by the tool to the Clipboard.
References MeaToolMgr::DisableRadioTool(), MeaToolMgr::HasRegion(), MeaSingleton_T< MeaToolMgr >::Instance(), m_snapshotTimer, and MeaTimer::Start().
CChildView::OnCreate (LPCREATESTRUCT lpCreateStruct) [protected]
Creates the view and the data display.
Also enables the appropriate tools.
Parameters:
lpCreateStruct [in] Window creation structure.
Returns:
0 if the creation was successful.
References MeaToolMgr::ChangeRadioToolEnable(), MeaTimer::Create(), MeaMagnifier::Create(), MeaDataDisplay::Create(), MeaToolMgr::EnableTool(), GetMenuWidth(), MeaSingleton_T< MeaToolMgr >::Instance(), MeaScreenTool::kToolName, m_adjustHeight, m_dataDisplay, m_magnifier, m_margin, m_snapshotTimer, and MeaLayout::SetWindowPos().
CChildView::OnCustomUnits () [protected]
If custom units have been defined, this method is called to select them for use.
References MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaSingleton_T< MeaToolMgr >::Instance(), MeaCustomId, MeaUnitsMgr::SetLinearUnits(), UnitsChanged, and MeaToolMgr::UpdateTools().
LRESULT CChildView::OnDataChange (WPARAM wParam, LPARAM lParam) [protected]
Called when data is entered into a field in the data display or a spin button is used.
Tells the current tool to set a new position.
Parameters:
wParam [in] New data value in pixels.
lParam [in] Data field that we modified.
Returns:
Always returns 0.
References MeaSingleton_T< MeaToolMgr >::Instance(), and MeaToolMgr::SetPosition().
CChildView::OnDefineCustomUnits () [protected]
Called when the user selects the Define Custom units menu item.
This method brings up the preferences dialog with the Custom Units property page selected.
References MeaPreferences::m_customPrefs, m_prefs, and OnPreferences().
CChildView::OnDeletePositions () [protected]
Called to delete all recorded positions.
References MeaPositionLogMgr::DeletePositions(), and MeaSingleton_T< MeaPositionLogMgr >::Instance().
CChildView::OnDestroy () [protected]
Disables all tools including the magnifier and destroys the window.
References MeaMagnifier::Disable(), MeaToolMgr::DisableRadioTools(), MeaSingleton_T< MeaToolMgr >::Instance(), and m_magnifier.
CChildView::OnEditClear () [protected]
Wires the application Edit menu Delete item into the data display text field that has the keyboard focus so that its contents are deleted.
References MeaDataDisplay::GetFieldFocus(), and m_dataDisplay.
CChildView::OnEditCopy () [protected]
Wires the application Edit menu Copy item into the data display text field that has the keyboard focus so that its contents are copied to the clipboard.
References MeaMagnifier::GetFieldFocus(), MeaDataDisplay::GetFieldFocus(), m_dataDisplay, and m_magnifier.
CChildView::OnEditCut () [protected]
Wires the application Edit menu Cut item into the data display text field that has the keyboard focus so that its contents are cut into the clipboard.
References MeaDataDisplay::GetFieldFocus(), and m_dataDisplay.
CChildView::OnEditPaste () [protected]
Wires the application Edit menu Paste item into the data display text field that has the keyboard focus so that the clipboard contents are pasted into the field.
References MeaDataDisplay::GetFieldFocus(), and m_dataDisplay.
CChildView::OnFindCrosshair () [protected]
Called to flash the current radio tool's crosshair(s).
References MeaToolMgr::FlashTool(), and MeaSingleton_T< MeaToolMgr >::Instance().
LRESULT CChildView::OnGetPosition (WPARAM wParam, LPARAM lParam) [protected]
Called when the magnifier wants the current position.
Parameters:
wParam [in] Not used.
lParam [in] POINT structure to fill with current position.
Returns:
Always returns TRUE.
References MeaToolMgr::GetPosition(), and MeaSingleton_T< MeaToolMgr >::Instance().
CChildView::OnHideCrosshairs () [protected]
Called to toggle between showing and hiding the tool crosshair(s).
References MeaToolMgr::CrosshairsEnabled(), MeaToolMgr::DisableCrosshairs(), MeaToolMgr::EnableCrosshairs(), and MeaSingleton_T< MeaToolMgr >::Instance().
LRESULT CChildView::OnHPTimer (WPARAM wParam, LPARAM lParam) [protected]
Called when the region snapshot timer expires.
Parameters:
wParam [in] Not used
lParam [in] Not used.
Returns:
Always returns 0.
References MeaToolMgr::EnableRadioTool(), and MeaSingleton_T< MeaToolMgr >::Instance().
CChildView::OnInvertY () [protected]
Called when the Invert Y menu item is selected.
The y-axis inversion is toggled.
References MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaSingleton_T< MeaToolMgr >::Instance(), MeaUnitsMgr::SetInvertY(), and MeaToolMgr::UpdateTools().
CChildView::OnLoadPositions () [protected]
Called to load a position log file.
References MeaSingleton_T< MeaPositionLogMgr >::Instance(), and MeaPositionLogMgr::ManagePositions().
CChildView::OnLoadProfile () [protected]
Loads the user specified profile file to set the application configuration.
References MeaSingleton_T< MeaProfileMgr >::Instance(), and MeaProfileMgr::Load().
CChildView::OnMagnifier () [protected]
Called when the magnifier menu item is selected to toggle between showing and hiding the magnifier.
References MeaMagnifier::IsEnabled(), m_magnifier, and ViewMagnifier().
Referenced by InitView(), and OnCollapse().
CChildView::OnManagePositions () [protected]
Called to bring up the position management dialog.
References MeaSingleton_T< MeaPositionLogMgr >::Instance(), and MeaPositionLogMgr::ManagePositions().
void CChildView::OnMouseHook (WPARAM wParam, LPARAM lParam)
A number of tools (e.g.
pointer tool, magnifier) need to track the pointer position. This method is called by the application class when the system mouse hook is called. The method forwards the mouse hook information to the tools that are interested.
Parameters:
wParam [in] Message id.
lParam [in] MOUSEHOOKSTRUCT.
References MeaSingleton_T< MeaToolMgr >::Instance(), and MeaToolMgr::OnMouseHook().
CChildView::OnOrigin () [protected]
Called when the Set Origin menu item is selected.
The origin is repositioned to the current point.
References MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaSingleton_T< MeaToolMgr >::Instance(), OriginChanged, MeaUnitsMgr::SetOrigin(), and MeaToolMgr::UpdateTools().
CChildView::OnPreferences () [protected]
Called when the Preferences menu item is selected to bring up the preferences dialog.
References ApplyPreferences(), MeaScreenMgr::AtEnd(), MeaCalibrationPrefs::AutoRes, MeaProfileMgr::CreateLoadDialog(), MeaColors::CrossHairBack, MeaColors::CrossHairBorder, MeaColors::CrossHairHilite, MeaColors::CrossHairOpacity, MeaColors::Get(), MeaColors::GetA(), MeaCustomUnits::GetAbbrev(), MeaUnitsMgr::GetAngularDisplayPrecisions(), MeaScreenMgr::GetCalInInches(), MeaUnitsMgr::GetCustomUnits(), MeaUnitsMgr::GetLinearDisplayPrecisions(), MeaCustomUnits::GetName(), MeaCustomUnits::GetScaleBasis(), MeaCustomUnits::GetScaleFactor(), MeaScreenMgr::GetScreenIter(), MeaScreenMgr::GetScreenRes(), MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaSingleton_T< MeaProfileMgr >::Instance(), MeaSingleton_T< MeaToolMgr >::Instance(), MeaSingleton_T< MeaScreenMgr >::Instance(), MeaDataWin::IsArmed(), MeaToolMgr::IsToolEnabled(), MeaOriginTool::kToolName, MeaColors::LineFore, MeaCustomUnitsPrefs::m_abbrev, MeaPreferences::m_advancedPrefs, MeaRulerPrefs::m_backColor, MeaToolsPrefs::m_backColor, MeaRulerPrefs::m_borderColor, MeaToolsPrefs::m_borderColor, MeaPreferences::m_calibrationPrefs, MeaPreferences::m_customPrefs, MeaToolsPrefs::m_hiliteColor, MeaToolsPrefs::m_lineColor, MeaCustomUnitsPrefs::m_name, MeaRulerPrefs::m_opacity, MeaToolsPrefs::m_opacity, MeaToolsPrefs::m_originMarker, MeaPreferences::m_precisionPrefs, m_prefs, MeaCalibrationPrefs::Screen::m_res, MeaCalibrationPrefs::Screen::m_resMode, MeaCalibrationPrefs::Screen::m_resUnits, MeaPreferences::m_rulerPrefs, MeaCalibrationPrefs::m_screens, MeaToolsPrefs::m_showDataWin, MeaAdvancedPrefs::m_startupProfile, m_startupProfile, MeaAdvancedPrefs::m_startupProfileDlg, MeaPreferences::m_toolsPrefs, MeaCalibrationPrefs::ManualRes, MeaCentimetersId, MeaCustomId, MeaDegreesId, MeaInchesId, MeaMasterResetMsg, MeaMillimetersId, MeaPicasId, MeaPixelsId, MeaPointsId, MeaRadiansId, MeaTwipsId, MeaColors::RulerBack, MeaColors::RulerBorder, MeaColors::RulerOpacity, MeaPrecisionPrefs::SetAngularPrecisions(), MeaPrecisionPrefs::SetLinearPrecisions(), MeaCustomUnitsPrefs::SetScaleFactor(), MeaCalibrationPrefs::UseCentimeters, and MeaCalibrationPrefs::UseInches.
Referenced by OnDefineCustomUnits(), and OnShowCalPrefs().
LRESULT CChildView::OnPrefsApply (WPARAM wParam, LPARAM lParam) [protected]
Called when the Apply button is pressed on the preferences dialog.
Parameters:
wParam [in] Not used.
lParam [in] Not used.
Returns:
Always returns 0.
References ApplyPreferences().
void CChildView::OnRadioTool (UINT nID) [protected]
Called when a radio tool is selected.
Parameters:
nID [in] ID of the tool menu item.
References MeaSingleton_T< MeaToolMgr >::Instance(), MeaCursorTool::kToolName, MeaPointTool::kToolName, MeaWindowTool::kToolName, MeaLineTool::kToolName, MeaRectTool::kToolName, MeaCircleTool::kToolName, MeaAngleTool::kToolName, MeaAssert, and MeaToolMgr::SetRadioTool().
CChildView::OnRecordPosition () [protected]
Called to record the current radio tool's position.
References MeaSingleton_T< MeaPositionLogMgr >::Instance(), and MeaPositionLogMgr::RecordPosition().
CChildView::OnResetOrigin () [protected]
Called to reset the origin to its default location (0, 0).
The default origin location is (0, 0) at the upper left corner of the screen. In y-axis inversion is in effect, the origin is located at (0, 0) in the lower left corner of the screen.
References MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaSingleton_T< MeaToolMgr >::Instance(), MeaUnitsMgr::SetOrigin(), and MeaToolMgr::UpdateTools().
CChildView::OnRuler () [protected]
Called when the ruler menu item is selected to toggle the display of the screen measurement rulers.
References MeaSingleton_T< MeaToolMgr >::Instance(), MeaRulerTool::kToolName, and MeaToolMgr::ToggleEnableTool().
CChildView::OnRunState () [protected]
Called to toggle between paused and running states on the magnifier window.
References MeaMagnifier::Freeze, MeaMagnifier::GetRunState(), m_magnifier, MeaMagnifier::Run, and MeaMagnifier::SetRunState().
CChildView::OnSavePositions () [protected]
Called to save a position log file.
References MeaSingleton_T< MeaPositionLogMgr >::Instance(), and MeaPositionLogMgr::Save().
CChildView::OnSavePositionsAs () [protected]
Called to save a position log file with a new pathname.
References MeaSingleton_T< MeaPositionLogMgr >::Instance(), and MeaPositionLogMgr::Save().
CChildView::OnSaveProfile () [protected]
Saves the current application configuration to the user selected profile file.
References MeaSingleton_T< MeaProfileMgr >::Instance(), and MeaProfileMgr::Save().
CChildView::OnScreenGrid () [protected]
Called to toggle the display of the screen grid.
References MeaSingleton_T< MeaToolMgr >::Instance(), MeaGridTool::kToolName, and MeaToolMgr::ToggleEnableTool().
CChildView::OnScreenGridSpacing () [protected]
Called when the screen grid spacing menu item is selected.
Brings up the screen grid spacing dialog.
References MeaToolMgr::DisableTool(), MeaToolMgr::EnableTool(), MeaToolMgr::FindTool(), MeaSingleton_T< MeaToolMgr >::Instance(), MeaToolMgr::IsToolEnabled(), and MeaGridTool::kToolName.
CChildView::OnScreenInfo () [protected]
Called when the Screen Info view menu item is selected.
Toggles the display of the screen information section.
References MeaDataDisplay::IsEnabled(), m_dataDisplay, MeaScreenSection, and ViewScreenInfo().
Referenced by InitView(), and OnCollapse().
LRESULT CChildView::OnShowCalPrefs (WPARAM wParam, LPARAM lParam) [protected]
Called when the show calibration preferences message is received.
This message is issued by the resolution calibration warning dialogs and the calibration warning button.
Parameters:
wParam [in] Not used.
lParam [in] Not used.
Returns:
Always returns 0.
References MeaPreferences::m_calibrationPrefs, m_prefs, and OnPreferences().
CChildView::OnShowMagGrid () [protected]
Called when the magnifier grid menu item is selected to toggle the display of the pixel grid on the magnifier window.
References MeaMagnifier::GetShowGrid(), m_magnifier, and MeaMagnifier::SetShowGrid().
CChildView::OnToolInfo () [protected]
Called when the Tool Info view menu item is selected.
Toggles the display of the measurement section.
References MeaDataDisplay::IsEnabled(), m_dataDisplay, MeaRegionSection, and ViewToolInfo().
Referenced by InitView(), and OnCollapse().
void CChildView::OnUnits (UINT nID) [protected]
Called when new units are selected from the Units menu.
Parameters:
nID [in] ID of the Units menu item that was selected.
References MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaSingleton_T< MeaToolMgr >::Instance(), MeaAssert, MeaCentimetersId, MeaInchesId, MeaMillimetersId, MeaPicasId, MeaPixelsId, MeaPointsId, MeaTwipsId, MeaUnitsMgr::SetLinearUnits(), UnitsChanged, and MeaToolMgr::UpdateTools().
CChildView::OnUpdateAngles (CCmdUI * pCmdUI) [protected]
Updates the radio button state on the Units menu right before the menu is displayed.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaUnitsMgr::GetAngularUnitsId(), MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaAssert, MeaDegreesId, and MeaRadiansId.
CChildView::OnUpdateCollapse (CCmdUI * pCmdUI) [protected]
Updates the state of the collapse menu item to reflect whether the app is currently in a collapsed presentation.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References IsCollapsed().
CChildView::OnUpdateColorFmt (CCmdUI * pCmdUI) [protected]
Updates the state of the pixel color format menu item before it is displayed.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaMagnifier::CMYFmt, MeaMagnifier::CMYKFmt, MeaMagnifier::GetColorFmt(), MeaMagnifier::HSLFmt, m_magnifier, MeaAssert, MeaMagnifier::RGBFmt, MeaMagnifier::RGBHexFmt, MeaMagnifier::YCbCrFmt, and MeaMagnifier::YIQFmt.
CChildView::OnUpdateCopyRegion (CCmdUI * pCmdUI) [protected]
If a tool reports that it has a region that can be copied, the Copy Region menu item is enabled.
Otherwise the menu item is disabled.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaSingleton_T< MeaToolMgr >::Instance().
CChildView::OnUpdateCustomUnits (CCmdUI * pCmdUI) [protected]
Updates the custom units menu item to show the name of the custom units, if custom units have been defined.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaUnitsMgr::GetCustomUnits(), MeaUnitsMgr::GetLinearUnitsId(), MeaCustomUnits::GetName(), MeaCustomUnits::HaveCustomUnits(), MeaSingleton_T< MeaUnitsMgr >::Instance(), and MeaCustomId.
CChildView::OnUpdateDeletePositions (CCmdUI * pCmdUI) [protected]
Updates the state of the delete positions menu item to reflect whether there are any positions that can be deleted.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaSingleton_T< MeaPositionLogMgr >::Instance().
CChildView::OnUpdateEditClear (CCmdUI * pCmdUI) [protected]
Updates the application Edit menu Delete item so that its state reflects the Delete state of the data display text field that has the keyboard focus.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaDataDisplay::GetFieldFocus(), MeaNumberField::IsTextSelected(), and m_dataDisplay.
CChildView::OnUpdateEditCopy (CCmdUI * pCmdUI) [protected]
Updates the application Edit menu Copy item so that its state reflects the Copy state of the data display text field that has the keyboard focus.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaMagnifier::GetFieldFocus(), MeaDataDisplay::GetFieldFocus(), MeaNumberField::IsTextSelected(), m_dataDisplay, and m_magnifier.
CChildView::OnUpdateEditCut (CCmdUI * pCmdUI) [protected]
Updates the application Edit menu Cut item so that its state reflects the Cut state of the data display text field that has the keyboard focus.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaDataDisplay::GetFieldFocus(), MeaNumberField::IsTextSelected(), and m_dataDisplay.
CChildView::OnUpdateEditPaste (CCmdUI * pCmdUI) [protected]
Updates the application Edit menu Paste item so that its state reflects the Paste state of the data display text field that has the keyboard focus.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaDataDisplay::GetFieldFocus(), and m_dataDisplay.
CChildView::OnUpdateFindCrosshair (CCmdUI * pCmdUI) [protected]
Updates the flash menu item to reflect whether the tool has crosshairs that can be flashed.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaToolMgr::CrosshairsEnabled(), MeaToolMgr::HasCrosshairs(), and MeaSingleton_T< MeaToolMgr >::Instance().
CChildView::OnUpdateHideCrosshairs (CCmdUI * pCmdUI) [protected]
Updates the state of the Hide Crosshairs menu item to reflect whether the tool crosshair(s) are shown or hidden.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaToolMgr::CrosshairsEnabled(), MeaToolMgr::HasCrosshairs(), and MeaSingleton_T< MeaToolMgr >::Instance().
CChildView::OnUpdateInvertY (CCmdUI * pCmdUI) [protected]
Updates the state of the Invert Y menu item before it is displayed.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaSingleton_T< MeaUnitsMgr >::Instance().
CChildView::OnUpdateMagnifier (CCmdUI * pCmdUI) [protected]
Updates the state of the magnifier item on the view menu before it is displayed.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaMagnifier::IsEnabled(), and m_magnifier.
CChildView::OnUpdateRadioTool (CCmdUI * pCmdUI) [protected]
Called right before the Tool menu is displayed to update its radio state.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaSingleton_T< MeaToolMgr >::Instance(), MeaCursorTool::kToolName, MeaPointTool::kToolName, MeaLineTool::kToolName, MeaWindowTool::kToolName, MeaRectTool::kToolName, MeaCircleTool::kToolName, MeaAngleTool::kToolName, and MeaAssert.
CChildView::OnUpdateRuler (CCmdUI * pCmdUI) [protected]
Updates the state of the ruler menu item before it is displayed.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaSingleton_T< MeaToolMgr >::Instance(), and MeaRulerTool::kToolName.
CChildView::OnUpdateRunState (CCmdUI * pCmdUI) [protected]
Updates the state of the pause button on the magnifier window and on the menu.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaMagnifier::Freeze, MeaMagnifier::GetRunState(), and m_magnifier.
CChildView::OnUpdateSavePositions (CCmdUI * pCmdUI) [protected]
Called to update the state of the position save menu items.
If there are no positions currently in memory, the menu items are disabled.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaSingleton_T< MeaPositionLogMgr >::Instance().
CChildView::OnUpdateScreenGrid (CCmdUI * pCmdUI) [protected]
Updates the state of the screen grid menu item before it is displayed.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaSingleton_T< MeaToolMgr >::Instance(), and MeaGridTool::kToolName.
CChildView::OnUpdateScreenInfo (CCmdUI * pCmdUI) [protected]
Updates the state of the Screen Info view menu item before it is displayed.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaDataDisplay::IsEnabled(), m_dataDisplay, and MeaScreenSection.
CChildView::OnUpdateShowMagGrid (CCmdUI * pCmdUI) [protected]
Updates the state of the magnifier grid menu item before it is displayed.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaMagnifier::GetShowGrid(), and m_magnifier.
CChildView::OnUpdateToolInfo (CCmdUI * pCmdUI) [protected]
Updates the state of the Tool Info menu item before it is displayed.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaDataDisplay::IsEnabled(), m_dataDisplay, and MeaRegionSection.
CChildView::OnUpdateUnits (CCmdUI * pCmdUI) [protected]
Updates the radio button state on the Units menu right before the menu is displayed.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaUnitsMgr::GetLinearUnitsId(), MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaAssert, MeaCentimetersId, MeaInchesId, MeaMillimetersId, MeaPicasId, MeaPixelsId, MeaPointsId, and MeaTwipsId.
CChildView::OnUpdateZoomIn (CCmdUI * pCmdUI) [protected]
Updates the state of the Zoom In menu item before it is displayed.
If the magnifier is at maximum zoom, the Zoom In menu item is disabled.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaMagnifier::CanZoomIn(), and m_magnifier.
CChildView::OnUpdateZoomOut (CCmdUI * pCmdUI) [protected]
Updates the state of the Zoom Out menu item before it is displayed.
If the magnifier is at minimum zoom, the Zoom Out menu item is disabled.
Parameters:
pCmdUI [in] UI command object for updating the menu item.
References MeaMagnifier::CanZoomOut(), and m_magnifier.
CChildView::OnZoomIn () [protected]
Called to increase magnification on the magnifier window.
References m_magnifier, and MeaMagnifier::ZoomIn().
CChildView::OnZoomOut () [protected]
Called to decrease magnification on the magnifier window.
References m_magnifier, and MeaMagnifier::ZoomOut().
CChildView::PreCreateWindow (CREATESTRUCT & cs) [virtual]
Called before the window is created.
Sets up the View window class.
Parameters:
cs [in] Window creation information structure.
Returns:
TRUE if the pre-creation process was successful.
void CChildView::SaveProfile (MeaProfile & profile)
Persists the state of the view to the specified profile object.
In addition, this method calls the SaveProfile method on all objects it contains.
Parameters:
profile [in] Profile object into which the state is persisted.
References MeaSingleton_T< MeaScreenMgr >::Instance(), MeaSingleton_T< MeaProfileMgr >::Instance(), MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaSingleton_T< MeaToolMgr >::Instance(), MeaSingleton_T< MeaPositionLogMgr >::Instance(), MeaMagnifier::IsEnabled(), MeaDataDisplay::IsEnabled(), m_dataDisplay, m_expandMagnifier, m_expandScreenInfo, m_expandStatusbar, m_expandToolbar, m_expandToolInfo, m_magnifier, m_startupProfile, MeaRegionSection, MeaScreenSection, MeaToolMgr::SaveProfile(), MeaProfileMgr::SaveProfile(), MeaMagnifier::SaveProfile(), MeaScreenMgr::SaveProfile(), MeaPositionLogMgr::SaveProfile(), MeaUnitsMgr::SaveProfile(), MeaProfile::UserInitiated(), MeaProfile::WriteBool(), and MeaProfile::WriteStr().
Referenced by CMainFrame::SaveProfile().
void CChildView::ViewMagnifier (bool enable) [private]
Displays or hides the magnifier section.
Parameters:
enable [in] true if the section should be shown.
References CheckMargins(), MeaMagnifier::Disable(), MeaMagnifier::Enable(), MeaMagnifier::GetHeight(), MeaLayout::GetWindowHeight(), MeaMagnifier::IsEnabled(), m_magnifier, m_margin, and MeaLayout::SetWindowHeight().
Referenced by MasterReset(), and OnMagnifier().
void CChildView::ViewScreenInfo (bool enable) [private]
Displays or hides the screen information section.
Parameters:
enable [in] true if the section should be shown.
References CheckMargins(), MeaDataDisplay::Disable(), MeaDataDisplay::Enable(), MeaDataDisplay::GetHeight(), MeaLayout::GetWindowHeight(), MeaDataDisplay::IsEnabled(), m_dataDisplay, m_magnifier, MeaScreenSection, MeaLayout::MoveWindowHeight(), and MeaLayout::SetWindowHeight().
Referenced by MasterReset(), and OnScreenInfo().
void CChildView::ViewToolInfo (bool enable) [private]
Displays or hides the measurement data section.
Parameters:
enable [in] true if the section should be shown.
References CheckMargins(), MeaDataDisplay::Disable(), MeaDataDisplay::Enable(), MeaDataDisplay::GetHeight(), MeaLayout::GetWindowHeight(), MeaDataDisplay::IsEnabled(), m_dataDisplay, m_magnifier, MeaRegionSection, MeaLayout::MoveWindowHeight(), and MeaLayout::SetWindowHeight().
Referenced by MasterReset(), and OnToolInfo().
Member Data Documentation
bool CChildView::m_profileMagnifierEnabled [private]
Indicates if the stored user preference is to show the magnifier window.
Referenced by InitView(), and LoadProfile().
bool CChildView::m_profileRegionEnabled [private]
Indicates if the stored user preference is to show the measurement data window.
Referenced by InitView(), and LoadProfile().
bool CChildView::m_profileScreenEnabled [private]
Indicates if the stored user preference is to show the screen information section.
Referenced by InitView(), and LoadProfile().
The documentation for this class was generated from the following files:
ChildView.h
ChildView.cpp
Copyright 2011 C Thing Software