Meazure: ev::DFA Class Reference
ev::DFA Class Reference
This class represents a deterministic finite state automaton (DFA) (i.e.
Public Member Functions
DFA (Validator &validator, const ContentModel &contentModel)
Constructs a DFA.
virtual ~DFA ()
Destroys an instance of a DFA.
Validator & GetValidator ()
Returns the parent validator for this DFA.
const State * GetStartState () const
Returns the start state of the DFA.
int GetId () const
Obtains the ID assigned to the DFA.
Static Public Member Functions
static void ResetId ()
Resets the ID assigned to the DFAs.
Protected Types
typedef std::list< State * > StateList
List of all states in the DFA.
typedef StateList::iterator StateIter
Iterator over all states in the DFA.
typedef StateList::const_iterator StateIter_c
Constant iterator over all states in the DFA.
Protected Member Functions
DFA (const DFA &dfa)
Purposely undefined.
DFA & operator= (const DFA &dfa)
Purposely undefined.
void BuildEmptyDFA ()
Builds the DFA for an element with an EMPTY content model.
void BuildAnyDFA ()
Builds the DFA for an element with an ANY content model.
void BuildMixedDFA (const ContentModel &contentModel)
Builds the DFA for an element with a content model that accepts PCDATA.
void BuildChoiceDFA (const ContentModel &contentModel)
Builds the DFA for an element with an OR'd content model.
void BuildSeqDFA (const ContentModel &contentModel)
Builds the DFA for an element with a sequenced content model.
void BuildComplexDFA (const ParseNode *parseTree)
Builds the DFA for an element whose content model is a complex combination of elements.
ParseNode * BuildParseTree (const ContentModel &contentModel, bool top=true)
Builds a parse tree from the specified element content model.
State * GetUnmarkedState ()
Returns the first unmarked state in the list of states.
State * FindState (const ParseNode::NodeSet &positions)
Tests whether the list of positions correspond to a state already on the state list.
Protected Attributes
int m_id
ID for the DFA.
ParseNode * m_parseTree
Parse tree for a complex DFA.
StateList m_states
States that comprise the DFA.
Validator & m_validator
Parent validator for the DFA.
Static Protected Attributes
static int m_currentId = 0
ID to assign to the parse node created next.
Friends
EVOstream & operator<< (EVOstream &stream, const DFA *dfa)
Output stream operator for a DFA.
Detailed Description
This class represents a deterministic finite state automaton (DFA) (i.e.
a state machine). An element's content model is represented by a DFA. To validate the content of an element, its DFA is used by transitioning among its states based on the contained elements.
Constructor & Destructor Documentation
DFA()
DFA::DFA (Validator & validator, const ContentModel & contentModel)
Constructs a DFA.
Parameters
validator [in] The parent validator for this DFA.
contentModel [in] Content model represented by this DFA.
References ev::ContentModel::AnyCat, BuildAnyDFA(), BuildChoiceDFA(), BuildComplexDFA(), BuildEmptyDFA(), ev::ParseNode::BuildFollowpos(), BuildMixedDFA(), BuildParseTree(), BuildSeqDFA(), ev::ContentModel::ComplexCat, ev::ContentModel::EmptyCat, ev::ContentModel::GetCategory(), m_parseTree, ev::ContentModel::MixedCat, ev::ContentModel::PureChoiceCat, ev::ContentModel::PureSeqCat, ev::ParseNode::ResetId(), and ev::State::ResetId().
Member Function Documentation
BuildChoiceDFA()
void DFA::BuildChoiceDFA (const ContentModel & contentModel) protected
Builds the DFA for an element with an OR'd content model.
Parameters
contentModel [in] The content model to be represented by the DFA.
References ev::State::AddTransition(), ev::ContentModel::AtEnd(), ev::ContentModel::GetChild(), ev::ContentModel::GetChildIter(), ev::ContentModel::GetName(), ev::ContentModel::IsOpt(), ev::ContentModel::IsPlus(), ev::ContentModel::IsRep(), m_states, and ev::State::Normal.
Referenced by DFA().
BuildComplexDFA()
void DFA::BuildComplexDFA (const ParseNode * parseTree) protected
Builds the DFA for an element whose content model is a complex combination of elements.
Parameters
parseTree [in] The parse tree representing the complex content model.
References ev::State::AddTransition(), FindState(), ev::ParseNode::GetFirstpos(), ev::State::GetPositions(), ev::ParseNode::GetSymbolSet(), GetUnmarkedState(), m_states, ev::State::Mark(), ev::State::Normal, and ev::ParseNode::Union().
Referenced by DFA().
BuildMixedDFA()
void DFA::BuildMixedDFA (const ContentModel & contentModel) protected
Builds the DFA for an element with a content model that accepts PCDATA.
Parameters
contentModel [in] The content model to be represented by the DFA.
References ev::State::AddTransition(), ev::ContentModel::AtEnd(), ev::ContentModel::GetChild(), ev::ContentModel::GetChildIter(), ev::ContentModel::GetName(), m_states, and ev::State::Mixed.
Referenced by DFA().
BuildParseTree()
ParseNode * DFA::BuildParseTree (const ContentModel & contentModel, bool top = true) protected
Builds a parse tree from the specified element content model.
Parameters
contentModel [in] Content model that is to be parsed.
top [in] Is this the top of the parse tree (for use in recursion).
Returns
The root of the parse tree.
References ev::ContentModel::AnyType, ev::ContentModel::AtEnd(), BuildParseTree(), ev::ParseNode::Choice, ev::ContentModel::ChoiceType, ev::ParseNode::CloneType(), ev::ContentModel::EmptyType, ev::ParseNode::End, ev::ParseNode::Epsilon, ev::ContentModel::GetChild(), ev::ContentModel::GetChildIter(), ev::ContentModel::GetName(), ev::ContentModel::GetQuantity(), ev::ParseNode::GetRight(), ev::ContentModel::GetType(), ev::ParseNode::HaveLeft(), ev::ParseNode::HaveRight(), ev::ParseNode::IsChoice(), ev::ParseNode::IsEpsilon(), ev::ParseNode::IsSeq(), ev::ContentModel::MixedType, ev::ParseNode::Name, ev::ContentModel::NameType, ev::ContentModel::NoneQuant, ev::ParseNode::Opt, ev::ContentModel::OptQuant, ev::ParseNode::Plus, ev::ContentModel::PlusQuant, ev::ParseNode::Rep, ev::ContentModel::RepQuant, ev::ParseNode::Seq, ev::ContentModel::SeqType, ev::ParseNode::SetLeft(), ev::ParseNode::SetRight(), and ev::ParseNode::SetSymbol().
Referenced by BuildParseTree(), and DFA().
BuildSeqDFA()
void DFA::BuildSeqDFA (const ContentModel & contentModel) protected
Builds the DFA for an element with a sequenced content model.
Parameters
contentModel [in] The content model to be represented by the DFA.
References ev::State::AddTransition(), ev::ContentModel::AtEnd(), ev::ContentModel::GetChild(), ev::ContentModel::GetChildIter(), ev::ContentModel::GetName(), ev::ContentModel::GetNumChildren(), ev::ContentModel::IsOpt(), ev::ContentModel::IsPlus(), ev::ContentModel::IsRep(), m_states, ev::State::Normal, and ev::State::SetAccepting().
Referenced by DFA().
FindState()
State * DFA::FindState (const ParseNode::NodeSet & positions) protected
Tests whether the list of positions correspond to a state already on the state list.
Parameters
positions [in] List of positions to test against the state list.
Returns
Pointer to the state if positions correspond to a state on the list, NULL otherwise.
References m_states.
Referenced by BuildComplexDFA().
GetId()
int ev::DFA::GetId () const inline
Obtains the ID assigned to the DFA.
Returns
ID assigned to the DFA.
References m_id.
Referenced by ev::operator<<().
GetStartState()
const State * ev::DFA::GetStartState () const inline
Returns the start state of the DFA.
Returns
Start state of the DFA.
References m_states.
Referenced by ev::ElementDecl::GetStartState().
GetUnmarkedState()
State * DFA::GetUnmarkedState () protected
Returns the first unmarked state in the list of states.
Returns
First unmarked state in the list of states. Returns NULL if there are no unmarked states.
References m_states.
Referenced by BuildComplexDFA().
GetValidator()
Validator & ev::DFA::GetValidator () inline
Returns the parent validator for this DFA.
Returns
Parent validator for this DFA.
References m_validator.
Referenced by ev::State::GetNextState().
Friends And Related Function Documentation
operator<<
EVOstream & operator<< (EVOstream & stream, const DFA * dfa) friend
Output stream operator for a DFA.
Used to dump the state of the DFA to the specified output stream for debugging purposes.
Parameters
stream [in] Output stream.
dfa [in] DFA to output.
Returns
Output stream.
The documentation for this class was generated from the following file:
exval.cpp
Copyright 2011 C Thing Software