Meazure: MeaColorDialog Class Reference
MeaColorDialog Class Reference
Derived class of CColorDialog that manages persisting custom colors and simplifies using the dialog.
#include <ColorDialog.h>
Public Member Functions
MeaColorDialog (UINT titleId=0xFFFF, COLORREF clrInit=0, DWORD dwFlags=0, CWnd *pParentWnd=nullptr)
Constructs the color dialog.
virtual ~MeaColorDialog ()
Destroys a color dialog.
virtual INT_PTR DoModal () override
Modally displays the color dialog.
virtual BOOL OnInitDialog () override
Called when the dialog window has been created but before it is visible.
Static Public Member Functions
static void SaveProfile (MeaProfile &profile)
Persists the state of the dialog (e.g.
static void LoadProfile (MeaProfile &profile)
Restores the state of the dialog from the specified profile object.
static void MasterReset ()
Resets the color dialog to its default state.
Private Attributes
CString m_title
Title for the dialog.
Static Private Attributes
static constexpr int kNumCustomColors { 16 }
Number of available custom colors.
static COLORREF m_defColors []
Default colors.
static COLORREF m_customColors []
User definable custom colors.
Detailed Description
Derived class of CColorDialog that manages persisting custom colors and simplifies using the dialog.
Constructor & Destructor Documentation
MeaColorDialog()
MeaColorDialog::MeaColorDialog (UINT titleId = 0xFFFF, COLORREF clrInit = 0, DWORD dwFlags = 0, CWnd * pParentWnd = nullptr) explicit
Constructs the color dialog.
Parameters
titleId [in] String resource ID for the dialog title.
clrInit [in] Initial color to be selected by the dialog.
dwFlags [in] Dialog display flags defined by CColorDialog.
pParentWnd [in] Parent window for the dialog.
References m_title.
Member Function Documentation
DoModal()
INT_PTR MeaColorDialog::DoModal () override virtual
Modally displays the color dialog.
Returns
IDOK or IDCANCEL.
References m_customColors.
Referenced by MeaToolsPrefs::OnChangeBackColor(), MeaRulerPrefs::OnChangeBkColor(), MeaRulerPrefs::OnChangeBorderColor(), MeaToolsPrefs::OnChangeBorderColor(), MeaToolsPrefs::OnChangeHiliteColor(), and MeaToolsPrefs::OnChangeLineColor().
LoadProfile()
void MeaColorDialog::LoadProfile (MeaProfile & profile) static
Restores the state of the dialog from the specified profile object.
Parameters
profile [in] Profile object from which the state is persisted.
References kNumCustomColors, m_customColors, MeaProfile::ReadInt(), and MeaProfile::UserInitiated().
Referenced by AppView::LoadProfile().
OnInitDialog()
BOOL MeaColorDialog::OnInitDialog () override virtual
Called when the dialog window has been created but before it is visible.
This method customizes the dialog for this class.
Returns
Always TRUE.
References m_title.
SaveProfile()
void MeaColorDialog::SaveProfile (MeaProfile & profile) static
Persists the state of the dialog (e.g.
the custom colors) to the specified profile object.
Parameters
profile [in] Profile object into which the state is persisted.
References kNumCustomColors, m_customColors, MeaProfile::UserInitiated(), and MeaProfile::WriteInt().
Referenced by AppView::SaveProfile().
Member Data Documentation
m_customColors
COLORREF MeaColorDialog::m_customColors static private
Initial value:
{
    m_defColors[0],
    m_defColors[1],
    m_defColors[2],
    m_defColors[3],
    m_defColors[4],
    m_defColors[5],
    m_defColors[6],
    m_defColors[7],
    m_defColors[8],
    m_defColors[9],
    m_defColors[10],
    m_defColors[11],
    m_defColors[12],
    m_defColors[13],
    m_defColors[14],
    m_defColors[15],
}
User definable custom colors.
Referenced by DoModal(), LoadProfile(), MasterReset(), and SaveProfile().
m_defColors
COLORREF MeaColorDialog::m_defColors static private
Initial value:
{
    RGB(0x50, 0x50, 0x50),
    RGB(0xFF, 0xFF, 0xFF),
    RGB(0xFF, 0xFF, 0xFF),
    RGB(0xFF, 0xFF, 0xFF),
    RGB(0xFF, 0xFF, 0xFF),
    RGB(0xFF, 0xFF, 0xFF),
    RGB(0xFF, 0xFF, 0xFF),
    RGB(0xFF, 0xFF, 0xFF),
    RGB(0xFF, 0xFF, 0xFF),
    RGB(0xFF, 0xFF, 0xFF),
    RGB(0xFF, 0xFF, 0xFF),
    RGB(0xFF, 0xFF, 0xFF),
    RGB(0xFF, 0xFF, 0xFF),
    RGB(0xFF, 0xFF, 0xFF),
    RGB(0xFF, 0xFF, 0xFF),
    RGB(0xFF, 0xFF, 0xFF),
}
Default colors.
Referenced by MasterReset().
The documentation for this class was generated from the following files:
ColorDialog.h
ColorDialog.cpp
Copyright 2011 C Thing Software