Meazure: MeaRadioTool Class Reference
MeaRadioTool Class Reference abstract
Abstract base class for tools whose use is mutually exclusive.
#include <RadioTool.h>
Public Types
typedef std::map< CString, POINT > PointMap
Map of points used to set the position of a tool.
Public Member Functions
MeaRadioTool (MeaToolMgr &mgr, const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Constructs a new instance of an radio based measurement tool.
virtual bool IsRadioTool () override
Indicates that the derived tool is a Radio tool and cannot be enabled until any other enabled Radio tool is disabled.
virtual UINT GetLabelId () const
Returns a resource ID for the string used to label this tool on the data display.
virtual bool HasCrosshairs () const
Indicates whether the derived tool uses crosshairs.
virtual void EnableCrosshairs ()
Displays the tool's crosshairs.
virtual void DisableCrosshairs ()
Hides the tool's crosshairs.
virtual void Flash ()
Visually flashes the tool.
virtual void Strobe ()
Visually strobes the tool.
virtual bool HasRegion ()
Indicates whether the tool can define a rectangular region that can then be read for a screen capture.
virtual RECT GetRegion ()
Returns the rectangle defined by the tool.
virtual void SetPosition (const PointMap &points)
Sets the position of the tool.
virtual void RecordPosition (MeaPosition &position) const =0
Records the position of the tool.
virtual void OnMouseHook (WPARAM wParam, LPARAM lParam)
Called by the OS when the mouse pointer is moved.
Public Member Functions inherited from MeaTool
MeaTool (MeaToolMgr &mgr, const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Base class constructor.
virtual ~MeaTool ()=default
Destroys the tool.
virtual void Enable ()
Typically used by derived classes to show the tool.
virtual void Disable ()
Typically used by derived classes to hide the tool.
virtual void Update (MeaUpdateReason reason)
Used by derived classes to update the display of their data.
virtual bool IsRadioTool ()
Indicates whether the derived tool is a radio tool and cannot be enabled until any other enabled Radio tool is disabled.
virtual void SetPosition (MeaDataFieldId which, int pixels)
Sets the position of the tool.
virtual const POINT & GetPosition () const =0
Returns the tool's current position.
virtual void IncPosition (MeaDataFieldId which)
Increments the specified position field.
virtual void DecPosition (MeaDataFieldId which)
Decrements the specified position field.
virtual PCTSTR GetToolName () const =0
Returns the name of the tool.
virtual void SaveProfile (MeaProfile &profile)
Persists the state of the tool to the specified profile object.
virtual void LoadProfile (MeaProfile &profile)
Restores the state of the tool from the specified profile object.
virtual void MasterReset ()
Resets the tool to its default state.
virtual void ColorsChanged ()
Called to notify the tool that the colors in the MeaColors class have been changed.
bool IsEnabled () const
Indicates whether the tool is enabled.
Additional Inherited Members
Protected Attributes inherited from MeaTool
MeaToolMgr & m_mgr
Tool manager.
const MeaScreenProvider & m_screenProvider
Screen information provider.
const MeaUnitsProvider & m_unitsProvider
Units information provider.
bool m_enabled
Indicates whether the tool is enabled.
Static Protected Attributes inherited from MeaTool
static const CPoint m_defaultPos
A default position used by tools that do not have a defined position.
Detailed Description
Abstract base class for tools whose use is mutually exclusive.
For example, a Line tool cannot be used at the same time a Point tool is being used. Thus, the Line and Point tools are mutually exclusive and derive from MeaRadioTool.
Member Typedef Documentation
PointMap
typedef std::map<CString, POINT> MeaRadioTool::PointMap
Map of points used to set the position of a tool.
Typically the position log manager will fill a point map and pass it to the tool's SetPosition method.
Constructor & Destructor Documentation
MeaRadioTool()
MeaRadioTool::MeaRadioTool (MeaToolMgr & mgr, const MeaScreenProvider & screenProvider, const MeaUnitsProvider & unitsProvider) explicit
Constructs a new instance of an radio based measurement tool.
Typically, to use a newly constructed tool, the Enable() method must be called.
Parameters
mgr [in] Tool manager parent of the tool.
screenProvider [in] Screen information provider
unitsProvider [in] Units information provider
Member Function Documentation
DisableCrosshairs()
void MeaRadioTool::DisableCrosshairs () virtual
Hides the tool's crosshairs.
This base class implementation does nothing.
Reimplemented in MeaAngleTool, MeaCircleTool, MeaLineTool, MeaPointTool, and MeaRectTool.
Referenced by MeaToolMgr::DisableCrosshairs().
EnableCrosshairs()
void MeaRadioTool::EnableCrosshairs () virtual
Displays the tool's crosshairs.
If the Enable() method has not been previously called, this method has no effect. This base class implementation does nothing.
Reimplemented in MeaAngleTool, MeaCircleTool, MeaLineTool, MeaPointTool, and MeaRectTool.
Referenced by MeaToolMgr::EnableCrosshairs().
Flash()
void MeaRadioTool::Flash () virtual
Visually flashes the tool.
Typically, if a tool uses crosshairs, they are cycled between a hilite color and their normal color a number of times. Flashing the tool helps the user find it on the screen. This base class implementation does nothing.
Reimplemented in MeaAngleTool, MeaCircleTool, MeaLineTool, MeaPointTool, and MeaRectTool.
Referenced by MeaToolMgr::FlashTool().
GetLabelId()
UINT MeaRadioTool::GetLabelId () const virtual
Returns a resource ID for the string used to label this tool on the data display.
Returns
Resource ID for the label. This base class implementation returns the resource ID for an empty string.
Reimplemented in MeaAngleTool, MeaCircleTool, MeaCursorTool, MeaLineTool, MeaPointTool, MeaRectTool, and MeaWindowTool.
Referenced by MeaToolMgr::GetLabelId().
GetRegion()
RECT MeaRadioTool::GetRegion () virtual
Returns the rectangle defined by the tool.
This rectangle can then be read for a screen capture.
Returns
The region rectangle. This base class implementation returns an empty rectangle.
Reimplemented in MeaCircleTool, MeaRectTool, and MeaWindowTool.
Referenced by MeaToolMgr::GetRegion().
HasCrosshairs()
bool MeaRadioTool::HasCrosshairs () const virtual
Indicates whether the derived tool uses crosshairs.
Returns
This base class implementation always returns true.
Reimplemented in MeaCursorTool, and MeaWindowTool.
Referenced by MeaToolMgr::HasCrosshairs().
HasRegion()
bool MeaRadioTool::HasRegion () virtual
Indicates whether the tool can define a rectangular region that can then be read for a screen capture.
Returns
true if the tool defines a non-empty rectangular region. This base class implementation always returns false.
Reimplemented in MeaCircleTool, MeaRectTool, and MeaWindowTool.
Referenced by MeaToolMgr::HasRegion().
IsRadioTool()
bool MeaRadioTool::IsRadioTool () override virtual
Indicates that the derived tool is a Radio tool and cannot be enabled until any other enabled Radio tool is disabled.
Returns
Always true indicating that this class and its derived classes are Radio tools.
Reimplemented from MeaTool.
OnMouseHook()
void MeaRadioTool::OnMouseHook (WPARAM wParam, LPARAM lParam) virtual
Called by the OS when the mouse pointer is moved.
This base class implementation does nothing.
Parameters
wParam [in] OS Message ID
lParam [in] MOUSEHOOKSTRUCT
Reimplemented in MeaCursorTool, and MeaWindowTool.
Referenced by MeaToolMgr::OnMouseHook().
RecordPosition()
virtual void MeaRadioTool::RecordPosition (MeaPosition & position) const pure virtual
Records the position of the tool.
This method is called by the position log manager to record a position.
Parameters
position [in] The tool's current position is recorded into the position log manager's position object.
Implemented in MeaAngleTool, MeaCircleTool, MeaCursorTool, MeaLineTool, MeaPointTool, MeaRectTool, and MeaWindowTool.
Referenced by MeaToolMgr::RecordPosition().
SetPosition()
void MeaRadioTool::SetPosition (const PointMap & points) virtual
Sets the position of the tool.
This method is called by the position log manager to play back a tool's position that was previously recorded using the RecordPosition method. This base class implementation does nothing.
Parameters
points [in] Map of positions for the tool's crosshairs.
Reimplemented in MeaAngleTool, MeaCircleTool, MeaLineTool, MeaPointTool, and MeaRectTool.
Referenced by MeaToolMgr::SetPosition().
Strobe()
void MeaRadioTool::Strobe () virtual
Visually strobes the tool.
Typically, if a tool uses crosshairs, they are cycled between a hilite color and their normal color once. In addition, if the tool has data windows attached to the crosshairs, they are cycled between hidden and visible. Strobing the tool is done to visually confirm region capture and position recording. This base class implementation does nothing.
Reimplemented in MeaAngleTool, MeaCircleTool, MeaCursorTool, MeaLineTool, MeaPointTool, MeaRectTool, and MeaWindowTool.
Referenced by MeaToolMgr::StrobeTool().
The documentation for this class was generated from the following files:
RadioTool.h
RadioTool.cpp
Copyright 2011 C Thing Software