Meazure: MeaPositionCollection Class Reference
MeaPositionCollection Class Reference
Represents a collection of positions.
#include <PositionCollection.h>
Public Member Functions
~MeaPositionCollection ()
Destroys a position collection object and the positions objects it contains.
bool Empty () const
Indicates if there are any positions stored in the object.
unsigned int Size () const
Returns the number of positions stored in the object.
void Add (MeaPosition *position)
Adds the specified position to the collection of positions.
void Set (int posIndex, MeaPosition *position)
Replaces the specified position at the specified location in the collection.
MeaPosition & Get (int posIndex)
Returns the position object at the specified location in the collection.
void Delete (int posIndex)
Removes the position object from the specified location in the collection and destroys the object.
void DeleteAll ()
Removes all positions from the collection and destroys the position objects.
void Save (MeaXMLWriter &writer) const
Saves all positions in the collection to the log file.
Private Types
typedef std::map< int, MeaPosition * > PositionMap
Maps indices to position objects.
Private Attributes
PositionMap m_posMap
Collection of positions.
Detailed Description
Represents a collection of positions.
A position log consists of a collection of positions. In turn, a position consists of on or more points depending on the measurement tool.
Member Function Documentation
Add()
void MeaPositionCollection::Add (MeaPosition * position)
Adds the specified position to the collection of positions.
Parameters
position [in] Position to add to the collection.
References m_posMap, and Size().
Referenced by MeaPositionLogMgr::ProcessPositionNode(), and MeaPositionLogMgr::RecordPosition().
Delete()
void MeaPositionCollection::Delete (int posIndex)
Removes the position object from the specified location in the collection and destroys the object.
Parameters
posIndex [in] Zero based index indicating where in the collection to delete a position.
Exceptions
std::out_of_range if the specified position is out of bounds
References m_posMap.
Referenced by MeaPositionLogMgr::DeletePosition().
Empty()
bool MeaPositionCollection::Empty () const inline
Indicates if there are any positions stored in the object.
Returns
true if there are positions.
References m_posMap.
Referenced by MeaPositionLogMgr::HavePositions().
Get()
MeaPosition & MeaPositionCollection::Get (int posIndex)
Returns the position object at the specified location in the collection.
Parameters
posIndex [in] Zero based index into the collection.
Returns
Position object located at the specified location in the collection.
Exceptions
std::out_of_range if the specified position is out of bounds
References m_posMap.
Referenced by MeaPositionLogMgr::GetPosition(), and MeaPositionLogMgr::ShowPosition().
Save()
void MeaPositionCollection::Save (MeaXMLWriter & writer) const
Saves all positions in the collection to the log file.
Parameters
writer [in] Provides ability to write a position to the log.
References m_posMap.
Referenced by MeaPositionLogMgr::WritePositionsSection().
Set()
void MeaPositionCollection::Set (int posIndex, MeaPosition * position)
Replaces the specified position at the specified location in the collection.
Parameters
posIndex [in] Zero based index indicating where in the collection to place the position.
position [in] Position object to place in the collection.
Exceptions
std::out_of_range if the specified position is out of bounds
References m_posMap.
Referenced by MeaPositionLogMgr::ReplacePosition().
Size()
unsigned int MeaPositionCollection::Size () const inline
Returns the number of positions stored in the object.
Returns
Number of positions.
References m_posMap.
Referenced by Add(), MeaPositionLogMgr::NumPositions(), MeaPositionLogMgr::RecordPosition(), and MeaPositionLogMgr::ShowPosition().
The documentation for this class was generated from the following files:
PositionCollection.h
PositionCollection.cpp
Copyright 2011 C Thing Software