Meazure: MeaDataWin Class Reference
MeaDataWin Class Reference
A popup data display window.
#include <DataWin.h>
Public Member Functions
MeaDataWin ()
Constructs a data window.
virtual ~MeaDataWin ()
Destroys a data window.
bool Create (BYTE opacity, UINT xLabelId=kNoLabelId, UINT yLabelId=kNoLabelId, UINT wLabelId=kNoLabelId, UINT hLabelId=kNoLabelId, UINT dLabelId=kNoLabelId, UINT aLabelId=kNoLabelId, const CWnd *parent=NULL)
Creates the window for the data display.
void ShowXY (const FPOINT &point)
Displays the specified x and y coordinates.
void ShowWH (const FSIZE &size)
Displays the specified width and height.
void ShowDistance (const FSIZE &dist)
Displays a diagonal distance based on the specified width and height.
void ShowDistance (double dist)
Displays the specified distance.
void ShowAngle (double angle)
Displays the specified angle.
void Update (const CWnd &centerWin)
Displays the currently set data in the window.
void Update (const CRect &rect)
Displays the currently set data in the window.
void Show ()
Shows the data window, if the window is armed.
void Hide ()
Hides the data window.
void Strobe ()
Flashes the text in the data window once.
void SetOpacity (BYTE opacity)
Sets the opacity of the data window.
Static Public Member Functions
static void Arm (bool armed)
Arms the data window so that it can be displayed when the Show method is called.
static bool IsArmed ()
Indicates whether the data window can be displayed.
static void SaveProfile (MeaProfile &profile)
Persists the display settings of the data window to the specified profile object.
static void LoadProfile (MeaProfile &profile)
Restores the display settings of the data window from the specified profile object.
static void MasterReset ()
Called when the master reset is activated.
Static Public Attributes
static const bool kDefArmed = true
Indicates whether to display data windows by default.
static const int kNoLabelId = 0xffff
Indicates a data window label has not been specified.
Protected Member Functions
afx_msg void OnDestroy ()
Performs cleanup of objects created in the Create method.
afx_msg void OnPaint ()
Draws the data window.
afx_msg void OnTimer (UINT_PTR timerId)
Called in response to the flash timer so that the data window can be strobed.
Private Types
enum DrawState {
Normal ,
Inverted
}
Specifies how the data window is drawn in support of strobing the data window.
Private Member Functions
int CalcWidth ()
Calculates the width for the data window based on the width of the label, the width of the maximum data value and the display font.
void DrawWin (CDC &dc)
Draws the data window into the specified device context.
Private Attributes
CString m_xLabel
Label for the x coordinate data.
CString m_yLabel
Label for the y coordinate data.
CString m_wLabel
Label for the width data.
CString m_hLabel
Label for the height data.
CString m_dLabel
Label for the distance data.
CString m_aLabel
Label for the angle data.
CString m_xData
X coordinate data converted to a string.
CString m_yData
Y coordinate data converted to a string.
CString m_wData
Width data converted to a string.
CString m_hData
Height data converted to a string.
CString m_dData
Distance data converted to a string.
CString m_aData
Angle data converted to a string.
const CWnd * m_parent
Parent window or NULL if data window is floating.
CFont m_font
Font for the data display.
LONG m_textHeight
Height of the text, in pixels.
LONG m_winHeight
Height of the data window, in pixels.
int m_dataOffset
Position for the data strings, in pixels.
DrawState m_drawState
Indicates how the data window should be drawn.
int m_flashCount
Window flash interval, in milliseconds.
BYTE m_opacity
Data window opacity, 0 (transparent) to 255 (opaque).
Static Private Attributes
static bool m_armed = kDefArmed
Indicates if the data window is allowed to be displayed.
static SIZE m_margin = { 3, 1 }
Margin between the data text and the window border, in pixels.
static UINT m_flashInterval = 100
Window flash interval, in milliseconds.
Detailed Description
A popup data display window.
A data display window is attached to each radio tool's crosshair and a corner of the Window Tool. When the user hovers over a crosshair and while the user drags the crosshair, the data display window is shown and provides a continues readout of the measurements appropriate to the tool. The user can set a preference to not display the data windows.
Member Enumeration Documentation
DrawState
enum MeaDataWin::DrawState private
Specifies how the data window is drawn in support of strobing the data window.
Enumerator
Normal
Draw the data window in its normal appearance.
Inverted
Draw the data window with its background and text colors swapped.
Constructor & Destructor Documentation
MeaDataWin()
MeaDataWin::MeaDataWin ()
Constructs a data window.
To use the data window, its Create method must be called and the window must be displayed using the Show method.
Member Function Documentation
Arm()
static void MeaDataWin::Arm (bool armed) inline static
Arms the data window so that it can be displayed when the Show method is called.
Parameters
armed [in] Specifies whether the data window is allowed to be displayed.
References m_armed.
Referenced by CChildView::ApplyPreferences().
CalcWidth()
int MeaDataWin::CalcWidth () private
Calculates the width for the data window based on the width of the label, the width of the maximum data value and the display font.
Returns
Width of the data window, in pixels.
References MeaLayout::CalcLength(), FSIZE::cx, FSIZE::cy, MeaUnitsMgr::Format(), MeaUnitsMgr::FormatConvertAngle(), MeaScreenMgr::GetVirtualRect(), MeaUnitsMgr::GetWidthHeight(), MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaSingleton_T< MeaScreenMgr >::Instance(), MeaSingleton_T< MeaToolMgr >::Instance(), MeaAngleTool::kToolName, m_dataOffset, m_font, m_margin, MeaD, MeaH, MeaW, MeaX, and MeaY.
Referenced by Show().
Create()
bool MeaDataWin::Create (BYTE opacity, UINT xLabelId = kNoLabelId, UINT yLabelId = kNoLabelId, UINT wLabelId = kNoLabelId, UINT hLabelId = kNoLabelId, UINT dLabelId = kNoLabelId, UINT aLabelId = kNoLabelId, const CWnd * parent = NULL)
Creates the window for the data display.
This method must be called prior to calling the Show method. A data item is displayed in the window if its label resource ID is a value other than kNoLabelId.
Parameters
opacity [in] Opacity for the window, where 0 is completely transparent and 255 is completely opaque.
xLabelId [in] String resource ID for the x coordinate label.
yLabelId [in] String resource ID for the y coordinate label.
wLabelId [in] String resource ID for the width label.
hLabelId [in] String resource ID for the height coordinate label.
dLabelId [in] String resource ID for the distance label.
aLabelId [in] String resource ID for the angle label.
parent [in] Parent window for the data window if it is used as a child window. Typically, this parameter is NULL, which creates a floating window.
Returns
true if the window is successfully created.
References HaveLayeredWindows(), kNoLabelId, m_aLabel, m_dataOffset, m_dLabel, m_font, m_hLabel, m_margin, m_parent, m_textHeight, m_winHeight, m_wLabel, m_xLabel, m_yLabel, SetOpacity(), and WS_EX_LAYERED.
Referenced by MeaAngleTool::Create(), MeaCircleTool::Create(), MeaCursorTool::Create(), MeaLineTool::Create(), MeaPointTool::Create(), MeaRectTool::Create(), MeaWindowTool::Create(), and MeaToolsPrefs::OnInitDialog().
DrawWin()
void MeaDataWin::DrawWin (CDC & dc) private
Draws the data window into the specified device context.
Parameters
dc [in] Device context into which the data window is drawn.
References m_aData, m_aLabel, m_dataOffset, m_dData, m_dLabel, m_drawState, m_font, m_hData, m_hLabel, m_margin, m_textHeight, m_wData, m_wLabel, m_xData, m_xLabel, m_yData, m_yLabel, and Normal.
Referenced by OnPaint().
IsArmed()
static bool MeaDataWin::IsArmed () inline static
Indicates whether the data window can be displayed.
Returns
true if the data window is allowed to be displayed using the Show method.
References m_armed.
Referenced by CChildView::OnPreferences(), MeaCursorTool::Update(), and MeaWindowTool::Update().
LoadProfile()
void MeaDataWin::LoadProfile (MeaProfile & profile) static
Restores the display settings of the data window from the specified profile object.
Parameters
profile [in] Profile object from which the data window state is restored.
References m_armed, MeaProfile::ReadBool(), and MeaProfile::UserInitiated().
Referenced by CChildView::LoadProfile().
MasterReset()
void MeaDataWin::MasterReset () static
Called when the master reset is activated.
Causes the data window to load its default settings.
References kDefArmed, and m_armed.
Referenced by CChildView::MasterReset().
OnTimer()
void MeaDataWin::OnTimer (UINT_PTR timerId) protected
Called in response to the flash timer so that the data window can be strobed.
Parameters
timerId [in] ID of the timer.
References Inverted, m_drawState, m_flashCount, m_flashInterval, and Normal.
SaveProfile()
void MeaDataWin::SaveProfile (MeaProfile & profile) static
Persists the display settings of the data window to the specified profile object.
Parameters
profile [in] Profile object into which the data window state is persisted.
References m_armed, MeaProfile::UserInitiated(), and MeaProfile::WriteBool().
Referenced by CChildView::SaveProfile().
SetOpacity()
void MeaDataWin::SetOpacity (BYTE opacity)
Sets the opacity of the data window.
Parameters
opacity [in] Opacity of the data window where 0 is transparent and 255 is opaque.
References LWA_ALPHA, m_opacity, m_parent, and SetLayeredWindowAttributes.
Referenced by MeaAngleTool::ColorsChanged(), MeaCircleTool::ColorsChanged(), MeaCursorTool::ColorsChanged(), MeaLineTool::ColorsChanged(), MeaPointTool::ColorsChanged(), MeaRectTool::ColorsChanged(), MeaWindowTool::ColorsChanged(), Create(), MeaToolsPrefs::OnHScroll(), and MeaToolsPrefs::OnInitDialog().
Show()
void MeaDataWin::Show ()
Shows the data window, if the window is armed.
If the window is not armed, calling Show does not display the window.
References CalcWidth(), m_armed, m_parent, and m_winHeight.
Referenced by MeaCursorTool::Enable(), MeaWindowTool::Enable(), MeaAngleTool::OnCHEnter(), MeaCircleTool::OnCHEnter(), MeaLineTool::OnCHEnter(), MeaPointTool::OnCHEnter(), MeaRectTool::OnCHEnter(), MeaToolsPrefs::OnInitDialog(), MeaCursorTool::Update(), and MeaWindowTool::Update().
ShowAngle()
void MeaDataWin::ShowAngle (double angle) inline
Displays the specified angle.
For the value to be displayed, a string resource ID value must be specified for the aLabelId parameter of the Create method.
Parameters
angle [in] Angle to display.
References MeaUnitsMgr::FormatConvertAngle(), MeaSingleton_T< MeaUnitsMgr >::Instance(), and m_aData.
Referenced by MeaAngleTool::Update().
ShowDistance() [1/2]
void MeaDataWin::ShowDistance (const FSIZE & dist) inline
Displays a diagonal distance based on the specified width and height.
For the value to be displayed, a string resource ID value must be specified for the dLabelId parameter of the Create method.
Parameters
dist [in] Dimensions used to calculate the distance.
References MeaLayout::CalcLength(), FSIZE::cx, FSIZE::cy, MeaUnitsMgr::Format(), MeaSingleton_T< MeaUnitsMgr >::Instance(), m_dData, and MeaD.
Referenced by MeaCircleTool::Update(), and MeaLineTool::Update().
ShowDistance() [2/2]
void MeaDataWin::ShowDistance (double dist) inline
Displays the specified distance.
For the value to be displayed, a string resource ID value must be specified for the dLabelId parameter of the Create method.
Parameters
dist [in] Distance to display.
References MeaUnitsMgr::Format(), MeaSingleton_T< MeaUnitsMgr >::Instance(), m_dData, and MeaD.
ShowWH()
void MeaDataWin::ShowWH (const FSIZE & size) inline
Displays the specified width and height.
For the values to be displayed, a string resource ID value must be specified for the wLabelId and hLabelId parameters of the Create method.
Parameters
size [in] Dimensions to display.
References FSIZE::cx, FSIZE::cy, MeaUnitsMgr::Format(), MeaSingleton_T< MeaUnitsMgr >::Instance(), m_hData, m_wData, MeaH, and MeaW.
Referenced by MeaRectTool::Update(), and MeaWindowTool::Update().
ShowXY()
void MeaDataWin::ShowXY (const FPOINT & point) inline
Displays the specified x and y coordinates.
For the values to be displayed, a string resource ID value must be specified for the xLabelId and yLabelId parameters of the Create method.
Parameters
point [in] Coordinates to display.
References MeaUnitsMgr::Format(), MeaSingleton_T< MeaUnitsMgr >::Instance(), m_xData, m_yData, MeaX, MeaY, FPOINT::x, and FPOINT::y.
Referenced by MeaAngleTool::Update(), MeaCircleTool::Update(), MeaCursorTool::Update(), MeaLineTool::Update(), MeaPointTool::Update(), and MeaRectTool::Update().
Strobe()
void MeaDataWin::Strobe ()
Flashes the text in the data window once.
Typically used to indicate that a tool position has been recorded.
References Inverted, m_drawState, m_flashCount, and m_flashInterval.
Referenced by MeaAngleTool::Strobe(), MeaCircleTool::Strobe(), MeaCursorTool::Strobe(), MeaLineTool::Strobe(), MeaPointTool::Strobe(), MeaRectTool::Strobe(), and MeaWindowTool::Strobe().
Update() [1/2]
void MeaDataWin::Update (const CRect & rect)
Displays the currently set data in the window.
Parameters
rect [in] The data window is displayed adjacent to the corner of this rectangle.
References MeaScreenMgr::GetScreenIter(), MeaScreenMgr::GetScreenRect(), and MeaSingleton_T< MeaScreenMgr >::Instance().
Update() [2/2]
void MeaDataWin::Update (const CWnd & centerWin) inline
Displays the currently set data in the window.
Parameters
centerWin [in] The data window is displayed adjacent to a corner of this window.
References Update().
Referenced by Update(), MeaAngleTool::Update(), MeaCircleTool::Update(), MeaCursorTool::Update(), MeaLineTool::Update(), MeaPointTool::Update(), MeaRectTool::Update(), and MeaWindowTool::Update().
The documentation for this class was generated from the following files:
DataWin.h
DataWin.cpp
Copyright 2011 C Thing Software