Meazure: MeaPositionLogMgr::Positions Class Reference
MeaPositionLogMgr::Positions Class Reference
Represents a collection of positions.
Public Member Functions
Positions ()
Constructs a position collection object.
~Positions ()
Destroys a position collection object.
bool Empty () const
Indicates if there are any positions stored in the object.
unsigned int Size () const
Returns the number of positions stored in the object.
void Add (Position *position)
Adds the specified position to the collection of positions.
void Set (int posIndex, Position *position)
Places the specified position at the specified location in the collection.
Position & Get (int posIndex)
Returns the position object at the specified location in the collection.
void Delete (int posIndex)
Removes the position object from the specified location in the collection and destroys the object.
void DeleteAll ()
Removes all positions from the collection and destroys the position objects.
void Save (int indent) const
Saves all positions in the collection to the log file.
Private Types
typedef std::map< int, Position * > PositionMap
Maps indices to position objects.
Private Attributes
PositionMap m_posMap
Collection of positions.
Detailed Description
Represents a collection of positions.
A position log consists of a collection of positions. In turn, a position consists of on or more points depending on the measurement tool.
Member Function Documentation
Add()
void MeaPositionLogMgr::Positions::Add (Position * position)
Adds the specified position to the collection of positions.
Parameters
position [in] Position to add to the collection.
Referenced by MeaPositionLogMgr::ProcessPositionNode(), and MeaPositionLogMgr::RecordPosition().
Delete()
void MeaPositionLogMgr::Positions::Delete (int posIndex)
Removes the position object from the specified location in the collection and destroys the object.
Parameters
posIndex [in] Zero based index indicating where in the collection to delete a position.
Exceptions
std::out_of_range if the specified position is out of bounds
Referenced by MeaPositionLogMgr::DeletePosition().
Empty()
bool MeaPositionLogMgr::Positions::Empty () const inline
Indicates if there are any positions stored in the object.
Returns
true if there are positions.
References m_posMap.
Referenced by MeaPositionLogMgr::HavePositions().
Get()
MeaPositionLogMgr::Position & MeaPositionLogMgr::Positions::Get (int posIndex)
Returns the position object at the specified location in the collection.
Parameters
posIndex [in] Zero based index into the collection.
Returns
Position object located at the specified location in the collection.
Exceptions
std::out_of_range if the specified position is out of bounds
Referenced by MeaPositionLogMgr::GetPosition(), and MeaPositionLogMgr::ShowPosition().
Save()
void MeaPositionLogMgr::Positions::Save (int indent) const
Saves all positions in the collection to the log file.
Parameters
indent [in] Output indentation level.
Exceptions
CFileException if there was a problem saving the position
Referenced by MeaPositionLogMgr::WritePositionsSection().
Set()
void MeaPositionLogMgr::Positions::Set (int posIndex, Position * position)
Places the specified position at the specified location in the collection.
Parameters
posIndex [in] Zero based index indicating where in the collection to place the position.
position [in] Position object to insert in the collection.
Exceptions
std::out_of_range if the specified position is out of bounds
Referenced by MeaPositionLogMgr::ReplacePosition().
Size()
unsigned int MeaPositionLogMgr::Positions::Size () const inline
Returns the number of positions stored in the object.
Returns
Number of positions.
References m_posMap.
Referenced by MeaPositionLogMgr::NumPositions(), MeaPositionLogMgr::RecordPosition(), and MeaPositionLogMgr::ShowPosition().
The documentation for this class was generated from the following files:
PositionLogMgr.h
PositionLogMgr.cpp
Copyright 2011 C Thing Software