Meazure: MeaRectTool Class Reference
MeaRectTool Class Reference
Rectangle measurement tool.
#include <RectTool.h>
Public Member Functions
MeaRectTool (MeaToolMgr &mgr, const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Constructs a new instance of a Rectangle measurement tool.
virtual ~MeaRectTool ()
Hides and then destroys the Rectangle tool.
virtual void Enable () override
Displays the Rectangle tool.
virtual void Disable () override
Hides the Rectangle tool.
virtual void Update (MeaUpdateReason reason) override
Requests that the tool update the display of its position data.
virtual bool HasRegion () override
Indicates whether the tool can define a rectangular region that can then be read for a screen capture.
virtual RECT GetRegion () override
Returns the rectangle defined by the tool.
virtual void SaveProfile (MeaProfile &profile) override
Persists the state of the tool to the specified profile object.
virtual void LoadProfile (MeaProfile &profile) override
Restores the state of the tool from the specified profile object.
virtual void EnableCrosshairs () override
Displays the tool's crosshairs.
virtual void DisableCrosshairs () override
Hides the tool's crosshairs.
virtual void Flash () override
Visually flashes the tool.
virtual void Strobe () override
Visually strobes the tool.
virtual void SetPosition (MeaDataFieldId which, int pixels) override
Sets the position of the tool.
virtual void SetPosition (const PointMap &points) override
Sets the position of the tool.
virtual const POINT & GetPosition () const override
Returns the tool's current position.
virtual void RecordPosition (MeaPosition &position) const override
Records the position of the tool.
virtual void IncPosition (MeaDataFieldId which) override
Increments the specified position field.
virtual void DecPosition (MeaDataFieldId which) override
Decrements the specified position field.
virtual PCTSTR GetToolName () const override
Returns the name of the tool.
virtual UINT GetLabelId () const override
Returns a resource ID for the string used to label this tool on the data display.
virtual void ColorsChanged () override
Called to notify the tool that the colors in the MeaColors class have been changed.
virtual void OnCHEnter (const CrossHairInfo *info) override
Called when the pointer enters one of the tool's crosshairs.
virtual void OnCHLeave (const CrossHairInfo *info) override
Called when the pointer leaves one of the tool's crosshairs.
virtual void OnCHMove (const CrossHairInfo *info) override
Called when the user attempts to drag one of the tool's crosshairs.
Public Member Functions inherited from MeaRadioTool
MeaRadioTool (MeaToolMgr &mgr, const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Constructs a new instance of an radio based measurement tool.
virtual bool IsRadioTool () override
Indicates that the derived tool is a Radio tool and cannot be enabled until any other enabled Radio tool is disabled.
virtual UINT GetLabelId () const
Returns a resource ID for the string used to label this tool on the data display.
virtual bool HasCrosshairs () const
Indicates whether the derived tool uses crosshairs.
virtual void EnableCrosshairs ()
Displays the tool's crosshairs.
virtual void DisableCrosshairs ()
Hides the tool's crosshairs.
virtual void Flash ()
Visually flashes the tool.
virtual void Strobe ()
Visually strobes the tool.
virtual bool HasRegion ()
Indicates whether the tool can define a rectangular region that can then be read for a screen capture.
virtual RECT GetRegion ()
Returns the rectangle defined by the tool.
virtual void SetPosition (const PointMap &points)
Sets the position of the tool.
virtual void RecordPosition (MeaPosition &position) const =0
Records the position of the tool.
virtual void OnMouseHook (WPARAM wParam, LPARAM lParam)
Called by the OS when the mouse pointer is moved.
Public Member Functions inherited from MeaTool
MeaTool (MeaToolMgr &mgr, const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Base class constructor.
virtual ~MeaTool ()=default
Destroys the tool.
virtual void Enable ()
Typically used by derived classes to show the tool.
virtual void Disable ()
Typically used by derived classes to hide the tool.
virtual void Update (MeaUpdateReason reason)
Used by derived classes to update the display of their data.
virtual bool IsRadioTool ()
Indicates whether the derived tool is a radio tool and cannot be enabled until any other enabled Radio tool is disabled.
virtual void SetPosition (MeaDataFieldId which, int pixels)
Sets the position of the tool.
virtual const POINT & GetPosition () const =0
Returns the tool's current position.
virtual void IncPosition (MeaDataFieldId which)
Increments the specified position field.
virtual void DecPosition (MeaDataFieldId which)
Decrements the specified position field.
virtual PCTSTR GetToolName () const =0
Returns the name of the tool.
virtual void SaveProfile (MeaProfile &profile)
Persists the state of the tool to the specified profile object.
virtual void LoadProfile (MeaProfile &profile)
Restores the state of the tool from the specified profile object.
virtual void MasterReset ()
Resets the tool to its default state.
virtual void ColorsChanged ()
Called to notify the tool that the colors in the MeaColors class have been changed.
bool IsEnabled () const
Indicates whether the tool is enabled.
Public Member Functions inherited from MeaCrossHairCallback
virtual void OnCHSelect (const CrossHairInfo *info)
Called when the left mouse button is pressed while the pointer is positioned over the crosshair.
virtual void OnCHDeselect (const CrossHairInfo *info)
Called when the left mouse button is release while the pointer is positioned over the crosshair.
virtual void OnCHMove (const CrossHairInfo *info)
Called when the user moves the mouse pointer over the crosshair while the left mouse button is pressed (i.e.
virtual void OnCHEnter (const CrossHairInfo *info)
Called when the pointer enters the crosshair window.
virtual void OnCHLeave (const CrossHairInfo *info)
Called when the pointer leaves the crosshair window.
Static Public Attributes
static constexpr PCTSTR kToolName { _T("RectTool") }
Private Member Functions
bool Create ()
Creates the tool's graphical components.
void SetPosition ()
Sets the position of the tool's crosshairs based on the current values of m_point1, and m_point2.
Private Attributes
CPoint m_point1
Location of one corner of the rectangle diagonally opposed to m_point2.
CPoint m_point2
Location of one corner of the rectangle diagonally opposed to m_point1.
CPoint * m_curPos
Points to m_point1 or m_point2 depending on which point the user is moving.
CPoint m_anchorPoint1
Location for vertical / horizontal lock when Shift is held while dragging the point 1 crosshair.
CPoint m_anchorPoint2
Location for vertical / horizontal lock when Shift is held while dragging the point 2 crosshair.
MeaCrossHair m_point1CH
Crosshair for one corner of the rectangle diagonally opposed to m_point2CH.
MeaCrossHair m_point2CH
Crosshair for one corner of the rectangle diagonally opposed to m_point1CH.
MeaRectangle m_rectangle
Rectangle connecting m_point1 and m_point2.
MeaDataWin m_dataWin1
Data window tooltip for point 1.
MeaDataWin m_dataWin2
Data window tooltip for point 2.
Static Private Attributes
static constexpr UINT kPoint1Id { 1 }
ID for the point 1 crosshair.
static constexpr UINT kPoint2Id { 2 }
ID for the point 2 crosshair.
Additional Inherited Members
Public Types inherited from MeaRadioTool
typedef std::map< CString, POINT > PointMap
Map of points used to set the position of a tool.
Protected Attributes inherited from MeaTool
MeaToolMgr & m_mgr
Tool manager.
const MeaScreenProvider & m_screenProvider
Screen information provider.
const MeaUnitsProvider & m_unitsProvider
Units information provider.
bool m_enabled
Indicates whether the tool is enabled.
Static Protected Attributes inherited from MeaTool
static const CPoint m_defaultPos
A default position used by tools that do not have a defined position.
Detailed Description
Rectangle measurement tool.
This tool provides a rectangle to measure an arbitrary rectangular area of the screen. Two crosshairs are provided one at the either end of the rectangle's diagonal (points 1 and 2). Each crosshair can be arbitrarily positioned, which results in moving the rectangle.
Constructor & Destructor Documentation
MeaRectTool()
MeaRectTool::MeaRectTool (MeaToolMgr & mgr, const MeaScreenProvider & screenProvider, const MeaUnitsProvider & unitsProvider) explicit
Constructs a new instance of a Rectangle measurement tool.
To use a newly constructed Rectangle tool, the Enable() method must be called. Enable() will call the Create() method the first time it is called if Create() has not previously been called.
Parameters
mgr [in] Tool manager parent of the Rectangle tool
screenProvider [in] Screen information provider
unitsProvider [in] Units information provider
References MeaScreenProvider::GetCenter(), m_anchorPoint1, m_anchorPoint2, m_point1, m_point2, and MeaTool::m_screenProvider.
Member Function Documentation
ColorsChanged()
void MeaRectTool::ColorsChanged () override virtual
Called to notify the tool that the colors in the MeaColors class have been changed.
The crosshairs and line colors are updated as well as the crosshair and data window opacities.
Reimplemented from MeaTool.
References MeaColors::CrossHairBack, MeaColors::CrossHairBorder, MeaColors::CrossHairHilite, MeaColors::CrossHairOpacity, MeaColors::Get(), MeaColors::GetA(), MeaColors::LineFore, m_dataWin1, m_dataWin2, m_point1CH, m_point2CH, m_rectangle, MeaRectangle::SetColor(), MeaCrossHair::SetColors(), MeaCrossHair::SetOpacity(), and MeaDataWin::SetOpacity().
Create()
bool MeaRectTool::Create () private
Creates the tool's graphical components.
The components include the crosshairs, rectangle and data windows. The Enable() method must be called to make the tool visible.
Returns
true if the window is successfully created.
References MeaDataWin::Create(), MeaCrossHair::Create(), MeaRectangle::Create(), MeaColors::CrossHairBack, MeaColors::CrossHairBorder, MeaColors::CrossHairHilite, MeaColors::CrossHairOpacity, MeaColors::Get(), MeaColors::GetA(), kPoint1Id, kPoint2Id, m_dataWin1, m_dataWin2, m_point1CH, m_point2CH, m_rectangle, MeaGraphic::SetAbove(), and SetPosition().
Referenced by Enable().
DecPosition()
void MeaRectTool::DecPosition (MeaDataFieldId which) override virtual
Decrements the specified position field.
Parameters
which Field to decrement
Reimplemented from MeaTool.
References m_point1, m_point2, MeaX1Field, MeaX2Field, MeaY1Field, MeaY2Field, and SetPosition().
Disable()
void MeaRectTool::Disable () override virtual
Hides the Rectangle tool.
Reimplemented from MeaTool.
References MeaTool::Disable(), DisableCrosshairs(), MeaDataWin::Hide(), MeaRectangle::Hide(), MeaTool::IsEnabled(), m_dataWin1, m_dataWin2, and m_rectangle.
Referenced by ~MeaRectTool().
DisableCrosshairs()
void MeaRectTool::DisableCrosshairs () override virtual
Hides the tool's crosshairs.
Reimplemented from MeaRadioTool.
References MeaGraphic::Hide(), m_point1CH, and m_point2CH.
Referenced by Disable().
Enable()
void MeaRectTool::Enable () override virtual
Displays the Rectangle tool.
If the Create() method has not been previously called, it will be called by Enable.
Reimplemented from MeaTool.
References Create(), MeaTool::Enable(), EnableCrosshairs(), MeaToolMgr::EnableRegionFields(), Flash(), MeaTool::IsEnabled(), MeaTool::m_mgr, m_rectangle, MeaAngleField, MeaAreaField, MeaAspectField, MeaDistanceField, MeaHeightField, MeaWidthField, MeaX1Field, MeaX2Field, MeaY1Field, MeaY2Field, NormalUpdate, MeaToolMgr::SetStatus(), MeaGraphic::Show(), and Update().
EnableCrosshairs()
void MeaRectTool::EnableCrosshairs () override virtual
Displays the tool's crosshairs.
If the Enable() method has not been previously called, this method has no effect.
Reimplemented from MeaRadioTool.
References MeaToolMgr::CrosshairsEnabled(), MeaTool::m_mgr, m_point1CH, m_point2CH, and MeaGraphic::Show().
Referenced by Enable().
Flash()
void MeaRectTool::Flash () override virtual
Visually flashes the tool.
The tool crosshairs are cycled between a hilite color and their normal color a number of times. Flashing the tool helps the user find it on the screen.
Reimplemented from MeaRadioTool.
References MeaCrossHair::Flash(), m_point1CH, and m_point2CH.
Referenced by Enable().
GetLabelId()
UINT MeaRectTool::GetLabelId () const override virtual
Returns a resource ID for the string used to label this tool on the data display.
Returns
Resource ID for the label.
Reimplemented from MeaRadioTool.
GetPosition()
const POINT & MeaRectTool::GetPosition () const override virtual
Returns the tool's current position.
The current position is the position of the last crosshair entered or moved. The default position is the location of point 1.
Returns
Current position
Implements MeaTool.
References m_curPos.
GetRegion()
RECT MeaRectTool::GetRegion () override virtual
Returns the rectangle defined by the tool.
This rectangle can then be read for a screen capture.
Returns
The rectangle formed by the tool.
Reimplemented from MeaRadioTool.
References m_point1, and m_point2.
Referenced by HasRegion().
GetToolName()
PCTSTR MeaRectTool::GetToolName () const override virtual
Returns the name of the tool.
Each tool has a unique name which is used to identify the tool in profiles and position logs.
Returns
Always "RectTool". The memory for the string is owned by the tool.
Implements MeaTool.
HasRegion()
bool MeaRectTool::HasRegion () override virtual
Indicates whether the tool can define a rectangular region that can then be read for a screen capture.
The rectangle tool defines such a rectangular area.
Returns
true if the tool defines a non-empty rectangular region.
Reimplemented from MeaRadioTool.
References GetRegion().
IncPosition()
void MeaRectTool::IncPosition (MeaDataFieldId which) override virtual
Increments the specified position field.
Parameters
which Field to increment
Reimplemented from MeaTool.
References m_point1, m_point2, MeaX1Field, MeaX2Field, MeaY1Field, MeaY2Field, and SetPosition().
LoadProfile()
void MeaRectTool::LoadProfile (MeaProfile & profile) override virtual
Restores the state of the tool from the specified profile object.
Parameters
profile [in] The source for the state information. Typically an MeaFileProfile or MeaRegistryProfile object.
Reimplemented from MeaTool.
References MeaUnitsProvider::ConvertPos(), m_anchorPoint1, m_anchorPoint2, m_point1, m_point2, MeaTool::m_unitsProvider, MeaProfile::ReadDbl(), SetPosition(), MeaUnitsProvider::UnconvertPos(), MeaFPoint::x, and MeaFPoint::y.
OnCHEnter()
void MeaRectTool::OnCHEnter (const CrossHairInfo * info) override virtual
Called when the pointer enters one of the tool's crosshairs.
The crosshair entered is identified by the MeaCrossHairCallback::CrossHairInfo structure passed to the method.
Parameters
info [in] Crosshair information structure
Reimplemented from MeaCrossHairCallback.
References MeaCrossHairCallback::CrossHairInfo::id, kPoint1Id, m_dataWin1, m_dataWin2, NormalUpdate, MeaDataWin::Show(), and Update().
OnCHLeave()
void MeaRectTool::OnCHLeave (const CrossHairInfo * info) override virtual
Called when the pointer leaves one of the tool's crosshairs.
The crosshair exited is identified by the MeaCrossHairCallback::CrossHairInfo structure passed to the method.
Parameters
info [in] Crosshair information structure
Reimplemented from MeaCrossHairCallback.
References MeaDataWin::Hide(), MeaCrossHairCallback::CrossHairInfo::id, kPoint1Id, m_dataWin1, and m_dataWin2.
OnCHMove()
void MeaRectTool::OnCHMove (const CrossHairInfo * info) override virtual
Called when the user attempts to drag one of the tool's crosshairs.
The crosshair to be moved is identified by the MeaCrossHairCallback::CrossHairInfo structure passed to the method. The info parameter indicates where the crosshair is to be moved and the tool actually moves the crosshair to the new position. This allows the tool to perform vertical or horizontal locking and move the entire tool depending on which keyboard modifiers are pressed during the drag.
Parameters
info [in] Crosshair information structure
Reimplemented from MeaCrossHairCallback.
References MeaCrossHairCallback::CrossHairInfo::center, MeaCrossHairCallback::CrossHairInfo::flags, MeaCrossHairCallback::CrossHairInfo::id, MeaGeometry::IsVerticallyOriented(), kPoint1Id, MeaScreenProvider::LimitPosition(), m_anchorPoint1, m_anchorPoint2, m_curPos, m_point1, m_point1CH, m_point2, m_point2CH, m_rectangle, MeaTool::m_screenProvider, NormalUpdate, MeaCrossHair::SetPosition(), MeaRectangle::SetPosition(), and Update().
RecordPosition()
void MeaRectTool::RecordPosition (MeaPosition & position) const override virtual
Records the position of the tool.
This method is called by the position log manager to record a position.
Parameters
position [in] The tool's current position is recorded into the position log manager's position object.
Implements MeaRadioTool.
References MeaGeometry::CalcAngle(), MeaUnitsProvider::ConvertAngle(), MeaUnitsProvider::ConvertCoord(), MeaUnitsProvider::GetWidthHeight(), m_point1, m_point2, MeaTool::m_unitsProvider, MeaPosition::RecordAngle(), MeaPosition::RecordDistance(), MeaPosition::RecordRectArea(), MeaPosition::RecordWH(), MeaPosition::RecordXY1(), MeaPosition::RecordXY2(), and MeaPosition::SetToolName().
SaveProfile()
void MeaRectTool::SaveProfile (MeaProfile & profile) override virtual
Persists the state of the tool to the specified profile object.
Parameters
profile [in] The destination for the state information. Typically an MeaFileProfile or MeaRegistryProfile object.
Reimplemented from MeaTool.
References MeaUnitsProvider::ConvertPos(), m_point1, m_point2, MeaTool::m_unitsProvider, MeaProfile::WriteStr(), MeaFPoint::x, and MeaFPoint::y.
SetPosition() [1/2]
void MeaRectTool::SetPosition (const PointMap & points) override virtual
Sets the position of the tool.
This method is called by the position log manager to play back a tool's position that was previously recorded using the RecordPosition method.
Parameters
points [in] Map of positions for the tool's crosshairs.
Reimplemented from MeaRadioTool.
References m_point1, m_point2, NormalUpdate, SetPosition(), and Update().
SetPosition() [2/2]
void MeaRectTool::SetPosition (MeaDataFieldId which, int pixels) override virtual
Sets the position of the tool.
This method sets the position one location component at a time. For example, the x position of the point 1 crosshair is specified by calling this method with the new position and specifying the MeaX1Field for the which parameter.
Parameters
which [in] Position component
pixels [in] Position to set for the component, in pixels
Reimplemented from MeaTool.
References MeaScreenProvider::LimitPosition(), m_curPos, m_point1, m_point1CH, m_point2, m_point2CH, m_rectangle, MeaTool::m_screenProvider, MeaX1Field, MeaX2Field, MeaY1Field, MeaY2Field, NormalUpdate, MeaCrossHair::SetPosition(), MeaRectangle::SetPosition(), and Update().
Strobe()
void MeaRectTool::Strobe () override virtual
Visually strobes the tool.
The tool crosshairs are cycled between a hilite color and their normal color once. In addition, the data windows attached to the crosshairs are cycled between hidden and visible. Strobing the tool is done to visually confirm region capture and position recording.
Reimplemented from MeaRadioTool.
References MeaCrossHair::Flash(), MeaCrossHair::kStrobeCount, m_dataWin1, m_dataWin2, m_point1CH, m_point2CH, and MeaDataWin::Strobe().
Update()
void MeaRectTool::Update (MeaUpdateReason reason) override virtual
Requests that the tool update the display of its position data.
Parameters
reason [in] Reason why the update has been requested
Reimplemented from MeaTool.
References MeaGeometry::CalcAngle(), MeaUnitsProvider::ConvertCoord(), MeaUnitsProvider::GetWidthHeight(), MeaTool::IsEnabled(), m_curPos, m_dataWin1, m_dataWin2, MeaTool::m_mgr, m_point1, m_point1CH, m_point2, m_point2CH, MeaTool::m_unitsProvider, MeaToolMgr::ShowAngle(), MeaToolMgr::ShowAspect(), MeaToolMgr::ShowDistance(), MeaToolMgr::ShowRectArea(), MeaToolMgr::ShowWH(), MeaDataWin::ShowWH(), MeaDataWin::ShowXY(), MeaToolMgr::ShowXY1(), MeaToolMgr::ShowXY2(), MeaDataWin::Update(), MeaTool::Update(), and MeaToolMgr::UpdateScreenInfo().
Referenced by Enable(), OnCHEnter(), OnCHMove(), and SetPosition().
The documentation for this class was generated from the following files:
RectTool.h
RectTool.cpp
Copyright 2011 C Thing Software