Meazure: MeaXMLParserHandler Class Reference
MeaXMLParserHandler Class Reference
Mix-in class for XML parser callback methods.
#include <XMLParser.h>
Public Member Functions
MeaXMLParserHandler ()
Empty constructor for the handler class.
virtual ~MeaXMLParserHandler ()
Empty destructor for the handler class.
virtual void StartElementHandler (const CString &container, const CString &elementName, const MeaXMLAttributes &attrs)
Called when a new element is opened (e.g.
virtual void EndElementHandler (const CString &container, const CString &elementName)
Called when an element is closed (e.g.
virtual void CharacterDataHandler (const CString &container, const CString &data)
Called for all character data encountered between elements.
virtual void ParseEntity (MeaXMLParser &parser, const CString &pathname)
Called to parse an external entity.
virtual CString GetFilePathname ()
Returns the pathname of the currently parsed file.
Detailed Description
Mix-in class for XML parser callback methods.
A class that wants XML parsing services mix-in inherits from this class, overrides the methods of this class for the events of interest, creates an instance of the MeaXMLParser class and points it at the XML file to parse. The parser calls back using the methods of this class to indicate various XML parsing events. This is classic SAX parsing behavior. The class contains noop implementations for the method.
Constructor & Destructor Documentation
MeaXMLParserHandler()
MeaXMLParserHandler::MeaXMLParserHandler () inline
Empty constructor for the handler class.
This class should be thought of more as an interface than as an instantiable class.
Member Function Documentation
CharacterDataHandler()
void MeaXMLParserHandler::CharacterDataHandler (const CString & container, const CString & data) virtual
Called for all character data encountered between elements.
Note that this method will be called for all character data including whitespace between consecutive elements. The DTD must must be used to determine what whitespace is relevant.
Parameters
container [in] Name of the closest open element containing the character data.
data [in] Character data.
Reimplemented in MeaFileProfile.
Referenced by MeaXMLParser::CharacterDataHandler().
EndElementHandler()
void MeaXMLParserHandler::EndElementHandler (const CString & container, const CString & elementName) virtual
Called when an element is closed (e.g.
</foo> or <foo/>).
Parameters
container [in] Parent element.
elementName [in] Name of the element being closed.
Referenced by MeaXMLParser::EndElementHandler().
GetFilePathname()
CString MeaXMLParserHandler::GetFilePathname () virtual
Returns the pathname of the currently parsed file.
Returns
Pathname of the file currently being parsed. This class's implementation of this method returns the empty string.
Reimplemented in MeaFileProfile, and MeaPositionLogMgr.
Referenced by MeaXMLParser::HandleParserError(), and MeaXMLParser::HandleValidationError().
ParseEntity()
void MeaXMLParserHandler::ParseEntity (MeaXMLParser & parser, const CString & pathname) virtual
Called to parse an external entity.
Parameters
parser [in] Current XML parser.
pathname [in] Pathname of the external entity.
Reimplemented in MeaFileProfile, and MeaPositionLogMgr.
Referenced by MeaXMLParser::ExternalEntityRefHandler().
StartElementHandler()
void MeaXMLParserHandler::StartElementHandler (const CString & container, const CString & elementName, const MeaXMLAttributes & attrs) virtual
Called when a new element is opened (e.g.
<foo> or <foo/>).
Parameters
container [in] Parent element.
elementName [in] Name of the element being opened.
attrs [in] Attributes associated with the element.
Reimplemented in MeaFileProfile.
Referenced by MeaXMLParser::StartElementHandler().
The documentation for this class was generated from the following files:
XMLParser.h
XMLParser.cpp
Copyright 2011 C Thing Software