Meazure: MeaScreenMgr::Screen Class Reference
MeaScreenMgr::Screen Class Reference
Represents a single display screen.
Public Member Functions
Screen (MeaScreenMgr &mgr, LPCRECT rect)
Constructs a display screen object.
virtual ~Screen ()
Destroys a display screen object.
const CRect & GetRect () const
Returns the screen rectangle.
const CPoint & GetCenter () const
Determines the center of the screen.
void SetScreenRes (bool useManualRes, const FSIZE *manualRes=NULL)
Sets the resolution of the screen, in pixels per inch.
void GetScreenRes (bool &useManualRes, FSIZE &manualRes) const
Obtains the currently set manual screen resolution, if set.
const FSIZE & GetScreenRes () const
Obtains the current screen resolution.
bool IsManualRes () const
Indicates if the screen resolution has been manually set.
void SetPrimary (bool primary)
In multiple monitor environments, one of the monitors is designated as the primary.
bool IsPrimary () const
Indicates if this is the primary screen.
void SetCalInInches (bool calInInches)
Specifies whether the resolution calibration has been performed in inches or centimeters.
bool GetCalInInches () const
Indicates whether the resolution calibration has been performed in inches or centimeters.
void SetName (LPCTSTR name)
Sets a descriptive name for the screen.
CString GetName () const
Returns the descriptive name for the screen.
Private Attributes
MeaScreenMgr & m_mgr
Parent manager.
CRect m_rect
Screen rectangle.
CPoint m_center
Center point of the screen.
FSIZE m_currentRes
Current screen resolution, pixels per inch.
FSIZE m_manualRes
Manually calibrated resolution, pixels per inch.
bool m_useManualRes
Indicates if manually calibrated resolution is used.
bool m_calInInches
Indicates if calibration in inches or centimeters.
bool m_primary
Indicates if this is the primary screen.
CString m_name
Descriptive name for the screen.
Detailed Description
Represents a single display screen.
Constructor & Destructor Documentation
Screen()
MeaScreenMgr::Screen::Screen (MeaScreenMgr & mgr, LPCRECT rect)
Constructs a display screen object.
Parameters
mgr [in] Parent manager.
rect [in] Rectangle representing the screen, in pixels. In multiple monitor environments, the screen rectangle can have negative coordinates.
References FSIZE::cx, FSIZE::cy, m_center, m_currentRes, m_manualRes, and m_rect.
Member Function Documentation
GetCalInInches()
bool MeaScreenMgr::Screen::GetCalInInches () const inline
Indicates whether the resolution calibration has been performed in inches or centimeters.
Returns
true if the calibration has been performed in inches.
References m_calInInches.
GetCenter()
const CPoint & MeaScreenMgr::Screen::GetCenter () const inline
Determines the center of the screen.
Returns
Center point of the screen.
References m_center.
GetName()
CString MeaScreenMgr::Screen::GetName () const inline
Returns the descriptive name for the screen.
Returns
Name for the screen or the empty string if there is no name.
References m_name.
GetRect()
const CRect & MeaScreenMgr::Screen::GetRect () const inline
Returns the screen rectangle.
Note that in multiple monitor environments, the screen rectangle can have negative coordinates.
Returns
Screen rectangle, in pixels.
References m_rect.
GetScreenRes() [1/2]
const FSIZE & MeaScreenMgr::Screen::GetScreenRes () const inline
Obtains the current screen resolution.
If the resolution has been manually calibrated, it is returned. Otherwise the operating system reported resolution is returned.
Returns
Screen resolution, in pixels per inch.
References m_currentRes.
GetScreenRes() [2/2]
void MeaScreenMgr::Screen::GetScreenRes (bool & useManualRes, FSIZE & manualRes) const inline
Obtains the currently set manual screen resolution, if set.
Parameters
useManualRes [out] Indicates whether the manually calibrated resolution is used (true) or the operating system resolution (false).
manualRes [out] Manually calibrated resolution, in pixels per inch.
References m_manualRes, and m_useManualRes.
IsManualRes()
bool MeaScreenMgr::Screen::IsManualRes () const inline
Indicates if the screen resolution has been manually set.
Returns
true if the screen resolution has been set manually.
References m_useManualRes.
IsPrimary()
bool MeaScreenMgr::Screen::IsPrimary () const inline
Indicates if this is the primary screen.
Returns
true if this is the primary screen.
References m_primary.
SetCalInInches()
void MeaScreenMgr::Screen::SetCalInInches (bool calInInches) inline
Specifies whether the resolution calibration has been performed in inches or centimeters.
Parameters
calInInches [in] true if the calibration has been performed in inches.
References m_calInInches.
Referenced by MeaScreenMgr::LoadProfile(), and MeaScreenMgr::MasterReset().
SetName()
void MeaScreenMgr::Screen::SetName (LPCTSTR name) inline
Sets a descriptive name for the screen.
Parameters
name [in] Name for the screen.
References m_name.
Referenced by MeaScreenMgr::CreateScreens().
SetPrimary()
void MeaScreenMgr::Screen::SetPrimary (bool primary) inline
In multiple monitor environments, one of the monitors is designated as the primary.
This method designates the screen as the primary.
Parameters
primary [in] Specify true if this screen is the primary.
References m_primary.
Referenced by MeaScreenMgr::CreateScreens().
SetScreenRes()
void MeaScreenMgr::Screen::SetScreenRes (bool useManualRes, const FSIZE * manualRes = NULL)
Sets the resolution of the screen, in pixels per inch.
Parameters
useManualRes [in] Specifies whether the manually calibrated resolution should be used (true) or the operating system resolution (false).
manualRes [in] If non-NULL, specifies the manually calibrated resolution.
Referenced by MeaScreenMgr::LoadProfile(), and MeaScreenMgr::MasterReset().
The documentation for this class was generated from the following files:
ScreenMgr.h
ScreenMgr.cpp
Copyright 2011 C Thing Software