Meazure: MeaToolsPrefs Class Reference
MeaToolsPrefs Class Reference
Property page for specifying the following tool preferences:
#include <ToolsPrefs.h>
Public Types
enum { IDD = IDD_PREF_TOOLS }
Public Member Functions
MeaToolsPrefs ()
Creates an instance of the tool property page.
~MeaToolsPrefs ()
Destroys an instance of the tool property page.
virtual BOOL OnInitDialog ()
Called when the property page is created.
Public Attributes
BOOL m_showDataWin
Preference variable indicating whether the data window popup should be displayed.
int m_opacity
Preference variable specifying the crosshair opacity where 0 is transparent and 255 is opaque.
BOOL m_originMarker
Preference variable indicating whether the origin marker should be displayed.
COLORREF m_lineColor
Line color.
COLORREF m_backColor
Crosshair background color.
COLORREF m_borderColor
Crosshair border color.
COLORREF m_hiliteColor
Crosshair hilite color.
Protected Member Functions
virtual void DoDataExchange (CDataExchange *pDX)
Performs Dynamic Data Exchange (DDX) for the page.
afx_msg void OnChangeLineColor ()
Called when the line color button is pressed.
afx_msg void OnDefLineColor ()
Called when the default line color button is pressed.
afx_msg void OnChangeBorderColor ()
Called when the crosshair border color button is pressed.
afx_msg void OnDefBorderColor ()
Called when the default border color button is pressed.
afx_msg void OnChangeBackColor ()
Called when the crosshair background color button is pressed.
afx_msg void OnDefBackColor ()
Called when the default background color button is pressed.
afx_msg void OnChangeHiliteColor ()
Called when the hilite color button is pressed.
afx_msg void OnDefHiliteColor ()
Called when the default hilite color button is pressed.
afx_msg void OnHScroll (UINT nSBCode, UINT nPos, CScrollBar *pScrollBar)
Called when the crosshair opacity slider is moved.
afx_msg void OnChange ()
Called whenever a value is changed on the property page.
Private Attributes
MeaSwatch m_line
Swatch to display the line color.
MeaCrossHair m_normalCH
Sample crosshair to preview the normal background color.
MeaCrossHair m_hiliteCH
Sample crosshair to preview the hilite color.
MeaDataWin m_dataWin
Sample data popup window.
Detailed Description
Property page for specifying the following tool preferences:
Line color
Crosshair normal background
Crosshair hilite color
Crosshair border color
Crosshair opacity
Display of popup data window
Display of the origin marker
Member Function Documentation
MeaToolsPrefs::DoDataExchange (CDataExchange * pDX) [protected, virtual]
Performs Dynamic Data Exchange (DDX) for the page.
Parameters:
pDX [in] DDX object for exchanging data between the page UI and the member variables.
References m_opacity, m_originMarker, and m_showDataWin.
MeaToolsPrefs::OnChange () [protected]
Called whenever a value is changed on the property page.
Sets the modified flag.
MeaToolsPrefs::OnChangeBackColor () [protected]
Called when the crosshair background color button is pressed.
Displays a color picker dialog for selecting a new background color and displays the selected color in the normal crosshair sample.
References MeaColorDialog::DoModal(), m_backColor, m_borderColor, m_normalCH, and MeaCrossHair::SetColors().
MeaToolsPrefs::OnChangeBorderColor () [protected]
Called when the crosshair border color button is pressed.
Displays a color picker dialog for selecting a new border color and displays the selected color on the sample crosshairs.
References MeaColorDialog::DoModal(), m_backColor, m_borderColor, m_hiliteCH, m_hiliteColor, m_normalCH, and MeaCrossHair::SetColors().
MeaToolsPrefs::OnChangeHiliteColor () [protected]
Called when the hilite color button is pressed.
Displays a color picker for selecting a new hilite color and displays the selected color in the hilite crosshair sample.
References MeaColorDialog::DoModal(), m_borderColor, m_hiliteCH, m_hiliteColor, and MeaCrossHair::SetColors().
MeaToolsPrefs::OnChangeLineColor () [protected]
Called when the line color button is pressed.
Displays a color picker dialog for selecting a new line color. The selected color is shown in the line color swatch.
References MeaColorDialog::DoModal(), m_line, m_lineColor, and MeaSwatch::SetColor().
MeaToolsPrefs::OnDefBackColor () [protected]
Called when the default background color button is pressed.
The default background color is set and displayed on the normal crosshair sample.
References MeaColors::CrossHairBack, MeaColors::GetDef(), m_backColor, m_borderColor, m_normalCH, and MeaCrossHair::SetColors().
MeaToolsPrefs::OnDefBorderColor () [protected]
Called when the default border color button is pressed.
The default border color is set and displayed on the sample crosshairs.
References MeaColors::CrossHairBorder, MeaColors::GetDef(), m_backColor, m_borderColor, m_hiliteCH, m_hiliteColor, m_normalCH, and MeaCrossHair::SetColors().
MeaToolsPrefs::OnDefHiliteColor () [protected]
Called when the default hilite color button is pressed.
The default hilite color is set and displayed on the hilite crosshair sample.
References MeaColors::CrossHairHilite, MeaColors::GetDef(), m_borderColor, m_hiliteCH, m_hiliteColor, and MeaCrossHair::SetColors().
MeaToolsPrefs::OnDefLineColor () [protected]
Called when the default line color button is pressed.
Resets the line color to its default value.
References MeaColors::GetDef(), MeaColors::LineFore, m_line, m_lineColor, and MeaSwatch::SetColor().
MeaToolsPrefs::OnHScroll (UINT nSBCode, UINT nPos, CScrollBar * pScrollBar) [protected]
Called when the crosshair opacity slider is moved.
Sets the new opacity on the crosshair samples.
References m_dataWin, m_hiliteCH, m_normalCH, m_opacity, MeaDataWin::SetOpacity(), and MeaCrossHair::SetOpacity().
BOOL MeaToolsPrefs::OnInitDialog () [virtual]
Called when the property page is created.
This method Creates the sample crosshairs, line color swatch, data window, and initializes the opacity slider.
Returns:
TRUE, indicating that the input focus should be set to the first control on the page.
References MeaSwatch::Create(), MeaDataWin::Create(), MeaCrossHair::Create(), MeaLayout::GetWindowHeight(), HaveLayeredWindows(), MeaDataWin::kNoLabelId, m_backColor, m_borderColor, m_dataWin, m_hiliteCH, m_hiliteColor, m_line, m_lineColor, m_normalCH, m_opacity, MeaDataWin::SetOpacity(), MeaCrossHair::SetOpacity(), MeaCrossHair::SetPosition(), MeaSwatch::Show(), MeaGraphic::Show(), and MeaDataWin::Show().
Member Data Documentation
MeaToolsPrefs::m_opacity
Preference variable specifying the crosshair opacity where 0 is transparent and 255 is opaque.
Referenced by CChildView::ApplyPreferences(), DoDataExchange(), OnHScroll(), OnInitDialog(), and CChildView::OnPreferences().
MeaToolsPrefs::m_originMarker
Preference variable indicating whether the origin marker should be displayed.
Referenced by CChildView::ApplyPreferences(), DoDataExchange(), and CChildView::OnPreferences().
MeaToolsPrefs::m_showDataWin
Preference variable indicating whether the data window popup should be displayed.
Referenced by CChildView::ApplyPreferences(), DoDataExchange(), and CChildView::OnPreferences().
The documentation for this class was generated from the following files:
ToolsPrefs.h
ToolsPrefs.cpp
Copyright 2011 C Thing Software