Meazure: AppFrame Class Reference
AppFrame Class Reference
The frame class for the application.
#include <AppFrame.h>
Public Member Functions
AppFrame ()
Constructs the application's frame window.
virtual ~AppFrame ()
Destroys the application's frame window.
AppView * GetView ()
Returns the view window associated with the frame.
HACCEL GetAccelTable ()
Returns the keyboard accelerator table for the application.
void UpdateVisibility ()
Sets the window to either the topmost (i.e.
void SetCommandLineFile (const CString &fileName)
Sets the filename specified on the command line, if any.
void SaveProfile (MeaProfile &profile)
Persists the frame's state to the specified profile object and initiates the persisting of the application view.
void LoadProfile (MeaProfile &profile)
Restores the frame's state from the specified profile object and initiates the restoring of the application view.
void InitView ()
Called at startup right before the application windows are shown.
bool IsNewInstall () const
Indicates whether this is the first time the application has been run.
virtual BOOL OnCmdMsg (UINT nID, int nCode, void *pExtra, AFX_CMDHANDLERINFO *pHandlerInfo) override
Forwards command messages to the view.
Static Public Attributes
static constexpr bool kDefAlwaysVisible { true }
Indicates whether the application's window is always the topmost window by default.
Protected Member Functions
virtual BOOL PreCreateWindow (CREATESTRUCT &cs) override
Called before the window is created to set the appearance of the application including setting the program's icon.
afx_msg int OnCreate (LPCREATESTRUCT lpCreateStruct)
Creates the main frame window, the toolbar and the view.
afx_msg void OnSetFocus (CWnd *pOldWnd)
Called when the frame gets the focus and forwards it on to the view.
afx_msg void OnAlwaysVisible ()
Called when the Always Visible item is selected on the View menu.
afx_msg void OnUpdateAlwaysVisible (CCmdUI *pCmdUI)
Called right before the View menu is displayed to update the Always Visible menu item.
afx_msg void OnEndSession (BOOL bEnding)
Called when the windows session is ending.
afx_msg void OnClose ()
Called when the application window is closing.
afx_msg void OnViewToolbar ()
Changes the window geometry according to whether the toolbar is displayed.
afx_msg void OnUpdateViewToolbar (CCmdUI *pCmdUI)
Updates the view toolbar menu item.
afx_msg void OnViewStatusbar ()
Called when the status bar view menu item is selected.
afx_msg void OnUpdateViewStatusbar (CCmdUI *pCmdUI)
Updates the view status bar menu item.
afx_msg void OnUpdateHelpMenu (CCmdUI *pCmdUI)
Called before the Help menu is displayed.
afx_msg void OnMeazureReleases ()
Called to open the Meazure GitHub releases web page.
afx_msg void OnReportIssue ()
Called to open the Meazure GitHub issue web page.
afx_msg LRESULT OnPrefsApply (WPARAM wParam, LPARAM lParam)
Called when the Apply button is pressed on the preferences dialog.
afx_msg LRESULT OnShowCalPrefs (WPARAM wParam, LPARAM lParam)
Called to display the preferences dialog from the resolution calibration warning dialogs.
afx_msg LRESULT OnCopyData (WPARAM wParam, LPARAM lParam)
Called when a second copy of the application is launched with a file specified on the command line.
afx_msg LRESULT OnMasterReset (WPARAM wParam, LPARAM lParam)
Called when a master reset has been requested from the advanced page on the preferences dialog.
Protected Attributes
CToolBar m_wndToolBar
Application toolbar.
MeaStatusBar m_wndStatusBar
Application status bar.
AppView m_wndView
Application view window.
bool m_alwaysVisible
Indicates if the application window is always top window on the desktop.
bool m_profileToolbarVisible
Indicates if the persisted preference is for the toolbar to be displayed.
bool m_profileStatusbarVisible
Indicates if the persisted preference if for the status bar to be displayed.
bool m_toolbarVisible
Indicates if the toolbar is currently visible.
bool m_statusbarVisible
Indicates if the status bar is currently visible.
Static Protected Attributes
static UINT m_indicators [] { ID_SEPARATOR }
Status bar indicators. Only one field is used.
Private Member Functions
bool CreateToolbar ()
Creates the application toolbar.
void ViewToolbar (bool enable)
Selects whether to show the toolbar.
void ViewStatusbar (bool enable)
Selects whether to show the status bar.
bool OpenUrl (int urlId)
Opens the specified URL in a web browser.
Private Attributes
bool m_newInstall
Indicates if this is the first time the application has been run.
int m_toolbarHeight
Height of the toolbar, in pixels.
int m_statusbarHeight
Height of the status bar, in pixels.
int m_appWidth
Total width of the application, in pixels.
CString m_cmdLineFile
Filename specified on the command line, if any.
Detailed Description
The frame class for the application.
The application frame is the root window for the application's window hierarchy.
Member Function Documentation
CreateToolbar()
bool AppFrame::CreateToolbar () private
Creates the application toolbar.
Returns
true if toolbar successfully created.
References MeaLayout::GetDPIScalePercent(), and m_wndToolBar.
Referenced by OnCreate().
GetAccelTable()
HACCEL AppFrame::GetAccelTable () inline
Returns the keyboard accelerator table for the application.
Returns
Handle for the application keyboard accelerator table.
GetView()
AppView * AppFrame::GetView () inline
Returns the view window associated with the frame.
Since this application is a single document style program, there is only one view held by the frame.
Returns
The application's view window.
References m_wndView.
Referenced by LoadProfile(), OnMasterReset(), OnPrefsApply(), OnShowCalPrefs(), and SaveProfile().
InitView()
void AppFrame::InitView ()
Called at startup right before the application windows are shown.
Shows/hides the portions of the view according to the registry profile.
References m_profileStatusbarVisible, m_profileToolbarVisible, OnViewStatusbar(), and OnViewToolbar().
Referenced by OnCreate().
IsNewInstall()
bool AppFrame::IsNewInstall () const inline
Indicates whether this is the first time the application has been run.
Returns
true if this is the first time the application has been run.
References m_newInstall.
LoadProfile()
void AppFrame::LoadProfile (MeaProfile & profile)
Restores the frame's state from the specified profile object and initiates the restoring of the application view.
Ultimately, this method causes the restoration of the entire state of the application.
Parameters
profile [in] Profile object from which the state of the application is restored.
References MeaScreenMgr::EnsureVisible(), GetView(), MeaSingleton_T< MeaScreenMgr >::Instance(), AppView::LoadProfile(), m_alwaysVisible, m_newInstall, m_profileStatusbarVisible, m_profileToolbarVisible, m_statusbarVisible, m_toolbarVisible, MeaProfile::ReadBool(), MeaProfile::ReadInt(), and MeaProfile::UserInitiated().
Referenced by OnCreate().
OnClose()
void AppFrame::OnClose () protected
Called when the application window is closing.
Saves the state of the application to the registry.
References SaveProfile().
OnCmdMsg()
BOOL AppFrame::OnCmdMsg (UINT nID, int nCode, void * pExtra, AFX_CMDHANDLERINFO * pHandlerInfo) override virtual
Forwards command messages to the view.
Parameters
nID [in] ID of control issuing the message.
nCode [in] Message code.
pExtra [in] Pointer to extra data.
pHandlerInfo [in] Handler information structure.
References m_wndView.
OnCopyData()
LRESULT AppFrame::OnCopyData (WPARAM wParam, LPARAM lParam) protected
Called when a second copy of the application is launched with a file specified on the command line.
This method receives the pathname of the file and loads it.
Parameters
wParam [in] Not used.
lParam [in] COPYDATASTRUCT
Returns
Always returns TRUE.
References AppView::LoadStartupFile(), and m_wndView.
OnCreate()
int AppFrame::OnCreate (LPCREATESTRUCT lpCreateStruct) protected
Creates the main frame window, the toolbar and the view.
Parameters
lpCreateStruct [in] Window creation parameters structure.
Returns
0 if creation successful.
References CreateToolbar(), InitView(), AppView::InitView(), LoadProfile(), AppView::LoadStartupFile(), m_appWidth, m_cmdLineFile, m_indicators, m_statusbarHeight, m_toolbarHeight, m_wndStatusBar, m_wndToolBar, m_wndView, MeaLayout::SetWindowSize(), and UpdateVisibility().
OnEndSession()
void AppFrame::OnEndSession (BOOL bEnding) protected
Called when the windows session is ending.
Saves the state of the application to the registry.
Parameters
bEnding [in] TRUE if the windows session is ending.
References SaveProfile().
OnMasterReset()
LRESULT AppFrame::OnMasterReset (WPARAM wParam, LPARAM lParam) protected
Called when a master reset has been requested from the advanced page on the preferences dialog.
Parameters
wParam [in] Not used.
lParam [in] Not used.
Returns
Always returns TRUE.
References GetView(), kDefAlwaysVisible, AppView::kDefStatusbarVisible, AppView::kDefToolbarVisible, m_alwaysVisible, AppView::MasterReset(), UpdateVisibility(), ViewStatusbar(), and ViewToolbar().
OnPrefsApply()
LRESULT AppFrame::OnPrefsApply (WPARAM wParam, LPARAM lParam) protected
Called when the Apply button is pressed on the preferences dialog.
Parameters
wParam [in] Not used.
lParam [in] Not used.
Returns
Always returns 0.
References GetView(), and MeaPrefsApplyMsg.
OnSetFocus()
void AppFrame::OnSetFocus (CWnd * pOldWnd) protected
Called when the frame gets the focus and forwards it on to the view.
Parameters
pOldWnd [in] Window that had the focus previously.
References m_wndView.
OnShowCalPrefs()
LRESULT AppFrame::OnShowCalPrefs (WPARAM wParam, LPARAM lParam) protected
Called to display the preferences dialog from the resolution calibration warning dialogs.
Parameters
wParam [in] Not used.
lParam [in] Not used.
Returns
Always returns 0.
References GetView(), and MeaShowCalPrefsMsg.
OnUpdateAlwaysVisible()
void AppFrame::OnUpdateAlwaysVisible (CCmdUI * pCmdUI) protected
Called right before the View menu is displayed to update the Always Visible menu item.
Parameters
pCmdUI [in] UI command class to update the menu item.
References m_alwaysVisible.
OnUpdateHelpMenu()
void AppFrame::OnUpdateHelpMenu (CCmdUI * pCmdUI) protected
Called before the Help menu is displayed.
Tests to see if the help file exists.
Parameters
pCmdUI [in] UI command class to update the menu item.
OnUpdateViewStatusbar()
void AppFrame::OnUpdateViewStatusbar (CCmdUI * pCmdUI) protected
Updates the view status bar menu item.
Parameters
pCmdUI [in] UI command class to update the menu item.
References m_statusbarVisible.
OnUpdateViewToolbar()
void AppFrame::OnUpdateViewToolbar (CCmdUI * pCmdUI) protected
Updates the view toolbar menu item.
Parameters
pCmdUI [in] UI command class to update the menu item.
References m_toolbarVisible.
OnViewStatusbar()
void AppFrame::OnViewStatusbar () protected
Called when the status bar view menu item is selected.
Toggles view / hide of the status bar.
References m_statusbarVisible, and ViewStatusbar().
Referenced by InitView().
OpenUrl()
bool AppFrame::OpenUrl (int urlId) private
Opens the specified URL in a web browser.
Parameters
urlId String resource ID for the URL
Returns
true if the browser was opened.
Referenced by OnMeazureReleases(), and OnReportIssue().
PreCreateWindow()
BOOL AppFrame::PreCreateWindow (CREATESTRUCT & cs) override protected virtual
Called before the window is created to set the appearance of the application including setting the program's icon.
Parameters
cs [in] Window creation structure.
SaveProfile()
void AppFrame::SaveProfile (MeaProfile & profile)
Persists the frame's state to the specified profile object and initiates the persisting of the application view.
Ultimately, this method causes the persistence of the entire state of the application.
Parameters
profile [in] Profile object into which the state of the application is persisted.
References GetView(), m_alwaysVisible, m_statusbarVisible, m_toolbarVisible, AppView::SaveProfile(), MeaProfile::UserInitiated(), MeaProfile::WriteBool(), and MeaProfile::WriteInt().
Referenced by OnClose(), and OnEndSession().
SetCommandLineFile()
void AppFrame::SetCommandLineFile (const CString & fileName) inline
Sets the filename specified on the command line, if any.
Parameters
fileName [in] Filename specified on the application command line, or the empty string if no filename was specified.
References m_cmdLineFile.
Referenced by App::InitInstance().
UpdateVisibility()
void AppFrame::UpdateVisibility ()
Sets the window to either the topmost (i.e.
always visible) position or a normal stacking order.
References m_alwaysVisible, and MeaLayout::SetWindowPos().
Referenced by OnAlwaysVisible(), OnCreate(), and OnMasterReset().
ViewStatusbar()
void AppFrame::ViewStatusbar (bool enable) private
Selects whether to show the status bar.
Parameters
enable [in] Indicates whether the status bar should be visible.
References m_appWidth, m_statusbarHeight, m_statusbarVisible, m_wndStatusBar, and MeaLayout::SetWindowSize().
Referenced by OnMasterReset(), and OnViewStatusbar().
ViewToolbar()
void AppFrame::ViewToolbar (bool enable) private
Selects whether to show the toolbar.
Parameters
enable [in] Indicates whether the toolbar should be visible.
References m_appWidth, m_toolbarHeight, m_toolbarVisible, m_wndToolBar, and MeaLayout::SetWindowSize().
Referenced by OnMasterReset(), and OnViewToolbar().
The documentation for this class was generated from the following files:
AppFrame.h
AppFrame.cpp
Copyright 2011 C Thing Software