Meazure: MeaLinearUnitsLabel Class Reference
MeaLinearUnitsLabel Class Reference
There are two categories of labels: those for angular measurements and those for linear measurements.
#include <Units.h>
Public Member Functions
virtual void SetUnits (MeaLinearUnitsId unitsId)
Displays the actual text of the label.
Public Member Functions inherited from MeaUnitsLabel
virtual ~MeaUnitsLabel ()
Destroys the base class instance for the label.
bool Create (UINT unitsId, DWORD style, const POINT &topLeft, CWnd *parentWnd, UINT id=0xffff)
Creates the underlying label control.
Public Member Functions inherited from MeaLabel
MeaLabel ()
Constructs a label object.
virtual ~MeaLabel ()
Destroys an instance of a label object.
bool Create (LPCTSTR label, DWORD style, const POINT &topLeft, CWnd *parentWnd, UINT id=0xffff)
Creates the window for the label.
bool Create (UINT labelID, DWORD style, const POINT &topLeft, CWnd *parentWnd, UINT id=0xffff)
Creates the window for the label.
Static Public Member Functions
static void ChangeLabel (MeaLinearUnitsId unitsId, const CString &label)
Sets the specified label string for the specified units.
Protected Member Functions
MeaLinearUnitsLabel (UINT format, int &width)
Constructs a linear units label.
virtual ~MeaLinearUnitsLabel ()
Destroys a linear units label.
Protected Member Functions inherited from MeaUnitsLabel
MeaUnitsLabel (UINT format, LabelMap &labels, int &width)
Base class constructor for the label instance.
UINT GetFormat () const
Returns the measurement type format string.
bool SetSize ()
Sets the overall width of the label object to the width of the widest label string over all the units.
CString ConstructLabel (int unitsId) const
Formats the label string corresponding to the specified units identifier.
Static Private Attributes
static LabelMap m_labels
Maps linear units identifiers to their corresponding label strings.
Additional Inherited Members
Public Types inherited from MeaUnitsLabel
typedef std::map< int, CString > LabelMap
Maps a units identifier to the corresponding label string.
Detailed Description
There are two categories of labels: those for angular measurements and those for linear measurements.
This class is the base class for linear measurement labels.
Constructor & Destructor Documentation
MeaLinearUnitsLabel()
MeaLinearUnitsLabel::MeaLinearUnitsLabel (UINT format, int & width) protected
Constructs a linear units label.
Parameters
format [in] Format string identifier. The format string provides label modifiers for the measurement type (e.g. "sq." for "sq. in").
width [out] Width of the label, in pixels.
References m_labels, MeaCentimetersId, MeaCustomId, MeaInchesId, MeaMillimetersId, MeaPicasId, MeaPixelsId, MeaPointsId, and MeaTwipsId.
Member Function Documentation
ChangeLabel()
static void MeaLinearUnitsLabel::ChangeLabel (MeaLinearUnitsId unitsId, const CString & label) inline static
Sets the specified label string for the specified units.
Parameters
unitsId [in] Identifier for the units whose label string is to be changed.
label [in] New label string for the units.
References m_labels.
Referenced by MeaCustomUnits::SetAbbrev().
SetUnits()
void MeaLinearUnitsLabel::SetUnits (MeaLinearUnitsId unitsId) virtual
Displays the actual text of the label.
Parameters
unitsId [in] Linear units identifier.
References MeaUnitsLabel::ConstructLabel(), MeaUnitsLabel::GetFormat(), MeaInchesId, and MeaPixelsId.
The documentation for this class was generated from the following files:
Units.h
Units.cpp
Copyright 2011 C Thing Software