Meazure: MeaPositionLogMgr::Screen Class Reference
MeaPositionLogMgr::Screen Class Reference
Represents a single monitor attached to the system.
#include <PositionLogMgr.h>
Public Member Functions
Screen ()
Constructs a screen object.
Screen (const MeaScreenMgr::ScreenIter &screenIter)
Constructs deep copy screen object from the specified iterator over the list of screens.
Screen (const Screen &screen)
Constructs a deep copy of the specified screen.
~Screen ()
Destroys a screen object.
void Load (const MeaXMLNode *screenNode)
Loads screen elements of the log file.
void Save (MeaPositionLogMgr &mgr, int indent) const throw (CFileException)
Saves the screen information.
Screen & operator= (const Screen &screen)
Assignment operator for a screen object.
bool operator== (const Screen &screen) const
Tests for equality between the specified screen object and this.
bool operator!= (const Screen &screen) const
Tests for inequality between the specified screen object and this.
Private Member Functions
Screen & Copy (const Screen &screen)
Makes a deep copy of the specified screen object.
bool IsEqual (const Screen &screen) const
Tests whether the specified screen object is equal to this.
Private Attributes
bool m_primary
Is this the primary screen.
FRECT m_rect
Screen rectangle expressed in the units that were in effect at the time the screen object was created.
FSIZE m_res
Screen resolution expressed in the units that were in effect at the time the screen object was created.
bool m_manualRes
Is the resolution calibrated manually.
CString m_desc
Description for the screen.
Detailed Description
Represents a single monitor attached to the system.
There is an instance of this class per monitor.
Constructor & Destructor Documentation
MeaPositionLogMgr::Screen::Screen (const MeaScreenMgr::ScreenIter & screenIter) [explicit]
Constructs deep copy screen object from the specified iterator over the list of screens.
Parameters:
screenIter [in] Iterator from which to construct a copy of the screen.
References FRECT::bottom, MeaUnitsMgr::ConvertCoord(), MeaUnitsMgr::ConvertRes(), MeaScreenMgr::GetScreenName(), MeaScreenMgr::GetScreenRect(), MeaScreenMgr::GetScreenRes(), MeaSingleton_T< MeaPositionLogMgr >::Instance(), MeaScreenMgr::IsManualRes(), MeaScreenMgr::IsPrimary(), FRECT::left, m_desc, m_manualRes, m_primary, m_rect, m_res, FRECT::right, FRECT::top, FPOINT::x, and FPOINT::y.
MeaPositionLogMgr::Screen::Screen (const Screen & screen) [inline]
Constructs a deep copy of the specified screen.
Parameters:
screen [in] Screen object to be copied.
References Copy().
Member Function Documentation
Screen& MeaPositionLogMgr::Screen::Copy (const Screen & screen) [inline, private]
Makes a deep copy of the specified screen object.
Parameters:
screen [in] Screen object to copy.
Returns:
Copy of the specified screen object.
References m_desc, m_manualRes, m_primary, m_rect, and m_res.
Referenced by operator=(), and Screen().
bool MeaPositionLogMgr::Screen::IsEqual (const Screen & screen) const [inline, private]
Tests whether the specified screen object is equal to this.
Parameters:
screen [in] Screen object to test against this.
Returns:
true if the specified screen object is equal to this.
References FRECT::bottom, FSIZE::cx, FSIZE::cy, FRECT::left, m_desc, m_manualRes, m_primary, m_rect, m_res, MEA_DBL_EQL, FRECT::right, and FRECT::top.
Referenced by operator!=(), and operator==().
void MeaPositionLogMgr::Screen::Load (const MeaXMLNode * screenNode)
Loads screen elements of the log file.
Parameters:
screenNode [in] screen node in the DOM.
References MeaXMLNode::AtEnd(), MeaXMLNode::Element, MeaXMLNode::GetAttributes(), MeaXMLNode::GetChildIter(), MeaXMLNode::GetData(), MeaXMLNode::GetType(), MeaXMLAttributes::GetValueBool(), MeaXMLAttributes::GetValueDbl(), MeaXMLAttributes::GetValueStr(), and MeaPositionLogMgr::m_desc.
Referenced by MeaPositionLogMgr::DesktopInfo::Load().
bool MeaPositionLogMgr::Screen::operator!= (const Screen & screen) const [inline]
Tests for inequality between the specified screen object and this.
Parameters:
screen [in] Screen object to test against this.
Returns:
true if the specified screen object and this are not equal.
References IsEqual().
Screen& MeaPositionLogMgr::Screen::operator= (const Screen & screen) [inline]
Assignment operator for a screen object.
Makes a deep copy of the object.
Parameters:
screen [in] Screen option to assign to this.
Returns:
This screen object.
References Copy().
bool MeaPositionLogMgr::Screen::operator== (const Screen & screen) const [inline]
Tests for equality between the specified screen object and this.
Parameters:
screen [in] Screen object to test against this.
Returns:
true if the specified screen object and this are equal.
References IsEqual().
void MeaPositionLogMgr::Screen::Save (MeaPositionLogMgr & mgr, int indent) const throw (CFileException)
Saves the screen information.
Parameters:
mgr [in] Parent manager.
indent [in] Output indentation level.
References MeaUtils::DblToStr(), and MeaPositionLogMgr::m_desc.
Member Data Documentation
FRECT MeaPositionLogMgr::Screen::m_rect [private]
Screen rectangle expressed in the units that were in effect at the time the screen object was created.
Referenced by Copy(), IsEqual(), and Screen().
FSIZE MeaPositionLogMgr::Screen::m_res [private]
Screen resolution expressed in the units that were in effect at the time the screen object was created.
Referenced by Copy(), IsEqual(), and Screen().
The documentation for this class was generated from the following files:
PositionLogMgr.h
PositionLogMgr.cpp
Copyright 2011 C Thing Software