Meazure: CMainFrame Class Reference
CMainFrame Class Reference
The frame class for the application.
#include <MainFrm.h>
Public Member Functions
CMainFrame ()
Constructs the application's frame window.
virtual ~CMainFrame ()
Destroys the application's frame window.
CChildView * GetView ()
Returns the view window associated with the frame.
HACCEL GetAccelTable ()
Returns the keyboard accelerator table for the application.
void UpdateVisibility ()
Sets the window to either the topmost (i.e.
void SetCommandLineFile (const CString &fileName)
Sets the filename specified on the command line, if any.
void SaveProfile (MeaProfile &profile)
Persists the frame's state to the specified profile object and initiates the persisting of the application view.
void LoadProfile (MeaProfile &profile)
Restores the frame's state from the specified profile object and initiates the restoring of the application view.
void InitView ()
Called at startup right before the app windows are shown.
bool IsNewInstall () const
Indicates whether this is the first time the application has been run.
virtual BOOL OnCmdMsg (UINT nID, int nCode, void *pExtra, AFX_CMDHANDLERINFO *pHandlerInfo)
Forwards command messages to the view.
Static Public Attributes
static const bool kDefAlwaysVisible = true
Indicates whether the app's window is always the topmost window by default.
Protected Member Functions
virtual BOOL PreCreateWindow (CREATESTRUCT &cs)
Called before the window is created to set the appearance of the application including setting the program's icon.
afx_msg int OnCreate (LPCREATESTRUCT lpCreateStruct)
Creates the main frame window, the toolbar and the view.
afx_msg void OnSetFocus (CWnd *pOldWnd)
Called when the frame gets the focus and forwards it on to the view.
afx_msg void OnAlwaysVisible ()
Called when the Always Visible item is selected on the View menu.
afx_msg void OnUpdateAlwaysVisible (CCmdUI *pCmdUI)
Called right before the View menu is displayed to update the Always Visible menu item.
afx_msg void OnEndSession (BOOL bEnding)
Called when the windows session is ending.
afx_msg void OnClose ()
Called when the application window is closing.
afx_msg void OnViewToolbar ()
Changes the window geometry according to whether the toolbar is displayed.
afx_msg void OnUpdateViewToolbar (CCmdUI *pCmdUI)
Updates the view toolbar menu item.
afx_msg void OnViewStatusbar ()
Called when the status bar view menu item is selected.
afx_msg void OnUpdateViewStatusbar (CCmdUI *pCmdUI)
Updates the view status bar menu item.
afx_msg void OnHelpSearch ()
Called when the Search / Index item is selected on the Help menu.
afx_msg void OnHelpIndex ()
Called when the Search / Index item is selected on the Help menu.
afx_msg void OnUpdateHelpMenu (CCmdUI *pCmdUI)
Called before the Help menu is displayed.
afx_msg LRESULT OnPrefsApply (WPARAM wParam, LPARAM lParam)
Called when the Apply button is pressed on the preferences dialog.
afx_msg LRESULT OnShowCalPrefs (WPARAM wParam, LPARAM lParam)
Called to display the preferences dialog from the resolution calibration warning dialogs.
afx_msg LRESULT OnCopyData (WPARAM wParam, LPARAM lParam)
Called when a second copy of the app is launched with a file specified on the command line.
afx_msg LRESULT OnMasterReset (WPARAM wParam, LPARAM lParam)
Called when a master reset has been requested from the advanced page on the preferences dialog.
Protected Attributes
CToolBar m_wndToolBar
Application toolbar.
MeaStatusBar m_wndStatusBar
Application status bar.
CChildView m_wndView
Application view window.
bool m_alwaysVisible
Indicates if the application window is always top window on the desktop.
bool m_profileToolbarVisible
Indicates if the persisted preference is for the toolbar to be displayed.
bool m_profileStatusbarVisible
Indicates if the persisted preference if for the status bar to be displayed.
bool m_toolbarVisible
Indicates if the toolbar is currently visible.
bool m_statusbarVisible
Indicates if the status bar is currently visible.
Static Protected Attributes
static UINT m_indicators []
Status bar indicators. Only one field is used.
Private Member Functions
void ViewToolbar (bool enable)
Selects whether to show the toolbar.
void ViewStatusbar (bool enable)
Selects whether to show the status bar.
Private Attributes
bool m_newInstall
Indicates if this is the first time the app has been run.
int m_toolbarHeight
Height of the toolbar, in pixels.
int m_statusbarHeight
Height of the status bar, in pixels.
int m_appWidth
Total width of the application, in pixels.
CString m_cmdLineFile
Filename specified on the command line, if any.
Detailed Description
The frame class for the application.
The application frame is the root window for the application's window hierarchy.
Member Function Documentation
HACCEL CMainFrame::GetAccelTable () [inline]
Returns the keyboard accelerator table for the application.
Returns:
Handle for the application keyboard accelerator table.
CChildView* CMainFrame::GetView () [inline]
Returns the view window associated with the frame.
Since this application is a single document style program, there is only one view held by the frame.
Returns:
The application's view window.
References m_wndView.
Referenced by LoadProfile(), OnMasterReset(), OnPrefsApply(), OnShowCalPrefs(), and SaveProfile().
void CMainFrame::InitView ()
Called at startup right before the app windows are shown.
Shows/hides the portions of the view according to the registry profile.
References m_profileStatusbarVisible, m_profileToolbarVisible, OnViewStatusbar(), and OnViewToolbar().
Referenced by OnCreate().
bool CMainFrame::IsNewInstall () const [inline]
Indicates whether this is the first time the application has been run.
Returns:
true if this is the first time the application has been run.
References m_newInstall.
Referenced by CMeazureApp::InitInstance().
void CMainFrame::LoadProfile (MeaProfile & profile)
Restores the frame's state from the specified profile object and initiates the restoring of the application view.
Ultimately, this method causes the restoration of the entire state of the application.
Parameters:
profile [in] Profile object from which the state of the application is restored.
References MeaScreenMgr::EnsureVisible(), GetView(), MeaSingleton_T< MeaScreenMgr >::Instance(), CChildView::LoadProfile(), m_alwaysVisible, m_newInstall, m_profileStatusbarVisible, m_profileToolbarVisible, m_statusbarVisible, m_toolbarVisible, MeaProfile::ReadBool(), MeaProfile::ReadInt(), and MeaProfile::UserInitiated().
Referenced by OnCreate().
CMainFrame::OnAlwaysVisible () [protected]
Called when the Always Visible item is selected on the View menu.
References m_alwaysVisible, and UpdateVisibility().
CMainFrame::OnClose () [protected]
Called when the application window is closing.
Saves the state of the application to the registry.
References SaveProfile().
CMainFrame::OnCmdMsg (UINT nID, int nCode, void * pExtra, AFX_CMDHANDLERINFO * pHandlerInfo) [virtual]
Forwards command messages to the view.
Parameters:
nID [in] ID of control issuing the message.
nCode [in] Message code.
pExtra [in] Pointer to extra data.
pHandlerInfo [in] Handler information structure.
References m_wndView.
LRESULT CMainFrame::OnCopyData (WPARAM wParam, LPARAM lParam) [protected]
Called when a second copy of the app is launched with a file specified on the command line.
This method receives the pathname of the file and loads it.
Parameters:
wParam [in] Not used.
lParam [in] COPYDATASTRUCT
Returns:
Always returns TRUE.
References CChildView::LoadStartupFile(), and m_wndView.
CMainFrame::OnCreate (LPCREATESTRUCT lpCreateStruct) [protected]
Creates the main frame window, the toolbar and the view.
Parameters:
lpCreateStruct [in] Window creation parameters structure.
Returns:
0 if creation successful.
References CChildView::InitView(), InitView(), LoadProfile(), CChildView::LoadStartupFile(), m_appWidth, m_cmdLineFile, m_indicators, m_statusbarHeight, m_toolbarHeight, m_wndStatusBar, m_wndToolBar, m_wndView, MeaLayout::SetWindowSize(), and UpdateVisibility().
CMainFrame::OnEndSession (BOOL bEnding) [protected]
Called when the windows session is ending.
Saves the state of the application to the registry.
Parameters:
bEnding [in] TRUE if the windows session is ending.
References SaveProfile().
void CMainFrame::OnHelpIndex () [protected]
Called when the Search / Index item is selected on the Help menu.
void CMainFrame::OnHelpSearch () [protected]
Called when the Search / Index item is selected on the Help menu.
LRESULT CMainFrame::OnMasterReset (WPARAM wParam, LPARAM lParam) [protected]
Called when a master reset has been requested from the advanced page on the preferences dialog.
Parameters:
wParam [in] Not used.
lParam [in] Not used.
Returns:
Always returns TRUE.
References GetView(), kDefAlwaysVisible, CChildView::kDefStatusbarVisible, CChildView::kDefToolbarVisible, m_alwaysVisible, CChildView::MasterReset(), UpdateVisibility(), ViewStatusbar(), and ViewToolbar().
LRESULT CMainFrame::OnPrefsApply (WPARAM wParam, LPARAM lParam) [protected]
Called when the Apply button is pressed on the preferences dialog.
Parameters:
wParam [in] Not used.
lParam [in] Not used.
Returns:
Always returns 0.
References GetView(), and MeaPrefsApplyMsg.
CMainFrame::OnSetFocus (CWnd * pOldWnd) [protected]
Called when the frame gets the focus and forwards it on to the view.
Parameters:
pOldWnd [in] Window that had the focus previously.
References m_wndView.
LRESULT CMainFrame::OnShowCalPrefs (WPARAM wParam, LPARAM lParam) [protected]
Called to display the preferences dialog from the resolution calibration warning dialogs.
Parameters:
wParam [in] Not used.
lParam [in] Not used.
Returns:
Always returns 0.
References GetView(), and MeaShowCalPrefsMsg.
CMainFrame::OnUpdateAlwaysVisible (CCmdUI * pCmdUI) [protected]
Called right before the View menu is displayed to update the Always Visible menu item.
Parameters:
pCmdUI [in] UI command class to update the menu item.
References m_alwaysVisible.
void CMainFrame::OnUpdateHelpMenu (CCmdUI * pCmdUI) [protected]
Called before the Help menu is displayed.
Tests to see if the help file exists.
Parameters:
pCmdUI [in] UI command class to update the menu item.
CMainFrame::OnUpdateViewStatusbar (CCmdUI * pCmdUI) [protected]
Updates the view status bar menu item.
Parameters:
pCmdUI [in] UI command class to update the menu item.
References m_statusbarVisible.
CMainFrame::OnUpdateViewToolbar (CCmdUI * pCmdUI) [protected]
Updates the view toolbar menu item.
Parameters:
pCmdUI [in] UI command class to update the menu item.
References m_toolbarVisible.
CMainFrame::OnViewStatusbar () [protected]
Called when the status bar view menu item is selected.
Toggles view / hide of the status bar.
References m_statusbarVisible, and ViewStatusbar().
Referenced by InitView().
CMainFrame::OnViewToolbar () [protected]
Changes the window geometry according to whether the toolbar is displayed.
References m_toolbarVisible, and ViewToolbar().
Referenced by InitView().
CMainFrame::PreCreateWindow (CREATESTRUCT & cs) [protected, virtual]
Called before the window is created to set the appearance of the application including setting the program's icon.
Parameters:
cs [in] Window creation structure.
void CMainFrame::SaveProfile (MeaProfile & profile)
Persists the frame's state to the specified profile object and initiates the persisting of the application view.
Ultimately, this method causes the persistence of the entire state of the application.
Parameters:
profile [in] Profile object into which the state of the application is persisted.
References GetView(), m_alwaysVisible, m_statusbarVisible, m_toolbarVisible, CChildView::SaveProfile(), MeaProfile::UserInitiated(), MeaProfile::WriteBool(), and MeaProfile::WriteInt().
Referenced by OnClose(), and OnEndSession().
void CMainFrame::SetCommandLineFile (const CString & fileName) [inline]
Sets the filename specified on the command line, if any.
Parameters:
fileName [in] Filename specified on the application command line, or the empty string if no filename was specified.
References m_cmdLineFile.
Referenced by CMeazureApp::InitInstance().
void CMainFrame::UpdateVisibility ()
Sets the window to either the topmost (i.e.
always visible) position or a normal stacking order.
References m_alwaysVisible.
Referenced by OnAlwaysVisible(), OnCreate(), and OnMasterReset().
void CMainFrame::ViewStatusbar (bool enable) [private]
Selects whether to show the status bar.
Parameters:
enable [in] Indicates whether the status bar should be visible.
References m_appWidth, m_statusbarHeight, m_statusbarVisible, m_wndStatusBar, and MeaLayout::SetWindowSize().
Referenced by OnMasterReset(), and OnViewStatusbar().
void CMainFrame::ViewToolbar (bool enable) [private]
Selects whether to show the toolbar.
Parameters:
enable [in] Indicates whether the toolbar should be visible.
References m_appWidth, m_toolbarHeight, m_toolbarVisible, m_wndToolBar, and MeaLayout::SetWindowSize().
Referenced by OnMasterReset(), and OnViewToolbar().
Member Data Documentation
const bool CMainFrame::kDefAlwaysVisible = true [static]
Indicates whether the app's window is always the topmost window by default.
Referenced by OnMasterReset().
UINT CMainFrame::m_indicators [static, protected]
Initial value:
 {
    ID_SEPARATOR
}
Status bar indicators. Only one field is used.
Referenced by OnCreate().
The documentation for this class was generated from the following files:
MainFrm.h
MainFrm.cpp
Copyright 2011 C Thing Software