Meazure: MeaPointTool Class Reference
MeaPointTool Class Reference
Point measurement tool.
#include <PointTool.h>
Public Member Functions
MeaPointTool (MeaToolMgr &mgr, const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Constructs a new instance of a Point measurement tool.
virtual ~MeaPointTool ()
Hides and then destroys the Point tool.
virtual void Enable () override
Displays the Point tool.
virtual void Disable () override
Hides the Point tool.
virtual void Update (MeaUpdateReason reason) override
Requests that the tool update the display of its position data.
virtual void SaveProfile (MeaProfile &profile) override
Persists the state of the tool to the specified profile object.
virtual void LoadProfile (MeaProfile &profile) override
Restores the state of the tool from the specified profile object.
virtual void EnableCrosshairs () override
Displays the tool's crosshair.
virtual void DisableCrosshairs () override
Hides the tool's crosshair.
virtual void Flash () override
Visually flashes the tool.
virtual void Strobe () override
Visually strobes the tool.
virtual void SetPosition (MeaDataFieldId which, int pixels) override
Sets the position of the tool.
virtual void SetPosition (const PointMap &points) override
Sets the position of the tool.
virtual const POINT & GetPosition () const override
Returns the position of the crosshair.
virtual void RecordPosition (MeaPosition &position) const override
Records the position of the tool crosshair.
virtual void IncPosition (MeaDataFieldId which) override
Increments the specified position field.
virtual void DecPosition (MeaDataFieldId which) override
Decrements the specified position field.
virtual PCTSTR GetToolName () const override
Returns the name of the tool.
virtual UINT GetLabelId () const override
Returns a resource ID for the string used to label this tool on the data display.
virtual void ColorsChanged () override
Called to notify the tool that the colors in the MeaColors class have been changed.
virtual void OnCHEnter (const CrossHairInfo *info) override
Called when the pointer the tool's crosshair.
virtual void OnCHLeave (const CrossHairInfo *info) override
Called when the pointer leaves the tool's crosshair.
virtual void OnCHMove (const CrossHairInfo *info) override
Called when the user attempts to drag the tool's crosshair.
Public Member Functions inherited from MeaRadioTool
MeaRadioTool (MeaToolMgr &mgr, const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Constructs a new instance of an radio based measurement tool.
virtual bool IsRadioTool () override
Indicates that the derived tool is a Radio tool and cannot be enabled until any other enabled Radio tool is disabled.
virtual UINT GetLabelId () const
Returns a resource ID for the string used to label this tool on the data display.
virtual bool HasCrosshairs () const
Indicates whether the derived tool uses crosshairs.
virtual void EnableCrosshairs ()
Displays the tool's crosshairs.
virtual void DisableCrosshairs ()
Hides the tool's crosshairs.
virtual void Flash ()
Visually flashes the tool.
virtual void Strobe ()
Visually strobes the tool.
virtual bool HasRegion ()
Indicates whether the tool can define a rectangular region that can then be read for a screen capture.
virtual RECT GetRegion ()
Returns the rectangle defined by the tool.
virtual void SetPosition (const PointMap &points)
Sets the position of the tool.
virtual void RecordPosition (MeaPosition &position) const =0
Records the position of the tool.
virtual void OnMouseHook (WPARAM wParam, LPARAM lParam)
Called by the OS when the mouse pointer is moved.
Public Member Functions inherited from MeaTool
MeaTool (MeaToolMgr &mgr, const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Base class constructor.
virtual ~MeaTool ()=default
Destroys the tool.
virtual void Enable ()
Typically used by derived classes to show the tool.
virtual void Disable ()
Typically used by derived classes to hide the tool.
virtual void Update (MeaUpdateReason reason)
Used by derived classes to update the display of their data.
virtual bool IsRadioTool ()
Indicates whether the derived tool is a radio tool and cannot be enabled until any other enabled Radio tool is disabled.
virtual void SetPosition (MeaDataFieldId which, int pixels)
Sets the position of the tool.
virtual const POINT & GetPosition () const =0
Returns the tool's current position.
virtual void IncPosition (MeaDataFieldId which)
Increments the specified position field.
virtual void DecPosition (MeaDataFieldId which)
Decrements the specified position field.
virtual PCTSTR GetToolName () const =0
Returns the name of the tool.
virtual void SaveProfile (MeaProfile &profile)
Persists the state of the tool to the specified profile object.
virtual void LoadProfile (MeaProfile &profile)
Restores the state of the tool from the specified profile object.
virtual void MasterReset ()
Resets the tool to its default state.
virtual void ColorsChanged ()
Called to notify the tool that the colors in the MeaColors class have been changed.
bool IsEnabled () const
Indicates whether the tool is enabled.
Public Member Functions inherited from MeaCrossHairCallback
virtual void OnCHSelect (const CrossHairInfo *info)
Called when the left mouse button is pressed while the pointer is positioned over the crosshair.
virtual void OnCHDeselect (const CrossHairInfo *info)
Called when the left mouse button is release while the pointer is positioned over the crosshair.
virtual void OnCHMove (const CrossHairInfo *info)
Called when the user moves the mouse pointer over the crosshair while the left mouse button is pressed (i.e.
virtual void OnCHEnter (const CrossHairInfo *info)
Called when the pointer enters the crosshair window.
virtual void OnCHLeave (const CrossHairInfo *info)
Called when the pointer leaves the crosshair window.
Static Public Attributes
static constexpr PCTSTR kToolName { _T("PointTool") }
Private Member Functions
bool Create ()
Creates the tool's crosshair and data window.
void SetPosition ()
Sets the position of the tool's crosshair based on the current value of m_center.
Private Attributes
CPoint m_center
Position of the crosshair.
CPoint m_anchorPoint
Location for vertical / horizontal lock when Shift is held while dragging.
MeaCrossHair m_crossHair
Crosshair for the tool.
MeaDataWin m_dataWin
Data window tooltip for the tool.
Additional Inherited Members
Public Types inherited from MeaRadioTool
typedef std::map< CString, POINT > PointMap
Map of points used to set the position of a tool.
Protected Attributes inherited from MeaTool
MeaToolMgr & m_mgr
Tool manager.
const MeaScreenProvider & m_screenProvider
Screen information provider.
const MeaUnitsProvider & m_unitsProvider
Units information provider.
bool m_enabled
Indicates whether the tool is enabled.
Static Protected Attributes inherited from MeaTool
static const CPoint m_defaultPos
A default position used by tools that do not have a defined position.
Detailed Description
Point measurement tool.
This tool provides a crosshair that can be placed arbitrarily on the screen to measure a location.
Constructor & Destructor Documentation
MeaPointTool()
MeaPointTool::MeaPointTool (MeaToolMgr & mgr, const MeaScreenProvider & screenProvider, const MeaUnitsProvider & unitsProvider) explicit
Constructs a new instance of a Point measurement tool.
To use a newly constructed Point tool, the Enable() method must be called. Enable() will call the Create() method the first time it is called if Create() has not previously been called.
Parameters
mgr [in] Tool manager parent of the Line tool
screenProvider [in] Screen information provider
unitsProvider [in] Units information provider
References m_anchorPoint, and m_center.
Member Function Documentation
ColorsChanged()
void MeaPointTool::ColorsChanged () override virtual
Called to notify the tool that the colors in the MeaColors class have been changed.
The crosshair is redrawn in the new color and the crosshair and data window opacities are updated.
Reimplemented from MeaTool.
References MeaColors::CrossHairBack, MeaColors::CrossHairBorder, MeaColors::CrossHairHilite, MeaColors::CrossHairOpacity, MeaColors::Get(), MeaColors::GetA(), m_crossHair, m_dataWin, MeaCrossHair::SetColors(), MeaCrossHair::SetOpacity(), and MeaDataWin::SetOpacity().
Create()
bool MeaPointTool::Create () private
Creates the tool's crosshair and data window.
The Enable() method must be called to make the tool visible.
Returns
true if the window is successfully created.
References MeaDataWin::Create(), MeaCrossHair::Create(), MeaColors::CrossHairBack, MeaColors::CrossHairBorder, MeaColors::CrossHairHilite, MeaColors::CrossHairOpacity, MeaColors::Get(), MeaColors::GetA(), m_crossHair, m_dataWin, and SetPosition().
Referenced by Enable().
DecPosition()
void MeaPointTool::DecPosition (MeaDataFieldId which) override virtual
Decrements the specified position field.
Parameters
which Field to decrement
Reimplemented from MeaTool.
References m_center, MeaX1Field, MeaY1Field, and SetPosition().
Disable()
void MeaPointTool::Disable () override virtual
Hides the Point tool.
Reimplemented from MeaTool.
References MeaTool::Disable(), DisableCrosshairs(), and MeaTool::IsEnabled().
Referenced by ~MeaPointTool().
DisableCrosshairs()
void MeaPointTool::DisableCrosshairs () override virtual
Hides the tool's crosshair.
Reimplemented from MeaRadioTool.
References MeaGraphic::Hide(), and m_crossHair.
Referenced by Disable().
Enable()
void MeaPointTool::Enable () override virtual
Displays the Point tool.
If the Create() method has not been previously called, it will be called by Enable.
Reimplemented from MeaTool.
References Create(), MeaTool::Enable(), EnableCrosshairs(), MeaToolMgr::EnableRegionFields(), Flash(), MeaTool::IsEnabled(), m_crossHair, MeaTool::m_mgr, MeaX1Field, MeaY1Field, NormalUpdate, MeaToolMgr::SetStatus(), and Update().
EnableCrosshairs()
void MeaPointTool::EnableCrosshairs () override virtual
Displays the tool's crosshair.
If the Enable() method has not been previously called, this method has no effect.
Reimplemented from MeaRadioTool.
References MeaToolMgr::CrosshairsEnabled(), m_crossHair, MeaTool::m_mgr, and MeaGraphic::Show().
Referenced by Enable().
Flash()
void MeaPointTool::Flash () override virtual
Visually flashes the tool.
The tool crosshair is cycled between a highlight color and its normal color a number of times. Flashing the tool helps the user find it on the screen.
Reimplemented from MeaRadioTool.
References MeaCrossHair::Flash(), and m_crossHair.
Referenced by Enable().
GetLabelId()
UINT MeaPointTool::GetLabelId () const override virtual
Returns a resource ID for the string used to label this tool on the data display.
Returns
Resource ID for the label.
Reimplemented from MeaRadioTool.
GetPosition()
const POINT & MeaPointTool::GetPosition () const override virtual
Returns the position of the crosshair.
Returns
Current position of the tool's crosshair.
Implements MeaTool.
References m_center.
GetToolName()
PCTSTR MeaPointTool::GetToolName () const override virtual
Returns the name of the tool.
Each tool has a unique name which is used to identify the tool in profiles and position logs.
Returns
Always "PointTool". The memory for the string is owned by the tool.
Implements MeaTool.
IncPosition()
void MeaPointTool::IncPosition (MeaDataFieldId which) override virtual
Increments the specified position field.
Parameters
which Field to increment
Reimplemented from MeaTool.
References m_center, MeaX1Field, MeaY1Field, and SetPosition().
LoadProfile()
void MeaPointTool::LoadProfile (MeaProfile & profile) override virtual
Restores the state of the tool from the specified profile object.
Parameters
profile [in] The source for the state information. Typically an MeaFileProfile or MeaRegistryProfile object.
Reimplemented from MeaTool.
References MeaUnitsProvider::ConvertPos(), m_anchorPoint, m_center, MeaTool::m_unitsProvider, MeaProfile::ReadDbl(), SetPosition(), MeaUnitsProvider::UnconvertPos(), MeaFPoint::x, and MeaFPoint::y.
OnCHEnter()
void MeaPointTool::OnCHEnter (const CrossHairInfo * info) override virtual
Called when the pointer the tool's crosshair.
Parameters
info [in] Crosshair information structure
Reimplemented from MeaCrossHairCallback.
References m_dataWin, NormalUpdate, MeaDataWin::Show(), and Update().
OnCHLeave()
void MeaPointTool::OnCHLeave (const CrossHairInfo * info) override virtual
Called when the pointer leaves the tool's crosshair.
Parameters
info [in] Crosshair information structure
Reimplemented from MeaCrossHairCallback.
References MeaDataWin::Hide(), and m_dataWin.
OnCHMove()
void MeaPointTool::OnCHMove (const CrossHairInfo * info) override virtual
Called when the user attempts to drag the tool's crosshair.
The info parameter indicates where the crosshair is to be moved and the tool actually moves the crosshair to the new position. This allows the tool to perform vertical or horizontal locking and move the entire tool depending on which keyboard modifiers are pressed during the drag.
Parameters
info [in] Crosshair information structure
Reimplemented from MeaCrossHairCallback.
References MeaCrossHairCallback::CrossHairInfo::center, MeaCrossHairCallback::CrossHairInfo::flags, MeaGeometry::IsVerticallyOriented(), m_anchorPoint, m_center, NormalUpdate, SetPosition(), and Update().
RecordPosition()
void MeaPointTool::RecordPosition (MeaPosition & position) const override virtual
Records the position of the tool crosshair.
This method is called by the position log manager to record a position.
Parameters
position [in] The tool's crosshair position is recorded into the position log manager's position object.
Implements MeaRadioTool.
References MeaUnitsProvider::ConvertCoord(), m_center, MeaTool::m_unitsProvider, MeaPosition::RecordXY1(), and MeaPosition::SetToolName().
SaveProfile()
void MeaPointTool::SaveProfile (MeaProfile & profile) override virtual
Persists the state of the tool to the specified profile object.
Parameters
profile [in] The destination for the state information. Typically an MeaFileProfile or MeaRegistryProfile object.
Reimplemented from MeaTool.
References MeaUnitsProvider::ConvertPos(), m_center, MeaTool::m_unitsProvider, MeaProfile::WriteStr(), MeaFPoint::x, and MeaFPoint::y.
SetPosition() [1/2]
void MeaPointTool::SetPosition (const PointMap & points) override virtual
Sets the position of the tool.
This method is called by the position log manager to play back a tool's position that was previously recorded using the RecordPosition method.
Parameters
points [in] Map of positions for the tool's crosshairs.
Reimplemented from MeaRadioTool.
References m_center, NormalUpdate, SetPosition(), and Update().
SetPosition() [2/2]
void MeaPointTool::SetPosition (MeaDataFieldId which, int pixels) override virtual
Sets the position of the tool.
This method sets the position one location component at a time. For example, the x position of the crosshair is specified by calling this method with the new position and specifying the MeaX1Field for the which parameter.
Parameters
which [in] Position component
pixels [in] Position to set for the component, in pixels
Reimplemented from MeaTool.
References m_center, MeaX1Field, MeaY1Field, NormalUpdate, SetPosition(), and Update().
Strobe()
void MeaPointTool::Strobe () override virtual
Visually strobes the tool.
The tool crosshair is cycled between a highlight color and its normal color once. In addition, the data window attached to the crosshair is cycled between hidden and visible. Strobing the tool is done to visually confirm position recording.
Reimplemented from MeaRadioTool.
References MeaCrossHair::Flash(), MeaCrossHair::kStrobeCount, m_crossHair, m_dataWin, and MeaDataWin::Strobe().
Update()
void MeaPointTool::Update (MeaUpdateReason reason) override virtual
Requests that the tool update the display of its position data.
Parameters
reason [in] Reason why the update has been requested
Reimplemented from MeaTool.
References MeaUnitsProvider::ConvertCoord(), MeaTool::IsEnabled(), m_center, m_crossHair, m_dataWin, MeaTool::m_mgr, MeaTool::m_unitsProvider, MeaDataWin::ShowXY(), MeaToolMgr::ShowXY1(), MeaDataWin::Update(), MeaTool::Update(), and MeaToolMgr::UpdateScreenInfo().
Referenced by Enable(), OnCHEnter(), OnCHMove(), and SetPosition().
The documentation for this class was generated from the following files:
PointTool.h
PointTool.cpp
Copyright 2011 C Thing Software