Meazure: MeaUnitsLabel Class Reference
MeaUnitsLabel Class Reference
Base class for measurement units labels.
#include <Units.h>
Public Types
typedef std::map< int, CString > LabelMap
Maps a units identifier to the corresponding label string.
Public Member Functions
virtual ~MeaUnitsLabel ()
Destroys the base class instance for the label.
bool Create (UINT unitsId, DWORD style, const POINT &topLeft, CWnd *parentWnd, UINT id=0xffff)
Creates the underlying label control.
Public Member Functions inherited from MeaLabel
MeaLabel ()
Constructs a label object.
virtual ~MeaLabel ()
Destroys an instance of a label object.
bool Create (LPCTSTR label, DWORD style, const POINT &topLeft, CWnd *parentWnd, UINT id=0xffff)
Creates the window for the label.
bool Create (UINT labelID, DWORD style, const POINT &topLeft, CWnd *parentWnd, UINT id=0xffff)
Creates the window for the label.
Protected Member Functions
MeaUnitsLabel (UINT format, LabelMap &labels, int &width)
Base class constructor for the label instance.
UINT GetFormat () const
Returns the measurement type format string.
bool SetSize ()
Sets the overall width of the label object to the width of the widest label string over all the units.
CString ConstructLabel (int unitsId) const
Formats the label string corresponding to the specified units identifier.
Private Attributes
LabelMap & m_labelsRef
Maps units identifiers to label strings.
int & m_widthRef
Width of the label object, in pixels.
UINT m_format
Label format string identifier.
Detailed Description
Base class for measurement units labels.
The label is shown on the data display. There is a derived class for each type of measurement: angles, lengths, areas and resolutions.
Constructor & Destructor Documentation
MeaUnitsLabel()
MeaUnitsLabel::MeaUnitsLabel (UINT format, LabelMap & labels, int & width) protected
Base class constructor for the label instance.
Parameters
format [in] Format string that defines the type of measurement units (e.g. "sq.").
labels [in] Map of measurement identifiers to label strings.
width [out] Width of the labels, in pixels.
Member Function Documentation
ConstructLabel()
CString MeaUnitsLabel::ConstructLabel (int unitsId) const protected
Formats the label string corresponding to the specified units identifier.
Parameters
unitsId [in] Units identifier whose label is to be constructed.
Returns
Formatted label string (e.g. "sq. in").
References m_format, and m_labelsRef.
Referenced by Create(), SetSize(), MeaAngularUnitsLabel::SetUnits(), and MeaLinearUnitsLabel::SetUnits().
Create()
bool MeaUnitsLabel::Create (UINT unitsId, DWORD style, const POINT & topLeft, CWnd * parentWnd, UINT id = 0xffff)
Creates the underlying label control.
Parameters
unitsId [in] Units identifier.
style [in] Window style for the label as defined by CStatic.
topLeft [in] Location for the top left corner of the label, in pixels.
parentWnd [in] Parent window for the label.
id [in] Caller defined identifier.
Returns
true if the label was created successfully.
References ConstructLabel(), MeaLabel::Create(), and SetSize().
Referenced by MeaDataDisplay::DataItem::CreateAngleUnits(), MeaDataDisplay::DataItem::CreateAreaUnits(), MeaDataDisplay::DataItem::CreateLengthUnits(), and MeaDataDisplay::DataItem::CreateResUnits().
GetFormat()
UINT MeaUnitsLabel::GetFormat () const inline protected
Returns the measurement type format string.
Returns
Format string identifier.
References m_format.
Referenced by MeaLinearUnitsLabel::SetUnits().
SetSize()
bool MeaUnitsLabel::SetSize () protected
Sets the overall width of the label object to the width of the widest label string over all the units.
Returns
true if the size was set successfully.
References ConstructLabel(), m_labelsRef, m_widthRef, and MeaLayout::SetWindowSize().
Referenced by Create().
The documentation for this class was generated from the following files:
Units.h
Units.cpp
Copyright 2011 C Thing Software