Meazure: MeaLinearUnits Class Reference
MeaLinearUnits Class Reference abstract
There are two major categories of units: linear and angular.
#include <Units.h>
Public Member Functions
MeaLinearUnitsId GetUnitsId () const
Returns the identifier for the linear units.
virtual bool RequiresRes () const
Internally all measurements are in pixels.
CString Format (MeaLinearMeasurementId id, double value) const
Formats the specified linear measurement value using the precision for the specified measurement ID.
FPOINT ConvertCoord (const POINT &pos) const
Converts the specified coordinate from pixels to the desired units.
FPOINT ConvertPos (const POINT &pos) const
Converts the specified position from pixels to the desired units.
FSIZE ConvertRes (const FSIZE &res) const
Converts the specified resolution in pixels/inch to the desired units.
double UnconvertCoord (MeaConvertDir dir, const CWnd *wnd, double pos) const
Converts from the current units to pixels.
bool UnconvertCoord (MeaConvertDir dir, const CWnd *wnd, double pos, int &c1, int &c2) const
Converts from the current units to pixels.
POINT UnconvertCoord (const FPOINT &pos) const
Converts from the current units to pixels.
POINT UnconvertPos (const FPOINT &pos) const
Converts from the current units to pixels.
int GetMajorTickCount () const
Returns the number of minor ticks to display before a major tick mark is displayed on the measurement rulers.
FSIZE GetMinorIncr (const RECT &rect) const
Returns the increment between minor tick marks on the measurement rulers.
SIZE ConvertToPixels (const FSIZE &res, double value, int minPixels) const
Converts the specified value from the current units to pixels.
Public Member Functions inherited from MeaUnits
virtual void SaveProfile (MeaProfile &profile)
Persists the state of a units class instance to the specified profile object.
virtual void LoadProfile (MeaProfile &profile)
Restores the state of a units class instance from the specified profile object.
void SavePrecision (MeaProfile &profile)
Persists the measurement precisions to the specified profile object.
void LoadPrecision (MeaProfile &profile)
Restores the measurement precisions from the specified profile object.
virtual void MasterReset ()
Called to restores the units to their default state.
CString GetUnitsStr () const
Returns a string describing the units.
void SetDisplayPrecisions (const DisplayPrecisions &displayPrecisions)
Sets the decimal place precisions for all measurement types.
const DisplayPrecisions & GetDisplayPrecisions () const
Returns the current decimal place precisions for all measurement types.
const DisplayPrecisions & GetDefaultPrecisions () const
Returns the default decimal place precisions for all measurement types.
void RestoreDefaultPrecisions ()
Sets the default display precisions as the current precisions.
const DisplayPrecisionNames & GetDisplayPrecisionNames () const
Returns the identifying names for the display precisions.
Static Public Member Functions
static void SetInvertY (bool invertY)
By default, the Windows coordinate system is inverted from the typical Cartesian coordinate system in that the origin is located in the upper left corner of the primary screen and the positive y-axis points downward.
static bool GetInvertY ()
Returns the orientation of the y-axis.
static void SetOrigin (const POINT &origin)
Moves the origin of the coordinate system to the specified point.
static const POINT & GetOrigin ()
Returns the location of the origin of the coordinate system.
Protected Member Functions
MeaLinearUnits (MeaLinearUnitsId unitsId, LPCTSTR unitsStr)
Constructs the linear units.
virtual ~MeaLinearUnits ()
Destroys the linear units.
virtual FSIZE GetResFromPixels (const FSIZE &res) const
Returns a resolution conversion factor.
virtual FSIZE FromPixels (const FSIZE &res) const =0
Returns the X and Y factors to convert from pixels to the current units.
double ConvertCoord (MeaConvertDir dir, const CWnd *wnd, int pos) const
Converts from the pixels to the current units.
const FSIZE & FindResFromCoord (const FPOINT &pos) const
In a multiple monitor environment there are multiple screen resolutions, one set per monitor.
const FSIZE & FindResFromPos (const FPOINT &pos) const
In a multiple monitor environment there are multiple screen resolutions, one set per monitor.
Protected Member Functions inherited from MeaUnits
MeaUnits (LPCTSTR unitsStr)
Base class constructor.
virtual ~MeaUnits ()
Base class destructor.
void AddPrecisionName (LPCTSTR name)
Adds the specified identifying name to the list of precision names.
void AddPrecision (int precision)
Adds the specified precision value to both the list of current precisions and the list of default precisions.
Private Attributes
MeaLinearUnitsId m_unitsId
Linear units identifier.
int m_majorTickCount
Number of minor ruler tick marks between major tick marks.
Static Private Attributes
static const double kTickIncrements [] = { 10.0, 25.0, 50.0, 75.0, 100.0 }
Ruler tick increments.
static const int kNumTickIncrements = sizeof(kTickIncrements) / sizeof(*kTickIncrements)
Number of tick mark increments in the kTickIncrements array.
static const int kMinSepPixels = 5
Minimum separation between ruler tick marks, in pixels.
static const double kMinSepInches = 0.1
Minimum separation between ruler tick marks, in inches.
static POINT m_originOffset = { 0, 0 }
Offset of the origin from the system origin, in pixels.
static bool m_invertY = MeaUnitsMgr::kDefInvertY
Indicates if the y-axis direction is inverted.
Additional Inherited Members
Public Types inherited from MeaUnits
typedef std::vector< int > DisplayPrecisions
Number of decimal places to display for each type of measurement.
typedef std::vector< CString > DisplayPrecisionNames
Strings to identify units precisions in profiles.
Static Public Attributes inherited from MeaUnits
static const double kPI = 3.14159265359
The value of pi.
Detailed Description
There are two major categories of units: linear and angular.
The linear units cover distance related measurements (e.g. coordinates, distances, resolutions). This is the base class for all linear units.
Constructor & Destructor Documentation
MeaLinearUnits()
MeaLinearUnits::MeaLinearUnits (MeaLinearUnitsId unitsId, LPCTSTR unitsStr) protected
Constructs the linear units.
Parameters
unitsId [in] Identifier for the linear units.
unitsStr [in] Name for the units.
References MeaUnits::AddPrecisionName().
Member Function Documentation
ConvertCoord() [1/2]
FPOINT MeaLinearUnits::ConvertCoord (const POINT & pos) const
Converts the specified coordinate from pixels to the desired units.
This conversion takes into account the location of the origin and the orientation of the y-axis.
Parameters
pos [in] Coordinates in pixels to convert to the desired units.
Returns
Coordinates converted from pixels to the desired units. The conversion takes into account the location of the origin and the orientation of the y-axis.
References FSIZE::cx, FSIZE::cy, FromPixels(), MeaScreenMgr::GetScreenIter(), MeaScreenMgr::GetScreenRes(), MeaScreenMgr::GetVirtualRect(), MeaSingleton_T< MeaScreenMgr >::Instance(), m_invertY, m_originOffset, FPOINT::x, and FPOINT::y.
Referenced by MeaUnitsMgr::ConvertCoord(), FindResFromCoord(), and UnconvertCoord().
ConvertCoord() [2/2]
double MeaLinearUnits::ConvertCoord (MeaConvertDir dir, const CWnd * wnd, int pos) const protected
Converts from the pixels to the current units.
The conversion takes into account the location of the origin and the orientation of the y-axis. The conversion is performed for the specified coordinate located on the specified axis.
Parameters
dir [in] Axis on which the conversion should take place.
wnd [in] Window used to determine the screen resolution.
pos [in] Coordinate to convert from pixels.
Returns
Coordinate converted from pixels to the current units. The conversion takes into account the location of the origin and the orientation of the y-axis.
References FSIZE::cx, FSIZE::cy, FromPixels(), MeaScreenMgr::GetScreenIter(), MeaScreenMgr::GetScreenRes(), MeaScreenMgr::GetVirtualRect(), MeaSingleton_T< MeaScreenMgr >::Instance(), m_invertY, m_originOffset, and MeaConvertX.
ConvertPos()
FPOINT MeaLinearUnits::ConvertPos (const POINT & pos) const
Converts the specified position from pixels to the desired units.
This conversion does not take into account the location of the origin nor does it compensate for the orientation of the y-axis.
Parameters
pos [in] Position in pixels to convert to the desired units.
Returns
Position converted from pixels to the desired units. The conversion does not take into account the location of the origin nor does it compensate for the orientation of the y-axis.
References FSIZE::cx, FSIZE::cy, FromPixels(), MeaScreenMgr::GetScreenIter(), MeaScreenMgr::GetScreenRes(), MeaSingleton_T< MeaScreenMgr >::Instance(), FPOINT::x, and FPOINT::y.
Referenced by MeaUnitsMgr::ConvertPos(), and FindResFromPos().
ConvertRes()
FSIZE MeaLinearUnits::ConvertRes (const FSIZE & res) const
Converts the specified resolution in pixels/inch to the desired units.
Parameters
res [in] Resolution in pixels/inch to convert to the desired units.
Returns
Resolution converted from pixels/inch to the desired units.
References FSIZE::cx, FSIZE::cy, and GetResFromPixels().
Referenced by MeaUnitsMgr::ConvertRes().
ConvertToPixels()
SIZE MeaLinearUnits::ConvertToPixels (const FSIZE & res, double value, int minPixels) const
Converts the specified value from the current units to pixels.
A minimum pixel value is specified in case the resolution is such that the conversion to pixels results in a value that is too small.
Parameters
res [in] Screen resolution to use to perform the conversion.
value [in] Value to be converted to pixels.
minPixels [in] If the converted pixel value in less than this minimum value, the minimum value is returned.
Returns
X and Y pixel values.
References FSIZE::cx, FSIZE::cy, and FromPixels().
FindResFromCoord()
const FSIZE & MeaLinearUnits::FindResFromCoord (const FPOINT & pos) const protected
In a multiple monitor environment there are multiple screen resolutions, one set per monitor.
Therefore, to determine the a resolution, a screen must be determined. This method uses the specified position to determined a screen and thus a resolution. The method compensates for the location of the origin and the orientation of the y-axis.
Parameters
pos [in] Position used to determine a screen and thus a resolution, in the current units.
Returns
Screen resolution, in the current units.
References MeaScreenMgr::AtEnd(), ConvertCoord(), MeaScreenMgr::GetNumScreens(), MeaScreenMgr::GetScreenIter(), MeaScreenMgr::GetScreenRect(), MeaScreenMgr::GetScreenRes(), MeaSingleton_T< MeaScreenMgr >::Instance(), FPOINT::x, and FPOINT::y.
Referenced by UnconvertCoord().
FindResFromPos()
const FSIZE & MeaLinearUnits::FindResFromPos (const FPOINT & pos) const protected
In a multiple monitor environment there are multiple screen resolutions, one set per monitor.
Therefore, to determine the a resolution, a screen must be determined. This method uses the specified position to determined a screen and thus a resolution. The method does not compensate for the location of the origin nor the orientation of the y-axis.
Parameters
pos [in] Position used to determine a screen and thus a resolution, in the current units.
Returns
Screen resolution, in the current units.
References MeaScreenMgr::AtEnd(), ConvertPos(), MeaScreenMgr::GetNumScreens(), MeaScreenMgr::GetScreenIter(), MeaScreenMgr::GetScreenRect(), MeaScreenMgr::GetScreenRes(), MeaSingleton_T< MeaScreenMgr >::Instance(), FPOINT::x, and FPOINT::y.
Referenced by UnconvertPos().
Format()
CString MeaLinearUnits::Format (MeaLinearMeasurementId id, double value) const
Formats the specified linear measurement value using the precision for the specified measurement ID.
Parameters
id [in] Identifier for the linear units whose precision is to be used to format the specified value.
value [in] Measurement value to be formatted.
Returns
Measurement value formatted with the appropriate precision and returned as a string.
References MeaUnits::GetDisplayPrecisions().
Referenced by MeaUnitsMgr::Format(), and UnconvertCoord().
FromPixels()
virtual FSIZE MeaLinearUnits::FromPixels (const FSIZE & res) const protected pure virtual
Returns the X and Y factors to convert from pixels to the current units.
In other words, multiplying the values returned from this method by pixels results in a value expressed in the current units.
Parameters
res [in] Screen resolution, in pixels/inch.
Returns
X and Y conversion factors, in units/pixels.
Implemented in MeaPixelUnits, MeaPointUnits, MeaPicaUnits, MeaTwipUnits, MeaInchUnits, MeaCentimeterUnits, MeaMillimeterUnits, and MeaCustomUnits.
Referenced by ConvertCoord(), ConvertPos(), ConvertToPixels(), GetMinorIncr(), GetResFromPixels(), UnconvertCoord(), and UnconvertPos().
GetInvertY()
static bool MeaLinearUnits::GetInvertY () inline static
Returns the orientation of the y-axis.
Returns
If true is returned, the origin of the coordinate system is located at the lower left of the primary screen, and the positive y-axis is pointing upward. If false is returned, the origin is located at the upper left corner and the positive y-axis is pointing down. Note that the actual location of the origin is determined by the SetOrigin method.
References m_invertY.
Referenced by MeaUnitsMgr::GetInvertY().
GetMajorTickCount()
int MeaLinearUnits::GetMajorTickCount () const inline
Returns the number of minor ticks to display before a major tick mark is displayed on the measurement rulers.
Returns
Number of minor tick marks to display before displaying a major tick mark.
References m_majorTickCount.
Referenced by MeaRuler::DrawRuler().
GetMinorIncr()
FSIZE MeaLinearUnits::GetMinorIncr (const RECT & rect) const
Returns the increment between minor tick marks on the measurement rulers.
Parameters
rect [in] Rectangle in screen coordinates, used to determine the current screen resolution.
Returns
Increment for the minor tick marks, in the current units.
References MeaUnitsMgr::ConvertToPixels(), FSIZE::cx, FSIZE::cy, floor(), FromPixels(), MeaScreenMgr::GetScreenIter(), MeaScreenMgr::GetScreenRes(), MeaSingleton_T< MeaScreenMgr >::Instance(), MeaSingleton_T< MeaUnitsMgr >::Instance(), kMinSepInches, kMinSepPixels, kNumTickIncrements, kTickIncrements, log10(), and MeaInchesId.
Referenced by MeaRuler::DrawRuler().
GetOrigin()
static const POINT & MeaLinearUnits::GetOrigin () inline static
Returns the location of the origin of the coordinate system.
Returns
Location of the origin of the coordinate system, in pixels.
References m_originOffset.
Referenced by MeaUnitsMgr::GetOrigin().
GetResFromPixels()
FSIZE MeaLinearUnits::GetResFromPixels (const FSIZE & res) const protected virtual
Returns a resolution conversion factor.
For most units this is the same as the values returned by the FromPixels method. However, since internally the resolution is expressed as pixels per inch, the pixel units need to provide their own conversion factor.
Parameters
res [in] Resolution to convert.
Returns
Resolution conversion factor.
Reimplemented in MeaPixelUnits.
References FromPixels().
Referenced by ConvertRes().
GetUnitsId()
MeaLinearUnitsId MeaLinearUnits::GetUnitsId () const inline
Returns the identifier for the linear units.
Returns
Linear units ID.
References m_unitsId.
Referenced by MeaDataDisplay::DataItem::CreateAreaUnits(), MeaDataDisplay::DataItem::CreateLengthUnits(), MeaDataDisplay::DataItem::CreateResUnits(), MeaUnitsMgr::GetLinearUnitsId(), and MeaPositionLogMgr::Position::Show().
RequiresRes()
bool MeaLinearUnits::RequiresRes () const virtual
Internally all measurements are in pixels.
Measurement units based solely on pixels do not require the use of the screen resolution for conversion. Measurement units such as inches, require the screen resolution for conversion from pixels. This method indicates whether the screen resolution is required for conversion from pixels to the desired measurement units and vice versa.
Returns
true if the screen resolution must be used to convert to and from pixels. This base class implementation always returns true.
Reimplemented in MeaPixelUnits, and MeaCustomUnits.
Referenced by MeaUnitsMgr::SetLinearUnits().
SetInvertY()
static void MeaLinearUnits::SetInvertY (bool invertY) inline static
By default, the Windows coordinate system is inverted from the typical Cartesian coordinate system in that the origin is located in the upper left corner of the primary screen and the positive y-axis points downward.
This method sets whether the y-axis should be inverted so that the origin is moved to the lower left corner of the primary screen and the positive y-axis points up. Note that the actual location of the origin is determined by the SetOrigin method.
Parameters
invertY [in] true inverts the y-axis, placing the origin at the lower left of the primary display screen and making positive y pointing upward.
References m_invertY.
Referenced by MeaUnitsMgr::SetInvertY().
SetOrigin()
static void MeaLinearUnits::SetOrigin (const POINT & origin) inline static
Moves the origin of the coordinate system to the specified point.
The orientation of the axes is not effected by this method. To change the orientation of the y-axis use the SetInvertY method.
Parameters
origin [in] New location for the origin of the coordinate system. in pixels.
References m_originOffset.
Referenced by MeaUnitsMgr::SetOrigin().
UnconvertCoord() [1/3]
POINT MeaLinearUnits::UnconvertCoord (const FPOINT & pos) const
Converts from the current units to pixels.
The conversion takes into account the location of the origin and the orientation of the y-axis.
Parameters
pos [in] Coordinates to convert to pixels.
Returns
Coordinates converted from the current units to pixels. The conversion takes into account the location of the origin and the orientation of the y-axis.
References FSIZE::cx, FSIZE::cy, FindResFromCoord(), FromPixels(), MeaScreenMgr::GetVirtualRect(), MeaSingleton_T< MeaScreenMgr >::Instance(), m_invertY, m_originOffset, FPOINT::x, and FPOINT::y.
UnconvertCoord() [2/3]
double MeaLinearUnits::UnconvertCoord (MeaConvertDir dir, const CWnd * wnd, double pos) const
Converts from the current units to pixels.
The conversion takes into account the location of the origin and the orientation of the y-axis. The conversion is performed for the specified coordinate located on the specified axis.
Parameters
dir [in] Axis on which the conversion should take place.
wnd [in] Window used to determine the screen resolution.
pos [in] Coordinate to convert to pixels.
Returns
Coordinate converted from the current units to pixels. The conversion takes into account the location of the origin and the orientation of the y-axis.
References FSIZE::cx, FSIZE::cy, FromPixels(), MeaScreenMgr::GetScreenIter(), MeaScreenMgr::GetScreenRes(), MeaScreenMgr::GetVirtualRect(), MeaSingleton_T< MeaScreenMgr >::Instance(), m_invertY, m_originOffset, and MeaConvertX.
Referenced by MeaRuler::DrawRuler(), MeaUnitsMgr::UnconvertCoord(), and UnconvertCoord().
UnconvertCoord() [3/3]
bool MeaLinearUnits::UnconvertCoord (MeaConvertDir dir, const CWnd * wnd, double pos, int & c1, int & c2) const
Converts from the current units to pixels.
The conversion takes into account the location of the origin and the orientation of the y-axis. The conversion is performed for the specified coordinate located on the specified axis. Since the specified coordinate might not convert to an integral number of pixels, this method returns the bounding integral pixel values and indicates whether an exact integral conversion could be performed.
Parameters
dir [in] Axis on which the conversion should take place.
wnd [in] Window used to determine the screen resolution.
pos [in] Coordinate to convert to pixels.
c1 [out] Closest integral pixel value below the converted coordinate.
c2 [out] Closest integral pixel value above the converted coordinate.
Returns
true if the conversion to pixels was exact.
References ConvertCoord(), Format(), MeaX, and UnconvertCoord().
UnconvertPos()
POINT MeaLinearUnits::UnconvertPos (const FPOINT & pos) const
Converts from the current units to pixels.
The conversion does not take into account the location of the origin nor the orientation of the y-axis.
Parameters
pos [in] Position to convert to pixels.
Returns
Position converted from the current units to pixels. The conversion does not take into account the location of the origin nor the orientation of the y-axis.
References FSIZE::cx, FSIZE::cy, FindResFromPos(), FromPixels(), FPOINT::x, and FPOINT::y.
Referenced by MeaUnitsMgr::UnconvertPos().
Member Data Documentation
kTickIncrements
const double MeaLinearUnits::kTickIncrements = { 10.0, 25.0, 50.0, 75.0, 100.0 } static private
Ruler tick increments.
The order of magnitude of these values is adjusted based on the units.
Referenced by GetMinorIncr().
The documentation for this class was generated from the following files:
Units.h
Units.cpp
Copyright 2011 C Thing Software