Meazure: MeaPositionDesktopRef Class Reference
MeaPositionDesktopRef Class Reference
References a desktop information object.
#include <PositionDesktop.h>
Public Member Functions
MeaPositionDesktopRef (MeaPositionDesktopRefCounter *counter, const MeaPositionDesktop &desktop)
Constructs a reference to the specified desktop information object.
MeaPositionDesktopRef (MeaPositionDesktopRefCounter *counter, const CString &idStr)
Constructs a reference to the specified desktop information object.
MeaPositionDesktopRef (const MeaPositionDesktopRef &ref)
Makes a copy of the specified desktop information reference.
MeaPositionDesktopRef & operator= (const MeaPositionDesktopRef &ref)
bool operator== (const MeaPositionDesktopRef &ref) const
bool operator!= (const MeaPositionDesktopRef &ref) const
const MeaGUID & GetId () const
CString ToString () const
Private Attributes
MeaPositionDesktopRefCounter * m_counter
MeaGUID m_id
Detailed Description
References a desktop information object.
Position objects hold a reference to the desktop on which they were recorded. References to desktop information object are reference counted so that unreferenced desktop information is not written to the log file. This class hides the reference counting details from the position object.
Constructor & Destructor Documentation
MeaPositionDesktopRef() [1/3]
MeaPositionDesktopRef::MeaPositionDesktopRef (MeaPositionDesktopRefCounter * counter, const MeaPositionDesktop & desktop) inline
Constructs a reference to the specified desktop information object.
Parameters
counter [in] Reference count manager
desktop [in] Desktop information object to reference
References MeaPositionDesktopRefCounter::AddDesktopRef().
MeaPositionDesktopRef() [2/3]
MeaPositionDesktopRef::MeaPositionDesktopRef (MeaPositionDesktopRefCounter * counter, const CString & idStr) inline
Constructs a reference to the specified desktop information object.
This constructor is used during deserialization of the position log file.
Parameters
counter [in] Reference count manager
idStr [in] GUID identifier for a desktop information object
References MeaPositionDesktopRefCounter::AddDesktopRef().
MeaPositionDesktopRef() [3/3]
MeaPositionDesktopRef::MeaPositionDesktopRef (const MeaPositionDesktopRef & ref) inline
Makes a copy of the specified desktop information reference.
Parameters
ref [in] Desktop information object to copy
References MeaPositionDesktopRefCounter::AddDesktopRef().
The documentation for this class was generated from the following file:
PositionDesktop.h
Copyright 2011 C Thing Software