Meazure: MeaProfile Class Reference
MeaProfile Class Reference abstract
Base class for the persisting the application state to either the Registry or a file.
#include <Profile.h>
Public Member Functions
virtual bool WriteBool (LPCTSTR key, bool value)=0
Writes a boolean value to the specified key.
virtual bool WriteInt (LPCTSTR key, int value)=0
Writes an integer value to the specified key.
virtual bool WriteDbl (LPCTSTR key, double value)=0
Writes a double value to the specified key.
virtual bool WriteStr (LPCTSTR key, LPCTSTR value)=0
Writes a string value to the specified key.
virtual bool ReadBool (LPCTSTR key, bool defaultValue)=0
Reads a boolean value from the specified key.
virtual UINT ReadInt (LPCTSTR key, int defaultValue)=0
Reads an unsigned integer value from the specified key.
virtual double ReadDbl (LPCTSTR key, double defaultValue)=0
Reads a double value from the specified key.
virtual CString ReadStr (LPCTSTR key, LPCTSTR defaultValue)=0
Reads a string value from the specified key.
virtual bool UserInitiated ()=0
Indicates whether the profile is being written at the user's request (i.e.
virtual int GetVersion ()=0
Returns the profile format version number.
Detailed Description
Base class for the persisting the application state to either the Registry or a file.
Member Function Documentation
GetVersion()
virtual int MeaProfile::GetVersion () pure virtual
Returns the profile format version number.
Returns
Profile format version number.
Implemented in MeaFileProfile, and MeaRegistryProfile.
Referenced by MeaScreenMgr::LoadProfile(), and MeaUnitsMgr::LoadProfile().
ReadBool()
virtual bool MeaProfile::ReadBool (LPCTSTR key, bool defaultValue) pure virtual
Reads a boolean value from the specified key.
Parameters
key [in] Profile key to read
defaultValue [in] Default value to use if the key is not found in the profile.
Returns
Boolean value for the key or the default value if the key is not found.
Implemented in MeaFileProfile, and MeaRegistryProfile.
Referenced by AppFrame::LoadProfile(), MeaToolMgr::LoadProfile(), AppView::LoadProfile(), MeaDataWin::LoadProfile(), MeaMagnifier::LoadProfile(), MeaScreenMgr::LoadProfile(), MeaUnitsMgr::LoadProfile(), MeaGridTool::LoadProfile(), MeaOriginTool::LoadProfile(), and MeaRulerTool::LoadProfile().
ReadDbl()
virtual double MeaProfile::ReadDbl (LPCTSTR key, double defaultValue) pure virtual
Reads a double value from the specified key.
Parameters
key [in] Profile key to read
defaultValue [in] Default value to use if the key is not found in the profile.
Returns
Double value for the key or the default value if the key is not found.
Implemented in MeaFileProfile, and MeaRegistryProfile.
Referenced by MeaScreenMgr::LoadProfile(), MeaUnitsMgr::LoadProfile(), MeaAngleTool::LoadProfile(), MeaCircleTool::LoadProfile(), MeaLineTool::LoadProfile(), MeaPointTool::LoadProfile(), MeaRectTool::LoadProfile(), and MeaCustomUnits::LoadProfile().
ReadInt()
virtual UINT MeaProfile::ReadInt (LPCTSTR key, int defaultValue) pure virtual
Reads an unsigned integer value from the specified key.
Parameters
key [in] Profile key to read
defaultValue [in] Default value to use if the key is not found in the profile.
Returns
Integer value for the key or the default value if the key is not found.
Implemented in MeaFileProfile, and MeaRegistryProfile.
Referenced by MeaUnits::LoadPrecision(), AppFrame::LoadProfile(), MeaColors::LoadProfile(), MeaColorDialog::LoadProfile(), MeaMagnifier::LoadProfile(), MeaScreenMgr::LoadProfile(), MeaUnitsMgr::LoadProfile(), MeaGridTool::LoadProfile(), and MeaRulerTool::LoadProfile().
ReadStr()
virtual CString MeaProfile::ReadStr (LPCTSTR key, LPCTSTR defaultValue) pure virtual
Reads a string value from the specified key.
Parameters
key [in] Profile key to read
defaultValue [in] Default value to use if the key is not found in the profile.
Returns
String value for the key or the default value if the key is not found.
Implemented in MeaFileProfile, and MeaRegistryProfile.
Referenced by MeaPositionLogMgr::LoadProfile(), MeaProfileMgr::LoadProfile(), MeaToolMgr::LoadProfile(), AppView::LoadProfile(), MeaUnitsMgr::LoadProfile(), and MeaCustomUnits::LoadProfile().
UserInitiated()
virtual bool MeaProfile::UserInitiated () pure virtual
Indicates whether the profile is being written at the user's request (i.e.
a file profile).
Returns
true if the user initiated the profile writing. The base class implementation of this method always returns false.
Implemented in MeaFileProfile, and MeaRegistryProfile.
Referenced by AppFrame::LoadProfile(), MeaColors::LoadProfile(), MeaPositionLogMgr::LoadProfile(), MeaProfileMgr::LoadProfile(), MeaToolMgr::LoadProfile(), AppView::LoadProfile(), MeaColorDialog::LoadProfile(), MeaDataWin::LoadProfile(), MeaMagnifier::LoadProfile(), MeaScreenMgr::LoadProfile(), MeaUnits::LoadProfile(), MeaUnitsMgr::LoadProfile(), AppFrame::SaveProfile(), MeaColors::SaveProfile(), MeaToolMgr::SaveProfile(), AppView::SaveProfile(), MeaColorDialog::SaveProfile(), MeaDataWin::SaveProfile(), MeaMagnifier::SaveProfile(), MeaUnits::SaveProfile(), MeaUnitsMgr::SaveProfile(), MeaPositionLogMgr::SaveProfile(), MeaProfileMgr::SaveProfile(), and MeaScreenMgr::SaveProfile().
WriteBool()
virtual bool MeaProfile::WriteBool (LPCTSTR key, bool value) pure virtual
Writes a boolean value to the specified key.
Parameters
key [in] Profile key to write
value [in] Boolean value for the key
Returns
true if successful.
Implemented in MeaFileProfile, and MeaRegistryProfile.
Referenced by AppFrame::SaveProfile(), MeaToolMgr::SaveProfile(), AppView::SaveProfile(), MeaDataWin::SaveProfile(), MeaMagnifier::SaveProfile(), MeaUnitsMgr::SaveProfile(), MeaScreenMgr::SaveProfile(), MeaGridTool::SaveProfile(), MeaOriginTool::SaveProfile(), and MeaRulerTool::SaveProfile().
WriteDbl()
virtual bool MeaProfile::WriteDbl (LPCTSTR key, double value) pure virtual
Writes a double value to the specified key.
Parameters
key [in] Profile key to write
value [in] Double value for the key
Returns
true if successful.
Implemented in MeaFileProfile, and MeaRegistryProfile.
Referenced by MeaCustomUnits::SaveProfile().
WriteInt()
virtual bool MeaProfile::WriteInt (LPCTSTR key, int value) pure virtual
Writes an integer value to the specified key.
Parameters
key [in] Profile key to write
value [in] Integer value for the key
Returns
true if successful.
Implemented in MeaFileProfile, and MeaRegistryProfile.
Referenced by MeaUnits::SavePrecision(), AppFrame::SaveProfile(), MeaColors::SaveProfile(), MeaColorDialog::SaveProfile(), MeaMagnifier::SaveProfile(), MeaScreenMgr::SaveProfile(), MeaGridTool::SaveProfile(), and MeaRulerTool::SaveProfile().
WriteStr()
virtual bool MeaProfile::WriteStr (LPCTSTR key, LPCTSTR value) pure virtual
Writes a string value to the specified key.
Parameters
key [in] Profile key to write
value [in] String value for the key
Returns
true if successful.
Implemented in MeaFileProfile, and MeaRegistryProfile.
Referenced by MeaToolMgr::SaveProfile(), AppView::SaveProfile(), MeaUnitsMgr::SaveProfile(), MeaPositionLogMgr::SaveProfile(), MeaProfileMgr::SaveProfile(), MeaScreenMgr::SaveProfile(), MeaAngleTool::SaveProfile(), MeaCircleTool::SaveProfile(), MeaLineTool::SaveProfile(), MeaPointTool::SaveProfile(), MeaRectTool::SaveProfile(), and MeaCustomUnits::SaveProfile().
The documentation for this class was generated from the following file:
Profile.h
Copyright 2011 C Thing Software