Meazure: MeaCursorTool Class Reference
MeaCursorTool Class Reference
Cursor position measurement tool.
#include <CursorTool.h>
Public Member Functions
MeaCursorTool (MeaToolMgr &mgr, const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Constructs a new instance of a cursor position measurement tool.
virtual ~MeaCursorTool ()
Destroys the Cursor tool.
virtual void Enable () override
Enables the Cursor tool's data window.
virtual void Disable () override
Disables the Cursor tool's data window.
virtual void Update (MeaUpdateReason reason) override
Requests that the tool update the display of its position data.
virtual bool HasCrosshairs () const override
Indicates whether the tool has crosshairs.
virtual void Strobe () override
Visually strobes the tool.
virtual const POINT & GetPosition () const override
Returns the position of the mouse pointer.
virtual void RecordPosition (MeaPosition &position) const override
Records the position of the mouse pointer.
virtual PCTSTR GetToolName () const override
Returns the name of the tool.
virtual UINT GetLabelId () const override
Returns a resource ID for the string used to label this tool on the data display.
virtual void ColorsChanged () override
Called to notify the tool that the colors in the MeaColors class have been changed.
virtual void OnMouseHook (WPARAM wParam, LPARAM lParam) override
Called by the OS when the mouse pointer is moved.
Public Member Functions inherited from MeaRadioTool
MeaRadioTool (MeaToolMgr &mgr, const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Constructs a new instance of an radio based measurement tool.
virtual bool IsRadioTool () override
Indicates that the derived tool is a Radio tool and cannot be enabled until any other enabled Radio tool is disabled.
virtual UINT GetLabelId () const
Returns a resource ID for the string used to label this tool on the data display.
virtual bool HasCrosshairs () const
Indicates whether the derived tool uses crosshairs.
virtual void EnableCrosshairs ()
Displays the tool's crosshairs.
virtual void DisableCrosshairs ()
Hides the tool's crosshairs.
virtual void Flash ()
Visually flashes the tool.
virtual void Strobe ()
Visually strobes the tool.
virtual bool HasRegion ()
Indicates whether the tool can define a rectangular region that can then be read for a screen capture.
virtual RECT GetRegion ()
Returns the rectangle defined by the tool.
virtual void SetPosition (const PointMap &points)
Sets the position of the tool.
virtual void RecordPosition (MeaPosition &position) const =0
Records the position of the tool.
virtual void OnMouseHook (WPARAM wParam, LPARAM lParam)
Called by the OS when the mouse pointer is moved.
Public Member Functions inherited from MeaTool
MeaTool (MeaToolMgr &mgr, const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Base class constructor.
virtual ~MeaTool ()=default
Destroys the tool.
virtual void Enable ()
Typically used by derived classes to show the tool.
virtual void Disable ()
Typically used by derived classes to hide the tool.
virtual void Update (MeaUpdateReason reason)
Used by derived classes to update the display of their data.
virtual bool IsRadioTool ()
Indicates whether the derived tool is a radio tool and cannot be enabled until any other enabled Radio tool is disabled.
virtual void SetPosition (MeaDataFieldId which, int pixels)
Sets the position of the tool.
virtual const POINT & GetPosition () const =0
Returns the tool's current position.
virtual void IncPosition (MeaDataFieldId which)
Increments the specified position field.
virtual void DecPosition (MeaDataFieldId which)
Decrements the specified position field.
virtual PCTSTR GetToolName () const =0
Returns the name of the tool.
virtual void SaveProfile (MeaProfile &profile)
Persists the state of the tool to the specified profile object.
virtual void LoadProfile (MeaProfile &profile)
Restores the state of the tool from the specified profile object.
virtual void MasterReset ()
Resets the tool to its default state.
virtual void ColorsChanged ()
Called to notify the tool that the colors in the MeaColors class have been changed.
bool IsEnabled () const
Indicates whether the tool is enabled.
Static Public Attributes
static constexpr PCTSTR kToolName { _T("CursorTool") }
Private Member Functions
void Create ()
Creates the tool's data window.
Private Attributes
CPoint m_cursorPos
Cached position of the mouse pointer.
MeaDataWin m_dataWin
Data window tooltip attached to the mouse pointer.
int m_xDist
Half the width of the cursor.
int m_yDist
Half the height of the cursor.
Additional Inherited Members
Public Types inherited from MeaRadioTool
typedef std::map< CString, POINT > PointMap
Map of points used to set the position of a tool.
Protected Attributes inherited from MeaTool
MeaToolMgr & m_mgr
Tool manager.
const MeaScreenProvider & m_screenProvider
Screen information provider.
const MeaUnitsProvider & m_unitsProvider
Units information provider.
bool m_enabled
Indicates whether the tool is enabled.
Static Protected Attributes inherited from MeaTool
static const CPoint m_defaultPos
A default position used by tools that do not have a defined position.
Detailed Description
Cursor position measurement tool.
This tool measures the position of the mouse pointer.
Constructor & Destructor Documentation
MeaCursorTool()
MeaCursorTool::MeaCursorTool (MeaToolMgr & mgr, const MeaScreenProvider & screenProvider, const MeaUnitsProvider & unitsProvider) explicit
Constructs a new instance of a cursor position measurement tool.
To use a newly constructed Cursor tool, the Enable() method must be called. Enable() will call the Create() method the first time it is called if Create() has not previously been called.
Parameters
mgr [in] Tool manager parent of the Cursor tool.
screenProvider [in] Screen information provider
unitsProvider [in] Units information provider
Member Function Documentation
ColorsChanged()
void MeaCursorTool::ColorsChanged () override virtual
Called to notify the tool that the colors in the MeaColors class have been changed.
The data window opacity is updated.
Reimplemented from MeaTool.
References MeaColors::CrossHairOpacity, MeaColors::GetA(), m_dataWin, and MeaDataWin::SetOpacity().
Create()
void MeaCursorTool::Create () private
Creates the tool's data window.
The Enable() method must be called to make the data window visible.
References MeaDataWin::Create(), MeaColors::CrossHairOpacity, MeaColors::GetA(), m_dataWin, m_xDist, and m_yDist.
Referenced by Enable().
Disable()
void MeaCursorTool::Disable () override virtual
Disables the Cursor tool's data window.
Reimplemented from MeaTool.
References MeaTool::Disable(), MeaDataWin::Hide(), MeaTool::IsEnabled(), m_dataWin, and MeaDisableMouseHook().
Referenced by ~MeaCursorTool().
Enable()
void MeaCursorTool::Enable () override virtual
Enables the Cursor tool's data window.
If the Create() method has not been previously called, it will be called by Enable.
Reimplemented from MeaTool.
References Create(), MeaTool::Enable(), MeaToolMgr::EnableRegionFields(), MeaTool::IsEnabled(), m_cursorPos, m_dataWin, MeaTool::m_mgr, MeaEnableMouseHook(), MeaX1Field, MeaY1Field, MeaToolMgr::SetStatus(), and MeaDataWin::Show().
GetLabelId()
UINT MeaCursorTool::GetLabelId () const override virtual
Returns a resource ID for the string used to label this tool on the data display.
Returns
Resource ID for the label.
Reimplemented from MeaRadioTool.
GetPosition()
const POINT & MeaCursorTool::GetPosition () const override virtual
Returns the position of the mouse pointer.
Returns
Position of the mouse pointer.
Implements MeaTool.
References m_cursorPos.
GetToolName()
PCTSTR MeaCursorTool::GetToolName () const override virtual
Returns the name of the tool.
Each tool has a unique name which is used to identify the tool in profiles and position logs.
Returns
Always "CursorTool". The memory for the string is owned by the tool.
Implements MeaTool.
HasCrosshairs()
bool MeaCursorTool::HasCrosshairs () const override virtual
Indicates whether the tool has crosshairs.
Returns
Always false because this tool only consists of a data window attached to the mouse pointer.
Reimplemented from MeaRadioTool.
OnMouseHook()
void MeaCursorTool::OnMouseHook (WPARAM wParam, LPARAM lParam) override virtual
Called by the OS when the mouse pointer is moved.
Parameters
wParam [in] OS Message ID
lParam [in] MOUSEHOOKSTRUCT
Reimplemented from MeaRadioTool.
References m_cursorPos, NormalUpdate, and Update().
RecordPosition()
void MeaCursorTool::RecordPosition (MeaPosition & position) const override virtual
Records the position of the mouse pointer.
This method is called by the position log manager to record a position.
Parameters
position [in] The position of the mouse pointer is recorded into the position log manager's position object.
Implements MeaRadioTool.
References MeaUnitsProvider::ConvertCoord(), m_cursorPos, MeaTool::m_unitsProvider, MeaPosition::RecordXY1(), and MeaPosition::SetToolName().
Strobe()
void MeaCursorTool::Strobe () override virtual
Visually strobes the tool.
The tool's data window is cycled between hidden and visible. Strobing the tool is done to visually confirm position recording.
Reimplemented from MeaRadioTool.
References m_dataWin, and MeaDataWin::Strobe().
Update()
void MeaCursorTool::Update (MeaUpdateReason reason) override virtual
Requests that the tool update the display of its position data.
Parameters
reason [in] Reason why the update has been requested
Reimplemented from MeaTool.
References MeaUnitsProvider::ConvertCoord(), DataWinArming, MeaDataWin::Hide(), MeaDataWin::IsArmed(), MeaTool::IsEnabled(), m_cursorPos, m_dataWin, MeaTool::m_mgr, MeaTool::m_unitsProvider, m_xDist, m_yDist, OriginChanged, MeaDataWin::Show(), MeaDataWin::ShowXY(), MeaToolMgr::ShowXY1(), UnitsChanged, MeaDataWin::Update(), MeaTool::Update(), and MeaToolMgr::UpdateScreenInfo().
Referenced by OnMouseHook().
The documentation for this class was generated from the following files:
CursorTool.h
CursorTool.cpp
Copyright 2011 C Thing Software