Meazure: ev::ParseNode Class Reference
ev::ParseNode Class Reference
Represents a node in the parse tree that is constructed by parsing the content model.
Classes
struct LessOp
Used by STL to compare two ParseNode objects.
Public Types
enum Type {
End ,
Epsilon ,
Name ,
Choice ,
Seq ,
Rep ,
Opt ,
Plus
}
Type of the parse node.
typedef std::set< ParseNode *, LessOp > NodeSet
A set of parse nodes.
typedef NodeSet::iterator NodeIter
Iterator over a set of parse nodes.
typedef NodeSet::const_iterator NodeIter_c
Constant iterator over a set of parse nodes.
Public Member Functions
ParseNode (Type type)
Constructs a parse node of the specified type.
ParseNode (Type type, ParseNode *left)
Constructs a parse node of the specified type and with the specified left child node.
virtual ~ParseNode ()
Destroys a parse node instance.
ParseNode * CloneType () const
Creates a copy of this node.
Type GetType () const
Returns the type of the parse node.
bool IsEnd () const
Indicates whether the node is a terminal node.
bool IsEpsilon () const
Indicates whether the node is an any input node.
bool IsName () const
Indicates whether the node contains an element name.
bool IsChoice () const
Indicates whether the node is an OR'd choice node.
bool IsSeq () const
Indicates whether the node is a sequence node.
bool IsRep () const
Indicates whether the cardinality of the node is zero of more.
bool IsOpt () const
Indicates whether the cardinality of the node is zero or one.
bool IsPlus () const
Indicates whether the cardinality of the node is one or more.
bool HaveLeft () const
Indicates whether this node has a child on its left branch.
bool HaveRight () const
Indicates whether this node has a child on its right branch.
void SetLeft (ParseNode *node)
Sets the specified parse node as the left side child of this node.
void SetRight (ParseNode *node)
Sets the specified parse node as the right side child of this node.
const ParseNode * GetLeft () const
Returns the left branch child node of this node.
const ParseNode * GetRight () const
Returns the right branch child node of this node.
ParseNode * GetRight ()
Returns the right branch child node of this node.
void SetSymbol (const XML_Char *symbol)
Sets the input symbol for this parse node.
void SetSymbol (const EVString &symbol)
Sets the input symbol for this parse node.
EVString GetSymbol () const
Returns the input symbol for this parse node.
void GetSymbolSet (SymbolSet &symbols) const
Fills the specified set with the input symbols for the parse tree.
void BuildFollowpos ()
Pre-constructs the followpos function as described in section 3.9 of the Dragon book.
int GetId () const
Returns the ID of this parse node.
const NodeSet & GetFirstpos () const
Returns the nodes that comprise the firstpos() set as defined in section 3.9 of the Dragon book.
const NodeSet & GetFollowpos () const
Returns the nodes that comprise the followpos() set as defined in section 3.9 of the Dragon book.
Static Public Member Functions
static void ResetId ()
Resets the ID assigned to the parse nodes.
static void Union (NodeSet &set1, const NodeSet &set2)
Performs a set union on the two specified sets of nodes.
static bool EqualOp (const ParseNode *n1, const ParseNode *n2)
Tests whether the two specified parse nodes are equal.
Protected Member Functions
ParseNode (const ParseNode &node)
Purposely undefined.
ParseNode & operator= (const ParseNode &node)
Purposely undefined.
void Nullable ()
Implements the nullable() function as defined in section 3.9 of the Dragon book.
void Firstpos ()
Implements the firstpos() function as defined in section 3.9 of the Dragon book.
void Lastpos ()
Implements the lastpos() function as defined in section 3.9 of the Dragon book.
void Followpos ()
Implements the followpos() function as defined in section 3.9 of the Dragon book.
Protected Attributes
int m_id
ID for this parse node.
Type m_type
Parse node's type.
ParseNode * m_left
Parse node's left child node.
ParseNode * m_right
Parse node's right child node.
EVString m_symbol
Input symbol.
bool m_nullable
true if the node is nullable.
NodeSet m_firstPos
Set of nodes that satisfy firstpos() for this node.
NodeSet m_lastPos
Set of nodes that satisfy lastpos() for this node.
NodeSet m_followPos
Set of nodes that satisfy followpos() for this node.
Static Protected Attributes
static int m_currentId = 0
ID to assign to the parse node created next.
Friends
EVOstream & operator<< (EVOstream &stream, const ParseNode *node)
Output stream operator for a parse node.
Detailed Description
Represents a node in the parse tree that is constructed by parsing the content model.
Creating a parse tree is the first step in creating a DFA for an element's content model. The parse tree is constructed according to the technique presented in algorithm 3.5 from the Dragon book.
Member Enumeration Documentation
Type
enum ev::ParseNode::Type
Type of the parse node.
Enumerator
End
Terminal node.
Epsilon
The any input node.
Name
An element name node.
Choice
An OR'd choice node.
Seq
A sequence node.
Rep
A zero or more node.
Opt
A zero or one node.
Plus
A one or mode node.
Constructor & Destructor Documentation
ParseNode() [1/2]
ParseNode::ParseNode (Type type) explicit
Constructs a parse node of the specified type.
Parameters
type [in] Parse node type.
Referenced by CloneType().
ParseNode() [2/2]
ParseNode::ParseNode (Type type, ParseNode * left)
Constructs a parse node of the specified type and with the specified left child node.
Parameters
type [in] Parse node type.
left [in] Left child node.
Member Function Documentation
CloneType()
ParseNode * ev::ParseNode::CloneType () const inline
Creates a copy of this node.
Returns
Copy of this node.
References m_type, and ParseNode().
Referenced by ev::DFA::BuildParseTree().
EqualOp()
static bool ev::ParseNode::EqualOp (const ParseNode * n1, const ParseNode * n2) inline static
Tests whether the two specified parse nodes are equal.
Parameters
n1 [in] First parse node
n2 [in] Second parse node
Returns
true if n1's ID == n2's ID.
References GetId().
Referenced by ev::State::operator==().
GetFirstpos()
const NodeSet & ev::ParseNode::GetFirstpos () const inline
Returns the nodes that comprise the firstpos() set as defined in section 3.9 of the Dragon book.
Returns
Set of nodes comprising the firstpos() set.
References m_firstPos.
Referenced by ev::DFA::BuildComplexDFA().
GetFollowpos()
const NodeSet & ev::ParseNode::GetFollowpos () const inline
Returns the nodes that comprise the followpos() set as defined in section 3.9 of the Dragon book.
Returns
Set of nodes comprising the followpos() set.
References m_followPos.
GetId()
int ev::ParseNode::GetId () const inline
Returns the ID of this parse node.
Returns
ID of this parse node.
References m_id.
Referenced by EqualOp(), and ev::ParseNode::LessOp::operator()().
GetLeft()
const ParseNode * ev::ParseNode::GetLeft () const inline
Returns the left branch child node of this node.
Returns
Child node on the left branch or NULL if there is no left child.
References m_left.
Referenced by ev::operator<<().
GetRight() [1/2]
ParseNode * ev::ParseNode::GetRight () inline
Returns the right branch child node of this node.
Returns
Child node on the right branch or NULL if there is no right child.
References m_right.
GetRight() [2/2]
const ParseNode * ev::ParseNode::GetRight () const inline
Returns the right branch child node of this node.
Returns
Child node on the right branch or NULL if there is no right child.
References m_right.
Referenced by ev::DFA::BuildParseTree(), and ev::operator<<().
GetSymbol()
EVString ev::ParseNode::GetSymbol () const inline
Returns the input symbol for this parse node.
Returns
Input symbol for this parse node.
References m_symbol.
Referenced by ev::operator<<().
GetSymbolSet()
void ParseNode::GetSymbolSet (SymbolSet & symbols) const
Fills the specified set with the input symbols for the parse tree.
Parameters
symbols [out] Set to be filled with the input symbols.
References GetSymbolSet(), m_left, m_right, and m_symbol.
Referenced by ev::DFA::BuildComplexDFA(), GetSymbolSet(), and ev::operator<<().
GetType()
Type ev::ParseNode::GetType () const inline
Returns the type of the parse node.
Returns
Parse node type.
References m_type.
Referenced by ev::operator<<().
HaveLeft()
bool ev::ParseNode::HaveLeft () const inline
Indicates whether this node has a child on its left branch.
Returns
true if a child node exists on the left branch.
References m_left.
Referenced by ev::DFA::BuildParseTree(), and ev::operator<<().
HaveRight()
bool ev::ParseNode::HaveRight () const inline
Indicates whether this node has a child on its right branch.
Returns
true if a child node exists on the right branch.
References m_right.
Referenced by ev::DFA::BuildParseTree(), and ev::operator<<().
IsChoice()
bool ev::ParseNode::IsChoice () const inline
Indicates whether the node is an OR'd choice node.
Returns
true if the node is an OR'd choice node.
References Choice, and m_type.
Referenced by ev::DFA::BuildParseTree(), Firstpos(), Lastpos(), and Nullable().
IsEnd()
bool ev::ParseNode::IsEnd () const inline
Indicates whether the node is a terminal node.
Returns
true if node is a terminal node.
References End, and m_type.
IsEpsilon()
bool ev::ParseNode::IsEpsilon () const inline
Indicates whether the node is an any input node.
Returns
true if the node is an any input node.
References Epsilon, and m_type.
Referenced by ev::DFA::BuildParseTree(), Firstpos(), Lastpos(), and Nullable().
IsName()
bool ev::ParseNode::IsName () const inline
Indicates whether the node contains an element name.
Returns
true if the node contains an element name.
References m_type, and Name.
IsOpt()
bool ev::ParseNode::IsOpt () const inline
Indicates whether the cardinality of the node is zero or one.
Returns
true if the cardinality of the node is zero or one.
References m_type, and Opt.
Referenced by Firstpos(), Lastpos(), and Nullable().
IsPlus()
bool ev::ParseNode::IsPlus () const inline
Indicates whether the cardinality of the node is one or more.
Returns
true if the cardinality of the node is one or more.
References m_type, and Plus.
Referenced by Firstpos(), Followpos(), and Lastpos().
IsRep()
bool ev::ParseNode::IsRep () const inline
Indicates whether the cardinality of the node is zero of more.
Returns
true if the cardinality of the node is zero or more.
References m_type, and Rep.
Referenced by Firstpos(), Followpos(), Lastpos(), and Nullable().
IsSeq()
bool ev::ParseNode::IsSeq () const inline
Indicates whether the node is a sequence node.
Returns
true if the node is a sequence node.
References m_type, and Seq.
Referenced by ev::DFA::BuildParseTree(), Firstpos(), Followpos(), Lastpos(), and Nullable().
SetSymbol() [1/2]
void ev::ParseNode::SetSymbol (const EVString & symbol) inline
Sets the input symbol for this parse node.
Parameters
symbol [in] Input symbol for the parse node.
References m_symbol.
SetSymbol() [2/2]
void ev::ParseNode::SetSymbol (const XML_Char * symbol) inline
Sets the input symbol for this parse node.
Parameters
symbol [in] Input symbol for the parse node.
References m_symbol.
Referenced by ev::DFA::BuildParseTree().
Union()
static void ev::ParseNode::Union (NodeSet & set1, const NodeSet & set2) inline static
Performs a set union on the two specified sets of nodes.
Parameters
set1 [in, out] First set of the union.
set2 [in] Second set of the union.
Referenced by ev::DFA::BuildComplexDFA(), Firstpos(), Followpos(), and Lastpos().
Friends And Related Function Documentation
operator<<
EVOstream & operator<< (EVOstream & stream, const ParseNode * node) friend
Output stream operator for a parse node.
Used to dump the state of the parse node to the specified output stream for debugging purposes.
Parameters
stream [in] Output stream.
node [in] Parse node to output.
Returns
Output stream.
The documentation for this class was generated from the following file:
exval.cpp
Copyright 2011 C Thing Software