Meazure: MeaRulerPrefs Class Reference
MeaRulerPrefs Class Reference
Property page for setting ruler preferences.
#include <RulerPrefs.h>
Public Types
enum { IDD = IDD_PREF_RULERS }
Public Member Functions
MeaRulerPrefs (const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Constructs an instance of the ruler property page.
~MeaRulerPrefs ()
Destroys an instance of the ruler property page.
virtual BOOL OnInitDialog ()
Called when the property page is created.
Public Attributes
int m_opacity
Opacity of the ruler where 0 is transparent and 255 is opaque.
COLORREF m_backColor
Ruler background color.
COLORREF m_borderColor
Color for the ruler border and tick marks.
Protected Member Functions
virtual void DoDataExchange (CDataExchange *pDX) override
Performs Dynamic Data Exchange (DDX) for the page.
afx_msg void OnChangeBkColor ()
Called when the background color button is pressed.
afx_msg void OnChangeBorderColor ()
Called when the border color button is pressed.
afx_msg void OnDefBkColor ()
Called when the default background color button is pressed.
afx_msg void OnDefBorderColor ()
Called when the default border color button is pressed.
afx_msg void OnHScroll (UINT nSBCode, UINT nPos, CScrollBar *pScrollBar)
Called when the ruler opacity slider is moved to change the ruler opacity.
Private Member Functions
void ColorsChanged ()
Sets the background and border color on the sample rulers and sets the modified flag.
Private Attributes
MeaRuler m_vRuler
Vertical sample ruler.
MeaRuler m_hRuler
Horizontal sample ruler.
Detailed Description
Property page for setting ruler preferences.
The ruler preferences include the ruler background and border colors and the ruler opacity (Windows 2000 and up). The property page provides a vertical and a horizontal ruler sample to preview the properties before they are applied.
Constructor & Destructor Documentation
MeaRulerPrefs()
MeaRulerPrefs::MeaRulerPrefs (const MeaScreenProvider & screenProvider, const MeaUnitsProvider & unitsProvider)
Constructs an instance of the ruler property page.
Parameters
screenProvider [in] Screen information provider
unitsProvider [in] Units information provider
Member Function Documentation
DoDataExchange()
void MeaRulerPrefs::DoDataExchange (CDataExchange * pDX) override protected virtual
Performs Dynamic Data Exchange (DDX) for the page.
Parameters
pDX [in] DDX object for exchanging data between the page UI and the member variables.
References m_opacity.
OnChangeBkColor()
void MeaRulerPrefs::OnChangeBkColor () protected
Called when the background color button is pressed.
This method displays the color picker dialog and calls the ColorsChanged() method if a new background color is chosen.
References ColorsChanged(), MeaColorDialog::DoModal(), and m_backColor.
OnChangeBorderColor()
void MeaRulerPrefs::OnChangeBorderColor () protected
Called when the border color button is pressed.
This method displays the color picker dialog and calls the ColorsChanged() method if a new border color is chosen.
References ColorsChanged(), MeaColorDialog::DoModal(), and m_borderColor.
OnDefBkColor()
void MeaRulerPrefs::OnDefBkColor () protected
Called when the default background color button is pressed.
This method restores the default background color.
References ColorsChanged(), MeaColors::GetDefault(), m_backColor, and MeaColors::RulerBack.
OnDefBorderColor()
void MeaRulerPrefs::OnDefBorderColor () protected
Called when the default border color button is pressed.
This method restores the default border color.
References ColorsChanged(), MeaColors::GetDefault(), m_borderColor, and MeaColors::RulerBorder.
OnInitDialog()
BOOL MeaRulerPrefs::OnInitDialog () virtual
Called when the property page is created.
This method Creates the sample rulers and initializes the opacity slider.
Returns
TRUE, indicating that the input focus should be set to the first control on the page.
References MeaRuler::Create(), HaveLayeredWindows(), MeaRuler::Horizontal, m_backColor, m_borderColor, m_hRuler, m_opacity, m_vRuler, MeaRuler::SetOpacity(), MeaRuler::SetPosition(), MeaGraphic::Show(), and MeaRuler::Vertical.
The documentation for this class was generated from the following files:
RulerPrefs.h
RulerPrefs.cpp
Copyright 2011 C Thing Software