Meazure: MeaPositionScreen Class Reference
MeaPositionScreen Class Reference
Represents a single monitor attached to the system.
#include <PositionScreen.h>
Public Member Functions
MeaPositionScreen ()
Constructs a screen object.
MeaPositionScreen (const MeaScreenProvider::ScreenIter &screenIter, const MeaUnitsProvider &unitsProvider, const MeaScreenProvider &screenProvider)
Constructs deep copy screen object from the specified iterator over the list of screens.
MeaPositionScreen (const MeaPositionScreen &screen)
Constructs a deep copy of the specified screen.
void Load (const MeaXMLNode *screenNode)
Loads screen elements of the log file.
void Save (MeaXMLWriter &writer) const
Saves the screen information.
MeaPositionScreen & operator= (const MeaPositionScreen &screen)
Assignment operator for a screen object.
bool operator== (const MeaPositionScreen &screen) const
Tests for equality between the specified screen object and this.
bool operator!= (const MeaPositionScreen &screen) const
Tests for inequality between the specified screen object and this.
bool IsPrimary () const
Indicates whether this screen is the primary display.
const MeaFRect & GetRect () const
Provides the screen rectangle expressed in the units that were in effect at the time the screen object was created.
const MeaFSize & GetRes () const
Provides the screen resolution expressed in the units that were in effect at the time the screen object was created.
bool IsManualRes () const
Indicates whether the resolution calibrated manually.
const CString & GetDesc () const
Description of the screen.
Private Member Functions
MeaPositionScreen & Copy (const MeaPositionScreen &screen)
Makes a deep copy of the specified screen object.
Private Attributes
bool m_primary
Is this the primary screen.
MeaFRect m_rect
Screen rectangle expressed in the units that were.
MeaFSize m_res
Screen resolution expressed in the units that were in effect at the time the screen object was created.
bool m_manualRes
Is the resolution calibrated manually.
CString m_desc
Description of the screen.
Detailed Description
Represents a single monitor attached to the system.
There is an instance of this class per monitor.
Constructor & Destructor Documentation
MeaPositionScreen() [1/2]
MeaPositionScreen::MeaPositionScreen (const MeaScreenProvider::ScreenIter & screenIter, const MeaUnitsProvider & unitsProvider, const MeaScreenProvider & screenProvider) explicit
Constructs deep copy screen object from the specified iterator over the list of screens.
Parameters
screenIter [in] Iterator from which to construct a copy of the screen.
unitsProvider [in] Units information and conversion provider
screenProvider [in] Screen information provider
References MeaFRect::bottom, MeaUnitsProvider::ConvertCoord(), MeaUnitsProvider::ConvertRes(), MeaScreenProvider::GetScreenName(), MeaScreenProvider::GetScreenRect(), MeaScreenProvider::GetScreenRes(), MeaScreenProvider::IsManualRes(), MeaScreenProvider::IsPrimary(), MeaFRect::left, m_desc, m_manualRes, m_primary, m_rect, m_res, MeaFRect::right, MeaFRect::top, MeaFPoint::x, and MeaFPoint::y.
MeaPositionScreen() [2/2]
MeaPositionScreen::MeaPositionScreen (const MeaPositionScreen & screen) inline
Constructs a deep copy of the specified screen.
Parameters
screen [in] Screen object to be copied.
References Copy().
Member Function Documentation
Copy()
MeaPositionScreen & MeaPositionScreen::Copy (const MeaPositionScreen & screen) inline private
Makes a deep copy of the specified screen object.
Parameters
screen [in] Screen object to copy.
Returns
Copy of the specified screen object.
References m_desc, m_manualRes, m_primary, m_rect, and m_res.
Referenced by MeaPositionScreen(), and operator=().
GetDesc()
const CString & MeaPositionScreen::GetDesc () const inline
Description of the screen.
Returns
Screen description.
References m_desc.
GetRect()
const MeaFRect & MeaPositionScreen::GetRect () const inline
Provides the screen rectangle expressed in the units that were in effect at the time the screen object was created.
Returns
Screen rectangle
References m_rect.
GetRes()
const MeaFSize & MeaPositionScreen::GetRes () const inline
Provides the screen resolution expressed in the units that were in effect at the time the screen object was created.
Returns
Screen resolution.
References m_res.
IsManualRes()
bool MeaPositionScreen::IsManualRes () const inline
Indicates whether the resolution calibrated manually.
Returns
true if the screen resolution has been manually calibrated.
References m_manualRes.
IsPrimary()
bool MeaPositionScreen::IsPrimary () const inline
Indicates whether this screen is the primary display.
Returns
true if this screen is the primary display.
References m_primary.
Load()
void MeaPositionScreen::Load (const MeaXMLNode * screenNode)
Loads screen elements of the log file.
Parameters
screenNode [in] screen node in the DOM.
References MeaXMLNode::AtEnd(), MeaFRect::bottom, MeaFSize::cx, MeaFSize::cy, MeaXMLNode::Element, MeaXMLNode::GetAttributes(), MeaXMLNode::GetChildIter(), MeaXMLNode::GetData(), MeaXMLNode::GetType(), MeaXMLAttributes::GetValueBool(), MeaXMLAttributes::GetValueDbl(), MeaXMLAttributes::GetValueStr(), MeaFRect::left, m_desc, m_manualRes, m_primary, m_rect, m_res, MeaFRect::right, and MeaFRect::top.
Referenced by MeaPositionDesktop::Load().
operator!=()
bool MeaPositionScreen::operator!= (const MeaPositionScreen & screen) const inline
Tests for inequality between the specified screen object and this.
Parameters
screen [in] Screen object to test against this.
Returns
true if the specified screen object and this are not equal.
operator=()
MeaPositionScreen & MeaPositionScreen::operator= (const MeaPositionScreen & screen) inline
Assignment operator for a screen object.
Makes a deep copy of the object.
Parameters
screen [in] Screen option to assign to this.
Returns
This screen object.
References Copy().
operator==()
bool MeaPositionScreen::operator== (const MeaPositionScreen & screen) const inline
Tests for equality between the specified screen object and this.
Parameters
screen [in] Screen object to test against this.
Returns
true if the specified screen object and this are equal.
References MeaFRect::bottom, MeaFSize::cx, MeaFSize::cy, MeaNumericUtils::IsEqualF(), MeaFRect::left, m_desc, m_manualRes, m_primary, m_rect, m_res, MeaFRect::right, and MeaFRect::top.
Save()
void MeaPositionScreen::Save (MeaXMLWriter & writer) const
Saves the screen information.
Parameters
writer [in] Provides ability to write a position to the log.
References MeaXMLWriter::AddAttribute(), MeaFRect::bottom, MeaFSize::cx, MeaFSize::cy, MeaXMLWriter::EndElement(), MeaFRect::left, m_desc, m_manualRes, m_primary, m_rect, m_res, MeaFRect::right, MeaXMLWriter::StartElement(), and MeaFRect::top.
Member Data Documentation
m_rect
MeaFRect MeaPositionScreen::m_rect private
Screen rectangle expressed in the units that were.
in effect at the time the screen object was created.
Referenced by Copy(), GetRect(), Load(), MeaPositionScreen(), operator==(), and Save().
The documentation for this class was generated from the following files:
PositionScreen.h
PositionScreen.cpp
Copyright 2011 C Thing Software