Meazure: ev::ContentModel Class Reference
ev::ContentModel Class Reference
Represents a node in an XML element content model.
Public Types
enum Category {
EmptyCat ,
AnyCat ,
MixedCat ,
PureChoiceCat ,
PureSeqCat ,
ComplexCat
}
Categorization of the content model.
enum Type {
EmptyType ,
AnyType ,
MixedType ,
NameType ,
ChoiceType ,
SeqType
}
Identifies a content model node.
enum Quantity {
NoneQuant ,
OptQuant ,
RepQuant ,
PlusQuant
}
Specifies the cardinality of a content model node.
typedef std::list< ContentModel * > Models
List of content models.
typedef Models::const_iterator Iter_c
Constant iterator over a list of content models.
typedef Models::iterator Iter
Iterator over a list of content models.
Public Member Functions
ContentModel (const XML_Content *model, bool root=true)
Constructs an exval content model based on the specified expat content model.
virtual ~ContentModel ()
Destroys a content model instance.
Category GetCategory () const
Returns the content model category.
EVString GetSignature () const
Returns the content model signature.
Type GetType () const
Returns the type of a content model node.
Quantity GetQuantity () const
Returns the cardinality of the content model node.
EVString GetName () const
Returns the element name in this content model node.
bool HasChildren () const
Indicates whether this content model node has child content model nodes.
int GetNumChildren () const
Returns the number of child content model nodes.
Iter_c GetChildIter () const
Returns an iterator over the list of child nodes.
Iter GetChildIter ()
Returns an iterator over the list of child nodes.
bool AtEnd (const Iter_c &iter) const
Indicates whether the specified iterator has hit the end of the child node list.
bool AtEnd (const Iter &iter)
Indicates whether the specified iterator has hit the end of the child node list.
ContentModel & GetChild (const Iter_c &iter) const
Returns the child content model node corresponding to the specified iterator.
ContentModel & GetChild (const Iter &iter) const
Returns the child content model node corresponding to the specified iterator.
bool IsEmpty () const
Indicates whether the content model node type is EMPTY.
bool IsAny () const
Indicates whether the content model node type is ANY.
bool IsMixed () const
Indicates whether the content model node type is mixed.
bool IsName () const
Indicates whether the content model node contains an element name.
bool IsChoice () const
Indicates whether the content model node is an OR'd choice.
bool IsSeq () const
Indicates whether the content model node is a sequence.
bool IsNone () const
Indicates whether the content model node has no cardinality associated with it.
bool IsOpt () const
Indicates whether the content model node has a cardinality of zero or one.
bool IsRep () const
Indicates whether the content model node has a cardinality of zero or more.
bool IsPlus () const
Indicates whether the content model node has a cardinality of one or more.
Protected Member Functions
ContentModel (const ContentModel &model)
Purposely undefined.
ContentModel & operator= (const ContentModel &model)
Purposely undefined.
void Optimize ()
Attempts to optimize the content model by removing extraneous levels of parenthesis, etc.
void Collapse (ContentModel *model)
Attempts to remove unnecessary parenthesis levels.
EVString MakeSignature () const
Constructs the signature string for the content model.
Category Categorize () const
Examines the content model to determine whether a DFA can be constructed directly or whether the DFA construction algorithm must be run.
bool HasPureChildren () const
Determines whether the children of the this content model node are simple name name nodes with no cardinality.
Protected Attributes
bool m_root
Indicates whether this node is the root of the content model tree.
Category m_category
Category for this content model node.
EVString m_signature
Signature string for the content model.
Type m_type
Type of this content model node.
Quantity m_quantity
Cardinality of this content model node.
EVString m_name
Element name if this is a name type node.
Models m_children
List of child content model nodes.
Friends
EVOstream & operator<< (EVOstream &stream, const ContentModel &contentModel)
Output stream operator for a content model.
Detailed Description
Represents a node in an XML element content model.
The content model is represented as a tree of ContentModel objects.
Member Enumeration Documentation
Category
enum ev::ContentModel::Category
Categorization of the content model.
The category is used to optimize the DFA creation process for the content model.
Enumerator
EmptyCat
Element cannot contain any elements or data.
AnyCat
The element can contain any element.
MixedCat
The element can contain PCDATA.
PureChoiceCat
The content model consists solely of OR'd elements.
PureSeqCat
The content model consists solely of a sequence of elements.
ComplexCat
The content model is none of the above.
Quantity
enum ev::ContentModel::Quantity
Specifies the cardinality of a content model node.
Enumerator
NoneQuant
No quantity specified.
OptQuant
Zero or one.
RepQuant
Zero or more.
PlusQuant
One or more.
Type
enum ev::ContentModel::Type
Identifies a content model node.
Enumerator
EmptyType
Element cannot contain any elements or data.
AnyType
Element can contain any element.
MixedType
Element can contain PCDATA.
NameType
Content model node is an element name.
ChoiceType
Content model is an OR'd choice node.
SeqType
Content model is a sequence node.
Constructor & Destructor Documentation
ContentModel()
ContentModel::ContentModel (const XML_Content * model, bool root = true) explicit
Constructs an exval content model based on the specified expat content model.
Parameters
model [in] Element content model constructed by the expat parser.
root [in] true if the root node of the content model tree is being constructed.
References AnyType, Categorize(), ChoiceType, ComplexCat, ContentModel(), EmptyType, m_category, m_children, m_name, m_quantity, m_root, m_signature, m_type, MakeSignature(), MeaAssert, MixedType, NameType, NoneQuant, Optimize(), OptQuant, PlusQuant, RepQuant, and SeqType.
Referenced by ContentModel().
Member Function Documentation
AtEnd() [1/2]
bool ev::ContentModel::AtEnd (const Iter & iter) inline
Indicates whether the specified iterator has hit the end of the child node list.
Parameters
iter [in] Iterator over the list of child nodes.
Returns
true if the end of the child list has been reached.
References m_children.
AtEnd() [2/2]
bool ev::ContentModel::AtEnd (const Iter_c & iter) const inline
Indicates whether the specified iterator has hit the end of the child node list.
Parameters
iter [in] Constant iterator over the list of child nodes.
Returns
true if the end of the child list has been reached.
References m_children.
Referenced by ev::DFA::BuildChoiceDFA(), ev::DFA::BuildMixedDFA(), ev::DFA::BuildParseTree(), ev::DFA::BuildSeqDFA(), Collapse(), HasPureChildren(), MakeSignature(), ev::operator<<(), and ~ContentModel().
Categorize()
ContentModel::Category ContentModel::Categorize () const protected
Examines the content model to determine whether a DFA can be constructed directly or whether the DFA construction algorithm must be run.
For example, the DFA for the content model (a|b|c) can be constructed directly, whereas a more complex DFA is required for the content model ((a|b)*,a,b,b,c*).
Returns
Content model category.
References AnyCat, ComplexCat, EmptyCat, HasPureChildren(), IsAny(), IsChoice(), IsEmpty(), IsMixed(), MixedCat, PureChoiceCat, and PureSeqCat.
Referenced by ContentModel().
Collapse()
void ContentModel::Collapse (ContentModel * model) protected
Attempts to remove unnecessary parenthesis levels.
Parameters
model [in] Content model to examine.
References AtEnd(), Collapse(), GetChildIter(), IsChoice(), IsNone(), IsRep(), IsSeq(), m_children, m_name, m_quantity, and m_type.
Referenced by Collapse(), and Optimize().
GetCategory()
Category ev::ContentModel::GetCategory () const inline
Returns the content model category.
The category is used in the DFA construction process to optimize the DFA.
Returns
Content model category.
References m_category.
Referenced by ev::DFA::DFA().
GetChild() [1/2]
ContentModel & ev::ContentModel::GetChild (const Iter & iter) const inline
Returns the child content model node corresponding to the specified iterator.
Parameters
iter [in] Iterator over the list of child nodes.
Returns
Content model node.
GetChild() [2/2]
ContentModel & ev::ContentModel::GetChild (const Iter_c & iter) const inline
Returns the child content model node corresponding to the specified iterator.
Parameters
iter [in] Constant iterator over the list of child nodes.
Returns
Content model node.
Referenced by ev::DFA::BuildChoiceDFA(), ev::DFA::BuildMixedDFA(), ev::DFA::BuildParseTree(), ev::DFA::BuildSeqDFA(), HasPureChildren(), MakeSignature(), and ev::operator<<().
GetChildIter() [1/2]
Iter ev::ContentModel::GetChildIter () inline
Returns an iterator over the list of child nodes.
Returns
Iterator over the list of child nodes.
References m_children.
GetChildIter() [2/2]
Iter_c ev::ContentModel::GetChildIter () const inline
Returns an iterator over the list of child nodes.
Returns
Constant iterator over the list of child nodes.
References m_children.
Referenced by ev::DFA::BuildChoiceDFA(), ev::DFA::BuildMixedDFA(), ev::DFA::BuildParseTree(), ev::DFA::BuildSeqDFA(), Collapse(), HasPureChildren(), MakeSignature(), ev::operator<<(), and ~ContentModel().
GetName()
EVString ev::ContentModel::GetName () const inline
Returns the element name in this content model node.
Returns
Element name in content model node.
References m_name.
Referenced by ev::DFA::BuildChoiceDFA(), ev::DFA::BuildMixedDFA(), ev::DFA::BuildParseTree(), and ev::DFA::BuildSeqDFA().
GetNumChildren()
int ev::ContentModel::GetNumChildren () const inline
Returns the number of child content model nodes.
Returns
Number of child nodes.
References m_children.
Referenced by ev::DFA::BuildSeqDFA().
GetQuantity()
Quantity ev::ContentModel::GetQuantity () const inline
Returns the cardinality of the content model node.
Returns
Content model node cardinality.
References m_quantity.
Referenced by ev::DFA::BuildParseTree().
GetSignature()
EVString ev::ContentModel::GetSignature () const inline
Returns the content model signature.
The signature is string that uniquely identifies a content model. Two identical content models will have the same signature. The signature is used to quickly determine whether two content models are identical so that DFAs are not constructed needlessly.
Returns
The string signature for the content model.
References m_signature.
Referenced by ev::Validator::AddElementDecl().
GetType()
Type ev::ContentModel::GetType () const inline
Returns the type of a content model node.
Returns
Type of the content model node.
References m_type.
Referenced by ev::DFA::BuildParseTree().
HasChildren()
bool ev::ContentModel::HasChildren () const inline
Indicates whether this content model node has child content model nodes.
Returns
true if the content model node has child node.
References m_children.
HasPureChildren()
bool ev::ContentModel::HasPureChildren () const inline protected
Determines whether the children of the this content model node are simple name name nodes with no cardinality.
Returns
true if the children are simple name nodes with no cardinality.
References AtEnd(), GetChild(), GetChildIter(), m_quantity, m_type, NameType, and NoneQuant.
Referenced by Categorize().
IsAny()
bool ev::ContentModel::IsAny () const inline
Indicates whether the content model node type is ANY.
Returns
true if the type is ANY.
References AnyType, and m_type.
Referenced by Categorize().
IsChoice()
bool ev::ContentModel::IsChoice () const inline
Indicates whether the content model node is an OR'd choice.
Returns
true if the node is an OR'd choice.
References ChoiceType, and m_type.
Referenced by Categorize(), Collapse(), and Optimize().
IsEmpty()
bool ev::ContentModel::IsEmpty () const inline
Indicates whether the content model node type is EMPTY.
Returns
true if the type is EMPTY.
References EmptyType, and m_type.
Referenced by Categorize().
IsMixed()
bool ev::ContentModel::IsMixed () const inline
Indicates whether the content model node type is mixed.
Returns
true if the type is mixed.
References m_type, and MixedType.
Referenced by ev::Validator::AddElementDecl(), and Categorize().
IsName()
bool ev::ContentModel::IsName () const inline
Indicates whether the content model node contains an element name.
Returns
true if the node contains an element name.
References m_type, and NameType.
IsNone()
bool ev::ContentModel::IsNone () const inline
Indicates whether the content model node has no cardinality associated with it.
Returns
true if the node has no cardinality.
References m_quantity, and NoneQuant.
Referenced by Collapse(), and Optimize().
IsOpt()
bool ev::ContentModel::IsOpt () const inline
Indicates whether the content model node has a cardinality of zero or one.
Returns
true if the node has a cardinality of zero or one.
References m_quantity, and OptQuant.
Referenced by ev::DFA::BuildChoiceDFA(), and ev::DFA::BuildSeqDFA().
IsPlus()
bool ev::ContentModel::IsPlus () const inline
Indicates whether the content model node has a cardinality of one or more.
Returns
true if the node has a cardinality of one or more.
References m_quantity, and PlusQuant.
Referenced by ev::DFA::BuildChoiceDFA(), and ev::DFA::BuildSeqDFA().
IsRep()
bool ev::ContentModel::IsRep () const inline
Indicates whether the content model node has a cardinality of zero or more.
Returns
true if the node has a cardinality of zero or more.
References m_quantity, and RepQuant.
Referenced by ev::DFA::BuildChoiceDFA(), ev::DFA::BuildSeqDFA(), and Collapse().
IsSeq()
bool ev::ContentModel::IsSeq () const inline
Indicates whether the content model node is a sequence.
Returns
true if the node is a sequence.
References m_type, and SeqType.
Referenced by Collapse(), and Optimize().
MakeSignature()
EVString ContentModel::MakeSignature () const protected
Constructs the signature string for the content model.
The signature string uniquely identifies the content model. Identical content models will have identical signature strings.
Returns
Signature string representing the content model.
References AnyType, AtEnd(), ChoiceType, EmptyType, EV_T, GetChild(), GetChildIter(), m_name, m_quantity, m_type, MakeSignature(), MeaAssert, MixedType, NameType, NoneQuant, OptQuant, PlusQuant, RepQuant, and SeqType.
Referenced by ContentModel(), and MakeSignature().
Friends And Related Function Documentation
operator<<
EVOstream & operator<< (EVOstream & stream, const ContentModel & contentModel) friend
Output stream operator for a content model.
Used to dump the state of the content model to the specified output stream for debugging purposes.
Parameters
stream [in] Output stream.
contentModel [in] Content model to output.
Returns
Output stream.
The documentation for this class was generated from the following file:
exval.cpp
Copyright 2011 C Thing Software