Meazure: MeaGUID Class Reference
MeaGUID Class Reference
Represents a globally unique identifier (GUID) and common operations on a GUID.
#include <GUID.h>
Classes
struct less
Used by the STL to perform ordering of MeaGUID objects in collections.
Public Member Functions
MeaGUID ()
Constructs a GUID with a newly generated GUID using CoCreateGuid.
MeaGUID (const GUID &guid)
Constructs a GUID based on the specified GUID structure.
MeaGUID (LPCTSTR guidStr)
Creates a GUID object initialized with by the string representing a GUID (e.g.
MeaGUID (const MeaGUID &guid)
Copy constructor.
~MeaGUID ()
Destroys a GUID object.
MeaGUID & operator= (const GUID &guid)
Assignment operator.
MeaGUID & operator= (const LPCTSTR guidStr)
Assignment operator.
MeaGUID & operator= (const MeaGUID &guid)
Assignment operator.
bool operator== (const MeaGUID &guid) const
Tests for equality between two MeaGUID objects.
bool operator!= (const MeaGUID &guid) const
Tests for inequality between two MeaGUID objects.
bool operator== (const GUID &guid) const
Tests for equality between two this object and a GUID structure.
bool operator!= (const GUID &guid) const
Tests for inequality between two this object and a GUID structure.
operator GUID () const
Casts to an operating system defined GUID structure.
operator LPCTSTR () const
Casts to a string.
MeaGUID & Assign (const GUID &guid)
Assign the specified GUID structure to this.
MeaGUID & Assign (LPCTSTR guidStr)
Assign the specified GUID string to this.
MeaGUID & Assign (const MeaGUID &guid)
Assign the specified MeaGUID object to this.
bool IsEqual (const MeaGUID &guid) const
Tests the specified MeaGUID object for equality with this.
bool IsEqual (const GUID &guid) const
Tests the specified GUID structure for equality with this.
CString ToString () const
Returns a string representation of the GUID.
Private Attributes
GUID m_guid
Underlying GUID for the object.
CString m_buffer
Buffer holding the string representation of the GUID.
Detailed Description
Represents a globally unique identifier (GUID) and common operations on a GUID.
Constructor & Destructor Documentation
MeaGUID() [1/3]
MeaGUID::MeaGUID (const GUID & guid) inline explicit
Constructs a GUID based on the specified GUID structure.
Parameters
guid [in] Operating system defined GUID structure.
References Assign().
MeaGUID() [2/3]
MeaGUID::MeaGUID (LPCTSTR guidStr) inline explicit
Creates a GUID object initialized with by the string representing a GUID (e.g.
"00000000-0000-0000-0000-000000000000")
Parameters
guidStr [in] String representing a GUID.
References Assign().
MeaGUID() [3/3]
MeaGUID::MeaGUID (const MeaGUID & guid) inline
Copy constructor.
Parameters
guid [in] MeaGUID object ot be copied.
References Assign().
Member Function Documentation
Assign() [1/3]
MeaGUID & MeaGUID::Assign (const GUID & guid) inline
Assign the specified GUID structure to this.
Parameters
guid [in] Operating system defined GUID structure.
Returns
This object.
References m_guid.
Referenced by Assign(), MeaGUID(), and operator=().
Assign() [2/3]
MeaGUID & MeaGUID::Assign (const MeaGUID & guid) inline
Assign the specified MeaGUID object to this.
Parameters
guid [in] MeaGUID object to assing.
Returns
This object.
References Assign(), and m_guid.
Assign() [3/3]
MeaGUID & MeaGUID::Assign (LPCTSTR guidStr)
Assign the specified GUID string to this.
Parameters
guidStr [in] String representing a GUID.
Returns
This object.
References m_guid.
IsEqual() [1/2]
bool MeaGUID::IsEqual (const GUID & guid) const inline
Tests the specified GUID structure for equality with this.
Parameters
guid [in] Opeating system defined GUID structure.
Returns
true if the specified GUID structure equals this object.
References m_guid.
IsEqual() [2/2]
bool MeaGUID::IsEqual (const MeaGUID & guid) const inline
Tests the specified MeaGUID object for equality with this.
Parameters
guid [in] MeaGUID object to test.
Returns
true if the specified GUID object equals this object.
References IsEqual(), and m_guid.
Referenced by IsEqual(), operator!=(), and operator==().
operator GUID()
MeaGUID::operator GUID () const inline
Casts to an operating system defined GUID structure.
Returns
Operating system defined GUID structure.
References m_guid.
operator LPCTSTR()
MeaGUID::operator LPCTSTR () const inline
Casts to a string.
Returns
String representation of the GUID.
References ToString().
operator!=() [1/2]
bool MeaGUID::operator!= (const GUID & guid) const inline
Tests for inequality between two this object and a GUID structure.
Parameters
guid [in] Operating system defined GUID structure to test against this object.
Returns
true if the specified GUID does not equal this object.
References IsEqual().
operator!=() [2/2]
bool MeaGUID::operator!= (const MeaGUID & guid) const inline
Tests for inequality between two MeaGUID objects.
Parameters
guid [in] MeaGUID object to test against this object.
Returns
true if the specified object does not equal this object.
References IsEqual().
operator=() [1/3]
MeaGUID & MeaGUID::operator= (const GUID & guid) inline
Assignment operator.
Parameters
guid [in] Operating system defined GUID structure.
Returns
This object.
References Assign().
operator=() [2/3]
MeaGUID & MeaGUID::operator= (const LPCTSTR guidStr) inline
Assignment operator.
Parameters
guidStr [in] String representing a GUID.
Returns
This object.
References Assign().
operator=() [3/3]
MeaGUID & MeaGUID::operator= (const MeaGUID & guid) inline
Assignment operator.
Parameters
guid [in] MeaGUID object.
Returns
This object.
References Assign().
operator==() [1/2]
bool MeaGUID::operator== (const GUID & guid) const inline
Tests for equality between two this object and a GUID structure.
Parameters
guid [in] Operating system defined GUID structure to test against this object.
Returns
true if the specified GUID equals this object.
References IsEqual().
operator==() [2/2]
bool MeaGUID::operator== (const MeaGUID & guid) const inline
Tests for equality between two MeaGUID objects.
Parameters
guid [in] MeaGUID object to test against this object.
Returns
true if the specified object equals this object.
References IsEqual().
ToString()
CString MeaGUID::ToString () const
Returns a string representation of the GUID.
Note that the string returned is not preserved across calls to this method. Copy the returned string to preserve it.
Returns
String representation of the GUID.
References m_buffer, and m_guid.
Referenced by operator LPCTSTR(), and MeaGUID::less::operator()().
The documentation for this class was generated from the following files:
GUID.h
GUID.cpp
Copyright 2011 C Thing Software