Meazure: MeaToolMgr Class Reference
MeaToolMgr Class Reference
Manages the measurement tools including selection, enabling, disabling, and communicating various messages to the tools.
#include <ToolMgr.h>
Public Member Functions
void SaveProfile (MeaProfile &profile)
Persists the state of the manager to the specified profile object.
void LoadProfile (MeaProfile &profile)
Restores the state of the manager from the specified profile object.
void MasterReset ()
Resets the screen manager to its default state.
void SetDataDisplay (MeaDataDisplay *dataDisplay)
Sets the measurement data display object for use by each measurement tool.
void SetRadioTool (const CString &toolName)
Makes the specified radio tool the current measurement tool.
void DisableRadioTools ()
Disables all radio tools.
MeaTool * FindTool (const CString &toolName) const
Returns the measurement tool corresponding to the specified tool name.
LPCTSTR GetToolName () const
Returns the name of the currently set radio tool.
UINT GetLabelId () const
Returns the ID of the currently set radio tool.
bool IsToolEnabled (const CString &toolName) const
Indicates if the specified tool is enabled.
void EnableTool (const CString &toolName) const
Enables the specified tool.
void DisableTool (const CString &toolName) const
Disables the specified tool.
void EnableRadioTool () const
Enables the currently selected radio tool.
void DisableRadioTool () const
Disables the currently selected radio tool.
void ChangeRadioToolEnable ()
Disables all radio tools and enables the currently selected radio tool.
void ToggleEnableTool (const CString &toolName) const
If the specified tool is enabled, this method disables it, and vice versa.
void UpdateTools (MeaUpdateReason reason=NormalUpdate) const
Tells all tools to update their visual display.
void ColorsChanged () const
Informs all tools that the color style sheet has changed.
bool HasCrosshairs () const
Indicates if the currently selected radio tool uses crosshairs.
bool CrosshairsEnabled () const
Indicates whether the display of crosshairs is enabled.
void EnableCrosshairs ()
Enables the display of crosshairs.
void DisableCrosshairs ()
Disables the display of crosshairs.
void FlashTool () const
Causes the current radio tool to flash.
void StrobeTool () const
Causes the current radio tool to strobe.
void OnMouseHook (WPARAM wParam, LPARAM lParam)
Called by the OS when the mouse pointer is moved.
void SetPosition (MeaFields which, int pixels)
Sets the position of the current radio tool.
void SetPosition (const MeaRadioTool::PointMap &points)
Sets the position of the current radio tool.
void SetPositionToCursor (MeaFields xfield, MeaFields yfield)
Sets the specified position based on the current location of the cursor.
const POINT & GetPosition () const
Returns a representative position from the current radio tool.
void GetPosition (MeaPositionLogMgr::Position &position) const
Returns the current radio tool's position as a position object.
void IncPosition (MeaFields which)
Increments the specified position field.
void DecPosition (MeaFields which)
Decrements the specified position field.
bool HasRegion () const
Indicates if the current radio tool has a rectangular region that can be captured.
RECT GetRegion () const
Obtains the current radio tools rectangular region.
void SetStatus (UINT id) const
Sets the text in the status bar using the specified string resource ID.
void EnableRegionFields (UINT enableFields, UINT editableFields)
Supervises enabling the appropriate fields in the measurement region portion of the UI.
void EnableScreenFields (UINT enableFields, UINT editableFields)
Supervises enabling the appropriate fields in the screen information portion of the UI.
void UpdateScreenInfo (const POINT &pos)
Updates the display of the screen size and resolution based on the screen containing the specified point.
void ShowXY1 (const POINT &point, const FPOINT &cpoint)
Displays the specified point in the X1/Y1 fields of the data display and on the rulers, if they are visible.
void ShowXY2 (const POINT &point, const FPOINT &cpoint)
Displays the specified point in the X2/Y2 fields of the data display and on the rulers, if they are visible.
void ShowXYV (const POINT &point, const FPOINT &cpoint)
Displays the specified point in the XV/YV fields of the data display and on the rulers, if they are visible.
void ShowWH (const FSIZE &size)
Displays the specified size in the width and height fields of the data display.
void ShowDistance (const FSIZE &size)
Displays a distance calculated from the specified size in the distance field of the data display.
void ShowDistance (double dist)
Displays the specified value in the distance field of the data display.
void ShowAngle (double angle)
Displays the specified angle in the angle field of the data display.
void ShowAspect (const FSIZE &size)
Displays the aspect ratio of the specified size in the aspect ratio field of the data display.
void ShowRectArea (const FSIZE &size)
Displays the rectangular area calculated from the specified width and height in the area field of the data display.
void ShowCircleArea (double radius)
Displays the area of a circle with the specified radius in the area field of the data display.
void ShowScreenName (const CString &name)
Displays the name of the current screen.
void ShowScreenWH (const FSIZE &size)
Displays the specified width and height in the appropriate screen fields.
void ShowScreenRes (const FSIZE &res)
Displays the specified resolution in the appropriate screen fields.
void ShowCalButton (bool show)
Displays or hides the screen calibration button.
Public Member Functions inherited from MeaSingleton_T< MeaToolMgr >
virtual ~MeaSingleton_T ()
Destructor for the Singleton.
Static Public Attributes
static const bool kDefCrosshairsEnabled = true
Crosshairs are enabled by default.
Private Types
typedef std::map< CString, MeaTool * > ToolsMap
Maps a tool name to the tool object.
Private Member Functions
MeaToolMgr (const MeaToolMgr &)
Managers are singletons.
MeaToolMgr & operator= (const MeaToolMgr &)
Purposely undefined.
Private Attributes
MeaDataDisplay * m_dataDisplay
Data display object.
bool m_crosshairsEnabled
Are crosshairs enabled.
ToolsMap m_tools
All measurement tools.
MeaRadioTool * m_currentRadioTool
Currently selected radio tool.
MeaScreenTool * m_screenTool
Screen information tool.
MeaCursorTool * m_cursorTool
Cursor position tool.
MeaPointTool * m_pointTool
Point position tool.
MeaLineTool * m_lineTool
Line measurement tool.
MeaRectTool * m_rectTool
Rectangle tool.
MeaCircleTool * m_circleTool
Circle measurement tool.
MeaAngleTool * m_angleTool
Angle measurement tool.
MeaWindowTool * m_windowTool
Window hierarchy measurement tool.
MeaRulerTool * m_rulerTool
Screen rulers.
MeaGridTool * m_gridTool
Screen grid.
MeaOriginTool * m_originTool
Origin marker.
Friends
class MeaSingleton_T< MeaToolMgr >
Additional Inherited Members
Static Public Member Functions inherited from MeaSingleton_T< MeaToolMgr >
static MeaToolMgr & Instance ()
The first time this method is called, a instance of the Singleton object is created and returned.
static void DestroyInstance ()
When the Singleton object is no longer needed, it must be destroyed using this method.
static bool IsDestroyed ()
Indicates whether the Singleton object has been destroyed.
Protected Member Functions inherited from MeaSingleton_T< MeaToolMgr >
MeaSingleton_T ()
Constructs a Singleton object instance.
Detailed Description
Manages the measurement tools including selection, enabling, disabling, and communicating various messages to the tools.
The term "radio tool" refers to those measurement tools that are mutually exclusive (i.e. only one radio tool can be used at a time).
Constructor & Destructor Documentation
MeaToolMgr()
MeaToolMgr::MeaToolMgr (const MeaToolMgr &) private
Managers are singletons.
Purposely undefined.
Member Function Documentation
CrosshairsEnabled()
bool MeaToolMgr::CrosshairsEnabled () const inline
Indicates whether the display of crosshairs is enabled.
Returns
true if the display of crosshairs is enabled.
References m_crosshairsEnabled.
Referenced by MeaAngleTool::EnableCrosshairs(), MeaCircleTool::EnableCrosshairs(), MeaLineTool::EnableCrosshairs(), MeaPointTool::EnableCrosshairs(), MeaRectTool::EnableCrosshairs(), CChildView::OnHideCrosshairs(), CChildView::OnUpdateFindCrosshair(), and CChildView::OnUpdateHideCrosshairs().
DecPosition()
void MeaToolMgr::DecPosition (MeaFields which) inline
Decrements the specified position field.
Parameters
which Position field to decrement
References MeaTool::DecPosition(), and m_currentRadioTool.
DisableRadioTools()
void MeaToolMgr::DisableRadioTools () inline
Disables all radio tools.
Among other things, disabling a tool hides it.
References MeaDataDisplay::ClearRegionData(), MeaTool::Disable(), MeaTool::IsEnabled(), MeaTool::IsRadioTool(), m_dataDisplay, and m_tools.
Referenced by ChangeRadioToolEnable(), CChildView::LoadProfile(), CChildView::MasterReset(), and CChildView::OnDestroy().
DisableTool()
void MeaToolMgr::DisableTool (const CString & toolName) const inline
Disables the specified tool.
Parameters
toolName [in] Name of tool to disable.
References MeaTool::Disable(), and FindTool().
Referenced by CChildView::ApplyPreferences(), and CChildView::OnScreenGridSpacing().
EnableRegionFields()
void MeaToolMgr::EnableRegionFields (UINT enableFields, UINT editableFields)
Supervises enabling the appropriate fields in the measurement region portion of the UI.
Parameters
enableFields [in] Bitmask indicating which fields on the UI should be enabled.
editableFields [in] Bitmask indicating which fields on the UI should be editable.
References MeaDataDisplay::EnableRegionFields(), MeaRuler::Ind2, MeaRuler::Ind3, MeaSingleton_T< MeaScreenMgr >::Instance(), m_dataDisplay, m_rulerTool, MeaX2Field, MeaXVField, and MeaRulerTool::SetIndicator().
Referenced by MeaAngleTool::Enable(), MeaCircleTool::Enable(), MeaCursorTool::Enable(), MeaLineTool::Enable(), MeaPointTool::Enable(), MeaRectTool::Enable(), and MeaWindowTool::Enable().
EnableScreenFields()
void MeaToolMgr::EnableScreenFields (UINT enableFields, UINT editableFields)
Supervises enabling the appropriate fields in the screen information portion of the UI.
Parameters
enableFields [in] Bitmask indicating which fields on the UI should be enabled.
editableFields [in] Bitmask indicating which fields on the UI should be editable.
References MeaDataDisplay::EnableScreenFields(), and m_dataDisplay.
Referenced by MeaScreenTool::Enable().
EnableTool()
void MeaToolMgr::EnableTool (const CString & toolName) const inline
Enables the specified tool.
Parameters
toolName [in] Name of tool to enable.
References MeaTool::Enable(), and FindTool().
Referenced by CChildView::ApplyPreferences(), CChildView::OnCreate(), and CChildView::OnScreenGridSpacing().
FindTool()
MeaTool * MeaToolMgr::FindTool (const CString & toolName) const inline
Returns the measurement tool corresponding to the specified tool name.
Parameters
toolName [in] Name of the measurement tool.
Returns
Measurement tool with the specified name.
References m_tools, and MeaAssert.
Referenced by DisableTool(), EnableTool(), IsToolEnabled(), CChildView::OnScreenGridSpacing(), SetRadioTool(), and ToggleEnableTool().
FlashTool()
void MeaToolMgr::FlashTool () const inline
Causes the current radio tool to flash.
Typically flashing a tool causes its crosshairs to cycle a number of times between their normal visual state and a hilited state.
References MeaRadioTool::Flash(), and m_currentRadioTool.
Referenced by CChildView::OnFindCrosshair().
GetLabelId()
UINT MeaToolMgr::GetLabelId () const inline
Returns the ID of the currently set radio tool.
Returns
ID of the currently set radio tool.
References MeaRadioTool::GetLabelId(), and m_currentRadioTool.
Referenced by ChangeRadioToolEnable().
GetPosition() [1/2]
const POINT & MeaToolMgr::GetPosition () const inline
Returns a representative position from the current radio tool.
Returns
The current radio tool returns a point that represents its current position.
References GetPosition(), and m_currentRadioTool.
Referenced by GetPosition(), CChildView::OnGetPosition(), and MeaPositionLogMgr::Position::Position().
GetPosition() [2/2]
void MeaToolMgr::GetPosition (MeaPositionLogMgr::Position & position) const inline
Returns the current radio tool's position as a position object.
The position object contains the complete set of points that describe the location of the tool.
Parameters
position [out] Position representing the location of the current radio tool.
References MeaRadioTool::GetPosition(), and m_currentRadioTool.
GetRegion()
RECT MeaToolMgr::GetRegion () const inline
Obtains the current radio tools rectangular region.
Returns
The current radio tools rectangular region.
References MeaRadioTool::GetRegion(), and m_currentRadioTool.
GetToolName()
LPCTSTR MeaToolMgr::GetToolName () const inline
Returns the name of the currently set radio tool.
Returns
Name of the currently set radio tool.
References MeaTool::GetToolName(), and m_currentRadioTool.
Referenced by MeaPositionLogMgr::Position::Show().
HasCrosshairs()
bool MeaToolMgr::HasCrosshairs () const inline
Indicates if the currently selected radio tool uses crosshairs.
Returns
true if the currently selected radio tool uses crosshairs.
References MeaRadioTool::HasCrosshairs(), and m_currentRadioTool.
Referenced by CChildView::OnUpdateFindCrosshair(), and CChildView::OnUpdateHideCrosshairs().
HasRegion()
bool MeaToolMgr::HasRegion () const inline
Indicates if the current radio tool has a rectangular region that can be captured.
Returns
true if the current radio tool has a rectangular region that can be captured.
References MeaRadioTool::HasRegion(), and m_currentRadioTool.
Referenced by CChildView::OnCopyRegion().
IncPosition()
void MeaToolMgr::IncPosition (MeaFields which) inline
Increments the specified position field.
Parameters
which Position field to increment
References MeaTool::IncPosition(), and m_currentRadioTool.
IsToolEnabled()
bool MeaToolMgr::IsToolEnabled (const CString & toolName) const inline
Indicates if the specified tool is enabled.
Returns
true if the specified tool is enabled.
References FindTool(), and MeaTool::IsEnabled().
Referenced by CChildView::OnPreferences(), and CChildView::OnScreenGridSpacing().
LoadProfile()
void MeaToolMgr::LoadProfile (MeaProfile & profile)
Restores the state of the manager from the specified profile object.
Parameters
profile [in] Profile object from which the state is to be restored.
References MeaTool::GetToolName(), MeaTool::IsRadioTool(), m_crosshairsEnabled, m_currentRadioTool, m_tools, MeaAssert, MeaProfile::ReadBool(), MeaProfile::ReadStr(), and MeaProfile::UserInitiated().
Referenced by CChildView::LoadProfile().
OnMouseHook()
void MeaToolMgr::OnMouseHook (WPARAM wParam, LPARAM lParam) inline
Called by the OS when the mouse pointer is moved.
Parameters
wParam [in] OS Message ID
lParam [in] MOUSEHOOKSTRUCT
References m_currentRadioTool, and MeaRadioTool::OnMouseHook().
Referenced by CChildView::OnMouseHook().
SaveProfile()
void MeaToolMgr::SaveProfile (MeaProfile & profile)
Persists the state of the manager to the specified profile object.
Parameters
profile [in] Profile object into which the state is to be persisted.
References MeaTool::GetToolName(), m_crosshairsEnabled, m_currentRadioTool, m_tools, MeaProfile::UserInitiated(), MeaProfile::WriteBool(), and MeaProfile::WriteStr().
Referenced by CChildView::SaveProfile().
SetDataDisplay()
void MeaToolMgr::SetDataDisplay (MeaDataDisplay * dataDisplay) inline
Sets the measurement data display object for use by each measurement tool.
Parameters
dataDisplay [in] Display object
References m_dataDisplay.
Referenced by CChildView::CChildView(), and CChildView::~CChildView().
SetPosition() [1/2]
void MeaToolMgr::SetPosition (const MeaRadioTool::PointMap & points) inline
Sets the position of the current radio tool.
Parameters
points [in] Complete set of points for the tool.
References m_currentRadioTool, and MeaRadioTool::SetPosition().
SetPosition() [2/2]
void MeaToolMgr::SetPosition (MeaFields which, int pixels) inline
Sets the position of the current radio tool.
The position of a specific part of the tool is set.
Parameters
which [in] Specifies the component of the tools position to set.
pixels [in] Position value for the component.
References m_currentRadioTool, and SetPosition().
Referenced by CChildView::OnDataChange(), SetPosition(), SetPositionToCursor(), and MeaPositionLogMgr::Position::Show().
SetPositionToCursor()
void MeaToolMgr::SetPositionToCursor (MeaFields xfield, MeaFields yfield)
Sets the specified position based on the current location of the cursor.
Parameters
xfield [in] X position to set
yfield [in] Y position to set
References SetPosition().
SetRadioTool()
void MeaToolMgr::SetRadioTool (const CString & toolName) inline
Makes the specified radio tool the current measurement tool.
Parameters
toolName [in] Name of the radio tool to set.
References ChangeRadioToolEnable(), FindTool(), MeaTool::IsRadioTool(), m_currentRadioTool, and MeaAssert.
Referenced by CChildView::OnRadioTool(), and MeaPositionLogMgr::Position::Show().
SetStatus()
void MeaToolMgr::SetStatus (UINT id) const
Sets the text in the status bar using the specified string resource ID.
Parameters
id [in] String resource ID.
References MeaStatusBar::SetIdleMessage().
Referenced by MeaAngleTool::Enable(), MeaCircleTool::Enable(), MeaCursorTool::Enable(), MeaLineTool::Enable(), MeaPointTool::Enable(), MeaRectTool::Enable(), and MeaWindowTool::Enable().
ShowAngle()
void MeaToolMgr::ShowAngle (double angle) inline
Displays the specified angle in the angle field of the data display.
Parameters
angle [in] Angle value, in the current angular units.
References m_dataDisplay, and MeaDataDisplay::ShowAngle().
Referenced by MeaAngleTool::Update(), MeaCircleTool::Update(), MeaLineTool::Update(), MeaRectTool::Update(), and MeaWindowTool::Update().
ShowAspect()
void MeaToolMgr::ShowAspect (const FSIZE & size) inline
Displays the aspect ratio of the specified size in the aspect ratio field of the data display.
Parameters
size [in] Width and height of the bounding rectangle.
References m_dataDisplay, and MeaDataDisplay::ShowAspect().
Referenced by MeaLineTool::Update(), MeaRectTool::Update(), and MeaWindowTool::Update().
ShowCalButton()
void MeaToolMgr::ShowCalButton (bool show) inline
Displays or hides the screen calibration button.
Parameters
show [in] true if the screen resolution calibration button should be displayed.
References m_dataDisplay, and MeaDataDisplay::ShowCalButton().
Referenced by MeaScreenTool::Update().
ShowCircleArea()
void MeaToolMgr::ShowCircleArea (double radius) inline
Displays the area of a circle with the specified radius in the area field of the data display.
Parameters
radius [in] Radius from which the circle's area is calculated, in the current units.
References m_dataDisplay, and MeaDataDisplay::ShowCircleArea().
Referenced by MeaCircleTool::Update().
ShowDistance() [1/2]
void MeaToolMgr::ShowDistance (const FSIZE & size) inline
Displays a distance calculated from the specified size in the distance field of the data display.
Parameters
size [in] The distance is calculated from this parameter, in the current units
References m_dataDisplay, and MeaDataDisplay::ShowDistance().
Referenced by MeaCircleTool::Update(), MeaLineTool::Update(), MeaRectTool::Update(), and MeaWindowTool::Update().
ShowDistance() [2/2]
void MeaToolMgr::ShowDistance (double dist) inline
Displays the specified value in the distance field of the data display.
Parameters
dist [in] The distance, in the current units
References m_dataDisplay, and MeaDataDisplay::ShowDistance().
ShowRectArea()
void MeaToolMgr::ShowRectArea (const FSIZE & size) inline
Displays the rectangular area calculated from the specified width and height in the area field of the data display.
Parameters
size [in] Width and height from which the rectangular area is calculated, in current units.
References m_dataDisplay, and MeaDataDisplay::ShowRectArea().
Referenced by MeaLineTool::Update(), MeaRectTool::Update(), and MeaWindowTool::Update().
ShowScreenName()
void MeaToolMgr::ShowScreenName (const CString & name) inline
Displays the name of the current screen.
Parameters
name [in] Name to be displayed.
References m_dataDisplay, and MeaDataDisplay::ShowScreenName().
Referenced by MeaScreenTool::Update().
ShowScreenRes()
void MeaToolMgr::ShowScreenRes (const FSIZE & res) inline
Displays the specified resolution in the appropriate screen fields.
Parameters
res [in] Screen resolution, in the current units.
References m_dataDisplay, and MeaDataDisplay::ShowScreenRes().
Referenced by MeaScreenTool::Update().
ShowScreenWH()
void MeaToolMgr::ShowScreenWH (const FSIZE & size) inline
Displays the specified width and height in the appropriate screen fields.
Parameters
size [in] Width and height, in the current units.
References m_dataDisplay, and MeaDataDisplay::ShowScreenWH().
Referenced by MeaScreenTool::Update().
ShowWH()
void MeaToolMgr::ShowWH (const FSIZE & size) inline
Displays the specified size in the width and height fields of the data display.
Parameters
size [in] Width and height, in the current units
References m_dataDisplay, and MeaDataDisplay::ShowWH().
Referenced by MeaCircleTool::Update(), MeaLineTool::Update(), MeaRectTool::Update(), and MeaWindowTool::Update().
ShowXY1()
void MeaToolMgr::ShowXY1 (const POINT & point, const FPOINT & cpoint) inline
Displays the specified point in the X1/Y1 fields of the data display and on the rulers, if they are visible.
Parameters
point [in] Point, in pixels.
cpoint [in] Point, in the current units.
References MeaRuler::Ind1, m_dataDisplay, m_rulerTool, MeaRulerTool::SetIndicator(), and MeaDataDisplay::ShowXY1().
Referenced by MeaAngleTool::Update(), MeaCircleTool::Update(), MeaCursorTool::Update(), MeaLineTool::Update(), MeaPointTool::Update(), MeaRectTool::Update(), and MeaWindowTool::Update().
ShowXY2()
void MeaToolMgr::ShowXY2 (const POINT & point, const FPOINT & cpoint) inline
Displays the specified point in the X2/Y2 fields of the data display and on the rulers, if they are visible.
Parameters
point [in] Point, in pixels.
cpoint [in] Point, in the current units.
References MeaRuler::Ind2, m_dataDisplay, m_rulerTool, MeaRulerTool::SetIndicator(), and MeaDataDisplay::ShowXY2().
Referenced by MeaAngleTool::Update(), MeaLineTool::Update(), MeaRectTool::Update(), and MeaWindowTool::Update().
ShowXYV()
void MeaToolMgr::ShowXYV (const POINT & point, const FPOINT & cpoint) inline
Displays the specified point in the XV/YV fields of the data display and on the rulers, if they are visible.
Parameters
point [in] Point, in pixels.
cpoint [in] Point, in the current units.
References MeaRuler::Ind3, m_dataDisplay, m_rulerTool, MeaRulerTool::SetIndicator(), and MeaDataDisplay::ShowXYV().
Referenced by MeaAngleTool::Update(), and MeaCircleTool::Update().
StrobeTool()
void MeaToolMgr::StrobeTool () const inline
Causes the current radio tool to strobe.
Typically strobing a tool causes its crosshairs to cycle once between their normal visual state and a hilited state.
References m_currentRadioTool, and MeaRadioTool::Strobe().
Referenced by MeaPositionLogMgr::RecordPosition(), and MeaPositionLogMgr::ReplacePosition().
ToggleEnableTool()
void MeaToolMgr::ToggleEnableTool (const CString & toolName) const inline
If the specified tool is enabled, this method disables it, and vice versa.
Parameters
toolName [in] Name of the tool to toggle.
References MeaTool::Disable(), MeaTool::Enable(), FindTool(), and MeaTool::IsEnabled().
Referenced by CChildView::OnRuler(), and CChildView::OnScreenGrid().
UpdateScreenInfo()
void MeaToolMgr::UpdateScreenInfo (const POINT & pos) inline
Updates the display of the screen size and resolution based on the screen containing the specified point.
In the case where there are multiple monitors attached to the system, the screen information display needs to be updated to reflect the screen containing the point being manipulated.
Parameters
pos [in] Point defining a screen.
References m_screenTool, and MeaScreenTool::SetPosition().
Referenced by MeaAngleTool::Update(), MeaCircleTool::Update(), MeaCursorTool::Update(), MeaLineTool::Update(), MeaPointTool::Update(), MeaRectTool::Update(), and MeaWindowTool::Update().
UpdateTools()
void MeaToolMgr::UpdateTools (MeaUpdateReason reason = NormalUpdate) const inline
Tells all tools to update their visual display.
Parameters
reason [in] Reason the update was requested.
References m_tools.
Referenced by CChildView::ApplyPreferences(), CChildView::LoadProfile(), CChildView::MasterReset(), CChildView::OnAngles(), CChildView::OnCustomUnits(), CChildView::OnInvertY(), CChildView::OnOrigin(), CChildView::OnResetOrigin(), CChildView::OnUnits(), and MeaPositionLogMgr::Position::Show().
Member Data Documentation
kDefCrosshairsEnabled
const bool MeaToolMgr::kDefCrosshairsEnabled = true static
Crosshairs are enabled by default.
Managers are singletons.
Referenced by MasterReset().
The documentation for this class was generated from the following files:
ToolMgr.h
ToolMgr.cpp
Copyright 2011 C Thing Software