Meazure: MeaLine Class Reference
MeaLine Class Reference
A line element.
#include <Line.h>
Public Member Functions
MeaLine ()
Constructs a line.
virtual ~MeaLine ()
Destroys the line.
bool Create (int shrink, const MeaScreenProvider &screenProvider, const CWnd *parent=nullptr)
Creates the window for the line.
virtual void Hide () override
Hides the graphic.
void SetPosition (const POINT &startPoint, const POINT &endPoint)
Sets the position of the line.
void GetPosition (POINT &startPoint, POINT &endPoint)
Obtains the position of the line.
void SetColor (COLORREF color)
Sets the color of the line.
Public Member Functions inherited from MeaGraphic
MeaGraphic ()
Base class constructor.
virtual ~MeaGraphic ()
Base class destructor.
bool Create (LPCTSTR classname, const SIZE &size, const CWnd *parent, UINT id=0xFFFF)
Creates the window for the graphic.
virtual void Show ()
Displays the graphic.
virtual void Hide ()
Hides the graphic.
void SetAbove (const CWnd *winBelow)
Changes the z-order of the graphic window so that it if above the specified window.
Protected Member Functions
afx_msg LRESULT OnHPTimer (WPARAM wParam, LPARAM lParam)
Windows GDI was not optimized for doing crazy things like creating a window that is a thin line.
Private Types
enum Orientation {
Vertical ,
Horizontal ,
Angled
}
If the line is vertical or horizontal, the creation of the window region can be heavily optimized.
Private Member Functions
MeaLine (const MeaLine &)
Copy constructor is purposely undefined.
MeaLine & operator= (const MeaLine &)
Assignment operator is purposely undefined.
void PlotLine ()
The window region is composed of single pixel rectangles arranged in a line from the start point to the end point.
void AddPoint (int x, int y)
The window is composed of a series of single pixel rectangles arranged in a line.
Private Attributes
CPoint m_startPoint
Location of the start point of the line, in pixels.
CPoint m_endPoint
Location of the end point of the line, in pixels.
bool m_wasAngled
Indicates if the line was angled the last time it was drawn.
CBrush * m_foreBrush
Brush used to draw the line.
MeaTimer m_timer
Timer for delayed drawing of line to reduce visual artifacts.
Orientation m_orientation
Current orientation of the line.
POINT * m_arr
Array of coordinates for each rectangle making up the window region.
unsigned int m_count
Number of rectangles in the window region.
int m_shrink
Number of pixels to shrink the length of the line.
Static Private Attributes
static const CSize kMargin
Padding around line bounding rectangle, in pixels.
static int * m_varr = nullptr
Number of coordinates comprising each polygon making up the window region (always 4 in our case)
Additional Inherited Members
Protected Attributes inherited from MeaGraphic
UINT m_id
ID for the graphic.
bool m_visible
Indicates whether the graphic is shown or hidden.
const CWnd * m_parent
Graphic's parent window or nullptr if graphic is a popup window.
Static Protected Attributes inherited from MeaGraphic
static constexpr int kInitCoord { -1000 }
An arbitrary initial coordinate for placing new graphics.
Detailed Description
A line element.
The line is used by many tools including the Line and Grid tools. The line is positioned by specifying the location of its two end points. The line is formed by arranging adjacent single pixel rectangular regions.
Member Enumeration Documentation
Orientation
enum MeaLine::Orientation private
If the line is vertical or horizontal, the creation of the window region can be heavily optimized.
If the line is at an arbitrary angle, the optimization cannot be used.
Enumerator
Vertical
The line is vertical.
Horizontal
The line is horizontal.
Angled
The line is oriented at an arbitrary angle.
Constructor & Destructor Documentation
MeaLine()
MeaLine::MeaLine ()
Constructs a line.
Prior to displaying the line with the Show() method, the Create() method must be called to create the line's window.
Member Function Documentation
AddPoint()
void MeaLine::AddPoint (int x, int y) inline private
The window is composed of a series of single pixel rectangles arranged in a line.
At each point on the line the coordinates of a rectangle surrounding that point are added to an array of points. This array of points will eventually be handed to the GDI function CreatePolyPolygonRgn.
Parameters
x [in] X coordinate of the point on the line
y [in] Y coordinate of the point on the line
References m_arr, and m_count.
Referenced by PlotLine().
Create()
bool MeaLine::Create (int shrink, const MeaScreenProvider & screenProvider, const CWnd * parent = nullptr)
Creates the window for the line.
This method must be called before the line can be displayed and before any operation that attempts to manipulate the line's window.
Parameters
shrink [in] Distance, in pixels, to shrink line from start and end points. The typical use for this parameter is in the Line tool. Shrinking the line allows the contents of the end points to be clear for viewing and measuring.
screenProvider [in] Screen information provider
parent [in] Parent window or nullptr if the line does not have an immediate parent. If a parent window is specified, the line is created as a child window (WS_CHILD). Otherwise the line is created as a popup window (WS_POPUP) and is assigned the main window as a parent.
Returns
true if the window is created successfully.
References MeaGeometry::CalcLength(), MeaTimer::Create(), MeaGraphic::Create(), MeaScreenProvider::GetVirtualRect(), m_arr, m_foreBrush, m_shrink, m_timer, and m_varr.
Referenced by MeaAngleTool::Create(), MeaCircleTool::Create(), MeaLineTool::Create(), MeaOriginTool::Create(), and MeaGridTool::SetLines().
GetPosition()
void MeaLine::GetPosition (POINT & startPoint, POINT & endPoint) inline
Obtains the position of the line.
Parameters
startPoint [out] Location of the start of the line, in pixels
endPoint [out] Location of the end of the line, in pixels
References m_endPoint, and m_startPoint.
Referenced by MeaAngleTool::OnCHMove(), and MeaLineTool::OnCHMove().
Hide()
void MeaLine::Hide () override virtual
Hides the graphic.
Call the Create() method prior to calling this method for the first time.
Reimplemented from MeaGraphic.
References MeaGraphic::Hide(), m_timer, and MeaTimer::Stop().
Referenced by MeaAngleTool::Disable(), MeaCircleTool::Disable(), MeaLineTool::Disable(), and MeaOriginTool::Disable().
OnHPTimer()
LRESULT MeaLine::OnHPTimer (WPARAM wParam, LPARAM lParam) protected
Windows GDI was not optimized for doing crazy things like creating a window that is a thin line.
Because of this, drawing the window is very expensive. To minimize visual artifacts when the line is repositioned or resized, a timer is used to effectively add damping to the drawing process. Even if the user may be making quick changes to the line, the time delay reduces the number of redraws. When the SetPosition() method is called, it just sets a timer and returns. When the timer expires, this method is called and actually redraws the window.
Parameters
wParam [in] not used
lParam [in] not used
Returns
The return is not used so 0 is returned.
References Angled, kMargin, m_arr, m_count, m_endPoint, m_orientation, m_shrink, m_startPoint, m_varr, MeaGraphic::m_visible, m_wasAngled, PlotLine(), MeaLayout::SetWindowPos(), MeaGraphic::Show(), and Vertical.
PlotLine()
void MeaLine::PlotLine () private
The window region is composed of single pixel rectangles arranged in a line from the start point to the end point.
The location of each rectangle is determined using the Bresenham algorithm adapted from "Graphics Gems", Academic Press, 1990, p. 685. The line needs to be created in this brute force way because relying on the polygon region method produces a horrible looking line.
References AddPoint(), m_count, m_endPoint, m_startPoint, and MeaPlotter::PlotLine().
Referenced by OnHPTimer().
SetColor()
void MeaLine::SetColor (COLORREF color)
Sets the color of the line.
Parameters
color [in] Color value defined by the Windows GDI RGB macro.
References m_foreBrush.
Referenced by MeaAngleTool::ColorsChanged(), MeaCircleTool::ColorsChanged(), MeaLineTool::ColorsChanged(), and MeaOriginTool::ColorsChanged().
SetPosition()
void MeaLine::SetPosition (const POINT & startPoint, const POINT & endPoint)
Sets the position of the line.
Parameters
startPoint [in] Location of the start of the line, in pixels
endPoint [in] Location of the end of the line, in pixels
References Angled, Horizontal, m_endPoint, m_orientation, m_startPoint, m_timer, MeaGraphic::m_visible, m_wasAngled, MeaGraphic::Show(), MeaTimer::Start(), and Vertical.
Referenced by MeaAngleTool::OnCHMove(), MeaCircleTool::OnCHMove(), MeaLineTool::OnCHMove(), MeaAngleTool::SetPosition(), MeaCircleTool::SetPosition(), MeaLineTool::SetPosition(), MeaOriginTool::Update(), and MeaAngleTool::UpdateBisector().
The documentation for this class was generated from the following files:
Line.h
Line.cpp
Copyright 2011 C Thing Software