Meazure: MeaColors Class Reference
MeaColors Class Reference
A color style sheet class that provides the colors and opacities used by the crosshairs, lines and other graphic elements.
#include <Colors.h>
Public Types
enum Item {
LineFore ,
CrossHairBack ,
CrossHairBorder ,
CrossHairHilite ,
CrossHairOpacity ,
RulerBack ,
RulerBorder ,
RulerOpacity
}
Identifies the item whose color and opacity are maintained by this class.
Static Public Member Functions
static void Initialize ()
Initializes the class by establishing the default colors.
static void Reset ()
Resets all colors to their default values.
static void SaveProfile (MeaProfile &profile)
Persists the color settings to the specified profile.
static void LoadProfile (MeaProfile &profile)
Restores the color settings from the specified profile.
static void MasterReset ()
Called when the master application reset is invoked.
static void Set (Item item, COLORREF clr)
Sets the specified item to the specified color.
static void SetA (Item item, BYTE opacity)
Sets the specified item to the specified opacity.
static COLORREF Get (Item item)
Returns the color of the specified item.
static BYTE GetR (Item item)
Returns the value of the red color component of the specified item.
static BYTE GetG (Item item)
Returns the value of the green color component of the specified item.
static BYTE GetB (Item item)
Returns the value of the blue color component of the specified item.
static BYTE GetA (Item item)
Returns the opacity of the specified item.
static COLORREF GetDef (Item item)
Returns the default color for the specified item.
static COLORREF InterpolateColor (COLORREF startRGB, COLORREF endRGB, int percent)
Performs linear interpolation between the specified RGB color.
static void RGBtoHSL (COLORREF rgb, HSL &hsl)
Converts from the RGB color space to the HSL color space.
static void HSLtoRGB (const HSL &hsl, COLORREF &rgb)
Converts from the HSL color space to the RGB color space.
Private Types
typedef std::map< Item, COLORREF > Colors
Maps items to their colors.
Private Member Functions
MeaColors ()
All members of this class are static.
~MeaColors ()
All members of this class are static.
Static Private Member Functions
static double Min (double a, double b)
Determines the minimum of two values.
static double Max (double a, double b)
Determines the maximum of two values.
static double HuetoRGB (double m1, double m2, double h)
Converts a hue to a RGB component value based on the specified weighting factors.
Static Private Attributes
static Colors m_defColors
Map of default colors.
static Colors m_colors
Map of active colors.
Detailed Description
A color style sheet class that provides the colors and opacities used by the crosshairs, lines and other graphic elements.
Member Enumeration Documentation
Item
enum MeaColors::Item
Identifies the item whose color and opacity are maintained by this class.
Enumerator
LineFore
Line foreground color.
CrossHairBack
Crosshair background color.
CrossHairBorder
Crosshair edge color.
CrossHairHilite
Crosshair highlight color.
CrossHairOpacity
Opacity of the crosshair.
RulerBack
Ruler background color.
RulerBorder
Ruler edge and tick mark color.
RulerOpacity
Ruler opacity.
Constructor & Destructor Documentation
MeaColors()
MeaColors::MeaColors () inline private
All members of this class are static.
No instances of this class are ever created.
~MeaColors()
MeaColors::~MeaColors () inline private
All members of this class are static.
No instances of this class are ever created.
Member Function Documentation
Get()
static COLORREF MeaColors::Get (Item item) inline static
Returns the color of the specified item.
Parameters
item [in] Item whose color is desired.
Returns
Color of the specified item.
References m_colors.
Referenced by MeaAngleTool::ColorsChanged(), MeaCircleTool::ColorsChanged(), MeaGridTool::ColorsChanged(), MeaLineTool::ColorsChanged(), MeaOriginTool::ColorsChanged(), MeaPointTool::ColorsChanged(), MeaRectTool::ColorsChanged(), MeaRulerTool::ColorsChanged(), MeaWindowTool::ColorsChanged(), MeaAngleTool::Create(), MeaCircleTool::Create(), MeaLineTool::Create(), MeaPointTool::Create(), MeaRectTool::Create(), MeaRulerTool::Enable(), and CChildView::OnPreferences().
GetA()
static BYTE MeaColors::GetA (Item item) inline static
Returns the opacity of the specified item.
Parameters
item [in] Item whose opacity is desired.
Returns
Opacity of the specified item, where 0 is completely transparent and 255 is completely opaque.
References m_colors.
Referenced by MeaAngleTool::ColorsChanged(), MeaCircleTool::ColorsChanged(), MeaCursorTool::ColorsChanged(), MeaLineTool::ColorsChanged(), MeaPointTool::ColorsChanged(), MeaRectTool::ColorsChanged(), MeaRulerTool::ColorsChanged(), MeaWindowTool::ColorsChanged(), MeaAngleTool::Create(), MeaCircleTool::Create(), MeaCursorTool::Create(), MeaLineTool::Create(), MeaPointTool::Create(), MeaRectTool::Create(), MeaWindowTool::Create(), MeaRulerTool::Enable(), and CChildView::OnPreferences().
GetB()
static BYTE MeaColors::GetB (Item item) inline static
Returns the value of the blue color component of the specified item.
Parameters
item [in] Item whose color component is desired.
Returns
Blue color component of the specified item.
References m_colors.
GetDef()
static COLORREF MeaColors::GetDef (Item item) inline static
Returns the default color for the specified item.
Parameters
item [in] Item whose default color is desired.
Returns
Default color for the specified item.
References m_defColors.
Referenced by MeaToolsPrefs::OnDefBackColor(), MeaRulerPrefs::OnDefBkColor(), MeaRulerPrefs::OnDefBorderColor(), MeaToolsPrefs::OnDefBorderColor(), MeaToolsPrefs::OnDefHiliteColor(), and MeaToolsPrefs::OnDefLineColor().
GetG()
static BYTE MeaColors::GetG (Item item) inline static
Returns the value of the green color component of the specified item.
Parameters
item [in] Item whose color component is desired.
Returns
Green color component of the specified item.
References m_colors.
GetR()
static BYTE MeaColors::GetR (Item item) inline static
Returns the value of the red color component of the specified item.
Parameters
item [in] Item whose color component is desired.
Returns
Red color component of the specified item.
References m_colors.
HSLtoRGB()
void MeaColors::HSLtoRGB (const HSL & hsl, COLORREF & rgb) static
Converts from the HSL color space to the RGB color space.
Parameters
hsl [in] HSL colors as values between 0.0 and 1.0.
rgb [out] RGB colors as values between 0 and 255.
References HuetoRGB().
Referenced by InterpolateColor().
HuetoRGB()
double MeaColors::HuetoRGB (double m1, double m2, double h) static private
Converts a hue to a RGB component value based on the specified weighting factors.
Parameters
m1 [in] Weighting factor between lightness and saturation.
m2 [in] Weighting factor between lightness and saturation.
h [in] Hue value.
Returns
Either an R, G, or B value between 0.0 and 1.0. The component returned depends on the weighting factors specified.
Referenced by HSLtoRGB().
InterpolateColor()
COLORREF MeaColors::InterpolateColor (COLORREF startRGB, COLORREF endRGB, int percent) static
Performs linear interpolation between the specified RGB color.
The interpolation is performed in HSL space, which provides a more visually appealing result.
Parameters
startRGB [in] Starting interpolation point.
endRGB [in] Ending interpolation point.
percent [in] Interpolation point between startRGB and endRGB as a percentage.
Returns
Interpolated color.
References HSLtoRGB(), and RGBtoHSL().
Referenced by MeaRuler::DrawRuler().
LoadProfile()
void MeaColors::LoadProfile (MeaProfile & profile) static
Restores the color settings from the specified profile.
Parameters
profile [in] Profile from which the color settings are restored.
References CrossHairBack, CrossHairBorder, CrossHairHilite, CrossHairOpacity, LineFore, m_colors, m_defColors, MeaProfile::ReadInt(), RulerBack, RulerBorder, RulerOpacity, and MeaProfile::UserInitiated().
Referenced by CChildView::LoadProfile().
MasterReset()
void MeaColors::MasterReset () static
Called when the master application reset is invoked.
The colors are reset to their default values.
References m_colors, and m_defColors.
Referenced by CChildView::MasterReset().
Max()
static double MeaColors::Max (double a, double b) inline static private
Determines the maximum of two values.
Returns
Maximum value.
Referenced by RGBtoHSL().
Min()
static double MeaColors::Min (double a, double b) inline static private
Determines the minimum of two values.
Returns
Minimum value.
Referenced by RGBtoHSL().
RGBtoHSL()
void MeaColors::RGBtoHSL (COLORREF rgb, HSL & hsl) static
Converts from the RGB color space to the HSL color space.
Parameters
rgb [in] RGB colors as values between 0 and 255.
hsl [out] HSL colors as values between 0.0 and 1.0
References Max(), MEA_DBL_EQL, and Min().
Referenced by MeaMagnifier::Draw(), and InterpolateColor().
SaveProfile()
void MeaColors::SaveProfile (MeaProfile & profile) static
Persists the color settings to the specified profile.
Parameters
profile [in] Profile into which the color settings are persisted.
References CrossHairBack, CrossHairBorder, CrossHairHilite, CrossHairOpacity, LineFore, m_colors, RulerBack, RulerBorder, RulerOpacity, MeaProfile::UserInitiated(), and MeaProfile::WriteInt().
Referenced by CChildView::SaveProfile().
Set()
static void MeaColors::Set (Item item, COLORREF clr) inline static
Sets the specified item to the specified color.
Parameters
item [in] Color item to set.
clr [in] Color to set.
References m_colors.
Referenced by CChildView::ApplyPreferences().
SetA()
static void MeaColors::SetA (Item item, BYTE opacity) inline static
Sets the specified item to the specified opacity.
Parameters
item [in] Item whose opacity is to be set.
opacity [in] Opacity to set, where 0 is completely transparent and 255 is completely opaque.
References m_colors.
Referenced by CChildView::ApplyPreferences().
The documentation for this class was generated from the following files:
Colors.h
Colors.cpp
Copyright 2011 C Thing Software