Meazure: MeaPositionLogMgr::Position Class Reference
MeaPositionLogMgr::Position Class Reference
Represents a tool position.
#include <PositionLogMgr.h>
Public Member Functions
Position ()
Constructs a position object.
Position (MeaPositionLogMgr *mgr, const MeaGUID &desktopInfoId)
Constructs a position object that references the specified desktop information object.
Position (MeaPositionLogMgr *mgr, const CString &desktopInfoIdStr, const CString &toolName, const CString &timestamp)
Constructs a position object that represents the position of the specified tool at the specified time.
Position (const Position &position)
Copy constructor.
~Position ()
Destroys a position object.
Position & operator= (const Position &position)
Performs assignment of the specified position object to this position object.
void SetDesc (const CString &desc)
Places a description on the position.
CString GetDesc () const
Returns the description of the position.
CString GetTimeStamp () const
Returns the timestamp indicating when this position was recorded.
void AddPoint (LPCTSTR name, const FPOINT &pt)
Adds the specified point to the position using the specified name to identify the point.
void RecordXY1 (const FPOINT &point)
Records the specified point as an x1, y1 point.
void RecordXY2 (const FPOINT &point)
Records the specified point as an x2, y2 point.
void RecordXYV (const FPOINT &point)
Records the specified point as an xv, yv point.
void RecordWH (const FSIZE &size)
Records the specified width and height.
void RecordDistance (const FSIZE &size)
Records a distance.
void RecordDistance (double dist)
Records the specified distance.
void RecordAngle (double angle)
Records the angle.
void RecordRectArea (const FSIZE &size)
Records a rectangular area.
void RecordCircleArea (double radius)
Records a circular area.
void Show () const
Tells the tool manager to display the position using the appropriate tool.
void Load (const MeaXMLNode *positionNode)
Loads the position elements of the log file.
void Save (int indent) const
Saves the position in the position log file.
Private Types
typedef std::map< CString, FPOINT > PointMap
Maps a point name to the coordinates of the point.
Private Member Functions
Position & Copy (const Position &position)
Copies the specified position to this object.
Private Attributes
UINT m_fieldMask
Data fields defined for this position. Different tools provide different amounts of data.
PointMap m_points
Location of the current tool, , in the units in effect when the position was recorded.
double m_width
Width of rectangle or bounding box, in the units in effect when the position was recorded.
double m_height
Height of rectangle or bounding box, in the units in effect when the position was recorded.
double m_distance
Length of line or diagonal, in the units in effect when the position was recorded.
double m_area
Area of rectangle or bounding box, in the units in effect when the position was recorded.
double m_angle
Angle of diagonal, line, or angle tool, in the units in effect when the position was recorded.
MeaPositionLogMgr * m_mgr
Parent manager.
MeaGUID m_desktopInfoId
Id of desktop information object referenced by this position.
CString m_toolName
Name of measurement tool whose position is represented by this object.
CString m_timestamp
Date and time the position was recorded.
CString m_desc
Description for position.
Detailed Description
Represents a tool position.
A position object references the desktop information that provides its environment. Since desktop environments do not tend to change often, many position objects typically reference the same desktop information object. The position object is ultimately persisted to the position log file along with the desktop information object.
A position consists of one or more (x,y) points. The number of points required for a position depends on the measurement tool whose position is being recorded. For example, the Point tool requires only one point to completely describe its position, whereas the Line tool requires two points, one per endpoint of the line. Each point is named by the tool (e.g. "v", "1", "2").
Constructor & Destructor Documentation
Position() [1/4]
MeaPositionLogMgr::Position::Position ()
Constructs a position object.
This constructor is intended for use solely by STL collections and is not used to construct new position objects in general use.
Position() [2/4]
MeaPositionLogMgr::Position::Position (MeaPositionLogMgr * mgr, const MeaGUID & desktopInfoId)
Constructs a position object that references the specified desktop information object.
Parameters
mgr [in] Parent manager.
desktopInfoId [in] GUID representing the desktop information object to be referenced by this position.
References MeaPositionLogMgr::AddDesktopRef(), MeaToolMgr::GetPosition(), MeaSingleton_T< MeaToolMgr >::Instance(), m_desktopInfoId, and m_mgr.
Position() [3/4]
MeaPositionLogMgr::Position::Position (MeaPositionLogMgr * mgr, const CString & desktopInfoIdStr, const CString & toolName, const CString & timestamp)
Constructs a position object that represents the position of the specified tool at the specified time.
Parameters
mgr [in] Parent manager.
desktopInfoIdStr [in] GUID expressed as a string representing the desktop information object referenced by this position.
toolName [in] Name of the measurement tool whose position is represented by this position object.
timestamp [in] Identifies when this position was recorded.
References MeaPositionLogMgr::AddDesktopRef(), m_desktopInfoId, and m_mgr.
Position() [4/4]
MeaPositionLogMgr::Position::Position (const Position & position)
Copy constructor.
Parameters
position [in] Position object to be copied into a new position object.
References Copy().
Member Function Documentation
AddPoint()
void MeaPositionLogMgr::Position::AddPoint (LPCTSTR name, const FPOINT & pt) inline
Adds the specified point to the position using the specified name to identify the point.
Parameters
name [in] Name to assign the point.
pt [in] Point to be stored in the position.
References m_points.
Copy()
MeaPositionLogMgr::Position & MeaPositionLogMgr::Position::Copy (const Position & position) private
Copies the specified position to this object.
Parameters
position [in] Position to be copied.
Returns
This object.
References m_angle, m_area, m_desc, MeaPositionLogMgr::m_desc, m_desktopInfoId, m_distance, m_fieldMask, m_height, m_mgr, m_points, m_timestamp, m_toolName, and m_width.
Referenced by operator=(), and Position().
GetDesc()
CString MeaPositionLogMgr::Position::GetDesc () const inline
Returns the description of the position.
Returns
Description of the position or the empty string if there is no description.
References m_desc.
Referenced by MeaPositionLogDlg::OnKillfocusPositionDesc(), and MeaPositionLogDlg::UpdatePositionInfo().
GetTimeStamp()
CString MeaPositionLogMgr::Position::GetTimeStamp () const inline
Returns the timestamp indicating when this position was recorded.
Returns
Timestamp for the position in ISO 8601 format.
References m_timestamp.
Referenced by MeaPositionLogDlg::UpdatePositionInfo().
Load()
void MeaPositionLogMgr::Position::Load (const MeaXMLNode * positionNode)
Loads the position elements of the log file.
Parameters
positionNode [in] Position node in the DOM.
References MeaXMLNode::AtEnd(), MeaXMLNode::Element, MeaXMLNode::GetAttributes(), MeaXMLNode::GetChildIter(), MeaXMLNode::GetData(), MeaXMLNode::GetType(), MeaXMLAttributes::GetValueDbl(), MeaXMLAttributes::GetValueStr(), MeaAngleField, MeaAreaField, MeaDistanceField, MeaHeightField, MeaWidthField, MeaPositionLogMgr::ProcessDataNodes(), FPOINT::x, and FPOINT::y.
Referenced by MeaPositionLogMgr::ProcessPositionNode().
operator=()
Position & MeaPositionLogMgr::Position::operator= (const Position & position) inline
Performs assignment of the specified position object to this position object.
Parameters
position [in] Object to be copied to this.
Returns
This object.
References Copy().
RecordAngle()
void MeaPositionLogMgr::Position::RecordAngle (double angle)
Records the angle.
Parameters
angle [in] Angle to record, in the current angular units.
References MeaUnitsMgr::ConvertAngle(), MeaSingleton_T< MeaUnitsMgr >::Instance(), and MeaAngleField.
Referenced by MeaAngleTool::GetPosition(), MeaCircleTool::GetPosition(), MeaLineTool::GetPosition(), MeaRectTool::GetPosition(), and MeaWindowTool::GetPosition().
RecordCircleArea()
void MeaPositionLogMgr::Position::RecordCircleArea (double radius)
Records a circular area.
The area is calculated using the formula:
Parameters
radius [in] Radius used to calculate the area, in the current units.
References MeaUnits::kPI, and MeaAreaField.
Referenced by MeaCircleTool::GetPosition().
RecordDistance() [1/2]
void MeaPositionLogMgr::Position::RecordDistance (const FSIZE & size)
Records a distance.
The distance is calculated by the method using the formula:
Parameters
size [in] Width and height used to calculate the distance, in the current units.
References MeaLayout::CalcLength(), FSIZE::cx, FSIZE::cy, and MeaDistanceField.
Referenced by MeaCircleTool::GetPosition(), MeaLineTool::GetPosition(), MeaRectTool::GetPosition(), and MeaWindowTool::GetPosition().
RecordDistance() [2/2]
void MeaPositionLogMgr::Position::RecordDistance (double dist)
Records the specified distance.
Parameters
dist [in] Distance to record, in the current units.
References MeaDistanceField.
RecordRectArea()
void MeaPositionLogMgr::Position::RecordRectArea (const FSIZE & size)
Records a rectangular area.
The area is calculated by the formula:
Parameters
size [in] WWidth and height used to calculate the area, in the current units.
References FSIZE::cx, FSIZE::cy, and MeaAreaField.
Referenced by MeaLineTool::GetPosition(), MeaRectTool::GetPosition(), and MeaWindowTool::GetPosition().
RecordWH()
void MeaPositionLogMgr::Position::RecordWH (const FSIZE & size)
Records the specified width and height.
Parameters
size [in] Width and height to record, in the current units.
References FSIZE::cx, FSIZE::cy, MeaHeightField, and MeaWidthField.
Referenced by MeaCircleTool::GetPosition(), MeaLineTool::GetPosition(), MeaRectTool::GetPosition(), and MeaWindowTool::GetPosition().
RecordXY1()
void MeaPositionLogMgr::Position::RecordXY1 (const FPOINT & point)
Records the specified point as an x1, y1 point.
Parameters
point [in] Point to record, in the current units.
References MeaX1Field, and MeaY1Field.
Referenced by MeaAngleTool::GetPosition(), MeaCircleTool::GetPosition(), MeaCursorTool::GetPosition(), MeaLineTool::GetPosition(), MeaPointTool::GetPosition(), MeaRectTool::GetPosition(), and MeaWindowTool::GetPosition().
RecordXY2()
void MeaPositionLogMgr::Position::RecordXY2 (const FPOINT & point)
Records the specified point as an x2, y2 point.
Parameters
point [in] Point to record, in the current units.
References MeaX2Field, and MeaY2Field.
Referenced by MeaAngleTool::GetPosition(), MeaLineTool::GetPosition(), MeaRectTool::GetPosition(), and MeaWindowTool::GetPosition().
RecordXYV()
void MeaPositionLogMgr::Position::RecordXYV (const FPOINT & point)
Records the specified point as an xv, yv point.
Parameters
point [in] Point to record, in the current units.
References MeaXVField, and MeaYVField.
Referenced by MeaAngleTool::GetPosition(), and MeaCircleTool::GetPosition().
Save()
void MeaPositionLogMgr::Position::Save (int indent) const
Saves the position in the position log file.
Parameters
indent [in] Output indentation level.
Exceptions
CFileException if there was a problem saving the position
References MeaUtils::CRLFtoLF(), MeaUtils::DblToStr(), MeaXMLParser::Encode(), MeaPositionLogMgr::m_desc, MeaAngleField, MeaAreaField, MeaDistanceField, MeaHeightField, and MeaWidthField.
SetDesc()
void MeaPositionLogMgr::Position::SetDesc (const CString & desc) inline
Places a description on the position.
Parameters
desc [in] Descriptive text for the position.
References m_desc.
Referenced by MeaPositionLogDlg::OnKillfocusPositionDesc().
The documentation for this class was generated from the following files:
PositionLogMgr.h
PositionLogMgr.cpp
Copyright 2011 C Thing Software