Meazure: MeaRectangle Class Reference
MeaRectangle Class Reference
A rectangle element.
#include <Rectangle.h>
Public Member Functions
MeaRectangle ()
Constructs a rectangle.
virtual ~MeaRectangle ()
Destroys the rectangle.
bool Create (int thk, int shrink, const CWnd *parent=nullptr)
Creates the window for the rectangle.
virtual void Hide () override
Hides the graphic.
void SetPosition (const POINT &point1, const POINT &point2)
Sets the position of the rectangle.
void SetColor (COLORREF color)
Sets the color of the rectangle's line.
Public Member Functions inherited from MeaGraphic
MeaGraphic ()
Base class constructor.
virtual ~MeaGraphic ()
Base class destructor.
bool Create (LPCTSTR classname, const SIZE &size, const CWnd *parent, UINT id=0xFFFF)
Creates the window for the graphic.
virtual void Show ()
Displays the graphic.
virtual void Hide ()
Hides the graphic.
void SetAbove (const CWnd *winBelow)
Changes the z-order of the graphic window so that it if above the specified window.
Protected Member Functions
afx_msg LRESULT OnHPTimer (WPARAM wParam, LPARAM lParam)
Windows GDI was not optimized for doing crazy things like creating a window that is a thin rectangle.
Private Member Functions
MeaRectangle (const MeaRectangle &)
Copy constructor is purposely undefined.
MeaRectangle & operator= (const MeaRectangle &)
Assignment operator is purposely undefined.
void SetRegion ()
Sets the windows region effectively forming the rectangle.
Private Attributes
CPoint m_point1
Location of the top left corner of the rectangle, in pixels.
CPoint m_point2
Location of the bottom right corner of the rectangle, in pixels.
CBrush * m_foreBrush
Brush to paint the rectangle's line.
MeaTimer m_timer
Timer for delayed drawing of the rectangle to reduce visual artifacts.
int m_thk
Thickness of the rectangle's line, in pixels.
int m_shrink
Number pixels to hang back from the top left and bottom right corners of the rectangle.
Additional Inherited Members
Protected Attributes inherited from MeaGraphic
UINT m_id
ID for the graphic.
bool m_visible
Indicates whether the graphic is shown or hidden.
const CWnd * m_parent
Graphic's parent window or nullptr if graphic is a popup window.
Static Protected Attributes inherited from MeaGraphic
static constexpr int kInitCoord { -1000 }
An arbitrary initial coordinate for placing new graphics.
Detailed Description
A rectangle element.
The rectangle is used by the Rectangle measurement tool. The rectangle is positioned by specifying the location of its its top left corner (point 1) and its bottom right corner (point 2). The rectangle is formed by creating a rectangular window and punching out a smaller rectangle from the window's interior. The remaining region forms the line of the rectangle.
Constructor & Destructor Documentation
MeaRectangle()
MeaRectangle::MeaRectangle ()
Constructs a rectangle.
Prior to displaying the rectangle with the Show() method, the Create() method must be called to create the rectangle's window.
Member Function Documentation
Create()
bool MeaRectangle::Create (int thk, int shrink, const CWnd * parent = nullptr)
Creates the window for the rectangle.
This method must be called before the rectangle can be displayed and before any operation that attempts to manipulate the rectangle's window.
Parameters
thk [in] Thickness of the rectangle's line, in pixels.
shrink [in] Distance, in pixels, to shrink line of the rectangle from the top left and bottom right corners. The typical use for this parameter is in the Rectangle tool. Shrinking the line allows the contents under the corner points to be clear for viewing and measuring.
parent [in] Parent window or nullptr if the rectangle does not have an immediate parent. If a parent window is specified, the rectangle is created as a child window (WS_CHILD). Otherwise the rectangle is created as a popup window (WS_POPUP) and is assigned the main window as a parent.
Returns
true if the window is created successfully.
References MeaTimer::Create(), MeaGraphic::Create(), m_foreBrush, m_shrink, m_thk, m_timer, and SetRegion().
Referenced by MeaRectTool::Create(), and MeaWindowTool::Enable().
Hide()
void MeaRectangle::Hide () override virtual
Hides the graphic.
Call the Create() method prior to calling this method for the first time.
Reimplemented from MeaGraphic.
References MeaGraphic::Hide(), m_timer, and MeaTimer::Stop().
Referenced by MeaRectTool::Disable(), and MeaWindowTool::Disable().
OnHPTimer()
LRESULT MeaRectangle::OnHPTimer (WPARAM wParam, LPARAM lParam) protected
Windows GDI was not optimized for doing crazy things like creating a window that is a thin rectangle.
Because of this, drawing the window is very expensive. To minimize visual artifacts when the rectangle is repositioned or resized, a timer is used to effectively add damping to the drawing process. Even if the user may be making quick changes to the rectangle, the time delay reduces the number of redraws. When the SetPosition() method is called, it just sets a timer and returns. When the timer expires, this method is called and actually redraws the window.
Parameters
wParam [in] not used
lParam [in] not used
Returns
The return is not used so 0 is returned.
References m_point1, m_point2, MeaGraphic::m_visible, SetRegion(), MeaLayout::SetWindowPos(), and MeaGraphic::Show().
SetColor()
void MeaRectangle::SetColor (COLORREF color)
Sets the color of the rectangle's line.
Parameters
color [in] Color value defined by the Windows GDI RGB macro.
References m_foreBrush.
Referenced by MeaRectTool::ColorsChanged(), and MeaWindowTool::ColorsChanged().
SetPosition()
void MeaRectangle::SetPosition (const POINT & point1, const POINT & point2)
Sets the position of the rectangle.
Parameters
point1 [in] Location of the top left corner of the rectangle, in pixels
point2 [in] Location of the bottom right corner of the rectangle, in pixels
References m_point1, m_point2, m_timer, and MeaTimer::Start().
Referenced by MeaWindowTool::Enable(), MeaRectTool::OnCHMove(), MeaWindowTool::OnMouseHook(), and MeaRectTool::SetPosition().
SetRegion()
void MeaRectangle::SetRegion () private
Sets the windows region effectively forming the rectangle.
The rectangle is formed by first creating a normal rectangular window. A smaller rectangle is formed based on the desired thickness for the rectangle's line. This smaller rectangle is used to punch out the window's region, thereby forming the rectangle. The shrinking of the rectangle lines around the top left and bottom right corners, if any, is done by using small rectangles the size of the shrink to punch out the corners of the window.
References m_point1, m_point2, m_shrink, and m_thk.
Referenced by Create(), and OnHPTimer().
The documentation for this class was generated from the following files:
Rectangle.h
Rectangle.cpp
Copyright 2011 C Thing Software