Meazure: MeaXMLNode Class Reference
MeaXMLNode Class Reference
A node in the XML DOM.
#include <XMLParser.h>
Public Types
enum Type {
Unknown,
Element,
Data
}
Indicates the type of the DOM node.
typedef std::list< MeaXMLNode * > NodeList
Represents a list of DOM nodes.
typedef NodeList::const_iterator NodeIter_c
Constant iterator over the DOM nodes.
Public Member Functions
MeaXMLNode ()
Constructs an empty DOM node of unknown type.
MeaXMLNode (const CString &elementName, const MeaXMLAttributes &attrs)
Constructs a DOM node representing the specified element.
MeaXMLNode (const CString &data)
Constructs a DOM node representing the specified data.
MeaXMLNode (const MeaXMLNode &node)
Copy constructor.
virtual ~MeaXMLNode ()
Destroys a node.
Type GetType () const
Returns the type of the node.
const CString & GetData () const
Returns the data for the node.
const MeaXMLAttributes & GetAttributes () const
Returns the attributes associated with the node if it is of type Element.
MeaXMLNode & operator= (const MeaXMLNode &node)
Performs a deep copy assignment of the specified node to this.
void AddChild (MeaXMLNode *child)
Adds the specified DOM node as a child of this node.
MeaXMLNode & Assign (const MeaXMLNode &node)
Performs a deep copy assignment of the specified node to this.
NodeIter_c GetChildIter () const
Returns a constant iterator over the children of this node.
bool AtEnd (const NodeIter_c &iter) const
Indicates whether the specified iterator has reached the end of the list of children nodes.
Private Member Functions
void SetParent (MeaXMLNode *parent)
Sets the specified node as the parent for this node.
Private Attributes
Type m_type
Type for the node.
CString m_data
Either empty, element name, or character data depending on the node type.
MeaXMLAttributes m_attributes
Attributes associated with an element node.
NodeList m_children
Children of this node.
MeaXMLNode * m_parent
Parent of this node.
Detailed Description
A node in the XML DOM.
The MeaXMLParser class can build a DOM from the parsed file. This is a very minimal DOM and does not conform to the W3C DOM spec.
Member Enumeration Documentation
enum MeaXMLNode::Type
Indicates the type of the DOM node.
Enumerator:
Unknown
Initial type for a DOM node.
Element
The node represents an XML element.
Data
The node represents data contained between XML elements.
Constructor & Destructor Documentation
MeaXMLNode::MeaXMLNode (const CString & elementName, const MeaXMLAttributes & attrs)
Constructs a DOM node representing the specified element.
Parameters:
elementName [in] The node represents this element.
attrs [in] Attributes associated with the element.
MeaXMLNode::MeaXMLNode (const CString & data) [explicit]
Constructs a DOM node representing the specified data.
Parameters:
data [in] Data for the node.
MeaXMLNode::MeaXMLNode (const MeaXMLNode & node) [inline]
Copy constructor.
Parameters:
node [in] Node to copy.
References Assign().
Member Function Documentation
void MeaXMLNode::AddChild (MeaXMLNode * child) [inline]
Adds the specified DOM node as a child of this node.
Parameters:
child [in] Node to add as a child.
References m_children, MeaAssert, and SetParent().
MeaXMLNode & MeaXMLNode::Assign (const MeaXMLNode & node)
Performs a deep copy assignment of the specified node to this.
Parameters:
node [in] DOM node to assign to this.
Returns:
this
References m_attributes, m_children, m_data, m_parent, and m_type.
Referenced by MeaXMLNode(), and operator=().
bool MeaXMLNode::AtEnd (const NodeIter_c & iter) const [inline]
Indicates whether the specified iterator has reached the end of the list of children nodes.
Parameters:
iter [in] Constant iter to test.
Returns:
true if the iterator has reached the end of the list of children nodes.
References m_children.
Referenced by MeaPositionLogMgr::Screen::Load(), MeaPositionLogMgr::DesktopInfo::Load(), MeaPositionLogMgr::Position::Load(), MeaPositionLogMgr::DesktopInfo::LoadCustomPrecisions(), MeaPositionLogMgr::ProcessDataNodes(), MeaPositionLogMgr::ProcessDOM(), and MeaPositionLogMgr::ProcessInfoNode().
const MeaXMLAttributes& MeaXMLNode::GetAttributes () const [inline]
Returns the attributes associated with the node if it is of type Element.
Returns:
Attributes associated with the node.
References m_attributes.
Referenced by MeaPositionLogMgr::Screen::Load(), MeaPositionLogMgr::DesktopInfo::Load(), MeaPositionLogMgr::Position::Load(), MeaPositionLogMgr::DesktopInfo::LoadCustomPrecisions(), MeaPositionLogMgr::ProcessDesktopNode(), and MeaPositionLogMgr::ProcessPositionNode().
NodeIter_c MeaXMLNode::GetChildIter () const [inline]
Returns a constant iterator over the children of this node.
Returns:
Constant iterator over the children nodes.
References m_children.
Referenced by MeaPositionLogMgr::Screen::Load(), MeaPositionLogMgr::DesktopInfo::Load(), MeaPositionLogMgr::Position::Load(), MeaPositionLogMgr::DesktopInfo::LoadCustomPrecisions(), MeaPositionLogMgr::ProcessDataNodes(), MeaPositionLogMgr::ProcessDOM(), and MeaPositionLogMgr::ProcessInfoNode().
const CString& MeaXMLNode::GetData () const [inline]
Returns the data for the node.
The data returned depends on the node type:
Node Type GetData() Return
Unknown ""
Element Element name
Data Data
Returns:
Data appropriate for the node.
References m_data.
Referenced by MeaPositionLogMgr::Screen::Load(), MeaPositionLogMgr::DesktopInfo::Load(), MeaPositionLogMgr::Position::Load(), MeaPositionLogMgr::DesktopInfo::LoadCustomPrecisions(), MeaPositionLogMgr::ProcessDataNodes(), MeaPositionLogMgr::ProcessDOM(), and MeaPositionLogMgr::ProcessInfoNode().
Type MeaXMLNode::GetType () const [inline]
Returns the type of the node.
Returns:
Node type.
References m_type.
Referenced by MeaPositionLogMgr::Screen::Load(), MeaPositionLogMgr::DesktopInfo::Load(), MeaPositionLogMgr::Position::Load(), MeaPositionLogMgr::ProcessDataNodes(), MeaPositionLogMgr::ProcessDOM(), and MeaPositionLogMgr::ProcessInfoNode().
MeaXMLNode& MeaXMLNode::operator= (const MeaXMLNode & node) [inline]
Performs a deep copy assignment of the specified node to this.
Parameters:
node [in] DOM node to assign to this.
Returns:
this
References Assign().
void MeaXMLNode::SetParent (MeaXMLNode * parent) [inline, private]
Sets the specified node as the parent for this node.
This allows moving up the node hierarchy to the root.
Parameters:
parent [in] Node to set as the parent of this.
References m_parent.
Referenced by AddChild().
Member Data Documentation
CString MeaXMLNode::m_data [private]
Either empty, element name, or character data depending on the node type.
Referenced by Assign(), and GetData().
The documentation for this class was generated from the following files:
XMLParser.h
XMLParser.cpp
Copyright 2011 C Thing Software