Meazure: MeaSwatch Class Reference
MeaSwatch Class Reference
Rectangular color swatch window.
#include <Swatch.h>
Public Member Functions
MeaSwatch ()
Constructs a color swatch window.
virtual ~MeaSwatch ()
Destroys an instance of a color swatch window.
bool Create (COLORREF color, const RECT &rect, CWnd *parent)
Creates the window for the color swatch and sets its background to the specified color.
void Show ()
Makes the window visible.
void Hide ()
Hides the window.
void SetColor (COLORREF color)
Sets the color to be displayed by the swatch.
Protected Member Functions
afx_msg void OnDestroy ()
Called when the window is about to be destroyed.
Private Member Functions
void DestroyColors ()
Deletes the brush used for painting the color swatch.
Private Attributes
CBrush * m_backBrush
Brush used for painting the color swatch.
Detailed Description
Rectangular color swatch window.
Constructor & Destructor Documentation
MeaSwatch()
MeaSwatch::MeaSwatch ()
Constructs a color swatch window.
Before the window can be displayed, the Create method must be called.
Member Function Documentation
Create()
bool MeaSwatch::Create (COLORREF color, const RECT & rect, CWnd * parent)
Creates the window for the color swatch and sets its background to the specified color.
Parameters
color [in] Color for the swatch.
rect [in] Dimensions for the swatch window.
parent [in] Parent window for the color swatch.
Returns
true if creation was successful.
References m_backBrush, MeaAssert, and SetColor().
Referenced by MeaToolsPrefs::OnInitDialog().
OnDestroy()
void MeaSwatch::OnDestroy () protected
Called when the window is about to be destroyed.
The method cleans up the brush used for painting the color swatch.
References DestroyColors().
SetColor()
void MeaSwatch::SetColor (COLORREF color)
Sets the color to be displayed by the swatch.
Parameters
color [in] Color to be displayed.
References DestroyColors(), and m_backBrush.
Referenced by Create(), MeaToolsPrefs::OnChangeLineColor(), and MeaToolsPrefs::OnDefLineColor().
The documentation for this class was generated from the following files:
Swatch.h
Swatch.cpp
Copyright 2011 C Thing Software