Meazure: MeaCustomUnitsPrefs Class Reference
MeaCustomUnitsPrefs Class Reference
Property page for custom measurement units preferences.
#include <CustomUnitsPrefs.h>
Public Types
enum { IDD = IDD_PREF_CUSTOM }
Public Member Functions
MeaCustomUnitsPrefs ()
Constructs an instance of the custom measurement units page.
~MeaCustomUnitsPrefs ()
Destroys an instance of the custom measurement units page.
void GetScaleFactor (MeaCustomUnits::ScaleBasis &scaleBasis, double &scaleFactor) const
Obtains the units basis and scale factor for the custom units.
void SetScaleFactor (MeaCustomUnits::ScaleBasis scaleBasis, double scaleFactor)
Sets the custom units basis and scale factor.
virtual BOOL OnInitDialog ()
Called when the property page is created.
virtual BOOL OnKillActive ()
Called when the page becomes inactive.
virtual BOOL OnSetActive ()
Called when the page becomes active.
virtual BOOL OnApply ()
Called when the Apply button is pressed and validates the page contents.
Public Attributes
CString m_abbrev
Abbreviation for the custom units.
CString m_name
Full name for the custom units.
int m_scaleBasis
Indicates whether the custom units are based on pixels, inches or centimeters.
double m_pxScaleFactor
Scale factor if the custom units are based on pixels.
double m_inScaleFactor
Scale factor if the custom units are based on inches.
double m_cmScaleFactor
Scale factor if the custom units are based on centimeters.
Protected Member Functions
virtual void DoDataExchange (CDataExchange *pDX)
Performs Dynamic Data Exchange (DDX) for the page.
afx_msg void OnClear ()
Called when the Clear Units button is pressed.
afx_msg void OnChange ()
Called when a value changes on the UI.
afx_msg void OnPixelChange ()
Called when the pixel-based scale factor text field value is changed.
afx_msg void OnInchChange ()
Called when the inch-based scale factor text field value is changed.
afx_msg void OnCentimeterChange ()
Called when the centimeter-based scale factor text field value is changed.
afx_msg void OnNameChange ()
Called when the units menu name text field value is changed.
afx_msg void OnAbbrevChange ()
Called when the units abbreviation text field value is changed.
afx_msg void OnPrecision ()
Called when the Set Display Precision button is pressed.
afx_msg void OnCentimeterBasis ()
Called when the centimeter-based scale factor radio button is selected.
afx_msg void OnInchBasis ()
Called when the inch-based scale factor radio button is selected.
afx_msg void OnPixelBasis ()
Called when the pixel-based scale factor radio button is selected.
Private Member Functions
void SetCheck (UINT buttonId)
Ensures radio button behavior on the scale factor basis radio buttons.
bool Validate ()
Validates the custom units data on the page.
void EnableScaleFactor ()
Enables or disables the scale factor and precision controls depending on whether the units name and abbrev.
Private Attributes
bool m_lockout
Prevents cyclic modification of text fields.
CWnd * m_nameField
Units menu name text field.
CWnd * m_abbrevField
Units abbreviation text field.
CWnd * m_precisionButton
Units display precision button.
CWnd * m_basisLabel
Label for the scale factor section of the page.
MeaNumberField m_pxScaleField
Numeric text field for the pixel-based scale factor.
MeaNumberField m_inScaleField
Numeric text field for the inch-based scale factor.
MeaNumberField m_cmScaleField
Numeric text field for the centimeter-based scale factor.
CButton * m_pxButton
Pixel-based scale factor radio button.
CButton * m_inButton
Inch-based scale factor radio button.
CButton * m_cmButton
Centimeter-based scale factor radio button.
CWnd * m_pxLabel
Pixel-based scale factor label.
CWnd * m_inLabel
Inch-based scale factor label.
CWnd * m_cmLabel
Centimeter-based scale factor label.
CWnd * m_pxAbbrev
Pixel-based scale factor abbreviation label.
CWnd * m_inAbbrev
Inch-based scale factor abbreviation label.
CWnd * m_cmAbbrev
Centimeter-based scale factor abbreviation label.
Detailed Description
Property page for custom measurement units preferences.
Using this property page, the user can define their own measurement units (i.e. label and conversion factor).
Member Function Documentation
MeaCustomUnitsPrefs::DoDataExchange (CDataExchange * pDX) [protected, virtual]
Performs Dynamic Data Exchange (DDX) for the page.
Parameters:
pDX [in] DDX object for exchanging data between the page UI and the member variables.
References m_abbrev, m_cmScaleFactor, m_inScaleFactor, m_name, m_pxScaleFactor, and m_scaleBasis.
void MeaCustomUnitsPrefs::EnableScaleFactor () [private]
Enables or disables the scale factor and precision controls depending on whether the units name and abbrev.
fields contain text or are empty.
References m_abbrevField, m_basisLabel, m_cmAbbrev, m_cmButton, m_cmLabel, m_cmScaleField, m_inAbbrev, m_inButton, m_inLabel, m_inScaleField, m_nameField, m_precisionButton, m_pxAbbrev, m_pxButton, m_pxLabel, m_pxScaleField, and MeaAssert.
Referenced by OnAbbrevChange(), OnInitDialog(), and OnNameChange().
void MeaCustomUnitsPrefs::GetScaleFactor (MeaCustomUnits::ScaleBasis & scaleBasis, double & scaleFactor) const
Obtains the units basis and scale factor for the custom units.
Parameters:
scaleBasis [out] Indicates whether the custom units are based on pixels, inches or centimeters.
scaleFactor [out] Conversion factor to/from scaleBasis to/from the custom units.
References MeaCustomUnits::CentimeterBasis, MeaCustomUnits::InchBasis, m_cmScaleFactor, m_inScaleFactor, m_pxScaleFactor, m_scaleBasis, MeaAssert, and MeaCustomUnits::PixelBasis.
Referenced by CChildView::ApplyPreferences().
MeaCustomUnitsPrefs::OnAbbrevChange () [protected]
Called when the units abbreviation text field value is changed.
References EnableScaleFactor(), m_abbrevField, m_cmAbbrev, m_inAbbrev, m_pxAbbrev, MeaAssert, and OnChange().
Referenced by OnClear(), and OnSetActive().
MeaCustomUnitsPrefs::OnApply () [virtual]
Called when the Apply button is pressed and validates the page contents.
The page contents are valid if the menu name label and abbreviation are either both empty or both non-empty and the scale factor is greater than zero.
Returns:
TRUE if the page contents are valid and can be applied. If the page contents are not valid, FALSE is returned.
References Validate().
MeaCustomUnitsPrefs::OnCentimeterBasis () [protected]
Called when the centimeter-based scale factor radio button is selected.
References OnChange().
MeaCustomUnitsPrefs::OnCentimeterChange () [protected]
Called when the centimeter-based scale factor text field value is changed.
References m_lockout, OnChange(), and SetCheck().
MeaCustomUnitsPrefs::OnChange () [protected]
Called when a value changes on the UI.
This method sets the modified flag.
References m_lockout.
Referenced by OnAbbrevChange(), OnCentimeterBasis(), OnCentimeterChange(), OnInchBasis(), OnInchChange(), OnNameChange(), OnPixelBasis(), and OnPixelChange().
MeaCustomUnitsPrefs::OnClear () [protected]
Called when the Clear Units button is pressed.
This method clears the text from the units label fields, which effectively deletes the custom units.
References m_abbrev, m_abbrevField, m_name, m_nameField, MeaAssert, and OnAbbrevChange().
MeaCustomUnitsPrefs::OnInchBasis () [protected]
Called when the inch-based scale factor radio button is selected.
References OnChange().
MeaCustomUnitsPrefs::OnInchChange () [protected]
Called when the inch-based scale factor text field value is changed.
References m_lockout, OnChange(), and SetCheck().
MeaCustomUnitsPrefs::OnInitDialog () [virtual]
Called when the property page is created.
This method subclasses a number of controls on the page, with our implementations and obtains pointers to the page controls.
Returns:
TRUE, indicating that the input focus should be set to the first control on the page.
References EnableScaleFactor(), m_abbrevField, m_basisLabel, m_cmAbbrev, m_cmButton, m_cmLabel, m_cmScaleField, m_inAbbrev, m_inButton, m_inLabel, m_inScaleField, m_nameField, m_precisionButton, m_pxAbbrev, m_pxButton, m_pxLabel, m_pxScaleField, MeaNumberField::PosValues, and MeaNumberField::SetValueType().
MeaCustomUnitsPrefs::OnKillActive () [virtual]
Called when the page becomes inactive.
The data on the page is validated.
Returns:
TRUE if the data was valid and the page can become inactive. FALSE if the data is not valid and the page must remain active.
References Validate().
MeaCustomUnitsPrefs::OnNameChange () [protected]
Called when the units menu name text field value is changed.
References EnableScaleFactor(), and OnChange().
MeaCustomUnitsPrefs::OnPixelBasis () [protected]
Called when the pixel-based scale factor radio button is selected.
References OnChange().
MeaCustomUnitsPrefs::OnPixelChange () [protected]
Called when the pixel-based scale factor text field value is changed.
References m_lockout, OnChange(), and SetCheck().
MeaCustomUnitsPrefs::OnPrecision () [protected]
Called when the Set Display Precision button is pressed.
Pressing this button makes the Precision property page active so that the precision can be set for the custom units.
References MeaAssert, and MeaPreferences::ShowCustomPrecision().
MeaCustomUnitsPrefs::OnSetActive () [virtual]
Called when the page becomes active.
This method ensures that the scale factor basis labels reflect the custom units abbreviation, if any.
Returns:
TRUE, indicating that the page is active.
References m_abbrevField, m_lockout, and OnAbbrevChange().
void MeaCustomUnitsPrefs::SetCheck (UINT buttonId) [private]
Ensures radio button behavior on the scale factor basis radio buttons.
The specified button is set and all other basis buttons are unset.
Parameters:
buttonId [in] ID for the radio button to set.
References m_cmButton, m_inButton, m_pxButton, and MeaAssert.
Referenced by OnCentimeterChange(), OnInchChange(), and OnPixelChange().
void MeaCustomUnitsPrefs::SetScaleFactor (MeaCustomUnits::ScaleBasis scaleBasis, double scaleFactor)
Sets the custom units basis and scale factor.
Parameters:
scaleBasis [in] Specifies whether the custom units are based on pixels, inches or centimeters.
scaleFactor [in] Conversion factor to/from scaleBasis to/from the custom units.
References MeaCustomUnits::CentimeterBasis, MeaCustomUnits::InchBasis, m_cmScaleFactor, m_inScaleFactor, m_pxScaleFactor, m_scaleBasis, MeaAssert, and MeaCustomUnits::PixelBasis.
Referenced by CChildView::OnPreferences().
bool MeaCustomUnitsPrefs::Validate () [private]
Validates the custom units data on the page.
The page data is considered valid either if both the name and abbrev. fields are empty, or if they both contain text and the scale factor is greater than 0.
Returns:
true if the page data is valid, and false if the data is invalid.
References MeaNumberField::GetValue(), m_abbrevField, m_cmScaleField, m_inScaleField, m_nameField, m_pxScaleField, and MeaAssert.
Referenced by OnApply(), and OnKillActive().
Member Data Documentation
MeaCustomUnitsPrefs::m_abbrev
Abbreviation for the custom units.
Referenced by CChildView::ApplyPreferences(), DoDataExchange(), OnClear(), and CChildView::OnPreferences().
MeaCustomUnitsPrefs::m_cmScaleFactor
Scale factor if the custom units are based on centimeters.
Referenced by DoDataExchange(), GetScaleFactor(), and SetScaleFactor().
MeaCustomUnitsPrefs::m_inScaleFactor
Scale factor if the custom units are based on inches.
Referenced by DoDataExchange(), GetScaleFactor(), and SetScaleFactor().
MeaCustomUnitsPrefs::m_name
Full name for the custom units.
Referenced by CChildView::ApplyPreferences(), DoDataExchange(), OnClear(), and CChildView::OnPreferences().
MeaCustomUnitsPrefs::m_pxScaleFactor
Scale factor if the custom units are based on pixels.
Referenced by DoDataExchange(), GetScaleFactor(), and SetScaleFactor().
MeaCustomUnitsPrefs::m_scaleBasis
Indicates whether the custom units are based on pixels, inches or centimeters.
Referenced by DoDataExchange(), GetScaleFactor(), and SetScaleFactor().
The documentation for this class was generated from the following files:
CustomUnitsPrefs.h
CustomUnitsPrefs.cpp
Copyright 2011 C Thing Software