Meazure: MeaRuler Class Reference
MeaRuler Class Reference
A ruler element.
#include <Ruler.h>
Public Types
enum IndicatorId {
Ind1 = 0 ,
Ind2 = 1 ,
Ind3 = 2
}
A ruler can display up to three position indicators.
enum Orientation {
Vertical ,
Horizontal
}
A ruler can be oriented vertically to measure along the height of the screen, or horizontally to measure along the width of the screen.
enum { NumIndicators = 3 }
Public Member Functions
MeaRuler ()
Constructs a ruler.
virtual ~MeaRuler ()
Destroys a ruler.
bool Create (COLORREF borderColor, COLORREF backColor, BYTE opacity, Orientation orientation, const CRect &targetRect, MeaRulerCallback *callback=NULL, const CWnd *parent=NULL, UINT id=0xffff)
Creates the window for the ruler.
void SetPosition (int position)
Sets the position of the ruler.
int GetPosition () const
Obtains the position of the ruler.
Orientation GetOrientation () const
Obtains the orientation of the ruler.
void SetIndicator (IndicatorId indId, int pixel)
Sets the position of the specified ruler indicator.
void ClearIndicator (IndicatorId indId)
Hides the specified position indicator.
void SetColors (COLORREF borderColor, COLORREF backColor)
Sets the colors for the ruler.
void SetOpacity (BYTE opacity)
Sets the opacity for the ruler.
void Update ()
Redraws the ruler.
Public Member Functions inherited from MeaGraphic
MeaGraphic ()
Base class constructor.
virtual ~MeaGraphic ()
Base class destructor.
bool Create (LPCTSTR classname, const SIZE &size, const CWnd *parent, UINT id=0xFFFF)
Creates the window for the graphic.
virtual void Show ()
Displays the graphic.
virtual void Hide ()
Hides the graphic.
void SetAbove (const CWnd *winBelow)
Changes the z-order of the graphic window so that it if above the specified window.
Protected Member Functions
afx_msg void OnDestroy ()
Called when the ruler window is about to be destroyed.
afx_msg void OnPaint ()
Called when the ruler needs repainting.
afx_msg void OnMouseMove (UINT flags, CPoint point)
Called when the ruler is dragged.
afx_msg void OnLButtonDown (UINT flags, CPoint point)
Called when the left mouse button is pressed while the pointer is over the ruler window.
afx_msg void OnLButtonUp (UINT flags, CPoint point)
Called when the left mouse button is released while the pointer is captured by the ruler window.
Private Types
enum LabelPosition {
Top ,
Bottom ,
Left ,
Right
}
Specifies the location of the ruler number labels.
Private Member Functions
void DrawIndicator (IndicatorId indId, CDC &dc)
Draws the specified position indicator on the ruler at the current position for that indicator.
void DrawRuler (CDC &dc)
Draws the ruler tick marks and number labels.
void FillInfo (MeaRulerCallback::RulerInfo &rulerInfo, UINT flags, const CPoint &point)
Fills the ruler information structure so that it can be passed to the callback method.
Private Attributes
COLORREF m_borderColor
Color for the ruler border and tick marks.
COLORREF m_backColor
Color for the ruler background.
SIZE m_majorTickHeight
Height of the major tick marks, in pixels.
SIZE m_minorTickHeight
Height of the minor tick marks, in pixels.
SIZE m_margin
Height spacing between tick marks, number label and border, in pixels.
MeaRulerCallback * m_callback
Object to be called on ruler drag.
Orientation m_orientation
Orientation of the rule (i.e. horizontal or vertical)
int m_position
Position of the ruler, in pixels.
CRect m_targetRect
Containment rectangle for the ruler.
LabelPosition m_labelPosition
Current location of the number labels.
CFont m_hFont
Font for horizontal ruler labels.
CFont m_vFont
Font for vertical ruler labels.
int m_fontHeight
Height of the current font, in pixels.
int m_thk
Thickness of the ruler (i.e. its minor dimension), in pixels.
int m_indicatorLoc [NumIndicators]
Location of each position indicator, in pixels.
bool m_mouseCaptured
Indicates whether the mouse is currently captured by the ruler window.
CSize m_pointerOffset
Offset between pointer position and ruler edge.
BYTE m_opacity
Current ruler opacity setting (0 - 255).
CDC m_rulerDC
Ruler device context.
CDC m_backDC
Background device context for alpha blending when the ruler is a child window.
CBitmap m_rulerBitmap
Bitmap into which to draw the ruler when it is a child window.
CBitmap * m_origRulerBitmap
Original bitmap for the ruler.
CBitmap m_backBitmap
Bitmap for the background when alpha blending when the ruler is a child window.
CBitmap * m_origBackBitmap
Original background bitmap.
Static Private Attributes
static const int kMinMajorTickHeight = 8
Minimum height of the major tick marks, in pixels.
static const double kMajorTickHeight = 0.08
Height of the major tick marks, in inches.
static const int kMinMinorTickHeight = 5
Minimum height of the minor tick marks, in pixels.
static const double kMinorTickHeight = 0.05
Height of the minor tick marks, in inches.
static const int kMinMargin = 1
Minimum label height margin, in pixels.
static const double kMargin = 0.01
Label height margin, in inches.
Additional Inherited Members
Protected Attributes inherited from MeaGraphic
UINT m_id
ID for the graphic.
bool m_visible
Indicates whether the graphic is shown or hidden.
const CWnd * m_parent
Graphic's parent window or NULL if graphic is a popup window.
Static Protected Attributes inherited from MeaGraphic
static const int kInitCoord = -1000
An arbitrary initial coordinate for placing new graphics.
Detailed Description
A ruler element.
The ruler resembles a classic measurement straight edge. The ruler can be oriented vertically to measure along the height of the screen or horizontally to measure along the width of the screen. A ruler can be positioned anywhere along the height or width of the screen. Using the MeaRulerCallback mixin, a class can provide dragging of the ruler.
Up to three position indicators can be displayed on the face of the ruler. These indicators are used by the MeaRulerTool to show the current position of crosshairs and other measurement points.
The MeaRulerTool uses one vertical and one horizontal ruler per monitor.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
NumIndicators
Maximum number of indicators.
IndicatorId
enum MeaRuler::IndicatorId
A ruler can display up to three position indicators.
An indicator is a line that can be moved along the ruler to show a position of interest. Each indicator is selected by an identifier.
Enumerator
Ind1
Identifier for indicator 1.
Ind2
Identifier for indicator 2.
Ind3
Identifier for indicator 3.
LabelPosition
enum MeaRuler::LabelPosition private
Specifies the location of the ruler number labels.
For horizontally oriented rulers, the labels may be position on the top or bottom relative to the tick marks. For vertical rulers, the labels may be positioned on the left or right relative to the tick marks. The positioning of the labels is determined automatically based on the position of the ruler on the screen. For example, a horizontal ruler located in the upper half of the screen has its labels positioned on the top, whereas the same ruler located in the lower half of the screen has labels on the bottom.
Enumerator
Top
Position number labels above the ruler tick marks.
Bottom
Position number labels below the ruler tick marks.
Left
Position number labels to the left of the ruler tick marks.
Right
Position number labels to the right of the ruler tick marks.
Orientation
enum MeaRuler::Orientation
A ruler can be oriented vertically to measure along the height of the screen, or horizontally to measure along the width of the screen.
Enumerator
Vertical
Orient the ruler vertically.
Horizontal
Orient the ruler horizontally.
Member Function Documentation
ClearIndicator()
void MeaRuler::ClearIndicator (IndicatorId indId)
Hides the specified position indicator.
Parameters
indId [in] Identifier of the indicator to be hidden.
References MeaScreenMgr::GetOffScreen(), MeaSingleton_T< MeaScreenMgr >::Instance(), and m_indicatorLoc.
Referenced by MeaRuler().
Create()
bool MeaRuler::Create (COLORREF borderColor, COLORREF backColor, BYTE opacity, Orientation orientation, const CRect & targetRect, MeaRulerCallback * callback = NULL, const CWnd * parent = NULL, UINT id = 0xffff)
Creates the window for the ruler.
This method must be called before the ruler can be displayed and before any operation that attempts to manipulate the ruler's window.
Parameters
borderColor [in] The color for the ruler border and tick lines.
backColor [in] Background color for the ruler.
opacity [in] Opacity value for the ruler expressed as a value between 0 (transparent) and 255 (opaque) inclusive.
orientation [in] Orientation of the ruler: vertical or horizontal.
targetRect [in] Containment rectangle for the ruler. The ruler's longest dimension will be sized to fit within this rectangle.
callback [in] A class derived from MeaRulerCallback that wants to receive notification of ruler movement. Can be set to NULL if no callback is desired.
parent [in] Parent window or NULL if the ruler does not have an immediate parent. If a parent window is specified, the ruler is created as a child window (WS_CHILD). Otherwise the ruler is created as a popup window (WS_POPUP) and is assigned the main window as a parent.
id [in] Caller-defined ID for the ruler.
Returns
true if the window is created successfully.
References MeaUnitsMgr::ConvertToPixels(), MeaGraphic::Create(), MeaLayout::DrawOpacityBackground(), MeaScreenMgr::GetScreenIter(), MeaScreenMgr::GetScreenRes(), HaveLayeredWindows(), Horizontal, MeaSingleton_T< MeaScreenMgr >::Instance(), MeaSingleton_T< MeaUnitsMgr >::Instance(), kMajorTickHeight, kMargin, kMinMajorTickHeight, kMinMargin, kMinMinorTickHeight, kMinorTickHeight, m_backBitmap, m_backDC, m_callback, m_fontHeight, m_hFont, m_majorTickHeight, m_margin, m_minorTickHeight, m_orientation, m_origBackBitmap, m_origRulerBitmap, MeaGraphic::m_parent, m_rulerBitmap, m_rulerDC, m_targetRect, m_thk, m_vFont, MeaInchesId, SetColors(), SetOpacity(), SetPosition(), and WS_EX_LAYERED.
Referenced by MeaRulerPrefs::OnInitDialog().
DrawIndicator()
void MeaRuler::DrawIndicator (IndicatorId indId, CDC & dc) private
Draws the specified position indicator on the ruler at the current position for that indicator.
Parameters
indId [in] Specifies the indicator to be drawn.
dc [in] Specifies the device context to use to draw the indicator.
References Horizontal, m_borderColor, m_indicatorLoc, m_orientation, MeaLayout::ScreenToClientX(), and MeaLayout::ScreenToClientY().
Referenced by DrawRuler(), and SetIndicator().
DrawRuler()
void MeaRuler::DrawRuler (CDC & dc) private
Draws the ruler tick marks and number labels.
Parameters
dc [in] Specifies the device context to use to draw the ruler.
References FSIZE::cx, FSIZE::cy, DrawIndicator(), MeaUnitsMgr::Format(), MeaUnitsMgr::GetLinearUnits(), MeaLinearUnits::GetMajorTickCount(), MeaLinearUnits::GetMinorIncr(), MeaScreenMgr::GetVirtualRect(), MeaSingleton_T< MeaScreenMgr >::Instance(), MeaSingleton_T< MeaUnitsMgr >::Instance(), MeaColors::InterpolateColor(), Left, m_backColor, m_borderColor, m_hFont, m_labelPosition, m_majorTickHeight, m_margin, m_minorTickHeight, m_vFont, MeaConvertX, MeaConvertY, MeaX, MeaY, NumIndicators, Right, MeaLayout::ScreenToClientX(), MeaLayout::ScreenToClientY(), Top, and MeaLinearUnits::UnconvertCoord().
Referenced by OnPaint().
FillInfo()
void MeaRuler::FillInfo (MeaRulerCallback::RulerInfo & rulerInfo, UINT flags, const CPoint & point) private
Fills the ruler information structure so that it can be passed to the callback method.
Parameters
rulerInfo [in] Ruler information structure to be filled.
flags [in] Virtual key flags including modifier keys (e.g. MK_CONTROL, MK_SHIFT).
point [in] Location of the mouse pointer, in pixels.
References MeaRulerCallback::RulerInfo::flags, MeaRulerCallback::RulerInfo::id, MeaSingleton_T< MeaScreenMgr >::Instance(), MeaScreenMgr::LimitPosition(), MeaGraphic::m_id, m_orientation, m_pointerOffset, MeaRulerCallback::RulerInfo::position, MeaRulerCallback::RulerInfo::ruler, and Vertical.
Referenced by OnMouseMove().
GetOrientation()
Orientation MeaRuler::GetOrientation () const inline
Obtains the orientation of the ruler.
Returns
The ruler is either vertically or horizontally oriented.
References m_orientation.
Referenced by MeaRulerTool::OnRulerMove().
GetPosition()
int MeaRuler::GetPosition () const inline
Obtains the position of the ruler.
Returns
Location of the ruler, in pixels. If the ruler is oriented vertically, the location of the left side of the ruler is returned. If the ruler is horizontal, the location of the top of the ruler is returned.
References m_position.
Referenced by MeaRulerTool::SaveProfile().
OnDestroy()
void MeaRuler::OnDestroy () protected
Called when the ruler window is about to be destroyed.
If the ruler was created with a parent window specified, a number of bitmaps were created to simulate an opacity effect. This method deletes those bitmaps.
References m_backBitmap, m_backDC, m_hFont, m_origBackBitmap, m_origRulerBitmap, m_rulerBitmap, m_rulerDC, and m_vFont.
OnLButtonDown()
void MeaRuler::OnLButtonDown (UINT flags, CPoint point) protected
Called when the left mouse button is pressed while the pointer is over the ruler window.
Parameters
flags [in] Virtual key state
point [in] Location of the pointer, in pixels
References m_mouseCaptured, and m_pointerOffset.
OnLButtonUp()
void MeaRuler::OnLButtonUp (UINT flags, CPoint point) protected
Called when the left mouse button is released while the pointer is captured by the ruler window.
Parameters
flags [in] Virtual key state
point [in] Location of the pointer, in pixels
References m_mouseCaptured.
OnMouseMove()
void MeaRuler::OnMouseMove (UINT flags, CPoint point) protected
Called when the ruler is dragged.
The method initializes the ruler information structure and calls the callback MeaRulerCallback::OnRulerMove method, if a callback has been specified.
Parameters
flags [in] Virtual key state
point [in] Location of the pointer, in pixels
References FillInfo(), m_callback, m_mouseCaptured, and MeaRulerCallback::OnRulerMove().
SetColors()
void MeaRuler::SetColors (COLORREF borderColor, COLORREF backColor)
Sets the colors for the ruler.
Parameters
borderColor [in] Color for the ruler border and tick lines
backColor [in] Background color for the ruler
References m_backColor, m_borderColor, and Update().
Referenced by MeaRulerPrefs::ColorsChanged(), and Create().
SetIndicator()
void MeaRuler::SetIndicator (IndicatorId indId, int pixel)
Sets the position of the specified ruler indicator.
Up to three position indicators can be displayed on the face of the ruler. These indicators are used by the MeaRulerTool to show the current position of crosshairs and other measurement points. Specifying a position for an indicator displays that indicator. To hide an indicator call ClearIndicator().
Parameters
indId [in] Identifier of the indicator whose position is to be set.
pixel [in] Position for the indicator, in pixels.
References DrawIndicator(), and m_indicatorLoc.
SetOpacity()
void MeaRuler::SetOpacity (BYTE opacity)
Sets the opacity for the ruler.
Parameters
opacity [in] Opacity value between 0 (transparent) and 255 (opaque) inclusive
References LWA_ALPHA, m_opacity, MeaGraphic::m_parent, SetLayeredWindowAttributes, and Update().
Referenced by Create(), MeaRulerPrefs::OnHScroll(), and MeaRulerPrefs::OnInitDialog().
SetPosition()
void MeaRuler::SetPosition (int position)
Sets the position of the ruler.
Parameters
position [in] Location for the ruler, in pixels. If the ruler is oriented vertically, the position parameter specifies the location of the left side of the ruler. If the ruler is horizontal, the position parameter specified the location of the top of the ruler.
References Bottom, Horizontal, Left, m_labelPosition, m_orientation, m_position, m_targetRect, m_thk, Right, Top, and Vertical.
Referenced by Create(), MeaRulerPrefs::OnInitDialog(), and MeaRulerTool::OnRulerMove().
Member Data Documentation
m_targetRect
CRect MeaRuler::m_targetRect private
Containment rectangle for the ruler.
The ruler's longest dimension will be sized to fit within this rectangle.
Referenced by Create(), and SetPosition().
The documentation for this class was generated from the following files:
Ruler.h
Ruler.cpp
Copyright 2011 C Thing Software