Meazure: MeaAngularUnits Class Reference
MeaAngularUnits Class Reference abstract
There are two major categories of units: linear and angular.
#include <Units.h>
Public Member Functions
MeaAngularUnitsId GetUnitsId () const
Returns the identifier for the angular units.
CString Format (MeaAngularMeasurementId id, double value) const
Formats the specified angular measurement value using the precision for the specified measurement ID.
virtual double ConvertAngle (double angle) const =0
Converts the specified angle value from its native radians to the desired units.
Public Member Functions inherited from MeaUnits
virtual void SaveProfile (MeaProfile &profile)
Persists the state of a units class instance to the specified profile object.
virtual void LoadProfile (MeaProfile &profile)
Restores the state of a units class instance from the specified profile object.
void SavePrecision (MeaProfile &profile)
Persists the measurement precisions to the specified profile object.
void LoadPrecision (MeaProfile &profile)
Restores the measurement precisions from the specified profile object.
virtual void MasterReset ()
Called to restores the units to their default state.
CString GetUnitsStr () const
Returns a string describing the units.
void SetDisplayPrecisions (const DisplayPrecisions &displayPrecisions)
Sets the decimal place precisions for all measurement types.
const DisplayPrecisions & GetDisplayPrecisions () const
Returns the current decimal place precisions for all measurement types.
const DisplayPrecisions & GetDefaultPrecisions () const
Returns the default decimal place precisions for all measurement types.
void RestoreDefaultPrecisions ()
Sets the default display precisions as the current precisions.
const DisplayPrecisionNames & GetDisplayPrecisionNames () const
Returns the identifying names for the display precisions.
Protected Member Functions
MeaAngularUnits (MeaAngularUnitsId unitsId, LPCTSTR unitsStr)
Constructs an angular-based unit.
virtual ~MeaAngularUnits ()
Destroys an angular-based unit.
Protected Member Functions inherited from MeaUnits
MeaUnits (LPCTSTR unitsStr)
Base class constructor.
virtual ~MeaUnits ()
Base class destructor.
void AddPrecisionName (LPCTSTR name)
Adds the specified identifying name to the list of precision names.
void AddPrecision (int precision)
Adds the specified precision value to both the list of current precisions and the list of default precisions.
Private Attributes
MeaAngularUnitsId m_unitsId
Identifier for the units.
Additional Inherited Members
Public Types inherited from MeaUnits
typedef std::vector< int > DisplayPrecisions
Number of decimal places to display for each type of measurement.
typedef std::vector< CString > DisplayPrecisionNames
Strings to identify units precisions in profiles.
Static Public Attributes inherited from MeaUnits
static const double kPI = 3.14159265359
The value of pi.
Detailed Description
There are two major categories of units: linear and angular.
The angular units cover the angle measurement units. This is the base class for all angular units.
Constructor & Destructor Documentation
MeaAngularUnits()
MeaAngularUnits::MeaAngularUnits (MeaAngularUnitsId unitsId, LPCTSTR unitsStr) protected
Constructs an angular-based unit.
Parameters
unitsId [in] Identifier for the angular units.
unitsStr [in] Name for the units.
References MeaUnits::AddPrecisionName().
Member Function Documentation
ConvertAngle()
virtual double MeaAngularUnits::ConvertAngle (double angle) const pure virtual
Converts the specified angle value from its native radians to the desired units.
Parameters
angle [in] Value to be converted.
Returns
Angle value converted to the desired units.
Implemented in MeaDegreeUnits, and MeaRadianUnits.
Referenced by MeaUnitsMgr::ConvertAngle().
Format()
CString MeaAngularUnits::Format (MeaAngularMeasurementId id, double value) const
Formats the specified angular measurement value using the precision for the specified measurement ID.
Parameters
id [in] Identifier for the angular units whose precision is to be used to format the specified value.
value [in] Measurement value to be formatted.
Returns
Measurement value formatted with the appropriate precision and returned as a string.
References MeaUnits::GetDisplayPrecisions().
Referenced by MeaUnitsMgr::Format().
GetUnitsId()
MeaAngularUnitsId MeaAngularUnits::GetUnitsId () const inline
Returns the identifier for the angular units.
Returns
Angular units ID.
References m_unitsId.
Referenced by MeaDataDisplay::DataItem::CreateAngleUnits(), and MeaUnitsMgr::GetAngularUnitsId().
The documentation for this class was generated from the following files:
Units.h
Units.cpp
Copyright 2011 C Thing Software