Meazure: MeaDataDisplay::DataItem Class Reference
MeaDataDisplay::DataItem Class Reference
Each data display field is actually composed of a label, a text field, possibly a spin control, and usually a units label.
Public Member Functions
DataItem ()
Constructs a data item.
~DataItem ()
Destroys a data item.
bool CreateField (UINT labelId, int numChars, CWnd *parentWnd, MeaFields fieldId, int spinId=0xFFFF)
Creates a labeled text entry field optionally with a spin button control and units label.
bool CreateSpinButton (CWnd *parentWnd, MeaFields id)
Creates a spin button control associated with the text field.
bool CreateLengthUnits (const MeaLinearUnits *units, CWnd *parentWnd)
Creates a linear units label.
bool CreateAngleUnits (const MeaAngularUnits *units, CWnd *parentWnd)
Creates an angular units label.
bool CreateAreaUnits (const MeaLinearUnits *units, CWnd *parentWnd)
Creates an area units label.
bool CreateResUnits (const MeaLinearUnits *units, CWnd *parentWnd)
Creates a resolution units label.
void Enable (bool enable)
Enables/disables all elements of the data item.
void SetReadOnly (bool readonly)
Controls whether the data item text field is editable or read-only.
void SetText (LPCTSTR text)
Displays the specified text in the data item's text field.
double GetValue () const
Returns the contents of the data item's text field converted to a double precision floating point value.
void SetLimitText (UINT numChars)
Sets the maximum number of characters allowed in the data item's text field.
void SetSpinRange (int lower, int upper)
Sets the upper and lower bounds of the spin control value.
void SetSpinPos (int pos)
Sets a value for the spin control.
const MeaLabel & GetTitleLabel () const
Returns the label object for the data item.
MeaNumberField & GetField ()
Returns the text field object for the data item.
CSpinButtonCtrl & GetSpin ()
Returns the spin control associated with the text field.
MeaUnitsLabel & GetUnitsLabel ()
Returns the units label object associated with the text field.
Private Attributes
MeaLabel m_titleLabel
Left side label for the data item.
MeaNumberField m_field
Data item's text field.
CSpinButtonCtrl * m_spin
Spin control associated with the text field or NULL if no spin control for this data item.
MeaUnitsLabel * m_unitsLabel
Units label or NULL if no units label for this data item.
Static Private Attributes
static const int kSpinWidth = 17
Width for the spin control, in pixels.
Detailed Description
Each data display field is actually composed of a label, a text field, possibly a spin control, and usually a units label.
This class packages all these pieces into a single data item component. This eases the burden and reduces the potential for code duplication for the data display class.
Constructor & Destructor Documentation
MeaDataDisplay::DataItem::DataItem () [inline]
Constructs a data item.
To complete the data item for use, the appropriate set of Create* methods must be called.
Member Function Documentation
bool MeaDataDisplay::DataItem::CreateAngleUnits (const MeaAngularUnits * units, CWnd * parentWnd) [inline]
Creates an angular units label.
Parameters:
units [in] Object representing the angular units for the label.
parentWnd [in] Parent window for the label.
Returns:
true if creation succeeded.
References MeaUnitsLabel::Create(), MeaAngularUnits::GetUnitsId(), MeaSingleton_T< MeaUnitsMgr >::Instance(), and MeaUnitsMgr::NewAngleUnitsLabel().
Referenced by MeaDataDisplay::CreateRegionSection().
bool MeaDataDisplay::DataItem::CreateAreaUnits (const MeaLinearUnits * units, CWnd * parentWnd) [inline]
Creates an area units label.
Parameters:
units [in] Object representing the area units for the label.
parentWnd [in] Parent window for the label.
Returns:
true if creation succeeded.
References MeaUnitsLabel::Create(), MeaLinearUnits::GetUnitsId(), MeaSingleton_T< MeaUnitsMgr >::Instance(), and MeaUnitsMgr::NewAreaUnitsLabel().
Referenced by MeaDataDisplay::CreateRegionSection().
bool MeaDataDisplay::DataItem::CreateField (UINT labelId, int numChars, CWnd * parentWnd, MeaFields fieldId, int spinId = 0xFFFF)
Creates a labeled text entry field optionally with a spin button control and units label.
Parameters:
labelId [in] String resource ID for the field label.
numChars [in] Number of characters the field is to display.
parentWnd [in] Parent for the field and its controls.
fieldId [in] ID for the text field.
spinId [in] ID for the spin control.
Returns:
true if creation succeeds.
References MeaLabel::Create(), MeaNumberField::Create(), CreateSpinButton(), m_field, and m_titleLabel.
Referenced by MeaDataDisplay::CreateRegionSection(), and MeaDataDisplay::CreateScreenSection().
bool MeaDataDisplay::DataItem::CreateLengthUnits (const MeaLinearUnits * units, CWnd * parentWnd) [inline]
Creates a linear units label.
Parameters:
units [in] Object representing the linear units for the label.
parentWnd [in] Parent window for the label.
Returns:
true if creation succeeded.
References MeaUnitsLabel::Create(), MeaLinearUnits::GetUnitsId(), MeaSingleton_T< MeaUnitsMgr >::Instance(), and MeaUnitsMgr::NewLengthUnitsLabel().
Referenced by MeaDataDisplay::CreateRegionSection(), and MeaDataDisplay::CreateScreenSection().
bool MeaDataDisplay::DataItem::CreateResUnits (const MeaLinearUnits * units, CWnd * parentWnd) [inline]
Creates a resolution units label.
Parameters:
units [in] Object representing the resolution units for the label.
parentWnd [in] Parent window for the label.
Returns:
true if creation succeeded.
References MeaUnitsLabel::Create(), MeaLinearUnits::GetUnitsId(), MeaSingleton_T< MeaUnitsMgr >::Instance(), and MeaUnitsMgr::NewResUnitsLabel().
Referenced by MeaDataDisplay::CreateScreenSection().
bool MeaDataDisplay::DataItem::CreateSpinButton (CWnd * parentWnd, MeaFields id)
Creates a spin button control associated with the text field.
Parameters:
parentWnd [in] Parent window for the spin button.
id [in] ID for the spin control.
Returns:
true if creation succeeded.
References MeaLayout::SetWindowSize().
Referenced by CreateField().
void MeaDataDisplay::DataItem::Enable (bool enable)
Enables/disables all elements of the data item.
Parameters:
enable [in] Indicates whether the data item should be enabled or disabled.
Referenced by MeaDataDisplay::EnableRegionFields(), and MeaDataDisplay::EnableScreenFields().
MeaNumberField& MeaDataDisplay::DataItem::GetField () [inline]
Returns the text field object for the data item.
Returns:
Text field object.
Referenced by MeaDataDisplay::CreateRegionSection(), MeaDataDisplay::CreateScreenSection(), and MeaDataDisplay::OnFieldEntry().
CSpinButtonCtrl& MeaDataDisplay::DataItem::GetSpin () [inline]
Returns the spin control associated with the text field.
Returns:
Spin control.
References MeaAssert.
Referenced by MeaDataDisplay::CreateRegionSection().
const MeaLabel& MeaDataDisplay::DataItem::GetTitleLabel () const [inline]
Returns the label object for the data item.
The label is displayed to the left of the text field.
Returns:
Label object.
Referenced by MeaDataDisplay::CreateRegionSection(), and MeaDataDisplay::CreateScreenSection().
MeaUnitsLabel& MeaDataDisplay::DataItem::GetUnitsLabel () [inline]
Returns the units label object associated with the text field.
The units are displayed to the right of the text field.
Returns:
Units label object.
References MeaAssert.
Referenced by MeaDataDisplay::CreateRegionSection(), and MeaDataDisplay::CreateScreenSection().
double MeaDataDisplay::DataItem::GetValue () const [inline]
Returns the contents of the data item's text field converted to a double precision floating point value.
Returns:
Contents of the text field converted to a double precision floating point value.
Referenced by MeaDataDisplay::OnFieldEntry().
void MeaDataDisplay::DataItem::SetLimitText (UINT numChars) [inline]
Sets the maximum number of characters allowed in the data item's text field.
Parameters:
numChars [in] Maximum number of characters allowed in the text field.
Referenced by MeaDataDisplay::CreateRegionSection().
void MeaDataDisplay::DataItem::SetReadOnly (bool readonly) [inline]
Controls whether the data item text field is editable or read-only.
Parameters:
readonly [in] true if the text field should be read-only.
Referenced by MeaDataDisplay::EnableRegionFields(), and MeaDataDisplay::EnableScreenFields().
void MeaDataDisplay::DataItem::SetSpinPos (int pos) [inline]
Sets a value for the spin control.
Note that the spin control can only take integer values.
Parameters:
pos [in] Value for the spin control.
Referenced by MeaDataDisplay::ShowXY1(), MeaDataDisplay::ShowXY2(), and MeaDataDisplay::ShowXYV().
void MeaDataDisplay::DataItem::SetSpinRange (int lower, int upper) [inline]
Sets the upper and lower bounds of the spin control value.
Note that the spin control can only take integer values. This means that the spin controls are not useful for fractional units adjustment.
Parameters:
lower [in] Minimum spin control value, inclusive.
upper [in] Upper spin control value, inclusive.
Referenced by MeaDataDisplay::CreateRegionSection().
void MeaDataDisplay::DataItem::SetText (LPCTSTR text) [inline]
Displays the specified text in the data item's text field.
Parameters:
text [in] Text to display.
Referenced by MeaDataDisplay::ClearRegionData(), MeaDataDisplay::ShowAngle(), MeaDataDisplay::ShowCircleArea(), MeaDataDisplay::ShowDistance(), MeaDataDisplay::ShowRectArea(), MeaDataDisplay::ShowScreenRes(), MeaDataDisplay::ShowScreenWH(), MeaDataDisplay::ShowWH(), MeaDataDisplay::ShowXY1(), MeaDataDisplay::ShowXY2(), and MeaDataDisplay::ShowXYV().
Member Data Documentation
CSpinButtonCtrl* MeaDataDisplay::DataItem::m_spin [private]
Spin control associated with the text field or NULL if no spin control for this data item.
MeaUnitsLabel* MeaDataDisplay::DataItem::m_unitsLabel [private]
Units label or NULL if no units label for this data item.
The documentation for this class was generated from the following files:
DataDisplay.h
DataDisplay.cpp
Copyright 2011 C Thing Software