Meazure: ev::AttributeDecl Class Reference
ev::AttributeDecl Class Reference
Represents an attribute declaration.
Public Types
enum Type {
Enumerated ,
CDATA ,
ENTITY ,
ENTITIES ,
ID ,
IDREF ,
IDREFS ,
NMTOKEN ,
NMTOKENS ,
NOTATION
}
Attribute value type.
Public Member Functions
AttributeDecl (ElementDecl &elementDecl, const XML_Char *attrName, const XML_Char *attrType, const XML_Char *defValue, bool isRequired)
Constructs an attribute declaration.
virtual ~AttributeDecl ()
Destroys an attribute declaration.
EVString GetName () const
Returns the name of the attribute.
Type GetType () const
Returns the type of the attribute's value.
bool IsEnumValue (const XML_Char *evalue) const
Tests whether the specified value is one of the enumeration values for an enumerated attribute.
bool HasDefault () const
Indicates whether the attribute has a default value.
EVString GetDefault () const
Returns the default value for the attribute.
bool IsRequired () const
Indicates if the attribute is required.
bool IsFixed () const
Indicates if the attribute is required and has only one value.
Protected Types
typedef std::set< EVString > ValueSet
If the attribute is enumerated, these are the possible values for the enumeration.
typedef ValueSet::iterator ValueIter
Iterator over the attribute's values.
typedef ValueSet::const_iterator ValueIter_c
Constant iterator over the attribute's values.
Protected Member Functions
AttributeDecl (const AttributeDecl &decl)
Purposely undefined.
AttributeDecl & operator= (const AttributeDecl &decl)
Purposely undefined.
void ParseValues (const XML_Char *valueStr)
Parses enumerated attribute values: (val1|val2|val3) and stores them in an internal set of values.
Protected Attributes
ElementDecl & m_elementDecl
Parent element's declaration.
EVString m_name
Attribute name.
EVString m_defValue
Default value, if any.
Type m_type
Attribute value type.
ValueSet m_values
Set of enumeration values.
bool m_required
Indicates if the attribute is required.
Friends
EVOstream & operator<< (EVOstream &stream, const AttributeDecl *attributeDecl)
Output stream operator for an attribute declaration.
Detailed Description
Represents an attribute declaration.
Member Enumeration Documentation
Type
enum ev::AttributeDecl::Type
Attribute value type.
Enumerator
Enumerated
Enumeration.
CDATA
Character data.
ENTITY
Entity reference.
ENTITIES
List of entity references.
ID
Unique identifier.
IDREF
Reference to a unique identifier.
IDREFS
List of references to a unique identifier.
NMTOKEN
Name token.
NMTOKENS
List of name tokens.
NOTATION
Notation reference.
Constructor & Destructor Documentation
AttributeDecl()
AttributeDecl::AttributeDecl (ElementDecl & elementDecl, const XML_Char * attrName, const XML_Char * attrType, const XML_Char * defValue, bool isRequired)
Constructs an attribute declaration.
Parameters
elementDecl [in] Parent element's declaration.
attrName [in] Name of the attribute being declared.
attrType [in] Type of the attribute's value.
defValue [in] Default value for the attribute or NULL if no default.
isRequired [in] Indicates if the attribute must be specified with the element.
References CDATA, ENTITIES, ENTITY, Enumerated, EV_T, ID, IDREF, IDREFS, m_type, MeaAssert, NMTOKEN, NMTOKENS, NOTATION, and ParseValues().
Member Function Documentation
GetDefault()
EVString ev::AttributeDecl::GetDefault () const inline
Returns the default value for the attribute.
Returns
Default value for the attribute or the empty string if there is no default value.
References m_defValue.
Referenced by ev::Validator::StartElement().
GetName()
EVString ev::AttributeDecl::GetName () const inline
Returns the name of the attribute.
Returns
Name of the attribute being declared.
References m_name.
GetType()
Type ev::AttributeDecl::GetType () const inline
Returns the type of the attribute's value.
Returns
Type of the attribute's value.
References m_type.
Referenced by ev::Validator::StartElement().
HasDefault()
bool ev::AttributeDecl::HasDefault () const inline
Indicates whether the attribute has a default value.
Returns
true if the attribute has a default value.
References m_defValue.
IsEnumValue()
bool ev::AttributeDecl::IsEnumValue (const XML_Char * evalue) const inline
Tests whether the specified value is one of the enumeration values for an enumerated attribute.
Parameters
evalue [in] Value to test
Returns
true if the value is a member of the enumeration set.
References m_values.
Referenced by ev::Validator::StartElement().
IsFixed()
bool ev::AttributeDecl::IsFixed () const inline
Indicates if the attribute is required and has only one value.
Returns
true if the attribute is required and its value is fixed.
References m_defValue, and m_required.
Referenced by ev::Validator::StartElement().
IsRequired()
bool ev::AttributeDecl::IsRequired () const inline
Indicates if the attribute is required.
Returns
true if the attribute is required.
References m_defValue, and m_required.
Referenced by ev::ElementDecl::AddAttributeDecl().
ParseValues()
void AttributeDecl::ParseValues (const XML_Char * valueStr) protected
Parses enumerated attribute values: (val1|val2|val3) and stores them in an internal set of values.
Parameters
valueStr [in] Value string to parse.
References EV_T, and m_values.
Referenced by AttributeDecl().
Friends And Related Function Documentation
operator<<
EVOstream & operator<< (EVOstream & stream, const AttributeDecl * attributeDecl) friend
Output stream operator for an attribute declaration.
Used to dump the state of the attribute declaration to the specified output stream for debugging purposes.
Parameters
stream [in] Output stream.
attributeDecl [in] Attribute declaration to output.
Returns
Output stream.
The documentation for this class was generated from the following file:
exval.cpp
Copyright 2011 C Thing Software