Meazure: MeaPositionLogDlg Class Reference
MeaPositionLogDlg Class Reference
A non-modal dialog for recording new positions and managing positions that have already been recorded.
#include <PositionLogDlg.h>
Public Types
enum { IDD = IDD_POSITION_MGR }
Public Member Functions
MeaPositionLogDlg ()
Constructs the position manager dialog.
virtual ~MeaPositionLogDlg ()
Destroys the dialog.
BOOL Create ()
Creates the window for the dialog.
virtual void LogLoaded ()
Called when a position log file is loaded.
virtual void LogSaved ()
Called when a position log file is saved.
virtual void PositionAdded (int posIndex)
Called when a new position is recorded.
virtual void PositionReplaced (int posIndex)
Called when an existing position is replaced with a new position.
virtual void PositionDeleted (int posIndex)
Called when a position is deleted.
virtual void PositionsDeleted ()
Called when all recorded positions have been deleted.
virtual BOOL PreTranslateMessage (MSG *pMsg)
Called to preprocess windows messages.
virtual BOOL OnInitDialog ()
Called right before the dialog is displayed.
Public Member Functions inherited from MeaPositionLogObserver
MeaPositionLogObserver ()
Interface does nothing in a constructor.
virtual ~MeaPositionLogObserver ()
Interface does nothing in a destructor.
virtual void LogLoaded ()=0
Called when a position log file is loaded.
virtual void LogSaved ()=0
Called when a position log file is saved.
virtual void PositionAdded (int posIndex)=0
Called when a new position is recorded.
virtual void PositionReplaced (int posIndex)=0
Called when an existing position is replaced with a new position.
virtual void PositionDeleted (int posIndex)=0
Called when a position is deleted.
virtual void PositionsDeleted ()=0
Called when all recorded positions have been deleted.
Protected Member Functions
afx_msg void OnAddPosition ()
Called when the Add position button is pressed.
afx_msg void OnDeletePositions ()
Called when the Delete All positions button is pressed.
afx_msg void OnDeletePosition ()
Called when the Delete position button is pressed.
afx_msg void OnReplacePosition ()
Called when the Replace button is pressed.
afx_msg void OnHScroll (UINT nSBCode, UINT nPos, CScrollBar *pScrollBar)
Called when the position scrollbar is moved.
afx_msg void OnKillfocusPositionDesc ()
Called when the position description field loses the keyboard focus.
afx_msg void OnLoadPositions ()
Called when the Load button is pressed.
afx_msg void OnSavePositions ()
Called when the Save button is pressed.
afx_msg void OnSavePositionsAs ()
Called when the Save As button is pressed.
virtual void OnCancel ()
Called when the dialog Close button is pressed.
virtual void PostNcDestroy ()
Called after the non-client area of the dialog is destroyed.
void SetDlgTitle ()
Sets the dialog title with the currently opened position filename.
int GetScrollPos () const
Returns the scrollbar value which is the position list index.
void SetScrollPos (int pos) const
Sets the scrollbar value which is the position list index.
void SetScrollRange () const
Sets the range for the position list scrollbar.
void UpdatePositionInfo (int posIndex=-1) const
Update the position number field, the recorded date field and the description field.
void UpdateEnable () const
Enables/disables the dialog controls based on the current state of the position manager.
Detailed Description
A non-modal dialog for recording new positions and managing positions that have already been recorded.
Besides recording positions, the dialog allows individual positions to be deleted, replaced, and annotated.
This class is an observer of the position log manager. This allows the dialog to be called when positions are recorded, deleted, loaded or saved.
Constructor & Destructor Documentation
MeaPositionLogDlg()
MeaPositionLogDlg::MeaPositionLogDlg ()
Constructs the position manager dialog.
Since this is a non-modal dialog, its Create method is called followed by a call to ShowWindow.
Member Function Documentation
Create()
BOOL MeaPositionLogDlg::Create () inline
Creates the window for the dialog.
Returns
TRUE if the window was created successfully.
Referenced by MeaPositionLogMgr::ManagePositions().
GetScrollPos()
int MeaPositionLogDlg::GetScrollPos () const protected
Returns the scrollbar value which is the position list index.
Returns
Scrollbar position.
References GetScrollPos().
Referenced by GetScrollPos(), OnDeletePosition(), OnKillfocusPositionDesc(), OnReplacePosition(), and UpdatePositionInfo().
LogLoaded()
void MeaPositionLogDlg::LogLoaded () virtual
Called when a position log file is loaded.
Implements MeaPositionLogObserver.
References MeaSingleton_T< MeaPositionLogMgr >::Instance(), SetDlgTitle(), SetScrollPos(), SetScrollRange(), MeaPositionLogMgr::ShowPosition(), UpdateEnable(), and UpdatePositionInfo().
LogSaved()
void MeaPositionLogDlg::LogSaved () virtual
Called when a position log file is saved.
Implements MeaPositionLogObserver.
References SetDlgTitle().
OnAddPosition()
MeaPositionLogDlg::OnAddPosition () protected
Called when the Add position button is pressed.
Records the current tool positions.
References MeaSingleton_T< MeaPositionLogMgr >::Instance(), and MeaPositionLogMgr::RecordPosition().
OnCancel()
void MeaPositionLogDlg::OnCancel () protected virtual
Called when the dialog Close button is pressed.
This method destroys the dialog's window.
OnDeletePosition()
MeaPositionLogDlg::OnDeletePosition () protected
Called when the Delete position button is pressed.
Deletes the position corresponding to the position scrollbar.
References MeaPositionLogMgr::DeletePosition(), GetScrollPos(), and MeaSingleton_T< MeaPositionLogMgr >::Instance().
OnDeletePositions()
MeaPositionLogDlg::OnDeletePositions () protected
Called when the Delete All positions button is pressed.
Deletes all positions.
References MeaPositionLogMgr::DeletePositions(), and MeaSingleton_T< MeaPositionLogMgr >::Instance().
OnHScroll()
MeaPositionLogDlg::OnHScroll (UINT nSBCode, UINT nPos, CScrollBar * pScrollBar) protected
Called when the position scrollbar is moved.
Parameters
nSBCode [in] Trackbar code.
nPos [in] Position value.
pScrollBar [in] Scrollbar control object.
References MeaSingleton_T< MeaPositionLogMgr >::Instance(), SetScrollPos(), MeaPositionLogMgr::ShowPosition(), and UpdatePositionInfo().
OnInitDialog()
MeaPositionLogDlg::OnInitDialog () virtual
Called right before the dialog is displayed.
Sets the state of all UI controls.
Returns
TRUE to continue the display of the dialog.
References MeaSingleton_T< MeaPositionLogMgr >::Instance(), SetDlgTitle(), MeaPositionLogMgr::SetObserver(), SetScrollPos(), SetScrollRange(), MeaPositionLogMgr::ShowPosition(), UpdateEnable(), and UpdatePositionInfo().
OnKillfocusPositionDesc()
MeaPositionLogDlg::OnKillfocusPositionDesc () protected
Called when the position description field loses the keyboard focus.
If the text in the field differs from that in the current position, it is entered into the position object.
References MeaPositionLogMgr::Position::GetDesc(), MeaPositionLogMgr::GetPosition(), GetScrollPos(), MeaPositionLogMgr::HavePositions(), MeaSingleton_T< MeaPositionLogMgr >::Instance(), and MeaPositionLogMgr::Position::SetDesc().
OnLoadPositions()
MeaPositionLogDlg::OnLoadPositions () protected
Called when the Load button is pressed.
Queries the user for the position log file to load.
References MeaSingleton_T< MeaPositionLogMgr >::Instance(), and MeaPositionLogMgr::Load().
OnReplacePosition()
MeaPositionLogDlg::OnReplacePosition () protected
Called when the Replace button is pressed.
The current scrollbar position is replaced with the current radio tool position.
References GetScrollPos(), MeaSingleton_T< MeaPositionLogMgr >::Instance(), and MeaPositionLogMgr::ReplacePosition().
OnSavePositions()
MeaPositionLogDlg::OnSavePositions () protected
Called when the Save button is pressed.
Saves the position log file to the current pathname or queries for a pathname.
References MeaSingleton_T< MeaPositionLogMgr >::Instance(), and MeaPositionLogMgr::Save().
OnSavePositionsAs()
MeaPositionLogDlg::OnSavePositionsAs () protected
Called when the Save As button is pressed.
Queries for a pathname and saves the position log file to that pathname.
References MeaSingleton_T< MeaPositionLogMgr >::Instance(), and MeaPositionLogMgr::Save().
PositionAdded()
void MeaPositionLogDlg::PositionAdded (int posIndex) virtual
Called when a new position is recorded.
Parameters
posIndex [in] Index of the new position.
Implements MeaPositionLogObserver.
References MeaSingleton_T< MeaPositionLogMgr >::Instance(), SetScrollPos(), SetScrollRange(), UpdateEnable(), and UpdatePositionInfo().
PositionDeleted()
void MeaPositionLogDlg::PositionDeleted (int posIndex) virtual
Called when a position is deleted.
Parameters
posIndex [in] Index of the deleted position.
Implements MeaPositionLogObserver.
References SetScrollRange(), UpdateEnable(), and UpdatePositionInfo().
PositionReplaced()
void MeaPositionLogDlg::PositionReplaced (int posIndex) virtual
Called when an existing position is replaced with a new position.
Parameters
posIndex [in] Index of the replaced position.
Implements MeaPositionLogObserver.
References UpdatePositionInfo().
PositionsDeleted()
void MeaPositionLogDlg::PositionsDeleted () virtual
Called when all recorded positions have been deleted.
Implements MeaPositionLogObserver.
References SetScrollRange(), and UpdateEnable().
PostNcDestroy()
void MeaPositionLogDlg::PostNcDestroy () protected virtual
Called after the non-client area of the dialog is destroyed.
This is the last step in dialog destruction and is the place where a non-modal dialog class instance can be deleted.
References MeaSingleton_T< MeaPositionLogMgr >::Instance(), MeaSingleton_T< MeaPositionLogMgr >::IsDestroyed(), MeaPositionLogMgr::ManageDlgDestroyed(), and MeaPositionLogMgr::SetObserver().
PreTranslateMessage()
BOOL MeaPositionLogDlg::PreTranslateMessage (MSG * pMsg) virtual
Called to preprocess windows messages.
This override allows accelerators to be processed for the dialog.
Parameters
pMsg [in] Windows message to process.
Returns
TRUE if message translated.
SetScrollPos()
void MeaPositionLogDlg::SetScrollPos (int pos) const protected
Sets the scrollbar value which is the position list index.
Parameters
pos [in] Position index.
References SetScrollPos().
Referenced by LogLoaded(), OnHScroll(), OnInitDialog(), PositionAdded(), and SetScrollPos().
UpdatePositionInfo()
void MeaPositionLogDlg::UpdatePositionInfo (int posIndex = -1) const protected
Update the position number field, the recorded date field and the description field.
Parameters
posIndex [in] Position index or -1 if the scrollbar should be read to determine the current position.
References MeaPositionLogMgr::Position::GetDesc(), MeaPositionLogMgr::GetPosition(), GetScrollPos(), MeaPositionLogMgr::Position::GetTimeStamp(), MeaSingleton_T< MeaPositionLogMgr >::Instance(), MeaParseTimeStamp(), and MeaPositionLogMgr::NumPositions().
Referenced by LogLoaded(), OnHScroll(), OnInitDialog(), PositionAdded(), PositionDeleted(), and PositionReplaced().
The documentation for this class was generated from the following files:
PositionLogDlg.h
PositionLogDlg.cpp
Copyright 2011 C Thing Software