Meazure: MeaXMLWriter Class Reference
MeaXMLWriter Class Reference
This class writes pretty printed XML in UTF-8 encoding.
#include <XMLWriter.h>
Classes
struct Attribute
Represents an XML element attribute.
struct Element
Represents an XML element.
Public Member Functions
MeaXMLWriter (std::ostream &out)
Creates an XML writer that writes to the specified writer.
void Reset ()
Resets the XML writer to its initial state so that it can be reused.
MeaXMLWriter & StartDocument ()
Starts an XML document by writing the XML header.
MeaXMLWriter & EndDocument ()
Ends the XML output.
MeaXMLWriter & Doctype (PCTSTR name, PCTSTR systemId)
Writes a Document Type Declaration.
MeaXMLWriter & StartElement (PCTSTR name)
Starts a new element.
MeaXMLWriter & EndElement ()
Writes an end tag for the element that is open at the current level.
MeaXMLWriter & AddAttribute (PCTSTR name, const CString &value)
Adds an attribute to the current start tag.
MeaXMLWriter & AddAttribute (PCTSTR name, int value)
Adds an attribute to the current start tag.
MeaXMLWriter & AddAttribute (PCTSTR name, double value)
Adds an attribute to the current start tag.
MeaXMLWriter & Characters (PCTSTR str)
Writes the specified string as escaped XML data.
void Flush ()
Flushes the output.
Protected Types
typedef std::shared_ptr< Attribute > AttributePtr
typedef std::list< AttributePtr > Attributes
Protected Member Functions
virtual void WriteStartElement (bool isEmpty)
Writes a start tag and handles the case where the element is empty.
virtual void WriteEndElement ()
Writes an end tag.
virtual void WriteAttributes (Attributes attributes)
Writes out an attribute list, quoting and escaping values.
virtual void WriteIndent ()
Indents the output based on the element nesting level.
virtual void WriteQuoted (PCTSTR str)
Writes the specified string to the output as an escaped string surrounded by double quotes.
virtual void WriteEscaped (PCTSTR str)
Writes the specified string to the output escaping the XML special characters using the standard XML escape sequences.
virtual void WriteEscaped (TCHAR ch)
Writes the specified character to the output escaping the special characters using the standard XML escape sequences.
virtual void WriteNewline ()
Writes a newline character.
virtual void WriteRaw (PCTSTR str)
Writes the specified string to the output without escaping.
virtual void WriteRaw (TCHAR ch)
Writes the specified character to the output without escaping.
virtual void WriteUTF8Literal (PCSTR str)
Writes the specified UTF-8 literal string without any escaping or conversion.
virtual void WriteUTF8Literal (char ch)
Writes the specified UTF-8 literal character without any escaping or conversion.
Private Types
enum class State {
BeforeDoc ,
BeforeRoot ,
InStartTag ,
AfterTag ,
AfterData ,
AfterRoot ,
AfterDoc
}
Represents the state of the writer.
enum class Event {
Attribute ,
Characters ,
EndDocument ,
EndElement ,
StartDocument ,
StartElement
}
Represents a writing state transition event.
typedef std::shared_ptr< Element > ElementPtr
typedef std::stack< ElementPtr > ElementStack
Private Member Functions
State HandleEvent (Event event)
Heart of the XmlWriter state machine.
Static Private Member Functions
static PCSTR GetStateName (State state)
Obtains a string representation of the specified writing state for debugging purposes.
static PCSTR GetEventName (Event event)
Obtains a string representation of the specified writing event for debugging purposes.
Private Attributes
std::ostream & m_out
Output stream to write the XML.
ElementStack m_elementStack
Stack of open elements.
State m_currentState
Current state of the writer state machine.
Static Private Attributes
static const char * kIndent = u8" "
String for each level of indentation.
Detailed Description
This class writes pretty printed XML in UTF-8 encoding.
Because this class serves only the needs of this application, it does not support XML namespaces. Typical usage:
Create an MeaXMLWriter specifying the output destination.
Begin the XML output by calling the startDocument method.
Call XML output methods as needed (e.g. startElement).
Complete the XML output by calling the endDocument method to properly terminate the XML document. No XML output methods can be called following the call to endDocument.
Optionally, reuse the XmlWriter instance by calling the reset method.
The following is an example of using MeaXMLWriter to write a simple XML document to the standard output:
MeaXMLWriter writer(std::cout);
writer.StartDocument();
writer.StartElement(_T("elem1"));
writer.AddAttribute(_T("id"), _T("1234"));
writer.Characters(_T("Hello World"));
writer.EndElement();
writer.EndDocument();
The following XML is displayed on the standard output:
<?xml version="1.0" encoding="UTF-8"?>
<elem1 id="1234">Hello World</elem1>
Constructor & Destructor Documentation
MeaXMLWriter()
MeaXMLWriter::MeaXMLWriter (std::ostream & out) inline
Creates an XML writer that writes to the specified writer.
Parameters
out [in] Output destination.
References Reset().
Member Function Documentation
AddAttribute() [1/3]
MeaXMLWriter & MeaXMLWriter::AddAttribute (PCTSTR name, const CString & value)
Adds an attribute to the current start tag.
Parameters
name [in] Attribute name
value [in] Attribute value
Returns
This writer instance
References HandleEvent(), and m_elementStack.
Referenced by AddAttribute(), MeaPositionLogWriter::Save(), MeaPosition::Save(), MeaPositionDesktop::Save(), MeaPositionScreen::Save(), MeaPositionDesktop::SaveCustomPrecisions(), and MeaPositionLogWriter::WriteInfoSection().
AddAttribute() [2/3]
MeaXMLWriter & MeaXMLWriter::AddAttribute (PCTSTR name, double value)
Adds an attribute to the current start tag.
Parameters
name [in] Attribute name
value [in] Attribute value
Returns
This writer instance
References AddAttribute().
AddAttribute() [3/3]
MeaXMLWriter & MeaXMLWriter::AddAttribute (PCTSTR name, int value)
Adds an attribute to the current start tag.
Parameters
name [in] Attribute name
value [in] Attribute value
Returns
This writer instance
References AddAttribute().
Characters()
MeaXMLWriter & MeaXMLWriter::Characters (PCTSTR str)
Writes the specified string as escaped XML data.
Line endings are normalized to LF so that the output stream can translate them to the platform specific ending.
Parameters
str [in] String to write
Returns
This writer instance
References HandleEvent(), and WriteEscaped().
Referenced by MeaPosition::Save(), and MeaPositionLogWriter::WriteInfoSection().
Doctype()
MeaXMLWriter & MeaXMLWriter::Doctype (PCTSTR name, PCTSTR systemId)
Writes a Document Type Declaration.
Parameters
name [in] Root element name
systemId [in] System identified (must be specified).
Returns
This writer instance
References WriteNewline(), WriteRaw(), and WriteUTF8Literal().
Referenced by MeaPositionLogWriter::Save().
EndDocument()
MeaXMLWriter & MeaXMLWriter::EndDocument ()
Ends the XML output.
This method must be called to properly terminate the XML document. Before the XmlWriter can be reused, the reset() method must be called. This method does not close the underlying output stream.
Returns
This writer instance
References Flush(), HandleEvent(), and WriteNewline().
Referenced by MeaPositionLogWriter::Save().
EndElement()
MeaXMLWriter & MeaXMLWriter::EndElement ()
Writes an end tag for the element that is open at the current level.
Each call to startElement() requires a corresponding call to endElement.
Returns
This writer instance
References HandleEvent().
Referenced by MeaPositionLogWriter::Save(), MeaPosition::Save(), MeaPositionDesktop::Save(), MeaPositionScreen::Save(), MeaPositionDesktop::SaveCustomPrecisions(), MeaPositionLogWriter::WriteDesktopsSection(), MeaPositionLogWriter::WriteInfoSection(), and MeaPositionLogWriter::WritePositionsSection().
Flush()
void MeaXMLWriter::Flush ()
Flushes the output.
This method is especially useful for ensuring that the entire document has been output without having to close the writer. This method is invoked automatically by the endDocument() method.
References m_out.
Referenced by EndDocument().
GetEventName()
PCSTR MeaXMLWriter::GetEventName (Event event) static private
Obtains a string representation of the specified writing event for debugging purposes.
Parameters
event [in] Writing event whose string representation is to be returned
Returns
String representation of the specified event.
Referenced by HandleEvent().
GetStateName()
PCSTR MeaXMLWriter::GetStateName (State state) static private
Obtains a string representation of the specified writing state for debugging purposes.
Parameters
state [in] Writing state whose string representation is to be returned
Returns
String representation of the specified state.
Referenced by HandleEvent().
HandleEvent()
MeaXMLWriter::State MeaXMLWriter::HandleEvent (Event event) private
Heart of the XmlWriter state machine.
Based on the current state and the specified event, an action is fired, if any, and the next state is set. If the event is illegal for the current state, an std::ios_base::failure is thrown.
Parameters
event [in] The event to handle
Returns
Previous state
Exceptions
std::ios_base::failure If the event is illegal given the current state.
References GetEventName(), GetStateName(), m_currentState, m_elementStack, WriteEndElement(), and WriteStartElement().
Referenced by AddAttribute(), Characters(), EndDocument(), EndElement(), StartDocument(), and StartElement().
Reset()
void MeaXMLWriter::Reset ()
Resets the XML writer to its initial state so that it can be reused.
After endDocument(), the reset method must be called before the XmlWriter can be reused for output.
References m_currentState, and m_elementStack.
Referenced by MeaXMLWriter().
StartDocument()
MeaXMLWriter & MeaXMLWriter::StartDocument ()
Starts an XML document by writing the XML header.
This method writes a header with UTF-8 encoding. Call This method must be called before any other XML writer output method is called.
Returns
This writer instance
References HandleEvent(), WriteNewline(), and WriteUTF8Literal().
Referenced by MeaPositionLogWriter::Save().
StartElement()
MeaXMLWriter & MeaXMLWriter::StartElement (PCTSTR name)
Starts a new element.
Attributes for the element can be specified using the addAttributes. Each call to startElement requires a corresponding call to endElement.
Parameters
name [in] Name of the element
Returns
This writer instance
References HandleEvent(), and m_elementStack.
Referenced by MeaPositionLogWriter::Save(), MeaPosition::Save(), MeaPositionDesktop::Save(), MeaPositionScreen::Save(), MeaPositionDesktop::SaveCustomPrecisions(), MeaPositionLogWriter::WriteDesktopsSection(), MeaPositionLogWriter::WriteInfoSection(), and MeaPositionLogWriter::WritePositionsSection().
WriteAttributes()
void MeaXMLWriter::WriteAttributes (Attributes attributes) protected virtual
Writes out an attribute list, quoting and escaping values.
The attributes will be written all on one line.
Parameters
attributes [in] The attribute list to write.
References WriteQuoted(), WriteRaw(), and WriteUTF8Literal().
Referenced by WriteStartElement().
WriteEscaped() [1/2]
void MeaXMLWriter::WriteEscaped (PCTSTR str) protected virtual
Writes the specified string to the output escaping the XML special characters using the standard XML escape sequences.
Control characters and characters outside the ASCII range are escaped using a numeric character reference. Invalid XML control characters are written as "ctrl-nnnn".
Parameters
str [in] String to escape and write
References WriteEscaped().
Referenced by Characters(), WriteEscaped(), and WriteQuoted().
WriteEscaped() [2/2]
void MeaXMLWriter::WriteEscaped (TCHAR ch) protected virtual
Writes the specified character to the output escaping the special characters using the standard XML escape sequences.
Control characters and characters outside the ASCII range are escaped using a numeric character reference. Invalid XML control characters are written as "ctrl-nnnn".
Parameters
ch [in] Character to escape and write
References WriteNewline(), and WriteUTF8Literal().
WriteNewline()
void MeaXMLWriter::WriteNewline () protected virtual
Writes a newline character.
The runtime is relied upon to translate the line feed character into the platform specific line ending appropriate to the output stream (e.g. CR+LF for ofstream on Windows).
References WriteUTF8Literal().
Referenced by Doctype(), EndDocument(), StartDocument(), WriteEndElement(), WriteEscaped(), and WriteStartElement().
WriteQuoted()
void MeaXMLWriter::WriteQuoted (PCTSTR str) protected virtual
Writes the specified string to the output as an escaped string surrounded by double quotes.
Parameters
str [in] String to quote, escape and write
References WriteEscaped(), and WriteUTF8Literal().
Referenced by WriteAttributes().
WriteRaw() [1/2]
void MeaXMLWriter::WriteRaw (PCTSTR str) protected virtual
Writes the specified string to the output without escaping.
Parameters
str [in] String to write
References WriteUTF8Literal().
Referenced by Doctype(), WriteAttributes(), WriteEndElement(), and WriteStartElement().
WriteRaw() [2/2]
void MeaXMLWriter::WriteRaw (TCHAR ch) protected virtual
Writes the specified character to the output without escaping.
Parameters
ch [in] Character to write
References WriteUTF8Literal().
WriteStartElement()
void MeaXMLWriter::WriteStartElement (bool isEmpty) protected virtual
Writes a start tag and handles the case where the element is empty.
Parameters
isEmpty [in] true to write start element as if it were empty
References m_elementStack, WriteAttributes(), WriteIndent(), WriteNewline(), WriteRaw(), and WriteUTF8Literal().
Referenced by HandleEvent().
WriteUTF8Literal() [1/2]
void MeaXMLWriter::WriteUTF8Literal (char ch) protected virtual
Writes the specified UTF-8 literal character without any escaping or conversion.
Parameters
ch [in] UTF-8 literal character to write
References m_out.
WriteUTF8Literal() [2/2]
void MeaXMLWriter::WriteUTF8Literal (PCSTR str) protected virtual
Writes the specified UTF-8 literal string without any escaping or conversion.
Parameters
str [in] UTF-8 literal string to write
References m_out.
Referenced by Doctype(), StartDocument(), WriteAttributes(), WriteEndElement(), WriteEscaped(), WriteIndent(), WriteNewline(), WriteQuoted(), WriteRaw(), and WriteStartElement().
The documentation for this class was generated from the following files:
XMLWriter.h
XMLWriter.cpp
Copyright 2011 C Thing Software