Meazure: MeaUnits Class Reference
MeaUnits Class Reference
Measurement units are packaged into a class, one for each set of units (e.g.
#include <Units.h>
Public Types
typedef std::vector< int > DisplayPrecisions
Number of decimal places to display for each type of measurement.
typedef std::vector< CString > DisplayPrecisionNames
Strings to identify units precisions in profiles.
Public Member Functions
virtual ~MeaUnits ()
Base class destructor.
virtual void SaveProfile (MeaProfile &profile)
Persists the state of a units class instance to the specified profile object.
virtual void LoadProfile (MeaProfile &profile)
Restores the state of a units class instance from the specified profile object.
void SavePrecision (MeaProfile &profile)
Persists the measurement precisions to the specified profile object.
void LoadPrecision (MeaProfile &profile)
Restores the measurement precisions from the specified profile object.
virtual void MasterReset ()
Called to restores the units to their default state.
CString GetUnitsStr () const
Returns a string describing the units.
void SetDisplayPrecisions (const DisplayPrecisions &displayPrecisions)
Sets the decimal place precisions for all measurement types.
const DisplayPrecisions & GetDisplayPrecisions () const
Returns the current decimal place precisions for all measurement types.
const DisplayPrecisions & GetDefaultPrecisions () const
Returns the default decimal place precisions for all measurement types.
void RestoreDefaultPrecisions ()
Sets the default display precisions as the current precisions.
const DisplayPrecisionNames & GetDisplayPrecisionNames () const
Returns the identifying names for the display precisions.
Protected Member Functions
MeaUnits (PCTSTR unitsStr)
Base class constructor.
void AddPrecisionName (PCTSTR name)
Adds the specified identifying name to the list of precision names.
void AddPrecision (int precision)
Adds the specified precision value to both the list of current precisions and the list of default precisions.
Private Attributes
DisplayPrecisions m_defaultPrecisions
Default precisions for all measurement types.
DisplayPrecisions m_displayPrecisions
Current precisions for all measurement types.
DisplayPrecisionNames m_displayPrecisionNames
Names for all precision values.
CString m_unitsStr
Name for the units.
Detailed Description
Measurement units are packaged into a class, one for each set of units (e.g.
inches). Each class contains methods for conversion, display precision, and persistence of the state of the class to a given profile object. Related to these classes but not contained by them are the set of unit label classes.
This class serves as the base class for all measurement units.
Constructor & Destructor Documentation
MeaUnits()
MeaUnits::MeaUnits (PCTSTR unitsStr) explicit protected
Base class constructor.
Parameters
unitsStr [in] Name for the units.
Member Function Documentation
AddPrecision()
void MeaUnits::AddPrecision (int precision) inline protected
Adds the specified precision value to both the list of current precisions and the list of default precisions.
Parameters
precision [in] Number of decimal places to display.
References m_defaultPrecisions, and m_displayPrecisions.
Referenced by MeaCentimeterUnits::MeaCentimeterUnits(), MeaCustomUnits::MeaCustomUnits(), MeaDegreeUnits::MeaDegreeUnits(), MeaInchUnits::MeaInchUnits(), MeaMillimeterUnits::MeaMillimeterUnits(), MeaPicaUnits::MeaPicaUnits(), MeaPixelUnits::MeaPixelUnits(), MeaPointUnits::MeaPointUnits(), MeaRadianUnits::MeaRadianUnits(), and MeaTwipUnits::MeaTwipUnits().
AddPrecisionName()
void MeaUnits::AddPrecisionName (PCTSTR name) inline protected
Adds the specified identifying name to the list of precision names.
Parameters
name [in] Identifying name for the precision.
References m_displayPrecisionNames.
Referenced by MeaAngularUnits::MeaAngularUnits(), and MeaLinearUnits::MeaLinearUnits().
GetDefaultPrecisions()
const DisplayPrecisions & MeaUnits::GetDefaultPrecisions () const inline
Returns the default decimal place precisions for all measurement types.
Returns
Set of default precisions for all measurement types.
References m_defaultPrecisions.
Referenced by MeaPositionDesktop::MeaPositionDesktop().
GetDisplayPrecisionNames()
const DisplayPrecisionNames & MeaUnits::GetDisplayPrecisionNames () const inline
Returns the identifying names for the display precisions.
Returns
Set of names identifying precisions for all measurement types.
References m_displayPrecisionNames.
Referenced by MeaPositionDesktop::LoadCustomPrecisions(), and MeaPositionDesktop::SaveCustomPrecisions().
GetDisplayPrecisions()
const DisplayPrecisions & MeaUnits::GetDisplayPrecisions () const inline
Returns the current decimal place precisions for all measurement types.
Returns
Set of precisions for all measurement types.
References m_displayPrecisions.
Referenced by MeaAngularUnits::Format(), MeaLinearUnits::Format(), and MeaPositionDesktop::LoadCustomPrecisions().
GetUnitsStr()
CString MeaUnits::GetUnitsStr () const inline
Returns a string describing the units.
Returns
String describing he units (e.g. "px')
References m_unitsStr.
Referenced by MeaUnitsMgr::GetAngularUnitsStr(), MeaUnitsMgr::GetLinearUnitsStr(), MeaPositionDesktop::Save(), MeaPositionDesktop::SaveCustomPrecisions(), and MeaPositionLogMgr::ShowPosition().
LoadPrecision()
void MeaUnits::LoadPrecision (MeaProfile & profile)
Restores the measurement precisions from the specified profile object.
Parameters
profile [in] Profile object from which to restore the decimal place precisions.
References m_displayPrecisionNames, m_displayPrecisions, m_unitsStr, and MeaProfile::ReadInt().
Referenced by LoadProfile(), and MeaCustomUnits::LoadProfile().
LoadProfile()
void MeaUnits::LoadProfile (MeaProfile & profile) virtual
Restores the state of a units class instance from the specified profile object.
Parameters
profile [in] Profile object from which to restore the state of the units class.
Reimplemented in MeaCustomUnits.
References LoadPrecision(), and MeaProfile::UserInitiated().
MasterReset()
void MeaUnits::MasterReset () virtual
Called to restores the units to their default state.
Reimplemented in MeaCustomUnits.
References RestoreDefaultPrecisions().
Referenced by MeaCustomUnits::MasterReset().
SavePrecision()
void MeaUnits::SavePrecision (MeaProfile & profile)
Persists the measurement precisions to the specified profile object.
Parameters
profile [in] Profile object into which to persist the decimal place precisions.
References m_displayPrecisionNames, m_displayPrecisions, m_unitsStr, and MeaProfile::WriteInt().
Referenced by SaveProfile(), and MeaCustomUnits::SaveProfile().
SaveProfile()
void MeaUnits::SaveProfile (MeaProfile & profile) virtual
Persists the state of a units class instance to the specified profile object.
Parameters
profile [in] Profile object into which to persist the state of the units class.
Reimplemented in MeaCustomUnits.
References SavePrecision(), and MeaProfile::UserInitiated().
SetDisplayPrecisions()
void MeaUnits::SetDisplayPrecisions (const DisplayPrecisions & displayPrecisions) inline
Sets the decimal place precisions for all measurement types.
Parameters
displayPrecisions [in] Set of precisions for all measurement types.
References m_displayPrecisions.
Referenced by MeaPositionLogMgr::ShowPosition().
The documentation for this class was generated from the following files:
Units.h
Units.cpp
Copyright 2011 C Thing Software