Meazure: MeaCalibrationPrefs Class Reference
MeaCalibrationPrefs Class Reference
Property page for screen resolution calibration preferences.
#include <CalibrationPrefs.h>
Classes
struct Screen
This structure represents the characteristics of a screen.
Public Types
enum ResolutionMode {
AutoRes = 0 ,
ManualRes = 1
}
Indicates how the screen resolution is determined.
enum ResolutionUnits {
UseInches = 0 ,
UseCentimeters = 1
}
Indicates which unit system was used to manually calibrate the screen resolution.
typedef std::map< MeaScreenMgr::ScreenIter, Screen, MeaScreenMgr::less > ScreenMap
Maps iterators pointing to the screens attached to the system, to Screen information structures that describe the screen characteristics.
Public Member Functions
MeaCalibrationPrefs ()
Constructs a calibration property page instance.
~MeaCalibrationPrefs ()
Destroys a calibration property page instance.
virtual BOOL OnInitDialog ()
Called when the property page is created.
virtual BOOL OnSetActive ()
Called when the page becomes active.
virtual BOOL OnKillActive ()
Called when the page becomes inactive.
afx_msg void OnMove (int x, int y)
Called by the property sheet dialog when it is dragged.
BOOL UpdateData (BOOL bSaveAndValidate=TRUE)
Overrides the base class UpdateData method.
Public Attributes
ScreenMap m_screens
Map of screen iterators to screen information structures.
Protected Member Functions
afx_msg void OnAutoRes ()
Called when the operating system resolution is selected.
afx_msg void OnManRes ()
Called when manual resolution calibration is selected.
afx_msg void OnCalInches ()
Called when manual resolution calibration using inches is selected.
afx_msg void OnCalCm ()
Called when manual resolution calibration using centimeters is selected.
afx_msg void OnChange ()
Called whenever any value is changed by the UI.
afx_msg void OnRxFieldChange ()
Called when the value is changed in the x-axis resolution text field.
afx_msg void OnRyFieldChange ()
Called when the value is changed in the y-axis resolution text field.
afx_msg void OnWFieldChange ()
Called when the value is changed in the screen width text field.
afx_msg void OnHFieldChange ()
Called when the value is changed in the screen height text field.
virtual void DoDataExchange (CDataExchange *pDX)
Performs Dynamic Data Exchange (DDX) for the page.
Private Member Functions
void SetResMode (ResolutionMode resMode)
Sets the resolution calibration mode (i.e.
void SetResUnits (ResolutionUnits resUnits)
For manual resolution calibration, sets whether the calibration is performed in inches or centimeters.
bool GetFieldValue (UINT fieldId, double &value)
Returns the numeric value in the specified text field.
void UpdateSliders ()
Updates the position of the resolution calibration sliders based on the current resolution values.
void UpdateSlider (UINT sliderId, double res)
Updates the position of the specified slider based on the specified resolution.
bool LockedUpdateData (UINT lockoutId, bool bSaveAndValidate=true)
Same as the DDX UpdateData method except the specified UI object is not updated.
bool IsMetric ()
Indicates whether manual resolution calibration is being done in metrics units.
void DDX_ResText (CDataExchange *pDX, int nIDC, double &resValue)
Performs DDX handling for the resolution text fields.
void DDX_DimText (CDataExchange *pDX, int nIDC, double &dimValue)
Performs DDX handling for the screen dimension text fields.
bool Validate ()
Performs data validation on all appropriate text field values.
bool ValidateField (UINT id)
Performs data validation on the specified text field.
void UpdateView ()
Updates the display of all data.
void UpdateCurrentScreen ()
Determines the UI based on the current screen information.
LRESULT OnCaliperChange (WPARAM pos, LPARAM id)
Called when the position of one of the calibration sliders is changed.
Screen & GetScreen ()
Obtains the screen information for the current screen (i.e.
Private Attributes
MeaNumberField m_rxField
Numeric text field for the x-axis resolution.
MeaNumberField m_ryField
Numeric text field for the y-axis resolution.
MeaNumberField m_wField
Numeric text field for the screen width dimension.
MeaNumberField m_hField
Numeric text field for the screen height dimension.
MeaRulerSlider m_rxSlider
Calibration slider for the x-axis resolution.
MeaRulerSlider m_rySlider
Calibration slider for the y-axis resolution.
UINT m_lockoutId
ID of the UI object that should not be updated during DDX.
bool m_inDDX
Indicates if currently in DoDataExchange method.
MeaScreenMgr::ScreenIter m_currentIter
Current screen.
Detailed Description
Property page for screen resolution calibration preferences.
Using this property page, the screen resolution can be calibrated using a number of different techniques including direct measurement of the screen.
Member Enumeration Documentation
ResolutionMode
enum MeaCalibrationPrefs::ResolutionMode
Indicates how the screen resolution is determined.
Enumerator
AutoRes
The operating system is supplying the screen resolution.
ManualRes
The screen resolution is supplied by the user.
ResolutionUnits
enum MeaCalibrationPrefs::ResolutionUnits
Indicates which unit system was used to manually calibrate the screen resolution.
Enumerator
UseInches
The resolution was calibrated using inches.
UseCentimeters
The resolution was calibrated using centimeters.
Member Function Documentation
DDX_DimText()
void MeaCalibrationPrefs::DDX_DimText (CDataExchange * pDX, int nIDC, double & dimValue) private
Performs DDX handling for the screen dimension text fields.
Internally dimension values are maintained in inches. If calibration is being done using centimeters, this method converts to/from inches.
Parameters
pDX [in] DDX object for exchanging data between the page UI and the member variables.
nIDC [in] ID of the UI control.
dimValue [in, out] Dimensions in either inches or centimeters.
References IsMetric().
Referenced by DoDataExchange().
DDX_ResText()
void MeaCalibrationPrefs::DDX_ResText (CDataExchange * pDX, int nIDC, double & resValue) private
Performs DDX handling for the resolution text fields.
Internally resolution values are maintained in pixels/inch. If calibration is being done using centimeters, this method converts to/from inches.
Parameters
pDX [in] DDX object for exchanging data between the page UI and the member variables.
nIDC [in] ID of the UI control.
resValue [in, out] Resolution in either pixels/inch or pixels/centimeter.
References IsMetric().
Referenced by DoDataExchange().
DoDataExchange()
void MeaCalibrationPrefs::DoDataExchange (CDataExchange * pDX) protected virtual
Performs Dynamic Data Exchange (DDX) for the page.
Parameters
pDX [in] DDX object for exchanging data between the page UI and the member variables.
References FSIZE::cx, FSIZE::cy, DDX_DimText(), DDX_ResText(), GetScreen(), m_inDDX, m_lockoutId, MeaCalibrationPrefs::Screen::m_res, MeaCalibrationPrefs::Screen::m_resMode, MeaCalibrationPrefs::Screen::m_resUnits, MeaCalibrationPrefs::Screen::m_size, and UpdateCurrentScreen().
GetFieldValue()
bool MeaCalibrationPrefs::GetFieldValue (UINT fieldId, double & value) private
Returns the numeric value in the specified text field.
Parameters
fieldId [in] Identifier of the text field.
value [out] Numerical value in the text field.
Returns
true if a numerical value greater than zero was read and that value differs from that passed in.
References IsMetric(), and MEA_DBL_EQL.
Referenced by OnHFieldChange(), OnRxFieldChange(), OnRyFieldChange(), OnWFieldChange(), and ValidateField().
GetScreen()
Screen & MeaCalibrationPrefs::GetScreen () inline private
Obtains the screen information for the current screen (i.e.
the screen on which the page is located).
Returns
Screen information structure.
References m_currentIter, m_screens, and MeaAssert.
Referenced by DoDataExchange(), IsMetric(), OnCaliperChange(), OnHFieldChange(), OnRxFieldChange(), OnRyFieldChange(), OnWFieldChange(), SetResMode(), SetResUnits(), UpdateSliders(), UpdateView(), Validate(), and ValidateField().
IsMetric()
bool MeaCalibrationPrefs::IsMetric () inline private
Indicates whether manual resolution calibration is being done in metrics units.
Returns
true if the calibration is being done in centimeters.
References GetScreen(), MeaCalibrationPrefs::Screen::m_resUnits, and UseCentimeters.
Referenced by DDX_DimText(), DDX_ResText(), GetFieldValue(), OnCaliperChange(), and UpdateSlider().
LockedUpdateData()
bool MeaCalibrationPrefs::LockedUpdateData (UINT lockoutId, bool bSaveAndValidate = true) private
Same as the DDX UpdateData method except the specified UI object is not updated.
This prevents cyclic updating.
Parameters
lockoutId [in] ID of UI object that should not be updated.
bSaveAndValidate [in] Indicates whether the UI should be saved to the member variables.
Returns
true if data update was successful.
References m_lockoutId, and UpdateData().
Referenced by OnHFieldChange(), OnRxFieldChange(), OnRyFieldChange(), and OnWFieldChange().
OnCaliperChange()
LRESULT MeaCalibrationPrefs::OnCaliperChange (WPARAM pos, LPARAM id) private
Called when the position of one of the calibration sliders is changed.
Parameters
pos [in] New position of the slider. This is the resolution either in pixels/inch or 2 * pixels/centimeter.
id [in] ID of the slider that has been changed.
Returns
TRUE to indicate successful processing.
References FSIZE::cx, FSIZE::cy, GetScreen(), MeaScreenMgr::GetScreenRect(), MeaSingleton_T< MeaScreenMgr >::Instance(), IsMetric(), m_currentIter, MeaCalibrationPrefs::Screen::m_res, MeaCalibrationPrefs::Screen::m_size, OnChange(), and UpdateData().
OnChange()
void MeaCalibrationPrefs::OnChange () protected
Called whenever any value is changed by the UI.
This method sets the page modified flag.
Referenced by OnAutoRes(), OnCaliperChange(), OnHFieldChange(), OnManRes(), OnRxFieldChange(), OnRyFieldChange(), and OnWFieldChange().
OnInitDialog()
BOOL MeaCalibrationPrefs::OnInitDialog () virtual
Called when the property page is created.
This method subclasses a number of controls on the page, with our implementations.
Returns
TRUE, indicating that the input focus should be set to the first control on the page.
References m_hField, m_rxField, m_rxSlider, m_ryField, m_rySlider, m_wField, MeaNumberField::PosValues, and MeaNumberField::SetValueType().
OnKillActive()
BOOL MeaCalibrationPrefs::OnKillActive () virtual
Called when the page becomes inactive.
The data on the page is validated.
Returns
TRUE if the data was valid and the page can become inactive. FALSE if the data is not valid and the page must remain active.
References Validate().
OnMove()
void MeaCalibrationPrefs::OnMove (int x, int y)
Called by the property sheet dialog when it is dragged.
This method updates the UI to reflect the current screen's resolution calibration information.
Parameters
x [in] x coordinate of the upper left corner of the dialog window in screen coordinates.
y [in] y coordinate of the upper left corner of the dialog window in screen coordinates.
References UpdateCurrentScreen().
Referenced by MeaPreferences::OnMove().
OnSetActive()
BOOL MeaCalibrationPrefs::OnSetActive () virtual
Called when the page becomes active.
This method ensures the the calibration information reflects the screen on which the page is being displayed.
Returns
TRUE, indicating that the page is active.
References UpdateCurrentScreen(), and UpdateView().
SetResMode()
void MeaCalibrationPrefs::SetResMode (ResolutionMode resMode) private
Sets the resolution calibration mode (i.e.
automatic or manual).
Parameters
resMode [in] Resolution mode (i.e. automatic or manual).
References GetScreen(), MeaCalibrationPrefs::Screen::m_resMode, and ManualRes.
Referenced by OnAutoRes(), OnManRes(), and UpdateView().
SetResUnits()
void MeaCalibrationPrefs::SetResUnits (ResolutionUnits resUnits) private
For manual resolution calibration, sets whether the calibration is performed in inches or centimeters.
Parameters
resUnits [in] Units used for manual resolution calibration.
References GetScreen(), MeaCalibrationPrefs::Screen::m_resUnits, and UseInches.
Referenced by OnCalCm(), OnCalInches(), and UpdateView().
UpdateCurrentScreen()
void MeaCalibrationPrefs::UpdateCurrentScreen () private
Determines the UI based on the current screen information.
The information displayed on this page is dependent on the screen on which it is shown.
References MeaScreenMgr::GetScreenIter(), MeaScreenMgr::GetScreenName(), MeaSingleton_T< MeaScreenMgr >::Instance(), m_currentIter, MeaAssert, and UpdateView().
Referenced by DoDataExchange(), OnMove(), and OnSetActive().
UpdateData()
BOOL MeaCalibrationPrefs::UpdateData (BOOL bSaveAndValidate = TRUE)
Overrides the base class UpdateData method.
The base class asserts if a recursive call to UpdateData is attempted. In case there is a recursive call, we don't want to assert, we just want to ignore the call. See CWnd::UpdateData for an explanation of the parameter and return value.
References m_inDDX.
Referenced by LockedUpdateData(), OnCalCm(), OnCalInches(), OnCaliperChange(), UpdateView(), and Validate().
UpdateSlider()
void MeaCalibrationPrefs::UpdateSlider (UINT sliderId, double res) private
Updates the position of the specified slider based on the specified resolution.
Parameters
sliderId [in] ID of the slider to update.
res [in] Resolution value, in pixels/inch.
References IsMetric(), and MeaRulerSlider::SetSliderPos().
Referenced by OnHFieldChange(), OnRxFieldChange(), OnRyFieldChange(), OnWFieldChange(), and UpdateSliders().
UpdateView()
void MeaCalibrationPrefs::UpdateView () private
Updates the display of all data.
This includes updating the text field values and slider positions.
References FSIZE::cx, FSIZE::cy, GetScreen(), MeaScreenMgr::GetScreenRect(), MeaSingleton_T< MeaScreenMgr >::Instance(), m_currentIter, MeaCalibrationPrefs::Screen::m_res, MeaCalibrationPrefs::Screen::m_resMode, MeaCalibrationPrefs::Screen::m_resUnits, MeaCalibrationPrefs::Screen::m_size, SetResMode(), SetResUnits(), UpdateData(), and UpdateSliders().
Referenced by OnSetActive(), and UpdateCurrentScreen().
Validate()
bool MeaCalibrationPrefs::Validate () private
Performs data validation on all appropriate text field values.
For these text fields, a value is considered valid if it is greater than zero.
Returns
true if all appropriate field values are valid.
References AutoRes, FSIZE::cx, FSIZE::cy, GetScreen(), MeaScreenMgr::GetScreenRect(), MeaScreenMgr::GetScreenRes(), MeaSingleton_T< MeaScreenMgr >::Instance(), m_currentIter, MeaCalibrationPrefs::Screen::m_res, MeaCalibrationPrefs::Screen::m_resMode, MeaCalibrationPrefs::Screen::m_size, UpdateData(), and ValidateField().
Referenced by OnKillActive().
ValidateField()
bool MeaCalibrationPrefs::ValidateField (UINT id) private
Performs data validation on the specified text field.
For these test fields, a value is considered valid if it is greater than zero.
Parameters
id [in] ID of the text field whose value is to be validated.
Returns
true if the field value is valid.
References GetFieldValue(), GetScreen(), and ManualRes.
Referenced by Validate().
The documentation for this class was generated from the following files:
CalibrationPrefs.h
CalibrationPrefs.cpp
Copyright 2011 C Thing Software