Meazure: ev::Validator Class Reference
ev::Validator Class Reference
The star of the show, this call performs XML validation for the expat parser.
#include <exval.h>
Public Member Functions
Validator (IValidationHandler *handler=NULL)
Typically an IValidationHandler is passed to the constructor so that the application can be informed of validation errors.
virtual ~Validator ()
Destroys a validator instance.
void SetValidationHandler (IValidationHandler *handler)
The validation handler can be set after object construction using this method.
void Clear ()
Deletes the entire state of the validator bringing it back to its newly constructed state.
void Reset ()
Resets the state of the validator so that another document with the same DTD can be validated.
void AddElementDecl (const XML_Char *elementName, const XML_Content *contentModel)
Call this method from the expat XML_ElementDeclHandler to register an element declaration with the validator.
void AddAttributeDecl (const XML_Char *elementName, const XML_Char *attrName, const XML_Char *attrType, const XML_Char *defValue, int isRequired)
Call this method from the expat XML_AttlistDeclHandler to register an attribute declaration.
void AddNotationDecl (const XML_Char *notationName)
Call this method from the expat XML_NotationDeclHandler to register a notation declaration.
void AddEntityDecl (const XML_Char *entityName)
Call this method from the expat XML_EntityDeclHandler to register an entity declaration.
void SetDocumentElement (const XML_Char *elementName)
An XML file must have a single top level element, known as the document element.
EVString GetDocumentElement () const
Returns the document element name.
const XML_Char * GetCurrentElement () const
Returns the element currently being validated.
SymbolSet GetAllowableElements () const
Returns the set of elements that are allowable at the current position in the document.
const SymbolSet & GetAnyElements () const
Returns the set of elements that are allowable for an ANY element.
bool StartElement (XML_Parser parser, const XML_Char *elementName, const XML_Char **attributes)
Call this method from the expat XML_StartElementHandler to test whether the element is valid according to the content model of the containing element.
bool EndElement (XML_Parser parser)
Call this method from the expat XML_EndElementHandler to test whether the ending of the element is valid according to the content model of the containing element.
bool CharacterData (XML_Parser parser, const XML_Char *buf, int len)
Call this method from the XML_CharacterDataHandler to test whether character data is allowed by the containing element's content model.
bool IsMixed (const XML_Char *elementName) const
Indicates whether the specified element allows PCDATA.
Protected Types
typedef std::map< EVString, ElementDecl * > ElementDeclMap
Maps an element name to its declaration.
typedef ElementDeclMap::iterator ElementDeclIter
Iterator over the element declaration map.
typedef ElementDeclMap::const_iterator ElementDeclIter_c
Constant iterator over the element declaration map.
typedef std::stack< const ElementDecl * > ElementStack
Open element stack.
typedef std::map< EVString, bool > MixedMap
Indicates whether the specified element name accepts PCDATA.
typedef MixedMap::const_iterator MixedIter
Iterates over the element PCDATA map.
typedef std::stack< const State * > StateStack
Validation DFA state stack.
typedef std::set< EVString > IDSet
Element ID set.
typedef IDSet::const_iterator IDIter_c
Iterator over the element ID set.
typedef std::set< EVString > IDRefSet
IDREF set.
typedef IDRefSet::const_iterator IDRefIter_c
Iterator over the IDREF set.
typedef std::set< EVString > NotationSet
Set of notations.
typedef NotationSet::const_iterator NotationIter_c
Iterator over the set of notations.
typedef std::set< EVString > EntitySet
Set of entities.
typedef EntitySet::const_iterator EntityIter_c
Iterator over the set of entities.
typedef std::map< EVString, DFA * > DFAMap
Maps the name of an element to its validation DFA.
typedef DFAMap::iterator DFAIter
Iterator over the DFA map.
typedef DFAMap::const_iterator DFAIter_c
Constant iterator over the DFA map.
Protected Member Functions
Validator (const Validator &validator)
Purposely undefined.
Validator & operator= (const Validator &validator)
Purposely undefined.
bool IsDocumentElement (const XML_Char *elementName) const
Indicates whether the specified element is the document element.
const ElementDecl * GetElementDecl (const EVString &elementName) const
Returns the declaration for the specified element.
bool HaveAttribute (const XML_Char **attributes, const EVString &attrName) const
Indicates whether the specified set of attributes contains the specified attribute.
void ClearStateStack ()
Removes all state objects from the DFA state stack.
bool IsStateStackEmpty () const
Tests whether the DFA state stack is empty.
void PushState (const State *state)
Pushes the specified DFA state onto the state stack.
void PopState ()
Pops the top DFA state object off the DFA state stack.
const State * TopState () const
Returns the state object at the top of the DFA state stack.
void SwapTopState (const State *state)
Replaces the state object on the top of the DFA state stack with the specified DFA state.
void ClearElementStack ()
Removes all elements from the open element stack.
bool IsElementStackEmpty () const
Tests whether the open element stack is empty.
void PushElement (const ElementDecl *state)
Pushes the specified element declaration onto the open element stack.
void PopElement ()
Pops the top element declaration off the top of the open element stack.
const ElementDecl * TopElement () const
Returns the element declaration at the top of the open element stack.
bool IsWhitespace (const XML_Char *str, int len) const
Tests whether the specified string consists only of XML whitespace characters.
void SendError (XML_Parser parser, ValidationError::Code errorCode, const XML_Char *currentElement=NULL, const XML_Char *containingElement=NULL)
Sends the specified error message to the validation handler.
Protected Attributes
IValidationHandler * m_handler
Validation error handler object.
EVString m_documentElement
XML document element.
DFAMap m_dfas
DFAs for all elements.
ElementDeclMap m_elementDecls
Element declarations.
MixedMap m_mixedElements
Elements that can contain PCDATA.
SymbolSet m_anyElements
Set of elements allowable in ANY.
ElementStack m_elementStack
Open element stack.
StateStack m_dfaStateStack
DFA stack stack.
IDSet m_ids
ID set.
IDRefSet m_idRefs
IDREF set.
NotationSet m_notations
Set of notations.
EntitySet m_entities
Set of entities.
bool m_foundDocumentElement
Indicates if document element found.
bool m_errorShutdown
Indicates if validation error should stop due to errors.
Friends
EVOstream & operator<< (EVOstream &stream, const Validator &validator)
Output stream operator for a validator.
Detailed Description
The star of the show, this call performs XML validation for the expat parser.
An application instantiates a Validator object and ties it into the expat parser via the parser's handler functions.
The validator constructs a DFA for each element's content model using the venerable algorithm 3.5 from the Dragon book. Optimizations bypass the algorithm and directly construct the DFA for simple content models (e.g. singletons, pure choice, pure sequence).
The validator is a C++ object with methods that you call from expat handlers. The method parameters are of the same types as those passed to the expat handlers.
To use the validator instantiate an ev::Validator object then call the following methods from the corresponding expat handlers:
Validator Method Call From expat Handler
AddElementDecl XML_ElementDeclHandler
AddAttributeDecl XML_AttlistDeclHandler
AddNotationDecl XML_NotationDeclHandler
AddEntityDecl XML_EntityDeclHandler
SetDocumentElement XML_StartDoctypeDeclHandler
StartElement XML_StartElementHandler
EndElement XML_EndElementHandler
CharacterData XML_CharacterDataHandler
Encoding uses expat's XML_Char encoding based on whether XML_UNICODE is defined. exval defines the types ev::EVString and ev::EVOStream but these are just convenience wrappers around the appropriate STL string and stream classes.
Constructor & Destructor Documentation
Validator()
Validator::Validator (IValidationHandler * handler = NULL) explicit
Typically an IValidationHandler is passed to the constructor so that the application can be informed of validation errors.
If it is not passed to the constructor, the IValidationHandler can be set later using the SetValidationHandler method.
Parameters
handler [in] Validation error handler object.
Member Function Documentation
AddAttributeDecl()
void Validator::AddAttributeDecl (const XML_Char * elementName, const XML_Char * attrName, const XML_Char * attrType, const XML_Char * defValue, int isRequired)
Call this method from the expat XML_AttlistDeclHandler to register an attribute declaration.
The method takes the name of the element which contains the attribute, the name of the attribute, its type, default value, and whether the attribute is required. All these values are provided to the expat handler function.
Parameters
elementName [in] Name of the element containing the attribute.
attrName [in] Name of the attribute being declared.
attrType [in] Type of the attribute.
defValue [in] Default value for the attribute, or NULL if no default.
isRequired [in] Non-zero if the attribute is required.
References ev::ElementDecl::AddAttributeDecl(), and m_elementDecls.
Referenced by MeaXMLParser::AttributeDeclHandler().
AddElementDecl()
void Validator::AddElementDecl (const XML_Char * elementName, const XML_Content * contentModel)
Call this method from the expat XML_ElementDeclHandler to register an element declaration with the validator.
The method takes the name of the element and its content model as provided by expat.
Parameters
elementName [in] Name of the element being declared.
contentModel [in] Content model for the element as constructed by expat.
References ev::ContentModel::GetSignature(), ev::ContentModel::IsMixed(), m_anyElements, m_dfas, m_documentElement, m_elementDecls, m_mixedElements, and ev::ElementDecl::SetDFA().
Referenced by MeaXMLParser::ElementDeclHandler().
AddEntityDecl()
void ev::Validator::AddEntityDecl (const XML_Char * entityName) inline
Call this method from the expat XML_EntityDeclHandler to register an entity declaration.
The method takes the name of the entity as provided to the expat handler.
Parameters
entityName [in] Name for the entity.
References m_entities.
AddNotationDecl()
void ev::Validator::AddNotationDecl (const XML_Char * notationName) inline
Call this method from the expat XML_NotationDeclHandler to register a notation declaration.
The method takes the name of the notation as provided to the expat handler.
Parameters
notationName [in] Name for the notation.
References m_notations.
CharacterData()
bool Validator::CharacterData (XML_Parser parser, const XML_Char * buf, int len)
Call this method from the XML_CharacterDataHandler to test whether character data is allowed by the containing element's content model.
The method takes the expat parser instance and the character data. The method compensates for whitespace that is element content (i.e. newlines and purely indenting whitespace). buf does not have to be NULL terminated. len is the number of bytes in buf.
Parameters
parser [in] XML parser.
buf [in] Character data (might not be NULL terminated).
len [in] Number of bytes in buf.
Returns
true if content is valid in the current parsing context, false otherwise and the HandleValidationError method will be called on the IValidationHandler interface.
References ev::State::IsAny(), ev::State::IsMixed(), IsWhitespace(), m_errorShutdown, ev::ValidationError::NoCharacterData, SendError(), TopElement(), TopState(), and ev::ValidationError::UncontainedCharacterData.
Referenced by MeaXMLParser::CharacterDataHandler().
Clear()
void Validator::Clear ()
Deletes the entire state of the validator bringing it back to its newly constructed state.
All DFA's and other maps are cleared.
References m_dfas, m_elementDecls, and Reset().
Referenced by ~Validator().
EndElement()
bool Validator::EndElement (XML_Parser parser)
Call this method from the expat XML_EndElementHandler to test whether the ending of the element is valid according to the content model of the containing element.
The method takes the expat parser instance.
Parameters
parser [in] XML parser.
Returns
Can return false on close of document element if, for example, there are unreconciled IDREF attributes.
References ev::ValidationError::IdNotFound, ev::ValidationError::InvalidElementPattern, ev::State::IsAccepting(), IsElementStackEmpty(), IsStateStackEmpty(), m_errorShutdown, m_idRefs, m_ids, PopElement(), PopState(), SendError(), TopElement(), and TopState().
Referenced by MeaXMLParser::EndElementHandler().
GetAllowableElements()
SymbolSet Validator::GetAllowableElements () const
Returns the set of elements that are allowable at the current position in the document.
Returns
A set of element names.
References ev::State::GetSymbolSet(), ev::State::IsAny(), m_anyElements, m_documentElement, and TopState().
GetAnyElements()
const SymbolSet & ev::Validator::GetAnyElements () const inline
Returns the set of elements that are allowable for an ANY element.
Returns
A set of element names.
References m_anyElements.
Referenced by ev::State::GetNextState().
GetCurrentElement()
const XML_Char * Validator::GetCurrentElement () const
Returns the element currently being validated.
Returns
Name of the element currently being validated.
References EV_T, TopElement(), and TopState().
GetDocumentElement()
EVString ev::Validator::GetDocumentElement () const inline
Returns the document element name.
Returns
Name of the document element.
References m_documentElement.
GetElementDecl()
const ElementDecl * ev::Validator::GetElementDecl (const EVString & elementName) const inline protected
Returns the declaration for the specified element.
Parameters
elementName [in] Name of element whose declaration is desired.
Returns
Declaration object for the specified element or NULL if the declaration could not be found.
References m_elementDecls.
Referenced by StartElement().
HaveAttribute()
bool Validator::HaveAttribute (const XML_Char ** attributes, const EVString & attrName) const protected
Indicates whether the specified set of attributes contains the specified attribute.
Parameters
attributes [in] Set of attribute name/value pairs.
attrName [in] Name of the attribute to look up.
Returns
true if the attribute is found in the specified array of attributes.
Referenced by StartElement().
IsDocumentElement()
bool ev::Validator::IsDocumentElement (const XML_Char * elementName) const inline protected
Indicates whether the specified element is the document element.
Parameters
elementName [in] Name of element to test.
Returns
true if the specified element is the document element.
References m_documentElement.
Referenced by StartElement().
IsElementStackEmpty()
bool ev::Validator::IsElementStackEmpty () const inline protected
Tests whether the open element stack is empty.
Returns
true if the element stack is empty.
References m_elementStack.
Referenced by EndElement(), and Reset().
IsMixed()
bool ev::Validator::IsMixed (const XML_Char * elementName) const inline
Indicates whether the specified element allows PCDATA.
Parameters
elementName [in] Name of the element to test.
Returns
true if the element allows PCDATA.
References m_mixedElements.
Referenced by MeaXMLParser::CharacterDataHandler().
IsStateStackEmpty()
bool ev::Validator::IsStateStackEmpty () const inline protected
Tests whether the DFA state stack is empty.
Returns
true if the DFA state stack is empty.
References m_dfaStateStack.
Referenced by EndElement(), Reset(), and StartElement().
IsWhitespace()
bool Validator::IsWhitespace (const XML_Char * str, int len) const protected
Tests whether the specified string consists only of XML whitespace characters.
Parameters
str [in] String buffer not NULL terminated.
len [in] Number of bytes in string buffer.
Returns
true if string consists solely of whitespace characters.
References EV_T.
Referenced by CharacterData().
PushElement()
void ev::Validator::PushElement (const ElementDecl * state) inline protected
Pushes the specified element declaration onto the open element stack.
The stack uses the element declaration so that the appropriate content model DFA can be used to validate the element content.
Parameters
state [in] element declaration.
References m_elementStack.
Referenced by StartElement().
PushState()
void ev::Validator::PushState (const State * state) inline protected
Pushes the specified DFA state onto the state stack.
Parameters
state [in] DFA state object.
References m_dfaStateStack.
Referenced by StartElement(), and SwapTopState().
Reset()
void Validator::Reset ()
Resets the state of the validator so that another document with the same DTD can be validated.
This method must be called after validation is complete or after an error has occurred if the validator is to be used again.
References IsElementStackEmpty(), IsStateStackEmpty(), m_errorShutdown, m_foundDocumentElement, m_idRefs, m_ids, PopElement(), and PopState().
Referenced by Clear().
SendError()
void Validator::SendError (XML_Parser parser, ValidationError::Code errorCode, const XML_Char * currentElement = NULL, const XML_Char * containingElement = NULL) protected
Sends the specified error message to the validation handler.
Parameters
parser [in] XML parser.
errorCode [in] Error code defined by ValidationError.
currentElement [in] Name of the element being processed.
containingElement [in] Name of the element containing the current element.
References ev::IValidationHandler::HandleValidationError(), m_errorShutdown, and m_handler.
Referenced by CharacterData(), EndElement(), and StartElement().
SetDocumentElement()
void Validator::SetDocumentElement (const XML_Char * elementName)
An XML file must have a single top level element, known as the document element.
Call SetDocumentElement from the expat XML_StartDoctypeDeclHandler to tell the validator which element is the document element.
Parameters
elementName [in] Name of the document element.
References m_documentElement.
Referenced by MeaXMLParser::DoctypeDeclHandler().
SetValidationHandler()
void ev::Validator::SetValidationHandler (IValidationHandler * handler) inline
The validation handler can be set after object construction using this method.
Parameters
handler [in] Validation error handler object.
References m_handler.
StartElement()
bool Validator::StartElement (XML_Parser parser, const XML_Char * elementName, const XML_Char ** attributes)
Call this method from the expat XML_StartElementHandler to test whether the element is valid according to the content model of the containing element.
In addition, the method validates the element's attributes. The method takes the expat parser instance, the name of the element and its list of attributes.
Parameters
parser [in] XML parser.
elementName [in] Name of the element.
attributes [in] Array of attribute name/value pairs for the element.
Returns
true if element is valid in the current parsing context, false otherwise and the HandleValidationError method will be called on the IValidationHandler interface.
References ev::ValidationError::BadAttributeValue, ev::AttributeDecl::CDATA, ev::ValidationError::DuplicateId, ev::ElementDecl::EndRequiredAttributes(), ev::AttributeDecl::ENTITIES, ev::AttributeDecl::ENTITY, ev::AttributeDecl::Enumerated, EV_T, ev::ElementDecl::GetAttributeDecl(), ev::AttributeDecl::GetDefault(), GetElementDecl(), ev::State::GetNextState(), ev::ElementDecl::GetStartState(), ev::AttributeDecl::GetType(), HaveAttribute(), ev::AttributeDecl::ID, ev::AttributeDecl::IDREF, ev::AttributeDecl::IDREFS, ev::ValidationError::InvalidDocumentElement, ev::ValidationError::InvalidElement, IsDocumentElement(), ev::AttributeDecl::IsEnumValue(), ev::AttributeDecl::IsFixed(), IsStateStackEmpty(), m_entities, m_errorShutdown, m_foundDocumentElement, m_idRefs, m_ids, m_notations, ev::ValidationError::MismatchedFixedValue, ev::ValidationError::MissingRequiredAttribute, ev::ValidationError::MultipleDocumentElements, ev::ValidationError::MultipleTopLevelElements, ev::AttributeDecl::NMTOKEN, ev::AttributeDecl::NMTOKENS, ev::AttributeDecl::NOTATION, PushElement(), PushState(), SendError(), ev::ElementDecl::StartRequiredAttributes(), SwapTopState(), TopElement(), TopState(), ev::ValidationError::UndeclaredAttribute, ev::ValidationError::UndeclaredElement, ev::ValidationError::UndeclaredEntity, and ev::ValidationError::UndeclaredNotation.
Referenced by MeaXMLParser::StartElementHandler().
SwapTopState()
void ev::Validator::SwapTopState (const State * state) inline protected
Replaces the state object on the top of the DFA state stack with the specified DFA state.
Parameters
state [in] DFA state object.
References PopState(), and PushState().
Referenced by StartElement().
TopElement()
const ElementDecl * ev::Validator::TopElement () const inline protected
Returns the element declaration at the top of the open element stack.
The declaration is not removed from the stack.
Returns
Element declaration or NULL if the stack is empty.
References m_elementStack.
Referenced by CharacterData(), EndElement(), GetCurrentElement(), and StartElement().
TopState()
const State * ev::Validator::TopState () const inline protected
Returns the state object at the top of the DFA state stack.
The object is not removed from the stack.
Returns
DFA state object or NULL if the stack is empty.
References m_dfaStateStack.
Referenced by CharacterData(), EndElement(), GetAllowableElements(), GetCurrentElement(), and StartElement().
Friends And Related Function Documentation
operator<<
EVOstream & operator<< (EVOstream & stream, const Validator & validator) friend
Output stream operator for a validator.
Used to dump the state of the validator to the specified output stream for debugging purposes.
Parameters
stream [in] Output stream.
validator [in] Validator object to output.
Returns
Output stream.
The documentation for this class was generated from the following files:
exval.h
exval.cpp
Copyright 2011 C Thing Software