Meazure: MeaXMLAttributes Class Reference
MeaXMLAttributes Class Reference
The class contains the attributes associated with an XML start element.
#include <XMLParser.h>
Classes
struct AttributeValue
Represents an attribute value.
Public Member Functions
MeaXMLAttributes ()
Constructs an empty instance of the XML attributes class.
MeaXMLAttributes (const MeaXMLAttributes &attrs)
Copy constructor.
virtual ~MeaXMLAttributes ()
Destroys an instance of the XML attributes class.
MeaXMLAttributes & operator= (const MeaXMLAttributes &attrs)
Performs a deep assignment of the specified XML attribute object.
bool GetValueStr (LPCTSTR name, CString &value, bool &isDefault) const
Returns the value of the specified attribute as a string.
bool GetValueInt (LPCTSTR name, int &value, bool &isDefault) const
Returns the value of the specified attribute converted to an integer.
bool GetValueDbl (LPCTSTR name, double &value, bool &isDefault) const
Returns the value of the specified attribute converted to a double.
bool GetValueBool (LPCTSTR name, bool &value, bool &isDefault) const
Returns the value of the specified attribute converted to a boolean.
MeaXMLAttributes & Assign (const MeaXMLAttributes &attrs)
Performs a deep copy assignment of the specified attribute object to this.
Protected Member Functions
MeaXMLAttributes (const XML_Char **atts, int numSpecified)
Constructs an instance of the class based on the specified attributes provided by the expat parser.
Protected Attributes
std::map< CString, AttributeValue > m_attributeMap
Maps attribute names to their values.
Friends
class MeaXMLParser
Detailed Description
The class contains the attributes associated with an XML start element.
In addition to iterating through the attributes, the class provides searching and other attribute manipulation capabilities.
Constructor & Destructor Documentation
MeaXMLAttributes() [1/2]
MeaXMLAttributes::MeaXMLAttributes (const MeaXMLAttributes & attrs) inline
Copy constructor.
A deep copy of the specified attribute object is performed.
Parameters
attrs [in] XML attribute object instance to copy.
References Assign().
MeaXMLAttributes() [2/2]
MeaXMLAttributes::MeaXMLAttributes (const XML_Char ** atts, int numSpecified) protected
Constructs an instance of the class based on the specified attributes provided by the expat parser.
Parameters
atts [in] Array of attribute name/value pairs from expat. In the array the name is followed by the value which is then followed by another name and so on until a NULL is encountered.
numSpecified [in] Number of attributes in the array that have been explicitly specified versus set by default from the DTD. The atts array is organized such that the explicitly specified attributes come first.
References MeaXMLParser::FromUTF8(), MeaXMLAttributes::AttributeValue::isDefault, m_attributeMap, MeaAssert, and MeaXMLAttributes::AttributeValue::value.
Member Function Documentation
Assign()
MeaXMLAttributes & MeaXMLAttributes::Assign (const MeaXMLAttributes & attrs)
Performs a deep copy assignment of the specified attribute object to this.
Parameters
attrs [in] Attribute object to assign to this.
Returns
this
References m_attributeMap.
Referenced by MeaXMLAttributes(), and operator=().
GetValueBool()
bool MeaXMLAttributes::GetValueBool (LPCTSTR name, bool & value, bool & isDefault) const
Returns the value of the specified attribute converted to a boolean.
Parameters
name [in] Attribute name.
value [out] Attribute value as a boolean. This parameter is set to true if the attribute contains the string "true" or "1". false is returned otherwise.
isDefault [out] true if the value is the DTD default.
Returns
true if the attribute is found.
References m_attributeMap.
Referenced by MeaPositionLogMgr::DesktopInfo::Load(), and MeaPositionLogMgr::Screen::Load().
GetValueDbl()
bool MeaXMLAttributes::GetValueDbl (LPCTSTR name, double & value, bool & isDefault) const
Returns the value of the specified attribute converted to a double.
Parameters
name [in] Attribute name.
value [out] Attribute value as a double.
isDefault [out] true if the value is the DTD default.
Returns
true if the attribute is found.
References m_attributeMap.
Referenced by MeaPositionLogMgr::DesktopInfo::Load(), MeaPositionLogMgr::Position::Load(), and MeaPositionLogMgr::Screen::Load().
GetValueInt()
bool MeaXMLAttributes::GetValueInt (LPCTSTR name, int & value, bool & isDefault) const
Returns the value of the specified attribute converted to an integer.
Parameters
name [in] Attribute name.
value [out] Attribute value as an integer.
isDefault [out] true if the value is the DTD default.
Returns
true if the attribute is found.
References m_attributeMap.
Referenced by MeaPositionLogMgr::DesktopInfo::LoadCustomPrecisions(), and MeaFileProfile::StartElementHandler().
GetValueStr()
bool MeaXMLAttributes::GetValueStr (LPCTSTR name, CString & value, bool & isDefault) const
Returns the value of the specified attribute as a string.
Parameters
name [in] Attribute name.
value [out] Attribute value as a string.
isDefault [out] true if the value is the DTD default.
Returns
true if the attribute is found.
References m_attributeMap.
Referenced by MeaPositionLogMgr::DesktopInfo::Load(), MeaPositionLogMgr::Position::Load(), MeaPositionLogMgr::Screen::Load(), MeaPositionLogMgr::DesktopInfo::LoadCustomPrecisions(), MeaPositionLogMgr::ProcessDesktopNode(), MeaPositionLogMgr::ProcessPositionNode(), and MeaFileProfile::StartElementHandler().
operator=()
MeaXMLAttributes & MeaXMLAttributes::operator= (const MeaXMLAttributes & attrs) inline
Performs a deep assignment of the specified XML attribute object.
Parameters
attrs [in] XML attribute object to assign to this.
Returns
this
References Assign().
The documentation for this class was generated from the following files:
XMLParser.h
XMLParser.cpp
Copyright 2011 C Thing Software