Meazure: Geometry.h File Reference
Geometry.h File Reference
Classes and convenience methods for working with geometry.
#include <cmath>
#include <iostream>
#include "NumericUtils.h"
Classes
struct MeaFSize
Represents a rectangular size.
struct MeaFRect
Represents a rectangular.
struct MeaFPoint
Represents a point.
Namespaces
namespace MeaGeometry
Convenience methods for calculating various geometric values (e.g.
Functions
std::ostream & operator<< (std::ostream &os, const MeaFSize &size)
Provides output of the size in the format "(cx,cy)".
MeaFSize log10 (const MeaFSize &fsize)
Calculates the log base 10 on each dimension of the specified size object and returns the results in a new size object.
MeaFSize floor (const MeaFSize &fsize)
Calculates the floor on each dimension of the specified size object and returns the results in a new size object.
MeaFSize operator- (double val, const MeaFSize &fsize)
Subtracts the specified size object from the specified value and returns a new size object.
std::ostream & operator<< (std::ostream &os, const MeaFRect &rect)
Provides output of the rectangle in the format "[top right bottom left]".
std::ostream & operator<< (std::ostream &os, const MeaFPoint &point)
Provides output of the point in the format "(x,y)".
int MeaGeometry::Scale (int value, double scaleFactor)
Multiplies the specified value by the specified scale factor.
RECT MeaGeometry::Scale (const RECT &rect, double scaleFactor)
Multiplies the top, bottom, left and right coordinates of the specified rectangle by the specified scale factor.
SIZE MeaGeometry::Scale (const SIZE &size, double scaleFactor)
Multiplies both dimensions of the specified size object by the specified scale factor.
double MeaGeometry::CalcLength (double dx, double dy)
Calculates the length corresponding to the specified x and y distances using the formula:
double MeaGeometry::CalcLength (const POINT &p1, const POINT &p2)
Calculates the length between the two specified points using the formula:
double MeaGeometry::CalcCircumference (double radius)
Calculates the circumference of the circle with the specified radius using the formula:
int MeaGeometry::CalcSector (const POINT &start, const POINT &end)
Returns the angular sector containing the vector specified by the two points.
bool MeaGeometry::IsVerticallyOriented (const POINT &start, const POINT &end)
Indicates whether the specified vector is oriented in a vertical direction.
bool MeaGeometry::IsHorizontallyOriented (const POINT &start, const POINT &end)
Indicates whether the specified vector is oriented in a horizontal direction.
double MeaGeometry::CalcAngle (const MeaFPoint &start, const MeaFPoint &end)
Returns the angle of the vector from the specified start point to the specified end point relative to the horizontal (x-axis), measured in radians.
double MeaGeometry::CalcAngle (const MeaFPoint &vertex, const MeaFPoint &p1, const MeaFPoint &p2)
Returns the angle, in radians, between the vector from the vertex to point p1 and the vector from the vertex to point p2.
Detailed Description
Classes and convenience methods for working with geometry.
Function Documentation
floor()
MeaFSize floor (const MeaFSize & fsize) inline
Calculates the floor on each dimension of the specified size object and returns the results in a new size object.
Parameters
fsize [in] Size object whose floor is to be obtained.
Returns
A new size object whose dimensions are the floor of the specified size object's dimensions.
References MeaFSize::cx, MeaFSize::cy, and floor().
Referenced by floor(), and MeaUnitsMgr::GetMinorIncr().
log10()
MeaFSize log10 (const MeaFSize & fsize) inline
Calculates the log base 10 on each dimension of the specified size object and returns the results in a new size object.
Parameters
fsize [in] Size object whose logarithm is to be obtained.
Returns
A new size object whose dimensions are the base 10 log of the specified size object's dimensions.
References MeaFSize::cx, MeaFSize::cy, and log10().
Referenced by MeaUnitsMgr::GetMinorIncr(), log10(), and MeaPrecisionPrefs::OnInitDialog().
operator-()
MeaFSize operator- (double val, const MeaFSize & fsize) inline
Subtracts the specified size object from the specified value and returns a new size object.
Parameters
val [in] The specified size object is subtracted from this value.
fsize [in] Size object to subtract from the specified value.
Returns
New size object formed by the specified size object being subtracted from the specified value.
References MeaFSize::cx, and MeaFSize::cy.
operator<<() [1/3]
std::ostream & operator<< (std::ostream & os, const MeaFPoint & point) inline
Provides output of the point in the format "(x,y)".
Parameters
os [in] Output stream to write
point [in] Point object to write
Returns
The specified output stream.
References MeaFPoint::x, and MeaFPoint::y.
operator<<() [2/3]
std::ostream & operator<< (std::ostream & os, const MeaFRect & rect) inline
Provides output of the rectangle in the format "[top right bottom left]".
Parameters
os [in] Output stream to write
rect [in] Rectangle object to write
Returns
The specified output stream.
References MeaFRect::bottom, MeaFRect::left, MeaFRect::right, and MeaFRect::top.
operator<<() [3/3]
std::ostream & operator<< (std::ostream & os, const MeaFSize & size) inline
Provides output of the size in the format "(cx,cy)".
Parameters
os [in] Output stream to write
size [in] Size object to write
Returns
The specified output stream.
References MeaFSize::cx, and MeaFSize::cy.
Copyright 2011 C Thing Software