Meazure: hooks.h File Reference
hooks.h File Reference
Hooks to pick up mouse movement information.
Macros
#define MEA_HOOKSAPI __declspec(dllimport)
#define MEA_MOUSE_MSG (WM_USER + 1)
Functions
bool MeaEnableMouseHook (void)
Enables mouse position reporting.
bool MeaDisableMouseHook (void)
Disables mouse position reporting.
Detailed Description
Hooks to pick up mouse movement information.
Function Documentation
MeaDisableMouseHook()
bool MeaDisableMouseHook (void)
Disables mouse position reporting.
This function removes the mouse hook procedure.
Returns
true if the mouse hook was removed successfully.
Referenced by MeaCursorTool::Disable(), and MeaWindowTool::Disable().
MeaEnableMouseHook()
bool MeaEnableMouseHook (void)
Enables mouse position reporting.
This function installs the mouse hook procedure that calls back to processes that are interested in the mouse pointer position as it changes.
Returns
true if the mouse hook was installed successfully.
Referenced by MeaCursorTool::Enable(), and MeaWindowTool::Enable().
Copyright 2011 C Thing Software