Meazure: LayeredWindows.h File Reference
LayeredWindows.h File Reference
Stub module that dynamically supports the Layered Windows API found on Windows 2000 and beyond.
Macros
#define WS_EX_LAYERED 0x00080000
Style for a layered window.
#define LWA_COLORKEY 0x00000001
Indicates color keyed transparency.
#define LWA_ALPHA 0x00000002
Indicates alpha blended transparency.
#define SetLayeredWindowAttributes xSetLayeredWindowAttributes
Replace the Windows API function with our function.
#define UpdateLayeredWindow xUpdateLayeredWindow
Replace the Windows API function with our function.
Functions
BOOL HaveLayeredWindows (void)
Indicates that layered windows are available.
BOOL WINAPI xSetLayeredWindowAttributes (HWND, COLORREF, BYTE, DWORD)
Sets layered windows attributes.
BOOL WINAPI xUpdateLayeredWindow (HWND, HDC, POINT *, SIZE *, HDC, POINT *, COLORREF, BLENDFUNCTION *, DWORD)
Updates a layered window from a memory bitmap.
Variables
BOOL g_enableLayeredWindows
Flag to use layered windows if they are present.
Detailed Description
Stub module that dynamically supports the Layered Windows API found on Windows 2000 and beyond.
Exactly one source file must include this header with the macro COMPILE_LAYERED_WINDOW_STUBS defined.
Function Documentation
HaveLayeredWindows()
BOOL HaveLayeredWindows (void)
Indicates that layered windows are available.
Returns
TRUE if layered windows are available.
Referenced by MeaDataWin::Create(), MeaRuler::Create(), MeaCrossHair::Create(), MeaColors::Initialize(), MeaRulerPrefs::OnInitDialog(), MeaToolsPrefs::OnInitDialog(), and MeaDataWin::OnPaint().
xSetLayeredWindowAttributes()
BOOL WINAPI xSetLayeredWindowAttributes (HWND , COLORREF , BYTE , DWORD)
Sets layered windows attributes.
The parameters are the same as those for the Windows API function SetLayeredWindowAttributes.
xUpdateLayeredWindow()
BOOL WINAPI xUpdateLayeredWindow (HWND , HDC , POINT * , SIZE * , HDC , POINT * , COLORREF , BLENDFUNCTION * , DWORD)
Updates a layered window from a memory bitmap.
The parameters are the same as those for the Windows API function UpdateLayeredWindow.
Copyright 2011 C Thing Software