Meazure: MeaPlotter Namespace Reference
MeaPlotter Namespace Reference
Plots the points for drawing various shapes (e.g.
Functions
void PlotLine (const POINT &start, const POINT &end, std::function< void(int, int)> addPoint)
The window region is composed of single pixel rectangles arranged in a line from the start point to the end point.
void PlotCircle (const POINT &center, int radius, std::function< void(int, int)> addPoint)
The circular window region is composed of single pixel rectangles arranged in a circle.
void PlotCrosshair (const SIZE &size, const SIZE &spread, int layers, std::function< void(int, int)> addPoint)
Plots the points comprising the crosshair.
Detailed Description
Plots the points for drawing various shapes (e.g.
lines, circles).
Function Documentation
PlotCircle()
void MeaPlotter::PlotCircle (const POINT & center, int radius, std::function< void(int, int)> addPoint) inline
The circular window region is composed of single pixel rectangles arranged in a circle.
The location of each rectangle is determined using an algorithm from the paper "A Fast Bresenham Type Algorithm for Drawing Circles" by John Kennedy, Mathematics Dept., Santa Monica College (http://homepage.smc.edu/kennedy_john/BCIRCLE.PDF, rkenn.nosp@m.edy@.nosp@m.ix.ne.nosp@m.tcom.nosp@m..com).
Parameters
center [in] Center of the circle
radius [in] Radius of the circle, in pixels
addPoint [in] Function called to record the plotted point (x, y)
Referenced by MeaCircle::PlotCircle().
PlotCrosshair()
void MeaPlotter::PlotCrosshair (const SIZE & size, const SIZE & spread, int layers, std::function< void(int, int)> addPoint) inline
Plots the points comprising the crosshair.
Four petals comprise the top, bottom, left and right of the crosshair. Each petal of the crosshair is made up of stacked rectangles. Each rectangle is thk high by 2 * spread wide. Each rectangle is called a layer.
          |---| spread
      ********* ---------
      *       * - thk   |
       *     *          |
       *     *          |
        *   *           |
        *   *       5 layers
         * *            |
         * *            |
          *             |
          * -------------
Parameters
size [in] total size of the crosshair
spread [in] half the width of the petal at its widest point
layers [in] number of rectangles comprising a crosshair petal
addPoint [in] Function called to record the plotted point (x, y)
Referenced by MeaCrossHair::SetRegion().
PlotLine()
void MeaPlotter::PlotLine (const POINT & start, const POINT & end, std::function< void(int, int)> addPoint) inline
The window region is composed of single pixel rectangles arranged in a line from the start point to the end point.
The location of each rectangle is determined using the Bresenham algorithm adapted from "Graphics Gems", Academic Press, 1990, p. 685. The line needs to be created in this brute force way because relying on the polygon region method produces a horrible looking line.
Parameters
start [in] Start point for the line
end [in] End point for the line
addPoint [in] Function called to record the plotted point (x, y)
Referenced by MeaLine::PlotLine().
Copyright 2011 C Thing Software