Meazure: MeaGeometry Namespace Reference
MeaGeometry Namespace Reference
Convenience methods for calculating various geometric values (e.g.
Functions
int Scale (int value, double scaleFactor)
Multiplies the specified value by the specified scale factor.
RECT Scale (const RECT &rect, double scaleFactor)
Multiplies the top, bottom, left and right coordinates of the specified rectangle by the specified scale factor.
SIZE Scale (const SIZE &size, double scaleFactor)
Multiplies both dimensions of the specified size object by the specified scale factor.
double CalcLength (double dx, double dy)
Calculates the length corresponding to the specified x and y distances using the formula:
double CalcLength (const POINT &p1, const POINT &p2)
Calculates the length between the two specified points using the formula:
double CalcCircumference (double radius)
Calculates the circumference of the circle with the specified radius using the formula:
int CalcSector (const POINT &start, const POINT &end)
Returns the angular sector containing the vector specified by the two points.
bool IsVerticallyOriented (const POINT &start, const POINT &end)
Indicates whether the specified vector is oriented in a vertical direction.
bool IsHorizontallyOriented (const POINT &start, const POINT &end)
Indicates whether the specified vector is oriented in a horizontal direction.
double CalcAngle (const MeaFPoint &start, const MeaFPoint &end)
Returns the angle of the vector from the specified start point to the specified end point relative to the horizontal (x-axis), measured in radians.
double CalcAngle (const MeaFPoint &vertex, const MeaFPoint &p1, const MeaFPoint &p2)
Returns the angle, in radians, between the vector from the vertex to point p1 and the vector from the vertex to point p2.
Detailed Description
Convenience methods for calculating various geometric values (e.g.
circumference, angle).
Function Documentation
CalcAngle() [1/2]
double MeaGeometry::CalcAngle (const MeaFPoint & start, const MeaFPoint & end) inline
Returns the angle of the vector from the specified start point to the specified end point relative to the horizontal (x-axis), measured in radians.
Using the default coordinate system (i.e. positive y-axis pointed down from the origin), positive angles are measured clockwise from the horizontal to the vector. The following formula is used:
Parameters
start [in] Starting point for the vector whose angle is to be determined.
end [in] Ending point for the vector whose angle is to be determined.
Returns
Angle between the x-axis and the line, in radians. Degenerate cases return 0.0.
References MeaNumericUtils::IsZeroF(), MeaFPoint::x, and MeaFPoint::y.
Referenced by MeaAngleTool::RecordPosition(), MeaCircleTool::RecordPosition(), MeaLineTool::RecordPosition(), MeaRectTool::RecordPosition(), MeaWindowTool::RecordPosition(), MeaAngleTool::Update(), MeaCircleTool::Update(), MeaLineTool::Update(), MeaRectTool::Update(), MeaWindowTool::Update(), and MeaAngleTool::UpdateBisector().
CalcAngle() [2/2]
double MeaGeometry::CalcAngle (const MeaFPoint & vertex, const MeaFPoint & p1, const MeaFPoint & p2) inline
Returns the angle, in radians, between the vector from the vertex to point p1 and the vector from the vertex to point p2.
Using the default coordinate system (i.e. positive y-axis pointed down from the origin), positive angles are measured clockwise from the vertex-p1 line to the vertex-p2 line.
Parameters
vertex [in] Intersection point for the two lines.
p1 [in] Forms the end point for the first line from the vertex.
p2 [in] Forms the end point for the second line from the vertex.
Returns
Angle between the vectors vertex-p1 and vertex-p2.
References MeaNumericUtils::IsZeroF(), MeaFPoint::x, and MeaFPoint::y.
CalcCircumference()
double MeaGeometry::CalcCircumference (double radius) inline
Calculates the circumference of the circle with the specified radius using the formula:
Parameters
radius [in] Radius of the circle.
Returns
Circumference of the circle.
Referenced by MeaCircle::Create().
CalcLength() [1/2]
double MeaGeometry::CalcLength (const POINT & p1, const POINT & p2) inline
Calculates the length between the two specified points using the formula:
Parameters
p1 [in] Point 1.
p2 [in] Point 2.
Returns
Length between point 1 and point 2.
References CalcLength().
CalcLength() [2/2]
double MeaGeometry::CalcLength (double dx, double dy) inline
Calculates the length corresponding to the specified x and y distances using the formula:
Parameters
dx [in] X distance.
dy [in] Y distance.
Returns
Length corresponding to the vertical and horizontal distances.
Referenced by CalcLength(), MeaDataWin::CalcWidth(), MeaCircle::Create(), MeaLine::Create(), MeaCircle::GetRadius(), MeaPosition::RecordDistance(), MeaDataWin::ShowDistance(), and MeaDataDisplay::ShowDistance().
CalcSector()
int MeaGeometry::CalcSector (const POINT & start, const POINT & end) inline
Returns the angular sector containing the vector specified by the two points.
A circle centered at the starting point of the vector is divided into eight 45 degree sectors numbered -4 through 4 inclusive. The sectors are numbered according to the following table of angle ranges. Positive angles go clockwise from the positive x-axis.
Angle Range (deg) Sector
[0, 45) 1
[45, 90) 2
[90, 135) 3
[135, 180) 4
[180, 225] -4
(225, 270] -3
(270, 315] -2
(315, 0] -1
Zero vector 0
Parameters
start [in] Starting point for the vector.
end [in] Ending point for the vector.
Returns
The circular sector corresponding to the vector in the range [-4.0, 4.0].
Referenced by IsHorizontallyOriented(), and IsVerticallyOriented().
IsHorizontallyOriented()
bool MeaGeometry::IsHorizontallyOriented (const POINT & start, const POINT & end) inline
Indicates whether the specified vector is oriented in a horizontal direction.
A vector is considered horizontally oriented if it is in sector +/-1 or +/-4. See the documentation for the CalcSector method.
Parameters
start [in] Starting point for the vector
end [in] Ending point for the vector
Returns
true if the specified vector is horizontally oriented. Returns false if the vector is vertically oriented or is the empty vector.
References CalcSector().
IsVerticallyOriented()
bool MeaGeometry::IsVerticallyOriented (const POINT & start, const POINT & end) inline
Indicates whether the specified vector is oriented in a vertical direction.
A vector is considered vertically oriented if it is in sector +/-2 or +/-3. See the documentation for the CalcSector method.
Parameters
start [in] Starting point for the vector
end [in] Ending point for the vector
Returns
true if the specified vector is vertically oriented. Returns false if the vector is horizontally oriented or is the empty vector.
References CalcSector().
Referenced by MeaAngleTool::OnCHMove(), MeaCircleTool::OnCHMove(), MeaLineTool::OnCHMove(), MeaPointTool::OnCHMove(), and MeaRectTool::OnCHMove().
Scale() [1/3]
RECT MeaGeometry::Scale (const RECT & rect, double scaleFactor) inline
Multiplies the top, bottom, left and right coordinates of the specified rectangle by the specified scale factor.
Parameters
rect [in] Rectangle to scale
scaleFactor [in] Multiplier for each coordinate
Returns
Scaled rectangle with each coordinate rounded to the nearest whole number.
References Scale().
Scale() [2/3]
SIZE MeaGeometry::Scale (const SIZE & size, double scaleFactor) inline
Multiplies both dimensions of the specified size object by the specified scale factor.
Parameters
size [in] Size object to scale
scaleFactor [in] Multiplier for both dimensions
Returns
Scaled size object with each dimension rounded to the nearest whole number.
References Scale().
Scale() [3/3]
int MeaGeometry::Scale (int value, double scaleFactor) inline
Multiplies the specified value by the specified scale factor.
Parameters
value [in] Value to scale
scaleFactor [in] Multiplier for the value
Returns
Scaled value rounded to the nearest whole number.
Referenced by MeaDataDisplay::Create(), MeaMagnifier::Create(), MeaDataDisplay::DataItem::CreateSpinButton(), AppView::OnCreate(), and Scale().
Copyright 2011 C Thing Software