Meazure: ev Namespace Reference
ev Namespace Reference
exval uses the namespace ev for everything.
Classes
class AttributeDecl
Represents an attribute declaration.
class ContentModel
Represents a node in an XML element content model.
class DFA
This class represents a deterministic finite state automaton (DFA) (i.e.
class ElementDecl
Represents an element declaration.
class IValidationHandler
An application class mixin inherits from the IValidationHandler interface and overrides the HandleValidationError method.
class ParseNode
Represents a node in the parse tree that is constructed by parsing the content model.
class State
A deterministic finite state automata (DFA) consists of a set of states.
class ValidationError
Class to represent a validation error.
class Validator
The star of the show, this call performs XML validation for the expat parser.
Typedefs
typedef boost::char_separator< char > EVSeparator
Separator character for tokenizing.
typedef boost::format EVFormat
Printf-like output format string.
typedef boost::tokenizer< EVSeparator > EVTokenizer
Tokenizer for parsing entities, enumeration, etc.
typedef std::string EVString
String type.
typedef std::ostream EVOstream
Output stream type.
typedef std::set< EVString > SymbolSet
Element name set.
typedef SymbolSet::iterator SymbolSetIter
Element name set iterator.
Functions
EVOstream & operator<< (EVOstream &stream, const ContentModel &contentModel)
Output stream operator for a content model.
EVOstream & operator<< (EVOstream &stream, const ParseNode *node)
Output stream operator for a parse node.
EVOstream & operator<< (EVOstream &stream, const State *state)
Output stream operator for a state.
EVOstream & operator<< (EVOstream &stream, const DFA *dfa)
Output stream operator for a DFA.
EVOstream & operator<< (EVOstream &stream, const ElementDecl *elementDecl)
Output stream operator for an element declaration.
EVOstream & operator<< (EVOstream &stream, const AttributeDecl *attributeDecl)
Output stream operator for an attribute declaration.
EVOstream & operator<< (EVOstream &stream, const Validator &validator)
Output stream operator for a validator.
Detailed Description
exval uses the namespace ev for everything.
Function Documentation
operator<<() [1/7]
EVOstream & ev::operator<< (EVOstream & stream, const AttributeDecl * attributeDecl)
Output stream operator for an attribute declaration.
Used to dump the state of the attribute declaration to the specified output stream for debugging purposes.
Parameters
stream [in] Output stream.
attributeDecl [in] Attribute declaration to output.
Returns
Output stream.
References ev::AttributeDecl::CDATA, ev::AttributeDecl::ENTITIES, ev::AttributeDecl::ENTITY, ev::AttributeDecl::Enumerated, EV_T, ev::AttributeDecl::ID, ev::AttributeDecl::IDREF, ev::AttributeDecl::IDREFS, ev::AttributeDecl::m_defValue, ev::AttributeDecl::m_name, ev::AttributeDecl::m_required, ev::AttributeDecl::m_type, ev::AttributeDecl::m_values, ev::AttributeDecl::NMTOKEN, ev::AttributeDecl::NMTOKENS, and ev::AttributeDecl::NOTATION.
operator<<() [2/7]
EVOstream & ev::operator<< (EVOstream & stream, const ContentModel & contentModel)
Output stream operator for a content model.
Used to dump the state of the content model to the specified output stream for debugging purposes.
Parameters
stream [in] Output stream.
contentModel [in] Content model to output.
Returns
Output stream.
References ev::ContentModel::AnyCat, ev::ContentModel::AnyType, ev::ContentModel::AtEnd(), ev::ContentModel::ChoiceType, ev::ContentModel::ComplexCat, ev::ContentModel::EmptyCat, ev::ContentModel::EmptyType, EV_T, ev::ContentModel::GetChild(), ev::ContentModel::GetChildIter(), ev::ContentModel::m_category, ev::ContentModel::m_name, ev::ContentModel::m_quantity, ev::ContentModel::m_root, ev::ContentModel::m_type, ev::ContentModel::MixedCat, ev::ContentModel::MixedType, ev::ContentModel::NameType, ev::ContentModel::NoneQuant, ev::ContentModel::OptQuant, ev::ContentModel::PlusQuant, ev::ContentModel::PureChoiceCat, ev::ContentModel::PureSeqCat, ev::ContentModel::RepQuant, and ev::ContentModel::SeqType.
operator<<() [3/7]
EVOstream & ev::operator<< (EVOstream & stream, const DFA * dfa)
Output stream operator for a DFA.
Used to dump the state of the DFA to the specified output stream for debugging purposes.
Parameters
stream [in] Output stream.
dfa [in] DFA to output.
Returns
Output stream.
References EV_T, ev::DFA::m_parseTree, and ev::DFA::m_states.
operator<<() [4/7]
EVOstream & ev::operator<< (EVOstream & stream, const ElementDecl * elementDecl)
Output stream operator for an element declaration.
Used to dump the state of the element declaration to the specified output stream for debugging purposes.
Parameters
stream [in] Output stream.
elementDecl [in] Element declaration to output.
Returns
Output stream.
References EV_T, ev::DFA::GetId(), ev::ElementDecl::m_attributes, and ev::ElementDecl::m_dfa.
operator<<() [5/7]
EVOstream & ev::operator<< (EVOstream & stream, const ParseNode * node)
Output stream operator for a parse node.
Used to dump the state of the parse node to the specified output stream for debugging purposes.
Parameters
stream [in] Output stream.
node [in] Parse node to output.
Returns
Output stream.
References ev::ParseNode::Choice, ev::ParseNode::End, ev::ParseNode::Epsilon, EV_T, ev::ParseNode::GetLeft(), ev::ParseNode::GetRight(), ev::ParseNode::GetSymbol(), ev::ParseNode::GetSymbolSet(), ev::ParseNode::GetType(), ev::ParseNode::HaveLeft(), ev::ParseNode::HaveRight(), ev::ParseNode::m_firstPos, ev::ParseNode::m_followPos, ev::ParseNode::m_id, ev::ParseNode::m_lastPos, ev::ParseNode::m_nullable, ev::ParseNode::Name, ev::ParseNode::Opt, ev::ParseNode::Plus, ev::ParseNode::Rep, and ev::ParseNode::Seq.
operator<<() [6/7]
EVOstream & ev::operator<< (EVOstream & stream, const State * state)
Output stream operator for a state.
Used to dump the state object to the specified output stream for debugging purposes.
Parameters
stream [in] Output stream.
state [in] State object to output.
Returns
Output stream.
References ev::State::Any, ev::State::Empty, EV_T, ev::State::m_accepting, ev::State::m_id, ev::State::m_positions, ev::State::m_transitions, ev::State::m_type, ev::State::Mixed, and ev::State::Normal.
operator<<() [7/7]
EVOstream & ev::operator<< (EVOstream & stream, const Validator & validator)
Output stream operator for a validator.
Used to dump the state of the validator to the specified output stream for debugging purposes.
Parameters
stream [in] Output stream.
validator [in] Validator object to output.
Returns
Output stream.
References EV_T, ev::Validator::m_dfas, ev::Validator::m_elementDecls, ev::Validator::m_entities, and ev::Validator::m_notations.
Copyright 2011 C Thing Software