Meazure: MeaColors Namespace Reference
MeaColors Namespace Reference
A color style sheet class that provides the colors and opacities used by the crosshairs, lines and other graphic elements.
Classes
struct CMY
Represents a color in the Cyan-Magenta-Yellow color space.
struct CMYK
Represents a color in the Cyan-Magenta-Yellow-Black color space.
struct ColorTableEntry
Entry in a color matching table.
struct HSL
Represents a color in the Hue (H), Saturation (S), and Lightness (L) color space.
struct Lab
Represents a color in the CIE L*a*b* color space.
struct XYZ
Represents a color in the CIE 1931 XYZ color space.
struct YCbCr
Represents a color in the Luminance (Y), Blue-Difference (Cb) and Red-Difference (Cr) chrominance color space.
struct YIQ
Represents a color in the Luminance (Y), In-phase (I) and Quadrature (Q) chrominance color space.
Enumerations
enum Item {
LineFore ,
CrossHairBack ,
CrossHairBorder ,
CrossHairHilite ,
CrossHairOpacity ,
RulerBack ,
RulerBorder ,
RulerOpacity
}
Identifies the item whose color and opacity are maintained by this class.
Functions
void Reset ()
Resets all colors to their default values.
void SaveProfile (MeaProfile &profile)
Persists the color settings to the specified profile.
void LoadProfile (MeaProfile &profile)
Restores the color settings from the specified profile.
void MasterReset ()
Called when the master application reset is invoked.
void Set (Item item, COLORREF color)
Sets the specified item to the specified color.
void SetA (Item item, std::uint8_t opacity)
Sets the specified item to the specified opacity.
COLORREF Get (Item item)
Returns the color of the specified item.
std::uint8_t GetR (Item item)
Returns the value of the red color component of the specified item.
std::uint8_t GetG (Item item)
Returns the value of the green color component of the specified item.
std::uint8_t GetB (Item item)
Returns the value of the blue color component of the specified item.
std::uint8_t GetA (Item item)
Returns the opacity of the specified item.
COLORREF GetDefault (Item item)
Returns the default color for the specified item.
COLORREF InterpolateColor (COLORREF startRGB, COLORREF endRGB, int percent)
Performs linear interpolation between the specified RGB color.
double ColorDifference (const Lab &color1, const Lab &color2)
Calculates the visual difference between the two specified colors.
const ColorTableEntry * MatchBasicColor (COLORREF rgb)
Attempts to match the specified color against the Web basic colors (https://en.wikipedia.org/wiki/Web_colors).
const ColorTableEntry * MatchExtendedColor (COLORREF rgb)
Attempts to match the specified color against the Web extended colors (https://en.wikipedia.org/wiki/Web_colors).
const ColorTableEntry * MatchColor (const ColorTableEntry *table, COLORREF rgb)
Attempts to match the specified color against the specified table of colors.
constexpr CMY RGBtoCMY (COLORREF rgb)
Converts from the RGB color space to the Cyan (C), Magenta (M) and Yellow (Y) color space.
CMYK RGBtoCMYK (COLORREF rgb)
Converts from the RGB color space to the Cyan (C), Magenta (M), Yellow (Y) and Black (K) color space.
HSL RGBtoHSL (COLORREF rgb)
Converts from the RGB color space to the Hue (H), Saturation (S) and Lightness (L) color space.
COLORREF HSLtoRGB (const HSL &hsl)
Converts from the HSL color space to the RGB color space.
YCbCr RGBtoYCbCr (COLORREF rgb)
Converts from the RGB color space to the Luminance (Y), Blue-Difference (Cb), Red-Difference (Cr) color space.
YIQ RGBtoYIQ (COLORREF rgb)
Converts from the RGB color space to the Luminance (Y), In-phase (I), Quadrature (Q) color space.
XYZ RGBtoXYZ (COLORREF rgb)
Converts from the RGB color space to the CIE 1931 XYZ color space.
Lab XYZtoLab (const XYZ &xyz)
Converts from the CIE 1931 XYZ color space to the CIE L*a*b* color space.
Lab RGBtoLab (COLORREF rgb)
Converts the specified RGB color to the CIE L*a*b* color space.
Detailed Description
A color style sheet class that provides the colors and opacities used by the crosshairs, lines and other graphic elements.
Enumeration Type Documentation
Item
enum MeaColors::Item
Identifies the item whose color and opacity are maintained by this class.
Enumerator
LineFore
Line foreground color.
CrossHairBack
Crosshair background color.
CrossHairBorder
Crosshair edge color.
CrossHairHilite
Crosshair highlight color.
CrossHairOpacity
Opacity of the crosshair.
RulerBack
Ruler background color.
RulerBorder
Ruler edge and tick mark color.
RulerOpacity
Ruler opacity.
Function Documentation
ColorDifference()
double MeaColors::ColorDifference (const Lab & color1, const Lab & color2)
Calculates the visual difference between the two specified colors.
The difference is calculated using the CIEDE2000 algorithm. See https://en.wikipedia.org/wiki/Color_difference#CIEDE2000, http://www.brucelindbloom.com/index.html?Eqn_DeltaE_CIE2000.html and https://hajim.rochester.edu/ece/sites/gsharma/ciede2000/ciede2000noteCRNA.pdf.
Parameters
color1 [in] First color in the difference
color2 [in] Second color in the difference
Returns
A value representing the difference between the two specified colors. The smaller the difference, the visually closer the two colors. The value is never negative.
References MeaNumericUtils::DegToRad(), and MeaNumericUtils::IsZeroF().
Referenced by MatchColor().
Get()
COLORREF MeaColors::Get (Item item)
Returns the color of the specified item.
Parameters
item [in] Item whose color is desired.
Returns
Color of the specified item.
Referenced by MeaAngleTool::ColorsChanged(), MeaCircleTool::ColorsChanged(), MeaGridTool::ColorsChanged(), MeaLineTool::ColorsChanged(), MeaOriginTool::ColorsChanged(), MeaPointTool::ColorsChanged(), MeaRectTool::ColorsChanged(), MeaRulerTool::ColorsChanged(), MeaWindowTool::ColorsChanged(), MeaAngleTool::Create(), MeaCircleTool::Create(), MeaLineTool::Create(), MeaPointTool::Create(), MeaRectTool::Create(), MeaRulerTool::Enable(), and AppView::OnPreferences().
GetA()
std::uint8_t MeaColors::GetA (Item item)
Returns the opacity of the specified item.
Parameters
item [in] Item whose opacity is desired.
Returns
Opacity of the specified item, where 0 is completely transparent and 255 is completely opaque.
Referenced by MeaAngleTool::ColorsChanged(), MeaCircleTool::ColorsChanged(), MeaCursorTool::ColorsChanged(), MeaLineTool::ColorsChanged(), MeaPointTool::ColorsChanged(), MeaRectTool::ColorsChanged(), MeaRulerTool::ColorsChanged(), MeaWindowTool::ColorsChanged(), MeaAngleTool::Create(), MeaCircleTool::Create(), MeaCursorTool::Create(), MeaLineTool::Create(), MeaPointTool::Create(), MeaRectTool::Create(), MeaWindowTool::Create(), MeaRulerTool::Enable(), and AppView::OnPreferences().
GetB()
std::uint8_t MeaColors::GetB (Item item)
Returns the value of the blue color component of the specified item.
Parameters
item [in] Item whose color component is desired.
Returns
Blue color component of the specified item.
GetDefault()
COLORREF MeaColors::GetDefault (Item item)
Returns the default color for the specified item.
Parameters
item [in] Item whose default color is desired.
Returns
Default color for the specified item.
Referenced by MeaToolsPrefs::OnDefBackColor(), MeaRulerPrefs::OnDefBkColor(), MeaRulerPrefs::OnDefBorderColor(), MeaToolsPrefs::OnDefBorderColor(), MeaToolsPrefs::OnDefHiliteColor(), and MeaToolsPrefs::OnDefLineColor().
GetG()
std::uint8_t MeaColors::GetG (Item item)
Returns the value of the green color component of the specified item.
Parameters
item [in] Item whose color component is desired.
Returns
Green color component of the specified item.
GetR()
std::uint8_t MeaColors::GetR (Item item)
Returns the value of the red color component of the specified item.
Parameters
item [in] Item whose color component is desired.
Returns
Red color component of the specified item.
HSLtoRGB()
COLORREF MeaColors::HSLtoRGB (const HSL & hsl)
Converts from the HSL color space to the RGB color space.
The conversion is done using the algorithm for HSL to RGB conversion presented at http://www.easyrgb.com/en/math.php. The input range is H in degrees in the range [0, 360), and S and L as percentages in the range [0, 100]. The output range is [0, 255].
Parameters
hsl [in] HSL color.
Returns
RGB color
Referenced by InterpolateColor().
InterpolateColor()
COLORREF MeaColors::InterpolateColor (COLORREF startRGB, COLORREF endRGB, int percent)
Performs linear interpolation between the specified RGB color.
The interpolation is performed in HSL space, which provides a more visually appealing result. The result of the interpolation is converted back to RGB.
Parameters
startRGB [in] Starting interpolation point.
endRGB [in] Ending interpolation point.
percent [in] Interpolation point between startRGB and endRGB as a percentage.
Returns
Interpolated color.
References HSLtoRGB(), and RGBtoHSL().
Referenced by MeaRuler::DrawRuler().
LoadProfile()
void MeaColors::LoadProfile (MeaProfile & profile)
Restores the color settings from the specified profile.
Parameters
profile [in] Profile from which the color settings are restored.
References CrossHairBack, CrossHairBorder, CrossHairHilite, CrossHairOpacity, LineFore, MeaProfile::ReadInt(), RulerBack, RulerBorder, RulerOpacity, and MeaProfile::UserInitiated().
Referenced by AppView::LoadProfile().
MasterReset()
void MeaColors::MasterReset ()
Called when the master application reset is invoked.
The colors are reset to their default values.
Referenced by AppView::MasterReset().
MatchBasicColor()
const MeaColors::ColorTableEntry * MeaColors::MatchBasicColor (COLORREF rgb)
Attempts to match the specified color against the Web basic colors (https://en.wikipedia.org/wiki/Web_colors).
The CIEDE2000 color difference algorithm is used to find the best match.
Parameters
rgb [in] Color to match
Returns
Closest basic web color to the specified color. Never returns nullptr.
References MatchColor().
Referenced by MeaMagnifier::Draw().
MatchColor()
const MeaColors::ColorTableEntry * MeaColors::MatchColor (const ColorTableEntry * table, COLORREF rgb)
Attempts to match the specified color against the specified table of colors.
The CIEDE2000 color difference algorithm is used to find the best match.
Parameters
table [in] Color table to match against. Last entry must have a nullptr name.
rgb [in] Color to match
Returns
Closest color in the table to the specified color. Return nullptr if the specified table is empty.
References ColorDifference(), and RGBtoLab().
Referenced by MatchBasicColor(), and MatchExtendedColor().
MatchExtendedColor()
const MeaColors::ColorTableEntry * MeaColors::MatchExtendedColor (COLORREF rgb)
Attempts to match the specified color against the Web extended colors (https://en.wikipedia.org/wiki/Web_colors).
The CIEDE2000 color difference algorithm is used to find the best match.
Parameters
rgb [in] Color to match
Returns
Closest extended web color to the specified color. Never returns nullptr.
References MatchColor().
Referenced by MeaMagnifier::Draw().
RGBtoCMY()
constexpr CMY MeaColors::RGBtoCMY (COLORREF rgb) constexpr
Converts from the RGB color space to the Cyan (C), Magenta (M) and Yellow (Y) color space.
The conversion is done using the algorithm for RGB to CMY conversion presented at http://www.easyrgb.com/en/math.php. The input and output range is [0, 255].
Parameters
rgb [in] RGB color
Returns
CMY color
Referenced by MeaMagnifier::Draw(), and RGBtoCMYK().
RGBtoCMYK()
MeaColors::CMYK MeaColors::RGBtoCMYK (COLORREF rgb)
Converts from the RGB color space to the Cyan (C), Magenta (M), Yellow (Y) and Black (K) color space.
The conversion is done using the algorithm presented at http://www.easyrgb.com/en/math.php. The input and output range is [0, 255].
Parameters
rgb [in] RGB color
Returns
CMYK color
References RGBtoCMY().
Referenced by MeaMagnifier::Draw().
RGBtoHSL()
MeaColors::HSL MeaColors::RGBtoHSL (COLORREF rgb)
Converts from the RGB color space to the Hue (H), Saturation (S) and Lightness (L) color space.
The conversion is done using the algorithm for RGB to HSL conversion presented at http://www.easyrgb.com/en/math.php. The input range is [0, 255]. The output range is scaled such that H values are in degrees in the range [0, 360), and S and L values are percentages in the range [0, 100].
Parameters
rgb [in] RGB color
Returns
HSL color
References MeaNumericUtils::IsEqualF(), and MeaNumericUtils::IsZeroF().
Referenced by MeaMagnifier::Draw(), and InterpolateColor().
RGBtoLab()
MeaColors::Lab MeaColors::RGBtoLab (COLORREF rgb)
Converts the specified RGB color to the CIE L*a*b* color space.
This is a convenience function which converts the RGB color to XYZ and then converts the XYZ value to Lab. See the RGBtoXYZ and XYZtoLab functions for details on these conversions.
Parameters
rgb [in] RGB color
Returns
L*a*b* color
References RGBtoXYZ(), and XYZtoLab().
Referenced by MatchColor().
RGBtoXYZ()
MeaColors::XYZ MeaColors::RGBtoXYZ (COLORREF rgb)
Converts from the RGB color space to the CIE 1931 XYZ color space.
The conversion is done assuming inputs in the Standard RGB color space and a D65 2 degree standard illuminant. The input range is [0, 255]. The output is scaled by 100.0 resulting in the X range [0.0, 95.0470], Y [0.0, 100.0] and Z [0.0, 108.8830]. See http://www.brucelindbloom.com/index.html?Math.html and http://www.easyrgb.com/en/math.php for more information.
Parameters
rgb [in] RGB color
Returns
XYZ color
Referenced by RGBtoLab().
RGBtoYCbCr()
MeaColors::YCbCr MeaColors::RGBtoYCbCr (COLORREF rgb)
Converts from the RGB color space to the Luminance (Y), Blue-Difference (Cb), Red-Difference (Cr) color space.
The conversion is done using the ITU-R BT.601 coefficients for digital YCbCr from digital RGB with input range [0, 255]. The output range is [16, 235] for Y, and [16, 240] for both Cb and Cr)values. See https://en.wikipedia.org/wiki/YCbCr for more information.
Parameters
rgb [in] RGB color
Returns
YCbCr color
Referenced by MeaMagnifier::Draw().
RGBtoYIQ()
MeaColors::YIQ MeaColors::RGBtoYIQ (COLORREF rgb)
Converts from the RGB color space to the Luminance (Y), In-phase (I), Quadrature (Q) color space.
The conversion is done using the NTSC 1953 colorimetry coefficients. The input range is [0, 255]. The output range is [0, 255] for Y, [-152, 152] I and [-133, 133] for quadrature. See https://en.wikipedia.org/wiki/YIQ for more information.
Parameters
rgb [in] RGB color
Returns
YIQ color
Referenced by MeaMagnifier::Draw().
SaveProfile()
void MeaColors::SaveProfile (MeaProfile & profile)
Persists the color settings to the specified profile.
Parameters
profile [in] Profile into which the color settings are persisted.
References CrossHairBack, CrossHairBorder, CrossHairHilite, CrossHairOpacity, LineFore, RulerBack, RulerBorder, RulerOpacity, MeaProfile::UserInitiated(), and MeaProfile::WriteInt().
Referenced by AppView::SaveProfile().
Set()
void MeaColors::Set (Item item, COLORREF color)
Sets the specified item to the specified color.
Parameters
item [in] Color item to set.
color [in] Color to set.
Referenced by AppView::ApplyPreferences().
SetA()
void MeaColors::SetA (Item item, std::uint8_t opacity)
Sets the specified item to the specified opacity.
Parameters
item [in] Item whose opacity is to be set.
opacity [in] Opacity to set, where 0 is completely transparent and 255 is completely opaque.
Referenced by AppView::ApplyPreferences().
XYZtoLab()
MeaColors::Lab MeaColors::XYZtoLab (const XYZ & xyz)
Converts from the CIE 1931 XYZ color space to the CIE L*a*b* color space.
The conversion is done assuming the Standard RGB color space and a D65 2 degree standard illuminant. The inputs are scaled XYZ with ranges X [0.0, 95.0470], Y [0.0, 100.0000] and Z [0.0, 108.8830]. The output range for L is [0.0, 100.0], and unbound for a and b. See http://www.brucelindbloom.com/index.html?Math.html and http://www.easyrgb.com/en/math.php for more information.
Parameters
xyz [in] XYZ color
Returns
L*a*b* color
Referenced by RGBtoLab().
Copyright 2011 C Thing Software