Meazure: MeaLayout Namespace Reference
MeaLayout Namespace Reference
Utility methods for performing various window layout tasks.
Functions
void AlignLeft (int leftX,...)
Aligns the specified windows such that their left edges all begin at the specified x location.
void AlignRight (int leftX,...)
Aligns the specified windows such that their right edges are all aligned.
void AlignCenter (int topY,...)
Aligns the specified windows such that they all share a common vertical center.
void AlignRightTo (const CWnd *baseWnd,...)
Performs a right alignment of the specified windows relative to the right edge of the specified base window.
void PlaceAfter (const CWnd &frontWnd, const CWnd &backWnd, int spacing)
Places the back window after the specified front window and separates them by the specified spacing.
bool SetWindowPos (const CWnd &wnd, int x, int y)
Sets the position of the specified window.
bool SetWindowSize (const CWnd &wnd, int cx, int cy)
Sets the size of the specified window.
int GetWindowHeight (const CWnd &wnd)
Returns the height of the specified window.
bool SetWindowHeight (const CWnd &wnd, int cy)
Sets the height of the window.
bool MoveWindowHeight (const CWnd &wnd, int cy)
Moves the specified window vertically.
void GetBoundingSize (SIZE *sizep, const CWnd *parentWnd)
Calculates the bounding dimensions for all the children of the specified window.
bool ScreenToClientX (const CWnd &wnd, int &x)
Converts the x position in screen coordinates to an x position in the specified window's coordinate system.
bool ScreenToClientY (const CWnd &wnd, int &y)
Converts the y position in screen coordinates to a y position in the specified window's coordinate system.
void AlphaBlend (CDC &dstDC, const CDC &srcDC, int width, int height, BYTE alpha)
Performs and alpha blend on the two specified device contexts.
void DrawOpacityBackground (const CWnd &wnd, CDC &dc, const MeaScreenProvider &screenProvider, const MeaUnitsProvider &unitsProvider)
Draws an image to use as a background for use in setting the a control's opacity.
int GetEffectiveDPI (const CWnd &wnd)
Returns the effective screen DPI.
int GetDPIScalePercent (const CWnd &wnd)
Returns the screen DPI scale factor as a percentage.
double GetDPIScaleFactor (const CWnd &wnd)
Returns the screen DPI scale factor.
Detailed Description
Utility methods for performing various window layout tasks.
Function Documentation
AlignCenter()
void MeaLayout::AlignCenter (int topY, ...)
Aligns the specified windows such that they all share a common vertical center.
The top of the tallest window begins at the specified y position.
Parameters
topY [in] Tallest window begins at this y position, in pixels.
... [in] CWnd pointers terminated by nullptr.
References SetWindowPos().
Referenced by MeaMagnifier::Create(), MeaDataDisplay::CreateRegionSection(), and MeaDataDisplay::CreateScreenSection().
AlignLeft()
void MeaLayout::AlignLeft (int leftX, ...)
Aligns the specified windows such that their left edges all begin at the specified x location.
Parameters
leftX [in] Align each window's left edge to this x position, in pixels.
... [in] CWnd pointers terminated by nullptr.
References SetWindowPos().
AlignRight()
void MeaLayout::AlignRight (int leftX, ...)
Aligns the specified windows such that their right edges are all aligned.
The widest window is positioned at the specified x location.
Parameters
leftX [in] Widest window starts at this x position, in pixels.
... [in] CWnd pointers terminated by nullptr.
References SetWindowPos().
Referenced by MeaDataDisplay::CreateRegionSection(), and MeaDataDisplay::CreateScreenSection().
AlignRightTo()
void MeaLayout::AlignRightTo (const CWnd * baseWnd, ...)
Performs a right alignment of the specified windows relative to the right edge of the specified base window.
Parameters
baseWnd [in] Align windows relative to this base window.
... [in] CWnd pointers terminated by nullptr.
References SetWindowPos().
Referenced by MeaDataDisplay::CreateRegionSection(), and MeaDataDisplay::CreateScreenSection().
AlphaBlend()
void MeaLayout::AlphaBlend (CDC & dstDC, const CDC & srcDC, int width, int height, BYTE alpha)
Performs and alpha blend on the two specified device contexts.
The resulting blend is stored in the destination device context. The device contexts must be the same size.
Parameters
dstDC [in] Destination device context.
srcDC [in] Source device context.
width [in] Width of the device contexts, in pixels.
height [in] Height of the device contexts, in pixels.
alpha [in] Opacity value between 0 (transparent) and 255 (opaque).
Referenced by MeaCrossHair::OnPaint(), MeaRuler::OnPaint(), and MeaDataWin::OnPaint().
DrawOpacityBackground()
void MeaLayout::DrawOpacityBackground (const CWnd & wnd, CDC & dc, const MeaScreenProvider & screenProvider, const MeaUnitsProvider & unitsProvider)
Draws an image to use as a background for use in setting the a control's opacity.
Parameters
wnd [in] Window representing the control.
dc [in] Device context into which to draw the background.
screenProvider [in] Screen information provider
unitsProvider [in] Units information provider
References MeaUnitsProvider::ConvertToPixels(), MeaScreenProvider::GetScreenIter(), MeaScreenProvider::GetScreenRes(), and MeaInchesId.
Referenced by MeaRuler::Create(), MeaCrossHair::Create(), and MeaDataWin::OnPaint().
GetBoundingSize()
void MeaLayout::GetBoundingSize (SIZE * sizep, const CWnd * parentWnd)
Calculates the bounding dimensions for all the children of the specified window.
Parameters
sizep [out] Bounding dimensions encompassing all child windows.
parentWnd [in] All child windows of this window form the bounding dimensions.
Referenced by MeaDataDisplay::Create(), MeaDataDisplay::CreateRegionSection(), and MeaDataDisplay::CreateScreenSection().
GetDPIScaleFactor()
double MeaLayout::GetDPIScaleFactor (const CWnd & wnd)
Returns the screen DPI scale factor.
The scale factor is calculated as:
Parameters
wnd [in] Window whose DPI scale factor is to be obtained
Returns
Screen DPI scale factor.
Referenced by MeaCrossHair::Create(), MeaDataDisplay::Create(), MeaMagnifier::Create(), MeaDataDisplay::DataItem::CreateSpinButton(), and AppView::OnCreate().
GetDPIScalePercent()
int MeaLayout::GetDPIScalePercent (const CWnd & wnd)
Returns the screen DPI scale factor as a percentage.
The scale factor is calculated as:
Parameters
wnd [in] Window whose DPI scale factor is to be obtained
Returns
Screen DPI scale factor percentage.
Referenced by MeaMagnifier::Create(), MeaDataDisplay::CreateScreenSection(), and AppFrame::CreateToolbar().
GetEffectiveDPI()
int MeaLayout::GetEffectiveDPI (const CWnd & wnd)
Returns the effective screen DPI.
Parameters
wnd [in] Window whose DPI is to be obtained
Returns
Effective DPI.
Referenced by MeaImageButton::Create().
GetWindowHeight()
int MeaLayout::GetWindowHeight (const CWnd & wnd) inline
Returns the height of the specified window.
Parameters
wnd [in] Window whose height is desired.
Returns
Height of the window in pixels.
Referenced by AppView::CheckMargins(), MeaToolsPrefs::OnInitDialog(), AppView::ViewMagnifier(), AppView::ViewScreenInfo(), and AppView::ViewToolInfo().
MoveWindowHeight()
bool MeaLayout::MoveWindowHeight (const CWnd & wnd, int cy) inline
Moves the specified window vertically.
Parameters
wnd [in] Window to be moved.
cy [in] Vertical distance to move window, in pixels.
Returns
true if the method succeeds.
References SetWindowPos().
Referenced by MeaDataDisplay::Disable(), MeaDataDisplay::Enable(), AppView::ViewScreenInfo(), and AppView::ViewToolInfo().
PlaceAfter()
void MeaLayout::PlaceAfter (const CWnd & frontWnd, const CWnd & backWnd, int spacing)
Places the back window after the specified front window and separates them by the specified spacing.
Parameters
frontWnd [in] Window in front of backWnd.
backWnd [in] Window to place after frontWnd.
spacing [in] Separation between the two windows, in pixels.
References SetWindowPos().
Referenced by MeaMagnifier::Create(), MeaDataDisplay::CreateRegionSection(), and MeaDataDisplay::CreateScreenSection().
ScreenToClientX()
bool MeaLayout::ScreenToClientX (const CWnd & wnd, int & x) inline
Converts the x position in screen coordinates to an x position in the specified window's coordinate system.
Parameters
wnd [in] The x coordinate is converts to this window's coordinate system.
x [in, out] The x coordinate to convert.
Returns
true if the conversion was successful.
Referenced by MeaRuler::DrawIndicator(), and MeaRuler::DrawRuler().
ScreenToClientY()
bool MeaLayout::ScreenToClientY (const CWnd & wnd, int & y) inline
Converts the y position in screen coordinates to a y position in the specified window's coordinate system.
Parameters
wnd [in] The y coordinate is converts to this window's coordinate system.
y [in, out] The y coordinate to convert.
Returns
true if the conversion was successful.
Referenced by MeaRuler::DrawIndicator(), and MeaRuler::DrawRuler().
SetWindowHeight()
bool MeaLayout::SetWindowHeight (const CWnd & wnd, int cy) inline
Sets the height of the window.
Parameters
wnd [in] Window whose height is to be set.
cy [in] Height for the window, in pixels.
Returns
true if the method succeeds.
References SetWindowPos().
Referenced by AppView::CheckMargins(), AppView::ViewMagnifier(), AppView::ViewScreenInfo(), and AppView::ViewToolInfo().
SetWindowPos()
bool MeaLayout::SetWindowPos (const CWnd & wnd, int x, int y) inline
Sets the position of the specified window.
Parameters
wnd [in] Window to position.
x [in] X position for the window, in pixels.
y [in] Y position for the window, in pixels.
Returns
true if the method succeeds.
References SetWindowPos().
Referenced by AlignCenter(), AlignLeft(), AlignRight(), AlignRightTo(), MeaRuler::Create(), MeaDataDisplay::Create(), MeaDataDisplay::CreateScreenSection(), MoveWindowHeight(), AppView::OnCreate(), MeaCircle::OnHPTimer(), MeaLine::OnHPTimer(), MeaRectangle::OnHPTimer(), PlaceAfter(), MeaGraphic::SetAbove(), MeaCrossHair::SetPosition(), MeaRuler::SetPosition(), SetWindowHeight(), SetWindowPos(), SetWindowSize(), MeaDataWin::Show(), MeaDataWin::Update(), and AppFrame::UpdateVisibility().
SetWindowSize()
bool MeaLayout::SetWindowSize (const CWnd & wnd, int cx, int cy) inline
Sets the size of the specified window.
Parameters
wnd [in] Window to size.
cx [in] Width for the window, in pixels.
cy [in] Height for the window, in pixels.
Returns
true if the method succeeds.
References SetWindowPos().
Referenced by MeaDataDisplay::Create(), MeaMagnifier::Create(), MeaTextField::Create(), MeaLabel::Create(), MeaDataDisplay::CreateRegionSection(), MeaDataDisplay::CreateScreenSection(), MeaDataDisplay::DataItem::CreateSpinButton(), AppFrame::OnCreate(), MeaUnitsLabel::SetSize(), AppFrame::ViewStatusbar(), and AppFrame::ViewToolbar().
Copyright 2011 C Thing Software