Meazure: MeaNumericUtils Namespace Reference
MeaNumericUtils Namespace Reference
Constants and convenience methods for working with numbers.
Functions
template<typename T >
bool IsEqualF (T f1, T f2)
Tests whether the two specified floating point values are equal.
template<typename T >
bool IsZeroF (T f)
Tests whether the specified floating point value is zero.
constexpr double DegToRad (double deg)
Converts the specified value in degrees to a corresponding value in radians.
constexpr double RadToDeg (double rad)
Converts the specified value in radians to a corresponding value in degrees.
Variables
constexpr double PI = 3.141592653589793
constexpr double PI4 = 0.785398163397448
Detailed Description
Constants and convenience methods for working with numbers.
Function Documentation
DegToRad()
constexpr double MeaNumericUtils::DegToRad (double deg) constexpr
Converts the specified value in degrees to a corresponding value in radians.
Parameters
deg [in] Degree value to convert to radians
Returns
Value in radians
Referenced by MeaColors::ColorDifference().
IsEqualF()
template<typename T > bool MeaNumericUtils::IsEqualF (T f1, T f2) inline
Tests whether the two specified floating point values are equal.
Template Parameters
T One of float, double, or long double
Parameters
f1 [in] Value to test
f2 [in] Value to test
Returns
true if the two values are equal within an epsilon of the floating point type compensated for the magnitude of the values. See Comparing Floating Point Numbers, 2012 Edition and Comparing Two Floating-Point Numbers for details on this implementation.
Referenced by MeaCalibrationPrefs::GetFieldValue(), MeaFPoint::operator==(), MeaFRect::operator==(), MeaFSize::operator==(), MeaPosition::operator==(), MeaPositionDesktop::operator==(), MeaPositionScreen::operator==(), MeaColors::RGBtoHSL(), and MeaScreenTool::SetPosition().
IsZeroF()
template<typename T > bool MeaNumericUtils::IsZeroF (T f) inline
Tests whether the specified floating point value is zero.
Template Parameters
T One of float, double, or long double
Parameters
f [in] Value to test
Returns
true if the value is equal to zero within an epsilon of the floating point type.
Referenced by MeaGeometry::CalcAngle(), MeaColors::ColorDifference(), and MeaColors::RGBtoHSL().
RadToDeg()
constexpr double MeaNumericUtils::RadToDeg (double rad) constexpr
Converts the specified value in radians to a corresponding value in degrees.
Parameters
rad [in] Radian value to convert to degrees
Returns
Value in degrees
Copyright 2011 C Thing Software