Meazure: StringUtils.h File Reference
StringUtils.h File Reference
String manipulation utility functions.
#include <limits.h>
#include <cstddef>
Functions
CString MeaStringUtils::IntToStr (int value)
Converts the specified integer to a string.
CString MeaStringUtils::DblToStr (double value)
Converts the specified double to a string with the minimum number of decimal places.
bool MeaStringUtils::IsNumber (LPCTSTR str, double *valuep=nullptr)
Tests whether the specified string is a number.
bool MeaStringUtils::IsBoolean (LPCTSTR str, bool *valuep=nullptr)
Tests whether the specified string is a boolean value.
CString MeaStringUtils::LFtoCRLF (CString str)
Converts standalone LF characters into a CR+LF pair.
CString MeaStringUtils::CRLFtoLF (CString str)
Converts CR+LF pairs to a single LF character.
CStringA MeaStringUtils::ACPtoUTF8 (const CString &str)
Converts a string encoded in the active code page (ACP) to a string in UTF-8 encoding.
CStringA MeaStringUtils::ACPtoUTF8 (PCTSTR str, std::size_t strLen=SIZE_MAX)
Converts a string encoded in the active code page (ACP) to a string in UTF-8 encoding.
CStringA MeaStringUtils::ACPtoUTF8 (TCHAR ch)
Converts a character encoded in the active code page (ACP) to a character in UTF-8 encoding.
Detailed Description
String manipulation utility functions.
Function Documentation
ACPtoUTF8() [1/3]
CStringA MeaStringUtils::ACPtoUTF8 (const CString & str)
Converts a string encoded in the active code page (ACP) to a string in UTF-8 encoding.
Parameters
str [in] String to covert to UTF-8 encoding. If _UNICODE is defined, the string in converted from wide characters to UTF-8. If _UNICODE is not defined, the string is converted from the ACP to UTF-8.
Returns
The specified string converted to UTF-8 encoding.
References MeaStringUtils::ACPtoUTF8().
Referenced by MeaStringUtils::ACPtoUTF8().
ACPtoUTF8() [2/3]
CStringA MeaStringUtils::ACPtoUTF8 (PCTSTR str, std::size_t strLen = SIZE_MAX)
Converts a string encoded in the active code page (ACP) to a string in UTF-8 encoding.
Parameters
str [in] String to covert to UTF-8 encoding. If _UNICODE is defined, the string in converted from wide characters to UTF-8. If _UNICODE is not defined, the string is converted from the ACP to UTF-8.
strLen [in] Number of characters (unicode) or bytes (mbcs) for the specified string. Default is SIZE_MAX if the length of the string is unknown.
Returns
The specified string converted to UTF-8 encoding.
References MeaStringUtils::ACPtoUTF8().
ACPtoUTF8() [3/3]
CStringA MeaStringUtils::ACPtoUTF8 (TCHAR ch)
Converts a character encoded in the active code page (ACP) to a character in UTF-8 encoding.
Parameters
ch [in] Character to covert to UTF-8 encoding. If _UNICODE is defined, the character in converted from wide characters to UTF-8. If _UNICODE is not defined, the character is converted from the ACP to UTF-8.
Returns
The specified character converted to UTF-8 encoding.
References MeaStringUtils::ACPtoUTF8().
CRLFtoLF()
CString MeaStringUtils::CRLFtoLF (CString str)
Converts CR+LF pairs to a single LF character.
Parameters
str [in] String to process.
Returns
Converted string.
References MeaStringUtils::CRLFtoLF().
Referenced by MeaStringUtils::CRLFtoLF().
DblToStr()
CString MeaStringUtils::DblToStr (double value)
Converts the specified double to a string with the minimum number of decimal places.
Parameters
value [in] Numerical value to convert to a string.
Returns
String corresponding to the double value.
References MeaStringUtils::DblToStr().
Referenced by MeaStringUtils::DblToStr().
IntToStr()
CString MeaStringUtils::IntToStr (int value)
Converts the specified integer to a string.
Parameters
value [in] Integer value to convert to a string.
Returns
String corresponding to the integer value.
References MeaStringUtils::IntToStr().
Referenced by MeaStringUtils::IntToStr().
IsBoolean()
bool MeaStringUtils::IsBoolean (LPCTSTR str, bool * valuep = nullptr)
Tests whether the specified string is a boolean value.
For the purpose of this method, the strings "1", "TRUE", "true" are boolean true values, while "0", "FALSE", "false" are boolean false.
Parameters
str [in] String to test
valuep [out] Value parsed from the string. nullptr if not interested. If the return value is false, valuep's value is undefined.
Returns
true if string represents a boolean value.
References MeaStringUtils::IsBoolean().
Referenced by MeaStringUtils::IsBoolean().
IsNumber()
bool MeaStringUtils::IsNumber (LPCTSTR str, double * valuep = nullptr)
Tests whether the specified string is a number.
For the purposes of this method, a number is a base 10 double precision floating point value.
Parameters
str [in] String to test
valuep [out] Value parsed from the string. nullptr if not interested. If the return value is false, valuep's value is undefined.
Returns
true if string represents a number.
References MeaStringUtils::IsNumber().
Referenced by MeaStringUtils::IsNumber().
LFtoCRLF()
CString MeaStringUtils::LFtoCRLF (CString str)
Converts standalone LF characters into a CR+LF pair.
Existing CR+LF pairs in the string are not effected.
Parameters
str [in] String to process.
Returns
Converted string.
References MeaStringUtils::LFtoCRLF().
Referenced by MeaStringUtils::LFtoCRLF().
Copyright 2011 C Thing Software