Meazure: MeaFSize Struct Reference
MeaFSize Struct Reference
Represents a rectangular size.
#include <Geometry.h>
Public Member Functions
constexpr MeaFSize ()
Constructs a size object initialized to 0.0 width and height.
constexpr MeaFSize (double x, double y)
Constructs a size object initialized to the specified dimensions.
bool operator== (const MeaFSize &other) const
Tests equality between this with the specified size.
bool operator!= (const MeaFSize &other) const
Tests inequality between this with the specified size.
constexpr MeaFSize operator+ (const MeaFSize &fsize) const
Adds this and the specified object and returns a new size object.
constexpr MeaFSize operator+ (double val) const
Adds this and the specified value and returns a new size object.
constexpr MeaFSize operator* (const MeaFSize &fsize) const
Multiplies this and the specified object and returns a new size object.
constexpr MeaFSize operator* (const SIZE &size) const
Multiplies this and the specified object and returns a new size object.
constexpr MeaFSize operator* (double mult) const
Multiplies this and the specified value and returns a new size object.
constexpr MeaFSize operator/ (double div) const
Divides this and the specified value and returns a new size object.
constexpr MeaFSize & operator+= (const MeaFSize &fsize)
Adds the specified size object to this.
constexpr MeaFSize & operator-= (const MeaFSize &fsize)
Subtracts the specified size object from this.
constexpr MeaFSize & operator*= (const MeaFSize &fsize)
Multiplies the specified size object and this.
Public Attributes
double cx
Length in the x dimension.
double cy
Length in the y dimension.
Detailed Description
Represents a rectangular size.
Unlike the Windows SIZE structure, the dimensions of the MeaFSize structure are double precision values.
Constructor & Destructor Documentation
MeaFSize()
constexpr MeaFSize::MeaFSize (double x, double y) inline constexpr
Constructs a size object initialized to the specified dimensions.
Parameters
x [in] Length in the x dimension
y [in] Length in the y dimension
Member Function Documentation
operator!=()
bool MeaFSize::operator!= (const MeaFSize & other) const inline
Tests inequality between this with the specified size.
Parameters
other [in] Other size to compare against this
Returns
true if this and the specified size have the different dimensions.
operator*() [1/3]
constexpr MeaFSize MeaFSize::operator* (const MeaFSize & fsize) const inline constexpr
Multiplies this and the specified object and returns a new size object.
Parameters
fsize [in] Size object to multiply.
Returns
New object that is the product of this and the specified object.
References cx, cy, and MeaFSize().
operator*() [2/3]
constexpr MeaFSize MeaFSize::operator* (const SIZE & size) const inline constexpr
Multiplies this and the specified object and returns a new size object.
Parameters
size [in] Size object to multiply.
Returns
New object that is the product of this and the specified object.
References cx, cy, and MeaFSize().
operator*() [3/3]
constexpr MeaFSize MeaFSize::operator* (double mult) const inline constexpr
Multiplies this and the specified value and returns a new size object.
Parameters
mult [in] Value to multiply both dimensions.
Returns
New object that is the product of this and the specified value.
References cx, cy, and MeaFSize().
operator*=()
constexpr MeaFSize & MeaFSize::operator*= (const MeaFSize & fsize) inline constexpr
Multiplies the specified size object and this.
Parameters
fsize [in] Size object to multiply with this.
Returns
this object.
References cx, and cy.
operator+() [1/2]
constexpr MeaFSize MeaFSize::operator+ (const MeaFSize & fsize) const inline constexpr
Adds this and the specified object and returns a new size object.
Parameters
fsize [in] Size object to add.
Returns
New object that is the sum of this and the specified object.
References cx, cy, and MeaFSize().
operator+() [2/2]
constexpr MeaFSize MeaFSize::operator+ (double val) const inline constexpr
Adds this and the specified value and returns a new size object.
Parameters
val [in] Length to add to both dimensions.
Returns
New object that is the sum of this and the specified value.
References cx, cy, and MeaFSize().
operator+=()
constexpr MeaFSize & MeaFSize::operator+= (const MeaFSize & fsize) inline constexpr
Adds the specified size object to this.
Parameters
fsize [in] Size object to add to this.
Returns
this object.
References cx, and cy.
operator-=()
constexpr MeaFSize & MeaFSize::operator-= (const MeaFSize & fsize) inline constexpr
Subtracts the specified size object from this.
Parameters
fsize [in] Size object to subtract from this.
Returns
this object.
References cx, and cy.
operator/()
constexpr MeaFSize MeaFSize::operator/ (double div) const inline constexpr
Divides this and the specified value and returns a new size object.
Parameters
div [in] Value to divide both dimensions.
Returns
New object that is the division of this by the specified value.
References cx, cy, and MeaFSize().
operator==()
bool MeaFSize::operator== (const MeaFSize & other) const inline
Tests equality between this with the specified size.
Parameters
other [in] Other size to compare against this
Returns
true if this and the specified size have the same dimensions.
References cx, cy, and MeaNumericUtils::IsEqualF().
The documentation for this struct was generated from the following file:
Geometry.h
Copyright 2011 C Thing Software