Meazure: MeaUnitsProvider Struct Reference
MeaUnitsProvider Struct Reference abstract
Interface for units related information.
#include <UnitsProvider.h>
Public Member Functions
virtual MeaLinearUnits * GetLinearUnits () const =0
Returns the current linear measurement units.
virtual MeaLinearUnits * GetLinearUnits (const CString &unitsStr) const =0
Returns the linear measurement units object corresponding to the specified identifier string (e.g.
virtual MeaAngularUnits * GetAngularUnits () const =0
Returns the current angular measurement units.
virtual MeaAngularUnits * GetAngularUnits (const CString &unitsStr) const =0
Returns the angular measurement units object corresponding to the specified identifier string (e.g.
virtual bool IsInvertY () const =0
Returns the orientation of the y-axis.
virtual const POINT & GetOrigin () const =0
Returns the location of the origin of the coordinate system.
virtual MeaFSize GetWidthHeight (const POINT &p1, const POINT &p2) const =0
Uses the current linear measurement units to convert the two specified points from pixels to the current units, and then calculates the width and height of the rectangle formed by the two points.
virtual CString FormatConvertAngle (double angle) const =0
Converts the specified angle to the current angular units and formats the result for display.
virtual CString Format (MeaLinearMeasurementId id, double value) const =0
Formats the specified linear measurement value for display.
virtual CString Format (MeaAngularMeasurementId id, double value) const =0
Formats the specified angular measurement value for display.
virtual MeaFPoint ConvertCoord (const POINT &pos) const =0
Converts the specified coordinate from pixels to the desired units.
virtual MeaFPoint ConvertPos (const POINT &pos) const =0
Converts the specified position from pixels to the desired units.
virtual POINT UnconvertPos (const MeaFPoint &pos) const =0
Converts from the current units to pixels.
virtual MeaFSize ConvertRes (const MeaFSize &res) const =0
Converts the specified resolution in pixels/inch to the desired units.
virtual double ConvertAngle (double angle) const =0
Converts the specified angle value from its native radians to the desired units.
virtual SIZE ConvertToPixels (MeaLinearUnitsId id, const MeaFSize &res, double value, int minPixels) const =0
Converts the specified value from the specified units to pixels.
virtual int GetMajorTickCount () const =0
Returns the number of minor ticks to display before a major tick mark is displayed on the measurement rulers.
virtual MeaFSize GetMinorIncr (const RECT &rect) const =0
Returns the increment between minor tick marks on the measurement rulers.
Detailed Description
Interface for units related information.
Member Function Documentation
ConvertAngle()
virtual double MeaUnitsProvider::ConvertAngle (double angle) const pure virtual
Converts the specified angle value from its native radians to the desired units.
Parameters
angle [in] Value to be converted.
Returns
Angle value converted to the desired units.
Implemented in MeaUnitsMgr.
Referenced by MeaAngleTool::RecordPosition(), MeaCircleTool::RecordPosition(), MeaLineTool::RecordPosition(), MeaRectTool::RecordPosition(), and MeaWindowTool::RecordPosition().
ConvertCoord()
virtual MeaFPoint MeaUnitsProvider::ConvertCoord (const POINT & pos) const pure virtual
Converts the specified coordinate from pixels to the desired units.
This conversion takes into account the location of the origin and the orientation of the y-axis.
Parameters
pos [in] Coordinates in pixels to convert to the desired units.
Returns
Coordinates converted from pixels to the desired units. The conversion takes into account the location of the origin and the orientation of the y-axis.
Implemented in MeaUnitsMgr.
Referenced by MeaPositionScreen::MeaPositionScreen(), MeaAngleTool::RecordPosition(), MeaCircleTool::RecordPosition(), MeaCursorTool::RecordPosition(), MeaLineTool::RecordPosition(), MeaPointTool::RecordPosition(), MeaRectTool::RecordPosition(), MeaWindowTool::RecordPosition(), MeaAngleTool::Update(), MeaCircleTool::Update(), MeaCursorTool::Update(), MeaLineTool::Update(), MeaPointTool::Update(), MeaRectTool::Update(), MeaWindowTool::Update(), and MeaAngleTool::UpdateBisector().
ConvertPos()
virtual MeaFPoint MeaUnitsProvider::ConvertPos (const POINT & pos) const pure virtual
Converts the specified position from pixels to the desired units.
This conversion does not take into account the location of the origin nor does it compensate for the orientation of the y-axis.
Parameters
pos [in] Position in pixels to convert to the desired units.
Returns
Position converted from pixels to the desired units. The conversion does not take into account the location of the origin nor does it compensate for the orientation of the y-axis.
Implemented in MeaUnitsMgr.
Referenced by MeaAngleTool::LoadProfile(), MeaCircleTool::LoadProfile(), MeaLineTool::LoadProfile(), MeaPointTool::LoadProfile(), MeaRectTool::LoadProfile(), MeaAngleTool::SaveProfile(), MeaCircleTool::SaveProfile(), MeaLineTool::SaveProfile(), MeaPointTool::SaveProfile(), and MeaRectTool::SaveProfile().
ConvertRes()
virtual MeaFSize MeaUnitsProvider::ConvertRes (const MeaFSize & res) const pure virtual
Converts the specified resolution in pixels/inch to the desired units.
Parameters
res [in] Resolution in pixels/inch to convert to the desired units.
Returns
Resolution converted from pixels/inch to the desired units.
Implemented in MeaUnitsMgr.
Referenced by MeaPositionScreen::MeaPositionScreen(), and MeaScreenTool::Update().
ConvertToPixels()
virtual SIZE MeaUnitsProvider::ConvertToPixels (MeaLinearUnitsId id, const MeaFSize & res, double value, int minPixels) const pure virtual
Converts the specified value from the specified units to pixels.
A minimum pixel value is specified in case the resolution is such that the conversion to pixels results in a value that is too small.
Parameters
id [in] Linear units identifier.
res [in] Screen resolution to use to perform the conversion.
value [in] Value to be converted to pixels.
minPixels [in] If the converted pixel value in less than this minimum value, the minimum value is returned.
Returns
X and Y pixel values.
Implemented in MeaUnitsMgr.
Referenced by MeaRuler::Create(), MeaCrossHair::Create(), MeaLayout::DrawOpacityBackground(), and MeaOriginTool::Update().
Format() [1/2]
virtual CString MeaUnitsProvider::Format (MeaAngularMeasurementId id, double value) const pure virtual
Formats the specified angular measurement value for display.
Parameters
id [in] Identifies the angular measurement for use in determining the display precision.
value [in] Angular measurement value to format, in current units.
Returns
String containing the formatted measurement data.
Implemented in MeaUnitsMgr.
Format() [2/2]
virtual CString MeaUnitsProvider::Format (MeaLinearMeasurementId id, double value) const pure virtual
Formats the specified linear measurement value for display.
Parameters
id [in] Identifies the linear measurement for use in determining the display precision.
value [in] Linear measurement value to format, in current units.
Returns
String containing the formatted measurement data.
Implemented in MeaUnitsMgr.
Referenced by MeaDataWin::CalcWidth(), MeaRuler::DrawRuler(), MeaDataWin::ShowDistance(), MeaDataWin::ShowWH(), and MeaDataWin::ShowXY().
FormatConvertAngle()
virtual CString MeaUnitsProvider::FormatConvertAngle (double angle) const pure virtual
Converts the specified angle to the current angular units and formats the result for display.
Parameters
angle [in] Angle to be converted and displayed, in radians.
Returns
String containing the converted and formatted angle data.
Implemented in MeaUnitsMgr.
Referenced by MeaDataWin::CalcWidth(), and MeaDataWin::ShowAngle().
GetAngularUnits() [1/2]
virtual MeaAngularUnits * MeaUnitsProvider::GetAngularUnits () const pure virtual
Returns the current angular measurement units.
Returns
Current angular units.
Implemented in MeaUnitsMgr.
Referenced by MeaPositionDesktop::SetAngularUnits().
GetAngularUnits() [2/2]
virtual MeaAngularUnits * MeaUnitsProvider::GetAngularUnits (const CString & unitsStr) const pure virtual
Returns the angular measurement units object corresponding to the specified identifier string (e.g.
"deg").
Parameters
unitsStr [in] Angular units identifier string.
Returns
Angular measurement units object.
Implemented in MeaUnitsMgr.
GetLinearUnits() [1/2]
virtual MeaLinearUnits * MeaUnitsProvider::GetLinearUnits () const pure virtual
Returns the current linear measurement units.
Returns
Current linear units.
Implemented in MeaUnitsMgr.
Referenced by MeaRuler::DrawRuler(), and MeaPositionDesktop::SetLinearUnits().
GetLinearUnits() [2/2]
virtual MeaLinearUnits * MeaUnitsProvider::GetLinearUnits (const CString & unitsStr) const pure virtual
Returns the linear measurement units object corresponding to the specified identifier string (e.g.
"px").
Parameters
unitsStr [in] Linear units identifier string.
Returns
Linear measurement units object.
Implemented in MeaUnitsMgr.
GetMajorTickCount()
virtual int MeaUnitsProvider::GetMajorTickCount () const pure virtual
Returns the number of minor ticks to display before a major tick mark is displayed on the measurement rulers.
Returns
Number of minor tick marks to display before displaying a major tick mark.
Implemented in MeaUnitsMgr.
Referenced by MeaRuler::DrawRuler().
GetMinorIncr()
virtual MeaFSize MeaUnitsProvider::GetMinorIncr (const RECT & rect) const pure virtual
Returns the increment between minor tick marks on the measurement rulers.
Parameters
rect [in] Rectangle in screen coordinates, used to determine the current screen resolution.
Returns
Increment for the minor tick marks, in the current units.
Implemented in MeaUnitsMgr.
Referenced by MeaRuler::DrawRuler().
GetOrigin()
virtual const POINT & MeaUnitsProvider::GetOrigin () const pure virtual
Returns the location of the origin of the coordinate system.
Returns
Location of the origin of the coordinate system, in pixels.
Implemented in MeaUnitsMgr.
Referenced by MeaOriginTool::GetPosition(), and MeaOriginTool::Update().
GetWidthHeight()
virtual MeaFSize MeaUnitsProvider::GetWidthHeight (const POINT & p1, const POINT & p2) const pure virtual
Uses the current linear measurement units to convert the two specified points from pixels to the current units, and then calculates the width and height of the rectangle formed by the two points.
Parameters
p1 [in] One point defining the rectangle, in pixels.
p2 [in] The other point defining the rectangle, in pixels.
Returns
The width and height of the rectangle formed by the two specified points converted to the current linear measurement units. Regardless of the relative locations of the two points, the width and height are always positive. In addition, the width and height are inclusive (e.g. p1.x = 1, p2.x = 3, width = p2.x - p1.x + 1 = 3).
Implemented in MeaUnitsMgr.
Referenced by MeaDataWin::CalcWidth(), MeaPositionDesktop::MeaPositionDesktop(), MeaCircleTool::RecordPosition(), MeaLineTool::RecordPosition(), MeaRectTool::RecordPosition(), MeaWindowTool::RecordPosition(), MeaCircleTool::Update(), MeaLineTool::Update(), MeaRectTool::Update(), MeaScreenTool::Update(), and MeaWindowTool::Update().
IsInvertY()
virtual bool MeaUnitsProvider::IsInvertY () const pure virtual
Returns the orientation of the y-axis.
Returns
If true is returned, the origin of the coordinate system is located at the lower left of the primary screen, and the positive y-axis is pointing upward. If false is returned, the origin is located at the upper left corner and the positive y-axis is pointing down. Note that the actual location of the origin is determined by the SetOrigin method.
Implemented in MeaUnitsMgr.
Referenced by MeaOriginTool::Update(), and MeaAngleTool::UpdateBisector().
UnconvertPos()
virtual POINT MeaUnitsProvider::UnconvertPos (const MeaFPoint & pos) const pure virtual
Converts from the current units to pixels.
The conversion does not take into account the location of the origin nor the orientation of the y-axis.
Parameters
pos [in] Position to convert to pixels.
Returns
Position converted from the current units to pixels. The conversion does not take into account the location of the origin nor the orientation of the y-axis.
Implemented in MeaUnitsMgr.
Referenced by MeaAngleTool::LoadProfile(), MeaCircleTool::LoadProfile(), MeaLineTool::LoadProfile(), MeaPointTool::LoadProfile(), and MeaRectTool::LoadProfile().
The documentation for this struct was generated from the following file:
UnitsProvider.h
Copyright 2011 C Thing Software