Meazure: MeaXMLParserHandler Struct Reference
MeaXMLParserHandler Struct Reference
Mix-in class for XML parser callback methods.
#include <XMLParser.h>
Public Member Functions
virtual void StartElement (const CString &container, const CString &elementName, const MeaXMLAttributes &attrs)
Called when a new element is opened (e.g.
virtual void EndElement (const CString &container, const CString &elementName)
Called when an element is closed (e.g.
virtual void CharacterData (const CString &container, const CString &data)
Called for all character data encountered between elements.
virtual xercesc::InputSource * ResolveEntity (const CString &pathname)
Called to resolve an external entity (e.g.
virtual void ParsingError (const CString &error, const CString &pathname, int line, int column)
Called when there is a parsing error (e.g.
virtual void ValidationError (const CString &error, const CString &pathname, int line, int column)
Called when there is a validation error (e.g.
virtual CString GetFilePathname ()
Returns the pathname of the currently parsed file.
Detailed Description
Mix-in class for XML parser callback methods.
A class that wants XML parsing services inherits from this class, overrides the methods of this class for the events of interest, creates an instance of the MeaXMLParser class and points it at the XML file to parse. The parser calls back using the methods of this class to indicate various XML parsing events. This is classic SAX parsing behavior. The class has noop implementations for all methods.
Member Function Documentation
CharacterData()
void MeaXMLParserHandler::CharacterData (const CString & container, const CString & data) virtual
Called for all character data encountered between elements.
Note that this method will be called for all character data including whitespace between consecutive elements. The DTD must be used to determine what whitespace is relevant.
Parameters
container [in] Name of the closest open element containing the character data.
data [in] Character data.
Reimplemented in MeaFileProfile.
Referenced by MeaXMLParser::characters().
EndElement()
void MeaXMLParserHandler::EndElement (const CString & container, const CString & elementName) virtual
Called when an element is closed (e.g.
</foo> or <foo/>).
Parameters
container [in] Parent element.
elementName [in] Name of the element being closed.
Referenced by MeaXMLParser::endElement().
GetFilePathname()
CString MeaXMLParserHandler::GetFilePathname () virtual
Returns the pathname of the currently parsed file.
Returns
Pathname of the file currently being parsed. This class's implementation of this method returns the empty string.
Reimplemented in MeaPositionLogMgr, and MeaFileProfile.
Referenced by MeaXMLParser::error(), and MeaXMLParser::fatalError().
ParsingError()
void MeaXMLParserHandler::ParsingError (const CString & error, const CString & pathname, int line, int column) virtual
Called when there is a parsing error (e.g.
syntax, structure).
Parameters
error [in] Error message
pathname [in] Pathname of the file containing the error
line [in] Line number on which the error occurred (1 based)
column [in] Column number in which the error occurred (1 based)
Referenced by MeaXMLParser::fatalError().
ResolveEntity()
xercesc::InputSource * MeaXMLParserHandler::ResolveEntity (const CString & pathname) virtual
Called to resolve an external entity (e.g.
DTD).
Parameters
pathname [in] Pathname of the external entity.
Returns
Input source for the external entity. The default implementation returns nullptr.
Reimplemented in MeaPositionLogMgr.
Referenced by MeaXMLParser::resolveEntity().
StartElement()
void MeaXMLParserHandler::StartElement (const CString & container, const CString & elementName, const MeaXMLAttributes & attrs) virtual
Called when a new element is opened (e.g.
<foo> or <foo/>).
Parameters
container [in] Parent element.
elementName [in] Name of the element being opened.
attrs [in] Attributes associated with the element.
Reimplemented in MeaFileProfile.
Referenced by MeaXMLParser::startElement().
ValidationError()
void MeaXMLParserHandler::ValidationError (const CString & error, const CString & pathname, int line, int column) virtual
Called when there is a validation error (e.g.
unknown element).
Parameters
error [in] Error message
pathname [in] Pathname of the file containing the error
line [in] Line number on which the error occurred (1 based)
column [in] Column number in which the error occurred (1 based)
Referenced by MeaXMLParser::error().
The documentation for this struct was generated from the following files:
XMLParser.h
XMLParser.cpp
Copyright 2011 C Thing Software