Meazure: MeaRegistryProvider Struct Reference
MeaRegistryProvider Struct Reference abstract
Interface for Windows Registry interaction.
#include <RegistryProvider.h>
Public Member Functions
virtual BOOL WriteInt (LPCTSTR section, LPCTSTR entry, int value)=0
Writes the specified value into the specified section of the application's registry.
virtual BOOL WriteString (LPCTSTR section, LPCTSTR entry, LPCTSTR value)=0
Write the specified string into the specified section of the application's registry.
virtual UINT GetInt (LPCTSTR section, LPCTSTR entry, int defaultValue)=0
Retrieves the value of an integer from an entry within a specified section of the application's registry.
virtual CString GetString (LPCTSTR section, LPCTSTR entry, LPCTSTR defaultValue)=0
Retrieves the string associated with an entry within the specified section in the application's registry.
virtual LPCTSTR GetKeyName ()=0
Determines where, in the registry or INI file, application profile settings are stored.
virtual LSTATUS OpenKey (HKEY key, LPCTSTR subKey, DWORD options, REGSAM samDesired, PHKEY result)=0
Opens the specified registry key.
virtual LSTATUS CloseKey (HKEY key)=0
Closes a handle to the specified registry key.
Detailed Description
Interface for Windows Registry interaction.
Member Function Documentation
CloseKey()
virtual LSTATUS MeaRegistryProvider::CloseKey (HKEY key) pure virtual
Closes a handle to the specified registry key.
Parameters
key [in] A handle to the open key to be closed
Returns
If the function succeeds, the return value is ERROR_SUCCESS.
Implemented in MeaRegistry.
Referenced by MeaRegistryProfile::HaveVersionKey().
GetInt()
virtual UINT MeaRegistryProvider::GetInt (LPCTSTR section, LPCTSTR entry, int defaultValue) pure virtual
Retrieves the value of an integer from an entry within a specified section of the application's registry.
Parameters
section [in] Points to a null-terminated string that specifies the section containing the entry.
entry [in] Points to a null-terminated string that contains the entry whose value is to be retrieved.
defaultValue [in] Specifies the default value to return if the framework cannot find the entry.
Returns
The integer value of the string that follows the specified entry if the function is successful. The return value is the value of the defaultValue parameter if the function does not find the entry. The return value is 0 if the value that corresponds to the specified entry is not an integer.
Implemented in MeaRegistry.
Referenced by MeaRegistryProfile::ReadBool(), and MeaRegistryProfile::ReadInt().
GetKeyName()
virtual LPCTSTR MeaRegistryProvider::GetKeyName () pure virtual
Determines where, in the registry or INI file, application profile settings are stored.
Returns
Application registry key.
Implemented in MeaRegistry.
Referenced by MeaRegistryProfile::HaveVersionKey().
GetString()
virtual CString MeaRegistryProvider::GetString (LPCTSTR section, LPCTSTR entry, LPCTSTR defaultValue) pure virtual
Retrieves the string associated with an entry within the specified section in the application's registry.
Parameters
section [in] Points to a null-terminated string that specifies the section containing the entry.
entry [in] Points to a null-terminated string that contains the entry whose string is to be retrieved. This value must not be NULL.
defaultValue [in] Points to the default string value for the given entry if the entry cannot be found
Returns
The return value is the string from the application's registry entry or defaultValue if the string cannot be found. The maximum string length supported by the framework is _MAX_PATH. If defaultValue is NULL, the return value is an empty string.
Implemented in MeaRegistry.
Referenced by MeaRegistryProfile::ReadDbl(), and MeaRegistryProfile::ReadStr().
OpenKey()
virtual LSTATUS MeaRegistryProvider::OpenKey (HKEY key, LPCTSTR subKey, DWORD options, REGSAM samDesired, PHKEY result) pure virtual
Opens the specified registry key.
Note that key names are not case sensitive.
Parameters
key [in] A handle to an open registry key
subKey [in] Name of the registry sub-key
options [in] Specifies the option to apply when opening the key
samDesired [in] A mask that specifies the desired access rights to the key to be opened
result [in] A pointer to a variable that receives a handle to the opened key
Returns
If the function succeeds, the return value is ERROR_SUCCESS.
Implemented in MeaRegistry.
Referenced by MeaRegistryProfile::HaveVersionKey().
WriteInt()
virtual BOOL MeaRegistryProvider::WriteInt (LPCTSTR section, LPCTSTR entry, int value) pure virtual
Writes the specified value into the specified section of the application's registry.
Parameters
section [in] Points to a null-terminated string that specifies the section containing the entry. If the section does not exist, it is created. The name of the section is case independent.
entry [in] Points to a null-terminated string that contains the entry into which the value is to be written. If the entry does not exist in the specified section, it is created.
value [in] Contains the value to be written.
Returns
TRUE if successful; otherwise FALSE.
Implemented in MeaRegistry.
Referenced by MeaRegistryProfile::WriteBool(), and MeaRegistryProfile::WriteInt().
WriteString()
virtual BOOL MeaRegistryProvider::WriteString (LPCTSTR section, LPCTSTR entry, LPCTSTR value) pure virtual
Write the specified string into the specified section of the application's registry.
Parameters
section [in] Points to a null-terminated string that specifies the section containing the entry. If the section does not exist, it is created. The name of the section is case independent.
entry [in] Points to a null-terminated string that contains the entry into which the value is to be written. If the entry does not exist in the specified section, it is created. If this parameter is NULL, the section specified by section is deleted.
value [in] Points to the string to be written. If this parameter is NULL, the entry specified by the entry parameter is deleted.
Returns
TRUE if successful; otherwise FALSE.
Implemented in MeaRegistry.
Referenced by MeaRegistryProfile::WriteDbl(), and MeaRegistryProfile::WriteStr().
The documentation for this struct was generated from the following file:
RegistryProvider.h
Copyright 2011 C Thing Software