Meazure: MeaScreenProvider Struct Reference
MeaScreenProvider Struct Reference abstract
Provides information on the display monitor(s).
#include <ScreenProvider.h>
Classes
struct less
Used by the STL collections for ordering comparisons.
class Screen
Represents a single display screen.
Public Types
typedef std::map< HMONITOR, Screen * > Screens
Maps a monitor handle to a screen object.
typedef Screens::const_iterator ScreenIter
Constant iterator over the screens.
Public Member Functions
virtual int GetNumScreens () const =0
Returns the number of display screens attached to the system.
virtual ScreenIter GetScreenIter () const =0
Obtains an iterator over each screen attached to the system.
virtual ScreenIter GetScreenIter (const CWnd *wnd) const =0
Obtains an iterator pointed at the screen that contains the specified window.
virtual ScreenIter GetScreenIter (const POINT &point) const =0
Obtains an iterator pointed at the screen that contains the specified point.
virtual ScreenIter GetScreenIter (const RECT &rect) const =0
Obtains an iterator pointed at the screen that contains the specified rectangle.
virtual bool AtEnd (const ScreenIter &iter) const =0
Indicates if the screen iterator is at the end of the screen collection.
virtual const CPoint & GetCenter () const =0
Determines the center of the screen that contains the app's main window.
virtual CPoint GetOffScreen () const =0
Returns a point guaranteed to be located off any screen.
virtual const CRect & GetVirtualRect () const =0
Returns the virtual screen rectangle.
virtual const CRect & GetScreenRect (const ScreenIter &iter) const =0
Returns the screen rectangle for the screen pointed to by the specified iterator.
virtual void GetScreenRes (const ScreenIter &iter, bool &useManualRes, MeaFSize &manualRes) const =0
Returns the manually set screen resolution for the screen pointed to by the specified iterator.
virtual const MeaFSize & GetScreenRes (const ScreenIter &iter) const =0
Returns the resolution for the screen pointed to by the specified iterator.
virtual bool IsManualRes (const ScreenIter &iter) const =0
Indicates it the resolution for the specified screen has been set manually.
virtual bool AnyOSRes () const =0
Indicates whether any screen is using the operating system reported resolution.
virtual bool IsPrimary (const ScreenIter &iter) const =0
Indicates if the screen pointed to by the specified iterator is the primary.
virtual CString GetScreenName (const ScreenIter &iter) const =0
Returns the name for the specified screen.
virtual CPoint LimitPosition (const CPoint &pt) const =0
Ensures that the specified point is on a screen.
Detailed Description
Provides information on the display monitor(s).
Member Function Documentation
AnyOSRes()
virtual bool MeaScreenProvider::AnyOSRes () const pure virtual
Indicates whether any screen is using the operating system reported resolution.
In other words, are there any screen that require calibration.
Returns
true if there are any screens requiring manual calibration.
Implemented in MeaScreenMgr.
Referenced by MeaScreenTool::SetPosition().
AtEnd()
virtual bool MeaScreenProvider::AtEnd (const ScreenIter & iter) const pure virtual
Indicates if the screen iterator is at the end of the screen collection.
Parameters
iter [in] Screen iterator to test.
Returns
true if the specified iterator is pointed to the end of the collection of screens.
Implemented in MeaScreenMgr.
Referenced by MeaRulerTool::Enable(), MeaLinearUnits::FindResFromCoord(), MeaLinearUnits::FindResFromPos(), MeaRulerTool::LoadProfile(), and MeaPositionDesktop::MeaPositionDesktop().
GetCenter()
virtual const CPoint & MeaScreenProvider::GetCenter () const pure virtual
Determines the center of the screen that contains the app's main window.
Returns
Center point of the screen containing the app's main window.
Implemented in MeaScreenMgr.
Referenced by MeaLineTool::MeaLineTool(), and MeaRectTool::MeaRectTool().
GetNumScreens()
virtual int MeaScreenProvider::GetNumScreens () const pure virtual
Returns the number of display screens attached to the system.
Returns
Number of display screens attached to the system.
Implemented in MeaScreenMgr.
Referenced by MeaLinearUnits::FindResFromCoord(), MeaLinearUnits::FindResFromPos(), MeaRulerTool::MeaRulerTool(), and MeaScreenMgr::SaveProfile().
GetOffScreen()
virtual CPoint MeaScreenProvider::GetOffScreen () const pure virtual
Returns a point guaranteed to be located off any screen.
Returns
Point located off any display screen.
Implemented in MeaScreenMgr.
Referenced by MeaRuler::ClearIndicator(), and MeaRulerTool::MeaRulerTool().
GetScreenIter() [1/4]
virtual ScreenIter MeaScreenProvider::GetScreenIter () const pure virtual
Obtains an iterator over each screen attached to the system.
Returns
Constant iterator over all screens.
Implemented in MeaScreenMgr.
Referenced by MeaLinearUnits::ConvertCoord(), MeaLinearUnits::ConvertPos(), MeaRuler::Create(), MeaCrossHair::Create(), MeaLayout::DrawOpacityBackground(), MeaRulerTool::Enable(), MeaLinearUnits::FindResFromCoord(), MeaLinearUnits::FindResFromPos(), MeaRulerTool::LoadProfile(), MeaPositionDesktop::MeaPositionDesktop(), MeaScreenTool::SetPosition(), MeaLinearUnits::UnconvertCoord(), MeaDataWin::Update(), MeaOriginTool::Update(), and MeaCalibrationPrefs::UpdateCurrentScreen().
GetScreenIter() [2/4]
virtual ScreenIter MeaScreenProvider::GetScreenIter (const CWnd * wnd) const pure virtual
Obtains an iterator pointed at the screen that contains the specified window.
Parameters
wnd [in] Window whose screen is desired.
Returns
Constant iterator pointed at screen containing the specified window.
Implemented in MeaScreenMgr.
GetScreenIter() [3/4]
virtual ScreenIter MeaScreenProvider::GetScreenIter (const POINT & point) const pure virtual
Obtains an iterator pointed at the screen that contains the specified point.
Parameters
point [in] Point whose screen is desired.
Returns
Constant iterator pointed at screen containing the specified point.
Implemented in MeaScreenMgr.
GetScreenIter() [4/4]
virtual ScreenIter MeaScreenProvider::GetScreenIter (const RECT & rect) const pure virtual
Obtains an iterator pointed at the screen that contains the specified rectangle.
Parameters
rect [in] Rectangle whose screen is desired.
Returns
Constant iterator pointed at screen containing the specified rectangle.
Implemented in MeaScreenMgr.
GetScreenName()
virtual CString MeaScreenProvider::GetScreenName (const ScreenIter & iter) const pure virtual
Returns the name for the specified screen.
Parameters
iter [in] Iterator pointing to the screen whose name is desired.
Returns
Name of the specified screen.
Implemented in MeaScreenMgr.
Referenced by MeaPositionScreen::MeaPositionScreen(), MeaScreenTool::SetPosition(), and MeaCalibrationPrefs::UpdateCurrentScreen().
GetScreenRect()
virtual const CRect & MeaScreenProvider::GetScreenRect (const ScreenIter & iter) const pure virtual
Returns the screen rectangle for the screen pointed to by the specified iterator.
Parameters
iter [in] Screen iterator pointed at the screen whose rectangle is desired.
Returns
Screen rectangle, in pixels.
Implemented in MeaScreenMgr.
Referenced by MeaRulerTool::Enable(), MeaLinearUnits::FindResFromCoord(), MeaLinearUnits::FindResFromPos(), MeaRulerTool::LoadProfile(), MeaPositionScreen::MeaPositionScreen(), MeaCalibrationPrefs::OnCaliperChange(), MeaCalibrationPrefs::OnHFieldChange(), MeaCalibrationPrefs::OnRxFieldChange(), MeaCalibrationPrefs::OnRyFieldChange(), MeaCalibrationPrefs::OnWFieldChange(), MeaScreenTool::SetPosition(), MeaDataWin::Update(), MeaCalibrationPrefs::UpdateView(), and MeaCalibrationPrefs::Validate().
GetScreenRes() [1/2]
virtual const MeaFSize & MeaScreenProvider::GetScreenRes (const ScreenIter & iter) const pure virtual
Returns the resolution for the screen pointed to by the specified iterator.
Parameters
iter [in] Screen iterator pointed at the screen whose resolution is desired.
Returns
Screen resolution, in pixels per inch. If the resolution has been set manually, it is returned. Otherwise, the operating system reported resolution is returned.
Implemented in MeaScreenMgr.
GetScreenRes() [2/2]
virtual void MeaScreenProvider::GetScreenRes (const ScreenIter & iter, bool & useManualRes, MeaFSize & manualRes) const pure virtual
Returns the manually set screen resolution for the screen pointed to by the specified iterator.
Parameters
iter [in] Screen iterator pointed at the screen whose manual resolution is desired.
useManualRes [out] true if the resolution was set manually.
manualRes [out] Manually set resolution, in pixels per inch.
Implemented in MeaScreenMgr.
Referenced by MeaLinearUnits::ConvertCoord(), MeaLinearUnits::ConvertPos(), MeaRuler::Create(), MeaCrossHair::Create(), MeaLayout::DrawOpacityBackground(), MeaLinearUnits::FindResFromCoord(), MeaLinearUnits::FindResFromPos(), MeaPositionScreen::MeaPositionScreen(), MeaScreenTool::SetPosition(), MeaLinearUnits::UnconvertCoord(), MeaOriginTool::Update(), and MeaCalibrationPrefs::Validate().
GetVirtualRect()
virtual const CRect & MeaScreenProvider::GetVirtualRect () const pure virtual
Returns the virtual screen rectangle.
The virtual rectangle is the rectangle containing all display screens attached to the system.
Returns
Rectangle encompassing all display screens attached to the system, in pixels.
Implemented in MeaScreenMgr.
Referenced by MeaDataWin::CalcWidth(), MeaLinearUnits::ConvertCoord(), MeaCircle::Create(), MeaLine::Create(), MeaRuler::DrawRuler(), MeaScreenMgr::GetOffScreen(), MeaPositionDesktop::MeaPositionDesktop(), MeaGridTool::SetLines(), MeaGridTool::ShowLines(), MeaLinearUnits::UnconvertCoord(), and MeaOriginTool::Update().
IsManualRes()
virtual bool MeaScreenProvider::IsManualRes (const ScreenIter & iter) const pure virtual
Indicates it the resolution for the specified screen has been set manually.
Parameters
iter [in] Screen iterator pointed at the screen whose resolution setting is being queried.
Returns
true if the screen's resolution was set manually.
Implemented in MeaScreenMgr.
Referenced by MeaPositionScreen::MeaPositionScreen().
IsPrimary()
virtual bool MeaScreenProvider::IsPrimary (const ScreenIter & iter) const pure virtual
Indicates if the screen pointed to by the specified iterator is the primary.
Returns
true if the specified screen is the primary.
Implemented in MeaScreenMgr.
Referenced by MeaPositionScreen::MeaPositionScreen().
LimitPosition()
virtual CPoint MeaScreenProvider::LimitPosition (const CPoint & pt) const pure virtual
Ensures that the specified point is on a screen.
Parameters
pt [in] Point to check.
Returns
New point based on the specified point that is guaranteed to be on a screen.
Implemented in MeaScreenMgr.
Referenced by MeaRuler::FillInfo(), MeaCrossHair::FindCenter(), MeaAngleTool::OnCHMove(), MeaCircleTool::OnCHMove(), MeaLineTool::OnCHMove(), MeaRectTool::OnCHMove(), MeaPointTool::SetPosition(), MeaAngleTool::SetPosition(), MeaCircleTool::SetPosition(), MeaLineTool::SetPosition(), and MeaRectTool::SetPosition().
The documentation for this struct was generated from the following file:
ScreenProvider.h
Copyright 2011 C Thing Software