Meazure: MeaPositionLogWriter Struct Reference
MeaPositionLogWriter Struct Reference abstract
Interface for classes that provide the ability to write to the position log file.
#include <PositionLogWriter.h>
Public Member Functions
virtual void Write (int indentLevel, LPCTSTR format,...)=0
Printf-like method for writing to a position log file.
Detailed Description
Interface for classes that provide the ability to write to the position log file.
Member Function Documentation
Write()
virtual void MeaPositionLogWriter::Write (int indentLevel, LPCTSTR format, ...) pure virtual
Printf-like method for writing to a position log file.
Parameters
indentLevel [in] Output indentation level.
format [in] Printf-style format string.
... [in] Items to write to the file.
Exceptions
CFileException if there was a problem writing the information
Implemented in MeaPositionLogMgr.
Referenced by MeaPosition::Save(), MeaPositionDesktop::Save(), MeaPositionScreen::Save(), and MeaPositionDesktop::SaveCustomPrecisions().
The documentation for this struct was generated from the following file:
PositionLogWriter.h
Copyright 2011 C Thing Software