Meazure: MeaPositionProvider Struct Reference
MeaPositionProvider Struct Reference abstract
Interface for providing position information.
#include <PositionProvider.h>
Public Types
typedef std::list< std::reference_wrapper< const MeaPositionDesktop > > PositionDesktops
Public Member Functions
virtual const CString & GetTitle () const =0
Returns the title for the position log.
virtual const CString & GetDescription () const =0
Returns the description for the position log.
virtual PCTSTR GetCurrentDtdUrl () const =0
Returns the URL for the current position log file DTD.
virtual PositionDesktops GetReferencedDesktops () const =0
Returns a list of desktop information objects that are currently referenced by recorded positions.
virtual const MeaPositionCollection & GetPositions () const =0
Returns the recorded positions.
Detailed Description
Interface for providing position information.
Member Function Documentation
GetCurrentDtdUrl()
virtual PCTSTR MeaPositionProvider::GetCurrentDtdUrl () const pure virtual
Returns the URL for the current position log file DTD.
Returns
Position log DTD URL.
Implemented in MeaPositionLogMgr.
Referenced by MeaPositionLogWriter::Save().
GetDescription()
virtual const CString & MeaPositionProvider::GetDescription () const pure virtual
Returns the description for the position log.
Returns
Description for the position log.
Implemented in MeaPositionLogMgr.
Referenced by MeaPositionLogWriter::WriteInfoSection().
GetPositions()
virtual const MeaPositionCollection & MeaPositionProvider::GetPositions () const pure virtual
Returns the recorded positions.
Returns
Recorded positions.
Implemented in MeaPositionLogMgr.
Referenced by MeaPositionLogWriter::WritePositionsSection().
GetReferencedDesktops()
virtual PositionDesktops MeaPositionProvider::GetReferencedDesktops () const pure virtual
Returns a list of desktop information objects that are currently referenced by recorded positions.
Returns
List of desktop information objects.
Implemented in MeaPositionLogMgr.
Referenced by MeaPositionLogWriter::WriteDesktopsSection().
GetTitle()
virtual const CString & MeaPositionProvider::GetTitle () const pure virtual
Returns the title for the position log.
Returns
Title for the position log.
Implemented in MeaPositionLogMgr.
Referenced by MeaPositionLogWriter::WriteInfoSection().
The documentation for this struct was generated from the following file:
PositionProvider.h
Copyright 2011 C Thing Software