Meazure: TimeStamp.h File Reference
TimeStamp.h File Reference
Produces an ISO 8601 compliant time stamp.
#include <time.h>
Functions
CString MeaMakeTimeStamp (time_t t)
Creates an ISO 8601 compliant time stamp based on the specified time value.
time_t MeaParseTimeStamp (const CString &timeStr)
Parses an ISO 8601 compliant time stamp and returns the corresponding time value.
Detailed Description
Produces an ISO 8601 compliant time stamp.
Function Documentation
MeaMakeTimeStamp()
CString MeaMakeTimeStamp (time_t t)
Creates an ISO 8601 compliant time stamp based on the specified time value.
The format of the timestamp is:
yyyy-mm-ddThh:mm:ssZ
Parameters
t [in] Number of seconds since the Epoch as defined by the system time() function.
Returns
String containing the timestamp in 8601 format corresponding to the specified time.
Referenced by MeaFileProfile::WriteFileStart(), and MeaPositionLogMgr::WriteInfoSection().
MeaParseTimeStamp()
time_t MeaParseTimeStamp (const CString & timeStr)
Parses an ISO 8601 compliant time stamp and returns the corresponding time value.
The format of the timestamp must be:
yyy-mm-ddThh:mm:ssZ
Parameters
timeStr [in] Time stamp string to parse.
Returns
Number of seconds since the Epoch as defined by the system time() function.
Referenced by MeaPositionLogDlg::UpdatePositionInfo().
Copyright 2011 C Thing Software