Meazure: Utils.h File Reference
Utils.h File Reference
Miscellaneous utility methods.
#include <math.h>
#include <float.h>
Classes
struct FSIZE
Represents a rectangular size.
struct FRECT
Represents a rectangular.
struct FPOINT
Represents a point.
class MeaUtils
Defines
#define MEA_DBL_EQL(x, y) (fabs((x) - (y)) < DBL_EPSILON)
Tests whether the two specified double precision values are equal.
Functions
FSIZE log10 (const FSIZE &fsize)
Calculates the log base 10 on each dimension of the specified size object and returns the results in a new size object.
FSIZE floor (const FSIZE &fsize)
Calculates the floor on each dimension of the specified size object and returns the results in a new size object.
FSIZE operator- (double val, const FSIZE &fsize)
Subtracts the specified size object from the specified value and returns a new size object.
Detailed Description
Miscellaneous utility methods.
Define Documentation
#define MEA_DBL_EQL (x, y) (fabs((x) - (y)) < DBL_EPSILON)
Tests whether the two specified double precision values are equal.
The resolution of the double is used to make the determination of equality.
Referenced by MeaCalibrationPrefs::GetFieldValue(), MeaPositionLogMgr::Screen::IsEqual(), MeaPositionLogMgr::DesktopInfo::IsEqual(), MeaColors::RGBtoHSL(), and MeaScreenTool::SetPosition().
Function Documentation
FSIZE floor (const FSIZE & fsize) [inline]
Calculates the floor on each dimension of the specified size object and returns the results in a new size object.
Parameters:
fsize [in] Size object whose floor is to be obtained.
Returns:
A new size object whose dimensions are the floor of the specified size object's dimensions.
References FSIZE::cx, and FSIZE::cy.
Referenced by MeaLinearUnits::GetMinorIncr().
FSIZE log10 (const FSIZE & fsize) [inline]
Calculates the log base 10 on each dimension of the specified size object and returns the results in a new size object.
Parameters:
fsize [in] Size object whose logarithm is to be obtained.
Returns:
A new size object whose dimensions are the base 10 log of the specified size object's dimensions.
References FSIZE::cx, and FSIZE::cy.
Referenced by MeaLinearUnits::GetMinorIncr(), and MeaPrecisionPrefs::OnInitDialog().
FSIZE operator- (double val, const FSIZE & fsize) [inline]
Subtracts the specified size object from the specified value and returns a new size object.
Parameters:
val [in] The specified size object is subtracted from this value.
fsize [in] Size object to subtract from the specified value.
Returns:
New size object formed by the specified size object being subtracted from the specified value.
References FSIZE::cx, and FSIZE::cy.
Copyright 2011 C Thing Software