#
# Copyright 2001 C Thing Software
#
# This file is part of Meazure.
# 
# Meazure is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# Meazure is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with Meazure.  If not, see <http://www.gnu.org/licenses/>.
#

import sys, os.path, re


# Context sensitive help support (see Technical note TN028 for more details)
# The constants are Help ID bases and have been taken from the private MFC
# header file afxpriv.h.
#
HID_BASE = {
    'ID':  0x00010000,
    'IDM': 0x00010000,
    'IDR': 0x00020000,
    'IDD': 0x00020000,
    'IDP': 0x00030000,
    'IDW': 0x00040000,
    'IDC': 0x00050000
    }


def usage():
    """Display program usage message.
    """

    print("Usage: %s resource.h hid.h" %
          os.path.splitext(os.path.basename(sys.argv[0]))[0])

# End def usage


def main():
    """Program entry point.
    """

    if len(sys.argv) < 3:
        usage()
        return 1

    resRE = re.compile(r'^\#define\s+(ID[MDRPWC]?)(_\w+)\s+(\d+)')

    resourcePathname = os.path.abspath(sys.argv[1])
    helpPathname = os.path.abspath(sys.argv[2])

    resourceFile = open(resourcePathname, "r")
    helpFile = open(helpPathname, "w")

    helpFile.write("// Generated by %s from %s - DO NOT EDIT\n//\n" % \
                   (os.path.basename(sys.argv[0]),
                    os.path.basename(resourcePathname)))

    for line in resourceFile:
        m = resRE.match(line)
        if m:
            idBase = m.group(1)
            idName = m.group(1) + m.group(2)
            idValue = int(m.group(3))
            if idBase in HID_BASE:
                idValue += HID_BASE[idBase]
                helpFile.write("#define H%s\t\t %d\n" % (idName, idValue))
    
    helpFile.close()
    resourceFile.close()
    
    return 0

# End def main


if __name__ == '__main__':
    sys.exit(main())
